gAbilityDescription_None: @ 81F99CC
	.string "특성 없음$"

gAbilityDescription_Stench: @ 81F99E0
	.string "포켓몬이 접근하기 어려워진다$"

gAbilityDescription_Drizzle: @ 81F99FA
	.string "배틀에 나오면 비를 내리게 한다$"

gAbilityDescription_SpeedBoost: @ 81F9A12
	.string "점점 스피드가 올라간다$"

gAbilityDescription_BattleArmor: @ 81F9A2A
	.string "기술을 급소에 맞지 않게 한다$"

gAbilityDescription_Sturdy: @ 81F9A40
	.string "일격필살이 통하지 않는다$"

gAbilityDescription_Damp: @ 81F9A5A
	.string "누구도 자폭할 수 없게 된다$"

gAbilityDescription_Limber: @ 81F9A75
	.string "마비 상태가 되지 않는다$"

gAbilityDescription_SandVeil: @ 81F9A89
	.string "모래바람으로 회피율이 올라간다$"

gAbilityDescription_Static: @ 81F9AA5
	.string "접촉한 상대를 마비시킨다$"

gAbilityDescription_VoltAbsorb: @ 81F9ABB
	.string "전기를 받으면 회복한다$"

gAbilityDescription_WaterAbsorb: @ 81F9AD6
	.string "물을 받으면 회복한다$"

gAbilityDescription_Oblivious: @ 81F9AED
	.string "헤롱헤롱 상태가 되지 않는다$"

gAbilityDescription_CloudNine: @ 81F9B02
	.string "날씨의 영향이 없어진다$"

gAbilityDescription_CompoundEyes: @ 81F9B1B
	.string "기술의 명중률이 올라간다$"

gAbilityDescription_Insomnia: @ 81F9B2C
	.string "잠듦 상태가 되지 않는다$"

gAbilityDescription_ColorChange: @ 81F9B3C
	.string "받은 기술의 타입으로 변화한다$"

gAbilityDescription_Immunity: @ 81F9B58
	.string "독 상태가 되지 않는다$"

gAbilityDescription_FlashFire: @ 81F9B6C
	.string "불꽃을 받으면 강해진다$"

gAbilityDescription_ShieldDust: @ 81F9B86
	.string "기술의 추가 효과를 받지 않는다$"

gAbilityDescription_OwnTempo: @ 81F9B9E
	.string "혼란 상태가 되지 않는다$"

gAbilityDescription_SuctionCups: @ 81F9BB2
	.string "몸을 단단히 고정시킨다$"

gAbilityDescription_Intimidate: @ 81F9BCB
	.string "상대의 공격을 떨어뜨린다$"

gAbilityDescription_ShadowTag: @ 81F9BE4
	.string "상대를 도망칠 수 없게 한다$"

gAbilityDescription_RoughSkin: @ 81F9BFF
	.string "접촉한 상대에게 상처를 입힌다$"

gAbilityDescription_WonderGuard: @ 81F9C0F
	.string "효과가 굉장한 기술밖에 맞지 않는다$"

gAbilityDescription_Levitate: @ 81F9C27
	.string "땅타입의 기술을 받지 않는다$"

gAbilityDescription_EffectSpore: @ 81F9C42
	.string "접촉한 상대에게 포자가 붙는다$"

gAbilityDescription_Synchronize: @ 81F9C5C
	.string "독, 마비, 화상을 상대에게 옮긴다$"

gAbilityDescription_ClearBody: @ 81F9C77
	.string "상대가 능력을 떨어뜨릴 수 없다$"

gAbilityDescription_NaturalCure: @ 81F9C93
	.string "교체하면 상태 이상이 치료된다$"

gAbilityDescription_LightningRod: @ 81F9CAD
	.string "전기타입 기술이 자신에게 맞는다$"

gAbilityDescription_SereneGrace: @ 81F9CC5
	.string "기술의 추가 효과가 나오기 쉽다$"

gAbilityDescription_SwiftSwim: @ 81F9CDD
	.string "비가 올 때 스피드가 오른다$"

gAbilityDescription_Chlorophyll: @ 81F9CF3
	.string "맑을 때 스피드가 오른다$"

gAbilityDescription_Illuminate: @ 81F9D0D
	.string "포켓몬과 만나기 쉬워진다$"

gAbilityDescription_Trace: @ 81F9D27
	.string "상대와 같은 특성이 된다$"

gAbilityDescription_HugePower: @ 81F9D3F
	.string "공격이 오른다$"

gAbilityDescription_PoisonPoint: @ 81F9D4E
	.string "접촉한 상대를 독 상태로 만든다$"

gAbilityDescription_InnerFocus: @ 81F9D66
	.string "풀죽지 않는다$"

gAbilityDescription_MagmaArmor: @ 81F9D7A
	.string "얼음 상태가 되지 않는다$"

gAbilityDescription_WaterVeil: @ 81F9D8D
	.string "화상 상태가 되지 않는다$"

gAbilityDescription_MagnetPull: @ 81F9D9D
	.string "강철타입이 도망칠 수 없게 된다$"

gAbilityDescription_Soundproof: @ 81F9DB7
	.string "소리 기술을 받지 않는다$"

gAbilityDescription_RainDish: @ 81F9DD1
	.string "비가 오면 조금씩 회복한다$"

gAbilityDescription_SandStream: @ 81F9DED
	.string "배틀에 나오면 모래바람을 일으킨다$"

gAbilityDescription_Pressure: @ 81F9E02
	.string "상대의 PP를 많이 줄인다$"

gAbilityDescription_ThickFat: @ 81F9E19
	.string "불꽃과 얼음타입의 기술에 강하다$"

gAbilityDescription_EarlyBird: @ 81F9E33
	.string "잠듦 상태에서 빨리 깨어난다$"

gAbilityDescription_FlameBody: @ 81F9E4F
	.string "접촉한 상대에게 화상을 입힌다$"

gAbilityDescription_RunAway: @ 81F9E69
	.string "배틀에서 도망치기 쉽다$"

gAbilityDescription_KeenEye: @ 81F9E80
	.string "명중률이 떨어지지 않는다$"

gAbilityDescription_HyperCutter: @ 81F9E9B
	.string "상대가 공격을 떨어뜨리지 못한다$"

gAbilityDescription_Pickup: @ 81F9EB6
	.string "도구를 주워올 때가 있다$"

gAbilityDescription_Truant: @ 81F9EC9
	.string "연속으로 공격할 수 없다$"

gAbilityDescription_Hustle: @ 81F9EE5
	.string "공격이 높지만 빗나가기 쉽다$"

gAbilityDescription_CuteCharm: @ 81F9F00
	.string "스치면 헤롱헤롱 상태가 된다$"

gAbilityDescription_Plus: @ 81F9F17
	.string "마이너스가 있으면 강해진다$"

gAbilityDescription_Minus: @ 81F9F2D
	.string "플러스가 있으면 강해진다$"

gAbilityDescription_Forecast: @ 81F9F42
	.string "날씨에 따라 캐스퐁이 변화한다$"

gAbilityDescription_StickyHold: @ 81F9F5C
	.string "달라붙어서 도구를 지킨다$"

gAbilityDescription_ShedSkin: @ 81F9F71
	.string "탈피하면서 상태 이상을 회복한다$"

gAbilityDescription_Guts: @ 81F9F8D
	.string "상태 이상이 되면 공격이 올라간다$"

gAbilityDescription_MarvelScale: @ 81F9FA6
	.string "상태 이상이 되면 방어가 올라간다$"

gAbilityDescription_LiquidOoze: @ 81F9FC0
	.string "흡수한 상대의 체력을 감소시킨다$"

gAbilityDescription_Overgrow: @ 81F9FD8
	.string "위급할 때 풀의 위력이 올라간다$"

gAbilityDescription_Blaze: @ 81F9FF4
	.string "위급할 때 불꽃의 위력이 올라간다$"

gAbilityDescription_Torrent: @ 81FA00F
	.string "위급할 때 물의 위력이 올라간다$"

gAbilityDescription_Swarm: @ 81FA02B
	.string "위급할 때 벌레의 위력이 올라간다$"

gAbilityDescription_RockHead: @ 81FA045
	.string "부딪쳐도 반동을 받지 않는다$"

gAbilityDescription_Drought: @ 81FA05D
	.string "배틀에 나가면 햇살이 강해진다$"

gAbilityDescription_ArenaTrap: @ 81FA079
	.string "상대를 도망칠 수 없게 한다$"

gAbilityDescription_VitalSpirit: @ 81FA08B
	.string "잠듦 상태가 되지 않는다$"

gAbilityDescription_WhiteSmoke: @ 81FA09B
	.string "상대가 능력을 떨어뜨릴 수 없다$"

gAbilityDescription_PurePower: @ 81FA0B7
	.string "공격의 위력이 올라간다$"

gAbilityDescription_ShellArmor: @ 81FA0C6
	.string "기술을 급소에 맞지 않게 한다$"

gAbilityDescription_Cacophony: @ 81FA0DC
	.string "소리 기술을 맞지 않는다$"

gAbilityDescription_AirLock: @ 81FA0F6
	.string "날씨의 영향이 없어진다$"

	.align 2
gAbilityDescriptions:: @ 81FA110
	.4byte gAbilityDescription_None
	.4byte gAbilityDescription_Stench
	.4byte gAbilityDescription_Drizzle
	.4byte gAbilityDescription_SpeedBoost
	.4byte gAbilityDescription_BattleArmor
	.4byte gAbilityDescription_Sturdy
	.4byte gAbilityDescription_Damp
	.4byte gAbilityDescription_Limber
	.4byte gAbilityDescription_SandVeil
	.4byte gAbilityDescription_Static
	.4byte gAbilityDescription_VoltAbsorb
	.4byte gAbilityDescription_WaterAbsorb
	.4byte gAbilityDescription_Oblivious
	.4byte gAbilityDescription_CloudNine
	.4byte gAbilityDescription_CompoundEyes
	.4byte gAbilityDescription_Insomnia
	.4byte gAbilityDescription_ColorChange
	.4byte gAbilityDescription_Immunity
	.4byte gAbilityDescription_FlashFire
	.4byte gAbilityDescription_ShieldDust
	.4byte gAbilityDescription_OwnTempo
	.4byte gAbilityDescription_SuctionCups
	.4byte gAbilityDescription_Intimidate
	.4byte gAbilityDescription_ShadowTag
	.4byte gAbilityDescription_RoughSkin
	.4byte gAbilityDescription_WonderGuard
	.4byte gAbilityDescription_Levitate
	.4byte gAbilityDescription_EffectSpore
	.4byte gAbilityDescription_Synchronize
	.4byte gAbilityDescription_ClearBody
	.4byte gAbilityDescription_NaturalCure
	.4byte gAbilityDescription_LightningRod
	.4byte gAbilityDescription_SereneGrace
	.4byte gAbilityDescription_SwiftSwim
	.4byte gAbilityDescription_Chlorophyll
	.4byte gAbilityDescription_Illuminate
	.4byte gAbilityDescription_Trace
	.4byte gAbilityDescription_HugePower
	.4byte gAbilityDescription_PoisonPoint
	.4byte gAbilityDescription_InnerFocus
	.4byte gAbilityDescription_MagmaArmor
	.4byte gAbilityDescription_WaterVeil
	.4byte gAbilityDescription_MagnetPull
	.4byte gAbilityDescription_Soundproof
	.4byte gAbilityDescription_RainDish
	.4byte gAbilityDescription_SandStream
	.4byte gAbilityDescription_Pressure
	.4byte gAbilityDescription_ThickFat
	.4byte gAbilityDescription_EarlyBird
	.4byte gAbilityDescription_FlameBody
	.4byte gAbilityDescription_RunAway
	.4byte gAbilityDescription_KeenEye
	.4byte gAbilityDescription_HyperCutter
	.4byte gAbilityDescription_Pickup
	.4byte gAbilityDescription_Truant
	.4byte gAbilityDescription_Hustle
	.4byte gAbilityDescription_CuteCharm
	.4byte gAbilityDescription_Plus
	.4byte gAbilityDescription_Minus
	.4byte gAbilityDescription_Forecast
	.4byte gAbilityDescription_StickyHold
	.4byte gAbilityDescription_ShedSkin
	.4byte gAbilityDescription_Guts
	.4byte gAbilityDescription_MarvelScale
	.4byte gAbilityDescription_LiquidOoze
	.4byte gAbilityDescription_Overgrow
	.4byte gAbilityDescription_Blaze
	.4byte gAbilityDescription_Torrent
	.4byte gAbilityDescription_Swarm
	.4byte gAbilityDescription_RockHead
	.4byte gAbilityDescription_Drought
	.4byte gAbilityDescription_ArenaTrap
	.4byte gAbilityDescription_VitalSpirit
	.4byte gAbilityDescription_WhiteSmoke
	.4byte gAbilityDescription_PurePower
	.4byte gAbilityDescription_ShellArmor
	.4byte gAbilityDescription_Cacophony
	.4byte gAbilityDescription_AirLock
