UnknownString_81B41B8: @ 81B41B8 //JP: 18CF39
	.string "아강: ...거기 멈춰라!$"

UnknownString_81B41D5: @ 81B41D5
	.string "아강: 후후후...\n"
	.string "역시 너였던 건가$"

UnknownString_81B4201: @ 81B4201
	.string "아강: 어떠냐 봐라!\p"
	.string "초 고대포켓몬 가이오가가\n"
	.string "조용히 잠들어 있는\l"
	.string "이 아름다운 모습을!\p"
	.string "난 이 날이 오기만을\n"
	.string "오랫동안 기다려왔다...$"

UnknownString_81B4289: @ 81B4289
	.string "아강: 그건 그렇고 설마 네가\n"
	.string "여기까지 왔을 줄이야!\p"
	.string "하지만 그것도 끝이다\n"
	.string "내 목적 달성을 위해\l"
	.string "너는 여기서 사라져 줘야겠다!$"

UnknownString_81B4319: @ 81B4319
	.string "이 내가...\n"
	.string "또다시 질 줄이야...$"

UnknownString_81B432C: @ 81B432C
	.string "아강: 후후후...\p"
	.string "역시나라고 해야 하나...\n"
	.string "너의 그 힘은 인정하마!\p"
	.string "허나...!\n"
	.string "내게는 이것이 있다!\p"
	.string "이 주홍구슬이 있으면\n"
	.string "가이오가를...$"

UnknownString_81B43C4: @ 81B43C4
	.string "주홍구슬이...\n"
	.string "멋대로 빛나기 시작했다...?!$"

UnknownString_81B43F2: @ 81B43F2
	.string "아강: ..?!\p"
	.string "나는 아무것도 하지 않았는데\n"
	.string "어째서 주홍구슬이...?\p"
	.string "가이오가는 어디로 사라졌지?$"

UnknownString_81B4443: @ 81B4443
	.string "아강: 밖에 있는\n"
	.string "단원한테로군$"

UnknownString_81B447A: @ 81B447A
	.string "아강: 뭔가...?\p"
	.string "흠...\n"
	.string "폭우가 내리고 있다고...\p"
	.string "그렇겠지... 그것이야말로\n"
	.string "우리들 아쿠아단의 목적\l"
	.string "바다를 넓히기 위해 가이오가를\l"
	.string "깨운 이유니까 말이다\p"
	.string "뭐라고!\p"
	.string "예상한 것 이상의 폭우로 이대로라면\n"
	.string "우리들도 위험하다고?!\p"
	.string "설마 그럴 리가...\n"
	.string "그럴 리가 없을 텐데...\p"
	.string "어쨌든 계속 상태를 보고 있어라!$"

UnknownString_81B45C6: @ 81B45C6
	.string "아강: 이상해...\p"
	.string "주홍구슬로 가이오가가 눈을 뜨고\n"
	.string "그리고 컨트롤할 수 있었을 텐데...\p"
	.string "그런데... 어째서...\n"
	.string "가이오가는 여기서 없어졌다?!\p"
	.string "어째서지?!$"

UnknownString_81B464D: @ 81B464D
	.string "마적: 무슨 일이란 말인가...\p"
	.string "아강... 너는 결국\n"
	.string "가이오가를 눈 뜨게 해버린 건가!\p"
	.string "이대로 영원히\n"
	.string "폭우가 쏟아져 내린다면\l"
	.string "세계는 대체 어떻게 되겠는가!\p"
	.string "모든 대지가\n"
	.string "물 깊숙히 가라앉게 되는 거다...$"

UnknownString_81B4723: @ 81B4723
	.string "아강: 뭐라고...?\p"
	.string "주홍구슬이 있으면 가이오가를\n"
	.string "컨트롤할 수 있을 텐데...\l"
	.string "그럴 리가...$"

UnknownString_81B4786: @ 81B4786
	.string "마적: 어쨌든 지금은 여기서\n"
	.string "말다툼하고 있을 때가 아니다!\p"
	.string "밖으로 나가서 확인하도록 해라!\n"
	.string "눈앞에 펼쳐진 게\l"
	.string "네가 원하던 세계인지 아닌지를$"

UnknownString_81B4818: @ 81B4818
	.string "마적: {PLAYER}도\n"
	.string "서둘러 밖으로 나가거라!$"
