MtChimney_Text_1B2DEE:: @ 81B2DEE
	.string "운석에 숨겨진 힘...\p"
	.string "이 장치로 증폭된다면\n"
	.string "눈 깜짝할 사이에 굴뚝산의\l"
	.string "화산 활동은 멈춘다...\p"
	.string "후후후... 언젠가\n"
	.string "식은 화산의 분화구에 빗물이 고여\l"
	.string "물포켓몬이 살아갈 수 있겠지$"

MtChimney_Text_1B2ED9:: @ 81B2ED9
	.string "아강: 또 네 녀석인가...\p"
	.string "... 알겠나 모든\n"
	.string "생명은 바다로부터 태어났다!\p"
	.string "그래 바다야말로 전부!\p"
	.string "그래서 우리 아쿠아단은\n"
	.string "바다를 넓혀서\l"
	.string "새로운 포켓몬을 탄생시킨다!\p"
	.string "포켓몬을 위해서\n"
	.string "자연을 되돌린다!\p"
	.string "이것이야말로 아쿠아단의 이상!\n"
	.string "아무것도 모르는 너같은 꼬마에게\l"
	.string "방해받을 수는 없다\p"
	.string "방해한다면 어떻게 되는지\n"
	.string "이 아강이 똑똑히 보여주마!$"

MtChimney_Text_1B3099:: @ 81B3099
	.string "뭣이!?\p"
	.string "이 아강이\n"
	.string "방심한 건가!?$"

MtChimney_Text_1B30C2:: @ 81B30C2
	.string "아강: 뭐 좋다\n"
	.string "이 굴뚝산은 일단\l"
	.string "포기하도록 하지...\p"
	.string "하지만 우리 아쿠아단의 활동은\n"
	.string "아무도 멈출 수 없다!\p"
	.string "그것만은 잊지 마라!$"

MtChimney_Text_1B3168:: @ 81B3168
	.string "우효효!\p"
	.string "너 여기까지 온 건가!\p"
	.string "하지만 늦었다고\n"
	.string "유성의 폭포에서 찾은\l"
	.string "운석은 리더에게 넘겼으니까 말이야!$"

MtChimney_Text_1B31EA:: @ 81B31EA
	.string "우효효...\n"
	.string "져버렸나...\p"
	.string "그 때 유성의 폭포에서\n"
	.string "싸우지 않아서 다행이군$"

MtChimney_Text_1B3239:: @ 81B3239
	.string "우효효...!\p"
	.string "나를 이겨도\n"
	.string "리더는 이길 수 없을 걸!\p"
	.string "빨리 돌아가는 편이\n"
	.string "아픈 기억이 남지 않을 거다$"

MtChimney_Text_1B32C8:: @ 81B32C8
	.string "우리 아쿠아단은\n"
	.string "모두를 위해 노력하고 있는 거다!\p"
	.string "물이 늘어나면\n"
	.string "물포켓몬들도 좋아할 거고\l"
	.string "사람들도 마음껏\l"
	.string "헤엄칠 수 있으니 좋잖아!$"

MtChimney_Text_1B336E:: @ 81B336E
	.string "어라-?\n"
	.string "나 진 건가-?$"

MtChimney_Text_1B338D:: @ 81B338D
	.string "우리들의 리더가\n"
	.string "“모두를 위한 일”이라고\l"
	.string "했단 말이다!\p"
	.string "근데 왜 다들 방해하는 거지?$"

MtChimney_Text_1B33EA:: @ 81B33EA
	.string "마그마단 녀석들...\n"
	.string "일일이 우리 방해나 해대고 말야!$"

MtChimney_Text_1B3427:: @ 81B3427
	.string "운석에는 엄청난 파워가 있어!$"

MtChimney_Text_1B3446:: @ 81B3446
	.string "가라! 마그마단을 부숴 버려라!\n"
	.string "어쨌든 바다를 늘리는 것이다!$"

MtChimney_Text_1B3470:: @ 81B3470
	.string "우리 방해하지 마라! 알겠어?\p"
	.string "우린 모두를 위해서\n"
	.string "바다를 늘리려고 하는 거니까!$"

MtChimney_Text_1B34C6:: @ 81B34C6
	.string "좋-아!\n"
	.string "물을 퍼부어 줘라!!$"

MtChimney_Text_1B34DC:: @ 81B34DC
	.string "좀 더 좀 더 바다를 넓히자고!$"

MtChimney_Text_1B3503:: @ 81B3503
	.string "후샤-!!$"

MtChimney_Text_1B350B:: @ 81B350B
	.string "마적: 오오! {PLAYER}!\e"
	.string "마침 잘 와 주었다!\p"
	.string "나를 대신해서\n"
	.string "아쿠아단을 멈추어다오!\p"
	.string "저 녀석들 빼앗은 운석의 파워로\n"
	.string "이 화산의 움직임을\l"
	.string "멈출 생각이다!$"

MtChimney_Text_1B3598:: @ 81B3598
	.string "마적: {PLAYER}!\p"
	.string "나를 대신해서\n"
	.string "아쿠아단을 멈추어다오!\p"
	.string "이 녀석들 조무래기 3명의 상대는\n"
	.string "역시 나라도 큰일이다!$"

MtChimney_Text_1B3608:: @ 81B3608
	.string "마적: {PLAYER}! 고맙다\n"
	.string "네 덕분에 아쿠아단의\l"
	.string "파괴활동을 막을 수 있었다\p"
	.string "하지만... 아직 그 녀석들의 야망은\n"
	.string "이걸로 끝난 것이 아니다!\p"
	.string "우리는 계속해서 아쿠아단을\n"
	.string "쫓아가도록 하겠다!\p"
	.string "{PLAYER} 다음에 보도록 하지!$"

MtChimney_Text_1B36F1:: @ 81B36F1
	.string "젠장 아쿠아단이 너무 많아...\n"
	.string "이대로라면 위험해!$"

MtChimney_Text_1B372E:: @ 81B372E
	.string "바다를 넓혀버리면\n"
	.string "포켓몬과 사람이 살 수 있는 장소가\l"
	.string "그만큼 줄어들잖아!$"

MtChimney_Text_1B3778:: @ 81B3778
	.string "아쿠아단 녀석들\n"
	.string "바다를 넓히려고 하다니\l"
	.string "어이없는 녀석들!$"

MtChimney_Text_1B37B4:: @ 81B37B4
	.string "부와-!!$"
