UnknownString_81C426C: @ 81C426C //JP: 1961BC
	.string "나는 큰 {STR_VAR_1}에\n"
	.string "무척 흥미가 있어!\p"
	.string "응? 너 {STR_VAR_1} 가지고 있어?\n"
	.string "자, 자, 잠깐...\l"
	.string "아저씨한테 좀 보여줘!$"

UnknownString_81C42CE: @ 81C42CE
	.string "오오! 이 녀석 커!\n"
	.string "무척 아름다운 {STR_VAR_1}\e야!\p"
	.string "보여줘서 고마워\n"
	.string "보답으로 이걸 가지고 가렴!$"

UnknownString_81C432C: @ 81C432C
	.string "{PLAYER}\s\n"
	.string "{STR_VAR_2}\f 받았다!$"

UnknownString_81C4340: @ 81C4340
	.string "어라?\n"
	.string "너 지닌물건이 가득 찼네$"

UnknownString_81C4360: @ 81C4360
	.string "으음 난 이것보다 큰\n"
	.string "{STR_VAR_1}\f 본 적이 있어...$"

UnknownString_81C438C: @ 81C438C
	.string "오오 이 녀석 꽤...아니\n"
	.string "이거 {STR_VAR_1} 아니잖아!$"

UnknownString_81C43C2: @ 81C43C2
	.string "큰 {STR_VAR_1} 없어?\n"
	.string "그거 안타깝네...\p"
	.string "다음에 큰 {STR_VAR_1} 보여줘$"

UnknownString_81C4417: @ 81C4417
	.string "사상 최대의 {STR_VAR_1}!\n"
	.string "{STR_VAR_2}의 {STR_VAR_3}cm인 녀석!$"
