gTextBard_BardTesting: @ 81B0A83
	.string "싱어송아저씨는 테스트 중!$"

gTextBard_HiImTheBard:: @ 81B0A91
	.string "난 싱어송아저씨\n"
	.string "내 노래 한번 들어볼래?$"

gTextBard_OhYouveLeftMe:: @ 81B0AC3
	.string "그래...\n"
	.string "아쉽네...$"

gTextBard_OhWhatAMovingSong:: @ 81B0AED
	.string "아아 좋은 노래구나...\n"
	.string "다른 사람들에게도 들려주고 싶다$"

gTextBard_SoHowDoYouLikeMySong:: @ 81B0B2C
	.string "내 노래 어때?\p"
	.string "근데 좀 가사가\n"
	.string "마음에 안 든단 말이지\p"
	.string "그래서 너 잠깐 가사 좀 써줄래?$"

gTextBard_OhYouveLeftMe2:: @ 81B0BA6
	.string "그래...\n"
	.string "아쉽네...$"

gTextBard_ThankYouKindly:: @ 81B0BD0
	.string "고마워!\n"
	.string "자 그럼 부른다!$"

gTextBard_WasThatHowYouWanted:: @ 81B0BFA
	.string "이런 느낌이면 되나?$"

gTextBard_OkayThatsIt:: @ 81B0C23
	.string "좋아 알았어!\n"
	.string "당분간 이 노래를 불러 볼게!$"
