Route102_Text_1A16B6:: @ 81A16B6
	.string "푹신푹신한 흙이다$"

Route102_Text_1A16CD:: @ 81A16CD
	.string "푹신푹신한 흙이다\n"
	.string "나무열매를 심겠습니까?$"

Route102_Text_1A16FB:: @ 81A16FB
	.string "{PLAYER}{K_EUNNEUN} 푹신푹신한 흙에\n"
	.string "{STR_VAR_1}열매를 심었다!$"

Route102_Text_1A172C:: @ 81A172C
	.string "{STR_VAR_1}열매 하나를 심은 장소다!$"

Route102_Text_1A174B:: @ 81A174B
	.string "{STR_VAR_1}열매의 싹이 나왔다!$"

Route102_Text_1A175C:: @ 81A175C
	.string "{STR_VAR_1}열매의 줄기가\n"
	.string "커다랗게 자랐다!$"

Route102_Text_1A177D:: @ 81A177D
	.string "{STR_VAR_1}열매의 꽃들이\n"
	.string "{STR_VAR_2} 피어있다!$"

Route102_Text_1A179F:: @ 81A179F
	.string "매우 아름답게$"

Route102_Text_1A17B0:: @ 81A17B0
	.string "아기자기하게$"

Route102_Text_1A17B7:: @ 81A17B7
	.string "예쁘게$"

Route102_Text_1A17C0:: @ 81A17C0
	.string "{STR_VAR_1}열매가 {STR_VAR_2}개 열려있다!\n"
	.string "{STR_VAR_1}열매를 따겠습니까?$"

Route102_Text_1A17FD:: @ 81A17FD
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "{STR_VAR_1}열매를 {STR_VAR_2}개 땄다!$"

Route102_Text_1A181A:: @ 81A181A
	.string "{PLAYER}{K_EUNNEUN} {STR_VAR_1}열매를\n"
	.string "나무열매 포켓에 넣었다!\p"
	.string "푹신푹신한 흙으로 되돌아갔다$"

Route102_Text_1A1881:: @ 81A1881
	.string "가방의 나무열매 포켓이 가득 찼다\n"
	.string "{STR_VAR_1}열매를 포기했다$"

Route102_Text_1A18C5:: @ 81A18C5
	.string "{PLAYER}{K_EUNNEUN} {STR_VAR_1}열매를\n"
	.string "그대로 뒀다$"

Route102_Text_1A18E6:: @ 81A18E6
	.string "고래왕자물뿌리개로 {STR_VAR_1}열매에\n"
	.string "물을 주겠습니까?$"

Route102_Text_1A1912:: @ 81A1912
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "{STR_VAR_1}열매에 물을 주었다$"

Route102_Text_1A1925:: @ 81A1925
	.string "식물은\n"
	.string "매우 기뻐하는 듯하다!$"

Route102_Text_1A1946:: @ 81A1946
	.string "!$"
