gBirchSpeech_Welcome:: @ 81C6D78
	.string "이야- 오래 기다리게 했구나!\p"
	.string "포켓몬스터의 세계에\n"
	.string "잘 왔다!\p"
	.string "내 이름은 털보박사!\p"
	.string "그러나 모두에게는\n"
	.string "“포켓몬 박사”라고 불린단다!\p$"

gBirchSpeech_ThisIsPokemon:: @ 81C6DF8
	.string "포켓몬스터\n"
	.string "...즉 포켓몬$"

gBirchSpeech_WorldInhabitedByPokemon:: @ 81C6E1A
	.string "이 세계에는\n"
	.string "포켓몬이라 불리는 생명체가\l"
	.string "도처에 살고 있다!\p"
	.string "우리 인간은\n"
	.string "포켓몬과 사이좋게 놀기도 하고\l"
	.string "서로 도와 일을 하거나\p"
	.string "때로는 힘을 합쳐\n" 
	.string "싸우면서\l"
	.string "함께 살고 있지!\p"
	.string "...하지만 우리는 포켓몬에 대해\n"
	.string "모든 것을 알고 있지는 않다\p"
	.string "포켓몬의 비밀은\n"
	.string "아직도 많이 있어!\p"
	.string "나는 그 비밀을 풀기 위해\n"
	.string "연구를 계속하고 있다\l"
	.string "뭐 그런 말씀이지!\p$"

gBirchSpeech_AndYouAre:: @ 81C6FCB
	.string "그건 그렇고...$"

gBirchSpeech_AreYouBoyOrGirl:: @ 81C6FD8
	.string "자네는 남자인가?\n"
	.string "아니면 여자인가?$"

gBirchSpeech_WhatsYourName:: @ 81C6FFA
	.string "이름도 알려주면 좋겠구나!$"

gBirchSpeech_SoItsPlayer:: @ 81C7017
	.string "{PLAYER}{K_I}로구나?$"

gBirchSpeech_AhOkayYouArePlayer:: @ 81C7025
	.string "...아!\p"
	.string "자네가 이번에 내가 사는 마을인\n"
	.string "미로마을로 이사 온다는\l"
	.string "{PLAYER}{K_I}로구나!$"

gBirchSpeech_AreYouReady:: @ 81C7074
	.string "좋-아 준비는 되었는가?\p"
	.string "이제부터 자네만의 이야기가\n"
	.string "시작되려고 한다!\p"
	.string "꿈과 모험과 만남이 가득한\n"
	.string "포켓몬스터의 세계로\l"
	.string "용기를 가지고 뛰어들어 보려무나!\p"
	.string "그럼 다음에 또 만나자!\n"
	.string "연구소에서 기다리고 있겠다!\p$"
