OldaleTown_PokemonCenter_2F_Text_1A4510:: @ 81A4510
	.string "포켓몬 통신 클럽\n"
	.string "콜로세움에 잘 오셨습니다!\p"
	.string "여기에서는 친구와\n"
	.string "포켓몬 대전을 즐길 수 있습니다\p"
	.string "포켓몬 배틀을 하겠습니까?$"

OldaleTown_PokemonCenter_2F_Text_1A457E:: @ 81A457E
	.string "포켓몬 통신 클럽\n"
	.string "트레이드센터에 잘 오셨습니다!\p"
	.string "여기에서는 친구와\n"
	.string "포켓몬 교환을 할 수 있습니다\p"
	.string "포켓몬 교환을 하겠습니까?$"

OldaleTown_PokemonCenter_2F_Text_1A45FE:: @ 81A45FE
	.string "포켓몬 통신 클럽\n"
	.if REVISION >= 1
	.string "레코드코너에 잘 오셨습니다!\p"
	.else
	.string "레코드코너에 잘 오셨습니다!\p"
	.endif
	.string "여기에서는 친구와\n"
	.string "레코드 섞기를 할 수 있습니다\p"
	.string "레코드 섞기를 하겠습니까?$"

OldaleTown_PokemonCenter_2F_Text_1A4696:: @ 81A4696
	.string "대전에는 3종류의\n"
	.string "모드가 있습니다\p"
	.string "싱글배틀은 포켓몬을\n"
	.string "각각 1마리 이상 참가시켜\l"
	.string "두 명이서 1대1로 대전합니다\p"
	.string "더블배틀은 포켓몬을\n"
	.string "각각 2마리 이상 참가시켜\l"
	.string "두 명이서 2대2로 대전합니다\p"
	.string "멀티배틀은\n"
	.string "4명이서 포켓몬을\l"
	.string "각각 1마리 이상 참가시켜\l"
	.string "2대2로 대전합니다$"

OldaleTown_PokemonCenter_2F_Text_1A4826:: @ 81A4826
	.string "포켓몬 배틀을 하겠습니까?$"

OldaleTown_PokemonCenter_2F_Text_1A4840:: @ 81A4840
	.string "어느 대전을 하겠습니까?$"

OldaleTown_PokemonCenter_2F_Text_1A486A:: @ 81A486A
	.string "더블배틀에서는 2마리 이상의\n"
	.string "포켓몬이 필요합니다$"

OldaleTown_PokemonCenter_2F_Text_1A48A3:: @ 81A48A3
	.string "교환을 하기 위해서는\n"
	.string "포켓몬 2마리 필요합니다$"

OldaleTown_PokemonCenter_2F_Text_1A48DD:: @ 81A48DD
	.string "{STR_VAR_1}열매를 지닌 포켓몬은\n"
	.string "교환할 수 없습니다!$"

gUnknown_081A490C:: @ 81A490C
OldaleTown_PokemonCenter_2F_Text_1A490C:: @ 81A490C
	.string "잠시 기다려 주십시오\n"
	.string "...B 버튼으로 취소$"

gUnknown_081A4932:: @ 81A4932
UnknownString_81A4932: @ 81A4932
	.string "인원수가 모이면 A 버튼으로 진행한다\n"
	.string "...B 버튼으로 취소$"

gUnknown_081A4975:: @ 81A4975
UnknownString_81A4975: @ 81A4975
	.string "{STR_VAR_1}명이서 통신을 시작합니다\n"
	.string "A 버튼으로 결정 B 버튼으로 취소$"

gUnknown_081A49B6:: @ 81A49B6
UnknownString_81A49B6: @ 81A49B6
	.string "통신 시작을 기다리고 있습니다\n"
	.string "...B 버튼으로 취소$"

UnknownString_81A49E2: @ 81A49E2
	.string "통신을 시작하기 전에\n"
	.string "리포트를 작성합니다만 괜찮습니까?$"

OldaleTown_PokemonCenter_2F_Text_1A4A22:: @ 81A4A22
	.string "그럼 방으로 들어가십시오!$"

FallarborTown_ContestLobby_Text_1A4A30:: @ 81A4A30
OldaleTown_PokemonCenter_2F_Text_1A4A30:: @ 81A4A30
	.string "친구의 준비가\n"
	.string "되지가 않은 것 같습니다\p"
	.string "준비를 마치면\n"
	.string "다시 와주십시오$"

FallarborTown_ContestLobby_Text_1A4A85:: @ 81A4A85
OldaleTown_PokemonCenter_2F_Text_1A4A85:: @ 81A4A85
	.string "통신 에러입니다\n"
	.string "리셋한 후 다시 해주십시오$"

OldaleTown_PokemonCenter_2F_Text_1A4AC8:: @ 81A4AC8
	.string "통신 에러입니다\n"
	.string "다른 나라의 언어와는\l"
	.string "통신할 수 없습니다$"

FallarborTown_ContestLobby_Text_1A4B1D:: @ 81A4B1D
OldaleTown_PokemonCenter_2F_Text_1A4B1D:: @ 81A4B1D
	.string "서로의 선택이 다른 것 같습니다$"

OldaleTown_PokemonCenter_2F_Text_1A4B59:: @ 81A4B59
	.string "그럼 또 방문해 주십시오$"

OldaleTown_PokemonCenter_2F_Text_1A4B6C:: @ 81A4B6C
	.string "참가한 인원수가\n"
	.string "맞지 않습니다$"

OldaleTown_PokemonCenter_2F_Text_1A4B95:: @ 81A4B95
	.string "싱글배틀은 {STR_VAR_1}명이서\n"
	.string "즐길 수 없습니다!$"

OldaleTown_PokemonCenter_2F_Text_1A4BCC:: @ 81A4BCC
	.string "더블배틀은 {STR_VAR_1}명이서\n"
	.string "즐길 수 없습니다!$"

OldaleTown_PokemonCenter_2F_Text_1A4C03:: @ 81A4C03
	.string "참가 인원수가 4명이 아니면\n"
	.string "대전할 수 없습니다!$"

OldaleTown_PokemonCenter_2F_Text_1A4C38:: @ 81A4C38
	.string "다시 한 번 인원수를 확인하고\n"
	.string "처음부터 다시 해주십시오$"

TradeRoom_WillLinkBeTerminated: @ 81A4C6E
	.string "방에서 나가면 통신이 종료\n"
	.string "됩니다만 괜찮겠습니까?$"

TradeRoom_TerminatingLink: @ 81A4CAF
	.string "통신을 종료하고 방 밖으로\n"
	.string "안내합니다! 잠시 기다려 주십시오$"

CableClub_TooBusyToNotice: @ 81A4CF6
	.string "바쁜 것 같다...$"

CableClub_LookAtTrainerCard1: @ 81A4D1C
	.string "{STR_VAR_1}의 트레이너카드를\n"
	.string "봤다!$"

CableClub_LookAtTrainerCard2: @ 81A4D45
	.string "{STR_VAR_1}의 트레이너카드를\n"
	.string "봤다!...{STR_VAR_2}카드다!$"

SingleBattleColosseum_Text_1A4D7E:: @ 81A4D7E
	.string "각자 자리에 서서\n"
	.string "대전을 시작해 주십시오$"

TradeCenter_Text_1A4DAB:: @ 81A4DAB
	.string "각자 자리에 서서\n"
	.string "교환을 시작해 주십시오$"

RecordCorner_Text_1A4DD7:: @ 81A4DD7
	.string "자리에 서서 기다려 주십시오$"

RecordCorner_Text_1A4DF7:: @ 81A4DF7
	.string "이용해 주셔서 감사합니다$"

UnknownString_81A4E0A: @ 81A4E0A
	.string "그럼 멀티배틀에 내보낼\n"
	.string "포켓몬을 선택해 주십시오$"

RecordCorner_Text_1A4E3B:: @ 81A4E3B
	.string "{STR_VAR_1}\d로부터\n"
	.string "{STR_VAR_2}\r 전송됐다!$"

OldaleTown_PokemonCenter_2F_Text_1A4E50:: @ 81A4E50
	.string "트레이너카드의\n"
	.string "기록을 다시 씁니다!$"

OldaleTown_PokemonCenter_2F_Text_1A4E79:: @ 81A4E79
	.string "또 이용해 주세요!$"
