ContestString_DescHighlyAppealing: //JP: 39F04C
	.string "많이 어필할 수 있다$"
ContestString_DescStartled1:
	.string "이 어필 다음에\n깜짝 놀라기 쉬워진다$"
ContestString_DescGreatLock:
	.string "엄청난 어필이 되지만 이후부터\n마지막까지 아무것도 할 수 없다$"
ContestString_DescRepeatable:
	.string "계속해서 써도 심사위원이\n싫증 내지 않게 어필할 수 있다$"
ContestString_DescStartled2:
	.string "다른 포켓몬이 놀래도\n한 번 정도는 참을 수 있다$"
ContestString_DescStartled3:
	.string "다른 포켓몬이 놀래도\n참을 수 있다$"
ContestString_DescStartled4:
	.string "다른 포켓몬이 놀래도\n조금 참을 수 있다$"
ContestString_DescStartled5:
	.string "이 기술을 쓴 이후부터\n그다지 놀라지 않게 된다$"
ContestString_DescStartled6:
	.string "자신의 앞에서 어필한\n포켓몬을 조금 놀라게 만든다$"
ContestString_DescStartled7:
	.string "어필이 끝난\n포켓몬 모두를 조금 놀라게 만든다$"
ContestString_DescStartled8:
	.string "자신의 앞에서 어필한\n포켓몬을 놀라게 만든다$"
ContestString_DescStartled9:
	.string "어필이 끝난\n포켓몬 모두를 놀라게 만든다$"
ContestString_DescStartled10:
	.string "자신의 앞에서 어필한\n포켓몬을 상당히 놀라게 만든다$"
ContestString_DescStartled11:
	.string "어필이 끝난 포켓몬\n모두를 상당히 놀라게 만든다$"
ContestString_DescStartled12:
	.string "자신의 앞에서 어필한\n포켓몬을 상당히 놀라게 만든다$"
ContestString_DescStartled13:
	.string "어필이 끝난\n포켓몬 모두를 놀라게 만든다$"
ContestString_DescAttentionShift:
	.string "심사위원의 다른 포켓몬에 대한\n주목을 줄일 수 있다$"
ContestString_DescStartled14:
	.string "심사위원에게 주목받는\n포켓몬을 특히 놀라게 한다$"
ContestString_DescJamOthersMissTurn:
	.string "모두를 방해하고\n다음 어필은 참가하지 않는다$"
ContestString_DescStartled15:
	.string "같은 타입의 어필을 한\n포켓몬을 특히 놀라게 만든다$"
ContestString_DescStartled16:
	.string "근사한 어필을 한\n포켓몬을 상당히 놀라게 만든다$"
ContestString_DescStartled17:
	.string "아름다운 어필을 한\n포켓몬을 상당히 놀라게 만든다$"
ContestString_DescStartled18:
	.string "귀여운 어필을 한\n포켓몬을 상당히 놀라게 만든다$"
ContestString_DescStartled19:
	.string "슬기로운 어필을 한\n포켓몬을 상당히 놀라게 만든다$"
ContestString_DescStartled20:
	.string "강인한 어필을 한\n포켓몬을 상당히 놀라게 만든다$"
ContestString_DescNervousOne:
	.string "이다음 어필을 하는\n포켓몬 한 마리를 긴장시킨다$"
ContestString_DescNervousAllAfter:
	.string "이다음 어필을 하는\n포켓몬 모두를 긴장시킨다$"
ContestString_DescConditionWorseBefore:
	.string "어필이 끝난\n포켓몬의 컨디션을 떨어뜨린다$"
ContestString_DescStartled21:
	.string "컨디션이 좋은 포켓몬\n모두를 상당히 놀라게 만든다$"
ContestString_DescGreatWhenFirst:
	.string "제일 처음으로 어필하면\n어필이 굉장히 잘 된다$"
ContestString_DescGreatWhenLast:
	.string "제일 마지막에 어필하면\n어필이 굉장히 잘 된다$"
ContestString_DescAppealGoodBeforeAll:
	.string "그 턴에서 어필한 다른 포켓몬과\n같은 정도의 어필을 보인다$"
ContestString_DescAppealGoodBeforeOne:
	.string "하나 앞의 포켓몬 어필과\n같은 정도로 잘 할 수 있다$"
ContestString_DescBetterWhenLater:
	.string "나중에 어필을 할수록\n굉장한 어필을 보여줄 수 있다$"
ContestString_DescAffectedByTiming:
	.string "쓸 때마다 어필의 완성도가\n여러 가지로 바뀐다$"
ContestString_DescBetterWhenSameType:
	.string "하나 앞의 포켓몬 어필과\n타입이 같다면 마음에 들게 된다$"
ContestString_DescBetterWhenDiffType:
	.string "하나 앞의 포켓몬 어필과\n타입이 다르다면 마음에 들게 된다$"
ContestString_DescAffectedByFront:
	.string "하나 앞의 포켓몬 어필이\n잘 된 정도에 따라 영향을 받는다$"
ContestString_DescConditionUp:
	.string "어필 컨디션이 올라간다\n긴장도 잘 하지 않게 된다$"
ContestString_DescAffectedByCondition:
	.string "컨디션이 좋을 때 쓰면\n어필이 아주 잘 된다$"
ContestString_DescAppealEarlier:
	.string "이다음의 어필을\n첫 번째로 할 수 있다$"
ContestString_DescAppealLater:
	.string "이다음의 어필을\n마지막에 쓸 수 있다$"
ContestString_DescRandomOrderEasier:
	.string "이다음의 어필의\n순서가 바뀌기 쉬워진다$"
ContestString_DescRandomOrder:
	.string "이다음의 어필 순서를\n엉망으로 한다$"
ContestString_DescAnyExcitement:
	.string "어느 콘테스트에서 보여도\n반드시 열광하는 어필$"
ContestString_DescStartled22:
	.string "어필이 잘 된 포켓몬 모두를\n상당히 놀라게 만든다$"
ContestString_DescScaleWithExcitement:
	.string "관객이 열광하고 있을수록\n어필이 마음에 들게 된다$"
ContestString_DescStopExcitement:
	.string "이 어필 다음에 관객이\n잠시 열광하지 않게 된다"

	.align 2
gUnknown_083CADD4:: @ 83CADD4
	.4byte ContestString_DescHighlyAppealing
	.4byte ContestString_DescStartled1
	.4byte ContestString_DescGreatLock
	.4byte ContestString_DescRepeatable
	.4byte ContestString_DescStartled2
	.4byte ContestString_DescStartled3
	.4byte ContestString_DescStartled4
	.4byte ContestString_DescStartled5
	.4byte ContestString_DescStartled6
	.4byte ContestString_DescStartled7
	.4byte ContestString_DescStartled8
	.4byte ContestString_DescStartled9
	.4byte ContestString_DescStartled10
	.4byte ContestString_DescStartled11
	.4byte ContestString_DescStartled12
	.4byte ContestString_DescStartled13
	.4byte ContestString_DescAttentionShift
	.4byte ContestString_DescStartled14
	.4byte ContestString_DescJamOthersMissTurn
	.4byte ContestString_DescStartled15
	.4byte ContestString_DescStartled16
	.4byte ContestString_DescStartled17
	.4byte ContestString_DescStartled18
	.4byte ContestString_DescStartled19
	.4byte ContestString_DescStartled20
	.4byte ContestString_DescNervousOne
	.4byte ContestString_DescNervousAllAfter
	.4byte ContestString_DescConditionWorseBefore
	.4byte ContestString_DescStartled21
	.4byte ContestString_DescGreatWhenFirst
	.4byte ContestString_DescGreatWhenLast
	.4byte ContestString_DescAppealGoodBeforeAll
	.4byte ContestString_DescAppealGoodBeforeOne
	.4byte ContestString_DescBetterWhenLater
	.4byte ContestString_DescAffectedByTiming
	.4byte ContestString_DescBetterWhenSameType
	.4byte ContestString_DescBetterWhenDiffType
	.4byte ContestString_DescAffectedByFront
	.4byte ContestString_DescConditionUp
	.4byte ContestString_DescAffectedByCondition
	.4byte ContestString_DescAppealEarlier
	.4byte ContestString_DescAppealLater
	.4byte ContestString_DescRandomOrderEasier
	.4byte ContestString_DescRandomOrder
	.4byte ContestString_DescAnyExcitement
	.4byte ContestString_DescStartled22
	.4byte ContestString_DescScaleWithExcitement
	.4byte ContestString_DescStopExcitement

ContestString_MoveRainDance:
	.string "비바라기$"
ContestString_MoveRage:
	.string "분노$"
ContestString_MoveFocusEnergy:
	.string "기충전$"
ContestString_MoveHypnosis:
	.string "최면술$"
ContestString_MoveSoftboiled:
	.string "알낳기$"
ContestString_MoveHornAttack:
	.string "뿔찌르기$"
ContestString_MoveSwordsDance:
	.string "칼춤$"
ContestString_MoveConversion:
	.string "텍스처$"
ContestString_MoveSunnyDay:
	.string "쾌청$"
ContestString_MoveRest:
	.string "잠자기$"
ContestString_MoveVicegrip:
	.string "찝기$"
ContestString_MoveDefenseCurl:
	.string "웅크리기$"
ContestString_MoveLockOn:
	.string "록온$"

	.align 2
	.4byte ContestString_MoveRainDance
	.4byte ContestString_MoveRainDance
	.4byte ContestString_MoveRage
	.4byte ContestString_MoveFocusEnergy
	.4byte ContestString_MoveHypnosis
	.4byte ContestString_MoveSoftboiled
	.4byte ContestString_MoveHornAttack
	.4byte ContestString_MoveSwordsDance
	.4byte ContestString_MoveConversion
	.4byte ContestString_MoveSunnyDay
	.4byte ContestString_MoveRest
	.4byte ContestString_MoveVicegrip
	.4byte ContestString_MoveDefenseCurl
	.4byte ContestString_MoveLockOn

ContestString_Cool:
	.string "근사한$"
ContestString_Beauty:
	.string "아름다운$"
ContestString_Cute:
	.string "귀여운$"
ContestString_Smart:
	.string "슬기로운$"
ContestString_Tough:
	.string "강인한$"

	.align 2
gUnknown_083CAF70:: @ 83CAF70
	.4byte ContestString_Cool
	.4byte ContestString_Beauty
	.4byte ContestString_Cute
	.4byte ContestString_Smart
	.4byte ContestString_Tough

gUnknown_083CAF84:: @ 83CAF84
	.string "{NAME_END}번째 어필!\n어느 기술을 쓸까?$"

gUnknown_083CAFAE:: @ 83CAFAE
	.string "{NAME_END}번째 어필!\n하지만 참가할 수 없다!$"

gUnknown_083CAFD7:: @ 83CAFD7
	.string "{STR_VAR_1}\s\n{STR_VAR_2}\d로 어필!$"
	.string "다른 포켓몬은\n기술을 썼다!{PAUSE 60}$"

gUnknown_083CB00D:: @ 83CB00D
	.string "{STR_VAR_1}\s\n모두를 바라보고 있다!{PAUSE 60}$"

gUnknown_083CB02C:: @ 83CB02C
	.string "어필타임 종료!{PAUSE 60}$"
	.string "{STR_VAR_1}의 {STR_VAR_3}!\n{STR_VAR_2} 효과!{PAUSE 60}$"
	.string "트릭$"
	.string "스페셜$"
ContestString_AppealJammed:
	.string "그러나 방해를 받았다!$"
ContestString_FollowLead:
	.string "다른 포켓몬을 따라했다!$"
ContestString_MessedUp:
	.string "그러나 실패했다!$"
ContestString_BetterUsual:
	.string "평소보다 잘했다!$"
ContestString_JudgeLookAway:
	.string "심사위원이 어쩐지\n시선을 돌렸다!$"
ContestString_WorkHard:
	.string "지금까지의 실패를\n토대로 열심히 해보았다!$"
ContestString_NoMoreMoves:
	.string "더 이상 기술을\n쓸 수 없게 됐다!$"
ContestString_WorkReallyWell:
	.string "무서울 정도로 잘했다!$"
ContestString_WorkHardStandout:
	.string "주목받고 있는 포켓몬과\n똑같이 열심히 했다!$"
ContestString_JudgeExpectantly:
	.string "심사위원이 기대하는\n눈으로 바라봤다!$"
ContestString_WorkRatherWell:
	.string "상당히 잘했다!$"
ContestString_WorkBetter:
	.string "아주 약간 잘했다!$"

	.align 2
	.4byte ContestString_AppealJammed
	.4byte ContestString_FollowLead
	.4byte ContestString_MessedUp
	.4byte ContestString_BetterUsual
	.4byte ContestString_BetterUsual
	.4byte ContestString_JudgeLookAway
	.4byte ContestString_WorkHard
	.4byte ContestString_NoMoreMoves
	.4byte ContestString_WorkReallyWell
	.4byte ContestString_WorkHardStandout
	.4byte ContestString_JudgeExpectantly
	.4byte ContestString_WorkRatherWell
	.4byte ContestString_WorkBetter

ContestString_StandOutNone:
	.string "{STR_VAR_1}\s\n전혀 눈에 띄지 않았다...{PAUSE_UNTIL_PRESS}$"
ContestString_StandOutNotMuch:
	.string "{STR_VAR_1}\s\n그다지 눈에 띄지 않았다...{PAUSE_UNTIL_PRESS}$"
ContestString_StandOutLittle:
	.string "{STR_VAR_1}\s\n그런대로 눈에 띄었다{PAUSE_UNTIL_PRESS}$"
ContestString_StandOutLot:
	.string "{STR_VAR_1}\s\n상당히 눈에 띄었다!{PAUSE_UNTIL_PRESS}$"
ContestString_StandOutTotal:
	.string "{STR_VAR_1}\s\n대단히 눈에 띄었다!{PAUSE_UNTIL_PRESS}$"
ContestString_StandOutDidnt:
	.string "{STR_VAR_1}\s\n어필하지 않았다!{PAUSE_UNTIL_PRESS}$"

	.align 2
gUnknown_083CB2F0:: @ 83CB2F0
	.4byte ContestString_StandOutNone
	.4byte ContestString_StandOutNotMuch
	.4byte ContestString_StandOutLittle
	.4byte ContestString_StandOutLot
	.4byte ContestString_StandOutTotal
	.4byte ContestString_StandOutDidnt

ContestString_AppealAnticipation3:
	.string "{STR_VAR_1}의 어필에\n 기대가 높아졌다!$"
ContestString_JudgeSatisfied:
	.string "심사위원은\n매우 만족했다!$"
ContestString_Terminator:
	.string "$"
ContestString_JudgeHeldFirm:
	.string "심사위원의 {STR_VAR_1}에게의\n인상은 변하지 않는다!$"
ContestString_ChangedPerceptions:
	.string "{STR_VAR_1}의 {STR_VAR_3}\s\n인상을 바꾸어 놓았다!$"
ContestString_AppealWoreOff:
	.string "{STR_VAR_1}의\n어필효과가 없어졌다!$"
ContestString_AppealWoreOff2:
	.string "스페셜 어필의\n효과가 없어졌다!$"
ContestString_AppealLookSame:
	.string "전원의 어필을\n수준이 같아 보이도록 보여줬다!$"
ContestString_AppealCheapened:
	.string "{STR_VAR_2}의 어필을\n 좋지 않아 보이게 보여줬다!$"
ContestString_AppealCheapened2:
	.string "{STR_VAR_1}보다 눈에 띄는 어필을\n좋지 않아 보이게 보여줬다!$"
ContestString_AppealAttentionStolen:
	.string "{STR_VAR_2}의\n주목을 빼앗았다!$"
ContestString_AppealCheapened3:
	.string "{STR_VAR_2}의 어필을\n좋지 않아 보이게 보여줬다!$"
ContestString_AppealCheapened4:
	.string "모두의 어필을\n아주 좋지 않아 보이게 보여줬다!$"
ContestString_AppealAnticipation:
	.string "다음 {STR_VAR_1}의 어필에\n기대가 높아졌다!$"
ContestString_AppealCheapened5:
	.string "{STR_VAR_1}보다 눈에 띄는 어필을\n좋지 않아 보이게 보여줬다!$"
ContestString_AppealCheapened6:
	.string "심사위원의 좋아하는 어필을\n평소보다 좋지 않게 보여줬다!$"
ContestString_AppealCheapened7:
	.string "자신 이외의 어필을\n반 정도만 좋아 보이게 보여줬다!$"
ContestString_JammedStoodOut:
	.string "지금까지 방해받았던\n울분을 떨쳐내고 주목받았다!$"
ContestString_AppealNoMore:
	.string "더는 어필에\n참가할 수 없게 됐다!$"
ContestString_AppealTouched:
	.string "심사위원의 마음에 호소하여\n굉장한 어필이 되었다!$"
ContestString_AppealAnticipation2:
	.string "다음부터의 어필에\n조금 기대가 높아졌다!$"
ContestString_AppealStoodOut2:
	.string "스페셜 어필이 있는\n수만큼 주목받았다!$"
ContestString_AppealStoodOut3:
	.string "{STR_VAR_1}\h\n같은 정도로 주목받았다!$"
ContestString_JammedAppealsNotice:
	.string "방해받은 어필을\n더욱 눈에 띄지 않게 했다!$"
ContestString_AppealSame:
	.string "전원의 어필과\n수준이 같아 보이도록 보여줬다!$"
ContestString_AppealFullWorse:
	.string "{STR_VAR_1}\s 많아서\n인상이 약해졌다!$"

	.align 2
	.4byte ContestString_JudgeHeldFirm
	.4byte ContestString_ChangedPerceptions
	.4byte ContestString_Terminator
	.4byte ContestString_AppealWoreOff
	.4byte ContestString_AppealWoreOff2
	.4byte ContestString_AppealLookSame
	.4byte ContestString_AppealCheapened
	.4byte ContestString_AppealCheapened2
	.4byte ContestString_AppealAttentionStolen
	.4byte ContestString_AppealCheapened3
	.4byte ContestString_AppealCheapened4
	.4byte ContestString_AppealAnticipation
	.4byte ContestString_AppealCheapened5
	.4byte ContestString_AppealCheapened6
	.4byte ContestString_AppealCheapened7
	.4byte ContestString_JammedStoodOut
	.4byte ContestString_AppealNoMore
	.4byte ContestString_AppealTouched
	.4byte ContestString_AppealAnticipation2
	.4byte ContestString_AppealStoodOut2
	.4byte ContestString_AppealStoodOut3
	.4byte ContestString_Terminator
	.4byte ContestString_Terminator
	.4byte ContestString_Terminator
	.4byte ContestString_JammedAppealsNotice
	.4byte ContestString_AppealSame
ContestString_MoreConscious:
	.string "다른 포켓몬에 대해 평소보다\n걱정이 밀려왔다!{PAUSE 60}$"
ContestString_NoAppeal:
	.string "{STR_VAR_1}\s 이후부터\n어필을 할 수 없게 되었다!{PAUSE 60}$"
ContestString_SettleDown:
	.string "아주 조금 마음이 진정되었다!{PAUSE 60}$"
ContestString_ObliviousToOthers:
	.string "다른 포켓몬이\n전혀 신경쓰이지 않게 되었다!{PAUSE 60}$"
ContestString_LessAware:
	.string "다른 포켓몬이\n그다지 신경쓰이지 않게 되었다!{PAUSE 60}$"
ContestString_StoppedCaring:
	.string "다른 포켓몬을\n그다지 신경쓰지 않게 되었다!{PAUSE 60}$"
ContestString_StartleAttempt:
	.string "다른 포켓몬을\n놀라게 만들어 보았다!{PAUSE 60}$"
ContestString_DazzleAttempt:
	.string "관객의 눈을\n속이도록 했다!{PAUSE 60}$"
ContestString_JudgeLookAway2:
	.string "심사위원은 {STR_VAR_1}에게서\n시선을 돌리고 말았다!{PAUSE 60}$"
ContestString_UnnerveAttempt:
	.string "다음을 기다리는 포켓몬을\n긴장하도록 했다!{PAUSE 60}$"
ContestString_Nervous:
	.string "{STR_VAR_1}\s\n긴장해 버렸다!{PAUSE 60}$"
ContestString_UnnerveWaiting:
	.string "어필을 아직 하지 않은 포켓몬을\n긴장하도록 했다!{PAUSE 60}$"
ContestString_TauntWell:
	.string "컨디션이 좋은 포켓몬을\n약 올렸다!{PAUSE 60}$"
ContestString_RegainedForm:
	.string "{STR_VAR_1}의 컨디션이\n돌아와 버렸다!{PAUSE 60}$"
ContestString_JamWell:
	.string "컨디션이 좋은 포켓몬을\n방해해 보았다!{PAUSE 60}$"
ContestString_HustleStandout:
	.string "주목받고 있는 {STR_VAR_1}\s\n더욱 힘을 냈다!{PAUSE 60}$"
ContestString_WorkHardUnnoticed:
	.string "주목받지 못한 {STR_VAR_1}\s\n열심히 했다!{PAUSE 60}$"
ContestString_WorkBefore:
	.string "앞의 포켓몬들에게\n지지 않을 정도로 힘을 냈다!{PAUSE 60}$"
ContestString_AppealNotWell:
	.string "{STR_VAR_1}\s 어필을\n잘 보여주지 못했다!{PAUSE 60}$"
ContestString_WorkPreceding:
	.string "앞의 포켓몬과\n같은 정도로 힘을 냈다!{PAUSE 60}$"
ContestString_AppealNotWell2:
	.string "{STR_VAR_1}\s 어필을\n잘 보여주지 못했다!{PAUSE 60}$"
ContestString_AppealNotShownWell:
	.string "{STR_VAR_1}\s 어필을\n잘 보여주지 못했다!{PAUSE 60}$"
ContestString_AppealSlightlyWell:
	.string "{STR_VAR_1}\s\n그럭저럭 어필을 잘했다!{PAUSE 60}$"
ContestString_AppealPrettyWell:
	.string "{STR_VAR_1}\s\n매우 어필을 잘했다!{PAUSE 60}$"
ContestString_AppealExcellently:
	.string "{STR_VAR_1}\s\n굉장히 어필을 잘했다!{PAUSE 60}$"
ContestString_AppealDud:
	.string "{STR_VAR_1}\s\n어필을 실패하고 말았다!{PAUSE 60}$"
ContestString_AppealNotVeryWell:
	.string "{STR_VAR_1}\s\n그다지 어필을 잘하지 못했다!{PAUSE 60}$"
ContestString_AppealSlightlyWell2:
	.string "{STR_VAR_1}\s\n그럭저럭 어필을 잘했다!{PAUSE 60}$"
ContestString_AppealPrettyWell2:
	.string "{STR_VAR_1}\s\n매우 어필을 잘했다!{PAUSE 60}$"
ContestString_AppealVeryWell:
	.string "{STR_VAR_1}\s\n상당히 어필을 잘했다!{PAUSE 60}$"
ContestString_AppealExcellently2:
	.string "{STR_VAR_1}\s\n굉장히 어필을 잘했다!{PAUSE 60}$"
ContestString_SameTypeGood:
	.string "앞의 포켓몬과 같은 타입으로\n호감을 샀다!{PAUSE 60}$"
ContestString_DiffTypeGood:
	.string "앞의 포켓몬과 다른 타입으로\n호감을 샀다!{PAUSE 60}$"
ContestString_StoodOutAsMuch:
	.string "앞의 포켓몬보다\n꽤 주목받았다!{PAUSE 60}$"
ContestString_NotAsWell:
	.string "앞의 포켓몬보다\n잘하지 못했다!{PAUSE 60}$"
ContestString_ConditionRose:
	.string "{STR_VAR_1}의 컨디션이\n평상시보다 좋아졌다!{PAUSE 60}$"
ContestString_HotStatus:
	.string "{STR_VAR_1}\s 컨디션이 좋아서\n더할 수 없이 좋은 어필을 했다!{PAUSE 60}$"
ContestString_MoveUpLine:
	.string "다음 어필을 빨리 하려고\n앞에 나왔다!{PAUSE 60}$"
ContestString_MoveBackLine:
	.string "다음 어필을 늦게 하려고\n한 걸음 물러섰다!{PAUSE 60}$"
ContestString_ScrambleOrder:
	.string "다음 턴의 순서를\n이상하게 했다!{PAUSE 60}$"

gUnknown_083CBD52:: @ 83CBD52
ContestString_JudgeExpectantly2:
	.string "심사위원이 기대하며\n{STR_VAR_1}\f 바라봤다!{PAUSE 60}$"

gUnknown_083CBD79:: @ 83CBD79
ContestString_WentOverWell:
	.string "어필의 조합이\n마음에 들었다!{PAUSE 60}$"

gUnknown_083CBD9D:: @ 83CBD9D
ContestString_WentOverVeryWell:
	.string "어필의 조합이\n상당히 마음에 들었다!{PAUSE 60}$"

gUnknown_083CBDC6:: @ 83CBDC6
ContestString_AppealComboExcellently:
	.string "어필의 조합이\n굉장히 마음에 들었다!{PAUSE 60}$"
ContestString_AvertGaze:
	.string "{STR_VAR_1}\s 어떻게든\n시선을 돌렸다!{PAUSE 60}$"
ContestString_AvoidSeeing:
	.string "{STR_VAR_1}\s\n그쪽을 보지 않았다!{PAUSE 60}$"
ContestString_NotFazed:
	.string "{STR_VAR_1}\s\n괜찮았다!{PAUSE 60}$"
ContestString_LittleDistracted:
	.string "{STR_VAR_1}\s 조금\n정신이 팔리고 말았다!{PAUSE 60}$"
ContestString_AttemptStartle:
	.string "다른 포켓몬을\n놀라게 만들어 보았다!{PAUSE 60}$"
ContestString_LookedDown:
	.string "{STR_VAR_1}\s 정신이 팔려서\n아래를 내려다봐버렸다!{PAUSE 60}$"
ContestString_TurnedBack:
	.string "{STR_VAR_1}\s 정신이 팔려서\n돌아봐버렸다!{PAUSE 60}$"
ContestString_UtterCry:
	.string "{STR_VAR_1}\s 무의식 중에\n소리를 질러버렸다!{PAUSE 60}$"
ContestString_LeaptUp:
	.string "{STR_VAR_1}\s 자기도 모르게\n펄쩍 뛰어버렸다!{PAUSE 60}$"
ContestString_TrippedOver:
	.string "{STR_VAR_1}\s 정신이 팔려서\n뒤집히고 말았다!{PAUSE 60}$"

gUnknown_083CBF60:: @ 83CBF60
ContestString_TooNervous:
	.string "{STR_VAR_1}\s 긴장해서\n어필을 할 수 없었다!{PAUSE 60}$"
ContestString_MessedUp2:
	.string "그러나 실패하고 말았다!{PAUSE 60}$"
ContestString_FailedTargetNervous:
	.string "그러나 긴장\n시킬 수 없었다!{PAUSE 60}$"
ContestString_FailedAnyoneNervous:
	.string "그러나 아무도\n긴장하지 않았다!{PAUSE 60}$"
ContestString_Ignored:
	.string "그러나 무시당하고 말았다...{PAUSE 60}$"
ContestString_NoConditionImprove:
	.string "그러나 컨디션이\n좋아지지 않았다...{PAUSE 60}$"
ContestString_BadConditionWeakAppeal:
	.string "컨디션이 좋지 않아서\n그리 잘하지 못했다...{PAUSE 60}$"
ContestString_Unaffected:
	.string "{STR_VAR_1}\s\n괜찮았다!{PAUSE 60}$"

gUnknown_083CC075:: @ 83CC075
ContestString_DissapointedRepeat:
	.string "{STR_VAR_1}\s 같은 어필을\n계속했기에 모두를 실망시켰다!{PAUSE 60}$"

gUnknown_083CC0A0:: @ 83CC0A0
ContestString_WentOverGreat:
	.string "{STR_VAR_1}의 {STR_VAR_3}\r\n주변에서 엄청 좋았다!{PAUSE 60}$"

gUnknown_083CC0BC:: @ 83CC0BC
ContestString_DidntGoWell:
	.string "{STR_VAR_1}의 {STR_VAR_3}\s\n여기서 먹히지 않는 듯하다...{PAUSE 60}$"

gUnknown_083CC0E3:: @ 83CC0E3
ContestString_GotCrowdGoing:
	.string "{STR_VAR_1}의 {STR_VAR_3}에\n주변의 분위기가 달아올랐다!{PAUSE 60}$"

gUnknown_083CC103:: @ 83CC103
ContestString_CantAppealNextTurn:
	.string "{STR_VAR_1}\s 다음 어필에\n참가할 수 없게 되었다!{PAUSE 60}$"
ContestString_AttractedAttention:
	.string "관객의\n주의를 끌었다!{PAUSE 60}$"

gUnknown_083CC14A:: @ 83CC14A
ContestString_CrowdWatches:
	.string "관객은 {STR_VAR_3}\f\n계속 주목하고 있다!{PAUSE 60}$"

gUnknown_083CC16E:: @ 83CC16E
ContestString_Ignored2:
	.string "{STR_VAR_1}의 {STR_VAR_2}\s\n눈길을 받지 못했다...{PAUSE 60}$"

	.align 2
gUnknown_083CC188:: @ 83CC188
	.4byte ContestString_MoreConscious
	.4byte ContestString_NoAppeal
	.4byte ContestString_SettleDown
	.4byte ContestString_ObliviousToOthers
	.4byte ContestString_LessAware
	.4byte ContestString_StoppedCaring
	.4byte ContestString_StartleAttempt
	.4byte ContestString_DazzleAttempt
	.4byte ContestString_JudgeLookAway2
	.4byte ContestString_UnnerveAttempt
	.4byte ContestString_Nervous
	.4byte ContestString_UnnerveWaiting
	.4byte ContestString_TauntWell
	.4byte ContestString_RegainedForm
	.4byte ContestString_JamWell
	.4byte ContestString_HustleStandout
	.4byte ContestString_WorkHardUnnoticed
	.4byte ContestString_WorkBefore
	.4byte ContestString_AppealNotWell
	.4byte ContestString_WorkPreceding
	.4byte ContestString_AppealNotWell2
	.4byte ContestString_AppealNotShownWell
	.4byte ContestString_AppealSlightlyWell
	.4byte ContestString_AppealPrettyWell
	.4byte ContestString_AppealExcellently
	.4byte ContestString_AppealDud
	.4byte ContestString_AppealNotVeryWell
	.4byte ContestString_AppealSlightlyWell2
	.4byte ContestString_AppealPrettyWell2
	.4byte ContestString_AppealVeryWell
	.4byte ContestString_AppealExcellently2
	.4byte ContestString_SameTypeGood
	.4byte ContestString_DiffTypeGood
	.4byte ContestString_StoodOutAsMuch
	.4byte ContestString_NotAsWell
	.4byte ContestString_ConditionRose
	.4byte ContestString_HotStatus
	.4byte ContestString_MoveUpLine
	.4byte ContestString_MoveBackLine
	.4byte ContestString_ScrambleOrder
	.4byte ContestString_JudgeExpectantly2 @ expectantly
	.4byte ContestString_WentOverWell
	.4byte ContestString_WentOverVeryWell
	.4byte ContestString_AppealComboExcellently
	.4byte ContestString_AvertGaze
	.4byte ContestString_AvoidSeeing
	.4byte ContestString_NotFazed
	.4byte ContestString_LittleDistracted
	.4byte ContestString_AttemptStartle
	.4byte ContestString_LookedDown
	.4byte ContestString_TurnedBack
	.4byte ContestString_UtterCry
	.4byte ContestString_LeaptUp
	.4byte ContestString_TrippedOver
	.4byte ContestString_MessedUp2
	.4byte ContestString_FailedTargetNervous
	.4byte ContestString_FailedAnyoneNervous
	.4byte ContestString_Ignored
	.4byte ContestString_NoConditionImprove
	.4byte ContestString_BadConditionWeakAppeal
	.4byte ContestString_Unaffected
	.4byte ContestString_AttractedAttention

gUnknown_083CC280:: @ 83CC280
	.string "꾸물꾸물$"

gUnknown_083CC288:: @ 83CC288
	.string "두근두근$"

gUnknown_083CC290:: @ 83CC290
	.string "부끄부끄$"

gUnknown_083CC299:: @ 83CC299
	.string "꾸물꾸물$"

gUnknown_083CC2A3:: @ 83CC2A3
	.string "흠칫흠칫$"

ContestString_Coolness:
	.string "근사함$"
ContestString_Beauty2:
	.string "아름다움$"
ContestString_Cuteness:
	.string "귀여움$"
ContestString_Smartness:
	.string "슬기로움$"
ContestString_Toughness:
	.string "강인함$"

	.align 2
gUnknown_083CC2D8:: @ 83CC2D8
	.4byte ContestString_Coolness
	.4byte ContestString_Beauty2
	.4byte ContestString_Cuteness
	.4byte ContestString_Smartness
	.4byte ContestString_Toughness

gUnknown_083CC2EC:: @ 83CC2EC
	.string "TENSION:$"

ContestString_CoolMove:
	.string "근사한 기술$"

ContestString_BeautyMove:
	.string "아름다운 기술$"

ContestString_CuteMove:
	.string "귀여운 기술$"

ContestString_SmartMove:
	.string "슬기로운 기술$"

ContestString_ToughMove:
	.string "강인한 기술$"

ContestString_UnknownMoveType:
	.string "???$"

	.align 2
gUnknown_083CC330:: @ 83CC330
	.4byte ContestString_CoolMove
	.4byte ContestString_BeautyMove
	.4byte ContestString_CuteMove
	.4byte ContestString_SmartMove
	.4byte ContestString_ToughMove
	.4byte ContestString_UnknownMoveType

@ unused?
ContestString_Rank:
	.string "랭크$"

	.string "{HIGHLIGHT TRANSPARENT}{COLOR MAGENTA} $"
