Route117_Text_1B25CB:: @ 81B25CB
	.string "나는 키우미집 할아버지라네\p"
	.string "여기서 모두의 소중한\n"
	.string "포켓몬을 돌보구 있구먼\p"
	.string "뭔가 키우고 싶다면\n"
	.string "할머니에게 부탁하게나$"

Route117_Text_1B2659:: @ 81B2659
	.string "오오! 자네구먼\p"
	.string "맡고 있던 포켓몬을\n"
	.string "키우고 있었더니... 글쎄!\p"
	.string "포켓몬이 알을\n"
	.string "가지고 있었구먼!\p"
	.string "어디서 가져왔는지 모르겠지만\n"
	.string "자네의 포켓몬이 가지고 있던\l"
	.string "알이구먼\p"
	.string "역시 갖고 싶겠지?$"

Route117_Text_1B2710:: @ 81B2710
	.string "오오 자네구먼! 잘 왔네\n"
	.string "{STR_VAR_1}{K_EUNNEUN} 잘 있구먼$"

Route117_Text_1B2745:: @ 81B2745
	.string "그럼 내가 갖겠네\n"
	.string "고맙구먼$"

Route117_Text_1B2766:: @ 81B2766
	.string "포켓몬이 가득이구먼...\n"
	.string "지닌 포켓몬을 정리하고\l"
	.string "다시 와 주게나$"

Route117_Text_1B27A2:: @ 81B27A2
	.string "{PLAYER}{K_EUNNEUN} 키우미집 할아버지에게서\n"
	.string "알을 받았다!$"

Route117_Text_1B27CD:: @ 81B27CD
	.string "소중하게 키우게!$"

Route117_Text_1B27E3:: @ 81B27E3
	.string "그런데 자네의 {STR_VAR_1} 말인데\n"
	.string "왠지 {STR_VAR_2}네 {STR_VAR_3}{K_WAGWA}\l"
	.string "사이좋게 놀고 있었구먼\p"
	.string "게다가 메일 같은 것도\n"
	.string "받는 것 같더구먼$"

UnknownString_81B2858: @ 81B2858
	.string "포켓몬을 데려가고 싶을 때는\n"
	.string "할머니에게 말해주게$"

Route117_Text_1B2897:: @ 81B2897
	.string "오오 자네구먼! 잘 왔네\n"
	.string "{STR_VAR_1}{K_WAGWA}\l"
	.string "{STR_VAR_2}{K_EUNNEUN} 잘 있구먼!$"

Route117_Text_1B28C4:: @ 81B28C4
	.string "내가 가져갈지도 모른다네\n"
	.string "사실은 갖고 싶지?$"

Route117_PokemonDayCare_Text_1B28F2:: @ 81B28F2
	.string "나는 키우미집 할머니라네\p"
	.string "자네를 대신해서\n"
	.string "포켓몬을 키워주지\p"
	.string "뭔가 키우고 싶은가?$"

Route117_PokemonDayCare_Text_1B2947:: @ 81B2947
	.string "어느 아이를 키워 볼 텐가?$"

Route117_PokemonDayCare_Text_1B296E:: @ 81B296E
	.string "그럼 {STR_VAR_1}{K_EULREUL}\n"
	.string "당분간 맡아주지\p"
	.string "적당히 시간이\n"
	.string "지나면 다시 오게나$"

Route117_PokemonDayCare_Text_1B29AD:: @ 81B29AD
	.string "2마리까지 맡을 수 있는데\n"
	.string "다른 1마리도 키워 볼 텐가?$"

Route117_PokemonDayCare_Text_1B29F4:: @ 81B29F4
	.string "할아버지가 자네를 찾고 있다네$"

Route117_PokemonDayCare_Text_1B2A14:: @ 81B2A14
	.string "그래\n"
	.string "그럼 또 오게나$"

Route117_PokemonDayCare_Text_1B2A30:: @ 81B2A30
	.string "돈이 부족한 것 같은데...$"

Route117_PokemonDayCare_Text_1B2A4F:: @ 81B2A4F
	.string "다른 1마리도 데리고 갈 텐가?$"

Route117_PokemonDayCare_Text_1B2A76:: @ 81B2A76
	.string "그럼 또 오게나$"

Route117_PokemonDayCare_Text_1B2A88:: @ 81B2A88
	.string "오오 자넨가! 잘 왔구먼\n"
	.string "자네 포켓몬은 잘 있네\l"
	.string "데리고 갈 건가?$"

Route117_PokemonDayCare_Text_1B2ACC:: @ 81B2ACC
	.string "{STR_VAR_1}{K_EUNNEUN} 레벨로 말하면\n"
	.string "{STR_VAR_2} 정도 자랐구먼$"

Route117_PokemonDayCare_Text_1B2AEF:: @ 81B2AEF
	.string "지닌 포켓몬이 가득이네!\n"
	.string "지닌 포켓몬을 정리하고\l"
	.string "다시 와 주구려$"

UnknownString_81B2B27: @ 81B2B27
	.string "어느 포켓몬을 데리고 갈 텐가?$"

Route117_PokemonDayCare_Text_1B2B49:: @ 81B2B49
	.string "{STR_VAR_1}{K_EULREUL} 데리고 갈 거면\n"
	.string "요금은 {STR_VAR_2}원이구먼$"

Route117_PokemonDayCare_Text_1B2B75:: @ 81B2B75
	.string "잘 받았네!\n"
	.string "그럼 데리고 가게나!$"

Route117_PokemonDayCare_Text_1B2B93:: @ 81B2B93
	.string "{PLAYER}{K_EUNNEUN} 키우미집 할머니한테서\n"
	.string "{STR_VAR_1}{K_EULREUL} 데리고 왔다!$"

Route117_PokemonDayCare_Text_1B2BBB:: @ 81B2BBB
	.string "어라? 포켓몬이\n"
	.string "1마리밖에 없구먼\p"
	.string "또 오게나$"

Route117_PokemonDayCare_Text_1B2BF6:: @ 81B2BF6
	.string "포켓몬을 찾아갈 텐가?$"

Route117_PokemonDayCare_Text_1B2C17:: @ 81B2C17
	.string "그 포켓몬을 맡기면\n"
	.string "싸울 수 없게 되네\p"
	.string "또 오게나$"

UnknownString_81B2C68: @ 81B2C68
	.string "어라...?$"

@ XXX JP
	.string "\p"
	.string "알의 상태가...\p"
	.string "......\p"
	.string "축하합니다!\n"
	.string "알이 부화해서\l"
	.string "{STR_VAR_1}{K_IGA} 태어났습니다!$"
