UnknownString_81C5033: @ 81C5033 //JP: 196960
	.string "아빠: {PLAYER}! 잘 왔다!\n"
	.string "맡아둔 편지가 있단다$"

UnknownString_81C5070: @ 81C5070
	.string "아빠: 나도 본 적 없는\n"
	.string "배의 티켓이로군...\l"
	.string "해안시티에 가보는 게 좋을 거다$"

LilycoveCity_Harbor_Text_1C50F2:: @ 81C50F2
	.string "잿빛도시행 연락선...\p"
	.string "어머?\n"
	.string "그 티켓은...!$"

LilycoveCity_Harbor_Text_1C5120:: @ 81C5120
	.string "이상한 티켓을\n"
	.string "가지고 온 게 너야?\p"
	.string "네가 가려고 하는 곳은\n"
	.string "남쪽 제일 끝에 있는 조그만 섬...\p"
	.string "그곳은 뭐가 일어날지\n"
	.string "아무도 모르는 곳...\l"
	.string "으음 선원의 피가 들끓는구만!\p"
	.string "자 어서 타!$"

SouthernIsland_Exterior_Text_1C5215:: @ 81C5215
	.string "아무것도 없는 시시한 섬이구만...\n"
	.string "해안시티로 돌아갈래?$"

SouthernIsland_Exterior_Text_1C5281:: @ 81C5281
	.string "그래 그럼 돌아간다$"

SouthernIsland_Exterior_Text_1C52A6:: @ 81C52A6
	.string "그러냐\n"
	.string "뭐 마음대로 해$"

SouthernIsland_Interior_Text_1C52C5:: @ 81C52C5
	.string "모든 꿈은 또 하나의 현실\n"
	.string "그걸 잊지 마...$"

SouthernIsland_Exterior_Text_1C52FB:: @ 81C52FB
	.string "기억이 흐려지는 자는\n"
	.string "마음에 새기는 것을 희망한다...$"
