Route111_Text_1ABED8:: @ 81ABED8
	.string "마리: 오 이런 곳에서\n"
	.string "강해 보이는 트레이너 발견!\p"
	.string "좋아 카메라 돌리고\n"
	.string "인터뷰 시작하자!$"

Route111_Text_1ABF50:: @ 81ABF50
Route118_Text_1ABF50:: @ 81ABF50
Route120_Text_1ABF50:: @ 81ABF50
	.string "마리: 아! 너는\n"
	.string "예전에 만났었던 {PLAYER} 트레이너!\p"
	.string "좋아 얼마나 강해졌는지\n"
	.string "바로 인터뷰 시작이야!$"

Route111_Text_1ABFD3:: @ 81ABFD3
	.string "마리: 내 눈은 틀림없어!\n"
	.string "엄청난 트레이너를 발견!$"

Route111_Text_1AC015:: @ 81AC015
	.string "마리: 대단해! 대단해!\n"
	.string "너 도대체 정체가 뭐야!?\p"
	.string "역시 우리가\n"
	.string "눈여겨본 사람이야!\p"
	.string "...아 사실 우리는\n"
	.string "여러 곳에서 다양한 트레이너를\l"
	.string "인터뷰하면서 다니고 있어\p"
	.string "그러니 잠깐만\n"
	.string "인터뷰에 응해 주면 안 될까?$"

Route111_Text_1AC10A:: @ 81AC10A
	.string "마리: “{STR_VAR_1}!”\p"
	.string "이거 기억해? 예전에 배틀했을 때\n"
	.string "네가 했던 말이야\p"
	.string "우리들 제대로\n"
	.string "기억하고 있지!$"

Route111_Text_1AC18D:: @ 81AC18D
	.string "맞아 예전에 배틀했을 때는\n"
	.string "손도 발도 안 못 썼었어...\p"
	.string "그건 그렇고 어때?\n"
	.string "또 인터뷰 한번 응해볼래?$"

Route111_Text_1AC219:: @ 81AC219
	.string "맞아 예전에 배틀했을 때는\n"
	.string "볼을 던졌었지...\p"
	.string "정말 놀라서 모두한테\n"
	.string "말해버리고 말았어!\p"
	.string "그건 그렇고 어때?\n"
	.string "또 인터뷰 한번 응해볼래?$"

Route111_Text_1AC2D6:: @ 81AC2D6
	.string "맞아 예전에 배틀했을 때는\n"
	.string "도구를 잘 사용해서\l"
	.string "져버리고 말았어\p"
	.string "그건 그렇고 어때?\n"
	.string "또 인터뷰 한번 응해볼래?$"

Route111_Text_1AC355:: @ 81AC355
	.string "맞아 예전에 배틀했을 때는\n"
	.string "근사한 승부를 했었지\p"
	.string "그건 그렇고 어때?\n"
	.string "또 인터뷰 한번 응해볼래?$"

Route111_Text_1AC3CF:: @ 81AC3CF
	.string "그건 그렇고 어때?\n"
	.string "또 인터뷰 한번 응해볼래?$"

Route111_Text_1AC40F:: @ 81AC40F
	.string "정말!?\n"
	.string "고마워!\p"
	.string "그럼 배틀을 하고 난 뒤의 감상을\n"
	.string "간단하게 한마디로\l"
	.string "부탁해!$"

Route111_Text_1AC487:: @ 81AC487
	.string "마리: 음-!\n"
	.string "최고의 명대사야\p"
	.string "왠지 괜찮은 TV 방송이\n"
	.string "만들어질 거 같은 예감이 들어!\p"
	.string "잘하면 이게\n"
	.string "TV에서 방송될지도 모르니까\l"
	.string "잊지 말고 TV를 체크해야 돼!\p"
	.string "그럼 이만\n"
	.string "또 보자!$"

Route111_Text_1AC553:: @ 81AC553
	.string "마리: 그래...\p"
	.string "그래도 앞으로도 힘내!\n"
	.string "널 주목하고 있으니까!$"

Route111_Text_1AC59E:: @ 81AC59E
Route118_Text_1AC59E:: @ 81AC59E
Route120_Text_1AC59E:: @ 81AC59E
	.string "마리: 널 주목하고 있어!$"

Route111_Text_1AC5CA:: @ 81AC5CA
Route118_Text_1AC5CA:: @ 81AC5CA
Route120_Text_1AC5CA:: @ 81AC5CA
	.string "마리: 포켓몬을 많이 데리고 다니는\n"
	.string "강한 트레이너는 없을까?$"

Route111_Text_1AC60B:: @ 81AC60B
	.string "마리: 음- 역시 훌륭해!\p"
	.string "예전에 배틀했을 때보다\n"
	.string "훨씬 더 강해졌구나!\p"
	.string "역시 우리가\n"
	.string "눈여겨본 트레이너야!\p"
	.string "그건 그렇고 어때?\n"
	.string "이번에야말로 인터뷰에\l"
	.string "응해보지 않을래?$"

Route111_Text_1AC6F8:: @ 81AC6F8
Route118_Text_1AC6F8:: @ 81AC6F8
Route120_Text_1AC6F8:: @ 81AC6F8
	.string "마리: 엄청난 배틀이었어!\n"
	.string "이봐 제대로 찍었겠지?!$"

Route111_Text_1AC73B:: @ 81AC73B
	.string "다이: 오 이런 곳에서\n"
	.string "강해 보이는 트레이너 발견!\l"
	.string "바로 녹화 개시다!!$"

Route111_Text_1AC790:: @ 81AC790
Route118_Text_1AC790:: @ 81AC790
Route120_Text_1AC790:: @ 81AC790
	.string "다이: 너는 요전의!\p"
	.string "좋아 여기서의 배틀을 모두\n"
	.string "카메라에 담아주겠어$"

Route111_Text_1AC7E4:: @ 81AC7E4
Route118_Text_1AC7E4:: @ 81AC7E4
Route120_Text_1AC7E4:: @ 81AC7E4
	.string "다이: 역시 훌륭해!\n"
	.string "괜찮은 영상을 찍을 수 있었어!$"

Route111_Text_1AC820:: @ 81AC820
Route118_Text_1AC820:: @ 81AC820
Route120_Text_1AC820:: @ 81AC820
	.string "다이: 넌 포켓몬을 1마리밖에\n"
	.string "데리고 있지 않은 거야?\p"
	.string "포켓몬이 많이 있어야\n"
	.string "그림이 더 좋은데...$"

Route111_Text_1AC892:: @ 81AC892
	.string "다이: 엄청난 트레이너를 발견했다!\n"
	.string "특종이다! 특종!$"

Route111_Text_1AC8D7:: @ 81AC8D7
Route118_Text_1AC8D7:: @ 81AC8D7
Route120_Text_1AC8D7:: @ 81AC8D7
	.string "다이: 조금 전 배틀의 모든 것이\n"
	.string "이 카메라에 담겼다!$"

gTVGabbyAndTyText1:: @ 81AC90D
	.string "“트레이너를 찾아서”\p"
	.string "마리: 네에 저는 지금\n"
	.string "{STR_VAR_1}에 왔습니다!\p"
	.string "오늘은 이곳에서 대단한 재능을\n"
	.string "발굴하고자 합니다!\p"
	.string "오늘 제가 주목한\n"
	.string "트레이너는 {PLAYER}님!\p"
	.string "저는 이 트레이너에게\n"
	.string "무언가를 느낍니다!$"

gTVGabbyAndTyText2:: @ 81ACA02
	.string "{PLAYER}님과는 전에\n"
	.string "배틀한 적이 있는데\l"
	.string "확실히 이전보다 강해진\l"
	.string "그런 느낌이 듭니다!\p"
	.string "역시 제가\n"
	.string "주목한 트레이너!$"

gTVGabbyAndTyText3:: @ 81ACAAA
	.string "자! 트레이너의 실력을\n"
	.string "보려면...\p"
	.string "배틀하는 것이\n"
	.string "제일 빠르죠!\p"
	.string "그럼 조사를\n"
	.string "시작하겠습니다!\p"
	.string "... ...\p"
	.string "이런 이유로\n"
	.string "배틀해봤습니다만\p"
	.string "멋지게 엉망으로 당했습니다!\n"
	.string "{PLAYER}님 너무 강한데요...\p"
	.string "그래서 배틀한 감상을\n"
	.string "말로 표현하자면$"

gTVGabbyAndTyText4:: @ 81ACC07
	.string "{STR_VAR_1}{K_WAGWA} {STR_VAR_3}의\n"
	.string "콤비 플레이가 최고였습니다!\p"
	.string "{STR_VAR_1}{K_WAGWA} {STR_VAR_3}{K_IGA} 서로\n"
	.string "도우며 배틀하는 모습...\p"
	.string "아아 그렇게\n"
	.string "근사할 수가 없어요!\p"
	.string "저희들과의 승부의\n"
	.string "마지막에 사용한 “{STR_VAR_2}”도\p"
	.string "{STR_VAR_1}{K_WAGWA} {STR_VAR_3}의 우정의\n"
	.string "“{STR_VAR_2}”인 거예요!$"

gTVGabbyAndTyText5:: @ 81ACD13
	.string "...저는 자신감을\n"
	.string "잃어버리고 말았습니다\p"
	.string "한 번이라도 공격할 틈도 없이\n"
	.string "바로 져버리고 말았습니다\l"
	.string "아아 후우...\p"
	.string "그래도 {PLAYER}님과의 배틀은\n"
	.string "한번 볼 가치가 있어요!\p"
	.string "자신 있는 트레이너는 한번\n"
	.string "배틀해보시는 것을 추천드려요!$"

gTVGabbyAndTyText6:: @ 81ACDFA
	.string "트레이너와 싸우고 있을 때에는\n"
	.string "몬스터볼을 던지지마!\l"
	.string "라는 겁니다\p"
	.string "{PLAYER}님은 승부에 강하시지만\n"
	.string "기본이 안 돼 있어요!\p"
	.string "자 TV를 보시고 있는 여러분들!\p"
	.string "{PLAYER}님을 만나면\n"
	.string "주의하라고 해주세요!$"

gTVGabbyAndTyText7:: @ 81ACEE7
	.string "{PLAYER}님은 상대의 행동을\n"
	.string "읽는 것을 무척 잘하세요!\p"
	.string "도구를 쓰는 타이밍은 왠지\n"
	.string "대단했습니다!$"

gTVGabbyAndTyText8:: @ 81ACF49
	.string "솔직히 저도 그럭저럭\n"
	.string "강하지 않느냐고 생각했습니다-!\p"
	.string "마지막엔 결국 져버렸지만\n"
	.string "좋은 시합이었죠-\p"
	.string "하지만 저에게 고전해서는\n"
	.string "아직입니다! {PLAYER}님!$"

gTVGabbyAndTyText9:: @ 81AD00A
	.string "대전 뒤 {PLAYER}님에게\n"
	.string "감상을 물었더니\p"
	.string "“{STR_VAR_1}”\n"
	.string "이렇게 대답해 주셨습니다\p"
	.string "{PLAYER}님의 포켓몬\n"
	.string "{STR_VAR_2}{K_WAGWA} {STR_VAR_3}\l"
	.string "그리고 “{STR_VAR_1}”...\p"
	.string "음-!\n"
	.string "왠지 뜻깊은 말이네요!\p"
	.string "역시 좋은 트레이너는\n"
	.string "좋은 말을 하네요\p"
	.string "그럼 다음 방송에서\n"
	.string "다시 만나뵙겠습니다$"
