gGiftRibbonDescriptionPart1_2003RegionalTourney: //JP: 3B79A4
	.string "2003년 지방 대회$"

gGiftRibbonDescriptionPart2_Champion:
	.string "우승 기념리본$"

gGiftRibbonDescriptionPart1_2003NationalTourney:
	.string "2003년 전국 대회$"

gGiftRibbonDescriptionPart1_2003GlobalCup:
	.string "2003년 월드컵$"

gGiftRibbonDescriptionPart2_RunnerUp:
	.string "준우승 기념리본$"

gGiftRibbonDescriptionPart2_Semifinalist:
	.string "베스트4 기념리본$"

gGiftRibbonDescriptionPart1_2004RegionalTourney:
	.string "2004년 지방 대회$"

gGiftRibbonDescriptionPart1_2004NationalTourney:
	.string "2004년 전국 대회$"

gGiftRibbonDescriptionPart1_2004GlobalCup:
	.string "2004년 월드컵$"

gGiftRibbonDescriptionPart1_2005RegionalTourney:
	.string "2005년 지방 대회$"

gGiftRibbonDescriptionPart1_2005NationalTourney:
	.string "2005년 전국 대회$"

gGiftRibbonDescriptionPart1_2005GlobalCup:
	.string "2005년 월드컵$"

gGiftRibbonDescriptionPart1_PokemonBattleCup:
	.string "포켓몬 배틀 컵$"

gGiftRibbonDescriptionPart2_Participation:
	.string "참가 기념리본$"

gGiftRibbonDescriptionPart1_PokemonLeague:
	.string "포켓몬리그$"

gGiftRibbonDescriptionPart1_AdvanceCup:
	.string "어드밴스 컵$"

gGiftRibbonDescriptionPart1_PokemonTournament:
	.string "포켓몬 대회에$"

gGiftRibbonDescriptionPart2_Participation2:
	.string "참가한 기념리본$"

gGiftRibbonDescriptionPart1_PokemonEvent:
	.string "포켓몬 이벤트에$"

gGiftRibbonDescriptionPart1_PokemonFestival:
	.string "포켓몬 축제에$"

gGiftRibbonDescriptionPart1_DifficultyClearing:
	.string "곤란에 싸워 이긴$"

gGiftRibbonDescriptionPart2_Commemorative:
	.string "기념리본$"

gGiftRibbonDescriptionPart1_ClearingAllDifficulties:
	.string "모든 고난을$"

gGiftRibbonDescriptionPart2_ClearingAllDifficulties:
	.string "극복한 기념리본$"

gGiftRibbonDescriptionPart1_100StraightWin:
	.string "100명에게 승리 달성$"

gGiftRibbonDescriptionPart1_DarknessTower:
	.string "어둠탑 클리어$"

gGiftRibbonDescriptionPart1_RedTower:
	.string "붉은 탑 클리어$"

gGiftRibbonDescriptionPart1_BlackironTower:
	.string "무쇠탑 클리어$"

gGiftRibbonDescriptionPart1_FinalTower:
	.string "최후의 탑 클리어$"

gGiftRibbonDescriptionPart1_LegendMaking:
	.string "전설을 만든$"

gGiftRibbonDescriptionPart1_PokemonCenterTokyo:
	.string "포켓몬센터 도쿄$"

gGiftRibbonDescriptionPart1_PokemonCenterOsaka:
	.string "포켓몬센터 오사카$"

gGiftRibbonDescriptionPart1_PokemonCenterNagoya:
	.string "포켓몬센터 나고야$"

gGiftRibbonDescriptionPart1_PokemonCenterNY:
	.string "포켓몬센터 뉴욕$"

gGiftRibbonDescriptionPart1_SummerHolidays:
	.string "여름 방학 기념리본$"

gGiftRibbonDescriptionPart2_EmptyString:
	.string "$"

gGiftRibbonDescriptionPart1_WinterHolidays:
	.string "겨울 방학 기념리본$"

gGiftRibbonDescriptionPart1_SpringHolidays:
	.string "봄 방학 기념리본$"

gGiftRibbonDescriptionPart1_Evergreen:
	.string "크리스마스 기념리본$"

gGiftRibbonDescriptionPart1_SpecialHoliday:
	.string "기념일 기념리본$"

gGiftRibbonDescriptionPart1_HardWorker:
	.string "열심히 한 기념리본$"

gGiftRibbonDescriptionPart1_LotsOfFriends:
	.string "친구 가득 기념리본$"

gGiftRibbonDescriptionPart1_FullOfEnergy:
	.string "기운 가득 기념리본$"

gGiftRibbonDescriptionPart1_LovedPokemon:
	.string "매우 좋아하는 포켓몬에게 달려 있는$"

gGiftRibbonDescriptionPart2_LovedPokemon:
	.string "기념리본$"

gGiftRibbonDescriptionPart1_LoveForPokemon:
	.string "포켓몬을 매우 좋아하는 것을$"

gGiftRibbonDescriptionPart2_LoveForPokemon:
	.string "증명하는 기념리본$"

	.align 2
gGiftRibbonDescriptions:: @ 83E158C
	.4byte gGiftRibbonDescriptionPart1_2003RegionalTourney,   gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_2003NationalTourney,   gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_2003GlobalCup,         gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_2003RegionalTourney,   gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_2003NationalTourney,   gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_2003GlobalCup,         gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_2003RegionalTourney,   gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_2003NationalTourney,   gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_2003GlobalCup,         gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_2004RegionalTourney,   gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_2004NationalTourney,   gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_2004GlobalCup,         gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_2004RegionalTourney,   gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_2004NationalTourney,   gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_2004GlobalCup,         gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_2004RegionalTourney,   gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_2004NationalTourney,   gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_2004GlobalCup,         gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_2005RegionalTourney,   gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_2005NationalTourney,   gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_2005GlobalCup,         gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_2005RegionalTourney,   gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_2005NationalTourney,   gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_2005GlobalCup,         gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_2005RegionalTourney,   gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_2005NationalTourney,   gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_2005GlobalCup,         gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_PokemonBattleCup,      gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_PokemonBattleCup,      gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_PokemonBattleCup,      gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_PokemonBattleCup,      gGiftRibbonDescriptionPart2_Participation
	.4byte gGiftRibbonDescriptionPart1_PokemonLeague,         gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_PokemonLeague,         gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_PokemonLeague,         gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_PokemonLeague,         gGiftRibbonDescriptionPart2_Participation
	.4byte gGiftRibbonDescriptionPart1_AdvanceCup,            gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_AdvanceCup,            gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_AdvanceCup,            gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_AdvanceCup,            gGiftRibbonDescriptionPart2_Participation
	.4byte gGiftRibbonDescriptionPart1_PokemonTournament,     gGiftRibbonDescriptionPart2_Participation2
	.4byte gGiftRibbonDescriptionPart1_PokemonEvent,          gGiftRibbonDescriptionPart2_Participation2
	.4byte gGiftRibbonDescriptionPart1_PokemonFestival,       gGiftRibbonDescriptionPart2_Participation2
	.4byte gGiftRibbonDescriptionPart1_DifficultyClearing,    gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_ClearingAllDifficulties, gGiftRibbonDescriptionPart2_ClearingAllDifficulties
	.4byte gGiftRibbonDescriptionPart1_100StraightWin,        gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_DarknessTower,         gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_RedTower,              gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_BlackironTower,        gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_FinalTower,            gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_LegendMaking,          gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_PokemonCenterTokyo,    gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_PokemonCenterOsaka,    gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_PokemonCenterNagoya,   gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_PokemonCenterNY,       gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_SummerHolidays,        gGiftRibbonDescriptionPart2_EmptyString
	.4byte gGiftRibbonDescriptionPart1_WinterHolidays,        gGiftRibbonDescriptionPart2_EmptyString
	.4byte gGiftRibbonDescriptionPart1_SpringHolidays,        gGiftRibbonDescriptionPart2_EmptyString
	.4byte gGiftRibbonDescriptionPart1_Evergreen,             gGiftRibbonDescriptionPart2_EmptyString
	.4byte gGiftRibbonDescriptionPart1_SpecialHoliday,        gGiftRibbonDescriptionPart2_EmptyString
	.4byte gGiftRibbonDescriptionPart1_HardWorker,            gGiftRibbonDescriptionPart2_EmptyString
	.4byte gGiftRibbonDescriptionPart1_LotsOfFriends,         gGiftRibbonDescriptionPart2_EmptyString
	.4byte gGiftRibbonDescriptionPart1_FullOfEnergy,          gGiftRibbonDescriptionPart2_EmptyString
	.4byte gGiftRibbonDescriptionPart1_LovedPokemon,          gGiftRibbonDescriptionPart2_LovedPokemon
	.4byte gGiftRibbonDescriptionPart1_LoveForPokemon,        gGiftRibbonDescriptionPart2_LoveForPokemon
