gLandmarkName_FlowerShop::
	.string "플라워숍$"

gLandmarkName_PetalburgWoods::
	.string "등화숲$"

gLandmarkName_MrBrineysCottage::
	.string "하기노인의 작은 집$"

gLandmarkName_AbandonedShip::
	.string "버려진 배$"

gLandmarkName_SeashoreHouse::
	.string "바다의 집$"

gLandmarkName_SlateportBeach::
	.string "잿빛도시의 해변$"

gLandmarkName_CyclingRoad::
	.string "사이클링 로드$"

gLandmarkName_NewMauville::
	.string "뉴보라$"

gLandmarkName_TrickHouse::
	.string "미궁의 대저택$"

gLandmarkName_OldLadysRestShop::
	.string "건강할머니$"

gLandmarkName_Desert::
	.string "사막$"

gLandmarkName_WinstrateFamily::
	.string "연승가족$"

gLandmarkName_CableCar::
	.string "케이블카 승강장$"

gLandmarkName_GlassWorkshop::
	.string "유리 세공 가게$"

gLandmarkName_WeatherInstitute::
	.string "날씨 연구소$"

gLandmarkName_MeteorFalls::
	.string "유성의 폭포$"

gLandmarkName_TunnelersRestHouse::
	.string "터널공사자 대기실$"

gLandmarkName_RusturfTunnel::
	.string "금잔터널$"

gLandmarkName_PokemonDayCare::
	.string "포켓몬 키우미집$"

gLandmarkName_SafariZoneEntrance::
	.string "사파리존 입구$"

gLandmarkName_MtPyre::
	.string "송화산$"

gLandmarkName_ShoalCave::
	.string "여울의 동굴$"

gLandmarkName_SeafloorCavern::
	.string "해저동굴$"

gLandmarkName_GraniteCave::
	.string "바위 동굴$"

gLandmarkName_OceanCurrent::
	.string "해류$"

gLandmarkName_LanettesHouse::
	.string "유미의 집$"

gLandmarkName_FieryPath::
	.string "불꽃샛길$"

gLandmarkName_JaggedPass::
	.string "울퉁불퉁 산길$"

gLandmarkName_SkyPillar::
	.string "하늘기둥$"

gLandmarkName_BerryMastersHouse::
	.string "나무열매 명인의 집$"

gLandmarkName_IslandCave::
	.string "작은 섬 옆굴$"

gLandmarkName_DesertRuins::
	.string "사막유적$"

gLandmarkName_ScorchedSlab::
	.string "가뭄의 암굴$"

gLandmarkName_AncientTomb::
	.string "고대의 무덤$"

gLandmarkName_SealedChamber::
	.string "고시의 석실$"

gLandmarkName_FossilManiacsHouse::
	.string "화석마니아의 집$"

gLandmarkName_HuntersHouse::
	.string "헌터의 작은 집$"
