LilycoveCity_DepartmentStore_1F_Text_1C4B5E:: @ 81C4B5E //JP: 196692
	.string "이곳은 ID 추첨센터\n"
	.string "추첨 코너입니다\p"
	.string "본 백화점에 방문하신\n"
	.string "모든 분께 ID 추첨센터\l"
	.string "추첨을 하고 있습니다!\p"
	.string "추첨한 번호와 손님의\n"
	.string "포켓몬 ID를 뒤에서부터 비교하여\l"
	.string "일치한 자릿수에 따라 멋진 상품을\l"
	.string "선물로 드립니다!\p"
	.string "ID 추첨센터\n"
	.string "추첨에 도전하겠습니까?$"

LilycoveCity_DepartmentStore_1F_Text_1C4C6A:: @ 81C4C6A
	.string "내일 다시 생각이\n"
	.string "나신다면 와 주십시오$"

LilycoveCity_DepartmentStore_1F_Text_1C4C85:: @ 81C4C85
	.string "그럼 다음에 또 이용해 주세요$"

UnknownString_81C4C9F: @ 81C4C9F
	.string "그럼 추첨을 하겠습니다\n"
	.string "...$"

LilycoveCity_DepartmentStore_1F_Text_1C4CC6:: @ 81C4CC6
	.string "그럼 추첨을 하겠습니다\n"
	.string "...{PAUSE}{0x39} ...{PAUSE}{0x39} ...{PAUSE}{0x39}$"

LilycoveCity_DepartmentStore_1F_Text_1C4CF6:: @ 81C4CF6
	.string "추첨 번호는 {STR_VAR_1}입니다!\p"
	.string "번호가 당신의 포켓몬 ID와\n"
	.string "일치하는지 알아볼 테니\l"
	.string "잠시 기다려 주십시오$"

LilycoveCity_DepartmentStore_1F_Text_1C4D7D:: @ 81C4D7D
	.string "축하합니다!\p"
	.string "당신이 데리고 있는\n"
	.string "{STR_VAR_1}의 ID가\l"
	.string "추첨 번호와 일치합니다!$"

LilycoveCity_DepartmentStore_1F_Text_1C4DD1:: @ 81C4DD1
	.string "축하합니다!\p"
	.string "PC에 맡긴\n"
	.string "{STR_VAR_1}의 ID가\l"
	.string "추첨 번호와 일치합니다!$"

LilycoveCity_DepartmentStore_1F_Text_1C4E27:: @ 81C4E27
	.string "아쉽네요\n"
	.string "꽝입니다...$"

LilycoveCity_DepartmentStore_1F_Text_1C4E4F:: @ 81C4E4F
	.string "2자리 일치하니\n"
	.string "3등입니다!\l"
	.string "{STR_VAR_1}{K_EULREUL} 드리겠습니다!$"

LilycoveCity_DepartmentStore_1F_Text_1C4E92:: @ 81C4E92
	.string "3자리 일치하니\n"
	.string "2등입니다!\l"
	.string "{STR_VAR_1}{K_EULREUL} 드리겠습니다!$"

LilycoveCity_DepartmentStore_1F_Text_1C4ED8:: @ 81C4ED8
	.string "4자리 일치하니\n"
	.string "1등입니다!\l"
	.string "{STR_VAR_1}{K_EULREUL} 드리겠습니다!$"

LilycoveCity_DepartmentStore_1F_Text_1C4F1C:: @ 81C4F1C
	.string "무려! 5자리 모두\n"
	.string "일치합니다!\p"
	.string "특등입니다!\n"
	.string "{STR_VAR_1}{K_EULREUL} 드리겠습니다!$"

LilycoveCity_DepartmentStore_1F_Text_1C4F77:: @ 81C4F77
	.string "...어라?\n"
	.string "도구가 가득한 모양입니다만\p"
	.string "도구를 정리하고 나서 다시 한 번\n"
	.string "와 주십시오$"

LilycoveCity_DepartmentStore_1F_Text_1C4FCC:: @ 81C4FCC
	.string "{PLAYER}님이시군요\n"
	.string "보관하고 있었습니다!\p"
	.string "그럼 상품을\n"
	.string "드리도록 하겠습니다$"

LilycoveCity_DepartmentStore_1F_Text_1C501C:: @ 81C501C
	.string "그럼 다음에 또 이용해 주세요$"
