MtPyre_Summit_Text_1B5CFD:: @ 81B5CFD //JP: 18DF43
	.string "마그마단의 진정한 무서움을\n"
	.string "너에게 가르쳐 주지!$"

MtPyre_Summit_Text_1B5D30:: @ 81B5D30
	.string "혼자서 마그마단에\n"
	.string "맞서겠다는 건가?$"

MtPyre_Summit_Text_1B5D6D:: @ 81B5D6D
	.string "넌 확실히 강하군...\n"
	.string "하지만 우리들은 아주 많다!$"

MtPyre_Summit_Text_1B5DA2:: @ 81B5DA2
	.string "뭐야 넌?\n"
	.string "어린애가 혼자서 뭘 하겠다는 거냐?$"

MtPyre_Summit_Text_1B5DDB:: @ 81B5DDB
	.string "젠장 강하다...$"

MtPyre_Summit_Text_1B5DF1:: @ 81B5DF1
	.string "아무것도 모르는 주제에\n"
	.string "우리를 방해하지 마라!$"

MtPyre_Summit_Text_1B5E27:: @ 81B5E27
	.string "넌... 굴뚝산에서 만났던!\n"
	.string "그 빚을 갚아주마!$"

MtPyre_Summit_Text_1B5E60:: @ 81B5E60
	.string "으으으...\n"
	.string "또 어린애에게 져버렸다...$"

MtPyre_Summit_Text_1B5E84:: @ 81B5E84
	.string "이 정도면 됐어... 시간은 벌었다!\p"
	.string "지금쯤 리더가 원하는 걸\n"
	.string "빼앗았을 거다!$"

MtPyre_Summit_Text_1B5EEC:: @ 81B5EEC
	.string "마적: 또 네 녀석인가...\p"
	.string "너에게는 여태까지 몇 번이나\n"
	.string "방해를 받았지만\l"
	.string "이번만큼은 늦은 모양이군!\p"
	.string "이 송화산에 모셔져 있던\n"
	.string "쪽빛구슬...\l"
	.string "분명히 이 마적이 가져간다!\p"
	.string "후후후... 이걸로 나의 목적도\n"
	.string "달성할 수 있다...\p"
	.string "다음은 잿빛도시다!\n"
	.string "서둘러라!!$"

MtPyre_Summit_Text_1B5FE6:: @ 81B5FE6
	.string "아아 이거 어쩌면 좋을꼬...!\p"
	.string "쪽빛구슬을...\n"
	.string "빼앗겨 버리다니...\p"
	.string "쪽빛구슬과 주홍구슬이\n"
	.string "서로 떨어져 버리다니\l"
	.string "결코 있어서는 안 될 일이거늘...\p"
	.string "... ... ...\n"
	.string "음...\p"
	.string "좋아! 너에게는 남겨진\n"
	.string "이 주홍구슬을 맡기마\p"
	.string "아까 전 남자를 쫓아서\n"
	.string "구슬을 되찾아 와 주거라...!$"

MtPyre_Summit_Text_1B60F9:: @ 81B60F9
	.string "너한테 준 주홍구슬과\n"
	.string "빼앗긴 쪽빛구슬...\p"
	.string "따로 떨어져 있으면\n"
	.string "분명 좋지 않은 일이 일어날 거야...$"

MtPyre_Summit_Text_1B617B:: @ 81B617B
	.string "그래...\n"
	.string "그란돈이 눈을 뜬 건가...\p"
	.string "일찍이 그란돈의 분노를\n"
	.string "잠재우는 신비로운 구슬이 바로\l"
	.string "그 주홍구슬이라고\l"
	.string "전해지고 있지...\p"
	.string "그리고 그 구슬을 우연히 찾아낸 곳이\n"
	.string "루네시티에 있는 각성의 사당...\p"
	.string "그란돈과 각성의 사당은\n"
	.string "무슨 관계가 있을지도 모르겠구먼...$"

MtPyre_Summit_Text_1B6283:: @ 81B6283
	.string "아까 전 남자\n"
	.string "쪽빛구슬을 돌려주었단다\p"
	.string "너도\n"
	.string "주홍구슬을 돌려주지 않겠니?$"

MtPyre_Summit_Text_1B62E7:: @ 81B62E7
	.string "뭐라고?!\n"
	.string "이대로 균형이 무너진 채라면\l"
	.string "뭔가 일어날지 모르는데?\p"
	.string "너\n"
	.string "주홍구슬을 돌려놓을 거지?$"

UnknownString_81B6374: @ 81B6374
	.string "{PLAYER}\s 할머니에게\n"
	.string "주홍구슬을 건네주었다!$"

MtPyre_Summit_Text_1B639C:: @ 81B639C
	.string "음...\n"
	.string "2개의 구슬은 여기에 놓아두마...\p"
	.string "그것이 이 호연을 위해서도\n"
	.string "가장 좋은 모습일 거야...$"

MtPyre_Summit_Text_1B63F8:: @ 81B63F8
	.string "대지의 화신...\n"
	.string "그것이 그란돈의 정체라고\l"
	.string "전해지고 있단다...\p"
	.string "우리들 인간이나 포켓몬에게\n"
	.string "생명이 있는 것처럼\l"
	.string "이 대지 역시 살아있단다...\p"
	.string "그란돈은 우리들에게 그것을\n"
	.string "알려주려 했던 거겠지...$"

MtPyre_Summit_Text_1B64B3:: @ 81B64B3
	.string "송화산은 포켓몬의 영혼을\n"
	.string "위로하기 위한 곳...\p"
	.string "여기는 높은 곳에 있기 때문에\n"
	.string "호연지방을 한눈에 볼 수 있어서\l"
	.string "포켓몬들의 영혼도\l"
	.string "평온함을 느낄 수 있는 거겠지...\p"
	.string "자네가 여기로 온 것도\n"
	.string "하나의 인연...\p"
	.string "호연지방에서 전해지고 있는\n"
	.string "이야기를 듣고 가게나...$"

MtPyre_Summit_Text_1B65D6:: @ 81B65D6
	.string "멀고도 먼 옛날...\p"
	.string "세계는 육지와 바다의 포켓몬이\n"
	.string "격렬한 싸움을 벌이고 있었지\p"
	.string "육지의 포켓몬은\n"
	.string "대지를 일으켜 세워 땅을 넓히고\p"
	.string "바다의 포켓몬은\n"
	.string "거센 파도를 일으켜 바다를 넓혔지\p"
	.string "두 마리의 싸움은 끝나지 않고\p"
	.string "이 세계는 휘몰아치는 폭풍과\n"
	.string "활활 타오르는 불꽃으로 휩싸였지\p"
	.string "그것을 잠재운 것이\n"
	.string "주홍구슬과 쪽빛구슬...\p"
	.string "두 구슬에서 퍼진 빛이\n"
	.string "두 마리의 분노를 잠재웠다\p"
	.string "그리고 얌전해진 두 마리는\n"
	.string "해저 깊은 곳으로 들어가\l"
	.string "머지않아 그 모습을 감추었다는군....$"

MtPyre_Summit_Text_1B6823:: @ 81B6823
	.string "그러냐...\n"
	.string "뭐 그것도 좋겠지...$"

MtPyre_Summit_Text_1B6848:: @ 81B6848
	.string "마적: 네가...\n"
	.string "그란돈을...\p"
	.string "역시나로군...\p"
	.string "어차피 인간은\n"
	.string "대지와 바다의 균형을\l"
	.string "자유롭게 조종할 수 없어...\p"
	.string "그래서 여기에\n"
	.string "쪽빛구슬을 돌려주러 왔다...\p"
	.string "다시 너와 만날 일은 없겠지...\n"
	.string "작별이다...$"
