MtChimney_Text_1B37BB:: @ 81B37BB
	.string "운석에 숨겨진 힘...\p"
	.string "이 장치로 증폭된다면\n"
	.string "눈 깜짝할 사이에 굴뚝산의\l"
	.string "화산 활동은 활발해진다...\p"
	.string "후후후... 화산은 분화해서\n"
	.string "뜨거워져 용암이 식어 굳으며\l"
	.string "대지가 넓어지겠지...$"

MtChimney_Text_1B38B3:: @ 81B38B3
	.string "마적: 또 네 녀석인가...\p"
	.string "... 알겠나 우리\n"
	.string "인간은 대지에서 진화해왔다!\p"
	.string "그래 대지야말로 전부다!\p"
	.string "그래서 우리 마그마단은\n"
	.string "대지를 넓혀서\l"
	.string "새로운 포켓몬을 진화시킨다!\p"
	.string "인간이 발전하기 위한\n"
	.string "장소도 넓힌다!\p"
	.string "이것이야말로 마그마단의 이상!\n"
	.string "아무것도 모르는 너같은 꼬마에게\l"
	.string "방해받을 수는 없다\p"
	.string "방해한다면 어떻게 되는지\n"
	.string "이 마적이 똑똑히 보여주마!$"

MtChimney_Text_1B3A68:: @ 81B3A68
	.string "뭣이!?\p"
	.string "이 마적이\n"
	.string "방심한 건가!?$"

MtChimney_Text_1B3A90:: @ 81B3A90
	.string "마적: 뭐 좋다\n"
	.string "이 굴뚝산은 일단\l"
	.string "포기하도록 하지...\p"
	.string "하지만 우리 마그마단의 활동은\n"
	.string "아무도 멈출 수 없다!\p"
	.string "그것만은 잊지 마라!$"

MtChimney_Text_1B3B36:: @ 81B3B36
	.string "우효효!\p"
	.string "너 여기까지 온 건가!\p"
	.string "하지만 늦었다고\n"
	.string "유성의 폭포에서 찾은\l"
	.string "운석은 리더에게 넘겼으니까 말이야!$"

MtChimney_Text_1B3BB8:: @ 81B3BB8
	.string "우효효...\n"
	.string "져버렸나...\p"
	.string "그 때 유성의 폭포에서\n"
	.string "싸우지 않아서 다행이군$"

MtChimney_Text_1B3C07:: @ 81B3C07
	.string "우효효...!\p"
	.string "나를 이겨도\n"
	.string "리더는 이길 수 없을 걸!\p"
	.string "빨리 돌아가는 편이\n"
	.string "아픈 기억이 남지 않을 거다$"

MtChimney_Text_1B3C96:: @ 81B3C96
	.string "우리 마그마단은\n"
	.string "모두를 위해 노력하고 있는 거다!\p"
	.string "땅이 늘어나면\n"
	.string "살 수 있는 곳이 늘어나니\l"
	.string "모두에게 좋은 일이지!$"

MtChimney_Text_1B3D1E:: @ 81B3D1E
	.string "어라-?\n"
	.string "나 진 건가-?$"

MtChimney_Text_1B3D3D:: @ 81B3D3D
	.string "우리들의 리더가\n"
	.string "“모두를 위한 일”이라고\l"
	.string "했단 말이다!\p"
	.string "근데 왜 다들 방해하는 거지?$"

MtChimney_Text_1B3D9A:: @ 81B3D9A
	.string "아쿠아단 녀석들...\n"
	.string "일일이 우리 방해나 해대고 말야!$"

MtChimney_Text_1B3DD6: @ 81B3DD6
	.string "운석에는 엄청난 파워가 있어!$"

MtChimney_Text_1B3DF5:: @ 81B3DF5
	.string "가라! 아쿠아단을 부숴 버려라!\n"
	.string "그리고 대지를 늘리는 것이다!$"

MtChimney_Text_1B3E1F:: @ 81B3E1F
	.string "우리 방해하지 마라! 알겠어?\p"
	.string "우린 모두를 위해서\n"
	.string "대지를 늘리려고 하는 거니까!$"

MtChimney_Text_1B3E7A:: @ 81B3E7A
	.string "좋아!\n"
	.string "불꽃을 퍼부어버려-!!$"

UnknownString_81B3E94: @ 81B3E94
	.string "좀 더 좀 더 대지를 넓히자고!$"

MtChimney_Text_1B3EBA:: @ 81B3EBA
	.string "부와-!!$"

MtChimney_Text_1B3EC1:: @ 81B3EC1
	.string "아강: 오오! {PLAYER}!\n"
	.string "마침 잘 와 주었다!\p"
	.string "나를 대신해서\n"
	.string "마그마단을 멈추어다오!\p"
	.string "저 녀석들 빼앗은 운석의 파워로\n"
	.string "이 화산을 분화시켜서\l"
	.string "육지를 넓히려고 하고 있다!$"

MtChimney_Text_1B3F8C:: @ 81B3F8C
	.string "아강: {PLAYER}!\p"
	.string "나를 대신해서\n"
	.string "마그마단을 멈추어다오!\p"
	.string "이 녀석들 조무래기 3명의 상대는\n"
	.string "역시 나라도 큰일이다!$"

MtChimney_Text_1B3FFE:: @ 81B3FFE
	.string "아강: {PLAYER}! 고맙다\n"
	.string "네 덕분에 마그마단의\l"
	.string "파괴활동을 막을 수 있었다\p"
	.string "하지만... 아직 그 녀석들의 야망은\n"
	.string "이걸로 끝난 것이 아니다!\p"
	.string "우리는 계속해서 마그마단을\n"
	.string "쫓아가도록 하겠다!\p"
	.string "{PLAYER} 다음에 보도록 하지!$"

MtChimney_Text_1B40EA:: @ 81B40EA
	.string "제길 마그마단이 너무 많아...\n"
	.string "이대로라면 위험해!$"

MtChimney_Text_1B4128:: @ 81B4128
	.string "대지를 늘려버리면\n"
	.string "물포켓몬이 살 수 있는 곳이\l"
	.string "적어지잖아!$"

MtChimney_Text_1B416E:: @ 81B416E
	.string "마그마단 녀석들\n"
	.string "육지를 늘리려고 하다니\l"
	.string "바보 같은 것들!$"

MtChimney_Text_1B41B0:: @ 81B41B0
	.string "후샤-!!$"
