SeafloorCavern_Room9_Text_1B4850:: @ 81B4850
	.string "마적: ...거기 멈춰라!$"

SeafloorCavern_Room9_Text_1B486C:: @ 81B486C
	.string "마적: 후후후...\n"
	.string "역시 너였던 건가$"

SeafloorCavern_Room9_Text_1B4897:: @ 81B4897
	.string "마적: 어떤가 보거라!\p"
	.string "초 고대포켓몬 그란돈이\n"
	.string "조용히 잠들어 있는\l"
	.string "이 아름다운 모습을!\p"
	.string "난 이 날이 오기만을\n"
	.string "오랫동안 기다려왔다...$"

SeafloorCavern_Room9_Text_1B491F:: @ 81B491F
	.string "마적: 그건 그렇고 설마 네가\n"
	.string "여기까지 왔을 줄이야!\p"
	.string "하지만 그것도 끝이다\n"
	.string "내 목적 달성을 위해\l"
	.string "너는 여기서 사라져 줘야겠다!$"

SeafloorCavern_Room9_Text_1B49AE:: @ 81B49AE
	.string "이 내가...\n"
	.string "또다시 질 줄이야...$"

SeafloorCavern_Room9_Text_1B49C1:: @ 81B49C1
	.string "마적: 후후후...\p"
	.string "역시나라고 해야 하나...\n"
	.string "너의 그 힘은 인정하마!\p"
	.string "허나...!\n"
	.string "내게는 이것이 있다!\p"
	.string "이 쪽빛구슬이 있으면\n"
	.string "그란돈을...$"

SeafloorCavern_Room9_Text_1B4A5A:: @ 81B4A5A
	.string "쪽빛구슬이...\n"
	.string "멋대로 빛나기 시작했다...?!$"

SeafloorCavern_Room9_Text_1B4A89:: @ 81B4A89
	.string "마적: ..?!\p"
	.string "나는 아무것도 하지 않았는데\n"
	.string "어째서 쪽빛구슬이...?\p"
	.string "그란돈은 어디로 사라졌지?$"

SeafloorCavern_Room9_Text_1B4ADB:: @ 81B4ADB
	.string "마적: 밖에 있는\n"
	.string "단원으로부터 온 연락인가$"

SeafloorCavern_Room9_Text_1B4B11:: @ 81B4B11
	.string "마적: 무슨 일인가...?\p"
	.string "흠...\n"
	.string "태양이 격렬하게 빛나고 있다...\p"
	.string "그렇겠지... 그것이야말로\n"
	.string "우리들 마그마단의 목적\l"
	.string "대지를 넓히기 위해 그란돈을\l"
	.string "깨운 이유니까 말이다\p"
	.string "뭐라고!\p"
	.string "예상을 뛰어넘는 열기라 이대로라면\n"
	.string "우리들도 위험하다고?!\p"
	.string "설마 그럴 리가...\n"
	.string "그럴 리가 없을 텐데...\p"
	.string "어쨌든 계속 상태를 보고 있어라!$"

SeafloorCavern_Room9_Text_1B4C79:: @ 81B4C79
	.string "마적: 이상하군...\p"
	.string "쪽빛구슬로 그란돈이 눈을 뜨고\n"
	.string "그리고 컨트롤할 수 있었을 텐데...\p"
	.string "그런데... 어째서...\n"
	.string "그란돈은 여기서 없어졌다?!\p"
	.string "왜 그런 거지?!$"

SeafloorCavern_Room9_Text_1B4D02:: @ 81B4D02
	.string "아강: 무슨 일이란 말인가...\p"
	.string "마적... 너는 결국\n"
	.string "그란돈을 눈 뜨게 해버린 건가!\p"
	.string "이대로 영원히\n"
	.string "햇빛이 내리쬐인다면\l"
	.string "세계는 대체 어떻게 되겠는가!\p"
	.string "모든 바다가\n"
	.string "말라 붙게 되는 거다...$"

SeafloorCavern_Room9_Text_1B4DD3:: @ 81B4DD3
	.string "마적: 뭐라고...?\p"
	.string "쪽빛구슬이 있으면 그란돈을\n"
	.string "컨트롤할 수 있을 텐데...\l"
	.string "그럴 리가...$"

SeafloorCavern_Room9_Text_1B4E37:: @ 81B4E37
	.string "아강: 어쨌든 지금은 여기서\n"
	.string "말다툼하고 있을 때가 아니다!\p"
	.string "밖으로 나가서 확인하도록 해라!\n"
	.string "눈앞에 펼쳐진 게\l"
	.string "네가 원하던 세계인지 아닌지를$"

SeafloorCavern_Room9_Text_1B4ECA:: @ 81B4ECA
	.string "아강: {PLAYER}도\n"
	.string "서둘러 밖으로 나가거라!$"
