gMoveDescription_Pound:	
	.string "손이나 꼬리 등으로\n"
	.string "적을 때려서 공격$"
	
gMoveDescription_KarateChop:	
	.string "당수로 적을 공격\n"
	.string "급소에 맞기 쉬워진다$"
	
gMoveDescription_DoubleSlap:	
	.string "적을 연속 뺨치기로\n"
	.string "2-5회 연속으로 공격$"
	
gMoveDescription_CometPunch:	
	.string "적을 연속으로 세게 때려서\n"
	.string "2-5회 연속으로 공격$"
	
gMoveDescription_MegaPunch:	
	.string "굉장한 힘을 담은 펀치로\n"
	.string "적을 때려서 공격$"
	
gMoveDescription_PayDay:	
	.string "돈을 던져서 적을 공격\n"
	.string "배틀 후에 돈을 얻을 수 있다$"
	
gMoveDescription_FirePunch:	
	.string "불꽃을 담은 펀치로 공격\n"
	.string "적을 화상 입힐 때가 있다$"
	
gMoveDescription_IcePunch:	
	.string "냉기를 담은 펀치로 공격\n"
	.string "적을 얼릴 때가 있다$"
	
gMoveDescription_ThunderPunch:	
	.string "전격을 담은 펀치로 공격\n"
	.string "적을 마비시킬 때가 있다$"
	
gMoveDescription_Scratch:	
	.string "날카로운 손톱으로\n"
	.string "적을 할퀴어서 공격$"
	
gMoveDescription_ViceGrip:	
	.string "큰 집게를 사용해서\n"
	.string "적을 집어 공격$"
	
gMoveDescription_Guillotine:	
	.string "큰 집게를 사용해서\n"
	.string "적을 집어 전투불능으로 만든다$"
	
gMoveDescription_RazorWind:	
	.string "1턴째에 바람의 칼날을 만들어\n"
	.string "다음 턴에 적을 공격$"
	
gMoveDescription_SwordsDance:	
	.string "싸움의 춤을 추어\n"
	.string "공격을 크게 올린다$"
	
gMoveDescription_Cut:	
	.string "날카로운 낫이나 손톱 등으로\n"
	.string "적을 베어 공격$"
	
gMoveDescription_Gust:	
	.string "날개로 격한 바람을 일으켜\n"
	.string "바람을 적에게 부딪쳐서 공격$"
	
gMoveDescription_WingAttack:	
	.string "날개를 크게 펼쳐\n"
	.string "그대로 적에게 맞힌다$"
	
gMoveDescription_Whirlwind:	
	.string "강한 바람으로 적을 날려버린다\n"
	.string "날려버리면 배틀은 끝난다$"
	
gMoveDescription_Fly:	
	.string "1턴째에 하늘로 날아올라\n"
	.string "다음 턴에 적을 공격$"
	
gMoveDescription_Bind:	
	.string "2-5턴 동안 긴 몸이나\n"
	.string "덩굴 등을 써서 적을 조인다$"
	
gMoveDescription_Slam:	
	.string "긴 꼬리나 덩굴 등을 써서\n"
	.string "적을 힘껏 쳐서 공격$"
	
gMoveDescription_VineWhip:	
	.string "채찍처럼 가늘고 긴 덩굴을\n"
	.string "적에게 힘껏 쳐서 공격$"
	
gMoveDescription_Stomp:	
	.string "큰 발로 적을 짓밟아서 공격\n"
	.string "적을 풀죽게 할 때가 있다$"
	
gMoveDescription_DoubleKick:	
	.string "2개의 다리로 적을\n"
	.string "2회 연속으로 공격$"
	
gMoveDescription_MegaKick:	
	.string "굉장한 힘을 담은 킥으로\n"
	.string "적을 걷어차서 공격$"
	
gMoveDescription_JumpKick:	
	.string "점프한 기세로 킥을\n"
	.string "날린다 빗나가면 데미지를 입는다$"
	
gMoveDescription_RollingKick:	
	.string "몸을 재빨리 1회전시켜\n"
	.string "그 기세로 킥을 날린다$"
	
gMoveDescription_SandAttack:	
	.string "적의 얼굴 등에 모래를 뿌려서\n"
	.string "명중률을 떨어뜨리게 한다$"
	
gMoveDescription_Headbutt:	
	.string "머리부터 돌진하여 공격\n"
	.string "적을 풀죽게 만들 때가 있다$"
	
gMoveDescription_HornAttack:	
	.string "뾰족한 뿔로\n"
	.string "적을 찔러서 공격$"
	
gMoveDescription_FuryAttack:	
	.string "뾰족한 뿔 등으로\n"
	.string "2-5회 연속으로 공격$"
	
gMoveDescription_HornDrill:	
	.string "뿔을 드릴같이 회전시켜\n"
	.string "적을 찔러서 전투불능으로 만든다$"
	
gMoveDescription_Tackle:	
	.string "몸 전체를 써가며\n"
	.string "적에게 부딪쳐서 공격$"
	
gMoveDescription_BodySlam:	
	.string "몸째로 자빠져서 공격\n"
	.string "적을 마비시킬 때가 있다$"
	
gMoveDescription_Wrap:	
	.string "2-5턴 동안 긴 몸이나\n"
	.string "덩굴을 사용해 적을 조인다$"
	
gMoveDescription_TakeDown:	
	.string "기세를 더해 적에게 부딪친다\n"
	.string "자신도 조금 데미지를 입는다$"
	
gMoveDescription_Thrash:	
	.string "2-3턴 동안 난동부린다\n"
	.string "난동부린 뒤에는 혼란에 빠져버린다$"
	
gMoveDescription_DoubleEdge:	
	.string "목숨을 걸고 적에게 부딪친다\n"
	.string "자신도 조금 데미지를 입는다$"
	
gMoveDescription_TailWhip:	
	.string "적에게 꼬리를 흔들어 방심시켜서\n"
	.string "방어를 떨어뜨리게 한다$"
	
gMoveDescription_PoisonSting:	
	.string "독이 있는 침이나 뿔로 공격\n"
	.string "적에게 독을 줄 때가 있다$"
	
gMoveDescription_Twineedle:	
	.string "양손의 침을 써서\n"
	.string "적을 2회 연속으로 공격$"
	
gMoveDescription_PinMissile:	
	.string "날카로운 침을 적에게 발사해서\n"
	.string "2-5회 연속으로 공격$"
	
gMoveDescription_Leer:	
	.string "적을 째려봐서 겁을 주어\n"
	.string "방어를 떨어뜨리게 한다$"
	
gMoveDescription_Bite:	
	.string "날카로운 이빨로 물어서 공격\n"
	.string "적을 풀죽게 만들 때가 있다$"
	
gMoveDescription_Growl:	
	.string "귀엽게 울어 적을 방심시켜서\n"
	.string "공격을 떨어뜨리게 한다$"
	
gMoveDescription_Roar:	
	.string "짖어서 적을 도망치게 한다\n"
	.string "적이 도망치면 배틀은 끝난다$"
	
gMoveDescription_Sing:	
	.string "기분 좋은 노랫소리로\n"
	.string "적을 깊은 잠으로 유도한다$"
	
gMoveDescription_Supersonic:	
	.string "몸에서 괴음파를 발산하여\n"
	.string "적을 혼란시킬 때가 있다$"
	
gMoveDescription_SonicBoom:	
	.string "충격파로 적을 공격\n"
	.string "언제나 20의 데미지를 준다$"
	
gMoveDescription_Disable:	
	.string "초능력으로 적의 움직임을\n"
	.string "막아서 기술을 1개 쓰지 못하게 한다$"
	
gMoveDescription_Acid:	
	.string "강한 산으로 적의 피부를 녹인다\n"
	.string "방어를 떨어뜨릴 때가 있다$"
	
gMoveDescription_Ember:	
	.string "작은 불꽃으로 공격\n"
	.string "적을 화상 입힐 때가 있다$"
	
gMoveDescription_Flamethrower:	
	.string "굉장한 불꽃으로 공격\n"
	.string "적을 화상 입힐 때가 있다$"
	
gMoveDescription_Mist:	
	.string "하얀 안개로 몸을 덮어\n"
	.string "능력이 떨어지지 않게 한다$"
	
gMoveDescription_WaterGun:	
	.string "물을 발사하여\n"
	.string "적을 공격$"
	
gMoveDescription_HydroPump:	
	.string "물을 굉장한 기세로\n"
	.string "발사하여 적을 공격$"
	
gMoveDescription_Surf:	
	.string "물에 파도를 일으켜 그것을\n"
	.string "굉장한 힘으로 내려친다$"
	
gMoveDescription_IceBeam:	
	.string "냉기를 발사하여 공격\n"
	.string "적을 얼릴 때가 있다$"
	
gMoveDescription_Blizzard:	
	.string "눈을 강한 바람에 실어서 공격\n"
	.string "적을 얼릴 때가 있다$"
	
gMoveDescription_Psybeam:	
	.string "이상한 빛을 발사한다\n"
	.string "적을 혼란시킬 때가 있다$"
	
gMoveDescription_BubbleBeam:	
	.string "거품을 기세 좋게 발사한다\n"
	.string "적의 스피드를 떨어뜨릴 때가 있다$"
	
gMoveDescription_AuroraBeam:	
	.string "무지개색의 빛을 발사한다\n"
	.string "공격을 떨어뜨릴 때가 있다$"
	
gMoveDescription_HyperBeam:	
	.string "데미지는 크지만 사용하면\n"
	.string "다음 턴은 움직일 수 없게 되어버린다$"
	
gMoveDescription_Peck:	
	.string "부리 등으로\n"
	.string "적을 쪼아서 공격$"
	
gMoveDescription_DrillPeck:	
	.string "부리를 중심으로 몸을\n"
	.string "회전시켜서 적에게 돌진한다$"
	
gMoveDescription_Submission:	
	.string "자신과 함께 땅에 내던진다\n"
	.string "자신도 조금 데미지를 입는다$"
	
gMoveDescription_LowKick:	
	.string "무거운 포켓몬에게는 더\n"
	.string "큰 데미지를 준다$"
	
gMoveDescription_Counter:	
	.string "적으로부터 받은 물리공격의\n"
	.string "데미지를 배로 만들어 돌려준다$"
	
gMoveDescription_SeismicToss:	
	.string "인력을 이용해 내던진다\n"
	.string "레벨만큼의 데미지를 준다$"
	
gMoveDescription_Strength:	
	.string "전신에 굉장한 힘을 담아서\n"
	.string "적을 공격$"
	
gMoveDescription_Absorb:	
	.string "적에게 입힌 데미지의\n"
	.string "절반에 해당하는 체력을 회복한다$"
	
gMoveDescription_MegaDrain:	
	.string "적에게 입힌 데미지의\n"
	.string "절반에 해당하는 체력을 회복한다$"
	
gMoveDescription_LeechSeed:	
	.string "적의 몸에 씨를 뿌려서\n"
	.string "턴마다 체력을 흡수한다$"
	
gMoveDescription_Growth:	
	.string "일시에 몸을 성장시켜\n"
	.string "특수공격을 올린다$"
	
gMoveDescription_RazorLeaf:	
	.string "잎사귀로 적을 벤다\n"
	.string "급소에 맞기 쉽다$"
	
gMoveDescription_SolarBeam:	
	.string "1턴째에 빛을 흡수\n"
	.string "다음 턴에 적을 공격$"
	
gMoveDescription_PoisonPowder:	
	.string "독소를 품은 가루를 흩뿌려서\n"
	.string "적에게 독을 준다$"
	
gMoveDescription_StunSpore:	
	.string "저리 가루를 흩뿌려서\n"
	.string "적을 마비시켜 버린다$"
	
gMoveDescription_SleepPowder:	
	.string "잠이 오는 가루를 흩뿌려서\n"
	.string "적을 잠들게 해버린다$"
	
gMoveDescription_PetalDance:	
	.string "2-3턴 동안 난동부린다\n"
	.string "난동부린 뒤에는 혼란에 빠져버린다$"
	
gMoveDescription_StringShot:	
	.string "실을 적의 몸에 휘감아서\n"
	.string "스피드를 떨어뜨리게 한다$"
	
gMoveDescription_DragonRage:	
	.string "충격파로 적을 공격\n"
	.string "언제나 40의 데미지를 준다$"
	
gMoveDescription_FireSpin:	
	.string "2-5턴 동안 적을\n"
	.string "불꽃의 중심에 가둔다$"
	
gMoveDescription_ThunderShock:	
	.string "전격을 날려서 공격\n"
	.string "적을 마비시킬 때가 있다$"
	
gMoveDescription_Thunderbolt:	
	.string "강한 전격을 날려서 공격\n"
	.string "적을 마비시킬 때가 있다$"
	
gMoveDescription_ThunderWave:	
	.string "약한 전격을 적에게 던져서\n"
	.string "마비시켜 버린다$"
	
gMoveDescription_Thunder:	
	.string "적을 향해 번개를 떨어뜨린다\n"
	.string "마비시킬 때가 있다$"
	
gMoveDescription_RockThrow:	
	.string "작은 바위를 내던져서\n"
	.string "적을 공격$"
	
gMoveDescription_Earthquake:	
	.string "땅을 흔들어서 공격\n"
	.string "날고 있는 포켓몬 이외에 큰 데미지$"
	
gMoveDescription_Fissure:	
	.string "땅을 갈라서 적을 삼킨다\n"
	.string "삼켜지면 전투불능이 된다$"
	
gMoveDescription_Dig:	
	.string "1턴째에 땅으로 파고들어\n"
	.string "다음 턴에 적을 공격$"
	
gMoveDescription_Toxic:	
	.string "서서히 데미지가 증가하는 독을\n"
	.string "적에게 준다$"
	
gMoveDescription_Confusion:	
	.string "초능력으로 공격\n"
	.string "적을 혼란시킬 때가 있다$"
	
gMoveDescription_Psychic:	
	.string "강한 염동력으로 적을 공격\n"
	.string "특수방어를 떨어뜨릴 때가 있다$"
	
gMoveDescription_Hypnosis:	
	.string "적에게 암시를 걸어서\n"
	.string "깊은 잠으로 유도한다$"
	
gMoveDescription_Meditate:	
	.string "요가포즈로 잠든 힘을\n"
	.string "끌어내어 공격을 올린다$"
	
gMoveDescription_Agility:	
	.string "힘을 빼고 몸을 가볍게 해서\n"
	.string "스피드를 크게 올린다$"
	
gMoveDescription_QuickAttack:	
	.string "굉장한 속도로 움직여서\n"
	.string "선제공격한다$"
	
gMoveDescription_Rage:	
	.string "공격을 받았을 때 분노로\n"
	.string "공격이 오른다$"
	
gMoveDescription_Teleport:	
	.string "초능력을 사용해\n"
	.string "배틀에서 탈출한다$"
	
gMoveDescription_NightShade:	
	.string "적에게 무시무시한 환상을 보게 해\n"
	.string "레벨만큼의 데미지를 준다$"
	
gMoveDescription_Mimic:	
	.string "적이 사용한 기술이\n"
	.string "그때에만 자신의 기술이 된다$"
	
gMoveDescription_Screech:	
	.string "싫은 소리를 내어 적의\n"
	.string "방어를 크게 떨어뜨리게 한다$"
	
gMoveDescription_DoubleTeam:	
	.string "분신으로 적을 혼란시켜\n"
	.string "회피율을 올린다$"
	
gMoveDescription_Recover:	
	.string "상처 입은 몸을 체력의\n"
	.string "절반만큼 회복한다$"
	
gMoveDescription_Harden:	
	.string "전신에 힘을 담아 단단하게 해\n"
	.string "방어를 올린다$"
	
gMoveDescription_Minimize:	
	.string "몸을 축소하여 작아짐으로써\n"
	.string "회피율을 올린다$"
	
gMoveDescription_Smokescreen:	
	.string "연기나 먹물 등으로 적의\n"
	.string "명중률을 떨어뜨리게 한다$"
	
gMoveDescription_ConfuseRay:	
	.string "이상한 빛으로 적을\n"
	.string "당황하게 해서 혼란시켜 버린다$"
	
gMoveDescription_Withdraw:	
	.string "단단한 껍질에 숨어\n"
	.string "방어를 올린다$"
	
gMoveDescription_DefenseCurl:	
	.string "몸을 둥글게 해 급소를\n"
	.string "숨김으로써 방어를 올린다$"
	
gMoveDescription_Barrier:	
	.string "눈앞에 장막을 만들어\n"
	.string "방어를 크게 올린다$"
	
gMoveDescription_LightScreen:	
	.string "빛의 장막을 만들어\n"
	.string "특수공격의 데미지를 약하게 한다$"
	
gMoveDescription_Haze:	
	.string "흑안개에 덮여 능력의\n"
	.string "이상을 원래대로 돌린다$"
	
gMoveDescription_Reflect:	
	.string "장막을 만들어 물리공격의\n"
	.string "데미지를 약하게 한다$"
	
gMoveDescription_FocusEnergy:	
	.string "공격에 기합을 넣어\n"
	.string "급소에 맞기 쉬워진다$"
	
gMoveDescription_Bide:	
	.string "2턴 공격을 견뎌\n"
	.string "받은 데미지를 배로 되돌려준다$"
	
gMoveDescription_Metronome:	
	.string "손가락을 흔들어 뇌를 자극해서\n"
	.string "여러 기술을 랜덤으로 날린다$"
	
gMoveDescription_MirrorMove:	
	.string "적의 기술을 흉내 내어\n"
	.string "똑같은 기술로 적을 공격$"
	
gMoveDescription_SelfDestruct:	
	.string "적에게 큰 데미지를 주지만\n"
	.string "쓰고 나서 전투불능이 된다$"
	
gMoveDescription_EggBomb:	
	.string "알을 있는 힘껏 내던져서\n"
	.string "적을 공격$"
	
gMoveDescription_Lick:	
	.string "긴 혀로 핥아서 공격\n"
	.string "적을 마비시킬 때가 있다$"
	
gMoveDescription_Smog:	
	.string "배기가스를 내뿜어 공격\n"
	.string "적에게 독을 줄 때가 있다$"
	
gMoveDescription_Sludge:	
	.string "오물을 내던져서 공격\n"
	.string "적에게 독을 줄 때가 있다$"
	
gMoveDescription_BoneClub:	
	.string "손에 들고 있는 뼈로 적을 공격\n"
	.string "적을 풀죽게 만들 때가 있다$"
	
gMoveDescription_FireBlast:	
	.string "큰 문자가 모든 것을 불태운다\n"
	.string "적을 화상 입힐 때가 있다$"
	
gMoveDescription_Waterfall:	
	.string "폭포를 거슬러 올라갈 듯한 기세로\n"
	.string "적에게 돌진한다$"
	
gMoveDescription_Clamp:	
	.string "2-5턴 동안 적을\n"
	.string "껍질에 끼워버린다$"
	
gMoveDescription_Swift:	
	.string "절대 피할 수 없는 별 모양의\n"
	.string "광선을 무수히 발사한다$"
	
gMoveDescription_SkullBash:	
	.string "1턴째에 머리를 움츠리고\n"
	.string "다음 턴에 적을 공격$"
	
gMoveDescription_SpikeCannon:	
	.string "날카로운 침을 적에게 발사해서\n"
	.string "2-5회 연속으로 공격$"
	
gMoveDescription_Constrict:	
	.string "적을 휘감아서 공격한다\n"
	.string "적의 스피드를 떨어뜨릴 때가 있다$"
	
gMoveDescription_Amnesia:	
	.string "순간적으로 무언가를 잊어버림으로써\n"
	.string "특수방어를 크게 올린다$"
	
gMoveDescription_Kinesis:	
	.string "적의 눈을 숟가락으로 향하게 하여\n"
	.string "명중률을 낮추게 한다$"
	
gMoveDescription_SoftBoiled:	
	.string "상처 입은 몸을 체력의\n"
	.string "절반만큼 회복한다$"
	
gMoveDescription_HiJumpKick:	
	.string "점프한 기세로 무릎차기를\n"
	.string "날린다 빗나가면 데미지를 입는다$"
	
gMoveDescription_Glare:	
	.string "배의 무늬로 적을 위협해\n"
	.string "겁을 주어서 마비시켜 버린다$"
	
gMoveDescription_DreamEater:	
	.string "잠자고 있는 적에게 준 데미지의\n"
	.string "절반만큼 체력을 회복한다$"
	
gMoveDescription_PoisonGas:	
	.string "독가스를 적에게 내뿜어\n"
	.string "독을 준다$"
	
gMoveDescription_Barrage:	
	.string "둥근 것을 적에게 내던져서\n"
	.string "2-5회 연속으로 공격$"
	
gMoveDescription_LeechLife:	
	.string "적에게 준 데미지의\n"
	.string "절반만큼 체력을 회복한다$"
	
gMoveDescription_LovelyKiss:	
	.string "무서운 얼굴로 키스한다\n"
	.string "키스당하면 잠들어 버린다$"
	
gMoveDescription_SkyAttack:	
	.string "1턴째에 약점을 찾고\n"
	.string "다음 턴에 적을 공격$"
	
gMoveDescription_Transform:	
	.string "적의 포켓몬과 똑같은 모습으로\n"
	.string "세포를 변화시켜 변신한다$"
	
gMoveDescription_Bubble:	
	.string "거품을 내뿜어 공격\n"
	.string "적의 스피드를 떨어뜨릴 때가 있다$"
	
gMoveDescription_DizzyPunch:	
	.string "리드미컬한 펀치로 공격\n"
	.string "적을 혼란시킬 때가 있다$"
	
gMoveDescription_Spore:	
	.string "최면 효과가 있는 포자를\n"
	.string "흩뿌려서 적을 잠재운다$"
	
gMoveDescription_Flash:	
	.string "강한 빛으로 눈을 부시게 해\n"
	.string "적의 명중률을 떨어뜨리게 한다$"
	
gMoveDescription_Psywave:	
	.string "이상한 염력파로 적을 공격\n"
	.string "사용할 때마다 위력이 바뀐다$"
	
gMoveDescription_Splash:	
	.string "튈 뿐 아무 일도 일어나지 않는다...\n"
	.string "$"
	
gMoveDescription_AcidArmor:	
	.string "몸을 액체로 변화시켜\n"
	.string "방어를 크게 올린다$"
	
gMoveDescription_Crabhammer:	
	.string "집게를 적에게 내리친다\n"
	.string "급소에 맞기 쉽다$"
	
gMoveDescription_Explosion:	
	.string "적에게 큰 데미지를 주지만\n"
	.string "쓰면 전투불능이 된다$"
	
gMoveDescription_FurySwipes:	
	.string "날카로운 손톱이나 낫 등으로 할퀴어서\n"
	.string "2-5회 연속으로 공격$"
	
gMoveDescription_Bonemerang:	
	.string "뼈를 날려서 날아갈 때와 돌아올 때\n"
	.string "2회 연속으로 공격$"
	
gMoveDescription_Rest:	
	.string "2턴 잠자서 체력과\n"
	.string "몸의 이상을 회복한다$"
	
gMoveDescription_RockSlide:	
	.string "큰 바위를 날린다\n"
	.string "적을 풀죽게 만들 때가 있다$"
	
gMoveDescription_HyperFang:	
	.string "날카로운 앞니로 적을 공격\n"
	.string "풀죽게 만들 때가 있다$"
	
gMoveDescription_Sharpen:	
	.string "폴리곤을 줄여 각지게 되어서\n"
	.string "공격을 올린다$"
	
gMoveDescription_Conversion:	
	.string "배운 기술의 타입 중\n"
	.string "어느 하나로 자신의 타입을 바꾼다$"
	
gMoveDescription_TriAttack:	
	.string "3종류의 광선을\n"
	.string "1개로 엮어서 적에게 발사한다$"
	
gMoveDescription_SuperFang:	
	.string "날카로운 앞니로 공격해서\n"
	.string "적의 체력을 절반으로 만든다$"
	
gMoveDescription_Slash:	
	.string "날카로운 낫이나 손톱 등으로 공격\n"
	.string "급소에 맞기 쉽다$"
	
gMoveDescription_Substitute:	
	.string "체력의 4분의 1을 써서\n"
	.string "자신의 분신을 낸다$"
	
gMoveDescription_Struggle:	
	.string "기술 포인트가 없어지면 쓰는 기술\n"
	.string "자신도 조금 데미지를 입는다$"
	
gMoveDescription_Sketch:	
	.string "적이 쓴 기술을 스케치해서\n"
	.string "그 기술을 자신의 것으로 만든다$"
	
gMoveDescription_TripleKick:	
	.string "적을 3회 연속으로 공격\n"
	.string "맞을 때마다 데미지가 올라간다$"
	
gMoveDescription_Thief:	
	.string "공격이 끝날 때 틈을 봐서\n"
	.string "적이 가지고 있는 도구를 훔친다$"
	
gMoveDescription_SpiderWeb:	
	.string "끈적끈적한 실을 휘감아\n"
	.string "적을 도망칠 수 없게 해버린다$"
	
gMoveDescription_MindReader:	
	.string "적의 움직임을 마음으로 읽고\n"
	.string "다음 공격을 반드시 명중시킨다$"
	
gMoveDescription_Nightmare:	
	.string "적이 잠든 동안 체력을\n"
	.string "매 턴마다 4분의 1씩 떨어뜨려 간다$"
	
gMoveDescription_FlameWheel:	
	.string "불꽃을 둘러 돌진한다\n"
	.string "적을 화상 입힐 때가 있다$"
	
gMoveDescription_Snore:	
	.string "잠들어 있을 때만 쓸 수 있는 기술\n"
	.string "굉장한 기세로 적을 공격$"
	
gMoveDescription_Curse:	
	.string "고스트타입일 때와 그 이외일 때는\n"
	.string "기술의 효과가 다르다$"
	
gMoveDescription_Flail:	
	.string "자신의 체력이 적을수록\n"
	.string "적에게 큰 데미지를 준다$"
	
gMoveDescription_Conversion2:	
	.string "받은 기술의 타입을 자신의\n"
	.string "저항력으로 바꾼다$"
	
gMoveDescription_Aeroblast:	
	.string "진공파를 발사하여 공격\n"
	.string "급소에 맞기 쉽다$"
	
gMoveDescription_CottonSpore:	
	.string "포자를 착 달라붙게 해서 적의\n"
	.string "스피드를 크게 떨어뜨린다$"
	
gMoveDescription_Reversal:	
	.string "자신의 체력이 적을수록\n"
	.string "적에게 큰 데미지를 준다$"
	
gMoveDescription_Spite:	
	.string "상대가 쓴 기술에 원망을 품어\n"
	.string "그 기술 포인트를 줄여버린다$"
	
gMoveDescription_PowderSnow:	
	.string "눈을 바람에 실어서 공격\n"
	.string "적을 얼릴 때가 있다$"
	
gMoveDescription_Protect:	
	.string "그 턴의 공격을 받지 않는다\n"
	.string "연속으로 쓰면 실패하기 쉽다$"
	
gMoveDescription_MachPunch:	
	.string "굉장한 속도로 펀치를 날려서\n"
	.string "선제공격한다$"
	
gMoveDescription_ScaryFace:	
	.string "무서운 얼굴로 적을 겁주어\n"
	.string "스피드를 크게 떨어뜨린다$"
	
gMoveDescription_FaintAttack:	
	.string "적을 방심시켜 다가가\n"
	.string "피할 수 없는 공격을 날린다$"
	
gMoveDescription_SweetKiss:	
	.string "귀여운 얼굴로 키스를 날린다\n"
	.string "키스당하면 혼란에 빠져버린다$"
	
gMoveDescription_BellyDrum:	
	.string "자신의 체력을 깎고\n"
	.string "공격을 최대치까지 올린다$"
	
gMoveDescription_SludgeBomb:	
	.string "오물을 내던져서 공격\n"
	.string "적에게 독을 줄 때가 있다$"
	
gMoveDescription_MudSlap:	
	.string "적의 얼굴 등에 진흙을 내던져서\n"
	.string "명중률을 떨어뜨리게 한다$"
	
gMoveDescription_Octazooka:	
	.string "먹물 덩어리를 발사하여\n"
	.string "명중률을 떨어뜨리게 한다$"
	
gMoveDescription_Spikes:	
	.string "적의 발밑에 함정을 설치해\n"
	.string "교체한 적에게 데미지를 준다$"
	
gMoveDescription_ZapCannon:	
	.string "맞추기 어렵지만 데미지는 크다\n"
	.string "맞추면 반드시 마비시킨다$"
	
gMoveDescription_Foresight:	
	.string "기술을 맞추기 어려워진 적에게\n"
	.string "공격을 줄 수 있게 된다$"
	
gMoveDescription_DestinyBond:	
	.string "이 기술을 쓴 뒤에 쓰러지면\n"
	.string "적도 전투불능이 된다$"
	
gMoveDescription_PerishSong:	
	.string "들은 포켓몬은 3턴 후에\n"
	.string "전투불능이 된다$"
	
gMoveDescription_IcyWind:	
	.string "굉장한 냉기를 적을 공격\n"
	.string "스피드를 떨어뜨리게 한다$"
	
gMoveDescription_Detect:	
	.string "적의 공격을 반드시 피한다\n"
	.string "연속으로 쓰면 실패하기 쉽다$"
	
gMoveDescription_BoneRush:	
	.string "손에 들고 있는 뼈로 2-5회\n"
	.string "연속으로 적을 공격$"
	
gMoveDescription_LockOn:	
	.string "적에게 조준을 맞춰서\n"
	.string "다음 공격을 반드시 명중시킨다$"
	
gMoveDescription_Outrage:	
	.string "2-3턴 동안 난동부린다\n"
	.string "난동부린 뒤에는 혼란에 빠진다$"
	
gMoveDescription_Sandstorm:	
	.string "모래바람을 발생시켜\n"
	.string "매 턴마다 데미지를 준다$"
	
gMoveDescription_GigaDrain:	
	.string "적에게 준 데미지의\n"
	.string "절반만큼의 체력을 회복한다$"
	
gMoveDescription_Endure:	
	.string "그 턴 공격을 받아도\n"
	.string "반드시 체력이 1 남는다$"
	
gMoveDescription_Charm:	
	.string "귀엽게 바라보고 적을 방심시켜\n"
	.string "공격을 크게 떨어뜨린다$"
	
gMoveDescription_Rollout:	
	.string "5턴 동안 적을 공격\n"
	.string "맞을 때마다 데미지가 올라간다$"
	
gMoveDescription_FalseSwipe:	
	.string "반드시 체력이 1 남도록\n"
	.string "조절하여 공격$"
	
gMoveDescription_Swagger:	
	.string "적을 화내게 해서 혼란시키지만\n"
	.string "공격도 크게 올라가버린다$"
	
gMoveDescription_MilkDrink:	
	.string "상처 입은 몸을 체력의\n"
	.string "절반만큼 회복한다$"
	
gMoveDescription_Spark:	
	.string "전기를 둘러 돌진한다\n"
	.string "적을 마비시킬 때가 있다$"
	
gMoveDescription_FuryCutter:	
	.string "기술을 맞힐 때마다\n"
	.string "위력이 점점 커져간다$"
	
gMoveDescription_SteelWing:	
	.string "단단한 날개를 크게 펼쳐\n"
	.string "그대로 적에게 맞힌다$"
	
gMoveDescription_MeanLook:	
	.string "적을 지긋이 바라보면 어째선가\n"
	.string "적이 도망가지 않게 되어버린다$"
	
gMoveDescription_Attract:	
	.string "수컷은 암컷에게, 암컷은 수컷에게\n"
	.string "기술을 쓰기 어려워진다$"
	
gMoveDescription_SleepTalk:	
	.string "잠들어 있을 때만 쓸 수 있는 기술\n"
	.string "랜덤으로 자신의 기술을 날린다$"
	
gMoveDescription_HealBell:	
	.string "기분 좋은 방울소리를 들려주어\n"
	.string "모든 상태 이상을 회복한다$"
	
gMoveDescription_Return:	
	.string "잘해 주는 트레이너를 위해\n"
	.string "전력으로 적을 공격$"
	
gMoveDescription_Present:	
	.string "적에게 폭탄을 선물한다\n"
	.string "가끔 회복시켜버릴 때도 있다$"
	
gMoveDescription_Frustration:	
	.string "애처로운 처사의 화풀이로\n"
	.string "적을 전력으로 공격$"
	
gMoveDescription_Safeguard:	
	.string "이상한 힘으로 보호받아\n"
	.string "특수 상태 이상이 되지 않는다$"
	
gMoveDescription_PainSplit:	
	.string "적과 자신의 체력을\n"
	.string "더한 것을 사이좋게 나눈다$"
	
gMoveDescription_SacredFire:	
	.string "신비로운 불꽃으로 공격\n"
	.string "적을 화상 입힐 때가 있다$"
	
gMoveDescription_Magnitude:	
	.string "땅을 흔들어서 적을 공격\n"
	.string "데미지는 랜덤하게 바뀐다$"
	
gMoveDescription_DynamicPunch:	
	.string "맞추기 어렵지만 데미지는 크다\n"
	.string "맞추면 반드시 혼란시킨다$"
	
gMoveDescription_Megahorn:	
	.string "단단한 뿔을 굉장한 기세로\n"
	.string "꿰찔러서 공격$"
	
gMoveDescription_DragonBreath:	
	.string "입에서 굉장한 숨결을 내뿜어\n"
	.string "적을 공격$"
	
gMoveDescription_BatonPass:	
	.string "추가 효과를 남긴 채로\n"
	.string "다른 포켓몬과 교체한다$"
	
gMoveDescription_Encore:	
	.string "적이 마지막으로 사용한 기술을\n"
	.string "2-6회 연속으로 쓰게 한다$"
	
gMoveDescription_Pursuit:	
	.string "상대가 교체할 때\n"
	.string "쓰면 큰 데미지를 준다$"
	
gMoveDescription_RapidSpin:	
	.string "몸을 빠르게 회전시켜\n"
	.string "적을 공격$"
	
gMoveDescription_SweetScent:	
	.string "달콤한 향기로 주의를 돌려\n"
	.string "적의 회피율을 떨어뜨리게 한다$"
	
gMoveDescription_IronTail:	
	.string "단단한 꼬리로 적을 공격\n"
	.string "적의 방어를 떨어뜨릴 때가 있다$"
	
gMoveDescription_MetalClaw:	
	.string "단단한 발톱으로 적을 공격\n"
	.string "공격이 올라갈 때도 있다$"
	
gMoveDescription_VitalThrow:	
	.string "나중에 공격하게 되지만 반드시\n"
	.string "공격이 맞는다$"
	
gMoveDescription_MorningSun:	
	.string "체력을 회복한다\n"
	.string "날씨에 따라 회복량이 변한다$"
	
gMoveDescription_Synthesis:	
	.string "체력을 회복한다\n"
	.string "날씨에 따라 회복량이 변한다$"
	
gMoveDescription_Moonlight:	
	.string "체력을 회복한다\n"
	.string "날씨에 따라 회복량이 변한다$"
	
gMoveDescription_HiddenPower:	
	.string "포켓몬에 따라 적에게 주는\n"
	.string "데미지량이 변한다$"
	
gMoveDescription_CrossChop:	
	.string "양손으로 당수를 쳐서 적을 공격\n"
	.string "급소에 맞기 쉽다$"
	
gMoveDescription_Twister:	
	.string "굉장한 바람을 일으켜\n"
	.string "적을 공격$"
	
gMoveDescription_RainDance:	
	.string "5턴 동안 물타입\n"
	.string "기술의 위력이 올라간다$"
	
gMoveDescription_SunnyDay:	
	.string "5턴 동안 불타입\n"
	.string "기술의 위력이 올라간다$"
	
gMoveDescription_Crunch:	
	.string "날카로운 이빨로 적을 깨문다\n"
	.string "특수방어를 떨어뜨릴 때가 있다$"
	
gMoveDescription_MirrorCoat:	
	.string "적에게 받은 특수공격의\n"
	.string "데미지를 배로 만들어 돌려준다$"
	
gMoveDescription_PsychUp:	
	.string "적에게 걸린 보조 효과를\n"
	.string "자신에게도 건다$"
	
gMoveDescription_ExtremeSpeed:	
	.string "굉장한 속도로 움직여서\n"
	.string "힘차게 공격한다$"
	
gMoveDescription_AncientPower:	
	.string "원시의 힘을 눈뜨게 한다\n"
	.string "능력이 오를 때가 있다$"
	
gMoveDescription_ShadowBall:	
	.string "까만 덩어리를 내던져서 공격\n"
	.string "특수방어를 떨어뜨릴 때가 있다$"
	
gMoveDescription_FutureSight:	
	.string "정신력을 높여\n"
	.string "2턴 후에 적을 공격한다$"
	
gMoveDescription_RockSmash:	
	.string "바위를 깨는 듯한 기세로 공격\n"
	.string "적의 방어를 떨어뜨릴 때가 있다$"
	
gMoveDescription_Whirlpool:	
	.string "2-5턴 동안 적을\n"
	.string "소용돌이의 중심에 가두어 공격$"
	
gMoveDescription_BeatUp:	
	.string "동료 포켓몬이\n"
	.string "공격에 참가해 준다$"
	
gMoveDescription_FakeOut:	
	.string "선제공격으로 풀죽게 한다\n"
	.string "처음 턴 이외에는 쓸 수 없다$"
	
gMoveDescription_Uproar:	
	.string "2-5턴 동안 소란피워서\n"
	.string "아무도 잠들지 않는다$"
	
gMoveDescription_Stockpile:	
	.string "최대 3회까지\n"
	.string "힘을 비축한다$"
	
gMoveDescription_SpitUp:	
	.string "비축된 힘으로 토해낸다\n"
	.string "횟수로 데미지가 변한다$"
	
gMoveDescription_Swallow:	
	.string "비축된 힘을 삼킨다\n"
	.string "체력을 회복한다$"
	
gMoveDescription_HeatWave:	
	.string "뜨거운 숨결을 상대에게 내뿜는다\n"
	.string "적을 화상 입힐 때가 있다$"
	
gMoveDescription_Hail:	
	.string "싸라기눈을 내려\n"
	.string "매 턴마다 데미지를 준다$"
	
gMoveDescription_Torment:	
	.string "상대에게 트집을 잡아 똑같은 기술을\n"
	.string "연속으로 쓸 수 없게 한다$"
	
gMoveDescription_Flatter:	
	.string "적을 부추겨서 혼란시키지만\n"
	.string "특수공격도 올려버린다$"
	
gMoveDescription_WillOWisp:	
	.string "도깨비같은 불로\n"
	.string "적을 화상 입힌다$"
	
gMoveDescription_Memento:	
	.string "자신은 기절하게 되지만\n"
	.string "상대의 능력이 떨어진다$"
	
gMoveDescription_Facade:	
	.string "독, 마비, 화상일 때\n"
	.string "공격의 위력이 올라간다$"
	
gMoveDescription_FocusPunch:	
	.string "위력이 높은 고급 기술\n"
	.string "공격을 받으면 풀죽는다$"
	
gMoveDescription_SmellingSalt:	
	.string "마비된 상대에게 큰 데미지\n"
	.string "그 대신에 마비가 낫는다$"
	
gMoveDescription_FollowMe:	
	.string "상대를 자신에게 주목시켜\n"
	.string "공격을 전부 자신이 받는다$"
	
gMoveDescription_NaturePower:	
	.string "자연의 힘을 빌려서 공격\n"
	.string "장소에 따라 나오는 기술이 바뀐다$"
	
gMoveDescription_Charge:	
	.string "전기를 비축함으로써\n"
	.string "다음에만 전기의 위력을 올린다$"
	
gMoveDescription_Taunt:	
	.string "상대를 도발해 혼란시킨다\n"
	.string "상대는 공격만 할 수 있게 된다$"
	
gMoveDescription_HelpingHand:	
	.string "도움받은 상대는\n"
	.string "기술의 위력이 올라간다$"
	
gMoveDescription_Trick:	
	.string "트릭을 써서\n"
	.string "도구를 교환해버린다$"
	
gMoveDescription_RolePlay:	
	.string "상대의 역할을 하여 상대의\n"
	.string "특성을 베낀다$"
	
gMoveDescription_Wish:	
	.string "소원을 빌어 회복한다\n"
	.string "이룰 때까지는 조금 걸린다$"
	
gMoveDescription_Assist:	
	.string "같은 편 포켓몬의 기술로 공격\n"
	.string "어느 기술이 나올지는 알 수 없다$"
	
gMoveDescription_Ingrain:	
	.string "뿌리를 박아 조금씩 회복한다\n"
	.string "뿌리 박고 있으므로 교체할 수 없다$"
	
gMoveDescription_Superpower:	
	.string "엄청난 힘을 발휘하지만\n"
	.string "지쳐서 능력이 떨어진다$"
	
gMoveDescription_MagicCoat:	
	.string "특수한 기술의 효과를\n"
	.string "되받아쳐서 상대에게 걸어버린다$"
	
gMoveDescription_Recycle:	
	.string "한 번 사용해버린 도구를\n"
	.string "다시 한 번 사용할 수 있다$"
	
gMoveDescription_Revenge:	
	.string "상대에게 데미지를 받으면\n"
	.string "위력이 올라간다$"
	
gMoveDescription_BrickBreak:	
	.string "리플렉터 등을 부숴서\n"
	.string "상대에게 데미지를 준다$"
	
gMoveDescription_Yawn:	
	.string "하품으로 유도해 다음 턴에\n"
	.string "상대가 잠듦 상태가 된다$"
	
gMoveDescription_KnockOff:	
	.string "상대의 도구를 탁 쳐서 떨어뜨려\n"
	.string "끝날 때까지 사용할 수 없게 한다$"
	
gMoveDescription_Endeavor:	
	.string "자신의 체력이 상대보다\n"
	.string "적은 만큼 데미지를 준다$"
	
gMoveDescription_Eruption:	
	.string "자신의 체력이 많을수록\n"
	.string "큰 데미지를 준다$"
	
gMoveDescription_SkillSwap:	
	.string "서로의 특성을\n"
	.string "바꿀 수 있다$"
	
gMoveDescription_Imprison:	
	.string "자신이 기억하고 있는 기술을\n"
	.string "상대는 사용할 수 없게 된다$"
	
gMoveDescription_Refresh:	
	.string "독, 마비, 화상 상태를\n"
	.string "치료해버린다$"
	
gMoveDescription_Grudge:	
	.string "적의 기술로 기절하면\n"
	.string "그 기술의 포인트를 0으로 만든다$"
	
gMoveDescription_Snatch:	
	.string "상대가 사용하려고 한 기술을\n"
	.string "빼앗아 자신에게 써버린다$"
	
gMoveDescription_SecretPower:	
	.string "비밀의 힘을 일깨운다\n"
	.string "장소에 따라 추가 효과가 다르다$"
	
gMoveDescription_Dive:	
	.string "1턴째에 물로 잠수했다가\n"
	.string "다음 턴에 적을 공격$"
	
gMoveDescription_ArmThrust:	
	.string "2-5회 연속으로 번갈아 쳐서\n"
	.string "적을 공격$"
	
gMoveDescription_Camouflage:	
	.string "장소에 맞춰서\n"
	.string "포켓몬의 타입이 변한다$"
	
gMoveDescription_TailGlow:	
	.string "빛을 깜빡거리게 해서\n"
	.string "특수공격을 크게 올린다$"
	
gMoveDescription_LusterPurge:	
	.string "빛을 방출하여 공격\n"
	.string "특수방어를 떨어뜨릴 때가 있다$"
	
gMoveDescription_MistBall:	
	.string "안개의 깃털로 공격\n"
	.string "특수방어를 떨어뜨릴 때가 있다$"
	
gMoveDescription_FeatherDance:	
	.string "깃털을 흩뿌려 휘감아서\n"
	.string "공격을 크게 떨어뜨린다$"
	
gMoveDescription_TeeterDance:	
	.string "모든 포켓몬을\n"
	.string "혼란 상태로 만든다$"
	
gMoveDescription_BlazeKick:	
	.string "급소에 맞기 쉽다\n"
	.string "가끔 화상 상태로 만든다$"
	
gMoveDescription_MudSport:	
	.string "진흙투성이가 돼서\n"
	.string "전기타입의 데미지를 줄인다$"
	
gMoveDescription_IceBall:	
	.string "5턴 동안 적을 공격\n"
	.string "맞을 때마다 데미지가 올라간다$"
	
gMoveDescription_NeedleArm:	
	.string "바늘투성이인 팔로 힘껏 쳐서 공격\n"
	.string "적을 풀죽게 만들 때가 있다$"
	
gMoveDescription_SlackOff:	
	.string "게으름 피워서 몸의 체력을\n"
	.string "절반만큼 회복한다$"
	
gMoveDescription_HyperVoice:	
	.string "큰 소리의 진동으로\n"
	.string "적에게 데미지를 준다$"
	
gMoveDescription_PoisonFang:	
	.string "날카로운 이빨로 공격\n"
	.string "가끔 맹독 상태로 만든다$"
	
gMoveDescription_CrushClaw:	
	.string "날카로운 손톱으로 적을 베어 가른다\n"
	.string "방어를 떨어뜨릴 때가 있다$"
	
gMoveDescription_BlastBurn:	
	.string "데미지는 크지만 사용하면\n"
	.string "다음 턴은 움직일 수 없게 되어버린다$"
	
gMoveDescription_HydroCannon:	
	.string "데미지는 크지만 사용하면\n"
	.string "다음 턴은 움직일 수 없게 되어버린다$"
	
gMoveDescription_MeteorMash:	
	.string "혜성과 같은 펀치를 날린다\n"
	.string "공격이 올라갈 때가 있다$"
	
gMoveDescription_Astonish:	
	.string "적을 놀래켜서 공격\n"
	.string "적을 풀죽게 만들 때가 있다$"
	
gMoveDescription_WeatherBall:	
	.string "날씨에 따라서\n"
	.string "타입과 위력이 변한다$"
	
gMoveDescription_Aromatherapy:	
	.string "기분 좋은 향기를 맡게 하여\n"
	.string "모든 상태 이상을 회복한다$"
	
gMoveDescription_FakeTears:	
	.string "우는 척으로 상대를 난처하게 만들어\n"
	.string "특수방어를 크게 떨어뜨리게 한다$"
	
gMoveDescription_AirCutter:	
	.string "날카로운 바람을 일으켜서 공격\n"
	.string "급소에 맞기 쉽다$"
	
gMoveDescription_Overheat:	
	.string "풀 파워로 공격할 수 있지만\n"
	.string "특수공격이 크게 떨어져버린다$"
	
gMoveDescription_OdorSleuth:	
	.string "기술을 맞추기 어려워진 적에게\n"
	.string "공격할 수 있게 된다$"
	
gMoveDescription_RockTomb:	
	.string "바위로 움직임을 막아서 공격\n"
	.string "상대의 스피드도 떨어뜨린다$"
	
gMoveDescription_SilverWind:	
	.string "바람에 날개 가루를 날려서 공격\n"
	.string "능력이 올라갈 때가 있다$"
	
gMoveDescription_MetalSound:	
	.string "싫은 소리를 내서 적의\n"
	.string "특수방어를 크게 떨어뜨리게 한다$"
	
gMoveDescription_GrassWhistle:	
	.string "기분 좋은 풀잎 소리로\n"
	.string "적을 깊은 잠으로 유도한다$"
	
gMoveDescription_Tickle:	
	.string "상대를 간질여 웃게 만들어서\n"
	.string "공격과 방어를 떨어뜨리게 한다$"
	
gMoveDescription_CosmicPower:	
	.string "신비로운 힘으로\n"
	.string "방어와 특수방어를 올린다$"
	
gMoveDescription_WaterSpout:	
	.string "자신의 체력이 많을수록\n"
	.string "큰 데미지를 준다$"
	
gMoveDescription_SignalBeam:	
	.string "이상한 빛을 발사한다\n"
	.string "적을 혼란시킬 때가 있다$"
	
gMoveDescription_ShadowPunch:	
	.string "그림자에 섞여 펀치를 날린다\n"
	.string "적은 절대로 피할 수 없다$"
	
gMoveDescription_Extrasensory:	
	.string "이상한 힘으로 적을 공격\n"
	.string "적을 풀죽게 만들 때가 있다$"
	
gMoveDescription_SkyUppercut:	
	.string "하늘을 향하는 듯한 기세로\n"
	.string "업퍼를 날려서 공격$"
	
gMoveDescription_SandTomb:	
	.string "2-5턴 동안 적을\n"
	.string "소용돌이의 중심에 가두어 공격$"
	
gMoveDescription_SheerCold:	
	.string "절대영도로 적을 덮친다\n"
	.string "맞으면 전투불능이 된다$"
	
gMoveDescription_MuddyWater:	
	.string "흙탕물로 적을 공격\n"
	.string "가끔 명중률을 떨어뜨리게 한다$"
	
gMoveDescription_BulletSeed:	
	.string "씨앗을 2-5회 연속으로\n"
	.string "발사하여 적을 공격$"
	
gMoveDescription_AerialAce:	
	.string "스피드로 농락한다\n"
	.string "적은 절대로 피할 수 없다$"
	
gMoveDescription_IcicleSpear:	
	.string "고드름을 2-5회 연속으로\n"
	.string "발사하여 적을 공격$"
	
gMoveDescription_IronDefense:	
	.string "피부의 표면을 단단하게 해서\n"
	.string "방어를 크게 올린다$"
	
gMoveDescription_Block:	
	.string "도주로를 가로막아\n"
	.string "적을 도망칠 수 없게 해버린다$"
	
gMoveDescription_Howl:	
	.string "짖어서 기합을 높임으로써\n"
	.string "공격을 올린다$"
	
gMoveDescription_DragonClaw:	
	.string "날카로운 발톱을 사용해\n"
	.string "적을 할퀴어서 공격$"
	
gMoveDescription_FrenzyPlant:	
	.string "데미지는 크지만 사용하면\n"
	.string "다음 턴은 움직일 수 없게 되어버린다$"
	
gMoveDescription_BulkUp:	
	.string "몸을 단련해서\n"
	.string "공격과 방어를 올린다$"
	
gMoveDescription_Bounce:	
	.string "1턴째에 뛰어올라 2턴째에\n"
	.string "떨어진다 가끔 적을 풀죽게 만든다$"
	
gMoveDescription_MudShot:	
	.string "진흙을 내던져서 공격\n"
	.string "스피드를 떨어뜨리게 한다$"
	
gMoveDescription_PoisonTail:	
	.string "가끔 독을 줄 때가 있고\n"
	.string "급소에도 맞기 쉽다$"
	
gMoveDescription_Covet:	
	.string "귀엽게 애교 부리며\n"
	.string "적이 지니고 있는 도구를 뺏는다$"
	
gMoveDescription_VoltTackle:	
	.string "목숨을 걸고 적에게 부딪친다\n"
	.string "자신도 조금 데미지를 입는다$"
	
gMoveDescription_MagicalLeaf:	
	.string "절대로 피할 수 없는\n"
	.string "이상한 잎사귀로 적을 공격$"
	
gMoveDescription_WaterSport:	
	.string "흠뻑 젖은 상태가 돼서\n"
	.string "불꽃타입의 데미지를 줄인다$"
	
gMoveDescription_CalmMind:	
	.string "정신을 집중시켜서\n"
	.string "특수공격과 특수방어를 올린다$"
	
gMoveDescription_LeafBlade:	
	.string "뾰족한 잎사귀로 적을 벤다\n"
	.string "급소에 맞기 쉽다$"
	
gMoveDescription_DragonDance:	
	.string "신비로운 춤을 춰서\n"
	.string "공격과 스피드를 올린다$"
	
gMoveDescription_RockBlast:	
	.string "바위를 2-5회 연속으로\n"
	.string "발사하여 적을 공격$"
	
gMoveDescription_ShockWave:	
	.string "재빠르게 전격을 날린다\n"
	.string "적은 절대로 피할 수 없다$"
	
gMoveDescription_WaterPulse:	
	.string "초음파로 적을 공격\n"
	.string "적을 혼란시킬 때가 있다$"
	
gMoveDescription_DoomDesire:	
	.string "많은 양의 빛이 쏟아져서\n"
	.string "2턴 후에 적을 공격한다$"
	
gMoveDescription_PsychoBoost:	
	.string "풀 파워로 공격할 수 있지만\n"
	.string "특수공격이 크게 떨어져버린다$"


	.align 2
gMoveDescriptions:: @ 83C09D8
	.4byte gMoveDescription_Pound
	.4byte gMoveDescription_KarateChop
	.4byte gMoveDescription_DoubleSlap
	.4byte gMoveDescription_CometPunch
	.4byte gMoveDescription_MegaPunch
	.4byte gMoveDescription_PayDay
	.4byte gMoveDescription_FirePunch
	.4byte gMoveDescription_IcePunch
	.4byte gMoveDescription_ThunderPunch
	.4byte gMoveDescription_Scratch
	.4byte gMoveDescription_ViceGrip
	.4byte gMoveDescription_Guillotine
	.4byte gMoveDescription_RazorWind
	.4byte gMoveDescription_SwordsDance
	.4byte gMoveDescription_Cut
	.4byte gMoveDescription_Gust
	.4byte gMoveDescription_WingAttack
	.4byte gMoveDescription_Whirlwind
	.4byte gMoveDescription_Fly
	.4byte gMoveDescription_Bind
	.4byte gMoveDescription_Slam
	.4byte gMoveDescription_VineWhip
	.4byte gMoveDescription_Stomp
	.4byte gMoveDescription_DoubleKick
	.4byte gMoveDescription_MegaKick
	.4byte gMoveDescription_JumpKick
	.4byte gMoveDescription_RollingKick
	.4byte gMoveDescription_SandAttack
	.4byte gMoveDescription_Headbutt
	.4byte gMoveDescription_HornAttack
	.4byte gMoveDescription_FuryAttack
	.4byte gMoveDescription_HornDrill
	.4byte gMoveDescription_Tackle
	.4byte gMoveDescription_BodySlam
	.4byte gMoveDescription_Wrap
	.4byte gMoveDescription_TakeDown
	.4byte gMoveDescription_Thrash
	.4byte gMoveDescription_DoubleEdge
	.4byte gMoveDescription_TailWhip
	.4byte gMoveDescription_PoisonSting
	.4byte gMoveDescription_Twineedle
	.4byte gMoveDescription_PinMissile
	.4byte gMoveDescription_Leer
	.4byte gMoveDescription_Bite
	.4byte gMoveDescription_Growl
	.4byte gMoveDescription_Roar
	.4byte gMoveDescription_Sing
	.4byte gMoveDescription_Supersonic
	.4byte gMoveDescription_SonicBoom
	.4byte gMoveDescription_Disable
	.4byte gMoveDescription_Acid
	.4byte gMoveDescription_Ember
	.4byte gMoveDescription_Flamethrower
	.4byte gMoveDescription_Mist
	.4byte gMoveDescription_WaterGun
	.4byte gMoveDescription_HydroPump
	.4byte gMoveDescription_Surf
	.4byte gMoveDescription_IceBeam
	.4byte gMoveDescription_Blizzard
	.4byte gMoveDescription_Psybeam
	.4byte gMoveDescription_BubbleBeam
	.4byte gMoveDescription_AuroraBeam
	.4byte gMoveDescription_HyperBeam
	.4byte gMoveDescription_Peck
	.4byte gMoveDescription_DrillPeck
	.4byte gMoveDescription_Submission
	.4byte gMoveDescription_LowKick
	.4byte gMoveDescription_Counter
	.4byte gMoveDescription_SeismicToss
	.4byte gMoveDescription_Strength
	.4byte gMoveDescription_Absorb
	.4byte gMoveDescription_MegaDrain
	.4byte gMoveDescription_LeechSeed
	.4byte gMoveDescription_Growth
	.4byte gMoveDescription_RazorLeaf
	.4byte gMoveDescription_SolarBeam
	.4byte gMoveDescription_PoisonPowder
	.4byte gMoveDescription_StunSpore
	.4byte gMoveDescription_SleepPowder
	.4byte gMoveDescription_PetalDance
	.4byte gMoveDescription_StringShot
	.4byte gMoveDescription_DragonRage
	.4byte gMoveDescription_FireSpin
	.4byte gMoveDescription_ThunderShock
	.4byte gMoveDescription_Thunderbolt
	.4byte gMoveDescription_ThunderWave
	.4byte gMoveDescription_Thunder
	.4byte gMoveDescription_RockThrow
	.4byte gMoveDescription_Earthquake
	.4byte gMoveDescription_Fissure
	.4byte gMoveDescription_Dig
	.4byte gMoveDescription_Toxic
	.4byte gMoveDescription_Confusion
	.4byte gMoveDescription_Psychic
	.4byte gMoveDescription_Hypnosis
	.4byte gMoveDescription_Meditate
	.4byte gMoveDescription_Agility
	.4byte gMoveDescription_QuickAttack
	.4byte gMoveDescription_Rage
	.4byte gMoveDescription_Teleport
	.4byte gMoveDescription_NightShade
	.4byte gMoveDescription_Mimic
	.4byte gMoveDescription_Screech
	.4byte gMoveDescription_DoubleTeam
	.4byte gMoveDescription_Recover
	.4byte gMoveDescription_Harden
	.4byte gMoveDescription_Minimize
	.4byte gMoveDescription_Smokescreen
	.4byte gMoveDescription_ConfuseRay
	.4byte gMoveDescription_Withdraw
	.4byte gMoveDescription_DefenseCurl
	.4byte gMoveDescription_Barrier
	.4byte gMoveDescription_LightScreen
	.4byte gMoveDescription_Haze
	.4byte gMoveDescription_Reflect
	.4byte gMoveDescription_FocusEnergy
	.4byte gMoveDescription_Bide
	.4byte gMoveDescription_Metronome
	.4byte gMoveDescription_MirrorMove
	.4byte gMoveDescription_SelfDestruct
	.4byte gMoveDescription_EggBomb
	.4byte gMoveDescription_Lick
	.4byte gMoveDescription_Smog
	.4byte gMoveDescription_Sludge
	.4byte gMoveDescription_BoneClub
	.4byte gMoveDescription_FireBlast
	.4byte gMoveDescription_Waterfall
	.4byte gMoveDescription_Clamp
	.4byte gMoveDescription_Swift
	.4byte gMoveDescription_SkullBash
	.4byte gMoveDescription_SpikeCannon
	.4byte gMoveDescription_Constrict
	.4byte gMoveDescription_Amnesia
	.4byte gMoveDescription_Kinesis
	.4byte gMoveDescription_SoftBoiled
	.4byte gMoveDescription_HiJumpKick
	.4byte gMoveDescription_Glare
	.4byte gMoveDescription_DreamEater
	.4byte gMoveDescription_PoisonGas
	.4byte gMoveDescription_Barrage
	.4byte gMoveDescription_LeechLife
	.4byte gMoveDescription_LovelyKiss
	.4byte gMoveDescription_SkyAttack
	.4byte gMoveDescription_Transform
	.4byte gMoveDescription_Bubble
	.4byte gMoveDescription_DizzyPunch
	.4byte gMoveDescription_Spore
	.4byte gMoveDescription_Flash
	.4byte gMoveDescription_Psywave
	.4byte gMoveDescription_Splash
	.4byte gMoveDescription_AcidArmor
	.4byte gMoveDescription_Crabhammer
	.4byte gMoveDescription_Explosion
	.4byte gMoveDescription_FurySwipes
	.4byte gMoveDescription_Bonemerang
	.4byte gMoveDescription_Rest
	.4byte gMoveDescription_RockSlide
	.4byte gMoveDescription_HyperFang
	.4byte gMoveDescription_Sharpen
	.4byte gMoveDescription_Conversion
	.4byte gMoveDescription_TriAttack
	.4byte gMoveDescription_SuperFang
	.4byte gMoveDescription_Slash
	.4byte gMoveDescription_Substitute
	.4byte gMoveDescription_Struggle
	.4byte gMoveDescription_Sketch
	.4byte gMoveDescription_TripleKick
	.4byte gMoveDescription_Thief
	.4byte gMoveDescription_SpiderWeb
	.4byte gMoveDescription_MindReader
	.4byte gMoveDescription_Nightmare
	.4byte gMoveDescription_FlameWheel
	.4byte gMoveDescription_Snore
	.4byte gMoveDescription_Curse
	.4byte gMoveDescription_Flail
	.4byte gMoveDescription_Conversion2
	.4byte gMoveDescription_Aeroblast
	.4byte gMoveDescription_CottonSpore
	.4byte gMoveDescription_Reversal
	.4byte gMoveDescription_Spite
	.4byte gMoveDescription_PowderSnow
	.4byte gMoveDescription_Protect
	.4byte gMoveDescription_MachPunch
	.4byte gMoveDescription_ScaryFace
	.4byte gMoveDescription_FaintAttack
	.4byte gMoveDescription_SweetKiss
	.4byte gMoveDescription_BellyDrum
	.4byte gMoveDescription_SludgeBomb
	.4byte gMoveDescription_MudSlap
	.4byte gMoveDescription_Octazooka
	.4byte gMoveDescription_Spikes
	.4byte gMoveDescription_ZapCannon
	.4byte gMoveDescription_Foresight
	.4byte gMoveDescription_DestinyBond
	.4byte gMoveDescription_PerishSong
	.4byte gMoveDescription_IcyWind
	.4byte gMoveDescription_Detect
	.4byte gMoveDescription_BoneRush
	.4byte gMoveDescription_LockOn
	.4byte gMoveDescription_Outrage
	.4byte gMoveDescription_Sandstorm
	.4byte gMoveDescription_GigaDrain
	.4byte gMoveDescription_Endure
	.4byte gMoveDescription_Charm
	.4byte gMoveDescription_Rollout
	.4byte gMoveDescription_FalseSwipe
	.4byte gMoveDescription_Swagger
	.4byte gMoveDescription_MilkDrink
	.4byte gMoveDescription_Spark
	.4byte gMoveDescription_FuryCutter
	.4byte gMoveDescription_SteelWing
	.4byte gMoveDescription_MeanLook
	.4byte gMoveDescription_Attract
	.4byte gMoveDescription_SleepTalk
	.4byte gMoveDescription_HealBell
	.4byte gMoveDescription_Return
	.4byte gMoveDescription_Present
	.4byte gMoveDescription_Frustration
	.4byte gMoveDescription_Safeguard
	.4byte gMoveDescription_PainSplit
	.4byte gMoveDescription_SacredFire
	.4byte gMoveDescription_Magnitude
	.4byte gMoveDescription_DynamicPunch
	.4byte gMoveDescription_Megahorn
	.4byte gMoveDescription_DragonBreath
	.4byte gMoveDescription_BatonPass
	.4byte gMoveDescription_Encore
	.4byte gMoveDescription_Pursuit
	.4byte gMoveDescription_RapidSpin
	.4byte gMoveDescription_SweetScent
	.4byte gMoveDescription_IronTail
	.4byte gMoveDescription_MetalClaw
	.4byte gMoveDescription_VitalThrow
	.4byte gMoveDescription_MorningSun
	.4byte gMoveDescription_Synthesis
	.4byte gMoveDescription_Moonlight
	.4byte gMoveDescription_HiddenPower
	.4byte gMoveDescription_CrossChop
	.4byte gMoveDescription_Twister
	.4byte gMoveDescription_RainDance
	.4byte gMoveDescription_SunnyDay
	.4byte gMoveDescription_Crunch
	.4byte gMoveDescription_MirrorCoat
	.4byte gMoveDescription_PsychUp
	.4byte gMoveDescription_ExtremeSpeed
	.4byte gMoveDescription_AncientPower
	.4byte gMoveDescription_ShadowBall
	.4byte gMoveDescription_FutureSight
	.4byte gMoveDescription_RockSmash
	.4byte gMoveDescription_Whirlpool
	.4byte gMoveDescription_BeatUp
	.4byte gMoveDescription_FakeOut
	.4byte gMoveDescription_Uproar
	.4byte gMoveDescription_Stockpile
	.4byte gMoveDescription_SpitUp
	.4byte gMoveDescription_Swallow
	.4byte gMoveDescription_HeatWave
	.4byte gMoveDescription_Hail
	.4byte gMoveDescription_Torment
	.4byte gMoveDescription_Flatter
	.4byte gMoveDescription_WillOWisp
	.4byte gMoveDescription_Memento
	.4byte gMoveDescription_Facade
	.4byte gMoveDescription_FocusPunch
	.4byte gMoveDescription_SmellingSalt
	.4byte gMoveDescription_FollowMe
	.4byte gMoveDescription_NaturePower
	.4byte gMoveDescription_Charge
	.4byte gMoveDescription_Taunt
	.4byte gMoveDescription_HelpingHand
	.4byte gMoveDescription_Trick
	.4byte gMoveDescription_RolePlay
	.4byte gMoveDescription_Wish
	.4byte gMoveDescription_Assist
	.4byte gMoveDescription_Ingrain
	.4byte gMoveDescription_Superpower
	.4byte gMoveDescription_MagicCoat
	.4byte gMoveDescription_Recycle
	.4byte gMoveDescription_Revenge
	.4byte gMoveDescription_BrickBreak
	.4byte gMoveDescription_Yawn
	.4byte gMoveDescription_KnockOff
	.4byte gMoveDescription_Endeavor
	.4byte gMoveDescription_Eruption
	.4byte gMoveDescription_SkillSwap
	.4byte gMoveDescription_Imprison
	.4byte gMoveDescription_Refresh
	.4byte gMoveDescription_Grudge
	.4byte gMoveDescription_Snatch
	.4byte gMoveDescription_SecretPower
	.4byte gMoveDescription_Dive
	.4byte gMoveDescription_ArmThrust
	.4byte gMoveDescription_Camouflage
	.4byte gMoveDescription_TailGlow
	.4byte gMoveDescription_LusterPurge
	.4byte gMoveDescription_MistBall
	.4byte gMoveDescription_FeatherDance
	.4byte gMoveDescription_TeeterDance
	.4byte gMoveDescription_BlazeKick
	.4byte gMoveDescription_MudSport
	.4byte gMoveDescription_IceBall
	.4byte gMoveDescription_NeedleArm
	.4byte gMoveDescription_SlackOff
	.4byte gMoveDescription_HyperVoice
	.4byte gMoveDescription_PoisonFang
	.4byte gMoveDescription_CrushClaw
	.4byte gMoveDescription_BlastBurn
	.4byte gMoveDescription_HydroCannon
	.4byte gMoveDescription_MeteorMash
	.4byte gMoveDescription_Astonish
	.4byte gMoveDescription_WeatherBall
	.4byte gMoveDescription_Aromatherapy
	.4byte gMoveDescription_FakeTears
	.4byte gMoveDescription_AirCutter
	.4byte gMoveDescription_Overheat
	.4byte gMoveDescription_OdorSleuth
	.4byte gMoveDescription_RockTomb
	.4byte gMoveDescription_SilverWind
	.4byte gMoveDescription_MetalSound
	.4byte gMoveDescription_GrassWhistle
	.4byte gMoveDescription_Tickle
	.4byte gMoveDescription_CosmicPower
	.4byte gMoveDescription_WaterSpout
	.4byte gMoveDescription_SignalBeam
	.4byte gMoveDescription_ShadowPunch
	.4byte gMoveDescription_Extrasensory
	.4byte gMoveDescription_SkyUppercut
	.4byte gMoveDescription_SandTomb
	.4byte gMoveDescription_SheerCold
	.4byte gMoveDescription_MuddyWater
	.4byte gMoveDescription_BulletSeed
	.4byte gMoveDescription_AerialAce
	.4byte gMoveDescription_IcicleSpear
	.4byte gMoveDescription_IronDefense
	.4byte gMoveDescription_Block
	.4byte gMoveDescription_Howl
	.4byte gMoveDescription_DragonClaw
	.4byte gMoveDescription_FrenzyPlant
	.4byte gMoveDescription_BulkUp
	.4byte gMoveDescription_Bounce
	.4byte gMoveDescription_MudShot
	.4byte gMoveDescription_PoisonTail
	.4byte gMoveDescription_Covet
	.4byte gMoveDescription_VoltTackle
	.4byte gMoveDescription_MagicalLeaf
	.4byte gMoveDescription_WaterSport
	.4byte gMoveDescription_CalmMind
	.4byte gMoveDescription_LeafBlade
	.4byte gMoveDescription_DragonDance
	.4byte gMoveDescription_RockBlast
	.4byte gMoveDescription_ShockWave
	.4byte gMoveDescription_WaterPulse
	.4byte gMoveDescription_DoomDesire
	.4byte gMoveDescription_PsychoBoost
