PetalburgCity_PokemonCenter_1F_Text_1B1C97:: @ 81B1C97
	.string "안녕하세요\n"
	.string "미소가 멋진 트레이너님!\p"
	.string "저는 트레이너들의 프로필을\n"
	.string "모으고 있습니다$"

PetalburgCity_PokemonCenter_1F_Text_1B1D10:: @ 81B1D10
	.string "혹시 당신의 프로필\n"
	.string "한번 봐도 될까요?$"

PetalburgCity_PokemonCenter_1F_Text_1B1D3A:: @ 81B1D3A
	.string "4개의 단어를 적절히 이용해서\n"
	.string "자신의 트레이너카드에\p"
	.string "적고 싶은 말을\n"
	.string "작성하시면 됩니다!\p"
	.string "여기 제가 4개의 단어로\n"
	.string "적은 프로필을 보여드릴테니\p"
	.string "4개의 단어를 각각 바꿔서\l"
	.string "자신만의 프로필을 만들면 됩니다\p"
	.string "쓸 수 있는 단어들은 많이 있으니\n"
	.string "한번 멋진 프로필을 만들어보세요!\p"
	.string "또한 그룹별로 포켓몬, 생활,\n"
	.string "취미 등으로 나누어져 있으니\l"
	.string "쉽게 만드실 수 있을 거예요!\p"
	.string "제일 먼저 그룹을 고르시면\n"
	.string "해당 그룹의\l"
	.string "단어 리스트가 나옵니다!\p"
	.string "그중에서\n"
	.string "마음에 드는 것을 고르세요!\p"
	.string "그렇게 4개의 단어를 모두 다 바꾸면\n"
	.string "자신만의 프로필이 완성됩니다!$"

UnknownString_81B1F7A: @ 81B1F7A
	.string "$"

PetalburgCity_PokemonCenter_1F_Text_1B1F7B:: @ 81B1F7B
	.string "네 감사합니다!\n"
	.string "그럼 당신의 프로필을 알려 주세요!$"

PetalburgCity_PokemonCenter_1F_Text_1B1FA3:: @ 81B1FA3
	.string "음 그런가요?\p"
	.string "당신의 프로필은 무척\n"
	.string "멋질 것 같았는데...$"

PetalburgCity_PokemonCenter_1F_Text_1B1FF0:: @ 81B1FF0
	.string "음? 지금은 프로필이\n" 
	.string "생각나지 않으신가요?\p"
	.string "뭐, 언제든 괜찮습니다!$"

PetalburgCity_PokemonCenter_1F_Text_1B202F:: @ 81B202F
	.string "안녕하세요\n"
	.string "미소가 멋진 트레이너님!$"

PetalburgCity_PokemonCenter_1F_Text_1B2063:: @ 81B2063
	.string "그럼 당신의\n"
	.string "새로운 프로필을 봐도 될까요?$"

PetalburgCity_PokemonCenter_1F_Text_1B207F:: @ 81B207F
	.string "네 감사합니다!\p"
	.string "전보다 더 멋진 프로필\n"
	.string "기대할게요!$"

PetalburgCity_PokemonCenter_1F_Text_1B20CE:: @ 81B20CE
	.string "음?\n"
	.string "지금의 프로필로 괜찮으신가요?\p"
	.string "아니아니 싫다고 하는게 아니에요!\n"
	.string "지금도 충분히 멋진\l"
	.string "프로필이라고 생각한답니다!$"

PetalburgCity_PokemonCenter_1F_Text_1B2137:: @ 81B2137
	.string "후-훌룡합니다!\p"
	.string "정말로 멋진 프로필이에요!!\n"
	.string "당신 그 자체의 프로필...\p"
	.string "듣는 사람은 누구든지\n"
	.string "당신에게 빠져버릴겁니다!\p"
	.string "멋진 프로필을 알려주셔서\n"
	.string "감사드려요!$"

PetalburgCity_PokemonCenter_1F_Text_1B21CC:: @ 81B21CC
	.string "음? 당신\n"
	.string "비밀의 말을 알고 있군요!\p"
	.string "그건 이제 당신이\n"
	.string "이상한 사건 클럽의\l"
	.string "회원이라는 뜻이죠!$"
