gNatureName_Hardy: @ 83C0F60
	.string "노력{COLOR 15}하는$"

gNatureName_Lonely: @ 83C0F66
	.string "외로움{COLOR 15}을 타는$"

gNatureName_Brave: @ 83C0F6D
	.string "용감{COLOR 15}한$"

gNatureName_Adamant: @ 83C0F73
	.string "고집{COLOR 15}스런$"

gNatureName_Naughty: @ 83C0F7B
	.string "개구쟁이{COLOR 15} 같은$"

gNatureName_Bold: @ 83C0F83
	.string "대담{COLOR 15}한$"

gNatureName_Docile: @ 83C0F88
	.string "온순{COLOR 15}한$"

gNatureName_Relaxed: @ 83C0F8F
	.string "무사태평{COLOR 15}한$"

gNatureName_Impish: @ 83C0F97
	.string "장난꾸러기{COLOR 15} 같은$"

gNatureName_Lax: @ 83C0F9E
	.string "촐랑{COLOR 15}거리는$"

gNatureName_Timid: @ 83C0FA2
	.string "겁쟁이{COLOR 15} 같은$"

gNatureName_Hasty: @ 83C0FA8
	.string "성급{COLOR 15}한$"

gNatureName_Serious: @ 83C0FAE
	.string "성실{COLOR 15}한$"

gNatureName_Jolly: @ 83C0FB6
	.string "명랑{COLOR 15}한$"

gNatureName_Naive: @ 83C0FBC
	.string "천진난만{COLOR 15}한$"

gNatureName_Modest: @ 83C0FC2
	.string "조심{COLOR 15}스러운$"

gNatureName_Mild: @ 83C0FC9
	.string "의젓{COLOR 15}한$"

gNatureName_Quiet: @ 83C0FCE
	.string "냉정{COLOR 15}한$"

gNatureName_Bashful: @ 83C0FD4
	.string "수줍음{COLOR 15}을 타는$"

gNatureName_Rash: @ 83C0FDC
	.string "덜렁{COLOR 15}거리는$"

gNatureName_Calm: @ 83C0FE1
	.string "차분{COLOR 15}한$"

gNatureName_Gentle: @ 83C0FE6
	.string "얌전{COLOR 15}한$"

gNatureName_Sassy: @ 83C0FED
	.string "건방{COLOR 15}진$"

gNatureName_Careful: @ 83C0FF3
	.string "신중{COLOR 15}한$"

gNatureName_Quirky: @ 83C0FFB
	.string "변덕{COLOR 15}스러운$"

	.align 2
gNatureNames:: @ 83C1004
	.4byte gNatureName_Hardy
	.4byte gNatureName_Lonely
	.4byte gNatureName_Brave
	.4byte gNatureName_Adamant
	.4byte gNatureName_Naughty
	.4byte gNatureName_Bold
	.4byte gNatureName_Docile
	.4byte gNatureName_Relaxed
	.4byte gNatureName_Impish
	.4byte gNatureName_Lax
	.4byte gNatureName_Timid
	.4byte gNatureName_Hasty
	.4byte gNatureName_Serious
	.4byte gNatureName_Jolly
	.4byte gNatureName_Naive
	.4byte gNatureName_Modest
	.4byte gNatureName_Mild
	.4byte gNatureName_Quiet
	.4byte gNatureName_Bashful
	.4byte gNatureName_Rash
	.4byte gNatureName_Calm
	.4byte gNatureName_Gentle
	.4byte gNatureName_Sassy
	.4byte gNatureName_Careful
	.4byte gNatureName_Quirky
