Route101_Text_1C4449:: @ 81C4449 //JP: 19621E
	.string "털보박사: 오오 {PLAYER}!\p"
	.string "포켓몬 도감의 상태를\n"
	.string "보여 주겠니?$"

Route101_Text_1C449B:: @ 81C449B
	.string "응? 보여 줄 정도로\n"
	.string "포켓몬을 잡지 않았구나$"

Route101_Text_1C44DC:: @ 81C44DC
	.string "흠흠...\p"
	.string "발견한 포켓몬 {STR_VAR_1}마리,\n"
	.string "잡은 포켓몬 {STR_VAR_2}마리군...$"

gBirchDexRatingText_LessThan10:: @ 81C4520
	.string "좀 더 풀숲에 들어가서\n"
	.string "포켓몬을 찾아보도록 해!$"

gBirchDexRatingText_LessThan20:: @ 81C456A
	.string "익숙해졌나 보구나\n"
	.string "하지만 앞으로가 큰일이라고!$"

gBirchDexRatingText_LessThan30:: @ 81C45B0
	.string "정해진 장소에서만 발견되는\n"
	.string "포켓몬은 집요하게 찾는 수밖에 없어!$"

gBirchDexRatingText_LessThan40:: @ 81C45F9
	.string "아직 수는 많지 않지만\n"
	.string "조금은 포켓몬 도감다워졌구나$"

gBirchDexRatingText_LessThan50:: @ 81C4648
	.string "제법 괜찮은 느낌이네!\n"
	.string "이 상태로 열심히 해봐$"

gBirchDexRatingText_LessThan60:: @ 81C467E
	.string "낚싯대는 사용하고 있니?\n"
	.string "바다에도 포켓몬은 많이 있단다$"

gBirchDexRatingText_LessThan70:: @ 81C46B9
	.string "포켓몬을 잡지만 말고\n"
	.string "한번 진화시켜보는 건 어때?$"

gBirchDexRatingText_LessThan80:: @ 81C46FE
	.string "멋진 포켓몬 도감이 될 것 같군\n"
	.string "그런 예감이 많이 들어!$"

gBirchDexRatingText_LessThan90:: @ 81C4747
	.string "이만큼이나 모으다니...\n"
	.string "너의 재능은 대단해!$"

gBirchDexRatingText_LessThan100:: @ 81C4780
	.string "사파리존에는 가봤니?\n"
	.string "거기서만 잡을 수 있는\l"
	.string "포켓몬도 있다고 하더라!$"

gBirchDexRatingText_LessThan110:: @ 81C47DF
	.string "드디어 100종류를 넘었군!\n"
	.string "포켓몬 도감으로서 훌륭해!$"

gBirchDexRatingText_LessThan120:: @ 81C4828
	.string "...그러고 보니 바위깨기를 사용하면\n"
	.string "발견되는 포켓몬도 있다지$"

gBirchDexRatingText_LessThan130:: @ 81C4863
	.string "포켓몬 교환을 하면\n"
	.string "더 모을 수 있을지도 몰라$"

gBirchDexRatingText_LessThan140:: @ 81C489C
	.string "친해지면 진화하는\n"
	.string "포켓몬도 있다고 한다!$"

gBirchDexRatingText_LessThan150:: @ 81C48EB
	.string "호연지방에는 이렇게나\n"
	.string "많은 포켓몬이 있었던 건가...$"

gBirchDexRatingText_LessThan160:: @ 81C4936
	.string "가끔씩 대량발생하는\n"
	.string "포켓몬이 있는 것 같더구나\l"
	.string "그 기회를 놓치지 마라!$"

gBirchDexRatingText_LessThan170:: @ 81C49A2
	.string "너의 도감을 보면\n"
	.string "호연지방 포켓몬의\l"
	.string "모든 것을 알 수 있을 것 같아$"

gBirchDexRatingText_LessThan180:: @ 81C4A06
	.string "너는 포켓몬 박사로서도\n"
	.string "우수하구나$"

gBirchDexRatingText_LessThan190:: @ 81C4A4F
	.string "이만큼이나 도감을 완성했다면\n"
	.string "이미 프로페셔널이야!$"

gBirchDexRatingText_LessThan200:: @ 81C4A91
	.string "이제 거의 완성되어 가!\n"
	.string "그런 예감이 든다!$"

gBirchDexRatingText_DexCompleted:: @ 81C4ADA
	.string "축하한다!!\n"
	.string "포켓몬 도감 완성이다!!$"

Route101_Text_1C4B05:: @ 81C4B05
	.string "흠흠...\n"
	.string "전국적으로는...\p"
	.string "발견한 포켓몬 {STR_VAR_1}마리,\n"
	.string "잡은 포켓몬 {STR_VAR_2}마리군...$"
