FallarborTown_ContestLobby_Text_1B6E63:: @ 81B6E63 //JP: 18E9DD
	.string "오! 아저씨랑 같이\n"
	.string "포켓몬스넥을 만들고 싶은 거니?$"

FallarborTown_ContestLobby_Text_1B6E9D:: @ 81B6E9D
	.string "그런 건가!$"

FallarborTown_ContestLobby_Text_1B6EA8:: @ 81B6EA8
	.string "그런가...\n"
	.string "아저씨 외로워...$"

FallarborTown_ContestLobby_Text_1B6ED0:: @ 81B6ED0
	.string "그럼 포켓몬스넥을 만드는 방법은\n"
	.string "이미 알고 있니?$"

FallarborTown_ContestLobby_Text_1B6EF1:: @ 81B6EF1
	.string "그럼 시작한다!\p"
	.string "레츠 나무열매블렌더!!$"

FallarborTown_ContestLobby_Text_1B6F1F:: @ 81B6F1F
	.string "좋아 설명할게!\p"
	.string "뭐 간단한 거야!\p"
	.string "나무열매블렌더의 마크가\n"
	.string "자기 쪽으로 온다면\l"
	.string "버튼을 누르기만 하면 돼!\p"
	.string "뭐 실제로 해보면\n"
	.string "금방 알게 돼!$"

FallarborTown_ContestLobby_Text_1B6FF0:: @ 81B6FF0
	.string "어라? 근데 나무열매를\n"
	.string "가지고 있지 않은 모양이네\p"
	.string "나무열매가 없으면 포켓몬스넥은\n"
	.string "만들 수가 없어$"

FallarborTown_ContestLobby_Text_1B704A:: @ 81B704A
	.string "뭐 어쩔 수 없지\p"
	.string "아저씨의 남은 나무열매라도\n"
	.string "괜찮다면 줄게!\p"
	.string "이걸로 같이 나무열매블렌더로\n"
	.string "포켓몬스넥을 만들자!$"

FallarborTown_ContestLobby_Text_1B70F6:: @ 81B70F6
	.string "아저씨의 남은 나무열매가 있으면\n"
	.string "줄 수 있을 텐데...\p"
	.string "오늘은 더 이상 남아있지 않아\n"
	.string "다음에 같이 하자고$"

FallarborTown_ContestLobby_Text_1B717C:: @ 81B717C
	.string "근데 포켓몬스넥케이스가\n"
	.string "가득 찬 것 같네\p"
	.string "포켓몬스넥을 줄이고 나서\n"
	.string "다시 오도록 해$"

FallarborTown_ContestLobby_Text_1B71D2:: @ 81B71D2
	.string "근데 포켓몬스넥케이스를\n"
	.string "아직 가지고 있지 않나 보네\p"
	.string "포켓몬스넥케이스를\n"
	.string "받고 나서 다시 오도록 해$"

LilycoveCity_ContestLobby_Text_1B7225:: @ 81B7225
SlateportCity_ContestLobby_Text_1B7225:: @ 81B7225
	.string "빨리 섞어 보자고!!$"

LilycoveCity_ContestLobby_Text_1B7241:: @ 81B7241
	.string "어떤 포켓몬스넥이 완성될까?\n"
	.string "두근두근거려!$"

FallarborTown_ContestLobby_Text_1B727C:: @ 81B727C
	.string "나무열매블렌더로 친구와 함께\n"
	.string "나무열매로부터\l"
	.string "포켓몬스넥을 만듭니다\p"
	.string "통신하기 전에\n"
	.string "리포트를 써도 괜찮겠습니까?$"

FallarborTown_ContestLobby_Text_1B7304:: @ 81B7304
	.string "친구를 찾고 있습니다\n"
	.string "...B 버튼으로 취소$"

FallarborTown_ContestLobby_Text_1B733B:: @ 81B733B
	.string "{STR_VAR_1}님이 왔습니다$"

FallarborTown_ContestLobby_Text_1B7347:: @ 81B7347
	.string "{STR_VAR_1}님과 {STR_VAR_2}님이\n"
	.string	"왔습니다$"

FallarborTown_ContestLobby_Text_1B735A:: @ 81B735A
	.string "{STR_VAR_1}님과 {STR_VAR_2}님\n"
	.string "{STR_VAR_3}님이 왔습니다$"

UnknownString_81B7372: @ 81B7372
	.string "아무도 오지 않았습니다...$"

FallarborTown_ContestLobby_Text_1B7381:: @ 81B7381
	.string "나무열매가 없어서\n"
	.string "나무열매블렌더는 쓸 수 없습니다$"

FallarborTown_ContestLobby_Text_1B73B7:: @ 81B73B7
	.string "포켓몬스넥케이스가 가득해서\n"
	.string "나무열매블렌더는 쓸 수 없습니다$"

FallarborTown_ContestLobby_Text_1B73F1:: @ 81B73F1
	.string "포켓몬스넥케이스가 없어서\n"
	.string "나무열매블렌더는 쓸 수 없습니다$"

FallarborTown_ContestLobby_Text_1B742F:: @ 81B742F
	.string "나는 포켓몬스넥을\n"
	.string "만드는 게 너무 좋아서\p"
	.string "언제나 나무열매를\n"
	.string "갖고 오지$"

FallarborTown_ContestLobby_Text_1B7469:: @ 81B7469
	.string "만약 괜찮다면\n"
	.string "같이 나무열매블렌더로\l"
	.string "포켓몬스넥을 만들자고$"

FallarborTown_ContestLobby_Text_1B74B4:: @ 81B74B4
	.string "어라?\n"
	.string "나무열매를 가지고 있지 않니?\p"
	.string "어쩔 수 없지 뭐\p"
	.string "뭐 어쩔 수 없지\p"
	.string "아저씨의 남은 나무열매라도\n"
	.string "괜찮다면 줄게!$"

FallarborTown_ContestLobby_Text_1B753A:: @ 81B753A
	.string "이걸로 같이 나무열매블렌더로\n"
	.string "포켓몬스넥을 만들자!$"

FallarborTown_ContestLobby_Text_1B7578:: @ 81B7578
	.string "어라?\n"
	.string "나무열매를 가지고 있지 않니?\p"
	.string "아저씨 여분이 있다면\n"
	.string "줄 수 있을 텐데...\p"
	.string "오늘은 더 이상 남아있지\n"
	.string "않아 미안해$"
