gRibbonDescriptionPart1_Champion: //JP: 3B7888
	.string "챔피언에게 이겨서$"

gRibbonDescriptionPart2_Champion:
	.string "전당등록한 기념리본$"

gRibbonDescriptionPart1_CoolContest:
	.string "근사함콘테스트$"

gRibbonDescriptionPart1_BeautyContest:
	.string "아름다움콘테스트$"

gRibbonDescriptionPart1_CuteContest:
	.string "귀여움콘테스트$"

gRibbonDescriptionPart1_SmartContest:
	.string "슬기로움콘테스트$"

gRibbonDescriptionPart1_ToughContest:
	.string "강인함콘테스트$"

gRibbonDescriptionPart2_NormalRank:
	.string "노말랭크 우승!$"

gRibbonDescriptionPart2_SuperRank:
	.string "슈퍼랭크 우승!$"

gRibbonDescriptionPart2_HyperRank:
	.string "하이퍼랭크 우승!$"

gRibbonDescriptionPart2_MasterRank:
	.string "마스터랭크 우승!$"

gRibbonDescriptionPart1_Winning:
	.string "배틀타워 레벨50에서$"

gRibbonDescriptionPart2_Winning:
	.string "연승한 기념리본$"

gRibbonDescriptionPart1_Victory:
	.string "배틀타워 레벨100에서$"

gRibbonDescriptionPart2_Victory:
	.string "연승한 기념리본$"

gRibbonDescriptionPart1_Artist:
	.string "호화로운 초상화의 모델이$"

gRibbonDescriptionPart2_Artist:
	.string "된 기념리본$"

gRibbonDescriptionPart1_Effort:
	.string "많이 노력하고 있는$"

gRibbonDescriptionPart2_Effort:
	.string "포켓몬에게 수여되는 리본$"

	.align 2
gRibbonDescriptions:: @ 83E113C
	.4byte gRibbonDescriptionPart1_Champion,      gRibbonDescriptionPart2_Champion
	.4byte gRibbonDescriptionPart1_CoolContest,   gRibbonDescriptionPart2_NormalRank
	.4byte gRibbonDescriptionPart1_CoolContest,   gRibbonDescriptionPart2_SuperRank
	.4byte gRibbonDescriptionPart1_CoolContest,   gRibbonDescriptionPart2_HyperRank
	.4byte gRibbonDescriptionPart1_CoolContest,   gRibbonDescriptionPart2_MasterRank
	.4byte gRibbonDescriptionPart1_BeautyContest, gRibbonDescriptionPart2_NormalRank
	.4byte gRibbonDescriptionPart1_BeautyContest, gRibbonDescriptionPart2_SuperRank
	.4byte gRibbonDescriptionPart1_BeautyContest, gRibbonDescriptionPart2_HyperRank
	.4byte gRibbonDescriptionPart1_BeautyContest, gRibbonDescriptionPart2_MasterRank
	.4byte gRibbonDescriptionPart1_CuteContest,   gRibbonDescriptionPart2_NormalRank
	.4byte gRibbonDescriptionPart1_CuteContest,   gRibbonDescriptionPart2_SuperRank
	.4byte gRibbonDescriptionPart1_CuteContest,   gRibbonDescriptionPart2_HyperRank
	.4byte gRibbonDescriptionPart1_CuteContest,   gRibbonDescriptionPart2_MasterRank
	.4byte gRibbonDescriptionPart1_SmartContest,  gRibbonDescriptionPart2_NormalRank
	.4byte gRibbonDescriptionPart1_SmartContest,  gRibbonDescriptionPart2_SuperRank
	.4byte gRibbonDescriptionPart1_SmartContest,  gRibbonDescriptionPart2_HyperRank
	.4byte gRibbonDescriptionPart1_SmartContest,  gRibbonDescriptionPart2_MasterRank
	.4byte gRibbonDescriptionPart1_ToughContest,  gRibbonDescriptionPart2_NormalRank
	.4byte gRibbonDescriptionPart1_ToughContest,  gRibbonDescriptionPart2_SuperRank
	.4byte gRibbonDescriptionPart1_ToughContest,  gRibbonDescriptionPart2_HyperRank
	.4byte gRibbonDescriptionPart1_ToughContest,  gRibbonDescriptionPart2_MasterRank
	.4byte gRibbonDescriptionPart1_Winning,       gRibbonDescriptionPart2_Winning
	.4byte gRibbonDescriptionPart1_Victory,       gRibbonDescriptionPart2_Victory
	.4byte gRibbonDescriptionPart1_Artist,        gRibbonDescriptionPart2_Artist
	.4byte gRibbonDescriptionPart1_Effort,        gRibbonDescriptionPart2_Effort
