gUnknown_081C40DF:: @ 81C40DF
UnknownString_81C40DF: @ 81C40DF
	.string "여기는 레이트 {STR_VAR_1}의 룰렛입니다\n"
	.string "룰렛으로 즐기겠습니까?$"

gUnknown_081C411C:: @ 81C411C
UnknownString_81C411C: @ 81C411C
	.string "동전이 없습니다$"

gUnknown_081C4139:: @ 81C4139
UnknownString_81C4139: @ 81C4139
	.string "오늘 이 테이블은\n"
	.string "레이트 업!$"

gUnknown_081C4157:: @ 81C4157
	.string "배팅할 곳을 십자 버튼으로 선택하고\n"
	.string "A 버튼으로 결정합니다$"

gUnknown_081C4199:: @ 81C4199
UnknownString_81C4199: @ 81C4199
	.string "당첨-!$"

gUnknown_081C41A5:: @ 81C41A5
UnknownString_81C41A5: @ 81C41A5
	.string "대당첨!!$"

gUnknown_081C41AE:: @ 81C41AE
UnknownString_81C41AE: @ 81C41AE
	.string "꽝-$"

gUnknown_081C41BD:: @ 81C41BD
UnknownString_81C41BD: @ 81C41BD
	.string "동전 {STR_VAR_1}개를 얻습니다!$"

gUnknown_081C41D2:: @ 81C41D2
UnknownString_81C41D2: @ 81C41D2
	.string "동전이 다 떨어졌습니다$"

gUnknown_081C41E3:: @ 81C41E3
UnknownString_81C41E3: @ 81C41E3
	.string "계속해서 즐기겠습니까?$"

gUnknown_081C41F1:: @ 81C41F1
UnknownString_81C41F1: @ 81C41F1
	.string "테이블 위의 구슬들을\n"
	.string "리셋합니다$"

UnknownString_81C4215: @ 81C4215
	.string "동전케이스를 가지고 있지 않습니다$"

gUnknown_081C4231:: @ 81C4231
UnknownString_81C4231: @ 81C4231
	.string "동전이 가득 찼습니다!\n"
	.string "경품과 교환해 주십시오$"
