UnknownString_81C34B2: @ 81C34B2 //JP: 195865
	.string "사파리존을\n"
	.string "이대로 종료하시겠습니까?$"

UnknownString_81C34E4: @ 81C34E4
	.string "딩동! 시간이 다 되었습니다!\n"
	.string "사파리게임을 종료합니다$"

UnknownString_81C3514: @ 81C3514
	.string "사파리볼이 다 떨어졌으므로\n"
	.string "사파리게임을 종료합니다$"

UnknownString_81C354E: @ 81C354E
	.string "포켓몬스넥먹이통에\n"
	.string "포켓몬스넥을 놓겠습니까?$"

UnknownString_81C3583: @ 81C3583
	.string "아직 {STR_VAR_1}이\n"
	.string "남아있습니다$"

UnknownString_81C35A9: @ 81C35A9
	.string "{STR_VAR_1}을\n"
	.string "놓았습니다!$"

Route121_SafariZoneEntrance_Text_1C35D0:: @ 81C35D0
	.string "어서 오세요! 사파리존입니다\p"
	.string "여기에서는 호연지방에서는 좀처럼\n"
	.string "볼 수 없는 포켓몬을\p"
	.string "자연의 모습 그대로\n"
	.string "볼 수 있습니다\p"
	.string "게다가 트레이너의\n"
	.string "요구를 반영해서\p"
	.string "포켓몬을\n"
	.string "잡을 수 있게 되었습니다!\p"
	.string "사파리존을 즐겨주세요!$"

Route121_SafariZoneEntrance_Text_1C3704:: @ 81C3704
	.string "어서 오세요! 사파리존입니다\n"
	.string "사파리존은 처음입니까?$"

Route121_SafariZoneEntrance_Text_1C373C:: @ 81C373C
	.string "사파리존을 즐겨주세요!$"

Route121_SafariZoneEntrance_Text_1C375F:: @ 81C375F
	.string "사파리존에서는\n"
	.string "30개의 사파리볼을 사용해서\l"
	.string "포켓몬을 잡을 수 있습니다\p"
	.string "사파리볼을 다 쓰거나\n"
	.string "500걸음 걸으면\l"
	.string "게임은 종료됩니다\p"
	.string "사파리존을 즐겨주세요!$"

Route121_SafariZoneEntrance_Text_1C3832:: @ 81C3832
	.string "어서 오세요! 사파리존입니다\p"
	.string "500원으로 포켓몬 무제한 잡기\n"
	.string "사파리게임에 참가하시겠습니까?$"

Route121_SafariZoneEntrance_Text_1C3895:: @ 81C3895
	.string "그렇군요\n"
	.string "다음번에는 꼭 참가해주십시오!$"

Route121_SafariZoneEntrance_Text_1C38B5:: @ 81C38B5
	.string "돈이 부족합니다!$"

Route121_SafariZoneEntrance_Text_1C38D9:: @ 81C38D9
	.string "그럼 500원 받겠습니다$"

Route121_SafariZoneEntrance_Text_1C38F4:: @ 81C38F4
	.string "여기 사파리볼입니다!$"

Route121_SafariZoneEntrance_Text_1C3910:: @ 81C3910
	.string "{PLAYER}\s 사파리볼을\n"
	.string "30개 받았다!$"

Route121_SafariZoneEntrance_Text_1C392D:: @ 81C392D
	.string "시간이 다 되면\n"
	.string "이쪽에서 알려드리므로\p"
	.string "충분히 즐겨 주십시오!\n"
	.string "그럼 다녀오세요!$"

Route121_SafariZoneEntrance_Text_1C39A3:: @ 81C39A3
	.string "손님!\n"
	.string "박스가 가득합니다!$"

Route121_SafariZoneEntrance_Text_1C39C3:: @ 81C39C3
	.string "아! 손님\n"
	.string "포켓몬스넥케이스를\l"
	.string "가지고 있지 않으시군요?\p"
	.string "사파리존은 포켓몬스넥을 쓰면\n"
	.string "보다 재밌게 즐길 수 있으니\p"
	.string "꼭 포켓몬스넥케이스를\n"
	.string "가지고 와주십시오!$"

SafariZone_Southeast_Text_1C3A56:: @ 81C3A56
	.string "아직 시간이 남아 있습니다만\n"
	.string "사파리존을 그만두시겠습니까?$"

SafariZone_Southeast_Text_1C3A9C:: @ 81C3A9C
	.string "그럼 계속해서 즐겨주세요!$"

SafariZone_Southeast_Text_1C3ACA:: @ 81C3ACA
	.string "알겠습니다\p"
	.string "그럼 남은 사파리볼은\n"
	.string "이쪽으로 주세요\p"
	.string "수고하셨습니다\n"
	.string "또 이용해 주세요$"

SafariZone_Southeast_Text_1C3B2D:: @ 81C3B2D
	.string "그럼 다녀오세요!\p"
	.string "뭔가 있으면\n"
	.string "저에게 말을 걸어 주세요!$"

SafariZone_Southeast_Text_1C3B71:: @ 81C3B71
	.string "알고 있었어?\p"
	.string "저 네모난 상자에\n"
	.string "포켓몬스넥을 놓으면\l"
	.string "포켓몬이 모여들어!$"

SafariZone_Southeast_Text_1C3BBD:: @ 81C3BBD
	.string "이 앞으로 가고 싶지만\n"
	.string "자전거 갖고 오는 걸 까먹었어...\p"
	.string "깊숙한 곳에 희귀한 포켓몬이\n"
	.string "있을 것 같은데!$"

SafariZone_Southwest_Text_1C3C39:: @ 81C3C39
	.string "포켓몬에게 포켓몬스넥을 던지면\n"
	.string "무시당할 때도 있어\p"
	.string "포켓몬에게도 좋아하는 것과\n"
	.string "싫어하는 것이 있는 걸까?$"

SafariZone_Northwest_Text_1C3CAE:: @ 81C3CAE
	.string "허억... 허억...\n"
	.string "드디어 여기까지 왔지만...\p"
	.string "지쳐버려서 포켓몬 잡을\n"
	.string "기운이 없어...$"

SafariZone_Northeast_Text_1C3D19:: @ 81C3D19
	.string "호연에는 없는 물포켓몬을\n"
	.string "찾으러 왔는데...\p"
	.string "호수가 어디에 있는지\n"
	.string "너 알고 있니?$"

SafariZone_Northeast_Text_1C3D80:: @ 81C3D80
	.string "여기서 희귀한 포켓몬을\n"
	.string "잔뜩 잡아서\l"
	.string "친구와 교환할 거야!$"

SafariZone_Southeast_Text_1C3DCE:: @ 81C3DCE
	.string "포켓몬스넥먹이통에 놓은\n"
	.string "포켓몬스넥은\l"
	.string "어느새 없어져 있었다...\p"
	.string "모르는 사이에\n"
	.string "포켓몬이 먹어버린 걸까?$"

Route121_SafariZoneEntrance_Text_1C3E4B:: @ 81C3E4B
	.string "사파리존 정보 나눔!\p"
	.string "마주친 포켓몬에게\n"
	.string "포켓몬스넥을 던지면\l"
	.string "도망가기 어려워집니다!$"

SafariZone_Southwest_Text_1C3EA3:: @ 81C3EA3
	.string "걷느라 지쳤다면 잠시 한숨 돌리자!\n"
	.string "“모두의 휴게소”$"

SafariZone_RestHouse_Text_1C3EC9:: @ 81C3EC9
	.string "난 포켓몬스넥을 가지고 있지 않지만\n"
	.string "포켓몬을 잔뜩 잡았어\p"
	.string "가까이 다가가서 볼을 던졌을 뿐인데\n"
	.string "제법 잡을 수 있었단 말이지!$"

SafariZone_RestHouse_Text_1C3F71:: @ 81C3F71
	.string "포켓몬스넥을 쓰면 여느 때보다\n"
	.string "잘 도망치지 않게 되는 것 같아\p"
	.string "그러니까 잘 도망치지 않는\n"
	.string "포켓몬에게 써도\l"
	.string "그다지 의미는 없을지도 몰라$"

SafariZone_RestHouse_Text_1C3FF4:: @ 81C3FF4
	.string "포켓몬스넥먹이통에 포켓몬스넥을\n"
	.string "놓고 포켓몬을 잡으면\p"
	.string "같은 성격의 포켓몬이\n"
	.string "잡히는 것 같은 기분이 들어$"
