gSaveText_WouldYouLikeToSave:: @ 81C6C85
UnknownString_81C6C85: @ 81C6C85
	.string "지금까지의 활약을\n"
	.string "포켓몬 리포트로 작성할까요?$"

gSaveText_ThereIsAlreadyAFile:: @ 81C6CA6
UnknownString_81C6CA6: @ 81C6CA6
	.string "전에 작성한 리포트에\n"
	.string "덮어써도 괜찮습니까?$"

gSaveText_DontTurnOff:: @ 81C6CE1
BattleTower_BattleRoom_Text_1C6CE1:: @ 81C6CE1
	.string "포켓몬 리포트를 작성하고 있습니다\n"
	.string "전원을 끄지 않도록 해주십시오$"

gSaveText_PlayerSavedTheGame:: @ 81C6D05
BattleTower_BattleRoom_Text_1C6D05:: @ 81C6D05
	.string "{PLAYER}{K_EUNNEUN}\n"
    .string "리포트를 꼼꼼히 기록했다!$"

UnknownString_81C6D18: @ 81C6D18
	.string "포켓몬 리포트를\n" 
	.string "작성할 수 없습니다!$"

gSaveText_ThereIsADifferentFile:: @ 81C6D26
UnknownString_81C6D26: @ 81C6D26
	.string "다른 모험의\n"
	.string "리포트가 작성되어 있습니다!\p"
	.string "덮어써도 괜찮습니까?$"
