Route111_Text_1A3520:: @ 81A3520
	.string "엣 뭘 하고 있냐고?\p"
	.string "포켓몬의 기술을 써서\n"
	.string "여기에 나만의 방을\l"
	.string "만들려고 생각하고 있어!\p"
	.string "그래 이 기술머신을 줄 테니까\n"
	.string "너도 만들어 볼래?$"

Route111_Text_1A35C5:: @ 81A35C5
	.string "덩굴이 떨어질 것 같은 나무를 향해서\n"
	.string "비밀의힘을 써 봐!\l"
	.string "덩굴이 떨어져서\l"
	.string "나무 위에 들어갈 수 있어!\p"
	.string "그러면 위에 넓은 방이 있어서\n"
	.string "나는 거기에 좋아하는 물건을 놓지!\l"
	.string "자신만의 비밀의 방...\l"
	.string "그래 비밀기지!\l"
	.string "너도 만들면 좋을 거야\p"
	.string "아 참 비밀기지를 만들 수 있는 곳은\n"
	.string "나무 위뿐만이 아니야!\p"
	.string "작게 움푹 패인 벽 같은 곳에도\n"
	.string "비밀의힘을 써보면 좋을 거야!\p"
	.string "나는 다른 장소를 찾아보도록 할게\n"
	.string "그럼!$"

Route111_Text_1A37B5:: @ 81A37B5
	.string "그래 필요 없구나...\n"
	.string "가지고 싶어진다면 다시 말 걸어줘!$"

Route111_Text_1A37F6:: @ 81A37F6
	.string "어라?\n"
	.string "그 이상은 지닐 수 없는 것 같아\p"
	.string "다음에 가지러 와줘!$"
