ShoalCave_LowTideEntranceRoom_Text_1C6668:: @ 81C6668 //JP: 1974E1
	.string "이 앞으로 갈 건가?\p"
	.string "혹시 괜찮으면\n"
	.string "여울소금과 여울조개껍질을\l"
	.string "모아주지 않겠나\p"
	.string "재료가 모이면\n"
	.string "내가 좋은 걸 만들 텐데 말이야$"

ShoalCave_LowTideEntranceRoom_Text_1C670D:: @ 81C670D
	.string "여울소금과 여울조개껍질\n"
	.string "각각 4개가 있으면\l"
	.string "조개껍질방울을 만들 수 있어...\p"
	.string "조개껍질방울의 재료라면\n"
	.string "매일 캘 수 있어$"

ShoalCave_LowTideEntranceRoom_Text_1C6793:: @ 81C6793
	.string "오! 여울소금과 여울조개껍질!\n"
	.string "양도 충분해!\p"
	.string "이걸로 조개껍질방울을\n"
	.string "만들어도 되겠니?$"

ShoalCave_LowTideEntranceRoom_Text_1C6808:: @ 81C6808
	.string "그럼 바로\n"
	.string "조개껍질방울을 만들게\p"
	.string "... ... ... ...\n"
	.string "... ... ... ...\p"
	.string "자 됐다!$"

ShoalCave_LowTideEntranceRoom_Text_1C688E:: @ 81C688E
	.string "포켓몬에게 지니게 하면\n"
	.string "기뻐할 거야\p"
	.string "누가 뭐라 해도\n"
	.string "조개껍질방울의 소리는\l"
	.string "천하일품이니까\p"
	.string "조개껍질방울의 재료라면\n"
	.string "매일 캘 수 있으니\l"
	.string "모이면 다시 만들어 줄게$"

ShoalCave_LowTideEntranceRoom_Text_1C6944:: @ 81C6944
	.string "그렇구나...\n"
	.string "조개껍질방울 만들고 싶었는데...$"

ShoalCave_LowTideInnerRoom_Text_1C6979:: @ 81C6979
ShoalCave_LowTideLowerRoom_Text_1C6979:: @ 81C6979
ShoalCave_LowTideStairsRoom_Text_1C6979:: @ 81C6979
	.string "여울소금을 모은 다음...\n"
	.string "지금은 아무것도 없네...$"

ShoalCave_LowTideInnerRoom_Text_1C69B8:: @ 81C69B8
	.string "여울조개껍질을 찾은 다음...\n"
	.string "지금은 아무것도 없네...$"

ShoalCave_LowTideEntranceRoom_Text_1C69F5:: @ 81C69F5
	.string "만들어도 가방이 가득 차서\n"
	.string "지닐 수 없을 것 같아...\p"
	.string "정리하고 다시 와$"
