gTextStoryteller_Introduction:: @ 81AECC6
	.string "난 전설아저씨\n"
	.string "전설의 트레이너에 대한 이야기를\l"
	.string "해줄 수 있어\p"
	.string "내 얘기 한번 들어볼래?$"

gTextStoryteller_OhIFeelStifled:: @ 81AED1D
	.string "그래...\n"
	.string "아쉽네...$"

gTextStoryteller_WhichTale:: @ 81AED35
	.string "난 이런 전설들을 알고 있어\n"
	.string "어느 전설을 듣고 싶어?$"

gTextStoryteller_ButIKnowOfNoLegendaryTrainers:: @ 81AED70
	.string "그렇지만 난...\n"
	.string "전설의 트레이너에 대한 이야기를\l"
	.string "하나도 알고 있지 않아\p"
	.string "어딘가 전설에 남을 만한\n"
	.string "트레이너는 없는 걸까...$"

gTextStoryteller_BirthOfANewLegend:: @ 81AEDE8
	.string "뭐라고!!!\p"
	.string "너...\n"
	.string "{STR_VAR_2}번이나\n"
	.string "{STR_VAR_1}{K_EULREUL}!?\p"
	.string "으음 그거 대단한데!\n"
	.string "새로운 전설의 시작이야!$"

gTextStoryteller_CouldThereBeOtherTrainers:: @ 81AEE50
	.string "이것보다 좀 더 대단한\n"
	.string "전설을 가진 트레이너\l"
	.string "어딘가에 없을라나...$"

gTextStoryteller_HaveYouAnyTales:: @ 81AEEB4
	.string "너 트레이너야?\p"
	.string "그럼 뭔가 전설 같은 이야기\n"
	.string "나한테 좀 들려줘!$"

gTextStoryteller_HearAnotherLegendaryTale:: @ 81AEF0A
	.string "그런데...\n"
	.string "또 다른 전설 듣고 싶어?$"

gTextStoryteller_ImNotSatisfied:: @ 81AEF49
	.string "음 어딘가 부족한걸\p"
	.string "좀 더 재미있는 이야기를\n"
	.string "들려줬으면 좋겠는데$"

gTextStoryteller_WishMorePeopleWould:: @ 81AEFA5
	.string "좀 더 많은 사람들이\n"
	.string "전설의 트레이너의 이야기\l"
	.string "들어주면 좋을 텐데$"

gTextStoryteller_Story1Title:: @ 81AEFFC
	.string "리포트를 많이 작성한 트레이너$"

gTextStoryteller_Story1Action:: @ 81AF013
	.string "리포트를 작성했다$"

gTextStoryteller_Story1Text:: @ 81AF022
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "{STR_VAR_1}번이나\n"
	.string "리포트를 작성했다더라고!\l"
	.string "{STR_VAR_3}{K_I}만큼이나 조심성 있는\l"
	.string "트레이너는 없을 거야 분명!$"

gTextStoryteller_Story2Title:: @ 81AF0A3
	.string "유행 발신 트레이너$"

gTextStoryteller_Story2Action:: @ 81AF0BB
	.string "유행을 만들었다$"

gTextStoryteller_Story2Text:: @ 81AF0CA
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "{STR_VAR_1}번이나\n"
	.string "유행을 새로 만든 모양이야!\l"
	.string "{STR_VAR_3}{K_I}야말로 계속해서\l"
	.string "호연의 유행을 새로 만들고 있어!$"

gTextStoryteller_Story3Title:: @ 81AF149
	.string "나무열매를 많이 심은 트레이너$"

gTextStoryteller_Story3Action:: @ 81AF164
	.string "나무열매를 심었다$"

gTextStoryteller_Story3Text:: @ 81AF174
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "나무열매를 심은 것 같아!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 전설의\n"
	.string "나무열매 애호가일 거야 분명!$"

gTextStoryteller_Story4Title:: @ 81AF1E5
	.string "자전거 애호가 트레이너$"

gTextStoryteller_Story4Action:: @ 81AF1FD
	.string "자전거를 교환했다$"

gTextStoryteller_Story4Text:: @ 81AF20A
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "자전거를 교환한 것 같아!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 정말\n"
	.string "자전거를 좋아하는\l"
	.string "트레이너일 거야 분명!$"

gTextStoryteller_Story5Title:: @ 81AF281
	.string "인터뷰에 많이 응한 트레이너$"

gTextStoryteller_Story5Action:: @ 81AF299
	.string "인터뷰에 응했다$"

gTextStoryteller_Story5Text:: @ 81AF2A9
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "인터뷰에 응한 것 같아!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 정말\n"
	.string "주목받는 트레이너일 거야 분명!$"

gTextStoryteller_Story6Title:: @ 81AF32C
	.string "승부 애호가 트레이너$"

gTextStoryteller_Story6Action:: @ 81AF345
	.string "승부했다$"

gTextStoryteller_Story6Text:: @ 81AF34D
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "포켓몬 승부를 했다는 거야!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 트레이너를 보면\n"
	.string "승부를 하지 않으면 못 지나가는\l"
	.string "트레이너일 거야 분명!$"

gTextStoryteller_Story7Title:: @ 81AF3D0
	.string "많이 잡은 트레이너$"

gTextStoryteller_Story7Action:: @ 81AF3ED
	.string "포켓몬을 잡았다$"

gTextStoryteller_Story7Text:: @ 81AF3FC
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}마리씩이나\n"
	.string "포켓몬을 잡은 것 같아!\p"
	.string "{STR_VAR_3}{K_I}야말로 전설의\n"
	.string "포켓몬 잡기 달인일 거야 분명!$"

gTextStoryteller_Story8Title:: @ 81AF46D
	.string "많이 낚은 트레이너$"

gTextStoryteller_Story8Action:: @ 81AF481
	.string "포켓몬을 낚았다$"

gTextStoryteller_Story8Text:: @ 81AF49B
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "포켓몬을 낚은 모양이야!\p"
	.string "{STR_VAR_3}{K_I}야말로 전설의\n"
	.string "낚시 명인일 거야 분명!$"

gTextStoryteller_Story9Title:: @ 81AF511
	.string "많이 알을 품은 트레이너$"

gTextStoryteller_Story9Action:: @ 81AF529
	.string "알을 부화시켰다$"

gTextStoryteller_Story9Text:: @ 81AF536
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "{STR_VAR_1}개나 되는 알을\n"
	.string "부화시켰다고 하더라고!\p"
	.string "{STR_VAR_3}{K_I}야말로 전설의\n"
	.string "알품기 트레이너일 거야 분명!$"

gTextStoryteller_Story10Title:: @ 81AF5A9
	.string "진화를 많이 시킨 트레이너$"

gTextStoryteller_Story10Action:: @ 81AF5BD
	.string "포켓몬을 진화시켰다$"

gTextStoryteller_Story10Text:: @ 81AF5CD
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "무려 {STR_VAR_1}마리의\n"
	.string "포켓몬을 진화시킨 모양이야!\p"
	.string "{STR_VAR_3}{K_I}야말로 최고의\n"
	.string "포켓몬 진화 마스터일 거야 분명!$"

gTextStoryteller_Story11Title:: @ 81AF63F
	.string "포켓몬센터 애호가 트레이너$"

gTextStoryteller_Story11Action:: @ 81AF661
	.string "포켓몬센터에서 회복했다$"

gTextStoryteller_Story11Text:: @ 81AF676
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "포켓몬센터에서 회복했다더라고!\p"
	.string "{STR_VAR_3}만큼 포켓몬센터가\n"
	.string "마음에 드는 트레이너는\l"
	.string "없을 거야 분명!$"

gTextStoryteller_Story12Title:: @ 81AF711
	.string "집 애호가 트레이너$"

gTextStoryteller_Story12Action:: @ 81AF726
	.string "자신의 집에서 회복했다$"

gTextStoryteller_Story12Text:: @ 81AF73D
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "자신의 집에서\l"
	.string "포켓몬들을 회복시켰다는 거야!\p"
	.string "{STR_VAR_3}만큼\n"
	.string "집으로 돌아가는 걸 좋아하는\l"
	.string "트레이너는 없을 거야 분명!$"

gTextStoryteller_Story13Title:: @ 81AF7BF
	.string "사파리존에 자주 가는 트레이너$"

gTextStoryteller_Story13Action:: @ 81AF7D9
	.string "사파리존에 들어갔다$"

gTextStoryteller_Story13Text:: @ 81AF7F1
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "사파리존에 들어간 모양이야!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 사파리존에서라면\n"
	.string "피가 끓는 트레이너일 거야 분명!$"

gTextStoryteller_Story14Title:: @ 81AF88A
	.string "풀베기를 많이 쓴 트레이너$"

gTextStoryteller_Story14Action:: @ 81AF8A1
	.string "풀베기를 썼다$"

gTextStoryteller_Story14Text:: @ 81AF8AA
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "풀베기를 썼다고 하더라고!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 풀베기가 좋아서\n"
	.string "어쩔 수 없는 트레이너일 거야 분명!$"

gTextStoryteller_Story15Title:: @ 81AF91B
	.string "바위에 꺾이지 않고 깬 트레이너$"

gTextStoryteller_Story15Action:: @ 81AF935
	.string "바위깨기를 썼다$"

gTextStoryteller_Story15Text:: @ 81AF943
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "바위깨기를 썼다고 하더라고!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 바위를 봐도\n"
	.string "꺾이지 않는 트레이너일 거야 분명!$"

gTextStoryteller_Story16Title:: @ 81AF9C8
	.string "이사를 많이 한 트레이너$"

gTextStoryteller_Story16Action:: @ 81AF9E0
	.string "이사를 했다$"

gTextStoryteller_Story16Text:: @ 81AF9F6
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "비밀기지를 이사했다는 거야!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 이사를 무척\n"
	.string "좋아하는 트레이너일 거야 분명!$"

gTextStoryteller_Story17Title:: @ 81AFA79
	.string "튀어오르기를 많이 쓴 트레이너$"

gTextStoryteller_Story17Action:: @ 81AFA92
	.string "튀어오르기를 썼다$"

gTextStoryteller_Story17Text:: @ 81AFA9E
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "튀어오르기를 썼다는 모양이야!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 튀어오르는 것이\n"
	.string "무척 즐거운 트레이너일 거야 분명!$"

gTextStoryteller_Story18Title:: @ 81AFB17
	.string "포기하지 않는 트레이너$"

gTextStoryteller_Story18Action:: @ 81AFB2D
	.string "발버둥을 썼다$"

gTextStoryteller_Story18Text:: @ 81AFB48
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "발버둥을 쓴 모양이야!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 어떠한 상황에서라도\n"
	.string "결코 포기하지 않는\l"
	.string "트레이너일 거야 분명!$"

gTextStoryteller_Story19Title:: @ 81AFBD8
	.string "슬롯의 명인$"

gTextStoryteller_Story19Action:: @ 81AFBE7
	.string "슬롯에서 대당첨되었다$"

gTextStoryteller_Story19Text:: @ 81AFC04
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "슬롯에서 대당첨됐다는 거야!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 슬롯을\n"
	.string "잘 알고 있는 트레이너일 거야 분명!$"

gTextStoryteller_Story20Title:: @ 81AFC8A
	.string "룰렛의 명인$"

gTextStoryteller_Story20Action:: @ 81AFC9D
	.string "룰렛을 연속으로 맞혔다$"

gTextStoryteller_Story20Text:: @ 81AFCBE
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "룰렛에서 연속으로 맞혔다는 거야!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 확실히 보고\n"
	.string "룰렛에 거는 트레이너일 거야 분명!$"

gTextStoryteller_Story21Title:: @ 81AFD44
	.string "배틀타워의 도전자$"

gTextStoryteller_Story21Action:: @ 81AFD60
	.string "배틀타워에 도전했다$"

gTextStoryteller_Story21Text:: @ 81AFD80
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "배틀타워에 도전했다는 거야!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 배틀타워에\n"
	.string "전력을 쏟는 트레이너일 거야 분명!$"

gTextStoryteller_Story22Title:: @ 81AFE1D
	.string "블렌드 애호가 트레이너$"

gTextStoryteller_Story22Action:: @ 81AFE36
	.string "포켓몬스넥을 만들었다$"

gTextStoryteller_Story22Text:: @ 81AFE42
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "포켓몬스넥을 만든 모양이야!\p"
	.string "{STR_VAR_3}만큼 나무열매블렌더를\n"
	.string "잘 쓰는 사람은 없을 거야 분명!$"

gTextStoryteller_Story23Title:: @ 81AFEC2
	.string "콘테스트 애호가 트레이너$"

gTextStoryteller_Story23Action:: @ 81AFEDD
	.string "콘테스트에 참가했다$"

gTextStoryteller_Story23Text:: @ 81AFEEE
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "{STR_VAR_1}번이나\n"
	.string "콘테스트에 참가했다더라고!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 자신의 포켓몬을\n"
	.string "사람들에게 보여주고 싶어하는\l"
	.string "트레이너일 거야 분명!$"

gTextStoryteller_Story24Title:: @ 81AFF68
	.string "콘테스트의 달인$"

gTextStoryteller_Story24Action:: @ 81AFF7B
	.string "콘테스트에서 우승했다$"

gTextStoryteller_Story24Text:: @ 81AFF88
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "콘테스트에서 우승했다더라고!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 엄청난\n"
	.string "콘테스트 마스터일 거야 분명!$"

gTextStoryteller_Story25Title:: @ 81AFFFB
	.string "쇼핑 애호가 트레이너$"

gTextStoryteller_Story25Action:: @ 81B000D
	.string "쇼핑을 했다$"

gTextStoryteller_Story25Text:: @ 81B0015
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "가게에서 쇼핑을 한 모양이야!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 가게에 들어가면\n"
	.string "계속 사는 트레이너일 거야 분명!$"

gTextStoryteller_Story26Title:: @ 81B009D
	.string "다우징 애호가 트레이너$"

gTextStoryteller_Story26Action:: @ 81B00B6
	.string "다우징머신을 사용했다$"

gTextStoryteller_Story26Text:: @ 81B00C9
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "다우징머신을 사용했던 모양이야!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 도구 찾기를\n"
	.string "정말 좋아하는\l"
	.string "트레이너일 거야 분명!$"

gTextStoryteller_Story27Title:: @ 81B014D
	.string "비에 젖은 트레이너$"

gTextStoryteller_Story27Action:: @ 81B0165
	.string "비에 젖었다$"

gTextStoryteller_Story27Text:: @ 81B0173
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "비에 흠뻑 젖은 모양이야!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 비도 끌리게 하는\n"
	.string "매력적인 트레이너일 거야 분명!$"

gTextStoryteller_Story28Title:: @ 81B01E9
	.string "도감을 많이 본 트레이너$"

gTextStoryteller_Story28Action:: @ 81B0201
	.string "도감을 봤다$"

gTextStoryteller_Story28Text:: @ 81B0213
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "도감을 본 모양이야!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 도감으로\n"
	.string "포켓몬을 조사하는 것을 좋아하는\l"
	.string "트레이너일 거야 분명!$"

gTextStoryteller_Story29Title:: @ 81B0290
	.string "리본을 잔뜩 모은 트레이너$"

gTextStoryteller_Story29Action:: @ 81B02A5
	.string "리본을 받았다$"

gTextStoryteller_Story29Text:: @ 81B02B6
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "리본을 받은 모양이야!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 리본을 모으는 걸\n"
	.string "무척 좋아하는\l"
	.string "트레이너일 거야 분명!$"

gTextStoryteller_Story30Title:: @ 81B0337
	.string "언덕을 많이 뛰어넘은 트레이너$"

gTextStoryteller_Story30Action:: @ 81B0351
	.string "언덕을 뛰어넘었다$"

gTextStoryteller_Story30Text:: @ 81B0364
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "언덕을 뛰어넘었다더라고!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 언덕을 보면\n"
	.string "뛰어넘지 않으면 못 지나가는\l"
	.string "트레이너일 거야 분명!$"

gTextStoryteller_Story31Title:: @ 81B03E9
	.string "전설의 TV 시청자$"

gTextStoryteller_Story31Action:: @ 81B0401
	.string "TV를 봤다$"

gTextStoryteller_Story31Text:: @ 81B040C
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "TV를 봤다는 거야!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} TV 애호가인\n"
	.string "트레이너일 거야 분명!$"

gTextStoryteller_Story32Title:: @ 81B046E
	.string "시간을 신경 쓰는 트레이너$"

gTextStoryteller_Story32Action:: @ 81B0489
	.string "시계를 봤다$"

gTextStoryteller_Story32Text:: @ 81B049A
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "시계를 본 모양이야!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 시간을 신경 쓰는\n"
	.string "꼼꼼한 트레이너일 거야 분명!$"

gTextStoryteller_Story33Title:: @ 81B0523
	.string "포켓몬 추첨에 당첨된 트레이너$"

gTextStoryteller_Story33Action:: @ 81B053E
	.string "포켓몬 추첨에 당첨됐다$"

gTextStoryteller_Story33Text:: @ 81B0554
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "포켓몬 추첨에서 당첨됐다더라고!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 포켓몬을 교환할\n"
	.string "친구가 많은 트레이너일 거야 분명!$"

gTextStoryteller_Story34Title:: @ 81B05D8
	.string "키우미집 단골 트레이너$"

gTextStoryteller_Story34Action:: @ 81B05F3
	.string "키우미집에 포켓몬을 맡겼다$"

gTextStoryteller_Story34Text:: @ 81B0610
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "키우미집에 맡겼다더라고!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 어쨌든 키우고 보는\n"
	.string "맹렬한 트레이너일 거야 분명!$"

gTextStoryteller_Story35Title:: @ 81B06A9
	.string "케이블카 애호가 트레이너$"

gTextStoryteller_Story35Action:: @ 81B06C6
	.string "케이블카에 탔다$"

gTextStoryteller_Story35Text:: @ 81B06D9
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "케이블카를 탔던 모양이야!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 아래위로 왔다 갔다 하는\n"
	.string "매우 바쁜 트레이너일 거야 분명!$"

gTextStoryteller_Story36Title:: @ 81B0763
	.string "온천에 자주 다니는 트레이너$"

gTextStoryteller_Story36Action:: @ 81B0781
	.string "온천에 들어갔다$"

gTextStoryteller_Story36Text:: @ 81B0797
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기야...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "온천에 들어간 모양이야!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 피부가 매끈매끈한\n"
	.string "트레이너일 거야 분명!$"
