gTextTrader_Introduction:: @ 81AE88F
	.string "난 굿즈교환아저씨\n"
	.string "나랑 굿즈 교환하지 않을래?$"

gTextTrader_FeelUnwanted1:: @ 81AE8C6
	.string "그래...\n"
	.string "아쉽네...$"

gTextTrader_TradedAlready:: @ 81AE8DF
	.string "하지만 너하고는 이미\n"
	.string "굿즈를 교환했는걸$"

gTextTrader_MenuPrompt:: @ 81AE910
	.string "이거 내가 가지고 있는 굿즈인데\n"
	.string "가지고 싶은 거 있으면 말해$"

gTextTrader_DontWantAnything:: @ 81AE950
	.string "갖고 싶은 굿즈 없어?\n"
	.string "아쉽네...$"

gTextTrader_ItemOnceBelongedTo:: @ 81AE97C
	.string "그건 {STR_VAR_1}\r\n"
	.string "썼었던 굿즈야\p"
	.string "이걸로 할래?$"

gTextTrader_YouDontHaveDecorations:: @ 81AE9B6
	.string "...엣 너 굿즈\n"
	.string "하나도 가지고 있지 않잖아!$"

gTextTrader_PickDecorationYoullTrade:: @ 81AE9F8
	.string "자 교환에 내놓을\n"
	.string "굿즈를 골라줘!$"

gTextTrader_FeelUnwanted2:: @ 81AEA2B
	.string "갖고 싶은 굿즈 없어?\n"
	.string "아쉽네...$"

gTextTrader_NoRoomForThis:: @ 81AEA57
	.string "너 {STR_VAR_2}\r 가득해서\n"
	.string "더 이상 지닐 수 없어$"

gTextTrader_SoWellTrade:: @ 81AEA9B
	.string "자 그럼 내 {STR_VAR_3}\h\n"
	.string "너의 {STR_VAR_2}\f 교환할래?$"

gTextTrader_InUseYouCantTradeIt:: @ 81AEAC3
	.string "그 굿즈는 지금 장식되어 있네\n"
	.string "장식한 굿즈는 교환할 수 없어$"

gTextTrader_ThenWellTrade:: @ 81AEAFB
	.string "자 그럼 교환!\n"
	.string "네 PC에 전송했어!$"

gTextTrader_ICantTradeThatOneAway:: @ 81AEB31
	.string "앗! 미안!\n"
	.string "그거 굉장히 진귀한 굿즈라서\l"
	.string "교환할 수 없어!\p"
	.string "그 밖에 원하는 굿즈 없어?$"
