Route102_Text_1B79C3:: @ 81B79C3
	.string "포켓몬을 데리고 있다면\n"
	.string "너도 이제 어엿한 포켓몬 트레이너!\l"
	.string "내 도전을 받아 줄 거지?!$"

Route102_Text_1B7A2C:: @ 81B7A2C
	.string "으아 져버렸어...\n"
	.string "더 키워 놨으면 이길 수 있었을 텐데...$"

Route102_Text_1B7A60:: @ 81B7A60
	.string "너 말이야! 강하면 강하다고\n"
	.string "처음부터 말을 해 줬어야지!$"

Route102_Text_1B7A9F:: @ 81B7A9F
	.string "너한테 지고 나서 필사적으로\n"
	.string "포켓몬을 키웠어!\l"
	.string "당연히 내 도전을 받아주겠지?!$"

Route102_Text_1B7AFD:: @ 81B7AFD
	.string "아아... 졌어...\n"
	.string "키우는 방법이 잘못됐나?$"

Route102_Text_1B7B2F:: @ 81B7B2F
	.string "네가 강해진다면\n"
	.string "나도 더욱 강해지겠어!$"

Route102_Text_1B7B68:: @ 81B7B68
	.string "이제 막 트레이너가 됐니?\n"
	.string "우리 둘 다 초심자구나!$"

Route102_Text_1B7B9D:: @ 81B7B9D
	.string "이길 수 있을 거 같아서\n"
	.string "말을 걸었던 건데!$"

Route102_Text_1B7BD0:: @ 81B7BD0
	.string "아직 한 번도 못 이겼어...\n"
	.string "빨리 이기고 싶다...$"

Route102_Text_1B7C05:: @ 81B7C05
	.string "앗! 눈이 마주쳤다!\n"
	.string "벌레포켓몬으로 상대해주마!$"

Route102_Text_1B7C40:: @ 81B7C40
	.string "지고 말았다!$"

Route102_Text_1B7C52:: @ 81B7C52
	.string "눈이 마주친 트레이너에게는\n"
	.string "승부를 거는 게 원칙이지!$"

Route102_Text_1B7C97:: @ 81B7C97
	.string "나는 계속 이겨서\n"
	.string "최강 트레이너가 될 거야!\p"
	.string "너도 협력해!$"

Route102_Text_1B7CEC:: @ 81B7CEC
	.string "내가 너한테\n"
	.string "협력해 준 것 같아...$"

Route102_Text_1B7D11:: @ 81B7D11
	.string "계속 이기기 위해서는\n"
    .string "포켓몬을 더 많이\l"
	.string "잡아야 할 것 같아!$"

Route103_Text_1B7D55:: @ 81B7D55
	.string "당신도 마음이 편안해지는\n"
	.string "향기에 이끌려 왔군요...$"

Route103_Text_1B7D8B:: @ 81B7D8B
	.string "제 향기에\n" 
	.string "넘어가지 않으셨군요...$"

Route103_Text_1B7DB2:: @ 81B7DB2
	.string "아로마란 향기를 말합니다...\n"
	.string "향기는 몸과 마음을 치유하지요$"

Route103_Text_1B7DF7:: @ 81B7DF7
	.string "루비: 나는 루비!\n"
	.string "이쪽은 여동생 루미!\l"
	.string "둘이서 같이 승부할 거야!$"

Route103_Text_1B7E3B:: @ 81B7E3B
	.string "루비: 져버렸쪄...$"

Route103_Text_1B7E50:: @ 81B7E50
	.string "루비: 두 명을 상대하려면\n"
	.string "여러 가지를 곰곰이 생각해야 해!$"

Route103_Text_1B7EAC:: @ 81B7EAC
	.string "루비: 어? 포켓몬을\n"
	.string "딱 1마리만 데리고 있구나!\l"
	.string "그럼 우리랑 승부할 수 없어!$"

Route103_Text_1B7EFB:: @ 81B7EFB
	.string "루미: 우리 둘은 하나\n"
	.string "같이 승부할 거야!$"

Route103_Text_1B7F20:: @ 81B7F20
	.string "루미: 져버렸쪄... 언니...$"

Route103_Text_1B7F40:: @ 81B7F40
	.string "루미: 언니랑 나는\n"
	.string "호흡이 딱 맞는데...\p"
	.string "져버렸쪄...$"

Route103_Text_1B7F8E:: @ 81B7F8E
	.string "루미: 우리랑 승부하고 싶으면\n"
	.string "포켓몬이 2마리 있어야 해!\l"
	.string "없으면 승부할 수 없어!$"

Route103_Text_1B7FE7:: @ 81B7FE7
	.string "루비: 나는 루비!\n"
	.string "이쪽은 여동생 루미!\l"
	.string "둘이서 같이 승부할 거야!$"

Route103_Text_1B802B:: @ 81B802B
	.string "루비: 분해...\n"
	.string "또 져버렸쪄...$"

Route103_Text_1B8053:: @ 81B8053
	.string "루비: 두 명을 상대하려면\n"
	.string "여러 가지를 곰곰이 생각해야 해!$"

Route103_Text_1B80AF:: @ 81B80AF
	.string "루비: 어? 포켓몬을\n"
	.string "딱 1마리만 데리고 있구나!\l"
	.string "그럼 우리랑 승부할 수 없어!$"

Route103_Text_1B80FE:: @ 81B80FE
	.string "루미: 우리 둘은 하나\n"
	.string "항상 같이 승부하고 있어!$"

Route103_Text_1B8123:: @ 81B8123
	.string "루미: 또 져버렸쪄...\n"
	.string "언니...$"

Route103_Text_1B814D:: @ 81B814D
	.string "루미: 언니랑 나는\n"
	.string "호흡이 딱 맞는데...\p"
	.string "왜 또 져버렸을까?$"

Route103_Text_1B81A1:: @ 81B81A1
	.string "루미: 우리랑 승부하고 싶으면\n"
	.string "포켓몬이 2마리 있어야 해!\l"
	.string "없으면 승부할 수 없어!$"

Route103_Text_1B81FA:: @ 81B81FA
	.string "낚싯줄이 엉켜서 진짜 짜증 난다!\n"
	.string "에라잇! 승부다!$"

Route103_Text_1B8258:: @ 81B8258
	.string "졌다!\n"
	.string "괜히 더 짜증 난다-!$"

Route103_Text_1B8281:: @ 81B8281
	.string "아오 열 받아...!$"

Route103_Text_1B82A9:: @ 81B82A9
	.string "나의 엄청나게 귀여운\n"
	.string "포켓몬을 보고 가시지!$"

Route103_Text_1B82EC:: @ 81B82EC
	.string "으아아...\n"
	.string "나의 귀여운 포켓몬이!$"

Route103_Text_1B830D:: @ 81B830D
	.string "나의 귀여운 포켓몬은\n"
	.string "패배한 모습도 귀엽군...$"

Route103_Text_1B8349:: @ 81B8349
	.string "이봐 너! 나의 귀여운 포켓몬이\n"
	.string "더 귀여워졌다!$"

Route103_Text_1B838C:: @ 81B838C
	.string "아아!\n"
	.string "나의 귀여운 포켓몬이!$"

Route103_Text_1B83A4:: @ 81B83A4
	.string "함께 있으면 있을수록\n"
	.string "포켓몬이 귀여워져서 참을 수가 없다!$"

Route104_Text_1B83E9:: @ 81B83E9
	.string "치선: 좋-아!\n"
	.string "우리들의 포켓몬과 승부하는 거예요!$"

Route104_Text_1B8414:: @ 81B8414
	.string "치선: 져버려서 너무 분해$"

Route104_Text_1B842C:: @ 81B842C
	.string "치선: 우와- 당신 정말 강해요!\n"
	.string "우리 더 열심히 수행할 거예요$"

Route104_Text_1B845C:: @ 81B845C
	.string "치선: 어라? 포켓몬이\n"
	.string "한 마리뿐이잖아요?!\l"
	.string "그럼 우리랑 승부할 수 없어요!\p"
	.string "포켓몬이 한 마리뿐이면\n"
	.string "포켓몬이 외롭잖아요! 너무 불쌍해요!$"

Route104_Text_1B84DB:: @ 81B84DB
	.string "우나: 우리들은 쌍둥이니까\n"
	.string "포켓몬 승부도 같이 하는 거예요!$"

Route104_Text_1B850D:: @ 81B850D
	.string "우나: 둘이서 같이 승부했는데도\n"
	.string "져버렸어요...$"

Route104_Text_1B853B:: @ 81B853B
	.string "우나: 더 포켓몬을 키워서\n"
	.string "당신처럼 강해질 거예요!$"

Route104_Text_1B8577:: @ 81B8577
	.string "우나: 우리랑 승부하고 싶은가요?\p"
	.string "그럼 포켓몬을\n"
	.string "두 마리를 데리고 있어야 해요!\l"
	.string "왜냐면 우린 진짜 강하니까!$"

Route104_Text_1B85EB:: @ 81B85EB
	.string "이제 와서 무엇을 숨기리!\n"
	.string "바로 이 몸이\l"
	.string "물포켓몬 전문가이시다!\p"
	.string "...응?\n"
	.string "모른다고?$"

Route104_Text_1B8637:: @ 81B8637
	.string "나름 꽤 강하다고 생각했었는데...\n"
	.string "나한테... 실망이야...$"

Route104_Text_1B8680:: @ 81B8680
	.string "낚시에 푹 빠져서\n"
	.string "포켓몬 키우는 걸 잊고 있었어...$"

Route104_Text_1B86BE:: @ 81B86BE
	.string "백사장에 발자국을 남기는 건\n"
	.string "진-짜 신-나!$"

Route104_Text_1B86E8:: @ 81B86E8
	.string "으엑-!\n"
	.string "신발에 모래가 들어갔어!$"

Route104_Text_1B871C:: @ 81B871C
	.string "백사장을 내 발자국으로\n"
	.string "가득 채우고 싶은데\l"
	.string "금방 사라져 버려...$"

Route104_Text_1B8770:: @ 81B8770
	.string "승부할까...?\n"
	.string "그냥 하지 말까...?\p"
	.string "에잇! 모르겠다! 배틀 시작이다!$"

Route104_Text_1B87A7:: @ 81B87A7
	.string "하지 말 걸 그랬어...$"

Route104_Text_1B87C3:: @ 81B87C3
	.string "어느 쪽을 선택할지 망설여질 때\n"
	.string "스스로 결정하지 않고\l"
	.string "다른 사람에게 맡기면\p"
	.string "결과가 어떻게 되든\n"
	.string "후회하게 돼...$"

Route104_Text_1B8839:: @ 81B8839
	.string "나랑 승부하자!$"

Route104_Text_1B8852:: @ 81B8852
	.string "으-으...\n"
	.string "이길 수 있을 거 같았는데$"

Route104_Text_1B8872:: @ 81B8872
	.string "내가 승부하기로 결정했던 거라\n"
	.string "졌어도 그냥 후련해!\p"
	.string "...물론 분하기도 하지만$"

Route104_Text_1B88D4:: @ 81B88D4
	.string "내가 직접 상대해 주지\n"
	.string "럭셔리한 이 몸이 말이야$"

Route104_Text_1B8911:: @ 81B8911
	.string "왜 이길 수 없는 거지...!?$"

Route104_Text_1B8925:: @ 81B8925
	.string "돈으로 이길 수 없는 것도 있다더니...\n"
	.string "그게 바로 포켓몬 승부구나...$"

Route104_Text_1B895E:: @ 81B895E
	.string "너에게 진 후로 포켓몬에 대해\n"
	.string "많이 공부했어!$"

Route104_Text_1B899E:: @ 81B899E
	.string "또 졌다...\n"
	.string "왜 이길 수 없는 거지...!?$"

Route104_Text_1B89C0:: @ 81B89C0
	.string "이렇게 돈이 많은 내가\n"
	.string "포켓몬에서는 이길 수 없다니...\p"
	.string "포켓몬이란 정말 심오하군...$"

Route104_Text_1B8A24:: @ 81B8A24
	.string "이렇게 당신과 만나게 된 것도\n" 
	.string "인연이겠죠\l"
	.string "저와 승부해주시겠어요?$"

Route104_Text_1B8A61:: @ 81B8A61
	.string "어머!$"

Route104_Text_1B8A69:: @ 81B8A69
	.string "만남은 곧 이별의 시작...\n"
	.string "또 어딘가에서 만나게 되겠지요$"

Route104_Text_1B8AA7:: @ 81B8AA7
	.string "또 만났군요\n"
	.string "저와 승부해주시겠어요?$"

Route104_Text_1B8AD9:: @ 81B8AD9
	.string "어머...\n"
	.string "최선을 다했는데...$"

Route104_Text_1B8B02:: @ 81B8B02
	.string "만남은 곧 이별의 시작...\n"
	.string "또 어딘가에서 만나게 되겠지요$"

Route105_Text_1B8B40:: @ 81B8B40
	.string "이 근처에\n"
	.string "이상한 바위가 있다는데\l"
	.string "넌 뭐 아는 거 없나?$"

Route105_Text_1B8B93:: @ 81B8B93
	.string "바위 생각만 하고 있었더니\n"
	.string "포켓몬은 생각하지 못했군...$"

Route105_Text_1B8BDE:: @ 81B8BDE
	.string "멋진 바위는\n"
	.string "몇 시간을 보고 있어도 질리지 않지...$"

Route105_Text_1B8C28:: @ 81B8C28
	.string "다행이야! 어린애가 물에\n"
	.string "빠진 줄 알고 걱정했어!\p"
	.string "멀쩡해 보이니 나랑 승부하자!$"

Route105_Text_1B8C99:: @ 81B8C99
	.string "꼬륵... 꼬륵...$"

Route105_Text_1B8CA9:: @ 81B8CA9
	.string "해변 쪽으로 팔을 흔들면\n"
	.string "그게 물에 빠졌다는 신호야!$"

Route105_Text_1B8CEE:: @ 81B8CEE
	.string "새파란 바다에서 헤엄치고 있으면\n"
	.string "정말 기분 최고지!$"

Route105_Text_1B8D23:: @ 81B8D23
	.string "졌다...\n"
	.string "마음에 시퍼런 멍이 들었어...$"

Route105_Text_1B8D45:: @ 81B8D45
	.string "바다가 파란 이유?!\p"
	.string "잿빛도시에 있는 박물관에서\n"
	.string "듣긴 들었는데\l"
	.string "금방 잊어버렸다!$"

Route105_Text_1B8D99:: @ 81B8D99
	.string "물속에 들어오면 몸이 가벼워져서\n"
	.string "왠지 날씬해진 것 같은 기분이 들어!$"

Route105_Text_1B8DDD:: @ 81B8DDD
	.string "둥실둥실...$"

Route105_Text_1B8DED:: @ 81B8DED
	.string "물속에서는 체중이\n"
	.string "10분의 1 정도가 돼\p"
	.string "그럼 지금 난...\n"
	.string "안 돼! 내 몸무게가 들통 나고 말아!$"

Route105_Text_1B8E66:: @ 81B8E66
	.string "파란 하늘...\n"
	.string "넓은 바다...\l"
	.string "정말 편하고 느긋해...$"

Route105_Text_1B8EA0:: @ 81B8EA0
	.string "느긋하게 있다가\n"
	.string "져버렸어-!$"

Route105_Text_1B8EBD:: @ 81B8EBD
	.string "“너랑 같이 있으면 편안해져”\n"
	.string "라는 말을 듣고 싶어\p"
	.string "후후후후...!$"

Route106_Text_1B8EF0:: @ 81B8EF0
	.string "바다낚시와 민물낚시\n"
	.string "넌 어느 쪽이 더 좋으냐?$"

Route106_Text_1B8F25:: @ 81B8F25
	.string "마치 바다낚시와 같은\n"
	.string "광활한 패배다!$"

Route106_Text_1B8F55:: @ 81B8F55
	.string "바다든 강이든 낚시는 최고다!\n"
	.string "너도 그렇게 생각하지 않나?!$"

Route106_Text_1B8FAC:: @ 81B8FAC
	.string "포켓몬을 왕창 낚았다!\n"
	.string "엄청난 승부를 펼쳐주마-!$"

Route106_Text_1B8FF5:: @ 81B8FF5
	.string "또 광활한 패배다-!$"

Route106_Text_1B9011:: @ 81B9011
	.string "이기든 지든 포켓몬은 최고다!\n"
	.string "너도 그렇게 생각하지 않나?!$"

Route106_Text_1B9052:: @ 81B9052
	.string "다들 화장실에 가고 싶을 때는\n"
	.string "어떻게 하는 걸까...?\p"
	.string "화장실에 가 있는 동안 월척이\n"
	.string "걸릴지도 모른다고 생각하면...$"

Route106_Text_1B90D3:: @ 81B90D3
	.string "화장실에 안 가고 참고 있어서\n"
	.string "진 거야 분명히...$"

Route106_Text_1B910A:: @ 81B910A
	.string "으앗! 월척을\n"
	.string "낚을 수 있을 것 같은 예감이...!$"

Route106_Text_1B913D:: @ 81B913D
	.string "음핫핫핫!\n"
	.string "육지에서는 빨리 달릴 수 없지만\l"
	.string "물속에서는 지지 않는다!$"

Route106_Text_1B917F:: @ 81B917F
	.string "제가 졌습니다-!$"

Route106_Text_1B918A:: @ 81B918A
	.string "수영이라면\n"
	.string "지지 않을 자신이 있는데...$"

Route106_Text_1B91AC:: @ 81B91AC
	.string "바다는 내 구역이나 마찬가지야!\n"
	.string "어린애라고 봐주지 않겠어!$"

Route106_Text_1B91F8:: @ 81B91F8
	.string "설마\n"
	.string "정말 안 봐준 거야?$"

Route106_Text_1B9222:: @ 81B9222
	.string "흔들리는 파도에\n"
	.string "몸을 싣고 떠도는 게 좋아\p"
	.string "너도 해볼래?$"

Route107_Text_1B926B:: @ 81B926B
	.string "흠냐흠냐...\p"
	.string "적당한 파도에 몸을 맡겼더니\n"
	.string "기분이 좋아서 깜빡 졸고 말았군!$"

Route107_Text_1B92B7:: @ 81B92B7
	.string "아하하... 졌다...\n"
	.string "다시 잠이나 자야겠어...$"

Route107_Text_1B92E7:: @ 81B92E7
	.string "바다 위에 떠서 파도에 몸을 맡기면\n"
	.string "꼭 푹신푹신한 침대 위에\l"
	.string "누워 있는 느낌이야!$"

Route107_Text_1B933A:: @ 81B933A
	.string "바다는 내 구역이나 마찬가지다!\n"
	.string "승부하자!$"

Route107_Text_1B9365:: @ 81B9365
	.string "홈그라운드에서 져버리다니...\n"
	.string "쇼크다!$"

Route107_Text_1B938E:: @ 81B938E
	.string "커다란 꿈을 가득 채우고-\n"
	.string "드넓은 바다를 한번 헤엄쳐 볼까-?\p"
	.string "자 그럼!\n"
	.string "계속 헤엄치는 거다!$"

Route107_Text_1B93EB:: @ 81B93EB
	.string "드넓은 바다를 헤엄치고 있었더니\n"
	.string "포켓몬이 엄청 강해졌다!$"

Route107_Text_1B9429:: @ 81B9429
	.string "쇼크다!!\p"
	.string "포켓몬은 강해졌지만\n"
	.string "정작 트레이너인 난 약한 그대로인 건가?!$"

Route107_Text_1B9477:: @ 81B9477
	.string "배틀 속에서 익힌 모든 것들이\n"
	.string "트레이너의 실력으로 이어진다!\l"
	.string "드넓은 바다가 그렇게 말했다고-!$"

Route107_Text_1B94C8:: @ 81B94C8
	.string "무로마을이라는\n"
	.string "작은 마을을 알고 있니?$"

Route107_Text_1B94F2:: @ 81B94F2
	.string "아 정말 이게 뭐야-!$"

Route107_Text_1B94FF:: @ 81B94FF
	.string "무로마을에 있는 무로집회소에서\n"
	.string "이상한 말이 유행하고 있어!$"

Route107_Text_1B9538:: @ 81B9538
	.string "나랑 승부하고 싶은 거야?\n"
	.string "좋아! 상대해 줄게!$"

Route107_Text_1B956B:: @ 81B956B
	.string "나는 전혀 상대가 안 되는구나!$"

Route107_Text_1B9589:: @ 81B9589
	.string "넌 앞으로도 계속 강해질 것 같아\n"
	.string "나도 열심히 해야지!$"

Route107_Text_1B95CB:: @ 81B95CB
	.string "유미: 우리 남매 둘이서\n"
	.string "상대해줄게!$"

Route107_Text_1B95FB:: @ 81B95FB
	.string "유미: 굉장해\n"
	.string "레벨이 다른 실력이야$"

Route107_Text_1B9630:: @ 81B9630
	.string "유미: 넌 같이 바다로\n"
	.string "놀러 갈 만한\l"
	.string "친구가 있니?$"

Route107_Text_1B9672:: @ 81B9672
	.string "유미: 우리랑 승부할 거면\n"
	.string "포켓몬을 더 데려오라고$"

Route107_Text_1B96AB:: @ 81B96AB
	.string "빈: 항상 둘이서\n"
	.string "포켓몬 승부를 하고 있어!\p"
	.string "...항상 내가 지고 있지만\n"
	.string "2대 2라면 널 이길 수 있어!$"

Route107_Text_1B9707:: @ 81B9707
	.string "빈: 으아-\n"
	.string "레벨이 달라도 너무 다르다$"

Route107_Text_1B9735:: @ 81B9735
	.string "빈: 누나한테 받아서 키운\n"
	.string "내 포켓몬은\l"
	.string "나의 소중한 파트너야!$"

Route107_Text_1B9788:: @ 81B9788
	.string "빈: 우리랑 승부하고 싶으면\n"
	.string "포켓몬을 더 데려와!$"

Route108_Text_1B97C3:: @ 81B97C3
	.string "내 꿈은 전 세계에 있는\n"
	.string "7곳의 모든 바다에서\l"
	.string "헤엄치는 거야!!$"

Route108_Text_1B97EF:: @ 81B97EF
	.string "이래서는\n"
	.string "7곳의 모든 바다를 헤엄칠 수 없어...$"

Route108_Text_1B9823:: @ 81B9823
	.string "바다 포켓몬과 노는 것도\n"
	.string "헤엄치고 있을 때의\l"
	.string "즐거움 중 하나야!$"

Route108_Text_1B9864:: @ 81B9864
	.string "이봐 너!\n"
	.string "너도 버려진 배에 가는 거야?$"

Route108_Text_1B989F:: @ 81B989F
	.string "가라앉는다!\n"
	.string "꼬륵... 꼬륵...$"

Route108_Text_1B98BC:: @ 81B98BC
	.string "어떤 사람들은 버려진 배 안으로\n"
	.string "들어가기까지 해!$"

Route108_Text_1B98EC:: @ 81B98EC
	.string "거짓말쟁이 그 사람이 말했었어...\n"
	.string "비키니 입은 모습이\l"
	.string "정말 예쁘다고...$"

Route108_Text_1B992C:: @ 81B992C
	.string "싫어- 져버렸어-!$"

Route108_Text_1B9935:: @ 81B9935
	.string "거짓말이라도\n"
	.string "예쁘다는 말을 듣고 싶은\l"
	.string "복잡한 여자의 마음...$"

Route108_Text_1B9986:: @ 81B9986
	.string "바다가 너무 좋아!\n"
	.string "헤엄치고 있으면\l"
	.string "슬픈 일들을 잊어버릴 수 있어!$"

Route108_Text_1B99BB:: @ 81B99BB
	.string "승부에서 지면\n"
	.string "스트레스가 쌓여-!$"

Route108_Text_1B99E9:: @ 81B99E9
	.string "스트레스는 수영으로 발산할 거야!\n"
	.string "건강에도 최고지-!$"

Route109_Text_1B9A1C:: @ 81B9A1C
	.string "흐아아압!\n"
	.string "멋지게 갈라진 이 복근을 봐랏-!!$"

Route109_Text_1B9A59:: @ 81B9A59
	.string "흐아아압-!!\n"
	.string "져버렸다-!!$"

Route109_Text_1B9A6D:: @ 81B9A6D
	.string "흐아아압!!\p"
	.string "복근과 포켓몬 승부는\n"
	.string "아무 상관이 없다앗-!!$"

Route109_Text_1B9AAD:: @ 81B9AAD
	.string "자외선 차단 잘 하고 있니?$"

Route109_Text_1B9AD9:: @ 81B9AD9
	.string "아따따따가워!$"

Route109_Text_1B9AEB:: @ 81B9AEB
	.string "볼 주변이 제일\n"
	.string "타기 쉬워!$"

Route109_Text_1B9B11:: @ 81B9B11
	.string "전 세계의 항구를 찾아가 봤지만\n"
	.string "잿빛도시는 최고의 항구도시다!$"

Route109_Text_1B9B57:: @ 81B9B57
	.string "너도 최고군...$"

Route109_Text_1B9B68:: @ 81B9B68
	.string "최고의 항구에는\n"
	.string "최고의 트레이너가 있었군...$"

Route109_Text_1B9B91:: @ 81B9B91
	.string "으으으...\n"
	.string "지금 승부하려고? 나랑?$"

Route109_Text_1B9BAE:: @ 81B9BAE
	.string "우웨에에엑...$"

Route109_Text_1B9BD3:: @ 81B9BD3
	.string "원래 평소엔 더 강해!\n"
	.string "뱃멀미 때문에\l"
	.string "상태가 안 좋을 뿐이야!\p"
	.string "선원이긴 하지만...$"

Route109_Text_1B9C23:: @ 81B9C23
	.string "목마르다...\n"
	.string "바다의 집에서\l"
	.string "미네랄사이다가 마시고 싶어...$"

Route109_Text_1B9C65:: @ 81B9C65
	.string "으-으...$"

Route109_Text_1B9C6E:: @ 81B9C6E
	.string "배도 고파오니까...\n"
	.string "튜브가 커다란 도넛으로\l"
	.string "보이기 시작했어$"

Route109_Text_1B9CB3:: @ 81B9CB3
	.string "배는 고프지만\n"
	.string "승부할 힘은 남아 있어!$"

Route109_Text_1B9CEB:: @ 81B9CEB
	.string "졌다...\n"
	.string "배가 고파서 진 거야$"

Route109_Text_1B9D10:: @ 81B9D10
	.string "백사장에서 먹으면\n"
	.string "뭐든지 다 맛있게 느껴져$"

Route109_Text_1B9D54:: @ 81B9D54
	.string "비치파라솔은\n"
	.string "커다란 꽃처럼 보여-!$"

Route109_Text_1B9D87:: @ 81B9D87
	.string "엄마아-!$"

Route109_Text_1B9D8E:: @ 81B9D8E
	.string "하늘에서 모래 해변을 보면\n"
	.string "꽃밭처럼 보여!$"

Route109_Text_1B9DD8:: @ 81B9DD8
	.string "이제 지지 않을 거야!\n"
	.string "이기기 위해 튜브도 끼고 있으니까!$"

Route109_Text_1B9E16:: @ 81B9E16
	.string "엄마아-!$"

Route109_Text_1B9E1D:: @ 81B9E1D
	.string "튜브를 가지고 있으면\n"
	.string "나랑 포켓몬이 더 귀여워 보여!$"

Route109_Text_1B9E60:: @ 81B9E60
	.string "튜브가 없으면 헤엄칠 수 없지만\n"
	.string "포켓몬이라면 절대 지지 않아!$"

Route109_Text_1B9EA1:: @ 81B9EA1
	.string "튜브 때문에 진 건가?$"

Route109_Text_1B9ECA:: @ 81B9ECA
	.string "튜브는 내 패션의 완성이니까\n"
	.string "놓을 수가 없어$"

Route109_Text_1B9F07:: @ 81B9F07
	.string "지나가는 트레이너님!\n"
	.string "저랑 승부해쥬세여!$"

Route109_Text_1B9F31:: @ 81B9F31
	.string "너무 강했쪄여...$"

Route109_Text_1B9F44:: @ 81B9F44
	.string "어떻게 하면\n"
	.string "그렇게 강해질 쭈 있나여...?$"

Route109_Text_1B9F65:: @ 81B9F65
	.string "으하하하! 이 아저씨가\n"
	.string "대어를 낚는 걸 잘 보라고!$"

Route109_Text_1B9F9C:: @ 81B9F9C
	.string "아저씬 져버렸군...$"

Route109_Text_1B9FB7:: @ 81B9FB7
	.string "네가 진짜 대어인 것 같구나!\n"
	.string "분명 앞으로\l"
	.string "더욱 큰물에서 놀게 될 거다!$"

Route109_Text_1B9FF6:: @ 81B9FF6
	.string "리키: 흠- 이를 어쩌지?\p"
	.string "둘만의 시간을\n"
	.string "방해받고 싶지 않았는데 말이야$"

Route109_Text_1BA052:: @ 81BA052
	.string "리키: 흠- 이를 어쩌지?$"

Route109_Text_1BA069:: @ 81BA069
	.string "리키: 흠- 우리가 여기 있다고\n"
	.string "아무한테도 말하지 말아줘!\l"
	.string "여긴 우리 둘만의 세계니까 말이야!$"

Route109_Text_1BA0BF:: @ 81BA0BF
	.string "리키: 우리들은 러브러브니까\n"
	.string "우리들의 포켓몬도\l"
	.string "2마리가 같이 배틀하게 할 거야!$"

Route109_Text_1BA114:: @ 81BA114
	.string "지목: 우리 둘 사이가 뜨거우니까\n"
	.string "호연지방이 뜨거운 거예요옹-!$"

Route109_Text_1BA15F:: @ 81BA15F
	.string "지목: 나 때문에 진 거야...\n"
	.string "리키가 날 싫어하게 되면 어떡하지...$"

Route109_Text_1BA193:: @ 81BA193
	.string "지목: 저기 리키\n"
	.string "나한테 화낼 거야?\l"
	.string "화내면 나 싫어-$"

Route109_Text_1BA1D0:: @ 81BA1D0
	.string "지목: 우리들은 러브러브니까\n"
	.string "우리들의 포켓몬도\l"
	.string "2마리가 같이 배틀하게 할 거야!$"

Route110_Text_1BA22C:: @ 81BA22C
	.string "어이쿠 위험했다!\n"
	.string "자전거 레이스에\l"
	.string "익숙하지 않은 모양이군?!$"

Route110_Text_1BA264:: @ 81BA264
	.string "끼-익!\n"
	.string "브레이크가 고장 났다!$"

Route110_Text_1BA27C:: @ 81BA27C
	.string "타이어 펑크나\n"
	.string "브레이크 고장은 부상의 원인이지\l"
	.string "꼼꼼하게 점검해야 한다$"

Route110_Text_1BA2D4:: @ 81BA2D4
	.string "헤이 유-!\n"
	.string "내 스피드를 따라잡을 수 있을까?!$"

Route110_Text_1BA2FC:: @ 81BA2FC
	.string "오 마이 갓-!$"

Route110_Text_1BA30C:: @ 81BA30C
	.string "스피드만으론 포켓몬 승부\n"
	.string "이길 수 없습니다-! 반성하겠습니다-!$"

Route110_Text_1BA352:: @ 81BA352
	.string "자전거 스피드가 빨라져도\n"
	.string "서두르면 안 돼!$"

Route110_Text_1BA379:: @ 81BA379
	.string "포켓몬 승부도\n"
	.string "서두르면 안 되지...$"

Route110_Text_1BA3A5:: @ 81BA3A5
	.string "서두르지 말고 여유를 가지자\n"
	.string "시간은 충분하니까!$"

Route110_Text_1BA3EF:: @ 81BA3EF
	.string "오! 너무 빠른 거 아니야?\n"
	.string "잠깐 느긋하게 승부하자고!$"

Route110_Text_1BA432:: @ 81BA432
	.string "별로 서두르지도 않았는데...\n"
	.string "왠지 자꾸 져버리네...$"

Route110_Text_1BA456:: @ 81BA456
	.string "서두르지 말고 여유를 가지자\n"
	.string "시간은 충분하니까!$"

Route110_Text_1BA4A0:: @ 81BA4A0
	.string "트라이애슬론은 하드한 스포츠\n"
	.string "수영, 자전거, 마라톤의\l"
	.string "3종목을 소화하는 거야!$"

Route110_Text_1BA50F:: @ 81BA50F
	.string "포켓몬 승부도 하드하네!$"

Route110_Text_1BA52E:: @ 81BA52E
	.string "지쳤으니까 한숨 돌려야겠어\n"
	.string "휴식은 중요하다고!$"

Route110_Text_1BA573:: @ 81BA573
	.string "자전거 타면서\n"
	.string "포켓몬 승부하는 것도 좋네!$"

Route110_Text_1BA5A1:: @ 81BA5A1
	.string "우와-\n"
	.string "어째서 그렇게 강한 거야?$"

Route110_Text_1BA5C4:: @ 81BA5C4
	.string "혹시 기록에\n"
	.string "도전하고 있었던 거야?\p"
	.string "방해해서 미안해-$"

Route110_Text_1BA5FF:: @ 81BA5FF
	.string "자전거를 계속 밟아서\n"
	.string "허벅지가 딴딴해졌어$"

Route110_Text_1BA63C:: @ 81BA63C
	.string "근육이 걱정이야...$"

Route110_Text_1BA65F:: @ 81BA65F
	.string "체육관 배지를 가지고 있어?\n"
	.string "당연히 강하겠네!$"

Route110_Text_1BA699:: @ 81BA699
	.string "너의 작전은 이미\n"
	.string "모두 나에게 보였다!\l"
	.string "내가 질 이유는 없지!$"

Route110_Text_1BA6D2:: @ 81BA6D2
	.string "나 자신의 패배는 보이지 않았다...!$"

Route110_Text_1BA6F8:: @ 81BA6F8
	.string "너의 미래가 보인다...\p"
	.string "흠...\n"
	.string "아주 밝은 빛이 보이는군...!$"

Route110_Text_1BA72D:: @ 81BA72D
	.string "오호호호홋!\n"
	.string "저의 미라클을 보여드리죠!$"

Route110_Text_1BA759:: @ 81BA759
	.string "미라클하게 졌다-앗!$"

Route110_Text_1BA76C:: @ 81BA76C
	.string "저에게 이긴 것이 미라클...\n"
	.string "그래 기적이에요!\l"
	.string "언제나 이긴다고 생각하지 마세요!$"

Route110_Text_1BA7D2:: @ 81BA7D2
	.string "네 포켓몬을 보여주지 않을래?\n"
	.string "살짝 보기만 할 테니까 제발!$"

Route110_Text_1BA803:: @ 81BA803
	.string "도감을 완성하고 싶었는데...!$"

Route110_Text_1BA829:: @ 81BA829
	.string "처음 보는 포켓몬을 만나면\n"
	.string "내 수집욕이 불타오르지!$"

Route110_Text_1BA877:: @ 81BA877
	.string "저기 있잖아\n"
	.string "새로운 포켓몬은 잡았니?\p"
	.string "괜찮으면 포켓몬을\n"
	.string "보여주지 않을래?\l"
	.string "살짝 보기만 할 테니까 제발!$"

Route110_Text_1BA8CD:: @ 81BA8CD
	.string "네 포켓몬...\n"
	.string "부럽다...$"

Route110_Text_1BA8E9:: @ 81BA8E9
	.string "아-! 희귀한 포켓몬은\n"
	.string "무조건 몽땅 다 내 손에 넣고 싶어-!$"

Route110_Text_1BA913:: @ 81BA913
	.string "에-잇!\n"
	.string "뒤에서 보지 말라고-!!$"

Route110_Text_1BA93C:: @ 81BA93C
	.string "졌다!\n"
	.string "분하닷!!$"

Route110_Text_1BA94A:: @ 81BA94A
	.string "수면에 떠 있는 낚시찌를\n"
	.string "계속 바라본다...\l"
	.string "집중력이 중요해$"

Route110_Text_1BA990:: @ 81BA990
	.string "오호홋! 소중한 포켓몬을\n"
	.string "자랑하기 위해서라면\l"
	.string "어디든 갈 수 있어요$"

Route110_Text_1BA9D0:: @ 81BA9D0
	.string "어머 왜 이러니 싫다-$"

Route110_Text_1BA9E9:: @ 81BA9E9
	.string "승부보다는\n"
	.string "콘테스트에 올인할까?$"

Route110_Text_1BAA2D:: @ 81BAA2D
	.string "오호홋! 소중한 포켓몬이라면\n"
	.string "몇 번이든 계속 자랑하겠어요!$"

Route110_Text_1BAA76:: @ 81BAA76
	.string "어머 왜 이러니 싫다-$"

Route110_Text_1BAA8F:: @ 81BAA8F
	.string "콘테스트도 좋지만\n"
	.string "승부하는 것도 좋아해요!$"

Route110_Text_1BAAC3:: @ 81BAAC3
	.string "이 주변 풀숲에서\n"
	.string "멋있는 포켓몬을 발견했어!$"

Route110_Text_1BAAF7:: @ 81BAAF7
	.string "멋있기만 하면 안 되는 건가...$"

Route110_Text_1BAB19:: @ 81BAB19
	.string "방금 막 잡은 포켓몬으론\n"
	.string "배틀을 잘 할 수 없어!$"

Route111_Text_1BAB4B:: @ 81BAB4B
	.string "오! 고고고글 잘 어울리네!\n"
	.string "하지만 내 쪽이 더 잘 어울리지?\l"
	.string "어느 쪽이 더 잘 어울리는지 승부다!$"

Route111_Text_1BABC7:: @ 81BABC7
	.string "고고고글로 주변이\n"
	.string "잘 보이지 않았어$"

Route111_Text_1BAC10:: @ 81BAC10
	.string "고고고글이 있으면\n"
	.string "사막의 모래바람도 괜찮으니까\l"
	.string "그것만으로도 기뻐!$"

Route111_Text_1BAC60:: @ 81BAC60
	.string "상당히 눈이 따끔따끔하지만\n"
	.string "사막 한가운데에서도 피크닉!\p"
	.string "어떤 곳이라도 트레이너가 있으니까\n"
	.string "승부도 할 수 있어!$"

Route111_Text_1BACC5:: @ 81BACC5
	.string "아야-앙! 미워-!$"

Route111_Text_1BACD8:: @ 81BACD8
	.string "모래바람 속에서 배틀할 때는\n"
	.string "포켓몬의 체력을\l"
	.string "잘 신경 쓰지 않으면\l"
	.string "금방 기절하고 말아!$"

Route111_Text_1BAD4B:: @ 81BAD4B
	.string "고고고글을 쓰고 있으면\n"
	.string "왠지 히어로가 된 기분이야!\l"
	.string "지금의 나라면\l"
	.string "누구라도 이길 수 있어!$"

Route111_Text_1BADA3:: @ 81BADA3
	.string "기분만으로는 이길 수 없는 건가...$"

Route111_Text_1BADC2:: @ 81BADC2
	.string "언젠가는 진짜 히어로가 될 거야!\n"
	.string "그러기 위해 좀 더 힘내서\l"
	.string "포켓몬과 스스로를 단련해야지!$"

Route111_Text_1BAE24:: @ 81BAE24
	.string "사막에서 화석이\n"
	.string "발견되었다고 들었는데\l"
	.string "어디에 있는지 알고 있어?$"

Route111_Text_1BAE6E:: @ 81BAE6E
	.string "아직 부족한 것 같아...$"

Route111_Text_1BAE81:: @ 81BAE81
	.string "사막에서 화석이 발견되었다는 건\n"
	.string "여기는 옛날에 바다였다는 것이겠지!$"

Route111_Text_1BAEC9:: @ 81BAEC9
	.string "유적 찾아 30년!\n"
	.string "그런 이 몸과 겨루겠다고?$"

Route111_Text_1BAF14:: @ 81BAF14
	.string "유적은 찾고 있었지만\n"
	.string "강한 포켓몬은 찾지 않았어$"

Route111_Text_1BAF5B:: @ 81BAF5B
	.string "유적 찾아 30년!\p"
	.string "아니지, 이제 40년인가?\n"
	.string "응? 몇 년이었더라?$"

Route111_Text_1BAFC1:: @ 81BAFC1
	.string "유적 찾아 30년!\p"
	.string "아니지! 유적 찾아 40년!\n"
	.string "그런 이 몸과 겨루겠다고?$"

Route111_Text_1BB034:: @ 81BB034
	.string "유적도 못 찾겠고\n"
	.string "강한 포켓몬도 못 찾겠다$"

Route111_Text_1BB070:: @ 81BB070
	.string "유적 찾아 30년!\p"
	.string "아니지 벌써 한\n"
	.string "40년은 찾아다녔나?\p"
	.string "음... 50년인 것 같기도 하고...\n"
	.string "응? 몇 년이었더라??$"

Route111_Text_1BB111:: @ 81BB111
	.string "나도 힘이 넘치고!\n"
	.string "내 포켓몬도 힘이 넘친다!$"

Route111_Text_1BB140:: @ 81BB140
	.string "포켓몬이 기진맥진해졌다...$"

Route111_Text_1BB15B:: @ 81BB15B
	.string "힘이 넘쳐서 달려 나가고 있는\n"
	.string "트레이너를 보면\l"
	.string "나도 모르게 그쪽을 보게 되지!$"

Route111_Text_1BB199:: @ 81BB199
	.string "어디로 가고 있는지는 모르겠지만\n"
	.string "잠깐 승부하지 않을래?$"

Route111_Text_1BB1D8:: @ 81BB1D8
	.string "얄미울 정도로 강하구나?!$"

Route111_Text_1BB1F6:: @ 81BB1F6
	.string "굴뚝산에 가볼까 하고\n"
	.string "생각하고 있었는데\l"
	.string "이 주변 경치도 정말 좋아!$"

Route111_Text_1BB250:: @ 81BB250
	.string "나 자신을 단련시키기 위해\n"
	.string "만나는 모든 사람들에게\l"
	.string "승부를 걸고 있쑵니돠!$"

Route111_Text_1BB27E:: @ 81BB27E
	.string "졌쑵니돠...!$"

Route111_Text_1BB290:: @ 81BB290
	.string "당신처럼 강한 트레이너를\n"
	.string "이길 수 있을 때까지\l"
	.string "오직 수행만이 있을 뿐입니돠!$"

Route111_Text_1BB2E3:: @ 81BB2E3
	.string "네가 포켓몬을 얼마나\n"
	.string "단련시키고 있는지 확인해 주마!$"

Route111_Text_1BB313:: @ 81BB313
	.string "역시!\n"
	.string "상당히 단련시켰군!$"

Route111_Text_1BB33E:: @ 81BB33E
	.string "포켓몬도 트레이너도\n"
	.string "배틀을 통해 많은 것을 배운다!\p"
	.string "중요한 건\n"
	.string "패배해도 포기하지 않는 것이다!$"

Route111_Text_1BB3A7:: @ 81BB3A7
	.string "우리들은 더욱 높은 곳을 목표로\n"
	.string "여기서 포켓몬을 단련시키고 있다\l"
	.string "너도 같이 수행하자고!$"

Route111_Text_1BB3FA:: @ 81BB3FA
	.string "꽤 하는군!$"

Route111_Text_1BB40E:: @ 81BB40E
	.string "그렇게 강하니\n"
	.string "포켓몬리그에 도전하는 게 좋겠군!$"

Route111_Text_1BB44F:: @ 81BB44F
	.string "어머, 네 포켓몬\n"
	.string "상당히 강해 보여!\l"
	.string "내 상대를 해주지 않겠어? 부탁할게!$"

Route111_Text_1BB49F:: @ 81BB49F
	.string "강해 보이는 게 아니라\n"
	.string "진짜 강하구나!$"

Route111_Text_1BB4CE:: @ 81BB4CE
	.string "나도 더 노력해서\n"
	.string "포켓몬을 키우려고 하는데\l"
	.string "아직 해야 할 일이 산더미야!$"

Route111_Text_1BB529:: @ 81BB529
	.string "포켓몬은 쓰는 기술에 따라\n"
	.string "강해지기도 하고 약해지기도 해!\p"
	.string "네 포켓몬은\n"
	.string "어떤 기술을 배우고 있니?$"

Route111_Text_1BB5A2:: @ 81BB5A2
	.string "좋은 기술을 배우고 있구나!$"

Route111_Text_1BB5C1:: @ 81BB5C1
	.string "내 포켓몬은 진화시키지 말고\n"
	.string "먼저 기술을 배우게 하고 나서\l"
	.string "키우는 편이 좋았으려나?$"

Route112_Text_1BB619:: @ 81BB619
	.string "와핫핫!\n"
	.string "어떠냐?\l"
	.string "나와 승부하지 않겠나?\l"
	.string "와핫핫!$"

Route112_Text_1BB655:: @ 81BB655
	.string "졌다...\n"
	.string "와핫핫!$"

Route112_Text_1BB667:: @ 81BB667
	.string "재미있는 게 하나도 없는데\n"
	.string "우, 웃음이 멈추질 않는닷!\l"
	.string "와핫핫핫!$"

Route112_Text_1BB6A0:: @ 81BB6A0
	.string "등산으로 단련된 나의 다리와 허리는\n"
	.string "어지간해선 절대 무너지지 않는다!$"

Route112_Text_1BB707:: @ 81BB707
	.string "아...\n"
	.string "다리에 쥐가 났다...$"

Route112_Text_1BB721:: @ 81BB721
	.string "몇십 킬로나 되는 짐을 지고\n"
	.string "산길을 계속 걷는다\l"
	.string "몸이 튼튼해지지 않을 수가 없지!$"

Route112_Text_1BB7C7:: @ 81BB7C7
	.string "등산으로 단련된 몸이니만큼\n"
	.string "엄청 파워풀하다고!$"

Route112_Text_1BB801:: @ 81BB801
	.string "파워에서 진 건가?$"

Route112_Text_1BB819:: @ 81BB819
	.string "굴뚝산 위에는\n"
	.string "굉장한 트레이너가 있다고 하더군!\l"
	.string "다음에 승부하러 가볼 생각이다!$"

Route112_Text_1BB893:: @ 81BB893
	.string "난 강해...\n"
	.string "진다고 해도 울지 않아...!$"

Route112_Text_1BB8B6:: @ 81BB8B6
	.string "으아---앙!$"

Route112_Text_1BB8BE:: @ 81BB8BE
	.string "엄마가 보고 싶어서\n"
	.string "우는 게 아니야!\l"
	.string "훌쩍...$"

Route112_Text_1BB8F0:: @ 81BB8F0
	.string "피크닉 하면 노래지!\n"
	.string "자아- 다 같이 노래합시다!$"

Route112_Text_1BB942:: @ 81BB942
	.string "이렇게 강하다니...!$"

Route112_Text_1BB958:: @ 81BB958
	.string "노래도 포켓몬 승부도\n"
	.string "잘하고 못하고는 상관없어요!\p"
	.string "즐기는 게 이기는 거예요!$"

Route113_Text_1BB9BA:: @ 81BB9BA
	.string "이 근처가 비교적 시원한 이유가\n"
	.string "뭔지 아니?$"

Route113_Text_1BB9E6:: @ 81BB9E6
	.string "으아-!\n"
	.string "져버렸다-!$"

Route113_Text_1BB9FB:: @ 81BB9FB
	.string "화산재가 햇빛을\n"
	.string "가리고 있어서 서늘한 거야!\p"
	.string "더위를 잘 타는 나는\n"
	.string "덕분에 살 것 같아!$"

Route113_Text_1BBA62:: @ 81BBA62
	.string "산이 분화한다는 건\n"
	.string "지구가 살아 있다는 증거지!$"

Route113_Text_1BBA9B:: @ 81BBA9B
	.string "너 진짜 강하구나-!$"

Route113_Text_1BBAB7:: @ 81BBAB7
	.string "콜록콜록 우엑-!\n"
	.string "재가 폐에 들어갔어\p"
	.string "기침이 멈추질 않아...\n"
	.string "콜록... 콜록...$"

Route113_Text_1BBB27:: @ 81BBB27
	.string "저의 소중한 둔타에게\n"
	.string "화산재가 떨어지지 않도록\l"
	.string "파라솔을 들고 있답니다$"

Route113_Text_1BBB7A:: @ 81BBB7A
	.string "하아... 하아...\n"
	.string "이제 지쳤어요...$"

Route113_Text_1BBB9A:: @ 81BBB9A
	.string "정말 강하시군요\n"
	.string "정말 감동받았어요$"

Route113_Text_1BBBCE:: @ 81BBBCE
	.string "오랜만이에요\n"
	.string "시간 있으시면 승부하시겠어요?$"

Route113_Text_1BBC0D:: @ 81BBC0D
	.string "훌륭해요$"

Route113_Text_1BBC1C:: @ 81BBC1C
	.string "여전히 강하시군요\n"
	.string "정말 감동받았어요$"

Route113_Text_1BBC59:: @ 81BBC59
	.string "재 속에서 짜잔!!\n"
	.string "소인과 승부해주시오!$"

Route113_Text_1BBC90:: @ 81BBC90
	.string "지고 말았소$"

Route113_Text_1BBCAB:: @ 81BBCAB
	.string "좀 더 숨는 방법을 연구해야지\n"
	.string "그럼 이만 실례하겠소$"

Route113_Text_1BBCE6:: @ 81BBCE6
	.string "재가 없어도 짜자자잔!!\n"
	.string "소인과 승부해주시오!$"

Route113_Text_1BBD1D:: @ 81BBD1D
	.string "지고 말았소$"

Route113_Text_1BBD38:: @ 81BBD38
	.string "숨는 방법은 좋았지만\n"
	.string "승부가 좀 부족했어...\p"
	.string "그럼 이만 실례하겠소$"

Route113_Text_1BBD92:: @ 81BBD92
	.string "발견해 줘서 고마워!\n"
	.string "하지만 승부는 이야기가 다르지!$"

Route113_Text_1BBDC6:: @ 81BBDC6
	.string "비밀 기술! 화산재 속에 숨기!\p"
	.string "...응? 벌써 끝났나?$"

Route113_Text_1BBE1D:: @ 81BBE1D
	.string "숨어 있으면 뭐가 걱정이 되느냐고?\n"
	.string "아무도 지나가지 않으면 외로워...$"

Route113_Text_1BBE65:: @ 81BBE65
	.string "나나: 둘이서 화산재 모으고 있어\n"
	.string "근데 포켓몬 승부도 할 거야!$"

Route113_Text_1BBEA1:: @ 81BBEA1
	.string "나나: 져버렸다\n"
	.string "재미없으니까 화산재 모아야지!$"

Route113_Text_1BBEE4:: @ 81BBEE4
	.string "나나: 화산재 얼마나 모였을까?\n"
	.string "하양비드로 만들면 좋을 텐데!$"

Route113_Text_1BBF25:: @ 81BBF25
	.string "나나: 우리들은 2대 2로 싸우고 싶어\n"
	.string "그렇게 하지 않으면 져버리는걸!$"

Route113_Text_1BBF62:: @ 81BBF62
	.string "네네: 둘이서 화산재 모으고 있어\n"
	.string "근데 포켓몬 승부도 할 거야!$"

Route113_Text_1BBF9D:: @ 81BBF9D
	.string "네네: 이기지 못했어\n"
	.string "재미없으니까 화산재 모아야지!$"

Route113_Text_1BBFE2:: @ 81BBFE2
	.string "네네: 화산재 꽤 모였어!\n"
	.string "이제 하양비드로 만들 수 있어!$"

Route113_Text_1BC021:: @ 81BC021
	.string "네네: 우리들은 2대 2로 싸우고 싶어\n"
	.string "그렇게 하지 않으면 져버리는걸!$"

Route114_Text_1BC05B:: @ 81BC05B
	.string "얏호-!\p"
	.string "...\p"
	.string "네가 메아리 대신이 되어서\n"
	.string "얏호-! 라고 외쳐줘-!$"

Route114_Text_1BC0B5:: @ 81BC0B5
	.string "얏호-!$"

Route114_Text_1BC0C3:: @ 81BC0C3
	.string "어렸을 때는 메아리가\n"
	.string "건너편 산에 있는 성대모사 달인이\l"
	.string "얏호-! 라고 해주는 건 줄 알았어$"

Route114_Text_1BC125:: @ 81BC125
	.string "준비를 게을리하는 자는\n"
	.string "산에 오르지 마라!$"

Route114_Text_1BC163:: @ 81BC163
	.string "산은 무서운 곳이다...$"

Route114_Text_1BC184:: @ 81BC184
	.string "겨울 산에서는 눈사태나 눈보라로\n"
	.string "조난을 당할 위험이 크다!$"

Route114_Text_1BC1C8:: @ 81BC1C8
	.string "캠핑의 즐거움은\n"
	.string "낚시와 불꽃놀이 그리고 담력 훈련!\p"
	.string "하지만 제일 즐거운 건\n"
	.string "포켓몬 승부지!$"

Route114_Text_1BC23F:: @ 81BC23F
	.string "너무 강하다-앗!$"

Route114_Text_1BC24F:: @ 81BC24F
	.string "난 말이지 포켓몬과 같이\n"
	.string "캠핑을 할 수 있는 것만으로도 행복해$"

Route114_Text_1BC289:: @ 81BC289
	.string "식후의 운동!\n"
	.string "저와 승부합시다!$"

Route114_Text_1BC2BE:: @ 81BC2BE
	.string "져버렸다-!$"

Route114_Text_1BC2C6:: @ 81BC2C6
	.string "맛있는 밥도 먹었겠다\n"
	.string "이제 왠지 잠이 오기 시작하네요...$"

Route114_Text_1BC2F5:: @ 81BC2F5
	.string "우후후후후후...\n"
	.string "내 포켓몬과 승부하지 않을래?$"

Route114_Text_1BC327:: @ 81BC327
	.string "내, 내 포켓몬이...$"

Route114_Text_1BC337:: @ 81BC337
	.string "커다랗고 울퉁불퉁 딱딱한 몸에\n"
	.string "큰 뿔과 날카로운 엄니...\p"
	.string "우후후후후...\n"
	.string "그런 포켓몬을 가지고 싶어...$"

Route114_Text_1BC3B3:: @ 81BC3B3
	.string "우후후후후후...\n"
	.string "내 포켓몬과 승부하자$"

Route114_Text_1BC3E0:: @ 81BC3E0
	.string "아- 너의 포켓몬을 볼 수 있어서\n"
	.string "행복했어...$"

Route114_Text_1BC40F:: @ 81BC40F
	.string "우후후후후후...\p"
	.string "난 포켓몬이 승부하는 모습을\n"
	.string "보고 있으면 두근거려$"

Route114_Text_1BC45A:: @ 81BC45A
	.string "캠프파이어나\n"
	.string "불꽃놀이를 할 때는\l"
	.string "꼭 물을 준비해 두라고!$"

Route114_Text_1BC499:: @ 81BC499
	.string "타오르는 나의 투지를\n"
	.string "네가 꺼버렸어...$"

Route114_Text_1BC4B5:: @ 81BC4B5
	.string "불조심만큼은 정말 잊어서는 안 된다!\n"
	.string "불을 만만하게 봐서는 안 돼!$"

Route114_Text_1BC525:: @ 81BC525
	.string "캠프파이어나\n"
	.string "불꽃놀이를 할 때\l"
	.string "물을 준비하고 있겠지?!$"

Route114_Text_1BC559:: @ 81BC559
	.string "타오르기도 전에\n"
	.string "밟아서 꺼버리다니...$"

Route114_Text_1BC58C:: @ 81BC58C
	.string "불조심만큼은 정말 잊어서는 안 된다!\n"
	.string "불을 만만하게 봐서는 안 돼!$"

Route114_Text_1BC5FC:: @ 81BC5FC
	.string "낚시로 승부하면\n"
	.string "네가 이길 가망이 없겠지\l"
	.string "그러니 포켓몬으로 승부를 내자고!$"

Route114_Text_1BC653:: @ 81BC653
	.string "낚시였으면 이겼을 텐데...$"

Route114_Text_1BC679:: @ 81BC679
	.string "이렇게 됐으니 유성의 폭포에서\n"
	.string "월척이라도 낚아야겠어\l"
	.string "그 폭포에는 뭔가 있을 것 같아$"

Route114_Text_1BC6EC:: @ 81BC6EC
	.string "낚시도 좋지만\n"
	.string "승부도 좋지!\p"
	.string "승부 요청을 받으면\n"
	.string "낚시하는 중이더라도\l"
	.string "거절할 수가 없어!$"

Route114_Text_1BC750:: @ 81BC750
	.string "승부는 좋아하지만\n"
	.string "잘하는 건 아니야...$"

Route114_Text_1BC78A:: @ 81BC78A
	.string "이번에야말로!\p"
	.string "라는 생각을 해버리니까\n"
	.string "낚시도 승부도 그만둘 수 없어$"

Route114_Text_1BC7E3:: @ 81BC7E3
	.string "리세: 그래!\n"
	.string "왠지 기분이 좋으니까\l"
	.string "너한테도 포켓몬 승부를 가르쳐 줄게!$"

Route114_Text_1BC834:: @ 81BC834
	.string "리세: 엄청난 전술이다!$"

Route114_Text_1BC858:: @ 81BC858
	.string "리세: 내 후배 세리에게\n"
	.string "포켓몬 승부를 가르쳐 줬어!$"

Route114_Text_1BC88A:: @ 81BC88A
	.string "리세: 우후후!\n"
	.string "우리들이랑 승부하려면\l"
	.string "포켓몬 한 마리로는 어림도 없어!$"

Route114_Text_1BC8D8:: @ 81BC8D8
	.string "세리: 너...\n"
	.string "포켓몬 승부 누구한테 배웠니?$"

Route114_Text_1BC8FB:: @ 81BC8FB
	.string "세리: 엄청난 전술이다!$"

Route114_Text_1BC91E:: @ 81BC91E
	.string "세리: 나는\n"
	.string "선배가 가르쳐 줘서\l"
	.string "포켓몬 승부를 시작하게 됐어$"

Route114_Text_1BC96A:: @ 81BC96A
	.string "세리: 포켓몬이 한 마리뿐이야?\n"
	.string "엄청 외롭겠는데?$"

Route115_Text_1BC9AC:: @ 81BC9AC
	.string "흐음...\n"
	.string "실력이 좋을 것 같군...\l"
	.string "내가 상대해주마!$"

Route115_Text_1BC9E6:: @ 81BC9E6
	.string "상상했던 것 이상으로 강하군...!$"

Route115_Text_1BCA0E:: @ 81BCA0E
	.string "천재 같은 건 없다\n"
	.string "모든 것은 노력!\l"
	.string "이 몸은 그렇게 믿고 있다...$"

Route115_Text_1BCA6B:: @ 81BCA6B
	.string "흠...\n"
	.string "여전히 좋은 몸놀림이군\l"
	.string "내 상대를 부탁한다!$"

Route115_Text_1BCAB3:: @ 81BCAB3
	.string "여전히 강하군...!$"

Route115_Text_1BCAC6:: @ 81BCAC6
	.string "오직 노력만이 있을 뿐!\p"
	.string "내가 패배한 것은\n"
	.string "아직 노력이 부족하기 때문이다!$"

Route115_Text_1BCB0D:: @ 81BCB0D
	.string "나의!\p"
	.string "알통몬이!\p"
	.string "승부를 갈구하고 있다!$"

Route115_Text_1BCB2E:: @ 81BCB2E
	.string "아야야야얏!$"

Route115_Text_1BCB40:: @ 81BCB40
	.string "나의 알통몬들이!\p"
	.string "더 강해지길 원하는 이상\p"
	.string "우리들은 얼마든지 강해진다!$"

Route115_Text_1BCB8A:: @ 81BCB8A
	.string "나의 주특기 기술은\n"
	.string "박치기로 벽돌을 깨부수는 거다!$"

Route115_Text_1BCBC1:: @ 81BCBC1
	.string "으아-악!\n"
	.string "머리가 부서진 것 같다-앗!$"

Route115_Text_1BCBDE:: @ 81BCBDE
	.string "포켓몬에게 태권도를 가르치고 있다\n"
	.string "나보다 강해질 것 같아서\l"
	.string "기대가 되는군!$"

Route115_Text_1BCC4C:: @ 81BCC4C
	.string "네게 지고 난 후\n"
	.string "열심히 나와 포켓몬을\l"
	.string "다시 단련시켰다!\l"
	.string "자! 다시 한 번 승부다!$"

Route115_Text_1BCCA2:: @ 81BCCA2
	.string "으갸-악!\n"
	.string "또 졌다-!$"

Route115_Text_1BCCBA:: @ 81BCCBA
	.string "내 포켓몬은\n"
	.string "앞으로도 계속 강해질 거다!\l"
	.string "열심히 단련하겠어!$"

Route115_Text_1BCCF4:: @ 81BCCF4
	.string "이 모래 해변은\n"
	.string "아무도 모르는 나만의 수행 장소야!\l"
	.string "마음대로 들어오지 말라고!$"

Route115_Text_1BCD32:: @ 81BCD32
	.string "수행이 부족해...!$"

Route115_Text_1BCD4C:: @ 81BCD4C
	.string "모래가 쿠션 역할을 해주니까\n"
	.string "몸에 상처를 입지 않아\l"
	.string "수행하기엔 최고의 장소지!$"

Route115_Text_1BCDB0:: @ 81BCDB0
	.string "자아- 포켓몬 승부 간닷!$"

Route115_Text_1BCDD0:: @ 81BCDD0
	.string "나는 더 할 수 있지만\n"
	.string "포켓몬이...$"

Route115_Text_1BCDEF:: @ 81BCDEF
	.string "졌어도 살짝 즐거운 건\n"
	.string "정말로 포켓몬을\l"
	.string "좋아하기 때문인 걸까?$"

UnknownString_81BCE47: @ 81BCE47
	.string "난 희귀한 포켓몬을 가지고 있어!\n"
	.string "괜찮으면 보여줄까?$"

UnknownString_81BCE7D: @ 81BCE7D
	.string "너...\n"
	.string "내 포켓몬 가지고 싶지?$"

UnknownString_81BCEA4: @ 81BCEA4
	.string "이렇게 희귀한 포켓몬을\n"
	.string "가지고 있으니까\l"
	.string "난 그것만으로도 만족해!$"

Route115_Text_1BCEE0:: @ 81BCEE0
	.string "난 희귀한 포켓몬을 가지고 있어!\n"
	.string "괜찮으면 보여줄까?$"

Route115_Text_1BCF16:: @ 81BCF16
	.string "너...\n"
	.string "내 포켓몬 가지고 싶지?$"

Route115_Text_1BCF3D:: @ 81BCF3D
	.string "이렇게 희귀한 포켓몬을\n"
	.string "가지고 있으니까\l"
	.string "난 그것만으로도 만족해!$"

Route116_Text_1BCF79:: @ 81BCF79
	.string "터널이 뚫리지 않았다면\n"
	.string "산을 넘어가면 되는 거다!$"

Route116_Text_1BCFBB:: @ 81BCFBB
	.string "허억... 허억...\n"
	.string "패배로 지쳐버렸다$"

Route116_Text_1BCFE3:: @ 81BCFE3
	.string "터널 따위 없어도 상관없다!\n"
	.string "등산가에겐 산이 곧 길이다!$"

Route116_Text_1BD02B:: @ 81BD02B
	.string "내 포켓몬은 강하다!\n"
	.string "한번 보라고!$"

Route116_Text_1BD04C:: @ 81BD04C
	.string "아야야야야얏! 상처가 생겼다!\n"
	.string "반창고 붙여야지!$"

Route116_Text_1BD078:: @ 81BD078
	.string "반창고는 남자의 훈장!\n"
	.string "훈장이 하나 더 늘었다!$"

Route116_Text_1BD0AF:: @ 81BD0AF
	.string "내 벌레포켓몬은 강해!\n"
	.string "승부하자!$"

Route116_Text_1BD0D7:: @ 81BD0D7
	.string "졌다...!\n"
	.string "이길 수 있을 것 같았는데...!$"

Route116_Text_1BD0F4:: @ 81BD0F4
	.string "벌레포켓몬은 빨리 진화하니까\n"
	.string "강해지는 것도 빨라!$"

Route116_Text_1BD131:: @ 81BD131
	.string "내 귀여운 포켓몬의 실력을\n"
	.string "천천히 알려주겠어!$"

Route116_Text_1BD165:: @ 81BD165
	.string "네가 한 수 위구나...$"

Route116_Text_1BD180:: @ 81BD180
	.string "귀여움과 실력을 겸비한 포켓몬...\n"
	.string "그게 내가 추구하는 이상이야!$"

Route116_Text_1BD1C0:: @ 81BD1C0
	.string "트레이너스쿨에서\n"
	.string "많은 걸 공부했으니까\l"
	.string "실전에서 확인해 볼 거야$"

Route116_Text_1BD21A:: @ 81BD21A
	.string "공부는 안 하고 게으름을 피워서\n"
	.string "진 거 같아$"

Route116_Text_1BD248:: @ 81BD248
	.string "트레이너스쿨에서\n"
	.string "다시 제대로 공부하지 않으면\l"
	.string "원규님에게 혼날 거야$"

Route116_Text_1BD2A5:: @ 81BD2A5
	.string "너랑 승부한 뒤로 트레이너스쿨에서\n"
	.string "열심히 공부했으니까 그때처럼\l"
	.string "당하고만 있지는 않을 거야!$"

Route116_Text_1BD2FE:: @ 81BD2FE
	.string "어-?\n"
	.string "분명히 제대로 공부했는데?$"

Route116_Text_1BD31A:: @ 81BD31A
	.string "트레이너스쿨에서\n"
	.string "다시 제대로 공부하지 않으면\l"
	.string "원규님에게 혼날 거야$"

Route116_Text_1BD377:: @ 81BD377
	.string "트레이너스쿨에서도 공부하고!\n"
	.string "집에 가는 길에서도 공부하는 거야!$"

Route116_Text_1BD3AC:: @ 81BD3AC
	.string "대박 쇼크야\n"
	.string "져버리다니...$"

Route116_Text_1BD3C3:: @ 81BD3C3
	.string "으아앙! 이래서는 원규님 같은\n"
	.string "엘레강트한 트레이너가 될 수 없어!$"

Route116_Text_1BD405:: @ 81BD405
	.string "그 후로 엄청나게 공부했어!\n"
	.string "그 성과를 보여줄게!$"

Route116_Text_1BD44A:: @ 81BD44A
	.string "대박 쇼크야\n"
	.string "또 져버리다니...$"

Route116_Text_1BD466:: @ 81BD466
	.string "원규님을 이긴 적이 있다고?\n"
	.string "지금의 나는 절대 널 이길 수 없겠네$"

Route117_Text_1BD49E:: @ 81BD49E
	.string "내가 키우고 있는 포켓몬과\n"
	.string "승부해 주지 않겠나?$"

Route117_Text_1BD4D9:: @ 81BD4D9
	.string "훌륭하게 키우고 있군...$"

Route117_Text_1BD4F9:: @ 81BD4F9
	.string "포켓몬을 강하게 키우는 게\n"
	.string "전부가 아니다!\p"
	.string "포켓몬의 개성을 갈고닦는 것도\n"
	.string "즐거움의 하나지!$"

Route117_Text_1BD569:: @ 81BD569
	.string "내가 키우고 있는 포켓몬은\n"
	.string "변함없이 잘 자라고 있다!$"

Route117_Text_1BD5AB:: @ 81BD5AB
	.string "잘 키우고 있군...\n"
	.string "너에겐 포켓몬 브리더의\l"
	.string "소질이 있을지도...$"

Route117_Text_1BD5F2:: @ 81BD5F2
	.string "아주 잘 자라고 있군!\n"
	.string "콘테스트에 나가 보면 어때?$"

Route117_Text_1BD634:: @ 81BD634
	.string "포켓몬을 잘 키우고 있는지\n"
	.string "제가 확인해 드리겠어요$"

Route117_Text_1BD67B:: @ 81BD67B
	.string "잘 키우고 있군요$"

Route117_Text_1BD69B:: @ 81BD69B
	.string "포켓몬스넥을 포켓몬에게 먹이면\n"
	.string "포켓몬의 개성이 한층 빛나게 돼요$"

Route117_Text_1BD6F2:: @ 81BD6F2
	.string "포켓몬을 잘 키우고 있는지\n"
	.string "제가 또 확인해 드리겠어요$"

Route117_Text_1BD733:: @ 81BD733
	.string "훌륭하게 자라고 있군요$"

Route117_Text_1BD74F:: @ 81BD74F
	.string "포켓몬의 성격에 따라\n"
	.string "좋아하는 포켓몬스넥이 다른 것 같아요$"

Route117_Text_1BD79A:: @ 81BD79A
	.string "트라이애슬론에\n"
	.string "한창 도전 중이긴 하지만\l"
	.string "잠깐만 승부 한판 하자고!$"

Route117_Text_1BD7E0:: @ 81BD7E0
	.string "체력이 떨어졌다!$"

Route117_Text_1BD7F5:: @ 81BD7F5
	.string "큰일이군...\p"
	.string "방금 승부하는 사이에\n"
	.string "꼴등이 된 것 같다...$"

Route117_Text_1BD83F:: @ 81BD83F
	.string "트라이애슬론에\n"
	.string "한창 도전 중이긴 하지만\l"
	.string "난 여유 만만이니까\l"
	.string "승부 한판 하자고!$"

Route117_Text_1BD8A2:: @ 81BD8A2
	.string "또 체력이 떨어졌다!$"

Route117_Text_1BD8BD:: @ 81BD8BD
	.string "수영과 자전거는 일등이지만\n"
	.string "포켓몬은 아직 자신이 없다$"

Route117_Text_1BD914:: @ 81BD914
	.string "트라이애슬론의 연습\n"
	.string "포켓몬과 같이 하고 있으니까\l"
	.string "스피드에는 자신 있어!$"

Route117_Text_1BD965:: @ 81BD965
	.string "연습이 부족했나?$"

Route117_Text_1BD98F:: @ 81BD98F
	.string "연습은 계속해야\n"
	.string "의미가 있는 거야\p"
	.string "좋-아! 다시 연습해야지\n"
	.string "내일부터!$"

Route117_Text_1BD9F1:: @ 81BD9F1
	.string "어때 연습 계속하고 있니?\n"
	.string "나는 물론 계속하고 있어\l"
	.string "그 증거를 보여줄게!$"

Route117_Text_1BDA41:: @ 81BDA41
	.string "연습이 부족했나?$"

Route117_Text_1BDA6B:: @ 81BDA6B
	.string "내일부터 또 연습할 거니까\n"
	.string "괜찮으면 또 승부해줘!$"

Route117_Text_1BDAA7:: @ 81BDAA7
	.string "어렸을 땐 곤충채집소년!\n"
	.string "지금은 곤충마니아\p"
	.string "하지만 포켓몬을 사랑하는 마음은\n"
	.string "변함없이 그대로다!$"

Route117_Text_1BDAFC:: @ 81BDAFC
	.string "포켓몬이 약한 것도 변함없다...$"

Route117_Text_1BDB24:: @ 81BDB24
	.string "좋아하는 것만 하다 보니\n"
	.string "어느샌가 마니아라고 불리게 됐어!\p"
	.string "뭐, 벌레포켓몬을 잘 알고 있으니\n"
	.string "마니아라고 불리는 게 당연하겠지!$"

Route117_Text_1BDBC3:: @ 81BDBC3
	.string "미호: 귀여운 후배 앞이니까\n"
	.string "멋진 모습을 보여야지!$"

Route117_Text_1BDC07:: @ 81BDC07
	.string "미호: 아이참!\n"
	.string "후배 앞이니까 좀 이기게 해달라고!$"

Route117_Text_1BDC44:: @ 81BDC44
	.string "미호: 너와 네 포켓몬\n"
	.string "상당한 팀워크군!\p"
	.string "그래! 우리들\n"
	.string "다음으로 대단하지 않을까?$"

Route117_Text_1BDC96:: @ 81BDC96
	.string "미호: 우리랑 승부하고 싶으면\n"
	.string "포켓몬을 2마리 데려와!$"

Route117_Text_1BDCD2:: @ 81BDCD2
	.string "리코: 멋진 선배랑 콤비로\n"
	.string "널 쓰러뜨릴 거야!$"

Route117_Text_1BDD1E:: @ 81BDD1E
	.string "리코: 꺄-\n"
	.string "죄송합니다! 선배님!$"

Route117_Text_1BDD4E:: @ 81BDD4E
	.string "리코: 나는 선배님에게 도움은커녕\n"
	.string "방해만 됐던 거야\p"
	.string "아니면 넌 우릴 이길 수 없었다고!$"

Route117_Text_1BDD8B:: @ 81BDD8B
	.string "리코: 포켓몬이 한 마리밖에 없어?\n"
	.string "그럼 승부할 수 없어\p"
	.string "우리는 2대 2로\n"
	.string "승부를 즐기고 싶으니까!$"

Route117_Text_1BDDEF:: @ 81BDDEF
	.string "미호: 후배 앞에서\n"
	.string "계속 지기만 할 수는 없지$"

Route117_Text_1BDE2F:: @ 81BDE2F
	.string "미호: 컨디션이 별로였어$"

Route117_Text_1BDE55:: @ 81BDE55
	.string "미호: 너와 네 포켓몬\n"
	.string "상당한 팀워크군!\p"
	.string "그래! 우리들\n"
	.string "다음으로 대단하지 않을까?$"

Route117_Text_1BDEA7:: @ 81BDEA7
	.string "미호: 우리랑 승부하고 싶으면\n"
	.string "포켓몬을 2마리 데려와!$"

Route117_Text_1BDEE3:: @ 81BDEE3
	.string "리코: 이번에야말로 선배님이랑\n"
	.string "콤비로 널 쓰러뜨리겠어!$"

Route117_Text_1BDF26:: @ 81BDF26
	.string "리코: 너무 강해$"

Route117_Text_1BDF37:: @ 81BDF37
	.string "리코: 선배님이랑 같이 배틀했는데도\n"
	.string "져버리다니... 우울해!$"

Route117_Text_1BDF90:: @ 81BDF90
	.string "리코: 포켓몬이 한 마리밖에 없어?\n"
	.string "그럼 승부할 수 없어\p"
	.string "우리는 2대 2로\n"
	.string "승부를 즐기고 싶으니까!$"

Route118_Text_1BDFF4:: @ 81BDFF4
	.string "꽃향기는 신비한 힘이 있어\n"
	.string "몸도 마음도 깨끗해지지$"

Route118_Text_1BE03C:: @ 81BE03C
	.string "어머머\n"
	.string "져버렸네$"

Route118_Text_1BE05E:: @ 81BE05E
	.string "꽃도 포켓몬도\n"
	.string "좋은 향기가 나는 걸 좋아해!\l"
	.string "이상한 냄새가 나는 건... 별로야$"

Route118_Text_1BE0AB:: @ 81BE0AB
	.string "좋은 향기에\n"
	.string "이끌려서 온 건가?$"

Route118_Text_1BE0D3:: @ 81BE0D3
	.string "향기의 효과...\n"
	.string "그다지 없었네$"

Route118_Text_1BE104:: @ 81BE104
	.string "달콤한향기를 잘 쓰면\n"
	.string "포켓몬이 향기에 이끌려서 찾아와$"

Route118_Text_1BE148:: @ 81BE148
	.string "화려하게 드넓은 하늘을 나는\n"
	.string "새포켓몬이 최고야!$"

Route118_Text_1BE188:: @ 81BE188
	.string "으으... 졌다...$"

Route118_Text_1BE19D:: @ 81BE19D
	.string "너도 좋은 포켓몬을 가지고 있구나!\n"
	.string "나도 지지 않고 포켓몬을 키울 거야!$"

Route118_Text_1BE1D7:: @ 81BE1D7
	.string "날아올라라!\n"
	.string "나의 새포켓몬!$"

Route118_Text_1BE1F5:: @ 81BE1F5
	.string "날아올랐지만...$"

Route118_Text_1BE20D:: @ 81BE20D
	.string "더 강해지면\n"
	.string "자유롭게 날 수 있을 텐데!$"

Route118_Text_1BE24A:: @ 81BE24A
	.string "난 낚시꾼이지만\n"
	.string "트레이너이기도 하지\l"
	.string "낚은 포켓몬을 잘 키우고 있다!$"

Route118_Text_1BE291:: @ 81BE291
	.string "왜지? 잘 키우고 있었는데...?$"

Route118_Text_1BE2BE:: @ 81BE2BE
	.string "낚시를 하면서\n"
	.string "포켓몬을 키웠지만\l"
	.string "이길 수 없었다...\p"
	.string "둘 다 애매한 실력인 건가?!$"

Route118_Text_1BE318:: @ 81BE318
	.string "낚시꾼에게\n"
	.string "가장 중요한 것은 도구다!\l"
	.string "트레이너에게 중요한 건\l"
	.string "물론 포켓몬과 마음이지!$"

Route118_Text_1BE385:: @ 81BE385
	.string "마음의 승부에서 진 건가?$"

Route118_Text_1BE39C:: @ 81BE39C
	.string "낚시라는 것도\n"
	.string "사람과 포켓몬의\l"
	.string "진지한 승부라고!$"

Route118_Text_1BE3E8:: @ 81BE3E8
	.string "나의 멜로디를...\n"
	.string "당신의 마음속 깊은 곳에 전하겠어...$"

Route118_Text_1BE406:: @ 81BE406
	.string "라- 라라라-$"

Route118_Text_1BE413:: @ 81BE413
	.string "전자 기타는\n"
	.string "그냥 시끄럽기만 한 게 아니야...\p"
	.string "이렇게 마음속에 스며드는\n"
	.string "멜로디도 연주할 수 있지...$"

Route118_Text_1BE489:: @ 81BE489
	.string "나와 포켓몬의 멜로디를...\n"
	.string "당신의 마음속 깊은 곳에 전하겠어...$"

Route118_Text_1BE4CC:: @ 81BE4CC
	.string "라- 라라라-$"

Route118_Text_1BE4D9:: @ 81BE4D9
	.string "연주하고 있는 나의 마음이\n"
	.string "전자 기타를 통해서\l"
	.string "당신에게 전해질 거야...$"

Route119_Text_1BE521:: @ 81BE521
	.string "우리는 흉내내기서클!\n"
	.string "너의 움직임을 흉내 내겠어!$"

Route119_Text_1BE54F:: @ 81BE54F
	.string "우와아- 졌다-앗!$"

Route119_Text_1BE561:: @ 81BE561
	.string "흉내 내는 게 뭐가 그렇게 즐겁냐고?\p"
	.string "후후후...\n"
	.string "알려줘도 넌 모를 거야$"

Route119_Text_1BE5A4:: @ 81BE5A4
	.string "드디어 만났구나!\n"
	.string "내 벌레포켓몬이 상대해 줄 거야!$"

Route119_Text_1BE5DF:: @ 81BE5DF
	.string "만나지 않았으면 좋았을 텐데...$"

Route119_Text_1BE5F8:: @ 81BE5F8
	.string "더 네 흉내를 내고 싶어!\p"
	.string "자! 빨리 움직여 봐!$"

Route119_Text_1BE632:: @ 81BE632
	.string "네가 앞으로 가면\n"
	.string "우리도 앞으로 가고\p"
	.string "네가 오른쪽으로 꺾으면\n"
	.string "우리도 꺾는다...$"

Route119_Text_1BE67B:: @ 81BE67B
	.string "네가 이겨도\n"
	.string "우린 진다...$"

Route119_Text_1BE695:: @ 81BE695
	.string "음- 승부의 승패만은\n"
	.string "흉내 낼 수 없구나\l"
	.string "왠지 분하다...$"

Route119_Text_1BE6EA:: @ 81BE6EA
	.string "드디어 날 잡았구나!\n"
	.string "아니면 도망가려고 했던 건가?$"

Route119_Text_1BE729:: @ 81BE729
	.string "훌륭한 승부였어!$"

Route119_Text_1BE748:: @ 81BE748
	.string "우리들은 흉내내기서클!\n"
	.string "우리들과의 승부는 즐거웠니?$"

Route119_Text_1BE784:: @ 81BE784
	.string "내가 누군지 모르지?\p"
	.string "...뭐 나도 네가 누군지 모르니까\n"
	.string "이렇게 승부하는 거겠지만!$"

Route119_Text_1BE7D3:: @ 81BE7D3
	.string "꽤 강하잖아?!$"

Route119_Text_1BE7E9:: @ 81BE7E9
	.string "네가 어딘가 다른 곳으로 갈 때까지\n"
	.string "우리들은 계속 흉내를 낼 거야!$"

Route119_Text_1BE82F:: @ 81BE82F
	.string "흉내 내기를 좋아하는 사람들이\n"
	.string "모여서 만든 흉내내기서클!\p"
	.string "만난 그 순간부터\n"
	.string "승부가 시작된다!$"

Route119_Text_1BE88D:: @ 81BE88D
	.string "졌습니다-앗!$"

Route119_Text_1BE89A:: @ 81BE89A
	.string "너도 흉내내기서클에\n"
	.string "들어오지 않을래?$"

Route119_Text_1BE8BB:: @ 81BE8BB
	.string "서바이벌에 필요한\n"
	.string "지식과 기술을 지닌 자!\p"
	.string "그게 바로 포켓몬 레인저다!$"

Route119_Text_1BE90E:: @ 81BE90E
	.string "포켓몬에 대한 지식은 부족했다...$"

Route119_Text_1BE937:: @ 81BE937
	.string "현대 문명에서 벗어나서\n"
	.string "인간의 야성을 깨운다!\l"
	.string "그것이 바로 우리들의 테마다!$"

Route119_Text_1BE98D:: @ 81BE98D
	.string "포켓몬과 함께 있는 걸로\n"
	.string "잃어버린 야성을 되찾는 거다!$"

Route119_Text_1BE9D0:: @ 81BE9D0
	.string "여전히 강하군!$"

Route119_Text_1BE9E8:: @ 81BE9E8
	.string "일단 포켓몬을 믿고!\n"
	.string "그리고 너 자신을 믿어라!\l"
	.string "그러면 길은 열린다!$"

Route119_Text_1BEA3A:: @ 81BEA3A
	.string "어머 당신...\n"
	.string "모험을 하고 있는 것치곤\l"
	.string "상당히 가벼운 복장이군요$"

Route119_Text_1BEA88:: @ 81BEA88
	.string "준비 부족은 사고의 원인...$"

Route119_Text_1BEAB3:: @ 81BEAB3
	.string "상당히 가벼운 복장이지만\n"
	.string "필요한 도구는 가지고 있고\l"
	.string "기력도 체력도 충분하군요!$"

Route119_Text_1BEB22:: @ 81BEB22
	.string "포켓몬과 함께하는 모험은\n"
	.string "잘 되고 있나요?$"

Route119_Text_1BEB49:: @ 81BEB49
	.string "아직 뭔가가\n"
	.string "부족하네요...$"

Route119_Text_1BEB68:: @ 81BEB68
	.string "트레이너인 당신이\n"
	.string "포켓몬에게 의지하고 있듯\l"
	.string "포켓몬도 당신에게 의지하고 있어요!$"

Route119_Text_1BEBC0:: @ 81BEBC0
	.string "드넓은 하늘은 남자의 로망!\p"
	.string "자유롭게 하늘을 나는 상쾌한 기분은\n"
	.string "그 무엇과도 바꿀 수 없지!$"

Route119_Text_1BEC1C:: @ 81BEC1C
	.string "졌다아-앗!$"

Route119_Text_1BEC2A:: @ 81BEC2A
	.string "하늘을 날아다니는 꿈은\n"
	.string "새포켓몬 덕분에 이룰 수 있었어!$"

Route119_Text_1BEC5E:: @ 81BEC5E
	.string "내 새포켓몬의 실력을\n"
	.string "보여주겠어!$"

Route119_Text_1BEC9A:: @ 81BEC9A
	.string "실력 부족이었어...$"

Route119_Text_1BECB1:: @ 81BECB1
	.string "나는 어렸을 때부터\n"
	.string "새포켓몬을 동경하고 있었어!$"

Route119_Text_1BECF1:: @ 81BECF1
	.string "그림자에 숨고 어둠에서 살아간다\n"
	.string "그것이 나의 운명...!\p"
	.string "간닷! 포켓몬 승부다!$"

Route119_Text_1BED4C:: @ 81BED4C
	.string "졌다...!$"

Route119_Text_1BED5C:: @ 81BED5C
	.string "승부에 진 자는 미련 없이\n"
	.string "그림자 속으로 돌아간다...\l"
	.string "이 또한 운명...$"

Route119_Text_1BEDB6:: @ 81BEDB6
	.string "방심하고 있으면\n"
	.string "따끔한 맛을 보게 될 것이다!$"

Route119_Text_1BEDEC:: @ 81BEDEC
	.string "강하군! 너는!$"

Route119_Text_1BEE06:: @ 81BEE06
	.string "기습 작전은 실패였다...$"

Route119_Text_1BEE2D:: @ 81BEE2D
	.string "등잔 밑이 어둡다!$"

Route119_Text_1BEE4B:: @ 81BEE4B //JP: 1933B0
	.string "상당한 실력이로군$"

Route119_Text_1BEE66:: @ 81BEE66
	.string "등잔 밑이 어둡다!\n"
	.string "포켓몬을 잡으려면 포켓몬 굴로!\p"
	.string "별 의미는 없소...$"

Route119_Text_1BEED0:: @ 81BEED0
	.string "나한테 말을 걸었다는 건 즉...\n"
	.string "나한테 승부를 걸겠다 이거지?!\p"
	.string "좋았어! 파도타기 하면서\n"
	.string "낚아 올린 포켓몬으로 승부하겠다!$"

Route119_Text_1BEF37:: @ 81BEF37
	.string "이길 수 있는 포인트를\n"
	.string "전혀 모르겠다!$"

Route119_Text_1BEF67:: @ 81BEF67
	.string "파도타기!\p"
	.string "포켓몬의 등에 타고\n"
	.string "낚시를 즐긴다!\p"
	.string "이 얼마나 여유로운 순간인가!$"

Route120_Text_1BEFC8:: @ 81BEFC8
	.string "하늘을 날고 있는 포켓몬에게\n"
	.string "데미지를 줄 수 있는 기술을\l"
	.string "가지고 있니?$"

Route120_Text_1BF000:: @ 81BF000
	.string "네가 나보다\n"
	.string "한 수 위였어!$"

Route120_Text_1BF015:: @ 81BF015
	.string "공중날기라는 기술은 참 편리하군!\p"
	.string "하늘을 날고 있는 동안에는\n"
	.string "거의 모든 기술에 맞지 않는 거지?$"

Route120_Text_1BF07E:: @ 81BF07E
	.string "내 포켓몬은 강하다!\n"
	.string "네 포켓몬은 어떨까?$"

Route120_Text_1BF0A5:: @ 81BF0A5
	.string "네 포켓몬이\n"
	.string "더 강했다...!$"

Route120_Text_1BF0C3:: @ 81BF0C3
	.string "점점 강해지는 포켓몬은\n"
	.string "정말 믿음직스럽지-!$"

Route120_Text_1BF0FA:: @ 81BF0FA
	.string "점점 강해지는 포켓몬은\n"
	.string "정말 믿음직스럽지-!$"

Route120_Text_1BF131:: @ 81BF131
	.string "네 포켓몬...\n"
	.string "정말 강하구나...$"

Route120_Text_1BF154:: @ 81BF154
	.string "강해지는 포켓몬과 함께\n"
	.string "나도 같이 강해져야겠지!$"

Route120_Text_1BF193:: @ 81BF193
	.string "너의 포켓몬\n"
	.string "조난당하지는 않을지 봐주겠어!$"

Route120_Text_1BF1D4:: @ 81BF1D4
	.string "그렇게 강한 포켓몬이 함께 있다면\n"
	.string "조난당할 걱정은 없겠군!$"

Route120_Text_1BF215:: @ 81BF215
	.string "포켓몬과 함께라면\n"
	.string "어디든 갈 수 있다는 게\l"
	.string "트레이너의 기쁨이라고 할 수 있겠지!$"

Route120_Text_1BF26E:: @ 81BF26E
	.string "네 체력은 어때?\n"
	.string "체력이 부족하면\l"
	.string "여차하는 순간에 곤경에 빠지고 말지!$"

Route120_Text_1BF2D2:: @ 81BF2D2
	.string "체력은 있었는데...$"

Route120_Text_1BF2EA:: @ 81BF2EA
	.string "체력 키우기가 나의 일과야\n"
	.string "매일 포켓몬과 달리기를 하지!$"

Route120_Text_1BF32B:: @ 81BF32B
	.string "... ... ...\n"
	.string "... ... ...\l"
	.string "승부할래...?$"

Route120_Text_1BF36B:: @ 81BF36B
	.string "... ... ...\n"
	.string "졌다...$"

Route120_Text_1BF38D:: @ 81BF38D
	.string "... ... ...\n"
	.string "... ... ...\l"
	.string "힘내야지...$"

Route120_Text_1BF3D0:: @ 81BF3D0
	.string "... ... ...\n"
	.string "... ... ...\l"
	.string "또 승부할래...?$"

Route120_Text_1BF416:: @ 81BF416
	.string "... ... ...\n"
	.string "또 졌다...$"

Route120_Text_1BF43E:: @ 81BF43E
	.string "... ... ...\n"
	.string "... ... ...\l"
	.string "또 힘내야지...\l"
	.string "소중한 벌레포켓몬을 위해서...$"

Route120_Text_1BF4A0:: @ 81BF4A0
	.string "포켓몬에게는 많은 특성이 있어\n"
	.string "그걸 잘 생각해야만\l"
	.string "일류 트레이너가 될 수 있는 거야!$"

Route120_Text_1BF504:: @ 81BF504
	.string "꽤 잘 생각하고 있구나$"

Route120_Text_1BF51F:: @ 81BF51F
	.string "그래 포켓몬의 특성에 따라\n"
	.string "전술도 많이 바뀌게 되지!$"

Route120_Text_1BF560:: @ 81BF560
	.string "뭐지 넌?\p"
	.string "설마, 있을지도\n"
	.string "모른다고 하는\l"
	.string "고대의 유적을 찾으러 온 겐가?!$"

Route120_Text_1BF5D6:: @ 81BF5D6
	.string "이거 참 큰일이군$"

Route120_Text_1BF5F4:: @ 81BF5F4
	.string "난 저 커다란 바위가\n"
	.string "유적이라고 믿고 싶지만 그러기엔\l"
	.string "입구를 찾을 수가 없단 말이지...$"

Route120_Text_1BF65B:: @ 81BF65B
	.string "내가 파라솔을 가지고 있는 이유?\p"
	.string "우후후 날 이기면\n"
	.string "가르쳐 줄게$"

Route120_Text_1BF6A4:: @ 81BF6A4
	.string "파라솔로 포켓몬의 공격은\n"
	.string "막을 수 없구나...$"

Route120_Text_1BF6D0:: @ 81BF6D0
	.string "내 포켓몬들도\n"
	.string "뜨거운 햇볕에 약하다고 생각해\l"
	.string "그래서 파라솔을 들고 있는 거야$"

Route120_Text_1BF728:: @ 81BF728
	.string "나랑 포켓몬이랑 파라솔\n"
	.string "셋 중 하나만 없어도\l"
	.string "아름다움에 금이 가고 말아$"

Route120_Text_1BF78C:: @ 81BF78C
	.string "기껏 지킨 아름다움이\n"
	.string "소용없어졌어...$"

Route120_Text_1BF7B2:: @ 81BF7B2
	.string "당신에게 파라솔은 어울리지 않아\p"
	.string "이런 걸 들고 있으면\n"
	.string "배틀에 엄청 방해될 거 같으니까$"

Route120_Text_1BF80B:: @ 81BF80B
	.string "포켓몬의 움직임을 접목시켜\n"
	.string "새로운 비밀 기술을 만들어 내는 거다!$"

Route120_Text_1BF852:: @ 81BF852
	.string "새로운 비밀 기술의 완성은\n"
	.string "아직 갈 길이 먼 것 같군$"

Route120_Text_1BF891:: @ 81BF891
	.string "스승으로 모실 만한 분을 찾아서\n"
	.string "제자로 들어가 볼까?$"

Route120_Text_1BF8C5:: @ 81BF8C5
	.string "닌자놀이의 위장술!\n"
	.string "어디 있는지 몰랐을 거야!$"

Route120_Text_1BF920:: @ 81BF920
	.string "졌다!\n"
	.string "위장술로 숨길 수 있나?$"

Route120_Text_1BF946:: @ 81BF946
	.string "우리 닌자놀이의 위장술!\n"
	.string "이건 직접 손으로 만든 거다!$"

Route121_Text_1BF96E:: @ 81BF96E
	.string "너무너무 깜찍한 내 포켓몬을\n"
	.string "귀여워해 줘!$"

Route121_Text_1BF9A1:: @ 81BF9A1
	.string "귀여워해 달랬잖아!$"

Route121_Text_1BF9BA:: @ 81BF9BA
	.string "해안시티의 콘테스트에 갈 거야\n"
	.string "내 포켓몬이라면\l"
	.string "마스터랭크도 문제없지!$"

Route121_Text_1BFA1B:: @ 81BFA1B
	.string "세계 각국을\n"
	.string "포켓몬과 함께 여행해 왔다\p"
	.string "실력에는 좀 자신이 있습니다!$"

Route121_Text_1BFA8C:: @ 81BFA8C
	.string "훌륭합니다$"

Route121_Text_1BFA9D:: @ 81BFA9D
	.string "또 포켓몬과 함께\n"
	.string "세계를 여행하고 싶군요$"

Route121_Text_1BFADA:: @ 81BFADA
	.string "세계 각국을\n"
	.string "포켓몬과 함께 여행해 왔다\p"
	.string "실력에는 좀 자신이 있습니다!$"

Route121_Text_1BFB4B:: @ 81BFB4B
	.string "정말 훌륭합니다!$"
	
Route121_Text_1BFB5C:: @ 81BFB5C
	.string "당신과 그 포켓몬이라면\n"
	.string "외국에서도 강하다는 말을\l"
	.string "들을 겁니다!$"

Route121_Text_1BFBB4:: @ 81BFBB4
	.string "세상에는 신비한 힘이\n"
	.string "많이 있어...$"

Route121_Text_1BFBEE:: @ 81BFBEE
	.string "난 진 거구나...$"

Route121_Text_1BFBFD:: @ 81BFBFD
	.string "송화산...\n"
	.string "그곳에 신비한 힘이 있어...$"

Route121_Text_1BFC36:: @ 81BFC36
	.string "마나: 둘이 모이면 무서울 게 없다!\n"
	.string "우리들의 힘을 보여주겠어!$"

Route121_Text_1BFC7A:: @ 81BFC7A
	.string "마나: 후배 앞에서 이런 꼴을 당하다니...$"

Route121_Text_1BFCB3:: @ 81BFCB3
	.string "마나: 나는 누군가가 나한테 의지하면\n"
	.string "나도 모르게 내 멋진 모습을\l"
	.string "더 보여주고 싶어져...$"

Route121_Text_1BFD08:: @ 81BFD08
	.string "마나: 포켓몬이 한 마리밖에 없구나\n"
	.string "그럼 승부할 수 없어!\p"
	.string "약자를 괴롭힐 수는 없잖아?$"

Route121_Text_1BFD60:: @ 81BFD60
	.string "유이: 둘이 모이면 무서울 게 없다!\n"
	.string "우리들의 힘을 보여주겠어!$"

Route121_Text_1BFDA3:: @ 81BFDA3
	.string "유이: 선배님 죄송합니다!$"

Route121_Text_1BFDC1:: @ 81BFDC1
	.string "유이: 에헤헤!\n"
	.string "또 선배님이랑 같이 특훈이다!$"

Route121_Text_1BFE0D:: @ 81BFE0D
	.string "유이: 우리들에게 도전하려면\n"
	.string "포켓몬이 2마리 필요하다고!$"

Route121_Text_1BFE51:: @ 81BFE51
	.string "내 소중한 포켓몬을\n"
	.string "좀 봐줘!$"

Route121_Text_1BFE80:: @ 81BFE80
	.string "흥흥!\n"
	.string "뭐야- 좀 봐주란 말이야!$"

Route121_Text_1BFEAE:: @ 81BFEAE
	.string "사파리에서 새로운\n"
	.string "포켓몬을 잡을까?$"

Route121_Text_1BFEDE:: @ 81BFEDE
	.string "내 소중한 포켓몬이 많이 성장했어!\n"
	.string "좀 보고 가라고!$"

Route121_Text_1BFF0A:: @ 81BFF0A
	.string "흥이다! 흥!\n"
	.string "또 인정사정 안 봐주는구나!$"

Route121_Text_1BFF3A:: @ 81BFF3A
	.string "사파리에서 새로운\n"
	.string "포켓몬을 잡을까?$"

Route123_Text_1BFF6A:: @ 81BFF6A
	.string "당신의 실력이\n"
	.string "어느 정도인지...\l"
	.string "내가 확인해 주겠어요!$"

Route123_Text_1BFFA2:: @ 81BFFA2
	.string "훌륭해요...!$"

Route123_Text_1BFFC1:: @ 81BFFC1
	.string "날 이기다니...\n"
	.string "당신의 실력도 상당하군요!$"

Route123_Text_1BFFF0:: @ 81BFFF0
	.string "체육관 배지를\n"
	.string "많이 가지고 있나 보군?!\p"
	.string "정말 그만큼 강한지\n"
	.string "확인해 주겠어!$"

Route123_Text_1C0057:: @ 81C0057
	.string "확실히 강하긴 강하군!$"

Route123_Text_1C0075:: @ 81C0075
	.string "가진 체육관 배지가 부끄럽지 않은\n"
	.string "좋은 승부였어!$"

Route123_Text_1C009E:: @ 81C009E
	.string "즐거운 일이 있을 때는\n"
	.string "좋은 향기로 가득 차$"

Route123_Text_1C00D4:: @ 81C00D4
	.string "아...\n"
	.string "슬픈 냄새야...$"

Route123_Text_1C0100:: @ 81C0100
	.string "나무열매 명인의 꽃밭은\n"
	.string "엄-청나게 좋은 향기로 가득 차 있어!$"

Route123_Text_1C013F:: @ 81C013F
	.string "초능력은 마음의 힘...\p"
	.string "그래 나는 누구에게도 지지 않겠다고\n"
	.string "마음먹고 있으니까 강한 거야!$"

Route123_Text_1C01A3:: @ 81C01A3
	.string "히잉...$"

Route123_Text_1C01B1:: @ 81C01B1
	.string "초능력은 마음의 힘...\n"
	.string "너에겐 지지 않겠다고\l"
	.string "마음먹고 있었는데...$"

Route123_Text_1C01F9:: @ 81C01F9
	.string "나는 이제 누구에게도 지지 않겠다고\n"
	.string "마음먹고 있으니까 강한 거야!!$"

Route123_Text_1C0240:: @ 81C0240
	.string "히잉...$"

Route123_Text_1C024E:: @ 81C024E
	.string "송화산에서 수행이라도 할까\n"
	.string "이대로라면 계속 너에게 이길 수 없어$"

Route123_Text_1C028C:: @ 81C028C
	.string "포켓몬도 초능력도\n"
	.string "쓸 수 있는 것만으로는 의미가 없어\l"
	.string "단련해야 비로소 진짜가 되는 거야$"

Route123_Text_1C0303:: @ 81C0303
	.string "굉장해!$"

Route123_Text_1C030F:: @ 81C030F
	.string "누구라도 초능력을 가지고 있어\n"
	.string "그냥 쓰는 법을 잊어버린 것 뿐이야$"

Route123_Text_1C0351:: @ 81C0351
	.string "어때? 당신 안의\n"
	.string "초능력 눈떴어?$"

Route123_Text_1C0380:: @ 81C0380
	.string "굉장해!$"

Route123_Text_1C038C:: @ 81C038C
	.string "당신의 강함\n"
	.string "그것도 초능력일 수 있어$"

Route123_Text_1C03CB:: @ 81C03CB
	.string "아영: 트레이너님의 포켓몬들아!\n"
	.string "져도 울지는 마-!$"

Route123_Text_1C040E:: @ 81C040E
	.string "아영: 져버렸어...$"

Route123_Text_1C0423:: @ 81C0423
	.string "아영: 트레이너님의 포켓몬들은\n"
	.string "사이가 좋아서 강한 거군요!$"

Route123_Text_1C0462:: @ 81C0462
	.string "아영: 포켓몬이 두 마리는 있어야\n"
	.string "승부를 해도 재미가 있지!$"

Route123_Text_1C049C:: @ 81C049C
	.string "아영: 좋-아! 트레이너님의\n"
	.string "포켓몬을 해치우겠어요!$"

Route123_Text_1C04CD:: @ 81C04CD
	.string "희아: 져버렸어...$"

Route123_Text_1C04E3:: @ 81C04E3
	.string "희아: 왜- 그렇게 강한 거예요?\n"
	.string "우리들 승부에서 진 건 처음이에요!$"

Route123_Text_1C0519:: @ 81C0519
	.string "아영: 포켓몬이 두 마리는 있어야지\n"
	.string "승부를 해도 재미가 있지!$"

Route123_Text_1C0554:: @ 81C0554
	.string "송화산은...\n"
	.string "포켓몬의 혼이 잠드는 곳...\l"
	.string "당신의 포켓몬도 잠들래?$"

Route123_Text_1C059F:: @ 81C059F
	.string "아주 건강하네...$"

Route123_Text_1C05BC:: @ 81C05BC
	.string "송화산은...\n"
	.string "포켓몬의 혼이 잠드는 곳...\p"
	.string "분명 영혼을 달래는\n"
	.string "힘이 넘쳐흐르는 걸꺼야$"

Route124_Text_1C0624:: @ 81C0624
	.string "오 길을 잃은 건가?\p"
	.string "내 포켓몬을 이기면\n"
	.string "물길을 안내해줄 수도 있는데!$"

Route124_Text_1C0675:: @ 81C0675
	.string "싸우는 감각을 잃어버렸다...$"

Route124_Text_1C0693:: @ 81C0693
	.string "바다에서 길을 잃는 사람들이 많지!\p"
	.string "그런 사람은 포켓내비로\n"
	.string "맵을 확인하면서 움직이는 편이 좋아!$"

Route124_Text_1C06F7:: @ 81C06F7
	.string "흥! 스스로 헤엄치지 않고\n"
	.string "포켓몬을 타고 있다니...\p"
	.string "엄청 부럽군!$"

Route124_Text_1C0741:: @ 81C0741
	.string "아아!\n"
	.string "틀렸어...!$"

Route124_Text_1C0750:: @ 81C0750
	.string "오랫동안 물속에 있었더니\n"
	.string "몸이 차가워지기 시작했어...\p"
	.string "너처럼 포켓몬을 타고 싶어$"

Route124_Text_1C07B4:: @ 81C07B4
	.string "이렇게 바다에 떠 있으면\n"
	.string "포켓몬들이 놀러 와!$"

Route124_Text_1C07F9:: @ 81C07F9
	.string "아-\n"
	.string "져버렸어...$"

Route124_Text_1C080E:: @ 81C080E
	.string "바다에서 헤엄치고 있으면\n"
	.string "공격하는 포켓몬도 있고\l"
	.string "그냥 보고만 있는 포켓몬도 있어\p"
	.string "포켓몬에게도 개성이 있는 거지!$"

Route124_Text_1C0888:: @ 81C0888
	.string "이렇게 바다에 떠 있으면\n"
	.string "트레이너가 배틀을 걸어와!$"

Route124_Text_1C08C8:: @ 81C08C8
	.string "이상하네-\n"
	.string "또 져버렸어...$"

Route124_Text_1C08EA:: @ 81C08EA
	.string "왠지 모르겠지만 미궁의 대저택에\n"
	.string "가봐야 할 것 같아...$"

Route124_Text_1C0936:: @ 81C0936
	.string "수영도 슬슬 질렸으니...\n"
	.string "나랑 승부하자!$"

Route124_Text_1C096B:: @ 81C096B
	.string "이렇게 강할 줄은\n"
	.string "전혀 예상도 못 했어!$"

Route124_Text_1C0994:: @ 81C0994
	.string "꾸준히 열심히 해온 나날들이\n"
	.string "바로 너의 실력이 된 거구나...!$"

Route124_Text_1C09CE:: @ 81C09CE
	.string "우후후후\n"
	.string "나는 잠수 전문 스위머다\l"
	.string "잠수는 나의 특기 중의 특기지!$"

Route124_Text_1C0A2F:: @ 81C0A2F
	.string "꼬륵꼬륵꼬륵...\n"
	.string "가라앉는다...$"

Route124_Text_1C0A52:: @ 81C0A52
	.string "바닷속으로 잠수할 수 있는 포인트가\n"
	.string "이 근처에 있는 것 같다!\l"
	.string "잠수 전문가의 피가 끓어오르는군...$"

Route124_Text_1C0ABD:: @ 81C0ABD
	.string "나미: 어휴-\p"
	.string "모처럼 바다에 왔는데\n"
	.string "동생이랑 같이 있다니...\p"
	.string "너! 기분 전환할 겸\n"
	.string "포켓몬 승부할래?!$"

Route124_Text_1C0B36:: @ 81C0B36
	.string "나미: 홍이 때문에 졌잖아!\n"
	.string "나중에 혼날 줄 알아!$"

Route124_Text_1C0B72:: @ 81C0B72
	.string "나미: 어휴-\p"
	.string "옆에 있는 게 동생이 아니라\n"
	.string "멋진 남자 친구라면 좋을 텐데...$"

Route124_Text_1C0BC8:: @ 81C0BC8
	.string "나미: 우리랑 승부할 거야?\n"
	.string "포켓몬 2마리가 없으면 안 돼$"

Route124_Text_1C0C0E:: @ 81C0C0E
	.string "홍이: 우리 누나는\n"
	.string "포켓몬 승부에 엄청 강해!\l"
	.string "지고서 엉엉 울지 말라고!$"

Route124_Text_1C0C4F:: @ 81C0C4F
	.string "홍이: 흐윽...\n"
	.string "미안해 누나...$"

Route124_Text_1C0C7F:: @ 81C0C7F
	.string "홍이: 우리 누나는\n"
	.string "화나면 엄청 무서워...\p"
	.string "그래서 남자 친구가 없어...$"

Route124_Text_1C0CE0:: @ 81C0CE0
	.string "홍이: 우리랑 승부하려고?\n"
	.string "그럼 포켓몬을 2마리 데려와!$"

Route124_Text_1C0D1F:: @ 81C0D1F
	.string "나미: 어휴-\p"
	.string "모처럼 바다에 왔는데\n"
	.string "동생이랑 같이 있다니...\p"
	.string "...어머? 너 오랜만이구나?\n"
	.string "기분 전환으로 포켓몬 승부할래?$"

Route124_Text_1C0DB5:: @ 81C0DB5
	.string "나미: 홍이 너!\n"
	.string "너 때문에 또 졌잖아!\l"
	.string "넌 오늘부터 특훈이야!!$"

Route124_Text_1C0E06:: @ 81C0E06
	.string "나미: 하-아\p"
	.string "나한테 멋진\n"
	.string "남자 친구가 있었으면...\p"
	.string "호흡을 척척 맞춰서\n"
	.string "상대가 누구든 간에\l"
	.string "이길 수 있을 텐데$"

Route124_Text_1C0E5C:: @ 81C0E5C
	.string "나미: 우리랑 승부할 거야?\n"
	.string "포켓몬 2마리가 없으면 안 돼$"

Route124_Text_1C0EA2:: @ 81C0EA2
	.string "홍이: 지면 내가 혼나니까\n"
	.string "진짜 젖 먹던 힘까지 다 내겠어!$"

Route124_Text_1C0EE5:: @ 81C0EE5
	.string "홍이: 흐앙-\n"
	.string "제발 좀 봐줘 누나-$"

Route124_Text_1C0F19:: @ 81C0F19
	.string "홍이: 우리 누나는\n"
	.string "화나면 엄청 무서워...\p"
	.string "이제 내일부터 나는 누나랑\n"
	.string "포켓몬 맹훈련이야...$"

Route124_Text_1C0F90:: @ 81C0F90
	.string "홍이: 우리랑 승부하려고?\n"
	.string "그럼 포켓몬을 2마리 데려와!$"

Route125_Text_1C0FCF:: @ 81C0FCF
	.string "네가 오는 소리를 듣고\n"
	.string "기다리고 있었어!$"

Route125_Text_1C1002:: @ 81C1002
	.string "졌어요!$"

Route125_Text_1C1013:: @ 81C1013
	.string "소리가 전달되는 속도는\n"
	.string "공기 중에서보다\l"
	.string "수중에서 더 빨라!$"

Route125_Text_1C104B:: @ 81C104B
	.string "이야-압!\n"
	.string "내 귀여운 포켓몬이다-!!$"

Route125_Text_1C1073:: @ 81C1073
	.string "져버렸다...!$"

Route125_Text_1C1083:: @ 81C1083
	.string "쏘드라의 매력에 빠져버려서\n"
	.string "나도 헤엄치게 되었다-!$"

Route125_Text_1C10C3:: @ 81C10C3
	.string "수영하다가 지쳐버렸어!\n"
	.string "나랑 한번 승부해볼래?$"

Route125_Text_1C10FB:: @ 81C10FB
	.string "넌 너무 강해!$"

Route125_Text_1C110C:: @ 81C110C
	.string "허억... 허억...\n"
	.string "이끼시티는 어느 쪽이더라?$"

Route125_Text_1C1136:: @ 81C1136
	.string "내가 키운 물포켓몬과\n"
	.string "승부해 볼래?$"

Route125_Text_1C1175:: @ 81C1175
	.string "졌다...$"

Route125_Text_1C117F:: @ 81C117F
	.string "넌 진짜 강하구나?!\n"
	.string "깜짝 놀랐어!$"

Route125_Text_1C11AF:: @ 81C11AF
	.string "나는야 듬직한 선원!\n"
	.string "전 세계의 바다를 건너는 남자지!$"

Route125_Text_1C11ED:: @ 81C11ED
	.string "크아아악-!\n"
	.string "이길 수 없다...!$"

Route125_Text_1C1208:: @ 81C1208
	.string "여울의 동굴은 시간에 따라\n"
	.string "바닷물이 차고 빠지는 걸 반복한다!\p"
	.string "참고로 밀물에서 썰물까지\n"
	.string "약 6시간이 걸린다고! 알고 있었나?$"

Route125_Text_1C1282:: @ 81C1282
	.string "오! 드디어 여기서 만났군\n"
	.string "일단 무조건 포켓몬 승부다!$"

Route125_Text_1C12C5:: @ 81C12C5
	.string "이길 수 없어\n"
	.string "절대 이길 수가 없다!$"

Route125_Text_1C12EE:: @ 81C12EE
	.string "여울의 동굴...\p"
	.string "바닷물의 밀물 썰물에 따라\n"
	.string "갈 수 있는 곳과\l"
	.string "갈 수 없는 곳이 있다\p"
	.string "참고로 밀물에서 썰물까지\n"
	.string "약 6시간이 걸린다고! 기억해둬!$"

Route125_Text_1C13A1:: @ 81C13A1
	.string "매희: 여울의 동굴에\n"
	.string "이상한 할아버지가 있대!\l"
	.string "너도 만나러 가는 중이니?$"

Route125_Text_1C13FF:: @ 81C13FF
	.string "매희: 이길 수 있다고 생각했는데...$"

Route125_Text_1C141C:: @ 81C141C
	.string "매희: 여울의 동굴에\n"
	.string "이상한 할아버지가 있는 거 맞지?\p"
	.string "자, 나호야 빨리 만나러 가자!$"

Route125_Text_1C146E:: @ 81C146E
	.string "매희: 안 된다니까!\n"
	.string "포켓몬이 2마리 없으면 안 된다고!$"

Route125_Text_1C14AB:: @ 81C14AB
	.string "나호: 선배님\n"
	.string "이런 곳에 뭐가 있다는 거죠?$"

Route125_Text_1C14E7:: @ 81C14E7
	.string "나호: 중간에 잠깐\n"
	.string "이길 뻔했을 때도 있었는데...$"

Route125_Text_1C1508:: @ 81C1508
	.string "나호: 선배... 진짜로 여울의 동굴에\n"
	.string "들어가려고요?\l"
	.string "옷이 다 젖어서 엉망이 될 텐데요?$"

Route125_Text_1C154F:: @ 81C154F
	.string "나호: 2대 1로 승부하다니\n"
	.string "우리들은 그런 짓 할 수 없어$"

Route126_Text_1C1590:: @ 81C1590
	.string "수영은 전신 운동!\n"
	.string "체력을 키우기에 안성맞춤이다!$"

Route126_Text_1C15C3:: @ 81C15C3
	.string "졌습니다-앗!$"

Route126_Text_1C15D8:: @ 81C15D8
	.string "보아라! 이 근육을!!\n"
	.string "매일 헤엄치고 있는 덕분이다!$"

Route126_Text_1C1627:: @ 81C1627
	.string "여기 솟아 있는 하얀 바위산이\n"
	.string "바로 루네시티다-!$"

Route126_Text_1C1660:: @ 81C1660
	.string "당한 건가?!$"

Route126_Text_1C166F:: @ 81C166F
	.string "루네시티의 입구를 못 찾겠다!\n"
	.string "대체 어디 있는 거지?$"

Route126_Text_1C16AB:: @ 81C16AB
	.string "오호호호홋!\n"
	.string "나는 인어야!$"

Route126_Text_1C16C5:: @ 81C16C5
	.string "거품이 되어 사라져 간다...\n"
	.string "보글보글보글...$"

Route126_Text_1C1702:: @ 81C1702
	.string "호되게 당했어...\n"
	.string "거품 속으로 도망이라도\l"
	.string "치고 싶은 기분이야...$"

Route126_Text_1C1741:: @ 81C1741
	.string "저기 너 말이야\n"
	.string "나랑 승부하지 않을래?$"

Route126_Text_1C1766:: @ 81C1766
	.string "안 돼-엥!$"

Route126_Text_1C1773:: @ 81C1773
	.string "이렇게 포켓몬과\n"
	.string "바다에서 노는 게 제일 좋아!$"

Route127_Text_1C17A8:: @ 81C17A8
	.string "나랑 승부하고 싶다고\n"
	.string "네 얼굴에 써있다고!$"

Route127_Text_1C17DD:: @ 81C17DD
	.string "으아아아아...$"

Route127_Text_1C17EC:: @ 81C17EC
	.string "좋은 승부를 한 뒤에는\n"
	.string "시원한 기분이 들지-$"

Route127_Text_1C1828:: @ 81C1828
	.string "지고 싶지 않다고 생각하는\n"
	.string "라이벌이 너에게는 있니?$"

Route127_Text_1C1860:: @ 81C1860
	.string "아아 무척 분해!$"

Route127_Text_1C1877:: @ 81C1877
	.string "라이벌이 있으면\n"
	.string "강해지고 싶다는 기분이\l"
	.string "점점 넘쳐흐르지$"

Route127_Text_1C18CC:: @ 81C18CC
	.string "낚시로 넣은\n"
	.string "온화한 마음...\l"
	.string "그 마음을 보여드리겠습니다...$"

Route127_Text_1C1930:: @ 81C1930
	.string "...졌지만\n"
	.string "마음만은 온화합니다$"

Route127_Text_1C195D:: @ 81C195D
	.string "낚이지 않아도 괜찮습니다\n"
	.string "계속 낚싯줄을 드리우고 있는 겁니다...$"

Route127_Text_1C19A3:: @ 81C19A3
	.string "어이쿠?! 파도타기를 쓰고 있는\n"
	.string "포켓몬을 낚아 올리고 말았나?$"

Route127_Text_1C19D6:: @ 81C19D6
	.string "이길 수가 없다!$"

Route127_Text_1C19E7:: @ 81C19E7
	.string "네 포켓몬은 강해 보이니\n"
	.string "낚아 올리면 아주 보람이 느껴지겠어!$"

Route127_Text_1C1A2E:: @ 81C1A2E
	.string "좋-았어!\n"
	.string "포켓몬광과 낚시광의 대결이다!$"

Route127_Text_1C1A73:: @ 81C1A73
	.string "으악! 낚싯줄이 엉켰다!\n"
	.string "채비를 잘해둘 걸 그랬군!$"

Route127_Text_1C1AA0:: @ 81C1AA0
	.string "낚시에서 낚싯줄이 엉키는 걸\n"
	.string "채비 엉킴이라고 하지$"

Route127_Text_1C1AE2:: @ 81C1AE2
	.string "무로마을의 포켓몬체육관에서\n"
	.string "배운 걸 지금 여기서 시험해 보겠어!!$"

Route127_Text_1C1B2A:: @ 81C1B2A
	.string "거친 파도에 휩쓸렸다!$"

Route127_Text_1C1B39:: @ 81C1B39
	.string "무로마을의 체육관 관장인 철구는\n"
	.string "옛날에 관동지방에서 시바라는\l"
	.string "남자와 함께 특훈했다고 하더군$"

Route127_Text_1C1B92:: @ 81C1B92
	.string "새포켓몬은 눈이 엄청나게 좋다!\n"
	.string "드넓은 하늘 높은 곳에서\l"
	.string "먹잇감을 찾아낸다고!$"

Route127_Text_1C1BD9:: @ 81C1BD9
	.string "후... 져버렸다$"

Route127_Text_1C1BEC:: @ 81C1BEC
	.string "이 주변엔\n"
	.string "잠수할 수 있을 것 같은 곳이\l"
	.string "굉장히 많군!\p"
	.string "하늘에서 보면\n"
	.string "바다의 색이 달라서 잘 보인다!$"

Route128_Text_1C1C67:: @ 81C1C67
	.string "그랜드시티까지는 아직 멀었지...$"

Route128_Text_1C1C95:: @ 81C1C95
	.string "나의 첫 승리도 아직 멀었군...$"

Route128_Text_1C1CC3:: @ 81C1CC3
	.string "계속 지기만 하는 인생이지만\n"
	.string "절대로 포기하지 않을 거야...!$"

Route128_Text_1C1D02:: @ 81C1D02
	.string "아직 힘이 남아 있으니\n"
	.string "그랜드시티를 목표로 헤엄쳐 나가겠어!$"

Route128_Text_1C1D45:: @ 81C1D45 //JP: 194D73
	.string "또 첫 승리를 얻지 못했다...$"

Route128_Text_1C1D6B:: @ 81C1D6B
	.string "포기하지 않으면\n"
	.string "언젠가는 이길 수 있다\l"
	.string "그랜드시티에도 도착할 수 있어...!$"

Route128_Text_1C1DB0:: @ 81C1DB0
	.string "트라이애슬론은\n"
	.string "수영, 자전거, 마라톤\p"
	.string "3개의 종목을 연이어 겨루는\n"
	.string "혹독한 레이스야!$"

Route128_Text_1C1E25:: @ 81C1E25
	.string "포켓몬 승부도 혹독하네...$"

Route128_Text_1C1E4A:: @ 81C1E4A
	.string "다음은 자전거 경주인데...\n"
	.string "기운이 없는 것 같아...$"

Route128_Text_1C1E90:: @ 81C1E90
	.string "트라이애슬론도 길지만\n"
	.string "포켓몬 챔피언을 노리는 것도\l"
	.string "먼 길이구나!$"

Route128_Text_1C1EFA:: @ 81C1EFA
	.string "정말\n"
	.string "포켓몬 승부는 힘드네...$"

Route128_Text_1C1F2E:: @ 81C1F2E
	.string "슬슬 챔피언 로드에\n"
	.string "도전해도 되려나?$"

Route128_Text_1C1F6D:: @ 81C1F6D
	.string "포켓몬리그에 도전하기 위해\n"
	.string "지금까지 노력해 왔어...\p"
	.string "여기서 질 수는 없는 거야!$"

Route128_Text_1C1FCC:: @ 81C1FCC
	.string "아앗!\n"
	.string "이럴 수가!$"

Route128_Text_1C1FE8:: @ 81C1FE8
	.string "여기까지 왔는걸...\n"
	.string "고작 한 번 졌다고 해서\l"
	.string "포기하지 않겠어$"

Route128_Text_1C202C:: @ 81C202C
	.string "나처럼 강한 포켓몬 트레이너는\n"
	.string "아마 또 없을 거다!$"

Route128_Text_1C2051:: @ 81C2051
	.string "어떻게 된 일이지...!$"

Route128_Text_1C2060:: @ 81C2060
	.string "나처럼 강한 포켓몬 트레이너는\n"
	.string "아마 또 없을 거다!$"

Route128_Text_1C2090:: @ 81C2090
	.string "그랜드시티에 가고 싶어서\n"
	.string "폭포오르기를 배운\l"
	.string "포켓몬을 낚았어!$"

Route128_Text_1C20FC:: @ 81C20FC
	.string "그 기세는\n"
	.string "마치 폭포오르기 같아!$"

Route128_Text_1C210D:: @ 81C210D
	.string "큰일 났다!\p"
	.string "폭포오르기를 배운\n"
	.string "포켓몬을 낚았지만\l"
	.string "루네시티의 체육관 배지가 없다!$"

Route129_Text_1C2161:: @ 81C2161
	.string "나는 초보 트라이애슬리트지\n"
	.string "첫 레이스에 긴장하고 있다!$"

Route129_Text_1C2198:: @ 81C2198
	.string "으아-!\n"
	.string "져버렸뜨아-!$"

Route129_Text_1C21B4:: @ 81C21B4
	.string "긴장하고 있으면\n"
	.string "제 실력을 발휘할 수 없지!$"

Route129_Text_1C21ED:: @ 81C21ED
	.string "트라이애슬론에\n"
	.string "한창 도전 중이긴 하지만\l"
	.string "잠깐만 승부 한판 하자고!$"

Route129_Text_1C222F:: @ 81C222F
	.string "이길 줄 알았는데-!$"

Route129_Text_1C2243:: @ 81C2243
	.string "대자연을 상대로\n"
	.string "자신의 힘을 시험하는 것도\l"
	.string "트라이애슬론의 묘미지!$"

Route129_Text_1C22C8:: @ 81C22C8
	.string "어이! 어이!\n"
	.string "얼른 승부하자고!$"

Route129_Text_1C22EC:: @ 81C22EC
	.string "졌다 졌어!\n"
	.string "얼른 끝내자고!$"

Route129_Text_1C230F:: @ 81C230F
	.string "졌으면 아무것도 없어\n"
	.string "얼른 집에 가야지!$"

Route129_Text_1C2349:: @ 81C2349
	.string "느긋-하게 천-천히 할까요?$"

Route129_Text_1C2378:: @ 81C2378
	.string "어머머\n"
	.string "더 느긋하게 하고 싶었는데...$"

Route129_Text_1C23A3:: @ 81C23A3
	.string "서두르다가 실수하면\n"
	.string "후회하게 되잖아요?\l"
	.string "느긋하게 하기로 했어요$"

Route130_Text_1C2401:: @ 81C2401
	.string "바다 한가운데에서 트레이너를\n"
	.string "만나다니 별일이 다 있군\l"
	.string "승부나 한판 벌여볼까?!$"

Route130_Text_1C245D:: @ 81C245D
	.string "이렇게 강한 어린애가 있다니...$"

Route130_Text_1C2479:: @ 81C2479
	.string "격렬한 승부를 헤쳐 나온\n"
	.string "멋진 눈빛이다!$"

Route130_Text_1C24DC:: @ 81C24DC
	.string "파란 바다를 보고 있으니\n"
	.string "파랗게 멍든 내 마음이\l"
	.string "낫는 것 같아...$"

Route130_Text_1C2525:: @ 81C2525
	.string "바다가 넓듯\n"
	.string "포켓몬의 세계도\l"
	.string "아직 넓디넓도다...$"

Route130_Text_1C256E:: @ 81C256E
	.string "어린이들은 모두\n"
	.string "포켓몬 챔피언을\l"
	.string "목표로 하고 있어...$"

Route131_Text_1C25B3:: @ 81C25B3
	.string "바다에는 포켓몬들이 많아서\n"
	.string "헤엄쳐서 건너기도 힘들어$"

Route131_Text_1C25F8:: @ 81C25F8
	.string "트레이너의 손으로 키운\n"
	.string "포켓몬은 정말 강하구나...$"

Route131_Text_1C262A:: @ 81C262A
	.string "허억허억... 지쳤어...\n"
	.string "출발할 때는 좋았지만\l"
	.string "돌아가는 게 문제야...\l"
	.string "돌아갈 체력이 남아 있을까...?$"

Route131_Text_1C26B9:: @ 81C26B9
	.string "바다 바다 바다...\n"
	.string "둘러봐도 온통 바다뿐...\l"
	.string "바다는 이제 질렸다고-!$"

Route131_Text_1C271F:: @ 81C271F
	.string "히에에에에엑!$"

Route131_Text_1C2726:: @ 81C2726
	.string "바다에 질려도\n"
	.string "속 헤엄칠 수밖에 없는 건가...\p"
	.string "그게 내 운명이겠지...$"

Route131_Text_1C2774:: @ 81C2774
	.string "잠깐 당신!\n"
	.string "저랑 승부합시다!$"

Route131_Text_1C27A4:: @ 81C27A4
	.string "겉보기와는 다르게\n"
	.string "강하군요-!$"

Route131_Text_1C27CF:: @ 81C27CF
	.string "저쪽에 바다는 질렸다고\n"
	.string "툴툴거리고 있는 남자 있죠?\p"
	.string "그건 그냥 하는 말일 뿐이고\n"
	.string "사실은 바다가 좋아서\l"
	.string "어쩔 줄을 모르고 있어요!$"

Route131_Text_1C284A:: @ 81C284A
	.string "왜 남자는\n"
	.string "비키니를 좋아하는 걸까?!\p"
	.string "다들 나를\n"
	.string "빤히 쳐다봐!$"

Route131_Text_1C2883:: @ 81C2883
	.string "나랑은 급이 다른 실력이야...!$"

Route131_Text_1C2898:: @ 81C2898
	.string "다들 비키니 때문에 보는 게 아니라\n"
	.string "내 미모를 감상하고 있는 건가...?$"

Route131_Text_1C28E2:: @ 81C28E2
	.string "애미: 남매가 힘을 합쳐서\n"
	.string "한번 열심히 해볼까?!$"

Route131_Text_1C2918:: @ 81C2918
	.string "애미: 남매가 힘을 합쳐도\n"
	.string "이길 수 없었어$"

Route131_Text_1C2950:: @ 81C2950
	.string "애미: 황금마을 사람은\n"
	.string "태어났을 때부터\l"
	.string "바다랑 포켓몬과 함께야$"

Route131_Text_1C29B2:: @ 81C29B2
	.string "애미: 포켓몬 2마리가 없어?\n"
	.string "포켓몬 승부를 즐길 수가 없겠네?$"

Route131_Text_1C29F3:: @ 81C29F3
	.string "승우: 남매가 힘을 합쳐서\n"
	.string "열심히 해보겠습니다-!$"

Route131_Text_1C2A20:: @ 81C2A20
	.string "승우: 누나랑 열심히 했는데도\n"
	.string "이길 수 없었어...$"

Route131_Text_1C2A5D:: @ 81C2A5D
	.string "승우: 황금마을은 바다 위에\n"
	.string "떠 있는 마을이잖아?\p"
	.string "그러니까 바다가 끝이 없듯이\n"
	.string "황금마을도 끝이 없는 거야!$"

Route131_Text_1C2ACA:: @ 81C2ACA
	.string "승우: 포켓몬이 2마리 있으면\n"
	.string "포켓몬 승부 해줄게!$"

Route132_Text_1C2AFB:: @ 81C2AFB
	.string "어렸을 때는 툭하면\n"
	.string "감기에 걸리곤 했는데\l"
	.string "수영을 시작하고 나서는\l"
	.string "이렇게 튼튼해졌어!$"

Route132_Text_1C2B5B:: @ 81C2B5B
	.string "더 강해지고 싶어...!$"

Route132_Text_1C2B71:: @ 81C2B71
	.string "포켓몬 트레이너도\n"
	.string "산과 들을 걸어 다니니\l"
	.string "정말 건강에 좋을 것 같아-!$"

Route132_Text_1C2BB5:: @ 81C2BB5
	.string "물살이 거센 곳에서는\n"
	.string "헤엄치지 않으려고 해$"

Route132_Text_1C2BEA:: @ 81C2BEA
	.string "꺄아아아아아앙-!$"

Route132_Text_1C2BFA:: @ 81C2BFA
	.string "물살에 떠밀리면 내가 어디 있는지\n"
	.string "알 수 없게 돼버려...$"

Route132_Text_1C2C32:: @ 81C2C32
	.string "이길 것인가 질 것인가\n"
	.string "승부하면 알게 되겠지!$"

Route132_Text_1C2C60:: @ 81C2C60
	.string "으앙-\n"
	.string "져버렸다-$"

Route132_Text_1C2C78:: @ 81C2C78
	.string "뻔히 이길 승부는 하지 않는다!\n"
	.string "이길 것인가 질 것인가\l"
	.string "그런 아슬아슬한 느낌이 좋거든!$"

Route132_Text_1C2CD9:: @ 81C2CD9
	.string "24시간 포켓몬만 생각하고 있는\n"
	.string "이 몸을 이길 수 있을 것 같나?!$"

Route132_Text_1C2D1F:: @ 81C2D1F
	.string "졌다\n"
	.string "너에게 져버렸다$"

Route132_Text_1C2D3E:: @ 81C2D3E
	.string "크으...\n"
	.string "너도 포켓몬밖에 모르는군!\p"
	.string "24시간 오로지\n"
	.string "포켓몬 생각밖에 안 하고 있구나!$"

Route133_Text_1C2DA5:: @ 81C2DA5
	.string "너도 물살에 떠밀려 왔니?\n"
	.string "이것도 어떻게 보면 인연이구나\l"
	.string "승부하자!$"

Route133_Text_1C2DF4:: @ 81C2DF4
	.string "강해!\n"
	.string "너무 강해!$"

Route133_Text_1C2E09:: @ 81C2E09
	.string "너 같은 강한 트레이너가\n"
	.string "떠밀려 오다니...\l"
	.string "난 참 운이 없군...$"

Route133_Text_1C2E61:: @ 81C2E61
	.string "나는 불쌍한 여자...\n"
	.string "여기저기 휩쓸리다가\l"
	.string "여기까지 왔어...$"

Route133_Text_1C2EBD:: @ 81C2EBD
	.string "졌어...$"

Route133_Text_1C2ECD:: @ 81C2ECD
	.string "휩쓸리기만 하는 인생이라니...\n"
	.string "이제 싫엇!$"

Route133_Text_1C2EF7:: @ 81C2EF7
	.string "어서 오세요-옷!\n"
	.string "기다리고 있었습니다!$"

Route133_Text_1C2F19:: @ 81C2F19
	.string "싫어-!$"

Route133_Text_1C2F25:: @ 81C2F25
	.string "어린 트레이너가 이렇게 강하다니...\n"
	.string "다 큰 어른으로서 부끄러워욧!$"

Route133_Text_1C2F53:: @ 81C2F53
	.string "이기고 싶다고 해서\n"
	.string "남들과 똑같은 포켓몬으로\l"
	.string "키우고 싶지는 않아!$"

Route133_Text_1C2FA3:: @ 81C2FA3
	.string "제길-!\n"
	.string "내 방식이 너무 물렀나!$"

Route133_Text_1C2FC7:: @ 81C2FC7
	.string "남이랑 똑같은 걸 하는 것보다는\n"
	.string "내가 하고 싶은 대로 하는 게\l"
	.string "당연히 즐겁지!$"

Route133_Text_1C302D:: @ 81C302D
	.string "새포켓몬과 함께\n"
	.string "이런 곳까지 와버렸습니다$"

Route133_Text_1C305F:: @ 81C305F
	.string "너...\n"
	.string "어떻게 그렇게 멋있을 수 있지?!$"

Route133_Text_1C307E:: @ 81C307E
	.string "슬슬 검방울시티로 돌아가고 싶은데\n"
	.string "여기가 마음에 들고 말았어! 왜지?!$"

Route134_Text_1C30C6:: @ 81C30C6
	.string "헤엄치는 게 특기인 포켓몬도\n"
	.string "떠밀려가 버릴 정도로\l"
	.string "이곳의 물살은 거세지!$"

Route134_Text_1C3110:: @ 81C3110
	.string "히에-엣!$"

Route134_Text_1C311A:: @ 81C311A
	.string "포켓몬들은 이 물살을\n"
	.string "즐기고 있는 것 같아!$"

Route134_Text_1C315E:: @ 81C315E
	.string "제 사랑동이들과\n"
	.string "즐겁게 승부합시다!$"

Route134_Text_1C3198:: @ 81C3198
	.string "어머머머머멋!$"

Route134_Text_1C31A0:: @ 81C31A0
	.string "어딘가에 있는 마니아가\n"
	.string "사랑동이의 비늘을 모으고 있어요-$"

Route134_Text_1C31D7:: @ 81C31D7
	.string "오케-이! 휴식 끝!\n"
	.string "포켓몬 승부다!$"

Route134_Text_1C3213:: @ 81C3213
	.string "또 지쳤다...$"

Route134_Text_1C3229:: @ 81C3229
	.string "내 새포켓몬들은...\n"
	.string "조금만 오래 날면 금방 지치고 말아$"

Route134_Text_1C3262:: @ 81C3262
	.string "포켓몬 트레이너라면\n"
	.string "말 따윈 필요 없지\l"
	.string "바로 포켓몬 승부다!$"

Route134_Text_1C329E:: @ 81C329E
	.string "... ... ...\n"
	.string "... ... ...$"

Route134_Text_1C32D6:: @ 81C32D6
	.string "스스로 승부를 걸어 놓고\n"
	.string "져버리다니...\l"
	.string "부끄러움이 하늘을 찌른다...$"

Route134_Text_1C3319:: @ 81C3319
	.string "이곳의 격렬한 물살!\n"
	.string "이 또한 우리를 단련시켜준다!$"

Route134_Text_1C335C:: @ 81C335C
	.string "솔직하게 패배를 인정하겠다$"

Route134_Text_1C336E:: @ 81C336E
	.string "유성의 폭포에서\n"
	.string "다시 수행하겠다!\p"
	.string "괜찮으면 너도 가봐\n"
	.string "반드시 지금보다 강해질 거야!$"
