TrainerEyeDescription_0: //JP: 3B7F38
	.string "부드럽게 해줘야지$"
	.string "좋은 향기의 풀포켓몬$"
	.string "좋은 향기가 몸과$"
	.string "마음을 건강하게 해줍니다!$"
TrainerEyeDescription_1:
	.string "힘으로 밀어붙이기가 신조!$"
	.string "거친 바위포켓몬!$"
	.string "고대의 로망을 찾아$"
	.string "동서남북 어디든지!$"
TrainerEyeDescription_2:
	.string "열심히 하겠습니다-!$"
	.string "헤엄을 잘 치는 포켓몬$"
	.string "튜브가 없어도$"
	.string "헤엄칠 수 있도록 되고 싶어-$"
TrainerEyeDescription_3:
	.string "잘 모르겠지만 힘낼 거야$"
	.string "물포켓몬은 친구!$"
	.string "헤엄을 못 치는 게 아니야!$"
	.string "튜브를 좋아하는 것뿐이다!$"
TrainerEyeDescription_4:
	.string "역할분담을 하고 있어$"
	.string "사이가 좋은 포켓몬이야!$"
	.string "남매가 사이좋게$"
	.string "포켓몬을 즐긴다!$"
TrainerEyeDescription_5:
	.string "상대의 약점을 공략한다$"
	.string "밸런스가 생명이야!$"
	.string "목표는 포켓몬 챔피언$"
	.string "포기하지 않을 거야!$"
TrainerEyeDescription_6:
	.string "상대가 싫어하는 배틀$"
	.string "타입을 가리지 않고 무엇이든$"
	.string "트레이너스쿨의$"
	.string "우등생이란 말이다$"
TrainerEyeDescription_7:
	.string "서서히 괴롭히겠습니다$"
	.string "밤에 만나면 무섭습니다$"
	.string "다른 사람에게는 보이지$"
	.string "않는 것이 보인단다...$"
TrainerEyeDescription_8:
	.string "이기면 되잖아?$"
	.string "럭셔리한 타입이야!$"
	.string "집에는 포켓몬 전용의$"
	.string "풀장이 있어$"
TrainerEyeDescription_9:
	.string "홀려버리겠어$"
	.string "귀여운 거$"
	.string "사파리존 정말 좋아!$"
	.string "나도 모르게 가게 돼$"
TrainerEyeDescription_10:
	.string "작전 따위는 필요 없다고$"
	.string "돈을 들여서 키웠단다!$"
	.string "나는 부자라서$"
	.string "포켓몬 침대에서 잠을 자지$"
TrainerEyeDescription_11:
	.string "파워로 굴복시키겠다...$"
	.string "밤을 꼬박 새워서 잡았다...$"
	.string "크고 늠름한$"
	.string "포켓몬이 최고...$"
TrainerEyeDescription_12:
	.string "온 힘을 다하여 싸운다!$"
	.string "좋은 물타입$"
	.string "헤엄칠 수 없을 때는$"
	.string "근육 단련을 하고 있다!$"
TrainerEyeDescription_13:
	.string "타격기술로 팍팍!$"
	.string "격투타입$"
	.string "자랑은 아니지만$"
	.string "기왓장을 10개는 깬다고!$"
TrainerEyeDescription_14:
	.string "찌릿찌릿 저리게 만들어주마!$"
	.string "전기의 힘을 보여주겠어!$"
	.string "내 마음의 멜로디로$"
	.string "모두를 울려주고 싶어$"
TrainerEyeDescription_15:
	.string "불꽃으로 모두 불태운다!$"
	.string "화상을 입을 것 같은 포켓몬$"
	.string "캠프파이어를 할 때는$"
	.string "불 끌 물을 잊지 마$"
TrainerEyeDescription_16:
	.string "버티고 버티고 버틴다!$"
	.string "어떤 포켓몬이든 키운다$"
	.string "자연에서 자란 포켓몬은$"
	.string "강해진다!$"
TrainerEyeDescription_17:
	.string "부부간의 사랑으로 이길 거야$"
	.string "긴 세월을 함께한 포켓몬$"
	.string "결혼하고 50년$"
	.string "포켓몬을 키워왔구먼$"
TrainerEyeDescription_18:
	.string "쉴 틈을 주지 않는 공격$"
	.string "벌레포켓몬은 멋있잖아$"
	.string "매일... 숲에 들어가서$"
	.string "벌레포켓몬을 잡는다...$"
TrainerEyeDescription_19:
	.string "상대를 농락한다$"
	.string "이상한 힘을 지닌 녀석$"
	.string "너의 생각은$"
	.string "모조리 꿰뚫어봤다!$"
TrainerEyeDescription_20:
	.string "풀파워로 싸운다$"
	.string "비밀이 많은 포켓몬$"
	.string "솔직히 말하자면$"
	.string "난 텔레파시로 말했어$"
TrainerEyeDescription_21:
	.string "당황하지 않고 허둥대지 않고$"
	.string "기품이 넘치는 포켓몬$"
	.string "외국에서 받은 선물로$"
	.string "매일 티타임을 가진답니다$"
TrainerEyeDescription_22:
	.string "머리를 써서 싸울 거야$"
	.string "포켓몬은 무엇이든 좋아해!$"
	.string "테스트에서 점수를 잘 받으면$"
	.string "아빠가 용돈을 주신다고!$"
TrainerEyeDescription_23:
	.string "지식이라면 지지 않아!$"
	.string "영리한 포켓몬!$"
	.string "장래희망은$"
	.string "포켓몬 연구자가 되는 거야!$"
TrainerEyeDescription_24:
	.string "둘이서 상담!$"
	.string "우리 둘이 좋아하는 포켓몬!$"
	.string "우리는 포켓몬클럽의$"
	.string "선배와 후배입니다-!$"
TrainerEyeDescription_25:
	.string "힘내라 포켓몬아!$"
	.string "가리는 건 없어$"
	.string "저녁거리 쇼핑을 하는 김에$"
	.string "승부 한판 하는 거야$"
TrainerEyeDescription_26:
	.string "애정으로 승부!$"
	.string "사랑을 쏟은 포켓몬$"
	.string "포켓몬과 신뢰관계를$"
	.string "쌓는 것이 중요해!$"
TrainerEyeDescription_27:
	.string "자네의 공격은 간파했다$"
	.string "격투의 필살기를 보아라!$"
	.string "젊은이에게는 더욱$"
	.string "질 수 없지!$"
TrainerEyeDescription_28:
	.string "방어하면서 공격!$"
	.string "격투타입이란다$"
	.string "늙은이에게는 늙은이만의$"
	.string "배틀 방법이 있단다$"
TrainerEyeDescription_29:
	.string "할 수 있는 건 해버리겠어!$"
	.string "여러 타입으로 승부$"
	.string "체육관 관장에게 이길 때까지$"
	.string "열심히 하겠어!$"
TrainerEyeDescription_30:
	.string "침착하게 승부!$"
	.string "물포켓몬으로 승부$"
	.string "그렇게 큼지막한 포켓몬을$"
	.string "낚은 사람은 세상에 나뿐이다$"
TrainerEyeDescription_31:
	.string "방어를 중요하게$"
	.string "내 포켓몬은 왕 딱딱$"
	.string "다이어트로 할 생각이었는데$"
	.string "즐거워서 빠져버렸다$"
TrainerEyeDescription_32:
	.string "시종일관 압도하는 작전!$"
	.string "강철의 강함을 보여주마$"
	.string "땀을 흘렸다면 틈틈이$"
	.string "수분을 보충하자!$"
TrainerEyeDescription_33:
	.string "지리를 이용한다$"
	.string "물타입 만세!$"
	.string "물놀이하는 수영팬티$"
	.string "소년에게는 지지 않아$"
TrainerEyeDescription_34:
	.string "팍팍 공격한다!$"
	.string "물포켓몬 최고!$"
	.string "매일 10킬로는$"
	.string "헤엄치고 있어!$"
TrainerEyeDescription_35:
	.string "스피드는 생명!$"
	.string "빠른 포켓몬을 쓴다$"
	.string "마라톤은 자신과의$"
	.string "승부란다!$"
TrainerEyeDescription_36:
	.string "상대보다 먼저 공격!$"
	.string "잘 달리는 포켓몬$"
	.string "계속해서 달리면$"
	.string "바람이 될 수 있는 거다...!$"
TrainerEyeDescription_37:
	.string "포켓몬의 파워가 전부다!$"
	.string "드래곤의 강함을 봐라!$"
	.string "언젠가 최강 전설을$"
	.string "만들어 보이겠어!$"
TrainerEyeDescription_38:
	.string "나의 테크닉을 보여주마$"
	.string "새포켓몬의 화려한 춤!$"
	.string "새포켓몬아, 내 마음을$"
	.string "저 아이에게 전해주렴$"
TrainerEyeDescription_39:
	.string "독 공격으로 괴롭힌다$"
	.string "맹독의 포켓몬$"
	.string "닌자가 되기 위해$"
	.string "매일 수행을 하고 있다$"
TrainerEyeDescription_40:
	.string "선수쳐서 반드시 이긴다!$"
	.string "민첩한 격투타입$"
	.string "포켓몬으로 진다면$"
	.string "내가 싸울 테다!$"
TrainerEyeDescription_41:
	.string "힘내라, 내 포켓몬!$"
	.string "무엇이든 키운다고!$"
	.string "자외선은 피부의 적$"
	.string "조심하지 않으면 안되겠지!$"
TrainerEyeDescription_42:
	.string "봐주지 않겠다!$"
	.string "귀여운 물포켓몬$"
	.string "팬이 많아서 곤란해$"
	.string "TV 취재도 받았는데$"
TrainerEyeDescription_43:
	.string "여러 가지 생각하고 있어$"
	.string "포켓몬은 모두 좋아$"
	.string "저 언덕 너머에는$"
	.string "무엇이 있을까...?$"
TrainerEyeDescription_44:
	.string "함께 싸우는 거야!$"
	.string "함께 키우는 거야!$"
	.string "좋아하는 포켓몬은 같지만$"
	.string "디저트의 취향은 달라$"
TrainerEyeDescription_45:
	.string "힘으로 누르겠어$"
	.string "물과 격투타입$"
	.string "바다의 사나이는 거칠다$"
	.string "어이- 불만 있느냐?$"
TrainerEyeDescription_46:
	.string "포켓몬이 다치지 않게$"
	.string "희귀한 포켓몬 아주 좋아해$"
	.string "이 세상의 희귀한$"
	.string "포켓몬을 손에 넣고 싶다!$"
TrainerEyeDescription_47:
	.string "강건하게 승부하겠습니다$"
	.string "포켓몬은 내 새끼$"
	.string "포켓몬을 키우는 요령은$"
	.string "지식과 애정이야!$"
TrainerEyeDescription_48:
	.string "팍팍 압도하겠습니다!$"
	.string "무엇이든 키운다$"
	.string "포켓몬스넥을 많이 주고$"
	.string "콘테스트도 노리고 있습니다$"
TrainerEyeDescription_49:
	.string "포켓몬의 힘을 믿는다$"
	.string "강한 포켓몬이 좋다$"
	.string "포켓몬과 함께$"
	.string "구조훈련을 하고 있어$"
TrainerEyeDescription_50:
	.string "쉴 틈을 주지 않는 공격$"
	.string "여러 타입으로 승부$"
	.string "자연을 훼손시키는 녀석은$"
	.string "절대 용서하지 않는다!$"
TrainerEyeDescription_51:
	.string "근성을 보여줘야지!$"
	.string "귀여운 포켓몬 아주 좋아해!$"
	.string "승부한 뒤에는 포켓몬과$"
	.string "목욕을 합니다-!$"
TrainerEyeDescription_52:
	.string "재빠른 공격이다!$"
	.string "벌레타입이 제일!$"
	.string "벌레포켓몬을 잡으려면$"
	.string "아침 일찍 일어나야 돼$"
TrainerEyeDescription_53:
	.string "파워로 승부!$"
	.string "단단한 몸의 포켓몬!$"
	.string "오늘의 등산을 위해$"
	.string "1개월 전부터 계획했다$"
TrainerEyeDescription_54:
	.string "러브러브 작전!$"
	.string "러브러브 포켓몬!$"
	.string "우리는 러브러브!$"
	.string "영원히 러브러브!$"
TrainerEyeDescription_55:
	.string "마음을 모조리 쏟겠습니다$"
	.string "처음으로 잡은 포켓몬$"
	.string "나랑 포켓몬은$"
	.string "함께 강해졌어요$"
TrainerEyeDescription_56:
	.string "바위타입 파워로 공격$"
	.string "튼실한 타입이 좋지요$"
	.string "승부를 하면서 포켓몬의$"
	.string "모든 것을 알고 싶습니다$"
TrainerEyeDescription_57:
	.string "직접 타격이 특기$"
	.string "격투포켓몬은 나의 생명!$"
	.string "세상의 빅웨이브가$"
	.string "나를 부른다!$"
TrainerEyeDescription_58:
	.string "찌릿찌릿 감전시킨다$"
	.string "전기 파워를 받아라!$"
	.string "아하하하핫! 건강의 비결은$"
	.string "좌우간 웃는 것이지$"
TrainerEyeDescription_59:
	.string "단숨에 공격한다$"
	.string "불타는 정열의 불꽃!$"
	.string "하루의 피로는$"
	.string "온천에서 가뿐하게!$"
TrainerEyeDescription_60:
	.string "임기응변으로 승부한다$"
	.string "밸런스 좋게 키우고 있다$"
	.string "포켓몬 외길 인생...$"
	.string "이 길은 험하다...$"
TrainerEyeDescription_61:
	.string "스피드를 잘 살려서 승부한다$"
	.string "화려하게 하늘에서 춤춘다!$"
	.string "나에게는 바람의$"
	.string "흐름이 보인다$"
TrainerEyeDescription_62:
	.string "둘이서 협력!$"
	.string "언제나 사이좋은 포켓몬!$"
	.string "서로의 마음을 안다$"
	.string "상대의 마음도 안다$"
TrainerEyeDescription_63:
	.string "한 수 가르침을 부탁합니다$"
	.string "우아한 포켓몬이 좋아$"
	.string "물의 일루전은$"
	.string "화려한 나에게 어울린다$"
TrainerEyeDescription_64:
	.string "방어보다도 공격!$"
	.string "악의 미학!$"
	.string "뭐니 뭐니 해도$"
	.string "강하기만 하다면 좋잖아?$"
TrainerEyeDescription_65:
	.string "상대를 현혹시켜서 승부한다$"
	.string "종잡을 수가 없어요$"
	.string "송화산의 할머니$"
	.string "건강하게 지내고 계실까?$"
TrainerEyeDescription_66:
	.string "도구를 구사하여 승부한다$"
	.string "빙점 아래의 정열!$"
	.string "따뜻한 지역이기 때문에$"
	.string "얼음타입이 단련된다!$"
TrainerEyeDescription_67:
	.string "뛰어난 능력으로 공격한다!$"
	.string "드래곤타입의 저력!$"
	.string "포켓몬과 서로 이해하기 위해$"
	.string "오늘도 승부를 계속한다...$"
TrainerEyeDescription_68:
	.string "상대의 약점을 공략한다!$"
	.string "최강의 강철포켓몬$"
	.string "결국 내가 제일$"
	.string "강하고 멋있어$"

	.align 2
gTrainerEyeDescriptions:: @ 83E309C
	.4byte TrainerEyeDescription_0
	.4byte TrainerEyeDescription_1
	.4byte TrainerEyeDescription_2
	.4byte TrainerEyeDescription_3
	.4byte TrainerEyeDescription_4
	.4byte TrainerEyeDescription_5
	.4byte TrainerEyeDescription_6
	.4byte TrainerEyeDescription_7
	.4byte TrainerEyeDescription_8
	.4byte TrainerEyeDescription_9
	.4byte TrainerEyeDescription_10
	.4byte TrainerEyeDescription_11
	.4byte TrainerEyeDescription_12
	.4byte TrainerEyeDescription_13
	.4byte TrainerEyeDescription_14
	.4byte TrainerEyeDescription_15
	.4byte TrainerEyeDescription_16
	.4byte TrainerEyeDescription_17
	.4byte TrainerEyeDescription_18
	.4byte TrainerEyeDescription_19
	.4byte TrainerEyeDescription_20
	.4byte TrainerEyeDescription_21
	.4byte TrainerEyeDescription_22
	.4byte TrainerEyeDescription_23
	.4byte TrainerEyeDescription_24
	.4byte TrainerEyeDescription_25
	.4byte TrainerEyeDescription_26
	.4byte TrainerEyeDescription_27
	.4byte TrainerEyeDescription_28
	.4byte TrainerEyeDescription_29
	.4byte TrainerEyeDescription_30
	.4byte TrainerEyeDescription_31
	.4byte TrainerEyeDescription_32
	.4byte TrainerEyeDescription_33
	.4byte TrainerEyeDescription_34
	.4byte TrainerEyeDescription_35
	.4byte TrainerEyeDescription_36
	.4byte TrainerEyeDescription_37
	.4byte TrainerEyeDescription_38
	.4byte TrainerEyeDescription_39
	.4byte TrainerEyeDescription_40
	.4byte TrainerEyeDescription_41
	.4byte TrainerEyeDescription_42
	.4byte TrainerEyeDescription_43
	.4byte TrainerEyeDescription_44
	.4byte TrainerEyeDescription_45
	.4byte TrainerEyeDescription_46
	.4byte TrainerEyeDescription_47
	.4byte TrainerEyeDescription_48
	.4byte TrainerEyeDescription_49
	.4byte TrainerEyeDescription_50
	.4byte TrainerEyeDescription_51
	.4byte TrainerEyeDescription_52
	.4byte TrainerEyeDescription_53
	.4byte TrainerEyeDescription_54
	.4byte TrainerEyeDescription_55
	.4byte TrainerEyeDescription_56
	.4byte TrainerEyeDescription_57
	.4byte TrainerEyeDescription_58
	.4byte TrainerEyeDescription_59
	.4byte TrainerEyeDescription_60
	.4byte TrainerEyeDescription_61
	.4byte TrainerEyeDescription_62
	.4byte TrainerEyeDescription_63
	.4byte TrainerEyeDescription_64
	.4byte TrainerEyeDescription_65
	.4byte TrainerEyeDescription_66
	.4byte TrainerEyeDescription_67
	.4byte TrainerEyeDescription_68
