gTrainerClassNames:: @ 81F0208
	.string "포켓몬 트레이너$", 16
	.string "포켓몬 트레이너$", 16
	.string "아쿠아단리더$", 16
	.string "아쿠아단$", 16
	.string "아쿠아단간부$", 16
	.string "아로마 아가씨$", 16
	.string "유적마니아$", 16
	.string "인터뷰어$", 16
	.string "튜브걸$", 16
	.string "튜브보이$", 16
	.string "엘리트 트레이너$", 16
	.string "오컬트마니아$", 16
	.string "아기씨$", 16
	.string "아가씨$", 16
	.string "도련님$", 16
	.string "포켓몬 매니아$", 16
	.string "수영팬티소년$", 16
	.string "태권왕$", 16
	.string "기타리스트$", 16
	.string "캠프파이어$", 16
	.string "캠프보이$", 16
	.string "곤충마니아$", 16
	.string "초능력자$", 16
	.string "신사$", 16
	.string "사천왕$", 16
	.string "체육관 관장$", 16
	.string "학원 끝난 아이$", 16
	.string "선배&후배$", 16
	.string "연승가족$", 16
	.string "애호가클럽$", 16
	.string "달인$", 16
	.string "반바지 꼬마$", 16
	.string "챔피언$", 16
	.string "낚시꾼$", 16
	.string "트라이애슬리트$", 16
	.string "드래곤 조련사$", 16
	.string "새 조련사$", 16
	.string "닌자놀이$", 16
	.string "배틀걸$", 16
	.string "파라솔 아가씨$", 16
	.string "비키니 아가씨$", 16
	.string "피크닉걸$", 16
	.string "쌍둥이$", 16
	.string "선원$", 16
	.string "보더$", 16
	.string "포켓몬 컬렉터$", 16
	.string "포켓몬 트레이너$", 16
	.string "포켓몬 브리더$", 16
	.string "포켓몬 레인저$", 16
	.string "마그마단리더$", 16
	.string "마그마단$", 16
	.string "마그마단간부$", 16
	.string "짧은 치마$", 16
	.string "곤충채집소년$", 16
	.string "등산가$", 16
	.string "러브러브커플$", 16
	.string "금혼식부부$", 16
	.string "바다남매$", 16
