FallarborTown_ContestLobby_Text_1A6F7C:: @ 81A6F7C
	.string "어라? 당신은 포켓몬 콘테스트에\n"
	.string "참가했었군요!\l"
	.string "그 포켓몬을 보면 알 수 있죠!\p"
	.string "저는 포켓몬 콘테스트에 대해\n"
	.string "기사를 쓰고 있습니다만\p"
	.string "괜찮다면 조금 감상을\n"
	.string "들려주시지 않겠습니까?$"

FallarborTown_ContestLobby_Text_1A704E:: @ 81A704E
	.string "정말입니까!\n"
	.string "감사합니다\p"
	.string "그럼 지금 콘테스트의 감상을\n"
	.string "한마디로 부탁합니다!$"

FallarborTown_ContestLobby_Text_1A70A5:: @ 81A70A5
	.string "으-음 그렇군요!\p"
	.string "어떤 콘테스트였는지\n"
	.string "잘 알 수 있는 한마디네요!\p"
	.string "...마지막으로\n"
	.string "조금 묻고 싶은 게 있습니다만\p"
	.string "당신이 생각하는 {STR_VAR_2}{K_EUNNEUN}\n"
	.string "대체 어떤 것인가요?$"

FallarborTown_ContestLobby_Text_1A7153:: @ 81A7153
	.string "그렇군요!\p"
	.string "그게 당신이 생각하는\n"
	.string "{STR_VAR_2}{K_I}군요!\p"
	.string "여러 가지 참고가 되었습니다!\p"
	.string "콘테스트에 대해 좋은\n"
	.string "기사를 쓸 수 있을 것 같습니다\p"
	.string "혹시 TV에 이 이야기가\n"
	.string "나올지도 모르니\l"
	.string "기대해 주세요!$"

FallarborTown_ContestLobby_Text_1A7256:: @ 81A7256
	.string "그렇군요...\p"
	.string "다음에 재미있는 게 있으면\n"
	.string "들려주세요$"

FallarborTown_ContestLobby_Text_1A72A8:: @ 81A72A8
	.string "다음 포켓몬 콘테스트도\n"
	.string "기대하고 있어요!$"

gTVBravoTrainerText1:: @ 81A72DE
	.string "이야-!\n"
	.string "“브라보 트레이너”의 시간이야!\p"
	.string "오늘은 {STR_VAR_3} 클래스의\n"
	.string "{STR_VAR_2}{K_EULREUL} 자랑하는\l"
	.string "{STR_VAR_1}의 포켓몬!$"

gTVBravoTrainerText2:: @ 81A736B
	.string "{STR_VAR_1}의 “{STR_VAR_2}”의\n"
	.string "소개다-!\p"
	.string "“{STR_VAR_2}”인가...\p"
	.string "벌써 닉네임에서부터\n"
	.string "{STR_VAR_3}{K_IGA} 넘쳐나는데!$"

gTVBravoTrainerText3:: @ 81A73CA
	.string "그-리고 이 {STR_VAR_1}{K_IGA}\n"
	.string "포켓몬 콘테스트에 참가햇을 때\l"
	.string "자신의 포켓몬에 대해\l"
	.string "열심히 이야기해 주었다고!$"

gTVBravoTrainerText4:: @ 81A744D
	.string "콘테스트를 한 뒤의\n"
	.string "감상을 물었더니\l"
	.string "무척 기쁜 듯이\p"
	.string "“{STR_VAR_2}”{K_I}라고\n"
	.string "대답해 주었어!\p"
	.string "뭐 콘테스트에서는\n"
	.string "{STR_VAR_3}번이었으니까-!\p"
	.string "지금의 {STR_VAR_1}에게는\n"
	.string "정말로 딱 맞는 말이야!$"

gTVBravoTrainerText5:: @ 81A7508
	.string "콘테스트를 한 뒤의\n"
	.string "감상을 물었더니\l"
	.string "미묘하게 분해하면서\p"
	.string "“{STR_VAR_2}”{K_I}라고\n"
	.string "대답해 주었어!\p"
	.string "뭐 콘테스트에서는\n"
	.string "{STR_VAR_3}번이었으니까-!\p"
	.string "이 말에 {STR_VAR_1}의\n"
	.string "분함이 잘 드러나네-!$"

gTVBravoTrainerText6:: @ 81A75CE
	.string "그나저나 {STR_VAR_1} 목표로 하는\n"
	.string "{STR_VAR_2}{K_EUNNEUN} 대체 뭘까?\l"
	.string "물어보고 싶네-!\p"
	.string "물론 물어봤습니다!\p"
	.string "그건 다음 한마디에\n"
	.string "모두 담겨 있습니다!\p"
	.string "그건 “{STR_VAR_3}!”\p"
	.string "그것이야말로 {STR_VAR_1}의\n"
	.string "{STR_VAR_1}의 모든 겁니다!$"

gTVBravoTrainerText7:: @ 81A768D
	.string "마지막으로 {STR_VAR_1}{K_IGA}\n"
	.string "쓴 {STR_VAR_2}도\l"
	.string "모두 “{STR_VAR_3}”인 겁니다!$"

gTVBravoTrainerText8:: @ 81A76C5
	.string "브라보-! {STR_VAR_1}\n"
	.string "브라보-!! {STR_VAR_2}\p"
	.string "앞으로 {STR_VAR_1}의 활약에\n"
	.string "기대하고 싶네-!\p"
	.string "자 그럼 다시 다음\n"
	.string "방송에서 만납시다-!$"

gTVBravoTrainerText9:: @ 81A774F
	.string "{STR_VAR_1}의 소개다!$"

BattleTower_Lobby_Text_1A776D:: @ 81A776D
	.string "아! 지금 막 배틀한\n"
	.string "트레이너 분이시군요!\p"
	.string "저는 지금 여러 트레이너의\n"
	.string "이야기를 물으며 다니고 있는데요\p"
	.string "배틀이 끝난 감상을\n"
	.string "조금만 들려주시지 않겠습니까?$"

BattleTower_Lobby_Text_1A7823:: @ 81A7823
	.string "정말?!\n"
	.string "고마워!\l"
	.string "아 그럼 말이죠...\p"
	.string "이번 배틀타워의\n"
	.string "대전은 어떠셨습니까\p"
	.string "만족하셨습니까!\n"
	.string "아니면 불만이 있습니까!$"

BattleTower_Lobby_Text_1A78B7:: @ 81A78B7
	.string "아!\n"
	.string "죄송합니다\p"
	.string "그럼 다음에 배틀타워에 오면\n"
	.string "들려주세요$"

BattleTower_Lobby_Text_1A791B:: @ 81A791B
	.string "역시나 그렇군요!\p"
	.string "그 만족한 얼굴을 보면\n"
	.string "얼마나 좋은 시합이었는지\l"
	.string "알 수 있어요!$"

BattleTower_Lobby_Text_1A7990:: @ 81A7990
	.string "으-음 그렇습니까...\p"
	.string "생각한 대로 승부한다는 건\n"
	.string "상당히 어려운 일이니까요...$"

BattleTower_Lobby_Text_1A79EB:: @ 81A79EB
	.string "아 그리고\p"
	.string "하나만 더 괜찮겠습니까?\n"
	.string "이번 배틀의 감상을\l"
	.string "한마디로 딱 맞게 들려주세요!$"

BattleTower_Lobby_Text_1A7A6E:: @ 81A7A6E
	.string "멋있어-!!\p"
	.string "좋은 마무리 대사네요\n"
	.string "다음 배틀도 기대하고 있어요\p"
	.string "그럼 나중에 또 봐요!$"

BattleTower_Lobby_Text_1A7AE0:: @ 81A7AE0
	.string "그렇군요...\p"
	.string "하지만 아무 말도 하지 않아도\n"
	.string "그것도 멋있어요!\p"
	.string "그럼 다음 기회에\n"
	.string "감상을 들려주세요!$"

BattleTower_Lobby_Text_1A7B66:: @ 81A7B66
	.string "다음 배틀도\n"
	.string "기대하고 있어요$"

gTVBravoTrainerBattleTowerText1:: @ 81A7B93
	.string "이야-!\n"
	.string "“브라보 트레이너”의 시간이야!\p"
	.string "오늘은 배틀타워에 도전했던\n"
	.string "{STR_VAR_1}의 소개다-!\p"
	.string "{STR_VAR_1}{K_EUNNEUN} {STR_VAR_2}{K_EULREUL}\n"
	.string "사용한 배틀을 해서$"

gTVBravoTrainerBattleTowerText2:: @ 81A7C26
	.string "무려 레벨{STR_VAR_1}의 방에서\n"
	.string "{STR_VAR_2}연승이라는\l"
	.string "기록을 세웠다고!$"

gTVBravoTrainerBattleTowerText3:: @ 81A7C7D
	.string "아깝게도 {STR_VAR_2}명 째의 배틀에서\n"
	.string "{STR_VAR_1}에게 져버리고 말았구나\l"
	.string "으-음! 아쉽게 됐네\p"
	.string "하지만 이렇게나 빨리 {STR_VAR_1}{K_WAGWA}\n"
	.string "배틀했다니 운이 없었다고 생각해\p"
	.string "자 그럼 그 {STR_VAR_1}{K_WAGWA}\n"
	.string "승부한 감상을 물어봤는데$"

gTVBravoTrainerBattleTowerText4:: @ 81A7D4A
	.string "마지막에는 {STR_VAR_1}의\n"
	.string "{STR_VAR_2}{K_EULREUL} 훌륭하게 쓰러뜨려서\l"
	.string "승리했구나\p"
	.string "이야 {STR_VAR_1}에게 이기다니\n"
	.string "정말 굉장하다고 밖에 말할 수 없네\p"
	.string "자 그럼 승리를 거머쥔\n"
	.string "순간의 감상을 물어봤는데$"

gTVBravoTrainerBattleTowerText5:: @ 81A7E0C
	.string "하지만 마지막에 등장한\n"
	.string "{STR_VAR_1}의 {STR_VAR_2}에게\l"
	.string "결국 져버렸구나\p"
	.string "뭐 “{STR_VAR_1}의 {STR_VAR_2}”{K_I}라면\n"
	.string "유명한 콤비니까 말야\p"
	.string "...자 그럼 유명인과\n"
	.string "승부한 감상을 물어봤는데$"

gTVBravoTrainerBattleTowerText6:: @ 81A7F0E
	.string "만족했어!!\p"
	.string "라고 시원하게 대답해주었어\n"
	.string "역시나!\p"
	.string "만족할 수 있는 배틀을 할 수 있다니\n"
	.string "정말 굉장하네!\p"
	.string "그 만족감은 다음 한마디를\n"
	.string "들었을 때 전부 알 수 있었지$"

gTVBravoTrainerBattleTowerText7:: @ 81A8004
	.string "불만스러웠어...\p"
	.string "라며 미묘하게 우울해하면서\n"
	.string "대답해주었어\p"
	.string "...뭐 만족할 수 있는 배틀이란 건\n"
	.string "쉽게 이루어지는 게 아니니까-\p"
	.string "그때의 분함은\n"
	.string "다음 한마디에 잘 나타나 있지$"

gTVBravoTrainerBattleTowerText8:: @ 81A8119
	.string "없음$"

gTVBravoTrainerBattleTowerText9:: @ 81A811E
	.string "없음$"

gTVBravoTrainerBattleTowerText10:: @ 81A8123
	.string "없음$"

gTVBravoTrainerBattleTowerText11:: @ 81A8128
	.string "없음$"

gTVBravoTrainerBattleTowerText12:: @ 81A812D
	.string "그 말은 바로\n"
	.string "“{STR_VAR_1}!”$"

gTVBravoTrainerBattleTowerText13:: @ 81A8133
	.string "“{STR_VAR_1}!”\n"
	.string "으-음 좋은 말이네!!\p"
	.string "{STR_VAR_2}의 기쁨을\n"
	.string "이 말이 잘 나타내주고 있네!\p"
	.string "확실히 {STR_VAR_3}{K_WAGWA}의 배틀은\n"
	.string "그야말로 “{STR_VAR_1}”{K_I}라는\l"
	.string "느낌이였으니까 말이지!$"

gTVBravoTrainerBattleTowerText14:: @ 81A81BC
	.string "“{STR_VAR_1}!”\n"
	.string "과연 그렇구나\p"
	.string "확실히 {STR_VAR_3}{K_WAGWA}의 배틀은\n"
	.string "“{STR_VAR_1}”{K_I}라고 밖에 말할 수\l"
	.string "없는 배틀이었으니까 말이지\p"
	.string "{STR_VAR_2}의 분함이\n"
	.string "잘 전달되고 있어! 크-!$"

gTVBravoTrainerBattleTowerText15:: @ 81A8267
	.string "브라보 {STR_VAR_1}!\n"
	.string "브라보 {STR_VAR_2}!!\p"
	.string "다음에 있을 {STR_VAR_1}의 활약에\n"
	.string "기대하고 있을게!\p"
	.string "자 그럼 다시 다음\n"
	.string "방송에서 만납시다-!$"


SlateportCity_PokemonFanClub_Text_1A82F1:: @ 81A82F1
	.string "와아!\p"
	.string "너 그 {STR_VAR_1}{K_EULREUL} 무척이나\n"
	.string "소중하게 여기고 있는 것 같네!\p"
	.string "{STR_VAR_2}{K_I}라고 하는구나...\p"
	.string "그렇지!\p"
	.string "난 지금 TV 취재로\n"
	.string "포켓몬 앙케트를 하고 있는데\p"
	.string "조금만 질문에\n"
	.string "대답해주면 안될까?$"

SlateportCity_PokemonFanClub_Text_1A83D0:: @ 81A83D0
	.string "고마워!\p"
	.string "그럼 질문할게\n"
	.string "딱 한마디로 대답해줘!$"

SlateportCity_PokemonFanClub_Text_1A8414:: @ 81A8414
	.string "네가 {STR_VAR_1}{K_WAGWA}\n"
	.string "만났을 때\p"
	.string "뭐가 느껴졌어?\n"
	.string "무슨 생각을 했는지 알려줘!$"

SlateportCity_PokemonFanClub_Text_1A8470:: @ 81A8470
	.string "네가 애지중지하는 {STR_VAR_1}!\p"
	.string "만약 뭔가 좋아하는 거에 비유를\n"
	.string "한다면 뭐라고 생각해?$"

SlateportCity_PokemonFanClub_Text_1A84D5:: @ 81A84D5
	.string "네가 애지중지하는 {STR_VAR_1}!\p"
	.string "너는 {STR_VAR_1}의 어떤 점이\n"
	.string "좋다고 생각해?$"

SlateportCity_PokemonFanClub_Text_1A852D:: @ 81A852D
	.string "으-음 역시 그렇구나\p"
	.string "자 다음은 조금\n"
	.string "어려운 질문을 할게!\p"
	.string "그럼...\p"
	.string "너에게 있어서 포켓몬은\n"
	.string "한마디로 뭐라고 생각해?$"

SlateportCity_PokemonFanClub_Text_1A85A6:: @ 81A85A6
	.string "그렇구나-!\p"
	.string "흠흠...\p"
	.string "아!\n"
	.string "협력해줘서 고마워\p"
	.string "여러 가지 이야기를 들어서\n"
	.string "재밌었어\p"
	.string "이 이야기가 혹시 TV에\n"
	.string "나올지도 모르니 기대해 주세요!\p"
	.string "그럼\n"
	.string "바이바이!$"

SlateportCity_PokemonFanClub_Text_1A8667:: @ 81A8667
	.string "그렇구나...\p"
	.string "그럼 다시 포켓몬에 대해\n"
	.string "말하고 싶어지면 들려줘$"

SlateportCity_PokemonFanClub_Text_1A86B5:: @ 81A86B5
	.string "여기 있으면 여러 포켓몬의\n"
	.string "이야기를 들을 수 있으니까 재밌어$"

SlateportCity_PokemonFanClub_Text_1A8704:: @ 81A8704
	.string "너의 그 {STR_VAR_1}{K_WAGWA}\n"
	.string "매우 사이가 좋아보이네\p"
	.string "맞아! 지금 나\n"
	.string "TV 취재를 하고 있어서\p"
	.string "여러 포켓몬의 이야기를\n"
	.string "들으며 돌아다니고 있는데\p"
	.string "괜찮다면 너의 {STR_VAR_1}의\n"
	.string "이야기를 들려주지 않을래?$"

SlateportCity_PokemonFanClub_Text_1A87CA:: @ 81A87CA
	.string "와아!\n"
	.string "고마워!\p"
	.string "그럼 {STR_VAR_1}의 이야기\n"
	.string "뭐든 좋으니까 들려줘!$"

SlateportCity_PokemonFanClub_Text_1A8818:: @ 81A8818
	.string "흠...\n"
	.string "재미있는 이야기네!\p"
	.string "너는 정말로 {STR_VAR_1}{K_WAGWA}\n"
	.string "사이가 좋구나\p"
	.string "으-음 왠지 이 이야기로\n"
	.string "좋은 방송이 만들어질 것 같은 느낌!\p"
	.string "분명 재미있는 방송으로\n"
	.string "만들 테니까 기다려줘\p"
	.string "그럼 고마워\n"
	.string "바이바이!$"

gTVFanClubOpinionsText1:: @ 81A8917
	.string "“우리는!\n"
	.string "포켓몬애호가클럽!”\p"
	.string "네, 힘차게 시작해 보겠습니다!\p"
	.string "이 방송은 여러분의 의견을\n"
	.string "제가 대신해서 외쳐버리겠다!\l"
	.string "라는 굉장한 방송!!\p"
	.string "자 오늘은 포켓몬애호가클럽에\n"
	.string "가서 여러 이야기를 듣고 온\l"
	.string "리포터로부터의 정보입니다!\p"
	.string "자 오늘의\n"
	.string "포켓몬애호가는?\p"
	.string "음...\p"
	.string "{STR_VAR_1}님입니다!\p"
	.string "그럼 본인의 포켓몬인\p"
	.string "{STR_VAR_2} “{STR_VAR_3}”에 대한\n"
	.string "뜨거운 마음을\p"
	.string "대신해서 제가 TV를\n"
	.string "향해 대신 외쳐드리겠습니다!\p"
	.string "우-!!\p"
	.string "렛츠 샤우트!!!$"

gTVFanClubOpinionsText2:: @ 81A8AE5
	.string "자 {STR_VAR_1}님이 처음\n"
	.string "{STR_VAR_2}{K_WAGWA} 만났을 때\l"
	.string "처음으로 느낀 생각은...\l"
	.string "... ...\p"
	.string "“{STR_VAR_3}!!”\p"
	.string "음- 좋은 외침이네요!\p"
	.string "마치 그때의 추억이\n"
	.string "느껴집니다-!$"

gTVFanClubOpinionsText3:: @ 81A8B9D
	.string "We asked {STR_VAR_1}, “If you were to\n"
	.string "liken your {STR_VAR_2} to something,\l"
	.string "it would be...”\p"
	.string "... ... ... ... ... ... ... ...\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Whoah-oh, now that’s an original idea!\p"
	.string "You sure can sense the intensity of\n"
	.string "feeling the TRAINER has for\l"
	.string "{STR_VAR_2}.$"

gTVFanClubOpinionsText4:: @ 81A8C77
	.string "And let’s see...\n"
	.string "What was it about that {STR_VAR_2}\l"
	.string "that so attracted {STR_VAR_1}?\p"
	.string "... ... ... ... ... ... ... ...\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Whoa! Such a spectacular declaration!\p"
	.string "The love of this TRAINER for the\n"
	.string "{STR_VAR_2} comes across loud and clear!$"

gTVFanClubOpinionsText5:: @ 81A8D45
	.string "Hm? Oh, there’s still more.\n"
	.string "Let’s check it out!\p"
	.string "Let me see, now...\p"
	.string "We asked {STR_VAR_1}, “What do POKéMON\n"
	.string "mean to you?”\p"
	.string "... ... ... ... ... ...\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Bravo!\p"
	.string "That’s the best shout I’ve had all day!\p"
	.string "“{STR_VAR_3}!”\p"
	.string "It makes you want to shout it out loud\n"
	.string "again and again!\p"
	.string "Now that we’ve had a great shout, it’s\n"
	.string "time to say good-bye until next time!\p"
	.string "So, let’s all have one last shout!\n"
	.string "All together now...\p"
	.string "“{STR_VAR_3}!”$"

gTVFanClubText1:: @ 81A8EC9
	.string "WE ARE THE POKéMON FAN CLUB!\p"
	.string "We’re on the air!\p"
	.string "Today, we’ll get rolling with the POKéMON\n"
	.string "SURVEY CORNER.\p"
	.string "Out of all the tales woven by POKéMON\n"
	.string "and TRAINERS, what startling new drama\l"
	.string "will grab our attention today?\p"
	.string "Let me see...\p"
	.string "This one!\p"
	.string "We’ll start with this letter!\p"
	.string "It’s a letter from {STR_VAR_1} about a\n"
	.string "beloved {STR_VAR_2}.\p"
	.string "Let’s see how passionately our writer\n"
	.string "can express love for the {STR_VAR_2}!\l"
	.string "Hmhm...$"

gTVFanClubText2:: @ 81A9048
	.string "Whoah!\n"
	.string "What an amazing letter!$"

gTVFanClubText3:: @ 81A9067
	.string "I loved it, so here it is again!$"

gTVFanClubText4:: @ 81A9088
	.string "A great letter bears reading over\n"
	.string "and over!$"

gTVFanClubText5:: @ 81A90B4
	.string "The bit “{STR_VAR_3},” that really\n"
	.string "accentuates emotional impact!\p"
	.string "It’s a great letter that has real\n"
	.string "heartfelt depth!$"

gTVFanClubText6:: @ 81A911F
	.string "Especially that “{STR_VAR_3}” bit!\p"
	.string "I love how “{STR_VAR_3}” is used!$"

gTVFanClubText7:: @ 81A9152
	.string "By the way, and it’s not important,\n"
	.string "but “{STR_VAR_3}” is a great saying.\p"
	.string "I’ve been using “{STR_VAR_3}” a lot\n"
	.string "in conversations lately.$"

gTVFanClubText8:: @ 81A91C6
	.string "If I had to score this letter,\n"
	.string "I’d give it {STR_VAR_3} points.\p"
	.string "Next time, I’ll be expecting an even\n"
	.string "better letter, {STR_VAR_1}!\p"
	.string "A-whoops, will you look at the time?\n"
	.string "Time to say good-bye until next time!$"

SlateportCity_OceanicMuseum_1F_Text_1A927F:: @ 81A927F
	.string "Oh?\n"
	.string "Do you perhaps like POKéMON?\p"
	.string "I’m on assignment with the TV network.\p"
	.string "I’m gathering stories on POKéMON and\n"
	.string "TRAINERS that occurred recently.\p"
	.string "If you don’t mind, could you tell me\n"
	.string "something about yourself?$"

SlateportCity_OceanicMuseum_1F_Text_1A934C:: @ 81A934C
	.string "I’m gathering stories on POKéMON and\n"
	.string "TRAINERS that occurred recently.\p"
	.string "If you don’t mind, could you tell me\n"
	.string "something about yourself?$"

SlateportCity_OceanicMuseum_1F_Text_1A93D1:: @ 81A93D1
	.string "Oh, you will?\n"
	.string "Thank you!\p"
	.string "Then, please, tell me anything of\n"
	.string "interest that you experienced recently\l"
	.string "involving POKéMON.$"

SlateportCity_OceanicMuseum_1F_Text_1A9446:: @ 81A9446
	.string "Oh, I see...\p"
	.string "Well, if you do have an interesting\n"
	.string "story to tell, please let me know.$"

SlateportCity_OceanicMuseum_1F_Text_1A949A:: @ 81A949A
	.string "Oh, what an uplifting story!\p"
	.string "I’ll be sure to get your story told\n"
	.string "on television.\p"
	.string "It should be aired sometime, I think,\n"
	.string "so please look forward to it.$"

SlateportCity_OceanicMuseum_1F_Text_1A952E:: @ 81A952E
	.string "Hmmm...\n"
	.string "I’ve got a good story for a TV program.\p"
	.string "I’d better write it up in a hurry!$"

gTVRecentHappeningsText1:: @ 81A9581
	.string "Hello, it’s time for RECENT HAPPENINGS.\p"
	.string "For POKéMON TRAINERS, every day is\n"
	.string "a storybook tale.\p"
	.string "What we want to do is to introduce you\n"
	.string "to some of these POKéMON tales.\p"
	.string "Today, we bring you the story of the\n"
	.string "TRAINER {STR_VAR_1}.\p"
	.string "What did {STR_VAR_1} experience recently?\n"
	.string "Let’s find out.\p"
	.string "Let’s see...$"

gTVRecentHappeningsText2:: @ 81A9694
	.string "Wasn’t that enlightening?\p"
	.string "The story gives you a clear idea of what\n"
	.string "{STR_VAR_1} has experienced recently.\l"
	.string "It’s as if we were there as witnesses!$"

gTVRecentHappeningsText3:: @ 81A971B
	.string "“{STR_VAR_3}.” That\n"
	.string "accents the tale and gives it depth.$"

gTVRecentHappeningsText4:: @ 81A974B
	.string "“{STR_VAR_3}.”\n"
	.string "That gives the tale a sense of place.\l"
	.string "It lets us envision the tale’s setting.$"

gTVRecentHappeningsText5:: @ 81A979F
	.string "The “{STR_VAR_3}”\n"
	.string "section of the tale is very expressive.$"

gTVRecentHappeningsText6:: @ 81A97D0
	.string "{STR_VAR_1} has recounted a wonderful\n"
	.string "tale involving POKéMON.\p"
	.string "And now {STR_VAR_1}’s tale is indelibly\n"
	.string "etched into your soul, too.\p"
	.string "That’s it for today.\n"
	.string "Please tune in next time.$"


gTVPokemonOutbreakText:: @ 81A986F
	.string "Greetings!\n"
	.string "It’s time for POKéMON NEWS.\p"
	.string "We’ve just received word of a very\n"
	.string "rare occurrence.\p"
	.string "There have been reports of a mass\n"
	.string "outbreak of {STR_VAR_2} in the vicinity\l"
	.string "of {STR_VAR_1}.\p"
	.string "{STR_VAR_2}, as you’re probably aware,\n"
	.string "is known as a POKéMON that’s rare\l"
	.string "and hard to find.\p"
	.string "It sounds like a rare opportunity to\n"
	.string "see the mystifying outbreak of\l"
	.string "{STR_VAR_2} in the wild.\p"
	.string "That’s the news on POKéMON NEWS.$"

gTVNameRaterText1:: @ 81A99D9
	.string "And now, it’s time for...\n"
	.string "THE NAME RATER SHOW.\p"
	.string "I tell your POKéMON’s fortune from\n"
	.string "the nickname you’ve bestowed.\p"
	.string "Advice is what I have to give, and it is\n"
	.string "helpful advice that I offer.\p"
	.string "Today, I shall prophesize the nickname\n"
	.string "{STR_VAR_3} of {STR_VAR_1}’s POKéMON\l"
	.string "{STR_VAR_2}.\p"
	.string "Hmhm...\p"
	.string "Hmm...\n"
	.string "This nickname is...$"

gTVNameRaterText2:: @ 81A9AF0
	.string "A nickname that hints at talent in many\n"
	.string "different ways.\p"
	.string "I urge this TRAINER to take courage\n"
	.string "and take on many challenges.$"

gTVNameRaterText3:: @ 81A9B69
	.string "A nickname that perfectly complements\n"
	.string "{STR_VAR_1}, the TRAINER’s name.\p"
	.string "It suggests that you will forge a fine\n"
	.string "partnership with precise timing.$"

gTVNameRaterText4:: @ 81A9BEF
	.string "A nickname fit for a unique individual\n"
	.string "of a POKéMON!\p"
	.string "If raised properly, this POKéMON’s\n"
	.string "uniqueness will bloom excessively!$"

gTVNameRaterText5:: @ 81A9C6A
	.string "A nickname that will nurture the caring\n"
	.string "and compassionate side of POKéMON.\p"
	.string "If raised properly, this POKéMON will\n"
	.string "come to exhibit real warmth!$"

gTVNameRaterText6:: @ 81A9CF8
	.string "A very fine nickname that hints at\n"
	.string "greatness to come.\p"
	.string "I am intrigued about what the future\n"
	.string "holds in store for this POKéMON.$"

gTVNameRaterText7:: @ 81A9D74
	.string "A good nickname that should make the\n"
	.string "POKéMON hale and hearty!\p"
	.string "That POKéMON should remain fit and\n"
	.string "robust for a long, long time.$"

gTVNameRaterText8:: @ 81A9DF3
	.string "A good nickname that should make the\n"
	.string "POKéMON very active!\p"
	.string "I should think that this POKéMON will be\n"
	.string "a strong performer in battles.$"

gTVNameRaterText9:: @ 81A9E75
	.string "An appealing nickname that should make\n"
	.string "the POKéMON very charming!\p"
	.string "I don’t doubt that this POKéMON will be\n"
	.string "quite the charmer in POKéMON CONTESTS.$"

gTVNameRaterText10:: @ 81A9F06
	.string "The nickname {STR_VAR_1} is rooted by\n"
	.string "the letter “{STR_VAR_3}.”\p"
	.string "That letter is supported by the first\n"
	.string "letter “{STR_VAR_2},” which gives it a solid sense\l"
	.string "of presence as a nickname.$"

gTVNameRaterText11:: @ 81A9F9F
	.string "The nickname {STR_VAR_1} is very\n"
	.string "shapely in a pleasing manner.\p"
	.string "The presence of the letters “{STR_VAR_2}” and\n"
	.string "“{STR_VAR_3}” - now that is remarkably good!$"

gTVNameRaterText12:: @ 81AA01E
	.string "The nickname {STR_VAR_1} - it has a\n"
	.string "sublime, flowing feel to it.\p"
	.string "The flow from the initial letter “{STR_VAR_2}” to\n"
	.string "“{STR_VAR_3}” is especially wonderful.$"

gTVNameRaterText13:: @ 81AA09D
	.string "Let’s examine other examples of fine\n"
	.string "nicknames, shall we?$"

gTVNameRaterText14:: @ 81AA0D7
	.string "Try this example. Take a part of the\n"
	.string "TRAINER name of {STR_VAR_1}, and end\l"
	.string "up with the fine nickname {STR_VAR_2}{STR_VAR_3}.$"

gTVNameRaterText15:: @ 81AA138
	.string "The nickname {STR_VAR_2}{STR_VAR_3} would also work\n"
	.string "quite well.$"

gTVNameRaterText16:: @ 81AA166
	.string "The POKéMON’s species name of\n"
	.string "{STR_VAR_2} could be used as the basis\l"
	.string "for making the nickname {STR_VAR_1}{STR_VAR_3}.$"

gTVNameRaterText17:: @ 81AA1C0
	.string "{STR_VAR_1}{STR_VAR_3} would also be an effective\n"
	.string "nickname.$"

gTVNameRaterText18:: @ 81AA1EA
	.string "What should always be avoided is using\n"
	.string "another POKéMON species name.\p"
	.string "For instance, avoid taking the name of\n"
	.string "{STR_VAR_2} to make the nickname {STR_VAR_1}{STR_VAR_3}.\l"
	.string "That is unacceptable.$"

gTVNameRaterText19:: @ 81AA28A
	.string "But I must say, {STR_VAR_2} has a most\n"
	.string "remarkable flair for devising nicknames.\p"
	.string "It is my hope that the TRAINER will\n"
	.string "continue to treat {STR_VAR_1} with love.\p"
	.string "That’s it for today’s show.\n"
	.string "May we meet again.$"


gTVFishingGuruAdviceText1:: @ 81AA344
	.string "{STR_VAR_2} ANGLER\p"
	.string "ANNOUNCER: Hello! Today, we’ll get tips\n"
	.string "on fishing for {STR_VAR_2}.\p"
	.string "GURU, what advice can you give for\n"
	.string "catching {STR_VAR_2}?\p"
	.string "GURU: Hm? Catching {STR_VAR_2}?\n"
	.string "Well, let me tell you, be patient and wait.\l"
	.string "That’s the bottom line.\p"
	.string "Do you see {STR_VAR_1} over there?\n"
	.string "That TRAINER makes a good example.\p"
	.string "That TRAINER’s already had {STR_VAR_3}\n"
	.string "POKéMON get away.\p"
	.string "But there {STR_VAR_1} waits. No giving up.\n"
	.string "That’s the law for catching {STR_VAR_2}.\p"
	.string "ANNOUNCER: I see...\p"
	.string "Oh! {STR_VAR_1} has finally landed an\n"
	.string "elusive {STR_VAR_2}!\p"
	.string "The TRAINER appears close to tears\n"
	.string "out of sheer joy!\p"
	.string "Seeing that elated look, I’m getting\n"
	.string "the itch to go fishing, too!\p"
	.string "Viewers, why not take this as a cue to\n"
	.string "try some {STR_VAR_2} fishing?\p"
	.string "Until our next broadcast, farewell and\n"
	.string "good fishing to you all!$"


gTVFishingGuruAdviceText2:: @ 81AA5F3
	.string "{STR_VAR_2} ANGLER\p"
	.string "ANNOUNCER: Hello! Today, we’ll get tips\n"
	.string "on fishing for {STR_VAR_2}.\p"
	.string "GURU, what advice can you give for\n"
	.string "catching {STR_VAR_2}?\p"
	.string "GURU: Hm? Catching {STR_VAR_2}?\n"
	.string "Well, let me tell you, use your fishing\l"
	.string "ROD with vigor!\p"
	.string "Do you see {STR_VAR_1} over there?\n"
	.string "See how the ROD is handled?\p"
	.string "That TRAINER’s already caught\n"
	.string "{STR_VAR_3} in a row.\p"
	.string "ANNOUNCER: It’s incredible!\n"
	.string "It looks like a storm...\p"
	.string "Seeing technique of that caliber, I’m\n"
	.string "getting the itch to go fishing, too.\p"
	.string "Viewers, why not take this as a cue to\n"
	.string "try some {STR_VAR_2} fishing?\p"
	.string "Until our next broadcast, farewell and\n"
	.string "good fishing to you all!$"


gTVPokemonTodayFailedCaptureText1:: @ 81AA814
	.string "Hello!\p"
	.string "It’s time for POKéMON TODAY!\p"
	.string "BIG SIS: Hi! Is everyone peachy and\n"
	.string "perky today?\p"
	.string "Today, we’re going to look at {STR_VAR_1}’s\n"
	.string "POKéMON {STR_VAR_2}!\p"
	.string "BIG BRO: Yeah! That’s what we’re going\n"
	.string "to do!$"

gTVPokemonTodayFailedCaptureText2:: @ 81AA8C6
	.string "Oh!\n"
	.string "Speaking of {STR_VAR_1}...\p"
	.string "BIG SIS, I saw the TRAINER with my very\n"
	.string "own eyes!\p"
	.string "BIG SIS: Oh, what did you see?\p"
	.string "BIG BRO: Well, I had to go on a trip to\n"
	.string "{STR_VAR_2}.\p"
	.string "That’s when I happened to come across\n"
	.string "{STR_VAR_1}, who was trying to catch the\l"
	.string "POKéMON {STR_VAR_3}, but...$"

gTVPokemonTodayFailedCaptureText3:: @ 81AA9B2
	.string "The POKéMON managed to get away!\p"
	.string "It ended up wasting this many\n"
	.string "POKé BALLS: {STR_VAR_2}!\p"
	.string "You should have seen the expression\n"
	.string "of frustration on {STR_VAR_1}’s face when\l"
	.string "the POKéMON took off!$"

gTVPokemonTodayFailedCaptureText4:: @ 81AAA5C
	.string "But {STR_VAR_1} goofed and made the\n"
	.string "POKéMON faint!\p"
	.string "It ended up wasting this many\n"
	.string "POKé BALLS: {STR_VAR_2}!\p"
	.string "You should have seen the expression\n"
	.string "of stunned dismay on {STR_VAR_1}’s face\l"
	.string "when the POKéMON fainted!$"

gTVPokemonTodayFailedCaptureText5:: @ 81AAB11
	.string "BIG SIS: Hey, there!\n"
	.string "That’s not nice!\p"
	.string "You shouldn’t be laughing at other\n"
	.string "people’s misfortune!\p"
	.string "Oh, poor {STR_VAR_1}.\n"
	.string "What a shame!\p"
	.string "BIG BRO: That’s true!\n"
	.string "Sorry for laughing.$"

gTVPokemonTodayFailedCaptureText6:: @ 81AABB4
	.string "BIG SIS: Bufufu...\p"
	.string "BIG BRO: Hey!\n"
	.string "You just laughed, too!\p"
	.string "BIG SIS: Huh?!\p"
	.string "I didn’t laugh!\n"
	.string "Honestly, I didn’t!\p"
	.string "Oh, poor {STR_VAR_1}.\n"
	.string "What a shame!\p"
	.string "BIG BRO: ...$"

gTVPokemonTodayFailedCaptureText7:: @ 81AAC47
	.string "BIG SIS: That’s enough silliness!\n"
	.string "Let’s look at today’s POKéMON...\p"
	.string "Huh?\n"
	.string "We’re out of time already?\p"
	.string "Aww!\n"
	.string "We couldn’t profile a POKéMON today!\p"
	.string "BIG BRO: See you again next time!\p"
	.string "BIG SIS: Hey, don’t end the show\n"
	.string "without me!$"

gTVPokemonTodayText1:: @ 81AAD23
	.string "Hello!\p"
	.string "It’s time for POKéMON TODAY!\p"
	.string "BIG SIS: Hi! Is everyone peachy and\n"
	.string "perky today?\p"
	.string "Today, we’re going to look at {STR_VAR_1}’s\n"
	.string "POKéMON {STR_VAR_2}!\p"
	.string "BIG BRO: Yeah! That’s what we’re going\n"
	.string "to do!$"

gTVPokemonTodayText2:: @ 81AADD5
	.string "BIG SIS: {STR_VAR_1} gave the nickname\n"
	.string "{STR_VAR_3} to the {STR_VAR_2}!\p"
	.string "It sounds like {STR_VAR_3} is getting\n"
	.string "good, loving care!$"

gTVPokemonTodayText3:: @ 81AAE31
	.string "BIG BRO: The TRAINER had to throw this\n"
	.string "many BALLS to catch it: {STR_VAR_3}!\p"
	.string "It finally took a single {STR_VAR_2}\n"
	.string "to catch it!$"

gTVPokemonTodayText4:: @ 81AAE9D
	.string "BIG SIS: If it was that easy to catch,\n"
	.string "it must have been destiny that brought\l"
	.string "{STR_VAR_1} and the {STR_VAR_2} together!$"

gTVPokemonTodayText5:: @ 81AAF03
	.string "BIG SIS: Wow! That’s so neat!\p"
	.string "But you know what they say, a POKéMON\n"
	.string "that takes a lot of effort to catch\l"
	.string "earns the love of its TRAINER!$"

gTVPokemonTodayText6:: @ 81AAF8A
	.string "BIG SIS: {STR_VAR_1}’s {STR_VAR_2} is a\n"
	.string "memorable POKéMON because it took an\l"
	.string "invaluable MASTER BALL to catch!\p"
	.string "BIG BRO: Wow! That’s mega-awesome!\p"
	.string "BIG SIS: {STR_VAR_1} must have really\n"
	.string "wanted that {STR_VAR_2}, for sure!$"

gTVPokemonTodayText7:: @ 81AB040
	.string "BIG BRO: Then to give the nickname\n"
	.string "{STR_VAR_3} to that {STR_VAR_2}...\p"
	.string "You really get a good idea about\n"
	.string "{STR_VAR_1}’s TRAINER sense.\p"
	.string "BIG SIS: I second that notion!$"

gTVPokemonTodayText8:: @ 81AB0C8
	.string "If it were me, I’d give that\n"
	.string "nickname to something like {STR_VAR_3}!\p"
	.string "BIG BRO: Whoa! That could be the start\n"
	.string "of something new!$"

gTVPokemonTodayText9:: @ 81AB13D
	.string "{STR_VAR_2} the {STR_VAR_1}?\n"
	.string "Doesn’t that sound perfect?\p"
	.string "The letters and everything - they sound\n"
	.string "just right for the POKéMON {STR_VAR_1}!\p"
	.string "BIG BRO: Yeah, true, that!$"

gTVPokemonTodayText10:: @ 81AB1C6
	.string "As far as I know, no TRAINER has ever\n"
	.string "given the nickname {STR_VAR_2} to their\l"
	.string "{STR_VAR_1}!\p"
	.string "BIG BRO: That just goes to show what\n"
	.string "great taste the TRAINER has in picking\l"
	.string "nicknames!$"

gTVPokemonTodayText11:: @ 81AB266
	.string "The next time I catch a POKéMON,\n"
	.string "I should give it the name {STR_VAR_2}.\p"
	.string "BIG BRO: Huh? Me, too!\n"
	.string "I’ll use the nickname {STR_VAR_2}, too!$"

gTVPokemonTodayText12:: @ 81AB2DB
	.string "BIG SIS: Oh, no!\n"
	.string "Look at the time!\p"
	.string "Well, gang, this is it for today.\n"
	.string "See you again next time!\p"
	.string "BIG BRO: Remember, it could be your\n"
	.string "POKéMON in the spotlight next time!$"


gTVSmartShopperText1:: @ 81AB381
	.string "Hello!\p"
	.string "It’s time for TODAY’S SMART SHOPPER.\p"
	.string "INTERVIEWER: How are you, viewers?\p"
	.if REVISION >= 1
	.string "Today we’re visiting a shop\n"
	.else
	.string "Today we’re visiting the POKéMON MART\n"
	.endif
	.string "in {STR_VAR_2}.\p"
	.string "Let’s check on what the hot sellers\n"
	.string "have been recently.$"

gTVSmartShopperText2:: @ 81AB435
	.string "Let’s interview the clerk to get the\n"
	.string "lowdown.\p"
	.string "Hi, how’s your business?\p"
	.string "CLERK: Oh, we’re doing excellent.\p"
	.string "Recently, {STR_VAR_2} has been selling\n"
	.string "especially strongly.\p"
	.string "Why, just the other day a TRAINER\n"
	.string "named {STR_VAR_1} bought {STR_VAR_3}.$"

gTVSmartShopperText3:: @ 81AB507
	.string "INTERVIEWER: The TRAINER bought\n"
	.string "{STR_VAR_3} {STR_VAR_2}S? That’s a haul!\p"
	.string "If I may say so, {STR_VAR_1} must have\n"
	.string "been stocking up for a long journey\l"
	.string "to far-off places.\p"
	.string "For traveling, {STR_VAR_2}S are so\n"
	.string "important!$"

gTVSmartShopperText4:: @ 81AB5B8
	.string "INTERVIEWER: Speaking of the item\n"
	.string "{STR_VAR_2}, I just bought {STR_VAR_3} of\l"
	.string "them recently.\p"
	.string "After all, {STR_VAR_2}’s a great item!$"

gTVSmartShopperText5:: @ 81AB61F
	.string "INTERVIEWER: {STR_VAR_2}?!\n"
	.string "But {STR_VAR_3} of them?!\p"
	.string "I didn’t think there would be anyone\n"
	.string "buying that many.\p"
	.string "My goodness, I can only afford one or\n"
	.string "two at a time...$"

gTVSmartShopperText6:: @ 81AB6B0
	.string "INTERVIEWER: One time, I bought\n"
	.string "a whole lot of the item {STR_VAR_2}.\p"
	.string "But it turned out to be too many.\n"
	.string "I ended up regretting it...\p"
	.string "Since then, I only buy strictly what\n"
	.string "I absolutely need...\p"
	.string "Oops!\p"
	.string "There’s no point talking about me!$"

gTVSmartShopperText7:: @ 81AB78D
	.string "CLERK: {STR_VAR_1} also bought the item\n"
	.string "{STR_VAR_2} in bulk, taking {STR_VAR_3}.\p"
	.string "INTERVIEWER: Oh, that’s smart.\n"
	.string "{STR_VAR_2}’s a very good item, too.$"

gTVSmartShopperText8:: @ 81AB7FE
	.string "CLERK: And, the TRAINER also bought\n"
	.string "{STR_VAR_3} of the item {STR_VAR_2}.$"

gTVSmartShopperText9:: @ 81AB835
	.string "CLERK: Plus, it was during a big sale.\n"
	.string "That’s smart shopping.$"

gTVSmartShopperText10:: @ 81AB873
	.string "INTERVIEWER: Hmm... {STR_VAR_1} sounds like\n"
	.string "quite the shrewd bargain hunter!\p"
	.string "In total, {STR_VAR_1}’s purchases came to...\p"
	.string "¥{STR_VAR_2}?!\n"
	.string "What an amazing sum!\p"
	.string "Oops! We’re out of time!\n"
	.string "See you on our next broadcast!$"

gTVSmartShopperText11:: @ 81AB92E
	.string "CLERK: {STR_VAR_1} is a VIP customer,\n"
	.string "no doubt about it.$"

gTVSmartShopperText12:: @ 81AB95E
	.string "Let’s interview the clerk to get the\n"
	.string "lowdown.\p"
	.string "Hi, how’s your business?\p"
	.string "CLERK: Oh, we’re doing unbelievable\n"
	.string "business. It’s almost overwhelming.\p"
	.string "Recently, a TRAINER named {STR_VAR_1}\n"
	.string "bought the item {STR_VAR_2}in bulk.\p"
	.string "The TRAINER almost cleared out our\n"
	.string "entire stock of {STR_VAR_2}S.\p"
	.string "I never dreamt that any customer\n"
	.string "would ever need so many {STR_VAR_2}S.\l"
	.string "It’s just unheard of!\p"
	.string "INTERVIEWER: So that would be like 100\n"
	.string "or 200 sold?\p"
	.string "CLERK: Oh, no, much more than that!\p"
	.string "INTERVIEWER: Oh, my goodness!\n"
	.string "{STR_VAR_1} must be a special shopper!\p"
	.string "CLERK: {STR_VAR_1} is a VIP customer,\n"
	.string "no doubt about it.$"

gTVSmartShopperText13:: @ 81ABB75
	.string "INTERVIEWER: Hmm...\n"
	.string "That is amazing.\p"
	.string "But why would the TRAINER need to buy\n"
	.string "so many?\p"
	.string "... ...\p"
	.string "The mystery deepens, but this is all\n"
	.string "the time we have today.\l"
	.string "See you on our next broadcast!\p"
	.string "Still, {STR_VAR_1} is certainly an enigma...$"


gTVWorldOfMastersText1:: @ 81ABC51
	.string "THE WORLD OF MASTERS\p"
	.string "Hello, viewers.\p"
	.string "Perhaps you are aware of a TRAINER\n"
	.string "named {STR_VAR_1}.\p"
	.string "{STR_VAR_1} is famous as a master at\n"
	.string "catching POKéMON.\p"
	.string "{STR_VAR_1}’s quest for POKéMON depends\n"
	.string "entirely on a careful search on foot.\p"
	.string "On one memorable day, the TRAINER\n"
	.string "walked some {STR_VAR_2} steps.\p"
	.string "The total number of POKéMON caught\n"
	.string "that day reached an impressive {STR_VAR_3}!$"

gTVWorldOfMastersText2:: @ 81ABD94
	.string "That remarkable feat must have been\n"
	.string "possible because of the trust between\l"
	.string "the TRAINER and {STR_VAR_1}.$"

gTVWorldOfMastersText3:: @ 81ABDF2
	.string "The master caught the day’s last\n"
	.string "{STR_VAR_3} near {STR_VAR_2}.\p"
	.string "That POKéMON apparently enjoys\n"
	.string "a special status as a record holder.\p"
	.string "Skilled TRAINERS should be encouraged\n"
	.string "to challenge this fine record.\p"
	.string "That’s all for today.\n"
	.string "Please tune in next time.$"

	.include "data/text/gabby_and_ty.inc"
	.include "data/text/pokemon_news.inc"
