gEasyChatGroupName_Pokemon:: @ 842C7DB
	.string "포켓몬$"

gEasyChatGroupName_Trainer:: @ 842C7E3
	.string "트레이너$"

gEasyChatGroupName_Status:: @ 842C7EB
	.string "스테이터스$"

gEasyChatGroupName_Battle:: @ 842C7F2
	.string "배틀$"

gEasyChatGroupName_Greetings:: @ 842C7F9
	.string "인사$"

gEasyChatGroupName_People:: @ 842C803
	.string "사람$"

gEasyChatGroupName_Voices:: @ 842C80A
	.string "목소리$"

gEasyChatGroupName_Speech:: @ 842C811
	.string "언어$"

gEasyChatGroupName_Endings:: @ 842C818
	.string "끝맺음$"

gEasyChatGroupName_Feelings:: @ 842C820
	.string "기분$"

gEasyChatGroupName_Conditions:: @ 842C829
	.string "컨디션$"

gEasyChatGroupName_Actions:: @ 842C834
	.string "행동$"

gEasyChatGroupName_Lifestyle:: @ 842C83C
	.string "생활$"

gEasyChatGroupName_Hobbies:: @ 842C846
	.string "취미$"

gEasyChatGroupName_Time:: @ 842C84E
	.string "시간$"

gEasyChatGroupName_Misc:: @ 842C853
	.string "이것저것$"

gEasyChatGroupName_Adjectives:: @ 842C859
	.string "반복$"

gEasyChatGroupName_Events:: @ 842C864
	.string "이벤트$"

gEasyChatGroupName_Move1:: @ 842C86B
	.string "기술1$"

gEasyChatGroupName_Move2:: @ 842C872
	.string "기술2$"

gEasyChatGroupName_TrendySaying:: @ 842C879
	.string "유행$"

gEasyChatGroupName_Pokemon2:: @ 842C887
	.string "포켓몬2$"
