AbandonedShip_Corridors_1F_Text_19843D:: @ 819843D
	.string "배 안에서도\n"
	.string "튜브를 가지고 있는 게 이상해?$"
	// ふねの なかでもｎ
	//うきわ もっていたら おかしい?

AbandonedShip_Corridors_1F_Text_198479:: @ 8198479
	.string "우와아 강해!$"
	// うわぁ つよ-い!

AbandonedShip_Corridors_1F_Text_198493:: @ 8198493
	.string "튜브를 끼고 있으면\n"
	.string "몬스터볼을 던지기 어려워$"
	// うきわを もったままだとｎ
	// モンスタ-ボ-ル なげにくいよ

AbandonedShip_Corridors_1F_Text_1984D8:: @ 81984D8
	.string "여긴 참 재미있구나!\n"
	.string "여기에 있는 것만으로도 두근거려!$"
	// ここって おもしろいね!ｎ
	// いるだけで ワクワク してくるよ!
