AbandonedShip_Corridors_B1F_Text_19856F:: @ 819856F
	.string "선원은 배에 탈 때\n"
	.string "반드시 포켓몬을 데리고 간다!\l"
	.string "잠깐 승부해줘야겠어!$"
	// ふなのりは ふねに のるときｎ
	// かならず ポケモンを もっている!ｌ
	// ちょいと しょうぶ してくれ!

AbandonedShip_Corridors_B1F_Text_1985C5:: @ 81985C5
	.string "이거 큰일인걸$"
	// こりゃ まいった

AbandonedShip_Corridors_B1F_Text_1985D7:: @ 81985D7
	.string "뱃바닥이 물속으로\n"
	.string "가라앉아있어\p"
	.string "포켓몬이 물속에 잠수하는 기술을\n"
	.string "쓸 수 있다면\l"
	.string "일이 쉬워질 텐데...$"
	// ふなぞこが みずの なかにｎ
	// しずんで いるんだよｐ
	// ポケモンが みずに もぐれる わざをｎ
	// つかえたら さきに すすめるんだがな……

AbandonedShip_Corridors_B1F_Text_19864A:: @ 819864A
	.string "와-!\n"
	.string "배다-!$"
	// わ-い!ｎ
	//ふね だぞ-!

AbandonedShip_Corridors_B1F_Text_19865C:: @ 819865C
	.string "열쇠가 걸려 있다\p"
	.string "문에는 “창고”라고 쓰여 있다$"
	// カギが かかっているｐ
	// とびらには そうこ と かかれている

AbandonedShip_Corridors_B1F_Text_198692:: @ 8198692
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "창고열쇠를 사용했다!\p"
	.string "넣은 열쇠는 뺄 수 없게 되었지만\n"
	.string "문은 열렸다!$"
	// §あはｎ
	// そうこのカギを つかった!ｐ
	// さしこんだ カギは ぬけなくなったがｎ
	// とびらは ひらいた!

AbandonedShip_Corridors_B1F_Text_1986EC:: @ 81986EC
