AbandonedShip_Rooms2_1F_Text_1987C1:: @ 81987C1
	.string "중문: 보물을 찾고 있었더니\n"
	.string "트레이너를 발견!$"
	// フミ『おたから さがしていたらｎ
	// トレ-ナ- はっけん!

AbandonedShip_Rooms2_1F_Text_1987FE:: @ 81987FE
	.string "중문: 우리 둘의 힘으로도\n"
	.string "이길 수 없는 건가...$"
	// フミ『ぼくたち ふたりの ちからでもｎ
	// かてなかったのか……

AbandonedShip_Rooms2_1F_Text_198835:: @ 8198835
	.string "중문: 보물을 찾을 수 없네...\n"
	.string "벌써 누가 가져간 거 아닌가?$"
	// フミ『おたから みつからないんだよね……ｎ
	// もう だれかが もっていったのかな?

AbandonedShip_Rooms2_1F_Text_19887F:: @ 819887F
	.string "중문: 포켓몬 2마리가 없구나\n"
	.string "그럼 우리를 이길 수 없어!$"
	// フミ『ポケモン 2ひき いないんだねｎ
	// それだと ぼくたちには かてないよ!

AbandonedShip_Rooms2_1F_Text_1988CC:: @ 81988CC
	.string "소영: 어머? 보물을 찾고 있었는데\n"
	.string "트레이너를 발견했어요!$"
	// アヤ『あら? おたから さがしていたのにｎ
	// トレ-ナ- はっけん しちゃった!

AbandonedShip_Rooms2_1F_Text_198916:: @ 8198916
	.string "소영: 강하군요!$"
	// アヤ『つよいんだ!

AbandonedShip_Rooms2_1F_Text_198934:: @ 8198934
	.string "소영: 이런 낡은 장소에 있는\n"
	.string "보물이란 무엇일까?\l"
	.string "뭐 어쨌든 뭘 살지를 정하고 있어$"
	// アヤ『おたから どこかな?ｎ
	// みつかったら なに かおうか きめてるのよ!

AbandonedShip_Rooms2_1F_Text_19899A:: @ 819899A
	.string "소영: 어머?\n"
	.string "포켓몬 2마리가 아니군요?\l"
	.string "그럼 승부는 다음에 해야겠네요!$"
	// アヤ『あら ポケモン 2ひき いないの?ｎ
	// じゃあ しょうぶは おあずけね!

AbandonedShip_Rooms2_1F_Text_1989DF:: @ 81989DF
	.string "중문: 계속 보물을 찾고 있다 보니\n"
	.string "포켓몬도 강해졌다고-!\p"
	.string "살짝 상대해 줘$"
	// フミ『ずっと おたから さがしていてｎ
	// ポケモンも つよく なったんだよね-!ｌ
	// ちょっと あいて してみてよ

AbandonedShip_Rooms2_1F_Text_198A53:: @ 8198A53
	.string "중문: 변함없이 강하군!$"
	// フミ『あいかわらず つよいな!

AbandonedShip_Rooms2_1F_Text_198A70:: @ 8198A70
	.string "중문: 보물도 못 찾겠고\n"
	.string "포켓몬 승부도 져버렸으니\l"
	.string "이제 집에 돌아가고 싶다\p"
	.string "하지만 그런 말을 하면\n"
	.string "그녀가 화를 내니까...$"
	// フミ『おたからは みつからないしｎ
	// ポケモンは まけるし いえに かえりたいよｐ
	// でも そんなこと いうとｎ
	// かのじょ おこりだすからな……

AbandonedShip_Rooms2_1F_Text_198AEE:: @ 8198AEE
	.string "중문: 포켓몬 2마리가 없구나\n"
	.string "그럼 우리를 이길 수 없어!$"
	// フミ『ポケモン 2ひき いないんだねｎ
	// それだと ぼくたちには かてないよ!

AbandonedShip_Rooms2_1F_Text_198B3B:: @ 8198B3B
	.string "소영: 어머? 또 만났군요!\n"
	.string "우리처럼 포기하지 않고\l"
	.string "보물을 찾고 있나보죠!\p"
	.string "승부해서 진 쪽이\n"
	.string "먼저 포기하는 걸로 하지 않을래요?$"
	// アヤ『あら? また であったわね!ｎ
	// あたしたちと いっしょで あきらめずにｌ
	// おたから さがしているのね!ｐ
	// しょうぶして まけた ほうはｎ
	// あきらめることに しない?

AbandonedShip_Rooms2_1F_Text_198BCF:: @ 8198BCF
	.string "소영: 또 져버렸어...$"
	// アヤ『また まけちゃった……

AbandonedShip_Rooms2_1F_Text_198BEA:: @ 8198BEA
	.string "소영: 더욱 포켓몬을 키워서\p"
	.string "보물을 찾아낼 때까지\n"
	.string "돌아가지 않을 거예요!$"
	// アヤ『もっと ポケモン そだててｎ
	// おたから みつけるまで かえらないわよ!

AbandonedShip_Rooms2_1F_Text_198C40:: @ 8198C40
	.string "소영: 어머?\n"
	.string "포켓몬이 2마리가 아니군요?\l"
	.string "그럼 승부는 다음에 해야겠네요!$"
	// アヤ『あら ポケモン 2ひき いないの?ｎ
	// じゃあ しょうぶは おあずけね!
