AquaHideout_B1F_Text_196E6F:: @ 8196E6F
	.string "아지트의 비밀을 알고 싶으면\n"
	.string "이 몸을 쓰려뜨려 보시지!$"

AquaHideout_B1F_Text_196EB6:: @ 8196EB6
	.string "절대 이길 수 없을 것 같습니다...!$"

AquaHideout_B1F_Text_196ECC:: @ 8196ECC
	.string "아지트의 비밀?\p"
	.string "그건 말이지... 가장 안쪽에\n"
	.string "잠수정이 있다는 거야!\p"
	.string "하지만 지금쯤...\n"
	.string "이히히...!$"

AquaHideout_B1F_Text_196F39:: @ 8196F39
	.string "연료 보급 OK!\n"
	.string "과자 보급도 OK!\p"
	.string "남은 건\n"
	.string "방해꾼을 처치하는 것뿐이군!$"

AquaHideout_B1F_Text_196F9B:: @ 8196F9B
	.string "제대로 당했다-앗!$"

AquaHideout_B1F_Text_196FB5:: @ 8196FB5
	.string "흥! 이제 됐어!\p"
	.string "널 방해하는 게\n"
	.string "내 임무였으니까$"

AquaHideout_B1F_Text_196FFD:: @ 8196FFD
	.string "하-앙 아지트를 지키고 있는 것도\n"
	.string "너무 지루하니까 상대해줄게용-$"

AquaHideout_B1F_Text_197040:: @ 8197040
	.string "하-앙 져버렸어용-$"

AquaHideout_B1F_Text_197056:: @ 8197056
	.string "너무 종종걸음으로 돌아다니면\n"
	.string "다른 {EVIL_TEAM}단에게 당할지도 몰라용-$"
