AquaHideout_B2F_Text_197093:: @ 8197093
	.string "하하하...\p"
	.string "이미 여기까지 와버렸나\n"
	.string "널 과소평가 한 거 같군!\p"
	.string "하지만!\p"
	.string "난 여태까지의 조무래기들보다\n"
	.string "훨씬 강하다고?\p"
	.string "난 시간을 끌기 위해서가 아니라...\p"
	.string "널 쳐부수기 위해 있는 거다!$"

AquaHideout_B2F_Text_197145:: @ 8197145
	.string "하하하...\n"
	.string "져버렸나...$"

AquaHideout_B2F_Text_197162:: @ 8197162
	.string "하하하!\p"
	.string "나하고 승부하는 사이에\n"
	.string "지금쯤 리더는\l"
	.string "목적을 달성하셨을 거다!$"

AquaHideout_B2F_Text_1971AE:: @ 81971AE
	.string "하하하!\p"
	.string "리더는 이미 바닷속 깊은 곳의\n"
	.string "동굴에 도착하셨을 거다!\p"
	.string "리더를 쫓으려면\n"
	.string "해안시티 너머의 그 넓은 바다를\l"
	.string "돌아다녀야 할 걸?\p"
	.string "리더를 찾을 수 있을까?\n"
	.string "하하하!$"

AquaHideout_B2F_Text_197270:: @ 8197270
	.string "왓핫핫 기다리다\n"
	.string "목이 빠지는 줄 알았다!\l"
	.string "나랑도 승부해 주실까?!$"

AquaHideout_B2F_Text_1972AC:: @ 81972AC
	.string "기다리다 너무 지쳐서\n"
	.string "져버렸다...$"

AquaHideout_B2F_Text_1972D2:: @ 81972D2
	.string "리더...\n"
	.string "이 정도면 된 건가요-?!$"

AquaHideout_B2F_Text_1972EF:: @ 81972EF
	.string "우리 아지트의 명물인 워프패널!\p"
	.string "지금 자신이 어디에 있는지\n"
	.string "전혀 짐작도 안 가겠죠?!\p"
	.string "그렇게 상대를 지치게 해서\n"
	.string "쓰러뜨리는 게 작전인 거예요!$"

AquaHideout_B2F_Text_197390:: @ 8197390
	.string "뭐얏!\n"
	.string "하나도 안 지쳐 있잖아?!$"

AquaHideout_B2F_Text_1973C0:: @ 81973C0
	.string "그러고 보니... 마스터볼을\n"
	.string "어디에 뒀었는지 까먹었어\p"
	.string "그걸 지키고 있지 않으면\n"
	.string "리더에게 혼이 난다구...$"
