BattleTower_Lobby_Text_199F2C:: @ 8199F2C
	.string "어서 오세요! 배틀타워입니다\p"
	.string "여기는 배틀룸의\n"
	.string "안내를 하고 있습니다$"

BattleTower_Lobby_Text_199F79:: @ 8199F79
	.string "배틀룸에\n"
	.string "도전하시겠습니까?$"

BattleTower_Lobby_Text_199FA9:: @ 8199FA9
	.string "그럼 다음에 또 이용해 주세요\n"
	.string "기다리고 있겠습니다!$"

BattleTower_Lobby_Text_199FDA:: @ 8199FDA
	.string "배틀룸으로 안내하기 전에\n"
	.string "리포트를 작성하시겠습니까?$"

BattleTower_Lobby_Text_19A024:: @ 819A024
	.string "레벨50 과 레벨100\n"
	.string "어느 쪽 배틀룸으로 하겠습니까?$"

BattleTower_Lobby_Text_19A07B:: @ 819A07B
	.string "그럼 참가할 포켓몬을\n"
	.string "선택해 주십시오$"

BattleTower_Lobby_Text_19A0A8:: @ 819A0A8
	.string "그럼 배틀룸으로\n"
	.string "안내하겠습니다!$"

BattleTower_Lobby_Text_19A0D1:: @ 819A0D1
	.string "배틀타워는 포켓몬 대전을\n"
	.string "하기 위한 시설입니다\p"
	.string "타워에는 배틀룸이라는\n"
	.string "대전을 위한 방이\l"
	.string "많이 준비되어 있습니다\p"
	.string "각각의 배틀룸에는\n"
	.string "7명의 트레이너가\l"
	.string "당신의 도전을 기다리고 있습니다\p"
	.string "그 7명을 멋지게 쓰러뜨리시면\n"
	.string "굉장한 상품을 드립니다\p"
	.string "그리고 도중에 도전을\n"
	.string "중단하고 싶을 경우에는\p"
	.string "리포트를 작성하지 않으면\n"
	.string "계속해서 도전을 할 수 없으므로\l"
	.string "부디 주의해 주십시오!$"

BattleTower_Lobby_Text_19A249:: @ 819A249
	.string "손님!\p"
	.string "참가할 수 있는 포켓몬이\n"
	.string "3마리는 필요합니다!\p"
	.string "참가하려면 종류가 다른\n"
	.string "레벨50의 포켓몬을\l"
	.string "3마리 준비해서\p"
	.string "지니게 할 도구도 모두\n"
	.string "다른 도구로 해주세요\p"
	.string "그리고 알{STR_VAR_1}{K_EUNNEUN}\l"
	.string "참가시킬 수 없습니다!\p"
	.string "준비되면\n"
	.string "다시 방문해 주십시오$"

BattleTower_Lobby_Text_19A32D:: @ 819A32D
	.string "손님!\p"
	.string "참가할 수 있는 포켓몬이\n"
	.string "3마리는 필요합니다!\p"
	.string "참가하려면 종류가 다른\n"
	.string "포켓몬을 3마리 준비해서\p"
	.string "지니게 할 도구도 모두\n"
	.string "다른 도구로 해주세요\p"
	.string "그리고 알{STR_VAR_1}{K_EUNNEUN}\l"
	.string "참가시킬 수 없습니다!\p"
	.string "준비되면\n"
	.string "다시 방문해 주십시오$"

BattleTower_Lobby_Text_19A3FD:: @ 819A3FD
	.string "손님!\p"
	.string "지난번에 종료하기 전에\n"
	.string "리포트를 제대로\l작성하지 않으셨죠?\p"
	.string "죄송합니다만 이런 경우에는\n"
	.string "도전이 무효가 됩니다$"

BattleTower_Lobby_Text_19A487:: @ 819A487
	.string "축하합니다!\n"
	.string "멋지게 7명 돌파하셨네요!\p"
	.string "$"

BattleTower_Lobby_Text_19A4BB:: @ 819A4BB
	.string "7명을 돌파하기를 달성하였으므로\n"
	.string "상품을 드리겠습니다!\p"
	.string "$"

BattleTower_Lobby_Text_19A506:: @ 819A506
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "{STR_VAR_1}{K_EULREUL} 받았다!$"

BattleTower_Lobby_Text_19A520:: @ 819A520
	.string "...어머 가방이 가득찼습니다\p"
	.string "가방을 정리하시고\n"
	.string "다시 와주시기 바랍니다$"

BattleTower_Lobby_Text_19A571:: @ 819A571
	.string "고생하셨습니다!\p"
	.string "$"

BattleTower_Lobby_Text_19A589:: @ 819A589
	.string "성적을 리포트에 작성중입니다\n"
	.string "기다려 주십시오$"

BattleTower_Lobby_Text_19A5B1:: @ 819A5B1
	.string "기다리고 있었습니다!\p"
	.string "$"

BattleTower_Lobby_Text_19A5CE:: @ 819A5CE
	.string "배틀룸에 안내하기 전에\n"
	.string "리포트를 작성하겠습니다\l"
	.string "기다려 주십시오$"

BattleTower_Lobby_Text_19A617:: @ 819A617
	.string "드디어 50명째\n"
	.string "트레이너와의 승부군요!\p"
	.string "이제부터 7연승을 할 때마다\n"
	.string "당신의 포켓몬에게 기념 리본이\l"
	.string "수여가 될테니 힘내주시기 바랍니다!$"

BattleTower_Lobby_Text_19A6BE:: @ 819A6BE
	.string "강한 트레이너 7명을 연속으로\n"
	.string "승리하신 기념의 리본을 받으세요!\p"
	.string "{PLAYER}{K_EUNNEUN} 리본을 받았다!$"

BattleTower_Lobby_Text_19A719:: @ 819A719
	.string "{PLAYER}{K_EUNNEUN} 포켓몬에게\n"
	.string "리본을 달아주었다!$"

BattleTower_Lobby_Text_19A747:: @ 819A747
	.string "저기 저기!\p"
	.string "배틀타워에서 이제부터 승부다!\n"
	.string "...라고 말할 때\l"
	.string "너의 마음을 알려줘!$"

BattleTower_Lobby_Text_19A7C3:: @ 819A7C3
	.string "우와 가르쳐주는건가!\n"
	.string "그럼 바로...$"

BattleTower_Lobby_Text_19A7FD:: @ 819A7FD
	.string "특별히 아무 생각이 없는건가?\n"
	.string "너 쿨하구나$"

BattleTower_Lobby_Text_19A83D:: @ 819A83D
	.string "어라? 역시 그만두는거야?\n"
	.string "변덕쟁이구나$"

BattleTower_Lobby_Text_19A871:: @ 819A871
	.string "와우 그런 기분인건가!\n"
	.string "좀 독특하구나...\p"
	.string "정말 고마워!$"

BattleTower_Lobby_Text_19A8AE:: @ 819A8AE
	.string "배틀에서 승리한 트레이너의 수가\n"
	.string "기록되고 있어!\p"
	.string "기록은 접수대 옆에 있고\n"
	.string "트레이너카드 뒷면에도 있어!$"

BattleTower_Lobby_Text_19A946:: @ 819A946
	.string "일단 배틀타워에 들어가면\n"
	.string "도중에 패배하거나\l"
	.string "7명을 승리할 때까지는\l"
	.string "퇴장할 수가 없어!\p"
	.string "각오하고 도전해야 돼!$"

BattleTower_Lobby_Text_19A9EE:: @ 819A9EE
	.string "하하하 이야 훌륭해요\n"
	.string "정말 좋아요!\p"
	.string "당신은 알고 계신가요?\n"
	.string "50명을 패배시켜버렸어요!\p"
	.string "굉장하십니다!\p"
	.string "배틀타워오너인 제게서\n"
	.string "반드시 기념품을 받아주세요!$"

BattleTower_Lobby_Text_19AAC4:: @ 819AAC4
	.string "하하하 이야 훌륭해요\n"
	.string "정말 좋아요!\p"
	.string "당신은 알고 계신가요?\n"
	.string "100명을 패배시켜버렸어요!\p"
	.string "굉장하십니다!\p"
	.string "배틀타워오너인 제게서\n"
	.string "반드시 기념품을 받아주세요!$"

BattleTower_Lobby_Text_19ABAA:: @ 819ABAA
	.string "이것을 장식해두면 주목받을 겁니다!$"

BattleTower_Lobby_Text_19ABED:: @ 819ABED
	.string "어라 PC가 가득하네요...\p"
	.string "하지만 모처럼이니까!\n"
	.string "나중에 괜찮을 때 받으러 오십시오!$"

BattleTower_Lobby_Text_19AC55:: @ 819AC55
	.string "이렇게 훌륭한 승부를\n"
	.string "보여주시니 만족입니다!\l"
	.string "배틀타워를 세운 보람이 있군요!$"
