BattleTower_Outside_Text_199C6F:: @ 8199C6F
	.string "여기는 배틀타워!\n"
	.string "이겨라! 최강의 트레이너$"

BattleTower_Outside_Text_199CA4:: @ 8199CA4
	.string "여기는 배틀타워야!\p"
	.string "트레이너는 단련된 포켓몬으로\n"
	.string "계속해서 이겨 나가는 거지!$"

BattleTower_Outside_Text_199D06:: @ 8199D06
	.string "연락선을 이용하시려는 거군요!\n"
	.string "티켓은 가지고 계신가요?$"

BattleTower_Outside_Text_199D40:: @ 8199D40
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "티켓이 없다!\p"
	.string "...죄송합니다!\p"
	.string "배에는 티켓을 가진 분들만\n"
	.string "탑승하실 수 있습니다$"

BattleTower_Outside_Text_199D9D:: @ 8199D9D
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "승선티켓을 보여줬다!\p"
	.string "네! 확인했습니다!\p"
	.string "어디로 가시겠어요?$"

BattleTower_Outside_Text_199DF2:: @ 8199DF2
	.string "잿빛도시 말씀이시군요?$"

BattleTower_Outside_Text_199E0E:: @ 8199E0E
	.string "해안시티 말씀이시군요?$"

BattleTower_Outside_Text_199E29:: @ 8199E29
	.string "또 이용해 주십시오!$"

BattleTower_Outside_Text_199E4B:: @ 8199E4B
	.string "연락선에서 잠시 기다려 주십시오$"

BattleTower_Outside_Text_199E7A:: @ 8199E7A
	.string "어디로 가시겠어요?$"

BattleTower_Outside_Text_199E9C:: @ 8199E9C
	.string "오늘 35연승을 하기 전까지는\n"
	.string "떠나지 않을 거야!$"

BattleTower_Outside_Text_199ED4:: @ 8199ED4
	.string "엄청 강할 것 같은 트레이너가\n"
	.string "많이 있네!\l"
	.string "나는 아직 들어가지 못할 것 같아...$"
