DewfordTown_Gym_Text_174D98:: @ 8174D98
	.string "잘 있었나!!\n"
	.string "챔피언을 노리는 {PLAYER}!!\p"
	.string "무로마을 체육관 관장 철구는\n"
	.string "격투타입 포켓몬을 쓴다!\p"
	.string "노말타입으로 도전하면 정말\n"
	.string "뼈아픈 한 방을 맞게 될 테니까\l"
	.string "조심하는 게 좋을 거야!\p"
	.string "게다가 체육관도 바다 깊은 곳처럼\n"
	.string "어두워서 스스로 길을 찾아야 하지!\p"
	.string "하지만 도중에 트레이너들을\n"
	.string "쓰러뜨릴수록 체육관이\l"
	.string "밝아지니까 괜찮을 거야!\p"
	.string "그럼 힘내라고-!!$"

DewfordTown_Gym_Text_174F1E:: @ 8174F1E
	.string "오오! 꽤나 밝아졌구나!\p"
	.string "네 미래도 밝을 거야!$"

DewfordTown_Gym_Text_174F61:: @ 8174F61
	.string "힘이야말로 정의!\n"
	.string "이야아아-압!!$"

DewfordTown_Gym_Text_174F7A:: @ 8174F7A
	.string "힘이 부족했다...!$"

DewfordTown_Gym_Text_174F8E:: @ 8174F8E
	.string "부드러운 것이 강한 것을 제압한다!\n"
	.string "아주 멋진 승부였다!$"

DewfordTown_Gym_Text_174FCE:: @ 8174FCE
	.string "철구님과 승부할 것까지도 없어!\n"
	.string "내가 지금 여기서\p"
	.string "쓰러뜨려 줄 테니까!$"

DewfordTown_Gym_Text_175009:: @ 8175009
	.string "이럴 수가...\n"
	.string "이렇게 쉽게 당하다니...$"

DewfordTown_Gym_Text_175031:: @ 8175031
	.string "이 패배가 헛되이 되지 않도록\n"
	.string "더욱 특훈하겠어!\p"
	.string "그리고 언젠가는 체육관 관장...\p"
	.string "아니지! 포켓몬리그의\n"
	.string "챔피언이 될 거야!$"

DewfordTown_Gym_Text_1750C9:: @ 81750C9
	.string "날 쉽게 보지 말라고!\n"
	.string "질질 짜게 돼도 난 모르니까!$"

DewfordTown_Gym_Text_175104:: @ 8175104
	.string "으아---앙!\n"
	.string "져버렸어---엉!$"

DewfordTown_Gym_Text_175117:: @ 8175117
	.string "정신을 단련하기 위해\n"
	.string "어둠 속에서 승부하고 있어!\p"
	.string "하지만 너무 어두워서\n"
	.string "철구님의 얼굴이 보이지 않아...$"

DewfordTown_Gym_Text_175182:: @ 8175182
	.string "난 무로마을 포켓몬체육관\n"
	.string "관장 철구!\p"
	.string "이 주변의\n"
	.string "거친 파도에 버티면서...\p"
	.string "마을 외곽에 있는 동굴과\n"
	.string "이 체육관의 설비를 사용해\l"
	.string "전력을 다해 수행하고 있어!\p"
	.string "나에게 도전하려고 하는\n"
	.string "너의 실력...\p"
	.string "어느 정도인지 시험해보겠어!$"

DewfordTown_Gym_Text_175246:: @ 8175246
	.string "으- 넌 예상보다\n"
	.string "빅 웨이브!\p"
	.string "날 이겼구나!\p"
	.string "훌륭해!\n"
	.string "이 배지를 가지고 가!$"

DewfordTown_Gym_Text_1752BB:: @ 81752BB
	.string "{PLAYER}{K_EUNNEUN} 철구에게\n"
	.string "너클배지를 받았다!$"

DewfordTown_Gym_Text_1752E6:: @ 81752E6
	.string "너클배지에는\n"
	.string "레벨30까지의 포켓몬이라면\p"
	.string "다른 사람에게 받은 포켓몬이라도\n"
	.string "얌전하게 만드는 효과가 있어!\p"
	.string "그리고 비전기술인 플래시를\n"
	.string "사용할 수 있게 돼!\p"
	.string "...음 그리고 괜찮으면\n"
	.string "이 기술머신도 한번 써 봐$"

DewfordTown_Gym_Text_1753BF:: @ 81753BF
	.string "기술머신08에는\n"
	.string "벌크업이 들어 있어!\p"
	.string "벌크업은 일시적으로 포켓몬의\n"
	.string "근육 파워를 올려줘!\p"
	.string "공격과 방어를\n"
	.string "끝내주게 올려주지!$"

DewfordTown_Gym_Text_175412:: @ 8175412
	.string "네 재능은\n"
	.string "언젠가 거대한 파도가 되어\p"
	.string "포켓몬 트레이너들 사이에서\n"
	.string "놀라움의 태풍을 불러일으키겠지!$"

DewfordTown_Gym_Text_175477:: @ 8175477
	.string "무로마을 포켓몬체육관$"

DewfordTown_Gym_Text_175490:: @ 8175490
	.string "무로마을 포켓몬체육관\p"
	.string "철구 인정 트레이너!\n"
	.string "{PLAYER}$"
