DewfordTown_House2_Text_175EFE:: @ 8175EFE
	.string "이게 바로!\p"
	.string "요즘 가장 유행하는 실크스카프!\n"
	.string "어때? 정말 멋지지?!\p"
	.string "오! 흥미가 생긴 모양이지?\n"
	.string "내 센스를 알아주는구나 너는!\p"
	.string "정말 고마워!\n"
	.string "이건 선물로 줄게!$"

DewfordTown_House2_Text_175FDA:: @ 8175FDA
	.string "오, 가방이 가득 찼구나!\p"
	.string "이 실크스카프는 필수 구매\n"
	.string "아이템이라고! 다른 물건을\l"
	.string "팔아서라도\l"
	.string "구매할 만큼 말야!$"

DewfordTown_House2_Text_176055:: @ 8176055
	.string "실크스카프는 노말타입의 기술의\n"
	.string "위력을 높여주지!\p"
	.string "대부분의 포켓몬에게 어울리는\n"
	.string "멋진 스카프야!$"

DewfordTown_House2_Text_1760C8:: @ 81760C8
	.string "우와! 일부러 바다를 건너서\n"
	.string "무로마을가지 왔구나!\p"
	.string "혹시 철구님의 소문을 듣고\n"
	.string "만나러 온 거야?\p"
	.string "철구님은 정말 멋있어서\n"
	.string "모두가 동경하잖아!$"
