DewfordTown_Text_16B23B:: @ 816B23B
	.string "무로마을은 작은 섬이어서\n"
	.string "뭔가 하나라도 유행하기 시작하면\l"
	.string "금세 다들 그걸 따라 하려고 해$"

DewfordTown_Text_16B2A7:: @ 816B2A7
	.string "여기는 무로마을\n"
	.string "푸른 바다에 떠 있는 작은 섬$"

DewfordTown_Text_16B2D5:: @ 816B2D5
	.string "무로마을 포켓몬체육관\n"
	.string "관장 철구\l"
	.string "격투의 빅 웨이브!$"

DewfordTown_Text_16B317:: @ 816B317
	.string "“무로집회소”\n"
	.string "모두의 정보교환 장소$"

Route104_Text_16B347:: @ 816B347
	.string "하기: 호이! 무로마을에 도착!\p"
	.string "분명 성호라는 남자한테\n"
	.string "편지를 전해준다고 했었지!$"

DewfordTown_Text_16B3BC:: @ 816B3BC
	.string "하기: 편지는 잘 전달했나?\p"
	.string "아니면 등화도시로 돌아갈 겐가?$"

DewfordTown_Text_16B417:: @ 816B417
	.string "하기: 그럼 등화도시로\n"
	.string "돌아가도록 하마!\p"
	.string "좋다! 가자 피코!$"

DewfordTown_Text_16B471:: @ 816B471
	.string "하기: 그럼 편지를\n"
	.string "전달하고 오너라\p"
	.string "나는 여기서 기다리마$"

Route104_Text_16B4B5:: @ 816B4B5
Route109_Text_16B4B5:: @ 816B4B5
	.string "하기: 호이! 무로마을에 도착!\p"
	.string "배를 타고 싶어지면\n"
	.string "언제든 나한테 말해 주게나!$"

DewfordTown_Text_16B522:: @ 816B522
	.string "하기: 여어! 자네가 원한다면\n"
	.string "언제든지 배를 준비시키지!\p"
	.string "자네가 가고 싶은 곳은 어딘가?$"

DewfordTown_Text_16B57D:: @ 816B57D
	.string "하기: 등화도시 말이지\p"
	.string "좋다! 가자 피코!$"

DewfordTown_Text_16B5D2:: @ 816B5D2
	.string "하기: 잿빛도시 말이지\p"
	.string "좋다! 가자 피코!$"

DewfordTown_Text_16B627:: @ 816B627
	.string "하기: 배를 타야 할 때는\n"
	.string "언제든지 말해 주게나$"

DewfordTown_Text_16B665:: @ 816B665
	.string "요 근처는 낚시의 명소야\n"
	.string "너도 낚시하고 싶어졌지?$"

DewfordTown_Text_16B6A8:: @ 816B6A8
	.string "응응 좋아\n"
	.string "나한테 있는 낚싯대 나눠줄게!$"

DewfordTown_Text_16B6F9:: @ 816B6F9
	.string "좋아 인심 쓴다!\n"
	.string "낚시 잘하는 방법도 알려줄게!\p"
	.string "먼저 수면을 향해\n"
	.string "낚싯대를 던져!\l"
	.string "그리고 정신을 집중하다가...\p"
	.string "물었다 물었어!!\n"
	.string "짠! 하는 느낌이 오면 재빠르게\l"
	.string "낚싯대를 잡아당기는 거야!\p"
	.string "바로 잡아당기게 되는 때도 있지만\n"
	.string "엄청난 놈은 몇 번이나 타이밍을\l"
	.string "맞출 필요가 있어!$"

DewfordTown_Text_16B828:: @ 816B828
	.string "그래...\n"
	.string "안타깝네$"

DewfordTown_Text_16B84E:: @ 816B84E
	.string "어때!\n"
	.string "낚시는 잘되고 있어?$"

DewfordTown_Text_16B866:: @ 816B866
	.string "그래? 그거 대단한데!\n"
	.string "엄청난 놈을 한번 잡아 줘!$"

DewfordTown_Text_16B89A:: @ 816B89A
	.string "너무 그렇게 실망하지 마!\n"
	.string "낚시 잘하는 방법을 알려줄 테니까!\p"
	.string "먼저 수면을 향해\n"
	.string "낚싯대를 던져!\l"
	.string "그리고 정신을 집중하다가...\p"
	.string "물었다 물었어!!\n"
	.string "짠! 하는 느낌이 오면 재빠르게\l"
	.string "낚싯대를 잡아당기는 거야!\p"
	.string "바로 잡아당기게 되는 때도 있지만\n"
	.string "엄청난 놈은 몇 번이나 타이밍을\l"
	.string "맞출 필요가 있어!$"

DewfordTown_Text_16B9CE:: @ 816B9CE
	.string "난 요즘 유행에 관심이 있어서\n"
	.string "항상 체크하고 있어\p"
	.string "혹시 “{STR_VAR_1}”{K_I}라고\n"
	.string "들어본 적 있어?\p"
	.string "당연히 들어본 적 있겠지!\p"
	.string "왜냐하면 요즘\n"
	.string "“{STR_VAR_1}”{K_IGA}\l"
	.string "완전 붐이잖아!\p"
	.string "네 주변에서도\n"
	.string "“{STR_VAR_1}”{K_IGA}\l"
	.string "유행하고 있지?$"

DewfordTown_Text_16BADC:: @ 816BADC
	.string "뭐?\n"
	.string "유행하지 않는다고?!\p"
	.string "그럼 요즘 뭐가 유행하고 있는지\n"
	.string "알려줘!$"

DewfordTown_Text_16BB44:: @ 816BB44
	.string "응? “{STR_VAR_2}”?\p"
	.string "... ...\p"
	.string "...아! 응응!\n"
	.string "응 알아 알아!\p"
	.string "무, 물론 알고 있지!\n"
	.string "“{STR_VAR_2}”{K_I}잖아?\p"
	.string "그거 좋지!\n"
	.string "“{STR_VAR_2}”!\p"
	.string "지금 엄청 붐이잖아\n"
	.string "내가 그걸 모를 리가 있나!\p"
	.string "“{STR_VAR_1}”{K_EUNNEUN}\n"
	.string "이미 한물갔지\p"
	.string "요즘은 “{STR_VAR_2}”의\n"
	.string "시대야!$"

DewfordTown_Text_16BCA2:: @ 816BCA2
	.string "음...\n"
	.string "“{STR_VAR_2}”?\p"
	.string "하지만 내 생각엔 역시\n"
	.string "“{STR_VAR_1}”{K_IGA}\l"
	.string "제일 멋지다고 생각해$"

DewfordTown_Text_16BCE9:: @ 816BCE9
	.string "새로운 유행을 알게 되면\n"
	.string "나한테 꼭 알려줘!$"

DewfordTown_Text_16BD37:: @ 816BD37
	.string "그치!\p"
	.string "역시 요즘에는\n"
	.string "“{STR_VAR_1}”{K_IGA} 대세야!$"

DewfordTown_Text_16BD79: @ 816BD79
	.string "지금 “{STR_VAR_2}”{K_EUNNEUN}\n"
	.string "유행의 절정이지!$"
