EverGrandeCity_PokemonLeague_Text_1916FD:: @ 81916FD
	.string "이 앞은\n"
	.string "모든 체육관 배지를 모은\l"
	.string "트레이너만이 지나갈 수 있습니다!\p"
	.string "트레이너여! 당신의 체육관 배지를\n"
	.string "확인하도록 하겠습니다$"
	// これより さきはｎ
	// すべての ジムバッジを あつめたｌ
	// トレ-ナ-だけが すすめます!ｐ
	// トレ-ナ-よ! きみの ジムバッジｎ
	// かくにん させてください

EverGrandeCity_PokemonLeague_Text_19179C:: @ 819179C
	.string "당신은 아직\n"
	.string "모든 체육관 배지를\l"
	.string "가지고 있지 않습니다!\p"
	.string "포켓몬리그를 목표로 한다면\n"
	.string "체육관 배지를 갖고\l"
	.string "되돌아오십시오$"
	// きみは まだｎ
	// すべての ジムバッジを もっていない!ｐ
	// ポケモン リ-グを めざすならｎ
	// でなおして きなさい

EverGrandeCity_PokemonLeague_Text_191804:: @ 8191804
	.string "트레이너여!\n"
	.string "자신과 포켓몬을 믿고 나아가시길!$"
	// トレ-ナ-よ! おのれとｎ
	// ポケモンを しんじて すすみたまえ!
