EverGrandeCity_PhoebesRoom_Text_1908F5:: @ 81908F5 //JP: 16E58A
	.string "아하하!\p"
	.string "난 사천왕 회연\p"
	.string "송화산에서 수행하면서\n"
	.string "고스트타입 포켓몬과\l"
	.string "마음이 통하게 됐어\p"
	.string "응 나와 내 포켓몬의 유대감은\n"
	.string "정말 강해!\p"
	.string "이런 내 포켓몬들에게\n"
	.string "과연 데미지를 줄 수 있을지\l"
	.string "한번 시험해봐!$"

EverGrandeCity_PhoebesRoom_Text_190A0C:: @ 8190A0C
	.string "아-아\n"
	.string "져버렸다$"

EverGrandeCity_PhoebesRoom_Text_190A2A:: @ 8190A2A
	.string "너와 네 포켓몬 사이에도\n"
	.string "분명한 유대감이 존재하는구나\p"
	.string "그걸 눈치채지 못했으니\n"
	.string "내가 지는 것도 당연할 수밖에\p"
	.string "응 너희들의 유대감이 과연\n"
	.string "어디까지 힘을 발휘할지 보고 싶네\l"
	.string "그럼 다음 방으로 가도록 해$"
