EverGrandeCity_GlaciasRoom_Text_190AF9:: @ 8190AF9 //JP: 16E73C
	.string "어서 오세요\n"
	.string "사천왕 미혜입니다\p"
	.string "얼음타입 기술을 갈고닦기 위해\n"
	.string "머나먼 호연지방까지 왔습니다\p"
	.string "하지만 이곳에 도전하러 오는 건\n"
	.string "모두 어설픈\l"
	.string "트레이너와 포켓몬뿐...\p"
	.string "당신은 어떤가요?\p"
	.string "제 진짜 실력을 발휘해도\n"
	.string "괜찮을 정도라면\l"
	.string "정말 기쁠 텐데 말이죠...!!$"

EverGrandeCity_GlaciasRoom_Text_190C01:: @ 8190C01
	.string "당신과 포켓몬들의\n"
	.string "뜨거운 혼!$"

EverGrandeCity_GlaciasRoom_Text_190C8F:: @ 8190C8F
	.string "당신들의 혼...\p"
	.string "그것은 무엇보다도 뜨거워서\n"
	.string "제 얼음타입 기술이\l"
	.string "통할 만한 것이 아니었군요\p"
	.string "계속 나아가세요\p"
	.string "그리고 포켓몬리그의\n"
	.string "진정한 두려움을 느껴보시길...$"
