EverGrandeCity_ChampionsRoom_Text_190F9C:: @ 8190F9C //JP: 16ECAB
	.string "성호: 어서 와 {PLAYER}\p"
	.string "네가 언제 여기까지 올지\n"
	.string "기대하고 있었어\p"
	.string "넌... 포켓몬과 함께 모험을 하면서\n"
	.string "무엇을 봤지?\p"
	.string "많은 트레이너와 만나면서\n"
	.string "무엇을 느꼈지?\p"
	.string "네 안에서 눈뜨기 시작한 무언가\n"
	.string "그 모든 것을 나에게\l"
	.string "쏟아부었으면 좋겠어!\p"
	.string "자 그럼 시작하지!!$"

EverGrandeCity_ChampionsRoom_Text_1910A0:: @ 81910A0
	.string "챔피언인\n"
	.string "내가 질 줄이야...\p"
	.string "역시 {PLAYER}!\p"
	.string "넌 정말 대단한\n"
	.string "포켓몬 트레이너야!$"

EverGrandeCity_ChampionsRoom_Text_1910FE:: @ 81910FE
	.string "성호: 축하한다!\p"
	.string "너의 포켓몬을 생각하는 마음\p"
	.string "그리고 그 마음에 부응하기 위해\n"
	.string "모든 힘을 쏟아내는 포켓몬...\p"
	.string "그것들이 모두 하나로 뭉쳐져\n"
	.string "더욱 거대한 힘을 탄생시켰어!\p"
	.string "그렇기에 이렇게 네가\n"
	.string "승리를 손에 쥘 수 있었던 거야!\p"
	.string "너야말로 호연지방의\n"
	.string "새로운...$"

EverGrandeCity_ChampionsRoom_Text_191225:: @ 8191225
	.string "봄이: {PLAYER}!\p"
	.string "챔피언한테 도전하기 전에\n"
	.string "어드바이스를...!$"

EverGrandeCity_ChampionsRoom_Text_191268:: @ 8191268
	.string "봄이: 응? 으응??\p"
	.string "{PLAYER}...\n"
	.string "설마...\l"
	.string "이미 끝난 거야...?$"

EverGrandeCity_ChampionsRoom_Text_1912B3:: @ 81912B3
	.string "휘웅: {PLAYER}!\p"
	.string "챔피언한테 도전하기 전에\n"
	.string "내가 어드바이스를 해줄 테니까...$"

EverGrandeCity_ChampionsRoom_Text_191305:: @ 8191305
	.string "휘웅: {PLAYER}...\p"
	.string "너 설마\n"
	.string "챔피언한테 이긴 거야?$"

EverGrandeCity_ChampionsRoom_Text_19134D:: @ 819134D
	.string "털보박사: 거봐라 {RIVAL}\i!\p"
	.string "{PLAYER}\e라면 걱정할 필요 없다고\n"
	.string "내가 말하지 않았더냐!\p"
	.string "... ... ...\n"
	.string "{PLAYER} 드디어 해냈구나\p"
	.string "네가 등화체육관에 있는 아빠한테\n"
	.string "이겼다고 들었을 때부터\l"
	.string "혹시나...하는 생각은 있었다만\p"
	.string "설마 진짜 챔피언이\n"
	.string "될 줄이야!\p"
	.string "...오오 맞다!\p"
	.string "너의 포켓몬 도감은 어떻게 되었니?\n"
	.string "나에게 보여다오!$"

EverGrandeCity_ChampionsRoom_Text_1914C6:: @ 81914C6
	.string "털보박사: 어쨌든 축하한다!\p"
	.string "자 그럼 당당하게 안쪽 방에\n"
	.string "갔다 오너라!$"

EverGrandeCity_ChampionsRoom_Text_191512:: @ 8191512
	.string "성호: {PLAYER}\p"
	.string "...아니 새로운 챔피언!\n"
	.string "날 따라와$"

EverGrandeCity_ChampionsRoom_Text_191546:: @ 8191546
	.string "성호: 정말 미안한데...\p"
	.string "여기서부터는 챔피언이 된\n"
	.string "트레이너만이 들어갈 수 있는 장소!\p"
	.string "너는 거기서 박사와 함께\n"
	.string "기다리고 있어줘$"

EverGrandeCity_ChampionsRoom_Text_1915D7:: @ 81915D7
	.string "봄이: ...힝!\p"
	.string "... ... ... ...\n"
	.string "... ... ... ...\p"
	.string "장난이야! 괜찮아 괜찮아!\n"
	.string "그게 룰이니까 지켜야지!\p"
	.string "{PLAYER}!\n"
	.string "정말 축하해!!$"

EverGrandeCity_ChampionsRoom_Text_191675:: @ 8191675
	.string "휘웅: !\p"
	.string "... ... ... ...\n"
	.string "... ... ... ...\p"
	.string "어쩔 수 없지\n"
	.string "룰이 그런 거니까\p"
	.string "{PLAYER}!\n"
	.string "정말 축하해!!$"
