EverGrandeCity_PokemonCenter_1F_Text_191967:: @ 8191967
	.string "포켓몬리그는\n"
	.string "챔피언로드를 빠져나가면\l"
	.string "바로 눈앞이야!\p"
	.string "여기까지 왔으면\n"
	.string "이제 앞으로 나아가는 수밖에 없어!$"
	// ポケモンリ-グはｎ
	// チャンピオンロ-ドを ぬけると すぐ!ｐ
	// ここまで きたらｎ
	// まえに すすむしかないわ!

EverGrandeCity_PokemonCenter_1F_Text_1919EF:: @ 81919EF
	.string "챔피언로드의\n"
	.string "멀고 험한 길...\p"
	.string "지금까지 걸어온 여정을\n"
	.string "다시 떠올리게 하는군\p"
	.string "너도 자신의 포켓몬을\n"
	.string "믿고 최선을 다하길 바란다!$"
	// チャンピオンロ-ドのｎ
	// ながくて けわしい みちのり……ｐ
	// まるで いままで あるいてきた みちをｎ
	// おもいださせるかの ようだなｐ
	// きみ じぶんの ポケモンを ｎ
	// しんじて がんばりたまえ!
