FallarborTown_House2_Text_177AF4:: @ 8177AF4
	.string "난 포켓몬 기술마니아\p"
	.string "포켓몬이 성장해서 배우는\n"
	.string "기술을 모두 알고 있어서\l"
	.string "포켓몬에게 가르쳐줄 수 있어!\p"
	.string "지금 내가 모으고 있는\n"
	.string "하트비늘을 주면\l"
	.string "알고 있는 기술을 가르쳐줄게!$"

FallarborTown_House2_Text_177BDB:: @ 8177BDB
	.string "오오!\n"
	.string "그건 바로 하트비늘!\p"
	.string "기술을 떠올리게 할 거야?$"

FallarborTown_House2_Text_177C3F:: @ 8177C3F
	.string "어느 포켓몬에게 할 거야?$"

FallarborTown_House2_Text_177C5D:: @ 8177C5D
	.string "어느 기술을 배우게 할 거야?$"

FallarborTown_House2_Text_177C78:: @ 8177C78
	.string "미안해...\p"
	.string "내가 그 포켓몬에게\n"
	.string "가르쳐줄 수 있는 기술은\l"
	.string "없는 것 같아$"

FallarborTown_House2_Text_177CC3:: @ 8177CC3
	.string "{PLAYER}{K_EUNNEUN} 보답으로\n"
	.string "하트비늘을 1장 주었다!$"

FallarborTown_House2_Text_177CEF:: @ 8177CEF
	.string "포켓몬에게 떠올리게 하고 싶은\n"
	.string "기술이 있으면\l"
	.string "하트비늘을 가지고 오렴!$"

FallarborTown_House2_Text_177D33:: @ 8177D33
	.string "엥?\n"
	.string "알에게 가르쳐줄 기술은 없어$"
