FallarborTown_Text_16C7FF:: @ 816C7FF
	.string "뭐야 뭐야!?\p"
	.string "공석박사님의 연구소에\n"
	.string "수상한 사람들이 드나들던데!$"

FallarborTown_Text_16C855:: @ 816C855
	.string "여기 일대는\n"
	.string "옛날부터 운석이 많아서 말이야\p"
	.string "유성의 폭포도 운석이 떨어져서\n"
	.string "만들어졌다나 그렇게 전해지고 있어$"

FallarborTown_Text_16C8D6:: @ 816C8D6
	.string "자! 이것 봐!\n"
	.string "내 소중한 루리리!\p"
	.string "매끈매끈이라\n"
	.string "쓰다듬으면 푹신푹신이라고!$"

FallarborTown_Text_16C92C:: @ 816C92C
	.string "루리리: 루-릴-$"

FallarborTown_Text_16C941:: @ 816C941
	.string "용암마을의 체육관 관장\n"
	.string "민지하고 배틀했니?\p"
	.string "그 아이의 할아버지는 굉장했어\n"
	.string "뭐라더라 포켓몬리그의\l"
	.string "사천왕이었다고 하더라고\p"
	.string "아마 민지도 이제부터\n"
	.string "훌륭한 트레이너가 되겠지$"

FallarborTown_Text_16CA39:: @ 816CA39
	.string "포켓몬 콘테스트 슈퍼랭크 접수처\n"
	.string "뽐내라! 포켓몬 트레이너!$"

FallarborTown_Text_16CA83:: @ 816CA83
	.string "여기는 단풍마을\n"
	.string "작은 밭이 있는 농촌$"

FallarborTown_Text_16CAB9:: @ 816CAB9
	.string "“기술마니아의 집”\n"
	.string "포켓몬 기술을 가르쳐 드립니다!$"
