FallarborTown_ContestHall_Text_177335:: @ 8177335
	.string "1차 심사에서는 잘하는데\n"
	.string "왠지 어필에서\l"
	.string "이기지 못하고 있어...\p"
	.string "자신의 포켓몬만 보고 있으면\n"
	.string "이길 수 없다는 거겠지$"

FallarborTown_ContestHall_Text_1773C6:: @ 81773C6
	.string "봐봐! 내 포켓몬\n"
	.string "이렇게나 리본이 많아!\p"
	.string "네 포켓몬은 리본을 받았니?\n"
	.string "받았다면 포켓내비에서 볼 수 있어!$"

FallarborTown_ContestHall_Text_177437:: @ 8177437
	.string "체육관 관장에게 이길 수 없어...\p"
	.string "콘테스트에서도 이길 수 없어...\p"
	.string "이 마을 저 마을을\n"
	.string "왔다리 갔다리 하고 있어...$"

FallarborTown_ContestHall_Text_1774B1:: @ 81774B1
	.string "포켓몬 콘테스트\n"
	.string "슈퍼랭크 스테이지!$"
