FallarborTown_ContestLobby_Text_177141:: @ 8177141
	.string "내 포켓몬 저쪽 벽에\n"
	.string "초상화가 걸려 있었는데\p"
	.string "벌써 다른 포켓몬 걸로\n"
	.string "바뀌어 버렸어...\p"
	.string "다음에 또 힘내서 나의 꽃님이를\n"
	.string "걸어 놓도록 하겠어!!$"

FallarborTown_ContestLobby_Text_1771F2:: @ 81771F2
	.string "포켓몬스넥 만들고 있어?\p"
	.string "다음에는 나무열매를 잔뜩\n"
	.string "가져오도록 해!$"

FallarborTown_ContestLobby_Text_177246:: @ 8177246
	.string "여기에 우승한 포켓몬의\n"
	.string "미소가 장식되어있지?\p"
	.string "이거 내가 그린 거야!\p"
	.string "너의 포켓몬이 우승하면\n"
	.string "힘내서 그려줄게!$"

FallarborTown_ContestLobby_Text_1772D8:: @ 81772D8
	.string "여어! 우승 축하해!\p"
	.string "네 포켓몬의 초상화는\n"
	.string "여기에 똑바로 장식되어있어!$"
