FallarborTown_PokemonCenter_1F_Text_1774D4:: @ 81774D4
	.string "당신은...?\p"
	.string "{PLAYER}{K_I}라고 하는군요\n"
	.string "당신 트레이너군요\p"
	.string "그렇다는 건 내가 만든\n"
	.string "보관 시스템 사용하고 계신 거죠?\p"
	.string "왜냐면 사용하고 싶으니까\n"
	.string "PC 앞에 있는 나한테\l"
	.string "말을 걸었을 거 아니에요\l"
	.string "간단한 추리예요\p"
	.string "아 전 보은이라고 해요\p"
	.string "보관 시스템을 사용하고 있는\n"
	.string "트레이너를 만나 너무 기뻐요\p"
	.string "괜찮으시다면 저희 집에도\n"
	.string "놀러 와 주세요\l"
	.string "114번도로에 있으니까요$"

FallarborTown_PokemonCenter_1F_Text_17768C:: @ 817768C
	.string "오랜 옛날의 포켓몬은\n"
	.string "어떤 모습을 하고 있었을까?\p"
	.string "이 마을 외곽에 있는\n"
	.string "화석마니아라면 알려줄지도$"

FallarborTown_PokemonCenter_1F_Text_1776F5:: @ 81776F5
	.string "여기 단풍마을의 밭에는\n"
	.string "화산재 안에서도 자랄 정도로\l"
	.string "튼튼한 나무의 모종을 심어놨단다$"
