FortreeCity_House2_Text_186306:: @ 8186306 //JP: 1654BF
	.string "사람도 포켓몬도\n"
	.string "자연 속에서 살아가는 것으로\l"
	.string "본연의 힘이 깨어난다...$"

FortreeCity_House2_Text_186360:: @ 8186360
	.string "자네의 힘이 깨어 있는지\n"
	.string "확인해보도록 하지...\p"
	.string "어디 보자... 내 오른손과 왼손\n"
	.string "어느 쪽에 코인이 있는지\l"
	.string "직감으로 선택해봐$"

FortreeCity_House2_Text_1863F6:: @ 81863F6
	.string "오오! 정답이다!\p"
	.string "오른손과 왼손\n"
	.string "어느 쪽에 코인이 있는지\l"
	.string "직감으로 선택해봐$"

FortreeCity_House2_Text_186455:: @ 8186455
	.string "오오! 정답이다!\p"
	.string "오른손과 왼손\n"
	.string "어느 쪽에 코인이 있는지\l"
	.string "직감으로 선택해봐$"

FortreeCity_House2_Text_1864C6:: @ 81864C6
	.string "오옷! 대단하군!\n"
	.string "자네의 힘은 깨어 있어!\p"
	.string "이것을 줄 테니\n"
	.string "자네의 포켓몬이 가진 힘을\l"
	.string "깨우도록 하게!$"

FortreeCity_House2_Text_18652F:: @ 818652F
	.string "잠재파워는 포켓몬에 따라\n"
	.string "위력이 달라지는 기술이라네!$"

FortreeCity_House2_Text_186565:: @ 8186565
	.string "이런...\n"
	.string "꽝이라네...$"

UnknownString_8186585: @ 8186585
	.string "검방울시티 주변은 마치 정글 같아!\n"
	.string "걷고 있으면 바로 녹초가 되어버려!\p"
	.string "그럴 때는 포켓몬의 공중날기로\n"
	.string "가본 적이 있는 마을까지 단숨에!$"
