FortreeCity_House3_Text_186624:: @ 8186624
	.string "포켓몬 도감 하니까\n"
	.string "기억나는 게 있어\p"
	.string "희귀한 돌을 찾고 있을 때\n"
	.string "성호라는 트레이너와 만났는데\l"
	.string "그 녀석의 포켓몬이 대단하더라고!\p"
	.string "희귀할 뿐 아니라\n"
	.string "무서울 정도로 단련되어 있었어!\p"
	.string "어쩌면 이 마을의\n"
	.string "체육관 관장보다 강할지도...$"

FortreeCity_House3_Text_186745:: @ 8186745
	.string "네가 가지고 있는 그건 뭐야?\p"
	.string "... ... ...\p"
	.string "오- 포켓몬 도감이라고 하는구나?\n"
	.string "굉장하다!$"
