FortreeCity_House4_Text_1867AF:: @ 81867AF //JP: 165873
	.string "포켓몬과 함께 있으면\n"
	.string "친한 친구들이 점점 늘어나게 돼...\p"
	.string "이렇게 전 세계는\n"
	.string "하나로 뭉쳐지는 거구나!\l"
	.string "너무 멋진 거 같아!$"

FortreeCity_House4_Text_186835:: @ 8186835
	.string "자!\n"
	.string "갔다 와! 새포켓몬$"

FortreeCity_House4_Text_18684E:: @ 818684E
	.string "헤헷 갈모매한테\n"
	.string "심부름 좀 시켰어$"

FortreeCity_House4_Text_186881:: @ 8186881
	.string "좋아!\n"
	.string "수고했어 갈모매!\p"
	.string "응?\n"
	.string "뭘 들고 있는 거야?\p"
	.string "멘탈허브네...\n"
	.string "오면서 주워 왔구나?\p"
	.string "그치만 난 트레이너가 아니니까\n"
	.string "필요 없어\l"
	.string "이거 너한테 줄게!$"

FortreeCity_House4_Text_186924:: @ 8186924
	.string "갈모매 덕분에\n"
	.string "멀리 있는 친구랑도\l"
	.string "친하게 지낼 수 있어!$"

FortreeCity_House4_Text_18695C:: @ 818695C
	.string "갈모매: 삐뾰-!$"
