FortreeCity_House1_Text_18568C:: @ 818568C
	.string "저기 있잖아 나\n"
	.string "지금 찾고 있는 포켓몬이 있어\p"
	.string "{STR_VAR_1}인데 혹시 가지고 있어?\n"
	.string "내 {STR_VAR_2}\e랑\l"
	.string "교환하지 않을래?$"

FortreeCity_House1_Text_1856F7:: @ 81856F7
	.string "고마워!!\p"
	.string "{STR_VAR_1} 많이 예뻐할 테니까\n"
	.string "너도 {STR_VAR_2} 많이 귀여워해 줘!$"

FortreeCity_House1_Text_185737:: @ 8185737
	.string "엥! 그 포켓몬\n"
	.string "{STR_VAR_1}\r 아니잖아!\l"
	.string "교환해줄 생각 없구나?$"

FortreeCity_House1_Text_18577F:: @ 818577F
	.string "아 그래? 그럼 어쩔 수 없지\n"
	.string "교환해 줄 마음이 생기면 다시 와 줘\l"
	.string "기다리고 있을게$"

FortreeCity_House1_Text_1857C7:: @ 81857C7
	.string "교환해줘서 고마워!\n"
	.string "정말 가지고 싶었던 포켓몬이었어\l"
	.string "소중하게 키울게!$"

FortreeCity_House1_Text_18582A:: @ 818582A
	.string "다른 사람과 포켓몬을\n"
	.string "교환하는 것...\p"
	.string "그건 자신들의 추억을\n"
	.string "교환하는 거나 마찬가지지$"

FortreeCity_House1_Text_185888:: @ 8185888
	.string "지그제구리: 크옹?$"
