FortreeCity_Gym_Text_18589C:: @ 818589C //JP: 164CAF
	.string "잘 있었나!!\n"
	.string "챔피언을 노리는 {PLAYER}!!\p"
	.string "검방울시티 체육관 관장 은송은\n"
	.string "비행타입의 포켓몬을 쓴다!\p"
	.string "이 회전문투성이인\n"
	.string "체육관 안에서\p"
	.string "그녀는 새로운 도전자가\n"
	.string "날아오르길 기다리고 있다!\p"
	.string "그럼 힘내라고-!!$"

FortreeCity_Gym_Text_185994:: @ 8185994
	.string "해냈구나! 넌 날아올랐어!$"

FortreeCity_Gym_Text_1859B9:: @ 81859B9
	.string "화려한 새포켓몬의 승부를\n"
	.string "보여주마!$"

FortreeCity_Gym_Text_1859EA:: @ 81859EA
	.string "너... 강하군...$"

FortreeCity_Gym_Text_185A02:: @ 8185A02
	.string "트레이너는 머리 회전도\n"
	.string "빠르지 않으면 안 된다!\p"
	.string "너는 체육관 관장이 있는 곳까지\n"
	.string "무사히 도착할 수 있을까?$"

FortreeCity_Gym_Text_185A7F:: @ 8185A7F
	.string "새포켓몬을 사랑하는 사람은\n"
	.string "이 체육관을 목표로 삼고 있지!\p"
	.string "검방울체육관의 일원으로서\n"
	.string "패배할 수는 없다!$"

FortreeCity_Gym_Text_185AEC:: @ 8185AEC
	.string "나에겐 너무 큰 짐이었나...!$"

FortreeCity_Gym_Text_185B18:: @ 8185B18
	.string "세계는 넓고\n"
	.string "강한 트레이너도 넘쳐나지\p"
	.string "나도 여기서 계속 수행해서\n"
	.string "강해지겠다!$"

FortreeCity_Gym_Text_185B8D:: @ 8185B8D
	.string "체육관 관장인 은송님이\n"
	.string "손쓰실 필요도 없어!\p"
	.string "네 상대는 나로 충분하다!$"

FortreeCity_Gym_Text_185BEB:: @ 8185BEB
	.string "은송님...! 제가 져버렸습니다...!$"

FortreeCity_Gym_Text_185C00:: @ 8185C00
	.string "은송님은 귀여운 데다가 강하시다...\n"
	.string "정말 최고의 관장이지!\p"
	.string "...좀 부끄럽군$"

FortreeCity_Gym_Text_185C45:: @ 8185C45
	.string "은송님의 가르침을 받은 나를!\n"
	.string "그렇게 간단히 쓰러뜨릴 수는 없을걸?$"

FortreeCity_Gym_Text_185C7C:: @ 8185C7C
	.string "쓰러졌다...$"

FortreeCity_Gym_Text_185C8C:: @ 8185C8C
	.string "검방울시티 사람들은\n"
	.string "은송님이 계셔서\l"
	.string "안심하고 지낼 수 있어$"

FortreeCity_Gym_Text_185CCB:: @ 8185CCB
	.string "저는 이 검방울시티 체육관에서\n"
	.string "관장을 맡고 있는 은송...\p"
	.string "새포켓몬과 마음을 나누며\n"
	.string "같이 드넓은 하늘을 날아...\p"
	.string "어떠한 괴로운 승부에서도\n"
	.string "우아하게 이겨 보이죠...\p"
	.string "자 저와 포켓몬이 만들어내는\n"
	.string "화려한 춤을 보세요!$"

FortreeCity_Gym_Text_185DBA:: @ 8185DBA
	.string "저보다 화려하게\n"
	.string "포켓몬을 다루는 사람은...\l"
	.string "처음 봤어요...\p"
	.string "그 실력을 인정하여\n"
	.string "이 체육관 배지를 드리겠습니다!$"

FortreeCity_Gym_Text_185E48:: @ 8185E48
	.string "{PLAYER}{K_EUNNEUN} 은송에게\n"
	.string "깃털배지를 받았다!$"

FortreeCity_Gym_Text_185E73:: @ 8185E73
	.string "깃털배지를 달고 있으면\n"
	.string "다른 사람에게 받은 포켓몬일지라도\l"
	.string "레벨 70까지의 포켓몬이라면\l"
	.string "명령에 잘 따라줍니다!\p"
	.string "비전기술 공중날기도\n"
	.string "사용할 수 있게 됩니다!\p"
	.string "그리고 이걸\n"
	.string "당신에게 선물하죠$"

FortreeCity_Gym_Text_185F4A:: @ 8185F4A
	.string "기술머신40의 내용물은\n"
	.string "제비반환!\p"
	.string "그 스피드는...\n"
	.string "어떤 포켓몬도\l"
	.string "피할 수 없겠지요!$"

FortreeCity_Gym_Text_185F98:: @ 8185F98
	.string "당신에게는 져버렸지만\p"
	.string "저는 앞으로도\n"
	.string "새포켓몬만을 사용할 거예요$"

FortreeCity_Gym_Text_185FD5:: @ 8185FD5
	.string "검방울시티 포켓몬체육관$"

FortreeCity_Gym_Text_185FEE:: @ 8185FEE
	.string "검방울시티 포켓몬체육관\p"
	.string "은송 인정 트레이너!\n"
	.string "{PLAYER}$"
