GraniteCave_StevensRoom_Text_194AE5:: @ 8194AE5
	.string "그 기계는...\n"
	.string "포켓내비?\p"
	.string "포켓내비를 가지고 있는\n"
	.string "트레이너들끼리 승부를 하면\l"
	.string "그 승부가 자동으로 기록되지\p"
	.string "이거 실례했네\n"
	.string "내 이름은 성호\p"
	.string "희귀한 돌에 흥미가 있어서\n"
	.string "이곳저곳을 여행하고 있어\p"
	.string "응?\n"
	.string "나한테 편지...?$"

GraniteCave_StevensRoom_Text_194BDD:: @ 8194BDD
	.string "성호: 응 고마워!\p"
	.string "일부러 전해주러 온 거구나\n"
	.string "뭔가 사례를 해 줘야겠는데\p"
	.string "...그래\n"
	.string "그럼 이 기술머신을 너한테 줄게\p"
	.string "강철날개라고 해서\n"
	.string "내가 좋아하는 기술이야$"

GraniteCave_StevensRoom_Text_194C8D:: @ 8194C8D
	.string "성호: 너와 네 포켓몬들...\p"
	.string "수행을 계속해 나가면\n"
	.string "언젠가 포켓몬리그의\l"
	.string "챔피언도 될 수 있을 거 같은...\p"
	.string "그런 생각이 드네 난$"

GraniteCave_StevensRoom_Text_194D43:: @ 8194D43
	.string "가방이 가득 찼구나...\n"
	.string "아쉽게 됐네$"
