JaggedPass_Text_195DAC:: @ 8195DAC
	.string "굴뚝산에 있는 울퉁불퉁 산길은\n"
	.string "완벽하게 내가 꿈에 그리던 산이야!\l"
	.string "울퉁불퉁! 너무 좋아서\l"
	.string "참을 수가 없어!$"

JaggedPass_Text_195E27:: @ 8195E27
	.string "져버려서 분하다!$"

JaggedPass_Text_195E3E:: @ 8195E3E
	.string "포켓몬 승부에서는 졌다...\p"
	.string "하지만 산을 사랑하는 마음만큼은\n"
	.string "나의 승리다!$"

JaggedPass_Text_195E9E:: @ 8195E9E
	.string "여긴 가벼운 마음으로\n"
	.string "오르면 안 되겠어\l"
	.string "피크닉엔 좀 어울리지 않아$"

JaggedPass_Text_195EDF:: @ 8195EDF
	.string "아-잉! 정말!\n"
	.string "발밑이 울퉁불퉁하니까...$"

JaggedPass_Text_195F04:: @ 8195F04
	.string "이렇게 울퉁불퉁한 곳을\n"
	.string "자전거로 잘 올라가는\l"
	.string "사람도 있어!$"

JaggedPass_Text_195F58:: @ 8195F58
	.string "어떤 길이라도 피크닉은 즐거워!\n"
	.string "포켓몬도 같이 있고 말이야!$"

JaggedPass_Text_195F8C:: @ 8195F8C
	.string "발밑이 울퉁불퉁해서\n"
	.string "져버린 거야!$"

JaggedPass_Text_195FB9:: @ 8195FB9
	.string "져버린 건 후딱 잊어버리고\n"
	.string "이 울퉁불퉁한 길을 마음껏 즐겨야지!$"

JaggedPass_Text_195FF2:: @ 8195FF2
	.string "이 울퉁불퉁 산길은\n"
	.string "걷기가 무척 힘들지!\p"
	.string "포켓몬을 단련시키기에\n"
	.string "딱 좋은 곳이다!$"

JaggedPass_Text_196032:: @ 8196032
	.string "발밑을 신경 쓰고 있는 사이에\n"
	.string "끝나버린 것 같군...$"

JaggedPass_Text_196077:: @ 8196077
	.string "나도 더트자전거가 있으면\n"
	.string "턱을 뛰어넘을 수 있을 텐데...$"

JaggedPass_Text_1960AA:: @ 81960AA
	.string "울퉁불퉁한 길에 익숙해져서\n"
	.string "요즘엔 그냥 노래를 흥얼거리면서\l"
	.string "올라갈 정도야!$"

JaggedPass_Text_1960E2:: @ 81960E2
	.string "울퉁불퉁하니까\n"
	.string "역시 배틀하기 힘들다...$"

JaggedPass_Text_196118:: @ 8196118
	.string "나도 보라시티에 있는 카제노님에게\n"
	.string "더트자전거를 달라고 해볼까?$"
