LavaridgeTown_PokemonCenter_1F_Text_176E92:: @ 8176E92
	.string "포켓몬이랑 같이 걷다 보면\n"
	.string "왠지 포켓몬이 더\l"
	.string "잘 따라주는 것 같은\l"
	.string "느낌이 든단 말이지$"

LavaridgeTown_PokemonCenter_1F_Text_176F08:: @ 8176F08
	.string "포켓몬한테 빨강포켓몬스넥을 줬더니\n"
	.string "왠지 모르게 근사해졌어!\p"
	.string "나도 빨강포켓몬스넥 먹어볼까?$"

LavaridgeTown_PokemonCenter_1F_Text_176F7A:: @ 8176F7A
	.string "허허허! 젊구먼\n"
	.string "여기서부터 온천에 갈 수 있단다!\p"
	.string "포켓몬이 여기서 쉰다면\n"
	.string "사람도 온천에서 푹 쉬어야지!$"
