LavaridgeTown_Gym_1F_Text_176312:: @ 8176312
	.string "잘 있었나!!\n"
	.string "챔피언을 목표로 하는 {PLAYER}!!\p"
	.string "용암마을 체육관 관장 민지는\n"
	.string "불꽃타입 포켓몬 사용자다!\p"
	.string "포켓몬에 대한 정열은\n"
	.string "화산보다 격렬하고 뜨겁다!\p"
	.string "잘못해서 가까이라도 가면\n"
	.string "화상 입으니 물로 식히면서\l"
	.string "힘내라-구!!$"

LavaridgeTown_Gym_1F_Text_17640C:: @ 817640C
	.string "아이고- 뜨거운 배틀이었다!$"

LavaridgeTown_Gym_1F_Text_176432:: @ 8176432
	.string "아뜨뜨뜨뜨뜨거!\n"
	.string "으아-! 뜨거웠어-!$"

LavaridgeTown_Gym_1F_Text_17644F:: @ 817644F
	.string "눈에 땀방울이 들어갔어...$"

LavaridgeTown_Gym_1F_Text_176472:: @ 8176472
	.string "목욕은 혈액순환을 도우니까\n"
	.string "관절 통증에 효과적이야!$"

LavaridgeTown_Gym_1F_Text_1764D1:: @ 81764D1
	.string "내 소중한 스트레스 해소 시간을\n"
	.string "방해하지 마-!$"

LavaridgeTown_Gym_1F_Text_176516:: @ 8176516
	.string "에잇! 민지님에게 져버려랏-!$"

LavaridgeTown_Gym_1F_Text_176537:: @ 8176537
	.string "하아... 후...\p"
	.string "목욕을 오래 하고 있으면\n"
	.string "꽤 피곤해져...$"

LavaridgeTown_Gym_1F_Text_17658D:: @ 817658D
	.string "너도 이제 슬슬 지친 것 같군?\n"
	.string "목욕하면서 한숨 쉬었다 가고 싶지?\p"
	.string "하지만 기력을 유지하는 것도\n"
	.string "트레이너에게 필요한 능력 중 하나다$"

LavaridgeTown_Gym_1F_Text_17663F:: @ 817663F
	.string "불장난이 부상의 원인인 건가...$"

LavaridgeTown_Gym_1F_Text_176660:: @ 8176660
	.string "네 실력은 진짜다...\n"
	.string "하지만 체육관 관장인 민지님은\l"
	.string "더 강해!\p"
	.string "방심하면 뜨거운 맛을 보게 될 거다!$"

LavaridgeTown_Gym_1F_Text_1766D2:: @ 81766D2
	.string "너의 포켓몬은\n"
	.string "200도의 열기를 이겨낼 수 있는가?!$"

LavaridgeTown_Gym_1F_Text_1766FE:: @ 81766FE
	.string "다 태워버렸어야 했거늘...$"

LavaridgeTown_Gym_1F_Text_17671D:: @ 817671D
	.string "200도의 열기라는 건\n"
	.string "용암의 온도!\p"
	.string "너의 포켓몬은 나를 이겼으니까\n"
	.string "용암 속에서도 문제없겠군!$"

LavaridgeTown_Gym_1F_Text_176784:: @ 8176784
	.string "자-!\n"
	.string "그럼 상대해 줄게!$"

LavaridgeTown_Gym_1F_Text_1767A6:: @ 81767A6
	.string "어떻게 그렇게 강할 수가 있지?$"

LavaridgeTown_Gym_1F_Text_1767C1:: @ 81767C1
	.string "나도 민지님처럼\n"
	.string "아름답고 강한 트레이너가 될 거야!$"

LavaridgeTown_Gym_1F_Text_176801:: @ 8176801
	.string "어서 오세요 ...가 아니라\p"
	.string "여기까지 잘도 왔구나!\p"
	.string "전 여기 체육관 관장을\n"
	.string "맡게 된 ...이 아니라\p"
	.string "체육관 관장을 맡은 민지다!\p"
	.string "끙...\n"
	.string "체육관 관장 된 지 얼마 안 됐다고\l"
	.string "방심하지 말라고!\p"
	.string "할아버지에게 물려받은 재능과\n"
	.string "이 땅에서 갈고닦은 핫한 기술\l"
	.string "너에게 보여주겠어!$"

LavaridgeTown_Gym_1F_Text_176960:: @ 8176960
	.string "크윽...\n"
	.string "어깨에 힘이 들어가고 말았어...\p"
	.string "나...\n"
	.string "체육관 관장 된 지 얼마 안 됐다고\l"
	.string "좀 무리한 걸까...\p"
	.string "역시 나는 나답게 싸워야지\n"
	.string "그게 아니라면 함께 싸워주는\l"
	.string "포켓몬도 힘들 거야!\p"
	.string "그걸 가르쳐준\n"
	.string "당신에게 이걸 줄게!$"

LavaridgeTown_Gym_1F_Text_176A62:: @ 8176A62
	.string "{PLAYER}\s 민지로부터\n"
	.string "히트배지를 받았다!$"

LavaridgeTown_Gym_1F_Text_176A8C:: @ 8176A8C
	.string "히트배지가 있으면\n"
	.string "다른 사람에게 받은 포켓몬이라도\l"
	.string "레벨50까지는\l"
	.string "말을 잘 들어줘!\p"
	.string "그리고 비전기술 괴력을\n"
	.string "사용할 수 있게 돼!\p"
	.string "이건 감사의 마음\n"
	.string "사양하지 말고 받아줘!$"

LavaridgeTown_Gym_1F_Text_176B8F:: @ 8176B8F
	.string "기술머신50에는\n"
	.string "오버히트가 들어 있어!\p"
	.string "그 기술은 상대에게\n"
	.string "큰 데미지를 줘!\p"
	.string "하지만 특수공격이\n"
	.string "크게 떨어지니까\l"
	.string "긴 승부에는 안 맞을지도...$"

LavaridgeTown_Gym_1F_Text_176C4A:: @ 8176C4A
	.string "당신의 실력\n"
	.string "누군가를 떠올리게 하네...\p"
	.string "그래! 등화도시의 체육관 관장\n"
	.string "종길님과 닮았어!$"

LavaridgeTown_Gym_1F_Text_176CAF:: @ 8176CAF
	.string "용암마을 포켓몬체육관$"

LavaridgeTown_Gym_1F_Text_176CCA:: @ 8176CCA
	.string "용암마을 포켓몬체육관\p"
	.string "민지 인정 트레이너!\n"
	.string "{PLAYER}$"
