LavaridgeTown_Text_16BDA4:: @ 816BDA4
	.string "봄이: {PLAYER}! 오랜만이야!\p"
	.string "어라? 내가 온천에\n"
	.string "들어간 사이에\l"
	.string "용암마을의 체육관 배지를\l"
	.string "손에 넣었구나!\p"
	.string "꽤 포켓몬을 모으고 있달까\n"
	.string "키우고 있구나!\p"
	.string "그럼 이걸 줘도\n"
	.string "괜찮겠네$"

LavaridgeTown_Text_16BE7D:: @ 816BE7D
	.string "봄이: 그 고고고글이 있으면\n"
	.string "111번 도로에 있는 사막에도\l"
	.string "갈 수 있게 돼!\p"
	.string "그건 그렇고 {PLAYER}\n"
	.string "포켓몬체육관에 도전이라니...\p"
	.string "나한테 지고 싶지 않아서\n"
	.string "열심히 하고 있구나!\p"
	.string "그럼 나 등화도시에서 {PLAYER}의\n"
	.string "아빠에게 도전해 볼까나?\p"
	.string "{PLAYER} 그럼 다음에 보자!$"

LavaridgeTown_Text_16BF92:: @ 816BF92
	.string "휘웅: {PLAYER} 오랜만이네\n"
	.string "상태는 어때?\p"
	.string "음...\n"
	.string "배지를 제법 모았구나\p"
	.string "그럼\n"
	.string "이걸 줄까나$"

LavaridgeTown_Text_16C020:: @ 816C020
	.string "휘웅: 그걸 가지고 있으면\n"
	.string "111번 도로에 있는 사막에도\l"
	.string "들어갈 수 있어\p"
	.string "사막에서밖에 만날 수 없는\n"
	.string "포켓몬도 있을 테니까\l"
	.string "괜찮다면 가보지 그래...?\p"
	.string "나는...\n"
	.string "등화도시의 체육관 관장 종길님에게\l"
	.string "도전해 볼까나...\p"
	.string "{PLAYER}의 아빠\n"
	.string "{PLAYER}{K_WAGWA} 달리 강해 보이니까\p"
	.string "그럼!$"

LavaridgeTown_Text_16C174:: @ 816C174
	.string "알을 부화시키려고\n"
	.string "모래찜질을 시켜서\l"
	.string "따뜻하게 해주고 있었는데\p"
	.string "그것만으로는\n"
	.string "안 되는 모양이더구먼...\p"
	.string "뭔가 건강한 포켓몬이랑 같이\n"
	.string "데리고 걸어 다니는 게\l"
	.string "좋다고 하던데...\p"
	.string "자네 트레이너지?\n"
	.string "게다가 건강한 포켓몬도\l"
	.string "데리고 있어\p"
	.string "어떤가?\n"
	.string "알을 부화시켜 보지 않겠나?$"

LavaridgeTown_Text_16C2B6:: @ 816C2B6
	.string "알이랑 같이\n"
	.string "많-이 걷고 와줘라!$"

LavaridgeTown_Text_16C2EA:: @ 816C2EA
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "알을 받았다!$"

LavaridgeTown_Text_16C2FF:: @ 816C2FF
	.string "어라? 포켓몬이 가득하구나\p"
	.string "알을 데리고 갈 수 있게 되면\n"
	.string "또 와주거라$"

LavaridgeTown_Text_16C33C:: @ 816C33C
	.string "그러냐...\p"
	.string "뭐 알을 부화시키고 싶어지면\n"
	.string "그때 또 와주거라$"

LavaridgeTown_Text_16C398:: @ 816C398
	.string "포켓몬알은\n"
	.string "가끔 키우미집에서 발견된다고...\p"
	.string "그런 소문을 들은 적이 있구나$"

LavaridgeTown_Text_16C3FD:: @ 816C3FD
	.string "퍼도 퍼도 따뜻한 물이 나와\n"
	.string "포트도 아니면서 따뜻한 물이 나와\p"
	.string "...이거 참 신기하지 않나?\p"
	.string "화산이 가까이 있는 곳에서는\n"
	.string "용암의 열로 지하수가\l"
	.string "데워지게 되거든!$"

LavaridgeTown_Text_16C4DB:: @ 816C4DB
	.string "이렇게 모래에 묻혀 있으면\n"
	.string "하아아...\p"
	.string "따뜻해서 좋은 기분...\p"
	.string "...음? 아얏!\p"
	.string "포켓몬한테 엉덩이를 물렸다!$"

LavaridgeTown_Text_16C54E:: @ 816C54E
	.string "응? 너\n"
	.string "온천 좋아하나 보지?\p"
	.string "아직 젊은데 특이하구먼...$"

LavaridgeTown_Text_16C59B:: @ 816C59B
	.string "나 민지님 같은\n"
	.string "멋있고 강한 체육관 관장이\l"
	.string "되기 위해서\l"
	.string "매일 온천에 들어가고 있어!$"

LavaridgeTown_Text_16C603:: @ 816C603
	.string "온천에 포켓몬을 넣으면\n"
	.string "전기온천이나 거품온천 또는\l"
	.string "용암온천이 돼서 엄청날 거 같아$"

LavaridgeTown_Text_16C694:: @ 816C694
	.string "이 온천은...\p"
	.string "신경통과 근육통 그리고\n"
	.string "연애운이랑 재물운에도\l"
	.string "효과적이라고 하더라고...$"

LavaridgeTown_Text_16C72F:: @ 816C72F
	.string "여기는 용암마을\p"
	.string "포켓몬센터와 온천이 좋은 곳$"

LavaridgeTown_Text_16C77C:: @ 816C77C
	.string "용암마을 포켓몬체육관\n"
	.string "관장 민지\l"
	.string "화상 입을 정도로 열정적인 사람$"

LavaridgeTown_Text_16C7CF:: @ 816C7CF
	.string "“포켓몬 한방약국”\n"
	.string "몸에 좋은 약이 입에 쓰다!$"
