LilycoveCity_DepartmentStoreRooftop_Text_18C61F:: @ 818C61F //JP: 16ADDB
	.string "득템 가게...\n"
	.string "언제 열 건지 정하지 않은 걸까?\p"
	.string "TV를 봐도\n"
	.string "전혀 광고가 없어$"

LilycoveCity_DepartmentStoreRooftop_Text_18C685:: @ 818C685
	.string "기다리고 기다리던 득템 가게!\n"
	.string "이곳에서만 살 수 있는 것들이 잔뜩!\l"
	.string "좋아 마음껏 사야지!$"

LilycoveCity_DepartmentStoreRooftop_Text_18C70E:: @ 818C70E
	.string "아아... 목이 말라...$"

LilycoveCity_DepartmentStoreRooftop_Text_18C72B:: @ 818C72B
	.string "자동 판매기가 있다!\n"
	.string "마시고 싶은 음료수는...$"

LilycoveCity_DepartmentStoreRooftop_Text_18C75F:: @ 818C75F
	.string "덜컹!\p"
	.string "{STR_VAR_1}{K_IGA} 나왔다!$"

LilycoveCity_DepartmentStoreRooftop_Text_18C780:: @ 818C780
	.string "덜컹!\p"
	.string "당첨이다! 하나 더\n"
	.string "{STR_VAR_1}{K_IGA} 나왔다!$"

LilycoveCity_DepartmentStoreRooftop_Text_18C7AF:: @ 818C7AF
	.string "돈이 모자라!$"

LilycoveCity_DepartmentStoreRooftop_Text_18C7C3:: @ 818C7C3
	.string "...역시 그만뒀다!$"
