LilycoveCity_PokemonCenter_1F_Text_189FC9:: @ 8189FC9 //JP: 1687AB
	.string "이 세상에는\n"
	.string "포켓몬이 과연 얼마나 있는 걸까?\p"
	.string "언젠가 바다를 넘어서\n"
	.string "먼 나라 사람과\l"
	.string "포켓몬 교환하고 싶다!$"

LilycoveCity_PokemonCenter_1F_Text_18A048:: @ 818A048
	.string "최근 사람들의 포켓몬을 뺏거나\n"
	.string "운석을 훔치거나 하는\l"
	.string "골치 아픈 놈들이 있다고 하더라고!$"

LilycoveCity_PokemonCenter_1F_Text_18A0A1:: @ 818A0A1
	.string "사람들의 포켓몬을 뺏거나\n"
	.string "운석을 훔치거나 했던\l"
	.string "골치 아픈 놈들...\p"
	.string "요즘 안 보이더라$"

UnknownString_818A10A: @ 818A10A
	.string "플러스파워를 포켓몬에게 써서\n"
	.string "공격력을 높이는 거야!\p"
	.string "이걸로 승리는 확실해!$"

UnknownString_818A168: @ 818A168
	.string "조금 비쌀지도 모르지만\n"
	.string "만병통치약은 편리해\p"
	.string "포켓몬의 어떤 이상도\n"
	.string "이걸로 고칠 수 있으니까!$"
