LilycoveCity_CoveLilyMotel_2F_Text_186FE7:: @ 8186FE7 //JP: 165EDD
	.string "저는 게임 디자이너입니다\p"
	.string "헤에-\n"
	.string "포켓몬 도감 채우고 계시는 군요?\p"
	.string "전부 모으는 건\n"
	.string "어렵겠지만 힘내세요!\p"
	.string "혹시 전부 채우신다면 알려주세요!$"
	// ぼくは ゲ-ム デザイナ-ｐ
	// へ-ｎ
	// ポケモンずかん あつめてるの?ｐ
	// ぜんぶ あつめるのｎ
	// たいへん だけど がんばって!ｐ
	// もし ぜんぶ あつめたら おしえてよ!

LilycoveCity_CoveLilyMotel_2F_Text_18708F:: @ 818708F
	.string "대단하네요-!\n"
	.string "이야- 당신 대단해요!!\p"
	.string "이 포켓몬 도감\n"
	.string "전부 채워져 있네요!\l"
	.string "그만큼 포켓몬을 사랑하는 거군요!\p"
	.string "감동했습니다!\n"
	.string "당신을 표창하게 해 주세요!$"
	// すごいな-!ｎ
	// いや- すごいよ きみ!!ｐ
	// この ポケモンずかんｎ
	// ぜんぶ あつまって いるんだね!ｌ
	// それだけ ポケモンを あいしてるんだね!ｐ
	// かんどう しました!ｎ
	// きみを ひょうしょう させてもらいますね!

LilycoveCity_CoveLilyMotel_2F_Text_187149:: @ 8187149
	.string "이 몸?\p"
	.string "프로그래머라고! 이쪽의\n"
	.string "슬롯은 왠지 즐겁네!$"
	// おれさま?ｐ
	// プログラマ-だよ! こっちのｎ
	// スロットは どんなのか たのしみだな!

LilycoveCity_CoveLilyMotel_2F_Text_18719E:: @ 818719E
	.string "나는 그래픽 담당!\n"
	.string "호연의 포켓몬은 재미있지$"
	// おれ グラフィッカ-!ｎ
	// ホウエンの ポケモンは おもしろいね

LilycoveCity_CoveLilyMotel_2F_Text_1871DF:: @ 81871DF
	.string "튜브걸 너무 귀엽지 않아?\n"
	.string "그 튜브걸과 승부할 수 있다니...\p"
	.string "우와-! 정말 최고야!\p"
	.string "쌍둥이도 무지 귀엽지!\n"
	.string "그런 쌍둥이와 2대2로\l"
	.string "승부할 수 있다니...\p"
	.string "이야-! 정말 최고야!$"
	// うきわガ-ル かわいい でしょ!ｎ
	// うきわガ-ルと しょうぶ なんて……ｐ
	// く-! たまらん-!ｐ
	// ふたごちゃん かわいい でしょ!ｎ
	// ふたごちゃんと 2たい2 なんて……ｐ
	// く-! たまらん-!

LilycoveCity_CoveLilyMotel_2F_Text_18729A:: @ 818729A
	.string "바닷바람이 상쾌해서\n"
	.string "기분이 좋아요!$"
	// なんだか しおかぜが こころを くすぐってｎ
	// きもち いいですね!

LilycoveCity_CoveLilyMotel_2F_Text_1872D4:: @ 81872D4
	.string "언제 어디서든 대전이나 승부를\n"
	.string "받을지 모르니까\p"
	.string "게임보이 어드밴스는\n"
	.string "놓고 나갈 수 없지!$"
	// いつ どこで たいせんや しょうぶをｎ
	// いどまれるか わからないからなｌ
	// ゲ-ムボ-イ アドバンスは てばなせないよ!
