LilycoveCity_MoveDeletersHouse_Text_18B622:: @ 818B622 //JP: 169BC6
	.string "그러니까...\n"
	.string "그렇지 나는 깜빡할아버지\p"
	.string "포켓몬의 기술을\n"
	.string "잊게 만들 수 있다네!\p"
	.string "기술을 잊게 할 텐가?$"
	// え-と……ｎ
	// そうじゃ わし わすれじいさんｐ
	// ポケモンの わざをｎ
	// わすれさせる ことが できるんじゃ!ｐ
	// わざを わすれ させるかね?

LilycoveCity_MoveDeletersHouse_Text_18B68C:: @ 818B68C
	.string "어느 포켓몬으로 할 겐가?$"
	// どの ポケモンに するんじゃ?

LilycoveCity_MoveDeletersHouse_Text_18B6B0:: @ 818B6B0
	.string "어느 기술을\n"
	.string "잊게 하려는 게냐?$"
	// どの わざをｎ
	// わすれ させるんじゃ?

LilycoveCity_MoveDeletersHouse_Text_18B6D0:: @ 818B6D0
	.string "{STR_VAR_1}{K_EUNNEUN} 기술을 하나밖에\n"
	.string "가지지 않았는데?$"
	// §いは わざを 1つしかｎ
	// もってない ようじゃ……

LilycoveCity_MoveDeletersHouse_Text_18B6F2:: @ 818B6F2
	.string "흠!\n"
	.string "{STR_VAR_1}의 {STR_VAR_2} 말이군?$"
	// むむ! ｎ
	// §いの §うじゃな?

LilycoveCity_MoveDeletersHouse_Text_18B71E:: @ 818B71E
	.string "대성공이군!\p"
	.string "{STR_VAR_1}{K_EUNNEUN} {STR_VAR_2}{K_EULREUL}\n"
	.string "잊어버린 것 같구먼!$"
	// だいせいこう じゃ!ｐ
	// §いは §うをｎ
	// わすれた ようじゃ!

LilycoveCity_MoveDeletersHouse_Text_18B757:: @ 818B757
	.string "잊게 하고 싶은 기술이 있다면\n"
	.string "또 오게!$"
	// わすれさせたい わざが あったらｎ
	// また くるのじゃぞ!

LilycoveCity_MoveDeletersHouse_Text_18B78C:: @ 818B78C
	.string "뭐야!? 알은\n"
	.string "아무런 기술도\l"
	.string "익히지 않은 것 같은데...?$"
	// なぬ!? タマゴはｎ
	// わざを おぼえていない ようじゃが……?
