LilycoveCity_PokemonTrainerFanClub_Text_18A1D6:: @ 818A1D6 //JP: 168E12
	.string "아!\n"
	.string "{PLAYER}{K_I}다!!$"
	// あ!ｎ
	// §あだ!!

LilycoveCity_PokemonTrainerFanClub_Text_18A1E8:: @ 818A1E8
	.string "들었어!\n"
	.string "너 강하다고 말야\p"
	.string "여기에서는 모두\n"
	.string "누가 가장 강한 트레이너인가\l"
	.string "이야기하고 있는데\p"
	.string "나 너에 대한 소문을 들어서\n"
	.string "네 팬이 되기로 했어!\p"
	.string "앞으로도 강한 트레이너와\n"
	.string "팍팍 싸워서\p"
	.string "우리들에게 뜨거운\n"
	.string "배틀을 보여줘!\p"
	.string "그러면 분명 모두\n"
	.string "너를 다시 보게 될 거야\p"
	.string "그럼 기대하고 있을게!\n"
	.string "{PLAYER}!!$"
	// きいたよ!ｎ
	// きみ つよいんだってなｐ
	// ここでは みんなｎ
	// だれが いちばん つよい トレ-ナ-かｌ
	// はなしを してるんだけどｐ
	// おれ きみの うわさを きいてｎ
	// きみの ファンに なることに したよ!ｐ
	// これからも つよい トレ-ナ-とｎ
	// バンバン たたかってｐ
	// おれたちに あついｎ
	// たたかいを みせてくれよ!ｐ
	// そうすれば きっと みんなもｎ
	// きみの ことを みなおすと おもうんだｐ
	// じゃあ きたい してるよ!ｎ
	// §あ!!

LilycoveCity_PokemonTrainerFanClub_Text_18A36A:: @ 818A36A
	.string "오 {PLAYER}!!\n"
	.string "응원하고 있어!!$"
	// おう §あ!!ｎ
	// おうえん してるぞ!!

LilycoveCity_PokemonTrainerFanClub_Text_18A391:: @ 818A391
	.string "저 녀석들은 몰라\n"
	.string "네가 가장 최고라는 걸 말야!\p"
	.string "그렇지 {PLAYER}!\n"
	.string "근성을 보여줘!$"
	// あいつらは しらないんだｎ
	// きみが いちばん すごいって ことをさ!ｐ
	// そうだろ §あ!ｎ
	// こんじょう みせてくれ!

LilycoveCity_PokemonTrainerFanClub_Text_18A400:: @ 818A400
	.string "너에게는 미안하지만 지금 가장\n"
	.string "주목받는 트레이너는\l"
	.string "{STR_VAR_1}{K_I}라고!\p"
	.string "그 강함은\n"
	.string "보통이 아니지$"
	// きみには わるいけど いま いちばんｎ
	// ちゅうもくの トレ-ナ-はｌ
	// まちがいなく §い だね!ｐ
	// あの つよさはｎ
	// だたものじゃ ないよ

LilycoveCity_PokemonTrainerFanClub_Text_18A48D:: @ 818A48D
	.string "젠장- 지금은 {STR_VAR_1}{K_IGA}\n"
	.string "가장 강하다고 말하는데도\p"
	.string "아무도 들어주지 않아...$"
	// くそ- いまは §いがｎ
	// いちばん つよいって いってるのにｐ
	// だれも きいて くれない……

LilycoveCity_PokemonTrainerFanClub_Text_18A4EA:: @ 818A4EA
	.string "최근 차례차례 체육관 관장을\n"
	.string "쓰러뜨리고 있다고 하는\p"
	.string "강한 트레이너가\n"
	.string "나타난 것 같아\p"
	.string "너 뭐 아는 거 없어?$"
	// さいきん つぎつぎと ジムリ-ダ-をｎ
	// たおしている っていうｐ
	// つよい トレ-ナ-がｎ
	// あらわれた らしいんだｐ
	// きみ しらないかい?

LilycoveCity_PokemonTrainerFanClub_Text_18A584:: @ 818A584
	.string "아!\n"
	.string "{PLAYER}!!\p"
	.string "힘내\n"
	.string "응원하고 있으니까!$"
	// あ!ｎ
	// §あ!!ｐ
	// がんばってねｎ
	// おうえん してるから!

LilycoveCity_PokemonTrainerFanClub_Text_18A5AC:: @ 818A5AC
	.string "철구님...\p"
	.string "아!\n"
	.string "아냐 아냐!\p"
	.string "나는 어디까지나 당신의\n"
	.string "팬이니까!\p"
	.string "그러니까 나를 위해\n"
	.string "힘내줘!$"
	// トウキさま……ｐ
	// あ!ｎ
	// ちがう ちがう!ｐ
	// わたしは あくまで あなたのｎ
	// ファン なんだからね!ｐ
	// だから あたしの ためにｎ
	// がんばってよ!

LilycoveCity_PokemonTrainerFanClub_Text_18A629:: @ 818A629
	.string "역시 나는 철구님만을\n"
	.string "좋아할 수밖에 없어-$"
	// やっぱり わたしは トウキさま しかｎ
	// すきに なれない のよね-

LilycoveCity_PokemonTrainerFanClub_Text_18A65B:: @ 818A65B
	.string "아무도 철구님의\n"
	.string "매력을 알아주지 않아...\p"
	.string "좋아!\p"
	.string "나 혼자서라도 철구님을\n"
	.string "응원해 나갈 테니까!$"
	// だれも トウキさまのｎ
	// みりょくを わかって くれないの……ｐ
	// いいわ!ｐ
	// わたし ひとりでも トウキさまの ことをｎ
	// おうえん しつづけるから!

LilycoveCity_PokemonTrainerFanClub_Text_18A6D4:: @ 818A6D4
	.string "내가 가장 좋아하는\n"
	.string "트레이너는 누가 뭐래도\p"
	.string "무로마을의 체육관 관장\n"
	.string "철구님이야!$"
	// わたしの いちばん すきなｎ
	// トレ-ナ-は なんと いってもｐ
	// ムロの ジムリ-ダ-ｎ
	// トウキさまよ!

LilycoveCity_PokemonTrainerFanClub_Text_18A71E:: @ 818A71E
	.string "너는 드디어 모든 면에서\n"
	.string "너의 아버지를 넘어섰구나!\p"
	.string "이 내가 말하는 거니까\n"
	.string "틀림없다!$"
	// きみは ついに あらゆる めんでｎ
	// きみの おとうさんを こえたな!ｐ
	// この わしが いって いるんだからｎ
	// まちがいない!

LilycoveCity_PokemonTrainerFanClub_Text_18A789:: @ 818A789
	.string "네 아버지는 위기가 되어도\n"
	.string "포기하지 않고 싸우고 있었다...\p"
	.string "나는 알고 있다네\p"
	.string "너는 아무리 져도 결코\n"
	.string "포기하지 않을 것을!\l"
	.string "그러니 힘내주게!$"
	// きみの おとうさんは ピンチに なってもｎ
	// あきらめずに たたかって いたよ……ｐ
	// わしは しっているよｐ
	// きみは いくら まけても けっしてｎ
	// あきらめない という ことを!ｌ
	// だから がんばってくれ!

LilycoveCity_PokemonTrainerFanClub_Text_18A814:: @ 818A814
	.string "너보다 종길씨 쪽이\n"
	.string "더 강하고 근사하게\l"
	.string "볼 만한 배틀을 했었다!\p"
	.string "아무리 네가 강하다고\n"
	.string "말해진다 한들\p"
	.string "네 아버지와 비교하면\n"
	.string "아직이구나$"
	// きみより センリさんの ほうがｎ
	// もっと つよくて かっこよくｌ
	// みごたえの ある たたかいを していたぞ!ｐ
	// いくら きみが つよいとｎ
	// いわれて いてもｐ
	// きみの おとうさんに くらべたらｎ
	// まだまだ だな 

LilycoveCity_PokemonTrainerFanClub_Text_18A8C4:: @ 818A8C4
	.string "너도 종길씨와 같은 분위기\n"
	.string "라고 해야 하나 박력 있구나\p"
	.string "하지만 종길씨와는 결정적으로\n"
	.string "다른 것이 있다!\p"
	.string "...그건 내가 말할 수 없다\n"
	.string "스스로 찾아보거라$"
	// きみも センリさんと おなじ ふんいきｎ
	// というか はくりょくが でてきたねｐ
	// しかし センリさん とは けっていてきにｎ
	// ちがう ものが ある!ｐ
	// ……それは わたしからは いえないｎ
	// じぶんで さがして みるんだな

LilycoveCity_PokemonTrainerFanClub_Text_18A984:: @ 818A984
	.string "여기 있는 모두는\n"
	.string "포켓몬 승부를 좋아해서 말야\p"
	.string "누가 가장 강한 트레이너인지\n"
	.string "이야기하고 있어!\p"
	.string "너도 유명해진다면\n"
	.string "모두 팬이 될지도 몰라!$"
	// ここにいる みんなはｎ
	// ポケモンしょうぶが だいすきでねｐ
	// だれが いちばん つよい トレ-ナ-かｎ
	// はなしを して いるんだ!ｐ
	// きみも ゆうめいに なればｎ
	// みんな ファンに なるかもな!

LilycoveCity_PokemonTrainerFanClub_Text_18AA39:: @ 818AA39
	.string "우와-! {PLAYER}{K_I}다-\n"
	.string "나 처음 봐-!\p"
	.string "악수해줘-\n"
	.string "악수!$"
	// うわ-! §あだ-ｎ
	// ほんもの だ-ｐ
	// あくしゅ して-ｎ
	// あくしゅ!

LilycoveCity_PokemonTrainerFanClub_Text_18AA83:: @ 818AA83
	.string "...나 언제까지나 {PLAYER}{K_EULREUL}\n"
	.string "응원할 거야!\p"
	.string "나 더 이상 {PLAYER}의 지는\n"
	.string "모습 보고 싶지 않아\p"
	.string "{PLAYER} 사실은\n"
	.string "강한걸 그치!$"
	// ……わたし いつまでも §あの ことｎ
	// おうえん する からね!ｐ
	// わたし もう §あの まけるｎ
	// とこなんて みたくないよｐ
	// §あ ほんとはｎ
	// つよいんだ もんね!

LilycoveCity_PokemonTrainerFanClub_Text_18AB0A:: @ 818AB0A
	.string "{STR_VAR_1}씨는 멋있어...\p"
	.string "저기 모두도\n"
	.string "그렇다고 생각하지-?$"
	// §いさん って かっこいい……ｐ
	// ねえ みんなもｎ
	// そう おもうでしょ-?

LilycoveCity_PokemonTrainerFanClub_Text_18AB41:: @ 818AB41
	.string "{STR_VAR_1}씨는 정말\n"
	.string "멋지지...\p"
	.string "나 혼자가 되어도\n"
	.string "쭉 응원할 거야-!$"
	// §いさん って ほんとうにｎ
	// かっこいい よねぇ……ｐ
	// わたし ひとりに なってもｎ
	// ずうっと おうえん するんだ-!

LilycoveCity_PokemonTrainerFanClub_Text_18ABAE:: @ 818ABAE
	.string "나 말야\n"
	.string "좋아하는 트레이너는\p"
	.string "근사하고\p"
	.string "강하고\p"
	.string "그리고 상냥한\p"
	.string "그런 트레이너가 좋아...$"
	// わたしのねｎ
	// すきな トレ-ナ-はｐ
	// かっこよくてｐ
	// つよくてｐ
	// それでいて やさしいｐ
	// そんな トレ-ナ-が いいなぁ……

LilycoveCity_PokemonTrainerFanClub_Text_18AC15:: @ 818AC15
	.string "아! {PLAYER}{K_I}다-!\n"
	.string "굉장해-!\p"
	.string "나도 자라면\n"
	.string "{PLAYER} 같이 강해지고 싶어!$"
	// あ! §あだ-!ｎ
	// すげ-!ｐ
	// ぼくも おおきく なったらｎ
	// §あ みたいに つよく なりたいよ!

LilycoveCity_PokemonTrainerFanClub_Text_18AC5E:: @ 818AC5E
	.string "...\n"
	.string "나 혼자가 되어도\p"
	.string "쭉 {PLAYER}{K_EULREUL}\n"
	.string "응원할 거야!\p"
	.string "그야 {PLAYER}{K_EULREUL}\n"
	.string "믿고 있으니까!$"
	// ……ｎ
	// ぼく ひとりに なったってｐ
	// ずっと §あの ことをｎ
	// おうえん するよ!ｐ
	// だって §あの ことｎ
	// しんじてるもん!

LilycoveCity_PokemonTrainerFanClub_Text_18ACC7:: @ 818ACC7
	.string "{STR_VAR_1}{K_EUNNEUN} 근사하지-\n"
	.string "나하고 악수해주면 좋겠다-$"
	// §いって かっこいいよね-ｎ
	// ぼく あくしゅ してほしいな-

LilycoveCity_PokemonTrainerFanClub_Text_18AD05:: @ 818AD05
	.string "...\n"
	.string "나 혼자가 되어도\p"
	.string "반드시 {STR_VAR_1}의 팬을\n"
	.string "그만두지 않을 거야!\p"
	.string "그야 나 들었어\n"
	.string "{STR_VAR_1}{K_EUNNEUN} 절대 지지 않는대$"
	// ……ｎ
	// ぼく ひとりに なったってｐ
	// ぜったい §いの ファンをｎ
	// やめない からね!ｐ
	// だって ぼく きいたんだもんｎ
	// §いは ぜったいに まけないって

LilycoveCity_PokemonTrainerFanClub_Text_18AD6D:: @ 818AD6D
	.string "{PLAYER}!\n"
	.string "역시 대단해 들었어!\p"
	.string "나는 너를 처음 봤을 때부터\n"
	.string "대단한 녀석이라고 생각했었어!\l"
	.string "역시 내 눈은 확실하다니까!$"
	// §あ!ｎ
	// やっぱり すごいよ きみは!ｐ
	// ぼくは きみを はじめて みたときからｎ
	// すごい やつだって おもってたよ!ｌ
	// やはり ぼくのめは たしかな ようだね!

LilycoveCity_PokemonTrainerFanClub_Text_18ADEF:: @ 818ADEF
	.string "뭐 다른 녀석들의\n"
	.string "말하는 건 신경 쓰지 마\l"
	.string "내가 있으니까!\p"
	.string "너는 걱정하지 말고 평소대로\n"
	.string "싸우고 있으면 돼$"
	// まあ ほかの やつのｎ
	// ことなんて きにするなよｌ
	// ぼくが ついて いるんだ!ｐ
	// きみは しんぱい しないで いつもどおりｎ
	// たたかって いれば いいんだよ

LilycoveCity_PokemonTrainerFanClub_Text_18AE63:: @ 818AE63
	.string "너도 상당히\n"
	.string "좋은 트레이너라고 생각하는데\p"
	.string "지금은 역시 {STR_VAR_1}{K_IGA}\n"
	.string "제일이라고 생각해\p"
	.string "뭐 내가 생각하는 것 뿐이니까\n"
	.string "그렇게 신경 쓰지 않아도 돼$"
	// きみも なかなかｎ
	// いい トレ-ナ-だと おもうけどｐ
	// いまは やっぱり §いがｎ
	// いちばんだと おもうんだｐ
	// まあ ぼくが おもっている だけだからｎ
	// あまり きにしなくて いいよ

LilycoveCity_PokemonTrainerFanClub_Text_18AEF5:: @ 818AEF5
	.string "너는 정말로 강하구나...\n"
	.string "{STR_VAR_1}보다 강할지도 모르겠어\p"
	.string "하지만 내가 {STR_VAR_1}{K_EULREUL}\n"
	.string "응원하지 않으면\l"
	.string "누가 응원하겠어!$"
	// きみは ほんとうに つよいな……ｎ
	// §い より つよいかも しれないｐ
	// でも §い にはｎ
	// ぼくが ひつよう なんだｐ
	// だって ぼくが §いをｎ
	// おうえん しなきゃｌ
	// だれが おうえん するんだ!

LilycoveCity_PokemonTrainerFanClub_Text_18AF62:: @ 818AF62
	.string "다시 봤어!\n"
	.string "당신 정말로 강하구나!\p"
	.string "어떻게 하면 그렇게 강해지는지\n"
	.string "가르침 받고 싶은걸$"
	// みなおしたわ!ｎ
	// あなたって ほんとうに つよいのね!ｐ
	// どうしたら そんなに つよく なれるのかｎ
	// おしえて もらいたいわ

LilycoveCity_PokemonTrainerFanClub_Text_18AFD0:: @ 818AFD0
	.string "당신은 위기에 몰리면 몰릴수록\n"
	.string "화려한 배틀을 하는구나\l"
	.string "다음 대전이 기대되는걸!$"
	// あなたって ピンチに なれば なるほどｎ
	// みりょくてきな たたかいを するのよねｌ
	// つぎの たいせんが たのしみだわ!

LilycoveCity_PokemonTrainerFanClub_Text_18B030:: @ 818B030
	.string "최근 트레이너하면\n"
	.string "역시 {STR_VAR_1}{K_I}지!\l"
	.string "그 강함은 보통이 아니야\p"
	.string "당신도 잘하지만\n"
	.string "{STR_VAR_1}{K_WAGWA} 비교하면 아직이지-$"
	// さいきんの トレ-ナ-はｎ
	// やっぱり §いよね!ｌ
	// あの つよさは ただもの じゃないわｐ
	// あなたも いいせん いってるけどｎ
	// §いに くらべたら まだまだね-

LilycoveCity_PokemonTrainerFanClub_Text_18B0C8:: @ 818B0C8
	.string "당신 정말로\n"
	.string "인기 있네...\p"
	.string "강하지 포켓몬에게 상냥하지\p"
	.string "말할 것도 없네\p"
	.string "하지만 말야! 나는\n"
	.string "{STR_VAR_1}{K_EULREUL} 믿고 있어!\p"
	.string "{STR_VAR_1} 쪽이 확실히\n"
	.string "강하다고 정해져 있으니까!$"
	// あなたって ほんとうにｎ
	// にんき ものよね……ｐ
	// つよいし ポケモンにも やさしいしｎ
	// いうこと ないわｐ
	// でもね! わたしはｎ
	// §いを しんじているの!ｐ
	// §いの ほうが ぜったいにｎ
	// つよいに きまってるん だから!

LilycoveCity_PokemonTrainerFanClub_Text_18B16E:: @ 818B16E
	.string "자네...\p"
	.string "꽤 하는군!$"
	// おぬし……ｐ
	// やるな!

LilycoveCity_PokemonTrainerFanClub_Text_18B181:: @ 818B181
	.string "자네의 진정한 힘은\n"
	.string "이 나만이 알고 있으면 된다\p"
	.string "모두는 그 감춰진 힘을\n"
	.string "알지 못할 게다...$"
	// おぬしの しんの ちからはｎ
	// この わしだけが しっていれば よいのじゃｐ
	// みなには その ひめられた ちからｎ
	// わかるまい……

LilycoveCity_PokemonTrainerFanClub_Text_18B1FD:: @ 818B1FD
	.string "음 자네 상당히 좋은\n"
	.string "눈을 하고 있구먼\p"
	.string "허나!\p"
	.string "...으-음\n"
	.string "아직인 모양이구먼$"
	// うむ おぬし なかなかのｎ
	// めを しておるなｐ
	// じゃが!ｐ
	// ……う-むｎ
	// まだまだの ようじゃな

LilycoveCity_PokemonTrainerFanClub_Text_18B24F:: @ 818B24F
	.string "확실히 자네는\n"
	.string "터무니없이 강할지도 모르겠군\p"
	.string "허나!\n"
	.string "나는 알 수 있다\p"
	.string "그 강함은 아직\n"
	.string "진정한 강함이라고 할 수 없다!\l"
	.string "진정한 강함이란!\p"
	.string "...\p"
	.string "실은 나도\n"
	.string "잘 모르겠구먼$"
	// たしかに おぬしはｎ
	// とてつもなく つよいかも しれないｐ
	// じゃが!ｎ
	// わしには わかるｐ
	// その つよさは まだｎ
	// しんの つよさとは いわないのじゃ!ｌ
	// しんの つよさとは!ｐ
	// ……ｐ
	// じつは わしもｎ
	// よく わからんのじゃ
