LilycoveCity_DepartmentStore_1F_Text_18BFB5:: @ 818BFB5 //JP: 16A4D5
	.string "어서 오세요!\n"
	.string "해안백화점입니다$"

LilycoveCity_DepartmentStore_1F_Text_18BFDB:: @ 818BFDB
	.string "백화점에 오면 즐거워서\n"
	.string "여러 물건을 사게 돼$"

LilycoveCity_DepartmentStore_1F_Text_18C044:: @ 818C044
	.string "오늘은 엄마가\n"
	.string "멋진 가구를 사 주신대$"

LilycoveCity_DepartmentStore_1F_Text_18C07A:: @ 818C07A
	.string "콘테스트 라이브에서\n"
	.string "우승해 준 선물로\l"
	.string "마릴리한테 뭔가 사줄 거야!$"

LilycoveCity_DepartmentStore_1F_Text_18C0C3:: @ 818C0C3
	.string "마릴리: 마리리리-!$"

LilycoveCity_DepartmentStore_1F_Text_18C0D9:: @ 818C0D9
	.string "1층 ... 서비스 카운터\n"
	.string "       추첨 회장\p"
	.string "2층 ... 트레이너즈 존\p"
	.string "3층 ... 배틀 컬렉션\p"
	.string "4층 ... 기술머신코너\p"
	.string "5층 ... 모양바꾸기 굿즈 플로어\p"
	.string "옥상 ... 휴식의 장$"
