LilycoveCity_LilycoveMuseum_1F_Text_187348:: @ 8187348 //JP: 166275
	.string "해안 미술관에 어서 오세요!\p"
	.string "포켓몬들을 그린\n"
	.string "멋진 명화들을\l"
	.string "천천히 관람해 주세요!$"

LilycoveCity_LilycoveMuseum_1F_Text_1873B9:: @ 81873B9
	.string "전 이 미술관의\n"
	.string "관장입니다!\p"
	.string "당신은 젊은데도 미술관에\n"
	.string "오시다니 감탄했어요!\p"
	.string "이제 그림 관람은 끝나신 건가요?$"
	
LilycoveCity_LilycoveMuseum_1F_Text_187459:: @ 8187459
	.string "그럼 방해 안 할 테니\n"
	.string "천천히 봐 주십시오!$"

LilycoveCity_LilycoveMuseum_1F_Text_187495:: @ 8187495
	.string "아니? 당신은\n"
	.string "포켓몬 트레이너인 것 같군요\p"
	.string "그림에도 흥미가 있으신가요?$"

LilycoveCity_LilycoveMuseum_1F_Text_1874F5:: @ 81874F5
	.string "그렇군요...\p"
	.string "그럼에도 일부러 와주시다니\n"
	.string "영광이군요$"

LilycoveCity_LilycoveMuseum_1F_Text_187534:: @ 8187534
	.string "그렇군요!\n"
	.string "그림을 좋아하시는군요!\p"
	.string "그럼 잠시 저를\n"
	.string "따라와 주시지 않겠습니까?$"

LilycoveCity_LilycoveMuseum_1F_Text_18757F:: @ 818757F
	.string "옛날 사람이 그린 그림이다!\n"
	.string "부분 부분 물감이 벗겨져 있다$"

LilycoveCity_LilycoveMuseum_1F_Text_1875BE:: @ 81875BE
	.string "본 적 없는 신비한\n"
	.string "모습이 그려져 있다$"

LilycoveCity_LilycoveMuseum_1F_Text_1875F8:: @ 81875F8
	.string "무릎에 포켓몬을 올려놓고 미소 짓는\n"
	.string "아름다운 여성이 그려져 있다$"

LilycoveCity_LilycoveMuseum_1F_Text_187641:: @ 8187641
	.string "옛날 사람이 상상해서 그린\n"
	.string "전설의 포켓몬의 그림이다!$"

LilycoveCity_LilycoveMuseum_1F_Text_1876A1:: @ 81876A1
	.string "바람에 나부끼며 기분 좋은 듯이\n"
	.string "흔들리는 풀포켓몬이 그려져 있다$"

LilycoveCity_LilycoveMuseum_1F_Text_18770C:: @ 818770C
	.string "맛있어 보이는 나무열매가\n"
	.string "그려져 있다\l"
	.string "배가 고파 온다!$"

LilycoveCity_LilycoveMuseum_1F_Text_18775F:: @ 818775F
	.string "고대의 새포켓몬을 조각한\p"
	.string "유명한 유리 조각상의 레플리카다!$"

LilycoveCity_LilycoveMuseum_1F_Text_1877A9:: @ 81877A9
	.string "검은 돌로 만들어진\n"
	.string "커다란 몬스터볼이다!\l"
	.string "옛날 축제 때 사용되었다고 한다$"

LilycoveCity_LilycoveMuseum_1F_Text_187810:: @ 8187810
	.string "포켓몬의 모습과 알 수 없는 문자가\n"
	.string "촘촘히 새겨져 있는 석판이다!$"

UnknownString_818788B: @ 818788B
	.string "음- 정말 멋진 작품이야...$"

LilycoveCity_LilycoveMuseum_1F_Text_1878B7:: @ 81878B7
	.string "포켓몬 승부도 좋지만\n"
	.string "예술을 사랑하는 마음도\l"
	.string "잊지 말아야 해!$"

LilycoveCity_LilycoveMuseum_1F_Text_18791D:: @ 818791D
	.string "이 미술관은\n"
	.string "대단한 그림을 많이 볼 수 있고\l"
	.string "관장도 멋있는 사람이라서\l"
	.string "우리 화가들도\l"
	.string "정말 동경하는 장소야$"

LilycoveCity_LilycoveMuseum_1F_Text_1879BF:: @ 81879BF
	.string "여기 있는 여자 예쁘다!\n"
	.string "엄마 같아!$"

LilycoveCity_LilycoveMuseum_1F_Text_1879E6:: @ 81879E6
	.string "이 포켓몬 너무 귀엽다!\n"
	.string "우리 아이 같아!$"

LilycoveCity_LilycoveMuseum_1F_Text_187A1A:: @ 8187A1A
	.string "새로운 작품이\n"
	.string "전시된다고 하길래\l"
	.string "바로 보러 왔어!\p"
	.string "2층에 있는 건가?$"

LilycoveCity_LilycoveMuseum_1F_Text_187AA0:: @ 8187AA0
	.string "최근 관장의 기분이\n"
	.string "굉장히 좋은 거 같아\p"
	.string "뭔가 좋은 일이라도 있었나 봐$"

LilycoveCity_LilycoveMuseum_1F_Text_187B04:: @ 8187B04
	.string "여기서 좋은 그림을 많이 보고\n"
	.string "공부해 둬야지!\p"
	.string "언젠가 이곳에 내 작품을\n"
	.string "전시하는 게 꿈이야!$"

LilycoveCity_LilycoveMuseum_1F_Text_187B7F:: @ 8187B7F
	.string "이 미술관도\n"
	.string "완전히 해안시티의...\p"
	.string "...아니 호연지방의\n"
	.string "관광 명소가 됐어!\p"
	.string "들은 얘기로는\n"
	.string "한 명의 트레이너가 2층의 그림을\l"
	.string "모아줬다나 봐!$"
