LilycoveCity_DepartmentStore_5F_Text_18C4F9:: @ 818C4F9 //JP: 16AABB
	.string "귀여운 인형이 많이 있구나-\n"
	.string "우리 애한테 사주려고 왔는데\l"
	.string "내 것도 사야겠어 오호호호호!$"
	// すてきな ぬいぐるみが いっぱい なのね-ｎ
	// こどものぶん だけじゃ なくてｌ
	// あたしのぶんも かおうかしら オホホホホ!

LilycoveCity_DepartmentStore_5F_Text_18C556:: @ 818C556
	.string "난 아직 포켓몬을 키울 수 없으니까\n"
	.string "귀여운 인형을 사달라고 할 거야$"
	// あたし まだ ポケモン そだてられないからｎ
	// かわいい ぬいぐるみ かってもらうの

LilycoveCity_DepartmentStore_5F_Text_18C59F:: @ 818C59F
	.string "귀여운 매트가 정말 많아!\n"
	.string "어떤 걸 살까...?\l"
	.string "몽땅 다 사버릴까...?$"
	// かわいい マットが たくさん うってるの!ｎ
	// どれを かおうかな……ｌ
	// ぜ-んぶ かっちゃおうかな……

UnknownString_818C5FA: @ 818C5FA
	.string "귀여운 친구들\n"
	.string "5층 ... 인형 플로어$"
	// かわいい ともだちｎ
	// 5かい …… ぬいぐるみ フロア-
