LilycoveCity_DepartmentStore_4F_Text_18C39C:: @ 818C39C //JP: 16A930
	.string "음...\p"
	.string "공격의 기술인가...\n"
	.string "방어의 기술인가...\p"
	.string "어떤 기술머신을\n"
	.string "포켓몬에게 배우게\l"
	.string "할 건지 고민되는군...$"

LilycoveCity_DepartmentStore_4F_Text_18C41B:: @ 818C41B
	.string "기술머신은 다양한 종류가 있구나!\p"
	.string "무언가의 카탈로그에는\n"
	.string "전부 50종류라고\l"
	.string "적혀 있었어$"

LilycoveCity_DepartmentStore_4F_Text_18C481:: @ 818C481
	.string "기술머신 전부 가지고 싶은데\n"
	.string "포켓몬이 4개밖에 기술을 못 배워...$"

UnknownString_818C4CE: @ 818C4CE
	.string "포켓몬리그로 가는 지름길\n"
	.string "4층 ... 기술머신코너$"
