LilycoveCity_Harbor_Text_18B306:: @ 818B306 //JP: 1699E8
	.string "에? 배 말입니까?\p"
	.string "죄송합니다만 현재\n"
	.string "연락선은 없습니다...$"
	// えっ? ふね ですか?ｐ
	// もうしわけ ございません げんざいｎ
	// れんらくせんは ないんです……

LilycoveCity_Harbor_Text_18B36F:: @ 818B36F
	.string "연락선을 이용하시려는 거군요!\n"
	.string "티켓은 가지고 계신가요?$"
	// れんらくせんを ごりよう ですね!ｎ
	// チケットは おもち でしょうか?

LilycoveCity_Harbor_Text_18B3A9:: @ 818B3A9
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "티켓이 없다!\p"
	.string "...죄송합니다!\p"
	.string "배에는 티켓을 가진 분들만\n"
	.string "탑승하실 수 있습니다$"
	// §あはｎ
	// チケットを もっていない!ｐ
	// ……もうしわけ ありません!ｐ
	// ふねに のれるのはｎ
	// チケットの ある かた だけです

LilycoveCity_Harbor_Text_18B406:: @ 818B406
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "승선티켓을 보여줬다!\p"
	.string "네! 확인했습니다!\p"
	.string "어디로 가시겠어요?$"
	// §あはｎ
	// ふねのチケットを みせた!ｐ
	// はい! けっこう です!ｐ
	// いきさきは どちら でしょう?

LilycoveCity_Harbor_Text_18B45B:: @ 818B45B
	.string "또 이용해 주십시오!$"
	// また ごりよう ください!

LilycoveCity_Harbor_Text_18B47D:: @ 818B47D
	.string "잿빛도시 말씀이시군요!$"
	// カイナ ですね!

LilycoveCity_Harbor_Text_18B499:: @ 818B499
	.string "배틀타워 말씀이시군요!$"
	// バトルタワ- ですね!

LilycoveCity_Harbor_Text_18B4B3:: @ 818B4B3
	.string "연락선에서 잠시 기다려 주십시오$"
	// れんらくせんに のって おまちください

LilycoveCity_Harbor_Text_18B4E2:: @ 818B4E2
	.string "어디로 가시겠어요?$"
	// いきさきは どちら でしょう?

LilycoveCity_Harbor_Text_18B504:: @ 818B504
	.string "연락선이 완성되지 않으면\n"
	.string "선원은 할 일이 없어 한가해...\p"
	.string "잿빛도시 조선소 녀석들\n"
	.string "빨리 좀 안 만들어주려나$"
	// れんらくせんが かんせい しないとｎ
	// ふなのり というものは ヒマだぜ……ｐ
	// カイナの ぞうせんじょの れんちゅうｎ
	// しゃかりきに がんばって くれよな

LilycoveCity_Harbor_Text_18B58E:: @ 818B58E
	.string "드디어 연락선 타이드립호가\n"
	.string "운행하기 시작했어!\p"
	.string "잿빛도시 조선소 녀석들\n"
	.string "무지 고생했겠네\l"
	.string "이제부턴 내가 바빠지겠군!$"
	// やっと れんらくせん タイドリップごうがｎ
	// うんこう するように なったんだ!ｐ
	// カイナの ぞうせんじょの みんなｎ
	// たいへん だったろうなｌ
	// これからは おれが いそがしくなるぞ!
