LilycoveCity_House3_Text_18B8CC:: @ 818B8CC //JP: 169EEA
	.string "어머 어머 어머! 너 젊은데\n"
	.string "혼자 여행하고 있는 거니?\l"
	.string "대단하네-!\p"
	.string "우리 애들도 보고 배웠으면 좋겠어\p"
	.string "나는 포켓몬스넥 명인!\n"
	.string "내가 조금만 진짜 실력을 내면\l"
	.string "정말 좋은\l"
	.string "포켓몬스넥이 완성된단다-!\p"
	.string "포켓몬스넥 명인인 내가\n"
	.string "여러 가지 알려 줄까?$"

LilycoveCity_House3_Text_18B9DC:: @ 818B9DC
	.string "어머 그러니?\n"
	.string "뭐든지 자기 혼자서\l"
	.string "감당하려고 하면 안 된단다-!$"

LilycoveCity_House3_Text_18BA2B:: @ 818BA2B
	.string "어머 정말 착한 아이구나-!\n"
	.string "그럼 조금 길지만 들어줄래\p"
	.string "알겠니?\p"
	.string "포켓몬스넥에는 부드러움이 있단다\n"
	.string "포켓몬스넥을 보면 알 수 있지?\l"
	.string "부드러움은 적을수록 좋아!\l"
	.string "이 부분이 중요해!\p"
	.string "부드러움 수치가 낮고\n"
	.string "레벨이 높을 것이 좋은 포켓몬스넥!\l"
	.string "좋은 포켓몬스넥은 잔뜩\l"
	.string "포켓몬이 먹어 준단다!\p"
	.string "그리고 말이지!\p"
	.string "부드러운 포켓몬스넥을\n"
	.string "만들고 싶으면\p"
	.string "아끼지 말고 여러 종류의\n"
	.string "나무열매로 만들어 보는 거야!\l"
	.string "섞은 나무열매에 따라 부드러움이\l"
	.string "달라지게 되니까!\p"
	.string "그리고 있잖아!\p"
	.string "되도록 여럿이서 만드는 편이\n"
	.string "부드러운 포켓몬스넥이 나와!\l"
	.string "누구라도 좋은니까 부탁해서\l"
	.string "같이 만들어봐!\p"
	.string "자 그럼 이 정도 외우고 있으면\n"
	.string "너도 충분히 혼자서\l"
	.string "만들 수 있게 될 거야!\p"
	.string "정말 좋아하는 포켓몬과\n"
	.string "부드러운 포켓몬스넥\l"
	.string "그리고 사이좋은 가족이 있으면\l"
	.string "이 세상은 행복해질 거야!\p"
	.string "그러니 너도 힘내!$"

LilycoveCity_House3_Text_18BD64:: @ 818BD64
	.string "네쌍둥이가 태어났을 때는\n"
	.string "정말 놀랐는데 모두 사이좋게\l"
	.string "놀고 있는 모습을 보고 있으면\n"
	.string "정말 행복한 기분이 들어!$"

LilycoveCity_House3_Text_18BDDB:: @ 818BDDB
	.string "멀티배틀을 하고 있는데\n"
	.string "내가 이기는 건 정해져 있다고!$"

LilycoveCity_House3_Text_18BE14:: @ 818BE14
	.string "레코드코너에서 뒤섞는다!\n"
	.string "라니 뭐가 섞이는 걸까?$"

LilycoveCity_House3_Text_18BE57:: @ 818BE57
	.string "나무열매블렌더로\n"
	.string "엄청난 포켓몬스넥 만들 거야!$"

LilycoveCity_House3_Text_18BE8E:: @ 818BE8E
	.string "포켓몬의 강인함을 자랑하고 싶어서\n"
	.string "모두 같이 콘테스트 하고 있어!$"
