LilycoveCity_LilycoveMuseum_2F_Text_187C42:: @ 8187C42 //JP: 1669A0
	.string "여기는 특별 전시실입니다$"

LilycoveCity_LilycoveMuseum_2F_Text_187C64:: @ 8187C64
	.string "보시는 대로 아직\n"
	.string "그림이 장식되어 있지 않습니다\p"
	.string "여기에는 1층에 있는\n"
	.string "소위 명화같은 것과는\l"
	.string "다른 그림을 장식하고 싶어요!\p"
	.string "오래된 명화만이\n"
	.string "예술인 것이 아니에요!\p"
	.string "이 전시실에는...\p"
	.string "지금이라도 포켓몬이 튀어나올 듯한\n"
	.string "모던하고 살아있는 듯한 작품을\l"
	.string "장식하고 싶습니다!$"

LilycoveCity_LilycoveMuseum_2F_Text_187E1D:: @ 8187E1D
	.string "무심코 오랫동안 실례했어요\p"
	.string "당신은 아직 젊고\n"
	.string "여행을 하시고 있는 것 같으니\p"
	.string "활기찬 포켓몬이나\n"
	.string "그것을 그린 멋진 작품과\l"
	.string "마주칠지도 몰라요!\p"
	.string "만약 그런 작품과 마주친다면\n"
	.string "그 그림을 여기에 장식할 수 있도록\l"
	.string "당신에게 부탁하게 해주신다면\l"
	.string "정말 기쁠 거예요$"

LilycoveCity_LilycoveMuseum_2F_Text_187F4E:: @ 8187F4E
	.string "이 전시실에는\n"
	.string "현대의 생생한 포켓몬의\l"
	.string "그림을 장식하고 싶은 겁니다$"

LilycoveCity_LilycoveMuseum_2F_Text_187F9D:: @ 8187F9D
	.string "덕분에 그림을\n"
	.string "장식할 수 있었어요!\p"
	.string "당신의 포켓몬이라 하더라고요!\n"
	.string "정말 굉장하군요!\p"
	.string "참으로 감사합니다...!$"

LilycoveCity_LilycoveMuseum_2F_Text_18802F:: @ 818802F
	.string "아! 당신! {PLAYER}님!$"

LilycoveCity_LilycoveMuseum_2F_Text_188041:: @ 8188041
	.string "어떻습니까 봐 주십시오!\n"
	.string "이 굉장한 작품들을!\p"
	.string "어느 것도 서로에게\n"
	.string "꿇리지 않는 굉장함!\p"
	.string "이 그림 덕분에게 미술관에\n"
	.string "오시는 분도 늘었어요!\p"
	.string "정말로 감사합니다 {PLAYER}님!\n"
	.string "제 꿈이 이루어졌어요!$"

LilycoveCity_LilycoveMuseum_2F_Text_188120:: @ 8188120
	.string "...이건 제가 드리는\n"
	.string "감사의 답례입니다!$"

UnknownString_8188148: @ 8188148
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "글라스오브제를 받았다!$"

LilycoveCity_LilycoveMuseum_2F_Text_188166:: @ 8188166
	.string "그럼 또 오셨을 때\n"
	.string "뵙도록 하죠$"

LilycoveCity_LilycoveMuseum_2F_Text_188194:: @ 8188194
	.string "오 이거 {PLAYER}님!\p"
	.string "바쁜 여행 도중에\n"
	.string "와 주시다니 영광입니다!\p"
	.string "그럼 천천히 있다 가세요$"

LilycoveCity_LilycoveMuseum_2F_Text_188219:: @ 8188219
	.string "분홍색 장식이 달린 액자다!$"

LilycoveCity_LilycoveMuseum_2F_Text_18824C:: @ 818824C
	.string "노란색 장식이 달린 액자다!$"

LilycoveCity_LilycoveMuseum_2F_Text_188281:: @ 8188281
	.string "파란색 장식이 달린 액자다!$"

LilycoveCity_LilycoveMuseum_2F_Text_1882B4:: @ 81882B4
	.string "빨간색 장식이 달린 액자다!$"

LilycoveCity_LilycoveMuseum_2F_Text_1882E6:: @ 81882E6
	.string "초록색 장식이 달린 액자다!$"

LilycoveCity_LilycoveMuseum_2F_Text_18831A:: @ 818831A
	.string "포켓몬의 그림이 장식되어 있다!$"

LilycoveCity_LilycoveMuseum_2F_Text_188336:: @ 8188336
	.string "오랜만에 와 봤는데 2층에도\n"
	.string "전시가 되어 있어서 깜짝 놀랐어!\p"
	.string "좋겠다 내 포켓몬도\n"
	.string "이렇게 멋지게 그려진다면 좋겠다$"

LilycoveCity_LilycoveMuseum_2F_Text_1883AB:: @ 81883AB
	.string "호오... 여기가 요즘\n"
	.string "화제의 포켓몬 그림이 있는 곳인가...\p"
	.string "과연 새로운 그림이 가득해서\n"
	.string "꽤나 재미있구먼...$"

LilycoveCity_LilycoveMuseum_2F_Text_188423:: @ 8188423
	.string "우와-! 이거\n"
	.string "네 포켓몬의 그림이구나!\p"
	.string "그거야말로 트레이너로서\n"
	.string "정말 최고의 행복이지!$"
