LilycoveCity_ContestLobby_Text_18848C:: @ 818848C //JP: 167621
	.string "이쪽은 포켓몬 콘테스트의\n"
	.string "4명 전용 접수처입니다!\p"
	.string "친구가 앞으로 3명 더 모이면\n"
	.string "4인이서 똑같은 콘테스트에\l"
	.string "나갈 수 있습니다!\l"
	.string "참가하겠습니까?$"

LilycoveCity_ContestLobby_Text_188521:: @ 8188521
	.string "콘테스트에 참가하기 전에\n"
	.string "리포트를 작성합니다$"

FallarborTown_ContestLobby_Text_188559:: @ 8188559
LilycoveCity_ContestLobby_Text_188559:: @ 8188559
	.string "다음번 참가를 기다리고 있겠습니다!$"

LilycoveCity_ContestLobby_Text_188584:: @ 8188584
	.string "콘테스트에\n"
	.string "참가하겠습니까?$"

LilycoveCity_ContestLobby_Text_1885A7:: @ 81885A7
	.string "트레이너인 친구가 4명\n"
	.string "모이면 케이블을 연결하고\l"
	.string "여기서 참가해 주십시오!\p"
	.string "콘테스트는 같은 것을\n"
	.string "선택해 주세요!\p"
	.string "여러분의 참가가 끝나면\n"
	.string "콘테스트가 시작되니\l"
	.string "다음은 평소와 똑같은 상태로\l"
	.string "힘내 주십시오!$"

UnknownString_81886A8: @ 81886A8
	.string "그럼 통신 준비가 끝났다면\n"
	.string "참가하고 싶은 콘테스트를\l"
	.string "선택해 주십시오!$"

LilycoveCity_ContestLobby_Text_1886DC:: @ 81886DC
	.string "어느 콘테스트에 참가하겠습니까?$"

LilycoveCity_ContestLobby_Text_188703:: @ 8188703
	.string "어느 포켓몬을 참가시키겠습니까?$"

LilycoveCity_ContestLobby_Text_18872A:: @ 818872A
	.string "통신하고 있습니다...$"

LilycoveCity_ContestLobby_Text_18873A:: @ 818873A
	.string "통신에 실패했습니다$"

LilycoveCity_ContestLobby_Text_188750:: @ 8188750
	.string "선택한 콘테스트가\n"
	.string "친구와 다른 것 같습니다!$"

LilycoveCity_ContestLobby_Text_18878D:: @ 818878D
	.string "서로의 선택이 다른 것 같습니다$"

LilycoveCity_ContestLobby_Text_1887C7:: @ 81887C7
	.string "잠시 기다려 주십시오\n"
	.string "...B 버튼 취소$"

LilycoveCity_ContestLobby_Text_1887F4:: @ 81887F4
	.string "다음번 참가를 기다리고 있겠습니다!$"

LilycoveCity_ContestLobby_Text_18881F:: @ 818881F
	.string "통신 에러입니다\n"
	.string "1번 더 진행해 주십시오$"

LilycoveCity_ContestLobby_Text_188845:: @ 8188845
	.string "그럼 손님의 포켓몬을\n"
	.string "참가시킵니다!\p"
	.string "손님의 참가 번호는\n"
	.string "{STR_VAR_2}번입니다!$"

UnknownString_8188890: @ 8188890
	.string "{STR_VAR_2}번 분은\n"
	.string "오늘은 이 색으로\l"
	.string "도전해 주십시오!$"

LilycoveCity_ContestLobby_Text_1888C6:: @ 81888C6
	.string "콘테스트가 곧 시작됩니다!$"

UnknownString_81888E6: @ 81888E6
	.string "이쪽에서 가세요!\n"
	.string "열심히 하세요!$"

LilycoveCity_ContestLobby_Text_18890F:: @ 818890F
	.string "우승 축하해!\p"
	.string "빨리 기념으로\n"
	.string "너의 포켓몬의 그림을\l"
	.string "그리고 싶은데...\p"
	.string "뭔가 네 포켓몬 어필이\n"
	.string "정말 굉장해서\l"
	.string "평소보다 잘 그렸어!\l"
	.string "자 이거!$"

UnknownString_81889D0: @ 81889D0
	.string "여기서 화면을 바꿔서\n"
	.string "그림을 보여줍니다$"

LilycoveCity_ContestLobby_Text_1889FD:: @ 81889FD
	.string "어때? 자신 있는 작품인데\n"
	.string "마음에 들었지?\p"
	.string "이 정도 된다면\n"
	.string "미술관에 장식되어 있어도\l"
	.string "이상하지 않겠는걸!\p"
	.string "...에 정말로 미술관에서\n"
	.string "그림을 찾아보고 있다고?\l"
	.string "그럼 이거 가져가 볼까?$"

LilycoveCity_ContestLobby_Text_188AE8:: @ 8188AE8
	.string "그 그래!\n"
	.string "그럼 지금 바로 가져가 볼게\l"
	.string "제목도 붙여 둘 테니까!\p"
	.string "이게 마음에 들어\n"
	.string "장식될지 어떨지\l"
	.string "너도 다음에 보러 와 줘!\l"
	.string "그럼 고마워!$"

LilycoveCity_ContestLobby_Text_188BB5:: @ 8188BB5
	.string "...아 맞다\p"
	.string "포켓몬을 그리게 해준 기념으로\n"
	.string "이걸 받아줘!$"

LilycoveCity_ContestLobby_Text_188C03:: @ 8188C03
	.string "{PLAYER}{K_EUNNEUN} 리본을 받았다!$"

LilycoveCity_ContestLobby_Text_188C19:: @ 8188C19
	.string "{PLAYER}{K_EUNNEUN} 리본을\n"
	.string "{STR_VAR_1}에게 달아줬다!$"

LilycoveCity_ContestLobby_Text_188C32:: @ 8188C32
	.string "그럼 이만!$"

LilycoveCity_ContestLobby_Text_188C41:: @ 8188C41
	.string "음... 그럼 이건\n"
	.string "내가 가지고 돌아갈까...\p"
	.string "하지만 역시 가져가고 싶은데...\n"
	.string "어떻게 생각해?$"

LilycoveCity_ContestLobby_Text_188CBD:: @ 8188CBD
	.string "그런가 어쩔 수 없지\n"
	.string "그럼 이건 내\l"
	.string "집에 장식할게\p"
	.string "다음에 열심히 해야겠다...\n"
	.string "그럼 안녕$"

LilycoveCity_ContestLobby_Text_188D3C:: @ 8188D3C
	.string "윽 드디어\n"
	.string "콘테스트도 마스터랭크...\p"
	.string "내 포켓몬이\n"
	.string "이 세상에서 가장\l"
	.string "귀엽다는 걸\l"
	.string "증명할 때가 온 거야...\l"
	.string "우헤헤헤헤$"

LilycoveCity_ContestLobby_Text_188DDA:: @ 8188DDA
	.string "여기에 오면\n"
	.string "포켓몬을 잔뜩 볼 수 있어서\l"
	.string "산책 코스로 다니고 있어!$"
	
LilycoveCity_ContestLobby_Text_188E47:: @ 8188E47
	.string "어머 아직 콘테스트패스를\n"
	.string "받지 않았구나!\l"
	.string "잔디마을에서 빨리 받아 오렴!\p"
	.string "소중히 키워진 포켓몬을\n"
	.string "많이 볼 수 있어서 행복해!$"

LilycoveCity_ContestLobby_Text_188F07:: @ 8188F07
	.string "이야 콘테스트도\n"
	.string "마스터랭크까지 오면\l"
	.string "기운 있는 포켓몬이\l"
	.string "잔뜩 있네!$"

LilycoveCity_ContestLobby_Text_188F81:: @ 8188F81
	.string "강인함콘테스트는\n"
	.string "최고로군!\p"
	.string "힘센 어필...\n"
	.string "샘솟는 땀... 못 참겠어!$"

LilycoveCity_ContestLobby_Text_188FE3:: @ 8188FE3
	.string "매일 소중히 소중히\n"
	.string "키워온 내 포켓몬\l"
	.string "컨디션은 완벽!\l"
	.string "오늘은 이긴다아아아아아아아!$"

LilycoveCity_ContestLobby_Text_18904D:: @ 818904D
	.string "엄마하고 아빠하고 누나하고\n"
	.string "4명이서 포켓몬스넥을 만들었더니\l"
	.string "엄청 좋은 게 나왔어!\p"
	.string "분명 여럿이서 만들면 만들수록\n"
	.string "부드럽고 좋은 포켓몬스넥이\l"
	.string "나오는 걸 거야$"
