LilycoveCity_ContestHall_Text_1890D4:: @ 81890D4 //JP: 167F50
	.string "아름다움 콘테스트에서\n"
	.string "우승한 이 포켓몬을\l"
	.string "오늘은 슬기로움 콘테스트에서\l"
	.string "우승시켰다고!\p"
	.string "아아 내 재능이 무섭다...$"

LilycoveCity_ContestHall_Text_18915F:: @ 818915F
	.string "몇 번이나 콘테스트에 나가서\n"
	.string "어떻게든 알았는데\p"
	.string "예를 들면 근사함콘테스트에서\n"
	.string "근사한 기술을 쓰면 반응이 좋지만\l"
	.string "슬기로운 어필이나 귀여운 어필은\l"
	.string "왠지 반응이 나쁘단 말이지...$"

LilycoveCity_ContestHall_Text_189221:: @ 8189221
	.string "방금 우승했던 오빠\n"
	.string "굉장히 많은 종류의\l"
	.string "포켓몬스넥을 가지고 있었어!\p"
	.string "저만큼 가지고 있으면\n"
	.string "우승할 수 있는 걸까?$"

LilycoveCity_ContestHall_Text_189299:: @ 8189299
	.string "우와 넓네 여기는!\n"
	.string "시골의 콘테스트 회장과는\l"
	.string "긴장감이 다르네!$"

LilycoveCity_ContestHall_Text_189301:: @ 8189301
	.string "사회자: 네에 근사한 포켓몬과\n"
	.string "그리고 트레이너 여러부-운!\l"
	.string "열심히 해주세요--오!\l"
	.string "렛츠! 어필!!$"

LilycoveCity_ContestHall_Text_189366:: @ 8189366
	.string "심사위원: 콘테스트\n"
	.string "즐기고 계십니까?\p"
	.string "친구를 3명 데리고 오면\n"
	.string "4명 같이 참가할 수 있답니다!$"

LilycoveCity_ContestHall_Text_1893CE:: @ 81893CE
	.string "어버버버...\n"
	.string "나갈 콘테스트를 착각했어...\p"
	.string "강인한 포켓몬을\n"
	.string "슬기로움콘테스트에...\p"
	.string "좋 좋앗\n"
	.string "슬기로운 바위깨기 부탁해!$"

LilycoveCity_ContestHall_Text_189463:: @ 8189463
	.string "내가 긴 세월 동안\n"
	.string "지식의 모든 걸 걸고서\l"
	.string "슬기롭게 키운 포켓몬!\p"
	.string "젊은 녀석들의 포켓몬 따위에\n"
	.string "그렇게 쉽게 지지는 않겠다!\p"
	.string "할멈 보고 계시오-!?$"

LilycoveCity_ContestHall_Text_189512:: @ 8189512
	.string "좋아! 내 포켓몬이\n"
	.string "이 다음에 슬기로운 기술을 쓰면\l"
	.string "회장이 익사이트해진다!$"

LilycoveCity_ContestHall_Text_18956B:: @ 818956B
	.string "싫다아!\p"
	.string "내 주뱃의\n"
	.string "흡혈이 정말 멋져서\l"
	.string "계속해서 몇 번이고 썼더니\l"
	.string "왠지 실망하고 있어-!$"

LilycoveCity_ContestHall_Text_1895F3:: @ 81895F3
	.string "캬-! 아저씨 멋져요-!$"

LilycoveCity_ContestHall_Text_189617:: @ 8189617
	.string "같은 포켓몬을 내보내도\n"
	.string "트레이너에 따라\l"
	.string "전혀 다른 기술로\l"
	.string "어필한단 말이지\p"
	.string "그건 승부하고 같네!$"

LilycoveCity_ContestHall_Text_1896BE:: @ 81896BE
	.string "트레이너보다 포켓몬 쪽이\n"
	.string "머리 좋아 보이네$"

LilycoveCity_ContestHall_Text_1896FE:: @ 81896FE
	.string "역시 슬기로움 콘테스트!\p"
	.string "지혜로운 초록색이\n"
	.string "으-음 멋지네-!$"

LilycoveCity_ContestHall_Text_189771:: @ 8189771
	.string "사회자: 어라? 당신도\n"
	.string "아름다움 콘테스트에 나오나요?\l"
	.string "열심히 하세요!$"

LilycoveCity_ContestHall_Text_1897AA:: @ 81897AA
	.string "심사위원: 어느 포켓몬도\n"
	.string "실로 아름답군요!\p"
	.string "깜빡하고 점수를 안 매겼네요!$"

LilycoveCity_ContestHall_Text_18980B:: @ 818980B
	.string "이렇게 아름다운 포켓몬\n"
	.string "달리 없지\p"
	.string "모두의 눈을 사로잡아 버릴걸!$"

LilycoveCity_ContestHall_Text_189874:: @ 8189874
	.string "으아-앙!\p"
	.string "이 콘테스트를 위해서\n"
	.string "정말 열심히 털을 가꾸었는데\p"
	.string "너무 가꾸었는지 내 포켓몬\n"
	.string "부수수해졌어!\p"
	.string "어쩌지...$"

LilycoveCity_ContestHall_Text_18990A:: @ 818990A
	.string "이 엄청 눈부신 오로라빔은\n"
	.string "심사위원도 볼 수 없다!\p"
	.string "...어라?\n"
	.string "그럼 의미가 없나?$"

LilycoveCity_ContestHall_Text_189981:: @ 8189981
	.string "이 예쁜 포켓몬\n"
	.string "내가 어릴 때와 닮았어!\p"
	.string "라고 말했더니... 남편이\n"
	.string "마시던 차를 뿜었어\p"
	.string "내가 뭔가 이상한 걸 말한 건가?$"

LilycoveCity_ContestHall_Text_189A1D:: @ 8189A1D
	.string "역시 여성으로서는\p"
	.string "아름다움콘테스트에 이기면\n"
	.string "평소보다 좀 더 기쁘지-!$"

LilycoveCity_ContestHall_Text_189A82:: @ 8189A82
	.string "우와하핫!\p"
	.string "예쁜 포켓몬이\n"
	.string "가득 있다...\l"
	.string "이거 화려해서 좋구먼!$"

LilycoveCity_ContestHall_Text_189AE1:: @ 8189AE1
	.string "그저 아름다운 것만으로는\n"
	.string "좀처럼 이길 수 없어!\p"
	.string "내 포켓몬처럼\n"
	.string "손질되어있고 반들반들하지 않으면!$"

LilycoveCity_ContestHall_Text_189B4E:: @ 8189B4E
	.string "사회자: 어머 어머-!\n"
	.string "지금은 콘테스트 중이에요-!\p"
	.string "접수처에서 참가하고 나서\n"
	.string "나와 주세요-오! 알겠죠!$"

LilycoveCity_ContestHall_Text_189BBF:: @ 8189BBF
	.string "심사위원: 오오\n"
	.string "모두 귀여운 어필이군!\p"
	.string "오옷 얼마나 아름다운\n"
	.string "물놀이 어필인가!$"

LilycoveCity_ContestHall_Text_189C29:: @ 8189C29
	.string "아아 내 마릴리가\n"
	.string "다른 포켓몬에게 시선을 뺏겼어!$"

LilycoveCity_ContestHall_Text_189C67:: @ 8189C67
	.string "내 포켓몬은 승부에서\n"
	.string "1번도 이긴 적 없지만\l"
	.string "콘테스트는 특기란다!$"

LilycoveCity_ContestHall_Text_189CB3:: @ 8189CB3
	.string "내 포켓몬의 우아한\n"
	.string "꽃잎댄스...\l"
	.string "누구도 방해하게 두진 않아!$"

LilycoveCity_ContestHall_Text_189D11:: @ 8189D11
	.string "어느 포켓몬도\n"
	.string "정말로 귀엽네\p"
	.string "하지만 내 포켓몬이\n"
	.string "귀여운 어필을 하면...\p"
	.string "분명 더 귀여울 거야$"

LilycoveCity_ContestHall_Text_189DA2:: @ 8189DA2
	.string "우리 애가 콘테스트에 나와 있어요\p"
	.string "자 힘내렴!\n"
	.string "네 포켓몬이 최고란다!$"

LilycoveCity_ContestHall_Text_189DF3:: @ 8189DF3
	.string "나는 저 여자아이가\n"
	.string "가장 귀엽다고 생각하네\p"
	.string "엣? 포켓몬의 모습을\n"
	.string "비교하는 거라고!?$"

LilycoveCity_ContestHall_Text_189E5F:: @ 8189E5F
	.string "아아 보고 나서\n"
	.string "저 포켓몬 가지고 싶어졌어\l"
	.string "잡으러 가자!$"

UnknownString_8189EC0: @ 8189EC0
	.string "근사함콘테스트 스테이지\n"
	.string "쿨한 포켓몬에 헤롱헤롱!$"

LilycoveCity_ContestHall_Text_189EF3:: @ 8189EF3
	.string "아름다움콘테스트 스테이지\n"
	.string "뷰티풀 포켓몬에 어질어질!$"

LilycoveCity_ContestHall_Text_189F29:: @ 8189F29
	.string "귀여움콘테스트 스테이지\n"
	.string "큐트한 포켓몬에 싱숭생숭!$"

LilycoveCity_ContestHall_Text_189F5C:: @ 8189F5C
	.string "슬기로움콘테스트 스테이지\n"
	.string "인텔리 포켓몬에 녹아녹아!$"

UnknownString_8189F93: @ 8189F93
	.string "강인함콘테스트 스테이지\n"
	.string "와일드한 포켓몬에 두근두근!$"
