LilycoveCity_DepartmentStore_2F_Text_18C162:: @ 818C162 //JP: 16A6D0
	.string "도구의 기본은 능숙하게 사용할 것\n"
	.string "이게 제일 중요한 거야$"

LilycoveCity_DepartmentStore_2F_Text_18C195:: @ 818C195
	.string "집에서 기다리고 있는 남편한테 줄\n"
	.string "선물인데 뭐가 좋을까?$"

LilycoveCity_DepartmentStore_2F_Text_18C1D9:: @ 818C1D9
	.string "이제부터 먼 곳으로\n"
	.string "여행을 떠날 거니까\l"
	.string "여기서 한가득 도구를 사 놓을 거야$"

UnknownString_818C21A: @ 818C21A
	.string "여행의 동반자\n"
	.string "2층 ... 트레이너즈 존$"
