LilycoveCity_Text_1679BF:: @ 81679BF //JP: 149105
	.string "봄이: 어라!?\n"
	.string "{PLAYER}도 쇼핑하러 왔어?\p"
	.string "난 봉제인형이랑 포스터\n"
	.string "엄청 많이 샀어!\p"
	.string "물론 예전에 만났을 때보다\n"
	.string "포켓몬도 더 많이 잡았고\l"
	.string "제대로 키우고도 있다고!\p"
	.string "그것보다 나로서는\n"
	.string "{PLAYER}{K_IGA}\p"
	.string "포켓몬을 제대로\n"
	.string "키우고 있는지가 더 걱정인데\p"
	.string "승부해줄 테니까\n"
	.string "{PLAYER}의 포켓몬도 보여줘!$"

LilycoveCity_Text_167AEB:: @ 8167AEB
	.string "봄이: 에- 어째서?\n"
	.string "{PLAYER} 포켓몬 안 키운 거야?\p"
	.string "그러면 트레이너로서\n"
	.string "아직 멀었네!$"

LilycoveCity_Text_167B55:: @ 8167B55
	.string "봄이: 승부해줄 테니까\n"
	.string "{PLAYER}의 포켓몬도 보여줘!$"

LilycoveCity_Text_167B94:: @ 8167B94
	.string "봄이: 내가 키운 포켓몬이\n"
	.string "{PLAYER}의 포켓몬에게\l"
	.string "질 리가 없지!$"

LilycoveCity_Text_167BD5:: @ 8167BD5
	.string "... ... ... ...\p"
	.string "103번 도로에서\n"
	.string "{PLAYER}{K_WAGWA} 승부한 게\l"
	.string "떠올랐어!\p"
	.string "그 승부가 덕분에\n"
	.string "{PLAYER}{K_IGA}\l"
	.string "이만큼 강해진 거야!$"

LilycoveCity_Text_167C6B:: @ 8167C6B
	.string "봄이: 나 이제 슬슬\n"
	.string "미로마을로 돌아가려고\p"
	.string "다양한 포켓몬을 잡아서\n"
	.string "도감도 꽤 모았으니까\l"
	.string "이제 아빠한테 보여줘야지!$"

LilycoveCity_Text_167D08:: @ 8167D08
	.string "{PLAYER}{K_EUNNEUN} 이제부터 어떻게 할 거야?\p"
	.string "이곳저곳의 체육관 배지를 모아서\n"
	.string "포켓몬리그에 도전할 거야?\p"
	.string "그럼 나는 {PLAYER}{K_IGA}\n"
	.string "배지 모으고 있는 사이에\l"
	.string "포켓몬 도감을 완성시켜놔야지!\p"
	.string "그럼 안녕!$"

LilycoveCity_Text_167DDD:: @ 8167DDD
	.string "{PLAYER}{K_EUNNEUN} 이제부터 어떻게 할 거야?\p"
	.string "포켓몬리그에 도전할 거야?\p"
	.string "아니면 포켓몬 도감\l"
	.string "완성시킬 거야?\p"
	.string "포켓몬 승부로는 졌지만\n"
	.string "도감은 내가\l"
	.string "먼저 완성시킬 거야!\p"
	.string "그럼 안녕!$"

LilycoveCity_Text_167EAA:: @ 8167EAA
	.string "{PLAYER}{K_EUNNEUN} 이제부터 어떻게 할 거야?\p"
	.string "배틀타워에 도전할 거야?\p"
	.string "아니면 포켓몬 도감\n"
	.string "완성시킬 거야?\p"
	.string "포켓몬 승부로는 졌지만\n"
	.string "도감은 내가\l"
	.string "먼저 완성시킬 거야!\p"
	.string "그럼 안녕!$"

LilycoveCity_Text_167F75:: @ 8167F75
	.string "휘웅: 뭐야 {PLAYER}{K_I}구나\p"
	.string "난 아빠에게 부탁한\n"
	.string "심부름을 하고 있었어\l"
	.string "봉제인형 같은 건 안 샀어 진짜\p"
	.string "그것보다 오랜만에 만났으니까\p"
	.string "누가 포켓몬을\n"
	.string "잘 키웠는지\l"
	.string "승부해볼래?$"

LilycoveCity_Text_16802C:: @ 816802C
	.string "휘웅: 뭐야\n"
	.string "자신이 없는 거야?$"

LilycoveCity_Text_168067:: @ 8168067
	.string "휘웅: 누가 포켓몬을\n"
	.string "잘 키웠는지\l"
	.string "승부해볼래?$"

LilycoveCity_Text_1680A9:: @ 81680A9
	.string "휘웅: 뭐 당연히 내가\n"
	.string "{PLAYER}한테 질 리는 없지만 말야$"

LilycoveCity_Text_1680E4:: @ 81680E4
	.string "흠...\n"
	.string "꽤 키우고 있구나\p"
	.string "이거 좀 분한걸\n"
	.string "트레이너로서는 내가\l"
	.string "선배였는데 말야...$"

LilycoveCity_Text_168149:: @ 8168149
	.string "휘웅: 나...\n"
	.string "이제 슬슬 미로마을로 돌아가려고\p"
	.string "아빠 도와드리려고 만들고 있는\n"
	.string "포켓몬 도감도 어느 정도 완성돼서\l"
	.string "아빠한테 한번 보여드리려고$"

LilycoveCity_Text_1681EA:: @ 81681EA
	.string "{PLAYER}{K_EUNNEUN} 어떻게 할 거야?\p"
	.string "역시 모든 배지를 모아서\n"
	.string "포켓몬리그에 도전할 거야?\p"
	.string "나도 그렇게 할까나\p"
	.string "뭐든 상관없나\n"
	.string "어쨌든 힘내!$"

LilycoveCity_Text_168282:: @ 8168282
	.string "{PLAYER}{K_EUNNEUN} 어떻게 할 거야?\p"
	.string "그렇게 강하니까\n"
	.string "포켓몬리그에 도전할 거야?\p"
	.string "나도 좀 더\n"
	.string "포켓몬 키우면 {PLAYER}보다도\l"
	.string "강해질 수 있으니까\p"
	.string "뭐든 상관없나\n"
	.string "어쨌든 힘내!$"

LilycoveCity_Text_16835A:: @ 816835A
	.string "{PLAYER}{K_EUNNEUN} 어떻게 할 거야?\p"
	.string "그렇게 강하니까\n"
	.string "배틀타워에 도전할 거야?\p"
	.string "나도 좀 더\n"
	.string "포켓몬 키우면 {PLAYER}보다도\l"
	.string "강해질 수 있으니까\l"
	.string "배틀타워에 가볼까?\p"
	.string "뭐든 상관없나\n"
	.string "어쨌든 힘내!$"

LilycoveCity_Text_168455:: @ 8168455
	.string "후후후...\p"
	.string "오늘도 무사히 빼앗은 물건을\n"
	.string "아지트에 옮겼다...\p"
	.string "뭐 뭐야 넌!\n"
	.string "바 방금 건 혼잣말이야!$"

LilycoveCity_Text_1684C2:: @ 81684C2
	.string "리더가 무슨 생각을 하시는지\n"
	.string "조무래기는 전혀 상상도 안 가지만\p"
	.string "{EVIL_TEAM}에 있으면\n"
	.string "엄청난 일을 할 수 있을 거 같거든!\p"
	.string "뭐 뭐야 넌!\n"
	.string "바 방금 건 혼잣말이야!$"

LilycoveCity_Text_168573:: @ 8168573
	.string "잠깐 너!\p"
	.string "저기 후미진 곳에 있는\n"
	.string "동굴에는 접근하지 마!\p"
	.string "왜냐고?\n"
	.string "이유는 뭐든 상관없잖아!\p"
	.string "어린이는 얌전히\n"
	.string "어른이 시키는 대로 해!!$"

LilycoveCity_Text_1685EB:: @ 81685EB
	.string "이 넓은 세상의 모든 것이\n"
	.string "우리 {EVIL_TEAM}단의 것이 되면\l"
	.string "포켓몬들도 행복해질 수 있을 거야!$"

LilycoveCity_Text_16864A:: @ 816864A
	.string "자! 고래왕자!\n"
	.string "거기 수면에서 점프하는 거야!$"

LilycoveCity_Text_168675:: @ 8168675
	.string "...응? 뭐야 넌?\p"
	.string "트레이닝에 방해되니까\n"
	.string "저리로 가 줘!$"

LilycoveCity_Text_1686C9:: @ 81686C9
	.string "이 콘테스트 회장에서는\n"
	.string "전국에서 이겨 온\l"
	.string "포켓몬이 모여 있어!\p"
	.string "이 몸의 심장도 두근두근거리지!$"

LilycoveCity_Text_168750:: @ 8168750
	.string "마을 변두리에 있는 후미진 곳에\n"
	.string "이상한 동굴 있는 거 봤어?$"

LilycoveCity_Text_168791:: @ 8168791
	.string "나 포켓몬\n"
	.string "콘테스트를 위해서 새로운 기술을\l"
	.string "배우게 할 거야!\p"
	.string "그래서 있잖아\n"
	.string "기술잊기 할아버지에게 부탁해서\l"
	.string "비전기술을 잊게 할 거야!$"

LilycoveCity_Text_168819:: @ 8168819
	.string "저는 관동에서 왔습니다!\p"
	.string "호연지방은 물과 초목이\n"
	.string "넘쳐흐르는 곳이네요!\p"
	.string "...응? 그렇다는 건?\p"
	.string "이 지방에서만 서식하는\n"
	.string "희귀한 포켓몬이 있을 수도?$"

LilycoveCity_Text_1688C1:: @ 81688C1
	.string "{EVIL_TEAM}단 녀석들이\n"
	.string "저기 후미진 곳에서 고래왕자를\l"
	.string "트레이닝시키고 있더라고!\p"
	.string "이대로는 우리 선원들이\n"
	.string "바다에 나갈 수가 없어!$"

LilycoveCity_Text_168934:: @ 8168934
	.string "너 그거 알아?\p"
	.string "누군지는 모르겠는데 {EVIL_TEAM}단을\n"
	.string "혼쭐을 내줬다고 하더라고!\p"
	.string "덕분에 고래왕자가 없어져서\n"
	.string "바다에 나갈 수 있게 됐어!$"

LilycoveCity_Text_1689BF:: @ 81689BF
	.string "해변에 있는 숙소에서 파도 소리를\n"
	.string "들으면서 여유롭게 낮잠!\p"
	.string "...을 자고 있었더니\n"
	.string "포켓몬을 도둑맞았어!\p"
	.string "범인은 누구지!?\n"
	.string "{EVIL_TEAM}단? {EVIL_TEAM}단이야!?$"

LilycoveCity_Text_168A55:: @ 8168A55
	.string "없어진 내 포켓몬이\n"
	.string "어느샌가 돌아와 있었어...!$"

LilycoveCity_Text_168A8D:: @ 8168A8D
	.string "전 화상입니다!\p"
	.string "아니 이름이 화상이라는 게 아니라\n"
	.string "가치 있는 그림을 사고팔고 하는\l"
	.string "직업의 이름이에요!\p"
	.string "이 마을 미술관에 정말 멋진\n"
	.string "명화가 있다고 들었습니다만...$"

LilycoveCity_Text_168B1F:: @ 8168B1F
	.string "우리들이 아무리 쭈글쭈글이 되어도\n"
	.string "이 바다는 늘 변함없이 싱그럽고\l"
	.string "생명의 반짝임으로 가득 차 있구려\p"
	.string "우하하 우하하하하...$"

LilycoveCity_Text_168B9B:: @ 8168B9B
	.string "60년 전에 할아범이 여기서\n"
	.string "나한테 프러포즈했을 때부터\l"
	.string "이 바다는 변함없이 아름다워요\p"
	.string "오호호 오호호호호...$"

LilycoveCity_Text_168C16:: @ 8168C16
	.string "여기 후미진 곳에\n"
	.string "이상한 동굴의 입구가 있지?\p"
	.string "예전에는 천연동굴이었는데\n"
	.string "{EVIL_TEAM}단이라고 하는 녀석들이\l"
	.string "저렇게 개조해 버렸지 뭔가!\p"
	.string "“자연을 사랑하는 {EVIL_TEAM}단!”\n"
	.string "...이라는 것 같더만\p"
	.string "말하는 것과 하는 것이\n"
	.string "다르지 않은가!$"

LilycoveCity_Text_168D15:: @ 8168D15
	.string "후미진 곳에 있는 동굴...\n"
	.string "어느샌가 입구가 없어져서\l"
	.string "안에 들어갈 수 없게 됐어!\p"
	.string "분명 {EVIL_TEAM}단이라고 하는 녀석들\n"
	.string "어딘가 먼 곳으로 가버린 게지!$"

LilycoveCity_Text_168DA9:: @ 8168DA9
	.string "여기는 해안시티\n"
	.string "육지가 끝나고 바다가 시작되는 곳$"

LilycoveCity_Text_168DE1:: @ 8168DE1
	.string "포켓몬 콘테스트 마스터랭크 접수처\n"
	.string "친구와 함께 참가할 수도 있습니다!$"

LilycoveCity_Text_168E2F:: @ 8168E2F
	.string "“안해민박”\n"
	.string "해안의 안해로 기억해 주세요$"

LilycoveCity_Text_168E67:: @ 8168E67
	.string "“해안 미술관”\n"
	.string "포켓몬 명화전 개최 중!$"

LilycoveCity_Text_168EA4:: @ 8168EA4
	.string "“해안 미술관”\p"
	.string "{PLAYER}의 포켓몬 컬렉션\n"
	.string "개최 중!$"

LilycoveCity_Text_168EDA:: @ 8168EDA
	.string "“해안시티 배 타는 곳”\p"
	.string "연락선 타이드립호는\n"
	.string "현재 잿빛도시에서 건조 중!\p"
	.string "조금만 더 기다려주세요!$"

LilycoveCity_Text_168F57:: @ 8168F57
	.string "“해안시티 배 타는 곳”\p"
	.string "연락선 타이드립호로\n"
	.string "즐거운 배여행을 만끽해 주세요!$"

LilycoveCity_Text_168FA1:: @ 8168FA1
	.string "“포켓몬 트레이너 팬클럽”\p"
	.string "간판에는 여러 트레이너들의\n"
	.string "이름이 낙서처럼 써져 있다...$"

LilycoveCity_Text_168FF3:: @ 8168FF3
	.string "“해안백화점”\p"
	.string "굿즈 한가득! 설렘 한가득!\n"
	.string "무언가를 발견할 수 있는 멋진 장소$"

LilycoveCity_Text_169072:: @ 8169072
	.string "“기술잊기 할아버지의 집”\n"
	.string "포켓몬 기술을 잊게 합니다$"
