LilycoveCity_DepartmentStore_3F_Text_18C24B:: @ 818C24B //JP: 16A731
	.string "쉽고 빠르게 포켓몬을 강하게 하려면\n"
	.string "도구를 사용하는 게 최고다!\p"
	.string "타우린은 공격이 오르고!\n"
	.string "리보플라빈은\l"
	.string "특수공격이 올라간다고!$"
	// てっとりばやく ポケモンを つよくするならｎ
	// どうぐを あたえるのが いちばん!ｐ
	// タウリンなら こうげきりょく アップ!ｎ
	// リゾチウムなら とくこう アップ だぜ!

LilycoveCity_DepartmentStore_3F_Text_18C2B5:: @ 818C2B5
	.string "튼튼한 포켓몬으로\n"
	.string "자라주었으면 하는데 말이지\p"
	.string "사포닌으로 방어를 올릴지\n"
	.string "키토산으로 특수방어를 올릴지\l"
	.string "고민하는 중이라네 지금$"
	// じょうぶな ポケモンにｎ
	// なって ほしいからねｐ
	// ブロムヘキシンで ぼうぎょりょくを あげるかｎ
	// キトサンで とくぼうを あげるかｌ
	// いま かんがえている ところ なんだ

LilycoveCity_DepartmentStore_3F_Text_18C32E:: @ 818C32E
	.string "포켓몬한테\n"
	.string "알칼로이드를 사용했더니\l"
	.string "스피드가 빨라졌어!$"
	// ポケモンにねｎ
	// インドメタシンを あげたらｌ
	// すばやさが あがったの!

UnknownString_818C363: @ 818C363
	.string "패배를 모르는 트레이너의 필수품\n"
	.string "3층 ... 배틀 콜렉션$"
	// まけない トレ-ナ-の ひつじゅひんｎ
	// 3かい …… バトル コレクション
