LittlerootTown_BrendansHouse_1F_Text_1730C2:: @ 81730C2
LittlerootTown_MaysHouse_1F_Text_1730C2:: @ 81730C2
	.string "응? 누구지?\p"
	.string "... ... ... ...\n"
	.string "... ... ... ...\p"
	.string "아 그래 네가 옆집으로\n"
	.string "이사 온 {PLAYER}\e구나!\p"
	.string "우리 집에도 너와 비슷한 또래의\n"
	.string "{STR_VAR_1}이 있단다!\p"
	.string "“새 친구가 생긴다!”\n"
	.string "라면서 무척 좋아했었어\p"
	.string "2층 방에 있을 테니까\n"
	.string "친구가 돼 주면 고맙겠구나!$"

LittlerootTown_BrendansHouse_1F_Text_1731C6:: @ 81731C6
	.string "우리 아이와\n"
	.string "친구가 돼 주면 고맙겠구나\p"
	.string "2층에 있을 테니까\n"
	.string "천천히 놀다 가렴$"

LittlerootTown_BrendansHouse_1F_Text_1731E3:: @ 81731E3
	.string "이 사람은 어딜 간 거지?\n"
	.string "모처럼 {PLAYER}\r\l"
	.string "인사하러 왔는데...\p"
	.string "연구소에 있는 걸까?$"

LittlerootTown_BrendansHouse_1F_Text_173262:: @ 8173262
	.string "어머 {RIVAL}\e라면\n"
	.string "어디 나가던데?\p"
	.string "정말 아빠를 닮아서 그런지\n"
	.string "집에 가만히 있지를 못한다니까$"

LittlerootTown_BrendansHouse_1F_Text_1732B9:: @ 81732B9
	.string "포켓몬이랑 같이\n"
	.string "모험하는 것도 좋지만\p"
	.string "가끔은 집에 돌아와서\n"
	.string "엄마한테 건강한 모습 좀\l"
	.string "보여주고 그러렴!\p"
	.string "분명 마음속에서는\n"
	.string "{PLAYER}\f\l"
	.string "걱정하고 있으실 테니까...$"
