LittlerootTown_BrendansHouse_2F_Text_172E18:: @ 8172E18
	.string "벽에 걸린 시계가 멈춰 있다...\p"
	.string "시간을 맞춰 놔야지!$"

LittlerootTown_BrendansHouse_2F_Text_172E4C:: @ 8172E4C
	.string "엄마: {PLAYER}\n"
	.string "새 방은 어떠니?\p"
	.string "응! 깔끔하게 정리되어 있네!\n"
	.string "아래 방도 이미 정리가 끝났단다\p"
	.string "포켓몬들이 도와주니까\n"
	.string "정말 편해!\p"
	.string "아 맞아! 책상 위의 물건들이\n"
	.string "문제없는지 한번 확인해보렴$"

UnknownString_8172F31: @ 8172F31
	.string "포켓몬 책이랑 사진집이\n"
	.string "죽 진열되어 있다!\p"
	.string "{PLAYER}{K_IGA} 여태까지 모은 상들도 있다!$"

UnknownString_8172F85: @ 8172F85
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "PC를 확인했다!$"

LittlerootTown_BrendansHouse_2F_Text_172F9A:: @ 8172F9A
	.string "{PLAYER}{K_EUNNEUN} 노트를 펼쳐 보았다!\p"
	.string "탐험 수칙이 적혀 있다!\p"
	.string "탐험 수칙 1\n"
	.string "START 버튼으로 메뉴를 연다!\p"
	.string "탐험 수칙 2\n"
	.string "리포트를 선택하면\l"
	.string "기록을 할 수 있다!\p"
	.string "그 뒤로는 아무것도 쓰여있지 않다...$"

UnknownString_817303D: @ 817303D
	.string "{PLAYER}{K_EUNNEUN} 호연지방의\n"
	.string "타운맵에 얼굴을 가까이 댔다!$"

LittlerootTown_BrendansHouse_2F_Text_17306C:: @ 817306C
	.string "게임큐브가 있다!\p"
	.string "컨트롤러 대신에\n"
	.string "게임보이 어드밴스가 연결되어 있어!$"
