LittlerootTown_Text_16A7C9:: @ 816A7C9
	.string "엄마: {PLAYER} 고생했어!\p"
	.string "계속 트럭이 흔들려서\n"
	.string "정신없었지?\p"
	.string "여기가 미로마을이란다!\p"
	.string "어떠니? 이게 우리 가족의\n"
	.string "새로운 집이야!\p"
	.string "살짝 고풍스러우면서도\n"
	.string "살기 좋은 곳일 거 같지 않니?\p"
	.string "이번에는 {PLAYER}\n" 
	.string "네 방도 있단다!\p"
	.string "자 그럼 안으로 들어가자!$"

LittlerootTown_Text_16A8EE:: @ 816A8EE
	.string "엄마: 잠깐 기다리렴 {PLAYER}!$"

LittlerootTown_Text_16A8FD:: @ 816A8FD
	.string "엄마: {PLAYER}! {PLAYER}!\n"
	.string "털보박사님께는 인사했니?\p"
	.string "어머! 귀여운 포켓몬!\n"
	.string "털보박사님께 받았구나\p"
	.string "역시 피는 못 속여...\n"
	.string "포켓몬이랑 함께 있는 모습이\l"
	.string "정말 그럴듯하구나!\p"
	.string "자! 모험을 떠나려면\n"
	.string "러닝슈즈를 신어야지!\p"
	.string "여러 장소를\n"
	.string "달릴 수 있게 될 거야!$"

LittlerootTown_Text_16AA32:: @ 816AA32
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "러닝슈즈로 갈아 신었다!$"

LittlerootTown_Text_16AA5C:: @ 816AA5C
	.string "엄마: {PLAYER}!\n"
	.string "이게 설명서란다\p"
	.string "“러닝슈즈는\n"
	.string "  B 버튼을 누르면 지금보다\l"
	.string "  빨리 달릴 수 있게 해 줍니다!\p"
	.string "  러닝슈즈를 신고\n"
	.string "  마음껏 달립시다!”$"

LittlerootTown_Text_16AB10:: @ 816AB10
	.string "... ... ... ...\n"
	.string "... ... ... ...\p"
	.string "네가 자신의 포켓몬을\n"
	.string "가지게 될 줄이야...\l"
	.string "아빠가 알면 정말 기뻐하시겠다!\p"
	.string "...그치만 무리는 하지 마렴\n"
	.string "무슨 일이 생기면\l"
	.string "집으로 와도 되니까\p"
	.string "그럼 힘내!$"

LittlerootTown_Text_16AC00:: @ 816AC00
	.string "PC를 쓰면\n"
	.string "아이템이나 포켓몬을\l"
	.string "보관할 수 있다고 하더라고!\p"
	.string "과학의 힘은 정말 대단해!$"

LittlerootTown_Text_16AC56:: @ 816AC56
	.string "계속 연구소에만 틀어박혀서\n"
	.string "연구만 하고 있다고 생각했는데\p"
	.string "또 갑자기\n"
	.string "산이나 들로 뛰쳐나가니...\p"
	.string "털보박사님은 도대체\n"
	.string "언제 집에 가시는 걸까?$"

LittlerootTown_Text_16ACEB:: @ 816ACEB
	.string "여기 앞에 있는 도로\n"
	.string "풀숲으로 들어가면\l"
	.string "야생 포켓몬이 나와!$"

LittlerootTown_Text_16AD3C:: @ 816AD3C
	.string "자기 포켓몬을 데리고 있지 않으면\n"
	.string "위험해!$"

LittlerootTown_Text_16AD82:: @ 816AD82
	.string "요 앞에서\n"
	.string "비명 소리가 들리는데!?\p"
	.string "어떡하지? 어떡하면 좋을까?\n"
	.string "누가 좀 도와주러 가야 할 텐데...$"

LittlerootTown_Text_16ADF2:: @ 816ADF2
	.string "{K_BOY_CALL} 덕분에\n"
	.string "박사님이 무사해서 다행이야!$"

LittlerootTown_Text_16AE25:: @ 816AE25
	.string "포켓몬 잡으러 가는 거야?\n"
	.string "파이팅!$"

LittlerootTown_Text_16AE50:: @ 816AE50
	.string "여기는 미로마을\n"
	.string "어떤 색에도 물들지 않는 마을$"

LittlerootTown_Text_16AE87:: @ 816AE87
	.string "“털보박사 포켓몬 연구소”$"

LittlerootTown_Text_16AEA1:: @ 816AEA1
	.string "“{PLAYER}의 집”$"

LittlerootTown_Text_16AEAC:: @ 816AEAC
	.string "“털보박사의 집”$"
