LittlerootTown_BrendansHouse_1F_Text_172429:: @ 8172429
	.string "엄마: {PLAYER}{K_AYA} 봐 보렴\n"
	.string "집 안도 멋지지 않니?$"

LittlerootTown_BrendansHouse_1F_Text_172453:: @ 8172453
	.string "집 안 정리를\n"
	.string "이삿짐센터 포켓몬이 도와주니까\l"
	.string "이렇게 편할 수가 없어!\p"
	.string "{PLAYER}도 2층에 있는\n"
	.string "네 방에 한번 가보렴!\p"
	.string "아빠가 이사 기념으로\n"
	.string "사 주신 시계가 있을 거니까\l"
	.string "시간 좀 맞춰 둬$"

LittlerootTown_BrendansHouse_1F_Text_172531:: @ 8172531
	.string "엄마: {PLAYER}\p"
	.string "네 방은 안 봐도 되니?$"

LittlerootTown_BrendansHouse_1F_Text_172574:: @ 8172574
LittlerootTown_MaysHouse_1F_Text_172574:: @ 8172574
	.string "엄마: {PLAYER}\n"
	.string "방 안에 있는 시계 좀 맞춰줄래?$"

LittlerootTown_BrendansHouse_1F_Text_1725A3:: @ 81725A3
	.string "엄마: ...아! {PLAYER}! {PLAYER}!\n"
	.string "이리로 빨리 와보렴!$"

LittlerootTown_BrendansHouse_1F_Text_1725C9:: @ 81725C9
LittlerootTown_MaysHouse_1F_Text_1725C9:: @ 81725C9
	.string "엄마: 등화도시 체육관이 나오고 있어\n"
	.string "아빠가 나올지도 몰라!!$"

LittlerootTown_BrendansHouse_1F_Text_1725FE:: @ 81725FE
LittlerootTown_MaysHouse_1F_Text_1725FE:: @ 81725FE
	.string "엄마: 어머... 끝나버렸네\p"
	.string "아빠가 나왔던 거 같은데\n"
	.string "아쉽네$"

LittlerootTown_BrendansHouse_1F_Text_172644:: @ 8172644
LittlerootTown_MaysHouse_1F_Text_172644:: @ 8172644
	.string "...아 맞다 맞다! 이 마을에\n"
	.string "털보박사님이라고 하시는\l"
	.string "아빠 친구분이 계시거든\p"
	.string "박사님 집은 옆집이니까\n"
	.string "얼른 인사 드리고 오렴!$"

LittlerootTown_BrendansHouse_1F_Text_1726D2:: @ 81726D2
	.string "엄마: 그럼 다녀오렴!$"

LittlerootTown_BrendansHouse_1F_Text_1726E7:: @ 81726E7
	.string "엄마: 어머? 털보박사님은\n"
	.string "잘 만나 뵙고 왔니?$"

LittlerootTown_BrendansHouse_1F_Text_172717:: @ 8172717
	.string "엄마: 어떠니? {PLAYER}\n"
	.string "조금 지쳐 보이네?\p"
	.string "집에서 좀 쉬다 가렴$"

LittlerootTown_BrendansHouse_1F_Text_17276B:: @ 817276B
	.string "엄마: 그럼 조심하고!$"

LittlerootTown_BrendansHouse_1F_Text_172782:: @ 8172782
	.string "엄마: 어머 그 배지\n"
	.string "아빠한테 받은 거니!?\p"
	.string "그럼 엄마도 이거 줘야겠다$"

LittlerootTown_BrendansHouse_1F_Text_1727CD:: @ 81727CD
	.string "너무 무리하지는 마렴\n"
	.string "언제든지 집에 와도 되니까!\p"
	.string "그럼 힘내!$"

LittlerootTown_BrendansHouse_1F_Text_17281D:: @ 817281D
	.string "가오오 가오 가오...$"

LittlerootTown_BrendansHouse_1F_Text_172831:: @ 8172831
	.string "그어 그어 그어...$"

LittlerootTown_BrendansHouse_1F_Text_172841:: @ 8172841
	.string "인터뷰어: ...이상으로\n"
	.string "등화도시 체육관 앞에서\l"
	.string "전해드렸습니다!$"

UnknownString_817288C: @ 817288C
	.string "TV에서 영화를 하고 있다!\p"
	.string "어른과 아이가 같이\n"
	.string "커다란 피아노 위에서 춤추고 있다!\p"
	.string "빨리 가자!$"

UnknownString_81728E3: @ 81728E3
    .string "러닝슈즈의 사용설명서다!\p"
	.string "“러닝슈즈는\n"
	.string "  B 버튼을 누르면 지금보다\l"
	.string "  빨리 달릴 수 있게 해줍니다!\p"
	.string "  러닝슈즈를 신고\n"
	.string "  마음껏 달립시다!”$"

LittlerootTown_BrendansHouse_1F_Text_17298B:: @ 817298B
	.string "아빠: 응?\p"
	.string "{PLAYER} 아니냐!\p"
	.string "오랜만에 보는데\n"
	.string "어딘지 모르게 늠름해진 거 같은...\l"
	.string "그런 느낌이 드는구나\p"
	.string "그렇지만 나도\n"
	.string "아직까진 팔팔하다고\p"
	.string "...아 그래 맞다\n"
	.string "네 앞으로 하기라는 사람한테서\l"
	.string "이게 도착했어!.$"

LittlerootTown_BrendansHouse_1F_Text_172A7D:: @ 8172A7D
	.string "아빠: 승선티켓이구나...\p"
	.string "분명 배를 타는 선착장은\n"
	.string "잿빛도시 또는 해안시티에 있었지\p"
	.string "{PLAYER}!\p"
	.string "지금보다 더 강해지고 싶으면\n"
	.string "그 배의 행선지인...\l"
	.string "배틀타워로 가보는 게 좋을 거야\p"
	.string "트레이너 수행에는\n"
	.string "끝이 없다는 걸 배우게 될 거다$"

LittlerootTown_BrendansHouse_1F_Text_172B5E:: @ 8172B5E
	.string "그럼 난\n"
	.string "등화도시 체육관에 돌아갈게\p"
	.string "여보\n"
	.string "그럼 다녀올게$"

LittlerootTown_BrendansHouse_1F_Text_172BBC:: @ 8172BBC
	.string "엄마: 네 아빠는 정말\n"
	.string "일밖에 모르는 사람이야\p"
	.string "오랜만에 집에 왔지만\n"
	.string "결국 포켓몬 얘기밖에 하지 않았단다\p"
	.string "가끔은 집에서\n"
	.string "천천히 쉬었다 가면 좋을 텐데!$"

UnknownString_8172C50: @ 8172C50
	.string "임시 뉴스입니다\p"
	.string "호연지방 각지에서\n"
	.string "파란 포켓몬이 날아다니는 걸\l"
	.string "봤다는 정보가 들어왔습니다\p"
	.string "아직까지 정체는\n"
	.string "확인하지 못했다고 합니다\p"
	.string "그럼 계속 이어지는\n"
	.string "영화를 즐겨주십시오...$"

UnknownString_8172D30: @ 8172D30
	.string "임시 뉴스입니다\p"
	.string "호연지방 각지에서\n"
	.string "빨간 포켓몬이 날아다니는 걸\l"
	.string "봤다는 정보가 들어왔습니다\p"
	.string "아직까지 정체는\n"
	.string "확인하지 못했다고 합니다\p"
	.string "그럼 계속 이어지는\n"
	.string "영화를 즐겨주십시오$"

UnknownString_8172E0F: @ 8172E0F
	.string "가우! 가우!$"
