UnknownString_8173A9D: @ 8173A9D
	.string "“포켓몬의 종류와 분포”\n"
	.string "“사람과 포켓몬의 공존”\l"
	.string "“초심자들을 위한 포켓몬학”\p"
	.string "털보박사가 쓴 책이\n"
	.string "죽 진열되어 있다!$"

LittlerootTown_ProfessorBirchsLab_Text_173B29:: @ 8173B29
	.string "응? 털보박사님?\p"
	.string "박사님이라면 필드워크하러\n"
	.string "나가셔서 지금 안 계셔요\p"
	.string "...아 필드워크라는 건\p"
	.string "실제로 산이나 들로 나가서\n"
	.string "연구를 하는 걸 말하는 거예요!\p"
	.string "박사님은 책상 위에서 연구하시는\n"
	.string "것보다 실제 밖으로 나가서\l"
	.string "체험하는 타입의 사람이에요!$"

LittlerootTown_ProfessorBirchsLab_Text_173C88:: @ 8173C88
	.string "박사님은 책상 위에서 연구하시는\n"
	.string "것보다 실제 밖으로 나가서\l"
	.string "체험하는 타입의 사람이에요!$"

LittlerootTown_ProfessorBirchsLab_Text_173D15:: @ 8173D15
	.string "털보박사님은\n"
	.string "포켓몬이 어디에 살고 있는가\l"
	.string "분포를 조사하고 있어요\p"
	.string "{RIVAL}{K_I}는 자기가 좋아하는 아빠를\n"
	.string "도와주고 있답니다$"

LittlerootTown_ProfessorBirchsLab_Text_173D94:: @ 8173D94
	.string "털보박사: ...자 그럼 {PLAYER}!\p"
	.string "너에 대한 얘기는 너희 아버지한테\n"
	.string "항상 듣고 있단다!\p"
	.string "넌 아직 자신의 포켓몬을\n"
	.string "가져본 적이 없다고 하던데?\p"
	.string "그런 거치고는 아까 전에 포켓몬을\n"
	.string "다루는 실력은\l"
	.string "꽤 괜찮았는데 말이지!\p"
	.string "역시 너한테는 아버지의\n"
	.string "피가 흐르고 있나 보구나!\p"
	.string "아 그래! 구해준 보답으로\n"
	.string "아까 고른 포켓몬을\l"
	.string "너에게 선물하도록 하마!\p"
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "{STR_VAR_1}{K_EULREUL} 받았다!$"

LittlerootTown_ProfessorBirchsLab_Text_173EF8:: @ 8173EF8
	.string "털보박사: 모처럼 이렇게 된 거\n"
	.string "별명을 지어주는 건 어떠니?$"

LittlerootTown_ProfessorBirchsLab_Text_173F3D:: @ 8173F3D
	.string "털보박사: 앞으로 더욱더 많은\n"
	.string "경험을 쌓아 가면\l"
	.string "더 좋은 트레이너가 될 거 같구나!\p"
	.string "마침 우리 {RIVAL}{K_I}가\n"
	.string "103번 도로에서 포켓몬에 관한\l"
	.string "조사를 하고 있으니까\l"
	.string "만나러 가면 어떻겠느냐?$"

LittlerootTown_ProfessorBirchsLab_Text_174015:: @ 8174015
	.string "털보박사: 그럴래!\n"
	.string "그거 우리 {RIVAL}{K_I}도 좋아하겠구나!\p"
	.string "트레이너가 어떤 건지\n"
	.string "배워 보는 것도 좋겠지!$"

LittlerootTown_ProfessorBirchsLab_Text_174075:: @ 8174075
	.string "털보박사: 그러지 말고\n"
	.string "만나러 가면 어떻겠느냐?$"

LittlerootTown_ProfessorBirchsLab_Text_1740B4:: @ 81740B4
	.string "털보박사: {RIVAL}{K_I}? 아마\n"
	.string "103번도로에 있을 거 같구나\p"
	.string "그리고 포켓몬이 다쳤다면\n"
	.string "너희 집에서 쉬었다가 움직이려무나!$"

LittlerootTown_ProfessorBirchsLab_Text_17411F:: @ 817411F
	.string "털보박사: 오 {PLAYER}{K_AYA}!\p"
	.string "처음인데도 {RIVAL}{K_I}한테\n"
	.string "이기다니 정말 대단하구나!\p"
	.string "{RIVAL}{K_I}는 상당히 예전부터\n"
	.string "내 연구를 도와주고 있어서\l"
	.string "트레이너 경력은 꽤 긴데 말이지!\p"
	.string "응! {PLAYER}한테도\n"
	.string "연구를 위해 마련해 놓은\l"
	.string "이 포켓몬 도감을 주도록 하지!$"

LittlerootTown_ProfessorBirchsLab_Text_17422F:: @ 817422F
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "포켓몬 도감을 받았다!$"

LittlerootTown_ProfessorBirchsLab_Text_174248:: @ 8174248
	.string "털보박사: 그 포켓몬 도감은 말이다\n"
	.string "네가 만난 포켓몬을\l"
	.string "자동으로 기록해주는\l"
	.string "하이테크한 도구란다!\p"
	.string "{RIVAL}{K_I}도 그 도감을 들고\n"
	.string "이곳저곳 놀러 다니고 있지\p"
	.string "그러면서 희귀한 포켓몬을 잡아서\n"
	.string "도감에 기록하면 말이지\p"
	.string "필드워크하고 있는 나를\n"
	.string "찾아내고는 그걸 보여준단다!$"

LittlerootTown_ProfessorBirchsLab_Text_17436C:: @ 817436C
	.string "털보박사: 수많은 포켓몬들이 너를\n"
	.string "기다리고 있다!\p"
	.string "...아-! 나도 빨리\n"
	.string "필드워크하러 나가고 싶어졌다!$"

LittlerootTown_ProfessorBirchsLab_Text_1743D4:: @ 81743D4
	.string "봄이: {PLAYER}도\n"
	.string "포켓몬 도감 받았구나!\p"
	.string "잘됐다! 나랑 똑같네!\n"
	.string "그럼 난 이걸 줄게!\p"
	.string "야생 포켓몬을\n"
	.string "잡을 수 있는 몬스터볼!$"

LittlerootTown_ProfessorBirchsLab_Text_17443D:: @ 817443D
	.string "봄이: 다양한 포켓몬을 만난다는 건\n"
	.string "정말로 두근거리는 일이지!\p"
	.string "...나도 이제부터 준비해서\n"
	.string "이 마을에서 출발할 거야\p"
	.string "어떤 포켓몬을 만나게 될지\n"
	.string "너무 기대돼!$"

LittlerootTown_ProfessorBirchsLab_Text_1744F0:: @ 81744F0
	.string "음? 가방이 가득 찼구나$"

LittlerootTown_ProfessorBirchsLab_Text_174505:: @ 8174505
	.string "봄이: 이번엔 어디까지\n"
	.string "포켓몬 찾으러 가볼까?$"

LittlerootTown_ProfessorBirchsLab_Text_17453C:: @ 817453C
	.string "휘웅: 흐응- {PLAYER}{K_I}도\n"
	.string "포켓몬 도감 받았구나\p"
	.string "그럼 난\n"
	.string "이걸 줄게$"

LittlerootTown_ProfessorBirchsLab_Text_17458C:: @ 817458C
	.string "휘웅: 많은 포켓몬을 잡는다는 건\n"
	.string "상상만 해도 기쁜 일이지!\p"
	.string "...나도 이제부터 준비해서\n"
	.string "이 마을에서 출발할 거야\p"
	.string "뭐랄까...\n"
	.string "왠지 모르게 두근두근해$"

LittlerootTown_ProfessorBirchsLab_Text_17465B:: @ 817465B
	.string "흐음- 가방이 가득 찼네$"

LittlerootTown_ProfessorBirchsLab_Text_174671:: @ 8174671
	.string "휘웅: 이번엔 어디로\n"
	.string "포켓몬 찾으러 가볼까나...$"

LittlerootTown_ProfessorBirchsLab_Text_1746A2:: @ 81746A2
	.string "무언가 엄청나 보이는 머신이다!\n"
	.string "박사님이 연구에 사용하시는 걸까?$"

LittlerootTown_ProfessorBirchsLab_Text_1746E7:: @ 81746E7
	.string "연구에 사용되고 있는 PC다!\n"
	.string "...만지지는 말자$"

LittlerootTown_ProfessorBirchsLab_Text_174724:: @ 8174724
	.string "포켓몬에 관한 책들로\n"
	.string "죽 진열되어 있다!$"

LittlerootTown_ProfessorBirchsLab_Text_174748:: @ 8174748
	.string "읽기에는 너무 어려운 책이 있다!$"
