MauvilleCity_GameCorner_Text_181C35:: @ 8181C35
	.string "어서 오세요!\n"
	.string "보라시티 게임코너입니다!$"

MauvilleCity_GameCorner_Text_181C53:: @ 8181C53
	.string "게임용 동전 말이죠?\p"
	.string "오잉? 동전을 넣는\n"
	.string "동전케이스가 없네요$"

MauvilleCity_GameCorner_Text_181CB4:: @ 8181CB4
	.string "게임용 동전 말이죠?\p"
	.string "50개에 1000원입니다!\n"
	.string "동전을 사시겠습니까?$"

MauvilleCity_GameCorner_Text_181CFE:: @ 8181CFE
	.string "네 감사합니다!\n"
	.string "동전입니다! 여기 있습니다!$"

MauvilleCity_GameCorner_Text_181D28:: @ 8181D28
	.string "손님...\n"
	.string "돈이 부족한 것 같아요$"

MauvilleCity_GameCorner_Text_181D57:: @ 8181D57
	.string "오잉?\n"
	.string "동전케이스가 가득 찼네요$"

MauvilleCity_GameCorner_Text_181D73:: @ 8181D73
	.string "...필요 없나요?\n"
	.string "그럼 다시 와주세요!$"

UnknownString_8181DB2: @ 8181DB2
	.string "50개에 1000원입니다!\n"
	.string "동전을 사시겠습니까?$"

MauvilleCity_GameCorner_Text_181DE1:: @ 8181DE1
	.string "어서 오세요!\p"
	.string "여기서는 게임으로 쌓은 동전을\n"
	.string "마음에 드는 경품과 교환합니다!$"

MauvilleCity_GameCorner_Text_181E17:: @ 8181E17
	.string "어느 것이 좋으세요?$"

MauvilleCity_GameCorner_Text_181E33:: @ 8181E33
	.string "{STR_VAR_1}로\n"
	.string "교환하시겠습니까?$"

MauvilleCity_GameCorner_Text_181E49:: @ 8181E49
	.string "감사합니다!\n"
	.string "집에 있는 PC에 보냈습니다!$"

MauvilleCity_GameCorner_Text_181E76:: @ 8181E76
	.string "동전이 모자라네요$"

UnknownString_8181E93: @ 8181E93
	.string "{STR_VAR_1}{K_EULREUL}\n"
	.string "놓을 장소가 없습니다!$"

MauvilleCity_GameCorner_Text_181EC2:: @ 8181EC2
	.string "어머 그렇군요\n"
	.string "동전 모아서 와주세요!$"

MauvilleCity_GameCorner_Text_181F08:: @ 8181F08
	.string "여기 있습니다!$"

UnknownString_8181F15: @ 8181F15
	.string "그 이상 가지실 수 없습니다$"

MauvilleCity_GameCorner_Text_181F3D:: @ 8181F3D
	.string "실수로 같은 인형을\n"
	.string "2개씩이나 사고 말았어!\p"
	.string "하나 줄까?$"

MauvilleCity_GameCorner_Text_181F89:: @ 8181F89
	.string "자 여기 받아!$"

MauvilleCity_GameCorner_Text_181F97:: @ 8181F97
	.string "음? 갖고 싶지만\n"
	.string "지금은 안 되는 거야-?$"

MauvilleCity_GameCorner_Text_181FBC:: @ 8181FBC
	.string "그런 말 하지 말고 받아!$"

MauvilleCity_GameCorner_Text_181FE9:: @ 8181FE9
	.string "갖고 싶은 경품이 있어서\n"
	.string "당첨을 노리고 있어!$"

MauvilleCity_GameCorner_Text_18201E:: @ 818201E
	.string "여기서 놀려면\n"
	.string "동전케이스가 필요하다고!\p"
	.string "갖고 싶으면 옆집의\n"
	.string "누나한테 가보는 건 어때?$"

MauvilleCity_GameCorner_Text_18208E:: @ 818208E
	.string "오늘은 계속 이겨서 말이야!\n"
	.string "너에게도 동전을 나눠주도록 하지!$"

MauvilleCity_GameCorner_Text_1820DD:: @ 81820DD
	.string "아저씨는 보라시티에 오면\n"
	.string "항상 게임코너에서 논단다\p"
	.string "뭔가 다른 곳과 비교해서\n"
	.string "접하기 쉬운 느낌이 들지$"

MauvilleCity_GameCorner_Text_182120:: @ 8182120
	.string "룰렛은 노는 테이블마다\n"
	.string "내는 동전의 개수가 다르단다\p"
	.string "가지고 있는 동전을 세서\n"
	.string "놀 테이블을 고르도록 해라!$"

MauvilleCity_GameCorner_Text_18217C:: @ 818217C
	.string "히익- 슬롯머신을 하다 보면\n"
	.string "할 일을 잊어버린다니까$"

MauvilleCity_GameCorner_Text_1821C1:: @ 81821C1
	.string "이 게임코너에서는\n"
	.string "동전을 써서 놀아$"

MauvilleCity_GameCorner_Text_1821F3:: @ 81821F3
	.string "이 룰렛은\n"
	.string "큰 걸 터뜨리려고 하면\l"
	.string "꽤 이기기 힘든데\l"
	.string "꽤 그만두기가 힘들단 말이지$"

MauvilleCity_GameCorner_Text_182241:: @ 8182241
	.string "슬롯머신은 동전 1개만 있어도\n"
	.string "즐길 수 있지만\l"
	.string "3개를 거는 게 좋지 않을까?\p"
	.string "당첨될 확률이 높아지거든!$"

MauvilleCity_GameCorner_Text_182272:: @ 8182272
	.string "너는 “7”을 노려서 멈출 수 있니?\p"
	.string "BD 타임에서 “7”을 노려서\n"
	.string "딱 멈출 수 있으면\l"
	.string "코인이 잔뜩 불어나게 돼$"

MauvilleCity_GameCorner_Text_1822F4:: @ 81822F4
	.string "슬롯머신에 대해 도움 되는 정보를\n"
	.string "너에게 알려줄게!\p"
	.string "번개가 많이 붙어 있을수록\n"
	.string "BD 타임의 횟수가 늘어나!\p"
	.string "최대 5번까지의 BD 타임으로\n"
	.string "레귤러 보너스를 4번 받고\p"
	.string "빅 보너스를 맞추게 되면\n"
	.string "동전을 660개나 얻을 수 있어!$"

MauvilleCity_GameCorner_Text_182420:: @ 8182420
	.string "동전케이스를\n"
	.string "가지고 있지 않으면 놀 수 없어!$"
