MauvilleCity_House2_Text_18244E:: @ 818244E
	.string "자전거에 타면\n"
	.string "잿빛도시도 금방인데...\p"
	.string "그리고 잿빛도시의 프렌들리숍에서\n"
	.string "항구메일을 살 수 있는데...$"

MauvilleCity_House2_Text_1824D8:: @ 81824D8
	.string "그거! 항구메일이잖아!\n"
	.string "동전케이스랑 바꾸지 않을래?$"

MauvilleCity_House2_Text_182515:: @ 8182515
	.string "정말 기뻐!\n"
	.string "그럼 동전케이스랑 교환하자!$"

MauvilleCity_House2_Text_182549:: @ 8182549
	.string "동전케이스가 있으면 게임코너에서\n"
	.string "룰렛이나 슬롯을\l"
	.string "즐길 수 있어!$"

MauvilleCity_House2_Text_182578:: @ 8182578
	.string "그래... 아쉽네\p"
	.string "동전케이스가 있으면 게임코너에서\n"
	.string "룰렛이나 슬롯을\l"
	.string "즐길 수 있는데...$"
