MauvilleCity_Gym_Text_180815:: @ 8180815
	.string "잘 있었나!!\n"
	.string "챔피언을 노리는 {PLAYER}!!\p"
	.string "보라시티의 체육관 관장 암페어는\n"
	.string "전기타입 포켓몬 사용자다!\p"
	.string "물타입의 포켓몬으로 대항하면\n"
	.string "찌릿찌릿 마비가 올지도 몰라!\p"
	.string "게다가 스위치로 여는\n"
	.string "묘한 문의 장치를\l"
	.string "체육관에 만들어버렸어!\p"
	.string "그럼 힘내-!$"

MauvilleCity_Gym_Text_18091D:: @ 818091D
	.string "이럴 수가 깜짝 놀랐구나!\n"
	.string "네 덕분에 문이 열렸어!$"

MauvilleCity_Gym_Text_180956:: @ 8180956
	.string "짜릿한 My heart로\n"
	.string "네 야망을 조각조각 내주마!$"

MauvilleCity_Gym_Text_180997:: @ 8180997
	.string "짜릿한 승부였다...$"

MauvilleCity_Gym_Text_1809D1:: @ 81809D1
	.string "포켓몬도 로큰롤도\n"
	.string "heart가 everything! 예-!$"

MauvilleCity_Gym_Text_180A05:: @ 8180A05
	.string "암페어님 밑에서 수련한 이 몸을\n"
	.string "간단히 쓰러뜨릴 수는 없을 거다!$"

MauvilleCity_Gym_Text_180A42:: @ 8180A42
	.string "기타나 쳐야지...$"

MauvilleCity_Gym_Text_180A5E:: @ 8180A5E
	.string "이 체육관의 관장인 암페어님은\n"
	.string "네 아버지가 태어나기도 전부터\l"
	.string "포켓몬과 함께한\l"
	.string "강자 중의 강자라고!$"

MauvilleCity_Gym_Text_180AE0:: @ 8180AE0
	.string "이 포켓몬체육관에는\n"
	.string "참 재미있는 장치가 있구나!$"

MauvilleCity_Gym_Text_180B06:: @ 8180B06
	.string "지는 건 재미없어$"

MauvilleCity_Gym_Text_180B1D:: @ 8180B1D
	.string "암페어님은 스위치로\n"
	.string "여러 가지 장치를 만드는 게 취미래!$"

MauvilleCity_Gym_Text_180B5A:: @ 8180B5A
	.string "나의 매력과 포켓몬의 기술로\n"
	.string "짜릿하게 만들어 줄게!$"

MauvilleCity_Gym_Text_180B93:: @ 8180B93
	.string "넌 정말 짜릿하게 강하구나!$"

MauvilleCity_Gym_Text_180BAE:: @ 8180BAE
	.string "이곳 보라시티는\n"
	.string "암페어님이 만들었다고 해\p"
	.string "우리가 태어나기도 전부터\n"
	.string "트레이너였으니까\l"
	.string "분명히 모르는 게 없을 거야$"

MauvilleCity_Gym_Text_180C32:: @ 8180C32
	.string "마을을 개조하는 계획도\n"
	.string "포기했으니\p"
	.string "지금은 이 체육관의 문의 장치를\n"
	.string "만드는 데 몰두하고 있지!\p"
	.string "...어라? 너\n"
	.string "왜 내 앞에 있지?\p"
	.string "뭐라-! 문의 장치를\n"
	.string "통과해서 왔다는 건가!\p"
	.string "와하하하핫!\n"
	.string "재미있구만!\p"
	.string "보라시티 체육관의 관장\n"
	.string "이 암페어가 찌리릿\l"
	.string "찌릿찌릿 전율하게 만들어주지$"

MauvilleCity_Gym_Text_180D64:: @ 8180D64
	.string "와하하하핫!\n"
	.string "내가 졌다!\p"
	.string "너에게 내가 마비되었군\n"
	.string "이 배지를 가져가도록 하게!$"

MauvilleCity_Gym_Text_180DAF:: @ 8180DAF
	.string "{PLAYER}{K_EUNNEUN} 암페어로부터\n"
	.string "다이나모배지를 받았다!$"

MauvilleCity_Gym_Text_180DDA:: @ 8180DDA
	.string "다이나모배지를 가지고 있으면\n"
	.string "비전기술인 바위깨기를\l"
	.string "사용할 수 있게 된다네!\p"
	.string "게다가 자네의 포켓몬의 스피드가\n"
	.string "조금 빨라질 거라네!\p"
	.string "음...\n"
	.string "이것도 가져가게!$"

MauvilleCity_Gym_Text_180E76:: @ 8180E76
	.string "그 기술머신34에는\n"
	.string "전격파가 들어 있다!\p"
	.string "반드시 명중하는\n"
	.string "믿음직한 기술이라고!$"

MauvilleCity_Gym_Text_180EDB:: @ 8180EDB
	.string "장래성이 있는 젊은이의 출현\n"
	.string "정말로 기대가 되는군!$"

MauvilleCity_Gym_Text_180F1D:: @ 8180F1D
	.string "와하하하하!\n"
	.string "젊은이여 더욱 힘내거라!$"

MauvilleCity_Gym_Text_180F4A:: @ 8180F4A
	.string "보라시티 포켓몬체육관$"

MauvilleCity_Gym_Text_180F64:: @ 8180F64
	.string "보라시티 포켓몬체육관\p"
	.string "암페어 인정 트레이너!\n"
	.string "{PLAYER}$"
