MauvilleCity_House1_Text_181B1A:: @ 8181B1A
	.string "헛!\n"
	.string "네 포켓몬은\l"
	.string "꽤 강해 보이는구나!\p"
	.string "좋아 마음에 들었어!\n"
	.string "이 비전머신을 주지!$"

MauvilleCity_House1_Text_181B64:: @ 8181B64
	.string "그것은 비전머신 “바위깨기”!\p"
	.string "너의 앞길을\n"
	.string "큰 바위가 막아도\p"
	.string "그 비전기술을 쓰면\n"
	.string "부술 수 있을 거야!$"

MauvilleCity_House1_Text_181BF6:: @ 8181BF6
	.string "그래그래\n"
	.string "바위를 부수면 숨어 있던\l"
	.string "포켓몬이 튀어나올 수도 있어!$"
