MauvilleCity_BikeShop_Text_180F9F:: @ 8180F9F
	.string "어라? 이거 참 꽤나\n"
	.string "활기찬 손님이 오셨군!\p"
	.string "사람들은 날\n"
	.string "미스터 카제노라 부르지\l"
	.string "이 사이클숍의 오너란다!$"

MauvilleCity_BikeShop_Text_181016:: @ 8181016
	.string "카제노: 네 러닝슈즈...\n"
	.string "굉장히 지저분한데\l"
	.string "어디 멀리서 왔니?$"

MauvilleCity_BikeShop_Text_181067:: @ 8181067
	.string "카제노: 그러니?\n"
	.string "그럼 내 자전거는\l"
	.string "필요 없을 것 같구나$"

MauvilleCity_BikeShop_Text_1810B1:: @ 81810B1
	.string "카제노: 흠흠...\n"
	.string "... ... ...\p"
	.string "뭐라고 미로마을에서 이곳까지!?\n"
	.string "굉장히 먼 곳이잖아!\p"
	.string "내 자전거가 있으면\n"
	.string "기분 좋은 바람을 느끼며\l"
	.string "여러 곳에 편하게 갈 수 있을 텐데!\p"
	.string "좋-아!\n"
	.string "너에게 자전거를 줄게!\p"
	.string "아니 잠깐만 기다려!\p"
	.string "자전거에는 두 가지\n"
	.string "타입이 있다는 걸 잊고 있었군!\p"
	.string "그건 말이지...\n"
	.string "마하자전거와 더트자전거야!\p"
	.string "마하자전거는\n"
	.string "온몸으로 바람을\l"
	.string "느끼고 싶은 사람에게!\p"
	.string "더트자전거는\n"
	.string "테크닉을 즐기고 싶은 사람에게!\p"
	.string "아저씨는 친절한 사람이니까\n"
	.string "네가 좋아하는 쪽을 주겠어!\p"
	.string "자! 어느 쪽을 선택할래?$"

MauvilleCity_BikeShop_Text_181332:: @ 8181332
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "마하자전거를 선택했다!$"

MauvilleCity_BikeShop_Text_18134A:: @ 818134A
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "더트자전거를 선택했다!$"

MauvilleCity_BikeShop_Text_181362:: @ 8181362
	.string "카제노: 만일 다른 타입으로\n"
	.string "교환하고 싶을 때는\l"
	.string "언제든지 내게 말을 걸어 주렴!$"

MauvilleCity_BikeShop_Text_1813A0:: @ 81813A0
	.string "카제노: 응? 다른 타입의\n"
	.string "자전거로 갈아타고 싶어진 거냐?$"

MauvilleCity_BikeShop_Text_1813D4:: @ 81813D4
	.string "카제노: 그럼 네가 지금 가지고 있는\n"
	.string "자전거와 교환해주지!$"

MauvilleCity_BikeShop_Text_181408:: @ 8181408
	.string "{PLAYER}{K_EUNNEUN} 마하자전거를\n"
	.string "더트자전거로 교환 받았다!$"

MauvilleCity_BikeShop_Text_181439:: @ 8181439
	.string "{PLAYER}{K_EUNNEUN} 더트자전거를\n"
	.string "마하자전거로 교환 받았다!$"

MauvilleCity_BikeShop_Text_181469:: @ 8181469
	.string "카제노: 그래 그래!\n"
	.string "맘에 들어하니 기쁘구나!$"

MauvilleCity_BikeShop_Text_181498:: @ 8181498
	.string "응?\n"
	.string "너에게 주었던 자전거는 어쨌니?\p"
	.string "그렇군 PC에 맡겨놓았구나\p"
	.string "PC에서 꺼내서 가지고 오면\n"
	.string "교환해줄게!\p"
	.string "너의 모험이...\n"
	.string "순조롭게 풀리길 기원하마!$"

MauvilleCity_BikeShop_Text_181568:: @ 8181568
	.string "나는 여기에서 일하면서\n"
	.string "자전거를 공부하고 있어\p"
	.string "자전거 타는 방법 중에\n"
	.string "잘 모르는 것이 있으면\p"
	.string "안쪽 방에 설명서가 있으니까\n"
	.string "그걸 읽어보는 게 좋아!$"

MauvilleCity_BikeShop_Text_1815EA:: @ 81815EA
	.string "마하자전거의\n"
	.string "설명서가 놓여 있다!\p"
	.string "어느 페이지를 읽어볼까?$"

MauvilleCity_BikeShop_Text_18162C:: @ 818162C
	.string "십자 버튼을\n"
	.string "조작하는 방향으로\l"
	.string "자전거가 달립니다!\p"
	.string "멈추고 싶을 때는\n"
	.string "십자 버튼에서\l"
	.string "손을 떼십시오!\p"
	.string "속도가 느려지면서\n"
	.string "자연스레 멈추게 됩니다!\p"
	.string "... 다른 페이지를 읽겠습니까?$"

MauvilleCity_BikeShop_Text_1816F5:: @ 81816F5
	.string "마하자전거는 스피드가 빨라\n"
	.string "갑자기 멈출 수는 없습니다\p"
	.string "돌기 위해서는 약간의 요령이\n"
	.string "필요합니다\p"
	.string "돌고 싶은 곳보다 조금 앞에서\n"
	.string "십자 버튼에서\l"
	.string "손을 떼 보십시오\l"
	.string "스피드를 떨어뜨려\l"
	.string "돌 수 있을 겁니다!\p"
	.string "... 다른 페이지를 읽겠습니까?$"

MauvilleCity_BikeShop_Text_1817BF:: @ 81817BF
	.string "호연지방에는 여기저기에\n"
	.string "모래 비탈길이 있습니다!\p"
	.string "모래 비탈길은\n"
	.string "무너지기 쉽기 때문에\l"
	.string "일반적으로는 넘어갈 수 없지만\l"
	.string "마하자전거를 타고 있으면\l"
	.string "놀랍게도 넘어갈 수 있습니다!\p"
	.string "... 다른 페이지를 읽겠습니까?$"

MauvilleCity_BikeShop_Text_181892:: @ 8181892
	.string "더트자전거의\n"
	.string "설명서가 놓여 있다!\p"
	.string "어느 페이지를 읽어볼까?$"

MauvilleCity_BikeShop_Text_1818D4:: @ 81818D4
	.string "자전거를 타고 B 버튼을 누르면\n"
	.string "그 장소에서 앞바퀴가 들립니다!\p"
	.string "그 상태에서 십자 버튼을\n"
	.string "조작하면\l"
	.string "앞바퀴를 든 상태로\l"
	.string "달릴 수 있습니다!\p"
	.string "이것이 윌리라고\n"
	.string "불리는 테크닉입니다!\p"
	.string "... 다른 페이지를 읽겠습니까?$"

MauvilleCity_BikeShop_Text_18199A:: @ 818199A
	.string "B 버튼을 누른 채로 있으면\n"
	.string "윌리를 하며 그 장소에서 뿅뿅\l"
	.string "튀어 오를 수 있습니다!\p"
	.string "이것이 다니엘이라\n"
	.string "불리는 테크닉입니다!\p"
	.string "다니엘 상태에서\n"
	.string "달리는 것도 가능합니다!\p"
	.string "... 다른 페이지를 읽겠습니까?$"

MauvilleCity_BikeShop_Text_181A3D:: @ 8181A3D
	.string "더트자전거를 탔을 때\n"
	.string "B 버튼과 동시에\l"
	.string "십자 버튼을 조작하면\l"
	.string "점프합니다!\p"
	.string "옆쪽으로 조작하면 옆으로 점프!\p"
	.string "뒤쪽으로 조작하면 점프하면서\n"
	.string "방향을 바꿀 수 있습니다!\p"
	.string "... 다른 페이지를 읽겠습니까?$"
