MeteorFalls_1F_1R_Text_193237:: @ 8193237 //JP: 170C05
	.string "우효효...!\p"
	.string "이 운석이 있으면\n"
	.string "굴뚝산이...$"

MeteorFalls_1F_1R_Text_193268:: @ 8193268
	.string "우효?\p"
	.string "네가 누군지는 모르겠지만\n"
	.string "우리 {EVIL_TEAM}단의 방해를 한다면\l"
	.string "용서는 하지 않는다!$"

MeteorFalls_1F_1R_Text_1932C5:: @ 81932C5
	.string "멈춰라!\n"
	.string "{EVIL_TEAM}단!\p"
	.string "너희들의 악행은\n"
	.string "우리 {GOOD_TEAM}단이 용서하지 않겠다!$"

MeteorFalls_1F_1R_Text_193320:: @ 8193320
	.string "우효효...!\n"
	.string "{GOOD_TEAM}단까지 온 건가!\p"
	.string "하나하나 상대하는 것도\n"
	.string "귀찮군...\p"
	.string "뭐 됐어!\n"
	.string "운석은 손에 넣었고\l"
	.string "서둘러 굴뚝산에 가볼까!\p"
	.string "우효효!\n"
	.string "안녕이다! 멍청한 {GOOD_TEAM}단!$"

MeteorFalls_1F_1R_Text_1933EC:: @ 81933EC
	.string "너는...?\p"
	.string "... ... ... ...\n"
	.string "... ... ... ...\p"
	.string "그런가 {PLAYER}{K_I}라고 하는군\p"
	.string "나는 마적!\n"
	.string "마그마단을 이끌고 아쿠아단의\l"
	.string "야망을 저지하려고 한다!\p"
	.string "왜냐하면 녀석들 아쿠아단은\n"
	.string "바다를 넓히려고 하면서\p"
	.string "파괴활동을 계속하는\n"
	.string "위험한 집단이니까...\p"
	.string "대지를 각별히 사랑하는\n"
	.string "우리 마그마단의 적이다!$"

MeteorFalls_1F_1R_Text_193584:: @ 8193584
	.string "너는...?\p"
	.string "... ... ... ...\n"
	.string "... ... ... ...\p"
	.string "그런가 {PLAYER}{K_I}라고 하는군\p"
	.string "나는 아강!\n"
	.string "아쿠아단을 이끌고 마그마단의\l"
	.string "야망을 저지하려고 한다!\p"
	.string "왜냐하면 녀석들 마그마단은\n"
	.string "땅을 넓히려고 하면서\p"
	.string "파괴활동을 계속하는\n"
	.string "위험한 집단이니까...\p"
	.string "바다를 각별히 사랑하는\n"
	.string "우리 아쿠아단의 적이다!$"

MeteorFalls_1F_1R_Text_193720:: @ 8193720
	.string "{GOOD_LEADER}님\n"
	.string "도망간 {EVIL_TEAM}단을 쫓아가야죠...$"

MeteorFalls_1F_1R_Text_193747:: @ 8193747
	.string "{GOOD_LEADER}: 그래!\p"
	.string "서두르지 않으면 {EVIL_TEAM}단 녀석들이\n"
	.string "굴뚝산에서 무슨 짓을 할지 모른다!$"

MeteorFalls_1F_1R_Text_1937AA:: @ 81937AA
	.string "{GOOD_LEADER}: {PLAYER} 너도\n"
	.string "{EVIL_TEAM}단에게는 전력을 다해라!\p"
	.string "그럼 작별이다!$"

MeteorFalls_1F_1R_Text_1937EB:: @ 81937EB
	.string "난... 공석박사...\n"
	.string "매일처럼 단풍마을에서 운석의\l"
	.string "연구를 하고 있는 박사인데...\p"
	.string "{EVIL_TEAM}단이라고 하는 녀석들이\n"
	.string "“유성의 폭포로 안내해라!”\l"
	.string "“운석을 발굴해야 하니까”라고\l"
	.string "해서 여기로 데려다주었어...\p"
	.string "하지만 난...\n"
	.string "{EVIL_TEAM}단에게 속았어...\p"
	.string "아아... 이제 그 운석\n"
	.string "내 것이 아니겠지...\p"
	.string "그런데 {EVIL_TEAM}단\n"
	.string "굴뚝산에서 운석을 써서\l"
	.string "뭘 할까...?$"

MeteorFalls_1F_1R_Text_19396A:: @ 819396A
	.string "공석박사: {EVIL_TEAM}단...\n"
	.string "굴뚝산에서 운석을 써서\l"
	.string "뭘 할까...?$"
