MossdeepCity_House1_Text_18D465:: @ 818D465
	.string "으음!\n"
	.string "자네의 {STR_VAR_1}...$"

MossdeepCity_House1_Text_18D475:: @ 818D475
	.string "{STR_VAR_1}{K_EULREUL}\n"
	.string "좋아하는구먼!\p"
	.string "아냐 틀림없이 {STR_VAR_1}{K_EULREUL}\n"
	.string "좋아하는 거라네!$"

MossdeepCity_House1_Text_18D4C0:: @ 818D4C0
	.string "포켓몬스넥을 좋아하지도\n"
	.string "싫어하지도 않는 것 같군$"

MossdeepCity_House1_Text_18D4F1:: @ 818D4F1
	.string "우리 남편은 보는 것만으로\n"
	.string "포켓몬이 좋아하는\l"
	.string "포켓몬스넥을 알 수 있어$"
