MossdeepCity_SpaceCenter_2F_Text_18E483:: @ 818E483 //JP: 16C783
	.string "이끼시티는 날씨가 좋은 날이 많고\n"
	.string "바람의 방향도 안정적이지\p"
	.string "로켓을 쏘아 올리기에\n"
	.string "안성맞춤인 장소로군$"

MossdeepCity_SpaceCenter_2F_Text_18E4EE:: @ 818E4EE
	.string "나도 조금만 더 젊었더라면\n"
	.string "우주 비행사를 꿈꿔 볼 텐데...\p"
	.string "아니지 지금부터라도 늦지 않아!\n"
	.string "좋-아 힘내자-!!$"

MossdeepCity_SpaceCenter_2F_Text_18E564:: @ 818E564
	.string "언젠가 평범한 사람들도\n"
	.string "우주에 갈 수 있게 되면 좋겠다...$"
