MossdeepCity_SpaceCenter_1F_Text_18E1F3:: @ 818E1F3 //JP: 16C511
	.string "이제 곧 로켓 발사할 거야!$"

MossdeepCity_SpaceCenter_1F_Text_18E214:: @ 818E214
	.string "로켓이 발사됐어!\n"
	.string "이걸로 {STR_VAR_1}번 발사 성공이야!$"

MossdeepCity_SpaceCenter_1F_Text_18E251:: @ 818E251
	.string "로켓을 발사하기 위해서는\n"
	.string "1퍼센트의 미스도 용납되지 않아\p"
	.string "99퍼센트 문제가 없다고 해도\n"
	.string "1퍼센트의 미스가 있다면 모든 게\l"
	.string "실패하게 되는 혹독한 세계야\p"
	.string "그래도 반드시 성공시키려고 하는 건\n"
	.string "거기에 로망이 가득 차 있으니까$"

MossdeepCity_SpaceCenter_1F_Text_18E335:: @ 818E335
	.string "해안에서 산책하면서\n"
	.string "이걸 발견했는데\l"
	.string "난 필요 없으니까 너 줄게!$"

MossdeepCity_SpaceCenter_1F_Text_18E39B:: @ 818E39B
	.string "예로부터 호연지방은\n"
	.string "운석이 많은 곳으로\l"
	.string "유명했어$"

MossdeepCity_SpaceCenter_1F_Text_18E3E5:: @ 818E3E5
	.string "사람에 따라\n"
	.string "포켓몬은 우주에서 왔어!\l"
	.string "라고 하는 사람도 있는데\l"
	.string "이거 진짜일까?$"

MossdeepCity_SpaceCenter_1F_Text_18E427:: @ 818E427
	.string "거대한 철 덩어리가\n"
	.string "창공을 뚫고\l"
	.string "우주까지 날아간다...\p"
	.string "정말 대박인 거 같아$"
