MossdeepCity_StevensHouse_Text_18DA77:: @ 818DA77 //JP: 16C0A4
	.string "성호: {PLAYER}?\p"
	.string "응... 여기가 우리 집\n"
	.string "아무것도 없으니까 조금 창피하네\p"
	.string "맞다\n"
	.string "이 비전머신을 가지고 가도록 해\p"
	.string "다이빙이 들어 있는데\n"
	.string "나는 이미 포켓몬에게 가르쳤으니까$"

MossdeepCity_StevensHouse_Text_18DB22:: @ 818DB22
	.string "성호: 파도타기를 하고 있으면\n"
	.string "물의 색이 진한 곳이 있어\p"
	.string "거기서 다이빙을 사용하면\n"
	.string "바닷속 깊은 곳으로\l"
	.string "잠수해서 들어갈 수 있어\p"
	.string "다시 떠오르고 싶을 때는\n"
	.string "다시 한 번 다이빙을 써\p"
	.string "장소에 따라\n"
	.string "떠오를 수 없는 경우도 있지만$"

MossdeepCity_StevensHouse_Text_18DC25:: @ 818DC25
	.string "성호: 이 이끼시티와\n"
	.string "루네시티 사이에는\l"
	.string "해저동굴이 있는 듯해\p"
	.string "해양관장이 잠수정으로\n"
	.string "발견했다고 한 거 말야\p"
	.string "해저동굴...\n"
	.string "희귀한 돌을 찾을지도 모르겠군\l"
	.string "한번 잠수해서 들어가 볼까$"

MossdeepCity_StevensHouse_Text_18DD12:: @ 818DD12
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "몬스터볼을 조사했다!\p"
	.string "몬스터볼 안에는\n"
	.string "포켓몬 메탕이 들어 있다!\p"
	.string "몬스터볼을 가지고 가겠습니까?$"

MossdeepCity_StevensHouse_Text_18DD61:: @ 818DD61
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "메탕을 손에 넣었다!$"

MossdeepCity_StevensHouse_Text_18DD77:: @ 818DD77
	.string "이 이상 포켓몬을 들 수 없다!$"

MossdeepCity_StevensHouse_Text_18DD9E:: @ 818DD9E
	.string "{PLAYER}{K_EUNNEUN} 몬스터볼을\n"
	.string "그대로 놔두었다$"

MossdeepCity_StevensHouse_Text_18DDC2:: @ 818DDC2
	.string "편지가 있다!\p"
	.string "... ... ... ...\p"
	.string "{PLAYER}에게\p"
	.string "난 생각할 게 좀 있어서\n"
	.string "조만간 수행을 계속할 거야\l"
	.string "당분간은 집에 돌아갈 생각이 없어\p"
	.string "그래서 부탁 하나 할게\p"
	.string "책상 위에 있는\n"
	.string "몬스터볼을 받아 줬으면 해\p"
	.string "안에 들어 있는 건 메탕이라는\n"
	.string "내가 좋아하는 포켓몬이니까\l"
	.string "그 포켓몬을 잘 부탁해\p"
	.string "그럼 또 어딘가에서 만나자!\p"
	.string "나성호$"

MossdeepCity_StevensHouse_Text_18DF1A:: @ 818DF1A
	.string "편지가 있다!\p"
	.string "... ... ... ...\p"
	.string "{PLAYER}에게\p"
	.string "난 생각할 게 좀 있어서\n"
	.string "조만간 수행을 계속할 거야\l"
	.string "당분간은 집에 돌아갈 생각이 없어\p"
	.string "그래서 부탁 하나 할게\p"
	.string "책상 위에 있는\n"
	.string "몬스터볼을 받아 줬으면 해\p"
	.string "안에 들어 있는 건 메탕이라는\n"
	.string "내가 좋아하는 포켓몬이니까\l"
	.string "그 포켓몬을 잘 부탁해\p"
	.string "괜찮다면 비전머신\n"
	.string "다이빙도 가지고 가도록 해\p"
	.string "그럼 또 어딘가에서 만나자!\p"
	.string "나성호가$"

MossdeepCity_StevensHouse_Text_18E0A3:: @ 818E0A3
	.string "성호가 모은\n"
	.string "희귀한 돌이 장식되어 있다!$"
