MossdeepCity_Text_1690A9:: @ 81690A9
	.string "이거... 성호님한테 받은 건데\n"
	.string "도무지 뭔지 잘 모르겠어!\p"
	.string "왕의징표석이라고 하는 거 같은데\n"
	.string "너 가질래?$"

MossdeepCity_Text_169117:: @ 8169117
	.string "이걸 가지고 싶어 하다니\n"
	.string "너도 참 별나구나!\p"
	.string "줄 순 있는데 그 대신\n"
	.string "성호님한테는 비밀이야!$"

MossdeepCity_Text_16916F:: @ 816916F
	.string "돌 모으는 게 그렇게 재미있나?\n"
	.string "이해를 못 하겠네!$"

MossdeepCity_Text_1691A7:: @ 81691A7
	.string "너도 그렇지! 이런 이상한 돌을 받아도\n"
	.string "어떻게 해야 할지 모르겠다니까!$"

MossdeepCity_Text_1691F2:: @ 81691F2
	.string "이 이끼시티 주변에서는\n"
	.string "야생 고래왕자를 볼 수 있어\p"
	.string "그걸 음...\n"
	.string "뭐라고 하더라...\p"
	.string "고래 고래 고래...\p"
	.string "그래! 고래왕자 워칭이라고 했었다!$"

MossdeepCity_Text_169266:: @ 8169266
	.string "섬에 있는 우주센터에서는\n"
	.string "엄청난 로켓을 날리고 있어!$"

MossdeepCity_Text_1692A1:: @ 81692A1
	.string "해안시티에 있는 동료한테\n"
	.string "고래왕자가 없어졌어! 라는\l"
	.string "연락을 받았어\p"
	.string "이거 도대체 해안시티에서\n"
	.string "무슨 일이 일어나고 있는 거지?$"

MossdeepCity_Text_169314:: @ 8169314
	.string "이 섬이...\p"
	.string "...아니요!\n"
	.string "전 세계가!\p"
	.string "전부 자연으로\n"
	.string "가득 차면 좋을 텐데!$"

MossdeepCity_Text_169370:: @ 8169370
	.string "생명의 근원은 모두 바다에서 태어나\n"
	.string "육지로 올라왔다\p"
	.string "자기 역할을 다한 생명은\n"
	.string "모두 흙이 되어 대지로 돌아가지\p"
	.string "그리고 바다와 대지는\n"
	.string "언제나 연결되어 있어...\p"
	.string "그래 저 해안선처럼$"

MossdeepCity_Text_16944E:: @ 816944E
	.string "배 여행도 좋지만 말이지\p"
	.string "포켓몬과 함께 파도타기로\n"
	.string "바다를 이동하면 말로 표현하기 힘든\l"
	.string "상쾌함을 느낄 수 있다네...\p"
	.string "그렇게 생각 안 하나? 젊은이$"

MossdeepCity_Text_1694DA:: @ 81694DA
	.string "이 바위는 말야\n"
	.string "우주센터에 있는 모든 사람에게\l"
	.string "정말 소중한 바위야\p"
	.string "로켓이 무사히 날아가길 빌며\n"
	.string "여기에 놓아 두었다더라고!\p"
	.string "너는 소원을 이루고 싶을 때\n"
	.string "어떻게 해?\l"
	.string "별똥별을 보고 빌어?\p"
	.string "나라면 역시 내가\n"
	.string "제일 잘 볼 수 있는 곳에\l"
	.string "소원을 적어 놓을 거 같아!$"

MossdeepCity_Text_1695D3:: @ 81695D3
	.string "하얀 바위다!$"

MossdeepCity_Text_1695E6:: @ 81695E6
	.string "이끼시티 포켓몬체육관\n"
	.string "관장 풍 란\p"
	.string "신비의 콤비네이션!!$"

MossdeepCity_Text_16962F:: @ 816962F
	.string "여기는 이끼시티\n"
	.string "신조는 “포켓몬을 소중히!”$"

MossdeepCity_Text_16965C:: @ 816965C
	.string "“이끼 우주센터”\n"
	.string "우주와 가장 가까운 곳$"
