MossdeepCity_House4_Text_18E0E3:: @ 818E0E3 //JP: 16C499
	.string "내 동생 말이야\n"
	.string "사람들의 비밀기지를 찾아보는 게\l"
	.string "즐겁대!$"

MossdeepCity_House4_Text_18E125:: @ 818E125
	.string "내 동생 말이야\n"
	.string "친구들의 비밀기지에 가서\l"
	.string "포켓몬 승부를 하는 게\l"
	.string "즐겁대!$"

MossdeepCity_House4_Text_18E17E:: @ 818E17E
	.string "혹시 {STR_VAR_1}에\n"
	.string "비밀기지를 만든 사람이 너야?$"

MossdeepCity_House4_Text_18E1A7:: @ 818E1A7
	.string "너 어딘가에 비밀기지를 만들어 봐!\n"
	.string "내가 찾아내 줄 테니까 말야$"

MossdeepCity_House4_Text_18E1E1:: @ 818E1E1
	.string "델케티: 미양?$"
