MossdeepCity_Gym_Text_18C7E3:: @ 818C7E3
	.string "잘 있었나!!\n"
	.string "챔피언을 노리는 {PLAYER}!!\p"
	.string "이 체육관의 체육관 관장은\n"
	.string "에스퍼타입 포켓몬을\l"
	.string "주로 사용하고 있다!\p"
	.string "격투타입이나 독타입\n"
	.string "포켓몬으로 도전했다가는\l"
	.string "생각지도 못한\l"
	.string "데미지를 입게 될 거야!\p"
	.string "게다가 끝내주는\n"
	.string "콤비네이션으로 공격을 펼치지!\p"
	.string "그러니깐 너도 이기기 위해서\n"
	.string "포켓몬과 호흡을 맞춰 싸워봐!$"

MossdeepCity_Gym_Text_18C938:: @ 818C938
	.string "와 이거 믿기지 않는데!!\n"
	.string "너 정말 대단한 트레이너야!$"

MossdeepCity_Gym_Text_18C96A:: @ 818C96A
	.string "승부는 마음이 강한 자가 이기는 법\n"
	.string "마음이 약한 자는 이길 수 없다!$"

MossdeepCity_Gym_Text_18C9BA:: @ 818C9BA
	.string "져버렸군!\n"
	.string "나도 다시 마음을 단련해야겠다!$"

MossdeepCity_Gym_Text_18C9E1:: @ 818C9E1
	.string "망설이는 쪽이 진다\n"
	.string "내가 해주는 충고다!$"

MossdeepCity_Gym_Text_18CA10:: @ 818CA10
	.string "네 재능을 한번 볼까?!$"

MossdeepCity_Gym_Text_18CA28:: @ 818CA28
	.string "정말 훌륭한 재능을 지녔군!$"

MossdeepCity_Gym_Text_18CA48:: @ 818CA48
	.string "세상에 천재가 있다면\n"
	.string "바로 이곳의 체육관 관장들이\l"
	.string "아마 그중 하나겠지...\p"
	.string "하지만 어쩌면 재능은\n"
	.string "네가 더 위일지도 모르겠군...$"

MossdeepCity_Gym_Text_18CAC0:: @ 818CAC0
	.string "후후후...\n"
	.string "염동력으로 몬스터볼을\l"
	.string "공중에 띄워 보이마...\p"
	.string "이야아아아아아압...!\n"
	.string "... ...\l"
	.string "... ... ...\l"
	.string "컨디션이 좋지 못할 때도 있다...$"

MossdeepCity_Gym_Text_18CB46:: @ 818CB46
	.string "포켓몬 승부도\n"
	.string "컨디션이 좋지 않아-!$"

MossdeepCity_Gym_Text_18CB77:: @ 818CB77
	.string "몬스터볼은 너무 컸다\n"
	.string "이 먼지 뭉치라면 반드시...\p"
	.string "후우우우우우우웁...!\n"
	.string "... ...\l"
	.string "아니닷!\l"
	.string "콧바람으로 날린 게 아니란 말이다!$"

MossdeepCity_Gym_Text_18CC1E:: @ 818CC1E
	.string "저에게 지더라도\n"
	.string "풀죽을 필요는 없어요!\p"
	.string "당신이 약한 게 아니라\n"
	.string "제가 너무 강한 거니까 말이에요!$"

MossdeepCity_Gym_Text_18CC83:: @ 818CC83
	.string "당신은 저보다 더 강하네요!$"

MossdeepCity_Gym_Text_18CC9B:: @ 818CC9B
	.string "졌다고 끙끙거리진 않을 거예요\n"
	.string "더욱 수행하면 되니까요!\p"
	.string "긍정이야말로 나의 힘!$"

MossdeepCity_Gym_Text_18CD14:: @ 818CD14
	.string "보인다...\n"
	.string "당신의 미래가 보여...\p"
	.string "날 이기면\n"
	.string "당신의 미래를 가르쳐주지!$"

MossdeepCity_Gym_Text_18CD66:: @ 818CD66
	.string "졌습니다...!$"

MossdeepCity_Gym_Text_18CD73:: @ 818CD73
	.string "당신과 체육관 관장님의 승부...\n"
	.string "엄청나게 격렬한 전개...\p"
	.string "결과는...\n"
	.string "내 입으로는 말할 수 없어...!$"

MossdeepCity_Gym_Text_18CDE0:: @ 818CDE0
	.string "네가 지금까지 밟아온 여정\n"
	.string "네가 겪어온 경험\p"
	.string "그 모든 것을 이용해 나에게 덤벼라!$"

MossdeepCity_Gym_Text_18CE47:: @ 818CE47
	.string "훌륭한 여정이었구나...!$"

MossdeepCity_Gym_Text_18CE6C:: @ 818CE6C
	.string "노력한 자에겐 밝은 미래\n"
	.string "게으른 자에겐 절망적인 내일\p"
	.string "인과응보...\n"
	.string "모든 것은\l"
	.string "자신에게 돌아오는 거야...$"

MossdeepCity_Gym_Text_18CF02:: @ 818CF02
	.string "풍: 에헤헤...체육관 관장이\p"
	.string "란: 우후후...체육관 관장이\p"
	.string "풍: 두 명이나 있어서 놀랐어?\n"
	.string "란: 두 명이나 있어서 놀랐지?\p"
	.string "풍: 우리는 쌍둥이!\n"
	.string "란: 우리는 쌍둥이!\p"
	.string "풍: 굳이 말을 하지 않아도\n"
	.string "란: 서로가 무슨 생각을 하고 있는지\p"
	.string "풍: 자동으로 머릿속에 떠오르니까\n"
	.string "란: 호흡을 척척 맞출 수가 있지!\p"
	.string "풍: 그런 우리들의 콤비네이션을\n"
	.string "란: 과연 네가 깨뜨릴 수 있을까?$"

MossdeepCity_Gym_Text_18D077:: @ 818D077
	.string "풍: 우, 우리들의\n"
	.string "란: 팀워크가...!\p"
	.string "풍: 우리가 졌으니 어쩔 수 없지\n"
	.string "란: 패배를 인정하고 이걸 줄게!$"

MossdeepCity_Gym_Text_18D0F9:: @ 818D0F9
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "풍&란에게 마인드배지를 받았다!$"

MossdeepCity_Gym_Text_18D128:: @ 818D128
	.string "풍: 마인드배지는 포켓몬의\n"
	.string "특수공격과 특수방어를 올리는\l"
	.string "효과를 가지고 있어!\p"
	.string "란: 그리고 비전기술 다이빙도\n"
	.string "사용할 수 있게 돼!\p"
	.string "풍: 그리고 이것도 가져가!$"

MossdeepCity_Gym_Text_18D1CF:: @ 818D1CF
	.string "풍: 그 기술머신04에는\n"
	.string "란: 명상이 들어 있어\p"
	.string "풍: 포켓몬의 특수공격과\n"
	.string "란: 포켓몬의 특수방어를\p"
	.string "풍: 올려주는 기술이야!\n"
	.string "란: 에스퍼 포켓몬에게\l"
	.string "딱 맞는 기술이지!$"

MossdeepCity_Gym_Text_18D273:: @ 818D273
	.string "풍: 남매의 유대감보다\n"
	.string "너와 네 포켓몬의 유대감이\l"
	.string "훨씬 더 강했던 거 같아...\p"
	.string "란: 너라면 더 강해질 수 있어!\n"
	.string "싸워 본 우리들은 알아!$"

MossdeepCity_Gym_Text_18D324:: @ 818D324
	.string "풍: 에헤헤...체육관 관장이\p"
	.string "란: 두 명이나 있어서 놀랐지?\p"
	.string "풍: 어머? 싸울 수 있는 포켓몬이\n"
	.string "란: 한 마리밖에 없네?p"
	.string "풍: 그럼 승부할 수 없어!\n"
	.string "란: 승부를 즐기고 싶으면\l"
	.string "포켓몬을 더 데리고 와!$"

MossdeepCity_Gym_Text_18D40A:: @ 818D40A
	.string "이끼시티 포켓몬체육관$"

MossdeepCity_Gym_Text_18D424:: @ 818D424
	.string "이끼시티 포켓몬체육관\p"
	.string "체육관 관장 풍, 란\n"
	.string "인정 트레이너!\l"
	.string "{PLAYER}$"
