MossdeepCity_House3_Text_18D909:: @ 818D909
	.string "이봐-아! 거기 트레이너!\n"
	.string "대단한낚싯대는 진짜 대단하다고\p"
	.string "해저에 있는 포켓몬까지\n"
	.string "낚아 올릴 수 있으니까 말이다!\p"
	.string "어때? 갖고 싶나?$"

MossdeepCity_House3_Text_18D9A9:: @ 818D9A9
	.string "암 그렇겠지 당연히 갖고 싶겠지!\n"
	.string "대단한낚싯대는 진짜\l"
	.string "대단하니까 말이다!$"

MossdeepCity_House3_Text_18D9E3:: @ 818D9E3
	.string "물이 있는 곳이라면 무조건\n"
	.string "낚싯대를 써보는 게 좋을 거다!$"

MossdeepCity_House3_Text_18DA26:: @ 818DA26
	.string "엉?\n"
	.string "낚시는 싫은감?$"

MossdeepCity_House3_Text_18DA44:: @ 818DA44
	.string "대단한낚싯대로\n"
	.string "해저에 있는 포켓몬을\l"
	.string "낚아 올려보라고!$"
