MtChimney_Text_195760:: @ 8195760
	.string "굴뚝산 명물\n"
	.string "용암전병이 하나에 200원!\l"
	.string "하나 사가렴$"

MtChimney_Text_1957A9:: @ 81957A9
	.string "고마워$"

MtChimney_Text_1957BA:: @ 81957BA
	.string "어머 돈이 없으면\n"
	.string "물건을 살 수 없어$"

MtChimney_Text_1957F7:: @ 81957F7
	.string "어머 그래$"

MtChimney_Text_195806:: @ 8195806
	.string "수수께끼 장치에\n"
	.string "운석이 박혀 있다...\p"
	.string "뭔가의 에너지를\n"
	.string "모으고 있는 듯하다$"

MtChimney_Text_195870:: @ 8195870
	.string "수수께끼 장치에\n"
	.string "운석이 박혀 있다...\p"
	.string "운석을 빼겠습니까?$"

MtChimney_Text_1958C6:: @ 81958C6
	.string "{PLAYER}{K_EUNNEUN} 운석을\n"
	.string "장치에서 빼냈다!$"

MtChimney_Text_1958FC:: @ 81958FC
	.string "{PLAYER}{K_EUNNEUN} 운석을\n"
	.string "그대로 두었다$"

MtChimney_Text_195920:: @ 8195920
	.string "수수께끼 장치...\n"
	.string "전혀 반응하지 않는다...$"

MtChimney_Text_19595C:: @ 819595C
	.string "{0x7A} 울퉁불퉁 산길\n"
	.string "빠져나가면 용암마을$"

MtChimney_Text_19597F:: @ 819597F
	.string "온천욕으로\n"
	.string "리프레쉬하고 왔으니\l"
	.string "나는 지금 누구에게도 지지 않는다네!$"

MtChimney_Text_1959D8:: @ 81959D8
	.string "흠- 이건 뭐-\n"
	.string "대단하구만-$"

MtChimney_Text_195A04:: @ 8195A04
	.string "져버렸구먼... 이래서는\n"
	.string "어디 가서 달인이라고 못 하겠어...$"

MtChimney_Text_195A45:: @ 8195A45
	.string "포켓몬과 한마음이 된다면\n"
	.string "아주 멋진 일을 할 수 있을 것 같군$"

MtChimney_Text_195AAD:: @ 8195AAD
	.string "흠냐- 이건 뭐-\n"
	.string "대단하구만-$"

MtChimney_Text_195AD9:: @ 8195AD9
	.string "자네와 포켓몬은\n"
	.string "한마음인 것 같군$"

MtChimney_Text_195B1C:: @ 8195B1C
	.string "왠지 불타올라서\n"
	.string "승부하고 싶어 참을 수 없어!$"

MtChimney_Text_195B5F:: @ 8195B5F
	.string "뜨거운 승부였어$"

MtChimney_Text_195B84:: @ 8195B84
	.string "굴뚝산의 열기가\n"
	.string "여자를 불태우지$"

MtChimney_Text_195BB2:: @ 8195BB2
	.string "모처럼 굴뚝산에 왔으니\n"
	.string "여기서도 포켓몬을 단련시키고 싶어!$"

MtChimney_Text_195BF9:: @ 8195BF9
	.string "네 배틀 실력은\n"
	.string "마치 분화하는 굴뚝산 같아!$"

MtChimney_Text_195C31:: @ 8195C31
	.string "모처럼 굴뚝산에 왔는데\n"
	.string "관광만 하고 가기엔 너무 아까워\p"
	.string "배틀도 즐기고 싶고\n"
	.string "선물로 전병도 꼭 사 가야지!$"

MtChimney_Text_195CD8:: @ 8195CD8
	.string "온천에 들어갔다 나왔더니\n"
	.string "난 지금 완전 최고의 컨디션이야!\l"
	.string "이길 확률 100%라니까!$"

MtChimney_Text_195D2F:: @ 8195D2F
	.string "으-응? 벌써 몸이 식었나?$"

MtChimney_Text_195D5C:: @ 8195D5C
	.string "한번 더 온천에 들어가야지!\n"
	.string "너도 같이 들어갈래?\p"
	.string "농담이야!$"
