MtPyre_1F_Text_196151:: @ 8196151 //JP: 1731D6
	.string "이 송화산에는\n"
	.string "여러 가지 것들이 떠돌고 있지...\p"
	.string "무슨 일이 일어날지 모른다\n"
	.string "혹시 모르니 이걸 가지고 가게$"

MtPyre_1F_Text_1961CE:: @ 81961CE
	.string "순결의부적을 말이다\n"
	.string "포켓몬에게 지니게 하게\p"
	.string "그럼 야생 포켓몬이\n"
	.string "별로 안 튀어나오게 되지$"

MtPyre_1F_Text_196218:: @ 8196218
	.string "너도 떠나보낸 포켓몬을 보러 왔니?\n"
	.string "포켓몬을 생각하는 마음이\l"
	.string "참 아름답구나$"

MtPyre_1F_Text_196283:: @ 8196283
	.string "여기엔 내가 소중히 키우던\n"
	.string "지그제구리가 편히 잠들어 있다...$"
