MtPyre_2F_Text_1962C6:: @ 81962C6
	.string "테르: 좋아! 담력 훈련을 하는 거야!\n"
	.string "멋진 내 모습을 보면\l"
	.string "그녀가 나에게 더 반하겠지?!\p"
	.string "그래! 널 쓰러뜨리고\n"
	.string "멋진 모습을 보여주겠어!$"

MtPyre_2F_Text_196358:: @ 8196358
	.string "테르: 어이쿠-!$"

MtPyre_2F_Text_196368:: @ 8196368
	.string "테르: 져버렸지만 괜찮아!\n"
	.string "내가 있잖아!\l"
	.string "담력 훈련 같은 건 아무것도 아니라고!$"

MtPyre_2F_Text_1963CB:: @ 81963CB
	.string "테르: 나랑 승부하려면\n"
	.string "포켓몬을 더 데려오라고!\p"
	.string "더 데려와야 내가 그녀 앞에서\n"
	.string "멋진 모습을 보일 수 있으니까!$"

MtPyre_2F_Text_196449:: @ 8196449
	.string "마코: 남자 친구랑\n"
	.string "담력 훈련을 하러 왔어\l"
	.string "엄청 무섭지만\l"
	.string "남자 친구가 있으니까 괜찮아!\p"
	.string "그래! 널 쓰러뜨리는\n"
	.string "남자 친구의 멋진 모습을 보여줄게!$"

MtPyre_2F_Text_1964EB:: @ 81964EB
	.string "마코: 아-앙 무서워-!$"

MtPyre_2F_Text_196504:: @ 8196504
	.string "마코: 우리들은 러브러브니까\n"
	.string "져도 괜찮아!$"

MtPyre_2F_Text_196539:: @ 8196539
	.string "마코: 우리랑 승부하고 싶으면\n"
	.string "포켓몬이 적어도\l"
	.string "두 마리는 있어야 해\p"
	.string "우리 자기는 엄청 강하니까 말이야\n"
	.string "한 마리 가지고는 어림없어$"

MtPyre_2F_Text_1965BB:: @ 81965BB
	.string "귀여웠던 에나비와의 추억...\n"
	.string "떠올리기만 해도 눈물이 자꾸 흘러...$"

MtPyre_2F_Text_196600:: @ 8196600
	.string "아야야야얏... 바닥의 이곳저곳에\n"
	.string "구멍이 뚫려 있는데 보질 못하고\l"
	.string "아저씨 위에서부터 떨어지고 말았어$"

MtPyre_2F_Text_196674:: @ 8196674
	.string "너도 포켓몬을 찾으러 온 건가?\n"
	.string "나중에 온 주제에 건방지군?!$"

MtPyre_2F_Text_1966BE:: @ 81966BE
	.string "흐이이이이이익!\n"
	.string "용서해 주십쇼-!$"

MtPyre_2F_Text_1966E7:: @ 81966E7
	.string "거의 사람이 드나들지 않는 산이니\n"
	.string "희귀한 포켓몬이 있을 것 같았어$"
