MtPyre_3F_Text_19672B:: @ 819672B //JP: 1735C6
	.string "영험하고 신통한 산의 힘으로\n"
	.string "사이코 파워가\l"
	.string "업그레이드된 이 몸을\l"
	.string "고작 어린애인 네가 이길 수 있을까?$"

MtPyre_3F_Text_19679D:: @ 819679D
	.string "업... 업...$"

MtPyre_3F_Text_1967B5:: @ 81967B5
	.string "나의 사이코 파워는 확실히\n"
	.string "올라갔을 텐데...$"

MtPyre_3F_Text_1967EF:: @ 81967EF
	.string "오호호호홋!\p"
	.string "여기는 당신 같은 어린애가\n"
	.string "올 곳이 아니랍니다!$"

MtPyre_3F_Text_19682B:: @ 819682B
	.string "깨끗이 졌어...!$"

MtPyre_3F_Text_196842:: @ 8196842
	.string "아직 수행이 부족하구나...\n"
	.string "정상을 노리겠어...!\p"
	.string "파이팅! 나!$"
