MtPyre_6F_Text_1969FE:: @ 81969FE //JP: 17365F
	.string "여기에 있으면...\n"
	.string "뭔지 모를 힘이 내 안으로 들어와...$"

MtPyre_6F_Text_196A30:: @ 8196A30
	.string "힘이 빠져나간다...$"

MtPyre_6F_Text_196A4C:: @ 8196A4C
	.string "여기에 잠들어 있는 포켓몬들의\n"
	.string "힘이 들어오고 있는 걸까...?$"

MtPyre_6F_Text_196A95:: @ 8196A95
	.string "당신 뒤...\n"
	.string "뭐가 있는 거지...?$"

MtPyre_6F_Text_196AB1:: @ 8196AB1
	.string "뭔가가 사라졌어...$"

MtPyre_6F_Text_196AC9:: @ 8196AC9
	.string "여기에 잠들어 있는 포켓몬들...\n"
	.string "가끔 함께 놀고 있는 것 같아...$"
