NewMauville_Inside_Text_198315:: @ 8198315 //JP: 175AB2
	.string "발전장치에 다가갔지만\n"
	.string "열기가 전해져 온다!\p"
	.string "빨리 멈추는 편이 좋을 것 같다$"

NewMauville_Inside_Text_198395:: @ 8198395
	.string "발전장치가 조용해 졌다$"

NewMauville_Inside_Text_1983B1:: @ 81983B1
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "스위치를 밟았다!\p"
	.string "...딸깍\p"
	.string "... ... ... ...\n"
	.string "... ... ... ...\p"
	.string "발전장치는\n"
	.string "멈춘 듯하다$"
