OldaleTown_PokemonCenter_1F_Text_1748D1:: @ 81748D1
	.string "카운터에 있는 PC는\n"
	.string "포켓몬 트레이너를 위해 놔둔 거야\p"
	.string "너도 자유롭게 써도 돼!$"

OldaleTown_PokemonCenter_1F_Text_174945:: @ 8174945
	.string "포켓몬센터는 정말 굉장해!\p"
	.string "포켓몬을 몇 마리 맡겨도\n"
	.string "돈이 들지 않으니까\l"
	.string "언제든지 안심할 수 있어!$"

OldaleTown_PokemonCenter_1F_Text_1749C0:: @ 81749C0
	.string "최근 포켓몬센터 2층에\n"
	.string "포켓몬 통신 클럽이 생겼던데\p"
	.string "하지만\n"
	.string "지금은 조정 중이래...$"

OldaleTown_PokemonCenter_1F_Text_174A2E:: @ 8174A2E
	.string "최근 포켓몬센터 2층에\n"
	.string "포켓몬 통신 클럽이 생겼어!\p"
	.string "그래서 곧바로 친구하고\n"
	.string "포켓몬 교환을 했지!$"
