OldaleTown_Text_16AEC0:: @ 816AEC0
	.string "잠시 쉬고 싶어서\n"
	.string "리포트를 작성하고 있어$"

OldaleTown_Text_16AEF2:: @ 816AEF2
	.string "난 프렌들리숍의 점원!\n"
	.string "잠깐 따라와 주겠니?$"

OldaleTown_Text_16AF2F:: @ 816AF2F
	.string "여기는 프렌들리숍!\n"
	.string "파란 지붕이 특징이지!\p"
	.string "포켓몬을 잡기 위한 볼이나\n"
	.string "다양한 상품을 팔고 있어!\p"
	.string "너에게는 서비스로\n"
	.string "이걸 줄게!$"

OldaleTown_Text_16AFE1:: @ 816AFE1
	.string "어떤 때라도 쓸 수 있는\n"
	.string "상처약은 경우에 따라서는\l"
	.string "포켓몬센터보다 도움이 돼!$"

OldaleTown_Text_16B045:: @ 816B045
	.string "아--!\n"
	.string "이쪽에 들어오지 말아줘!\p"
	.string "희귀한 포켓몬의 발자국을\n"
	.string "발견했어!\l"
	.string "스케치가 끝날 때까지 기다려줘$"

OldaleTown_Text_16B0CC:: @ 816B0CC
	.string "희귀한 포켓몬의 발자국을\n"
	.string "발견했어!\l"
	.string "스케치가 끝날 때까지 기다려줘$"

OldaleTown_Text_16B12A:: @ 816B12A
	.string "완성한 희귀한\n"
	.string "포켓몬의 발자국 스케치\l"
	.string "자세히 보니 내 발자국이었어...$"

OldaleTown_Text_16B196:: @ 816B196
	.string "봄이: {PLAYER}!\n"
	.string "이쪽 이쪽!\l"
	.string "빨리 돌아가자!$"

OldaleTown_Text_16B1BE:: @ 816B1BE
	.string "휘웅: 나 먼저\n"
	.string "연구소로 돌아갈 테니\l"
	.string "{PLAYER}도 빨리 오라고$"

OldaleTown_Text_16B20E:: @ 816B20E
	.string "여기는 고도마을\n"
	.string "무언가가 희미하게 시작되는 곳$"
