PacifidlogTown_PokemonCenter_1F_Text_178E47:: @ 8178E47
	.string "너의 트레이너카드는 무슨 색이야?\n"
	.string "나는 코퍼야!$"

PacifidlogTown_PokemonCenter_1F_Text_178E79:: @ 8178E79
	.string "황금마을은 코산호들이\n"
	.string "모여 있는 곳 위에 떠 있어\p"
	.string "...라고 말하면\n"
	.string "넌 믿을래?$"

PacifidlogTown_PokemonCenter_1F_Text_178ED9:: @ 8178ED9
	.string "황금마을 사람들의 선조는\n"
	.string "배 위에서 태어나\l"
	.string "배 위에서 죽었다고 하지\p"
	.string "뭔가를 찾기 위해\n"
	.string "그런 삶을 살았다는 모양이야$"
