PacifidlogTown_Text_16CFC5:: @ 816CFC5
	.string "황금마을에서 잿빛도시까지는\n"
	.string "해류의 흐름이 굉장히 격해서\p"
	.string "섣불리 파도타기를 하면\n"
	.string "생각지도 못한 방향으로\l"
	.string "떠내려가 버려$"

PacifidlogTown_Text_16D04A:: @ 816D04A
	.string "어때?! 어때?! 굉장하지?!\n"
	.string "물 위에 집이 있어!\p"
	.string "난 여기서 태어났지롱!$"

PacifidlogTown_Text_16D08A:: @ 816D08A
	.string "황금마을 사람들은\n"
	.string "다들 낚시나 잠수해서 얻은 걸로\l"
	.string "생활하고 있지$"

PacifidlogTown_Text_16D0CE:: @ 816D0CE
	.string "여기는 황금마을\n"
	.string "해님이 물가를 비춰주는 마을$"
