PacifidlogTown_House2_Text_1790C1:: @ 81790C1
	.string "엣헴!!\p"
	.string "내가 포켓몬애호가클럽에서\n"
	.string "제-일 높은 회장의...\p"
	.string "남동생입니다!\p"
	.string "뭐 여기에서 포켓몬과 같이\n"
	.string "바캉스를 즐기고 있답니다!$"

PacifidlogTown_House2_Text_179155:: @ 8179155
	.string "오호!\n"
	.string "당신의 포켓몬...$"

PacifidlogTown_House2_Text_179169:: @ 8179169
	.string "굉장히 잘 따르고 있군요\p"
	.string "이런 귀여운 포켓몬에게는\n"
	.string "이 기술머신이 어떨까요?$"

PacifidlogTown_House2_Text_1791CA:: @ 81791CA
	.string "흐음...\n"
	.string "나쁘지는 않지만 좋지도 않아...\p"
	.string "어버이 트레이너인 당신의\n"
	.string "노력이 필요하겠군요!$"

PacifidlogTown_House2_Text_17922D:: @ 817922D
	.string "왠지 눈매가 사나운데요\p"
	.string "이런 무서운 포켓몬에게는\n"
	.string "이 기술머신이 어떨까요?$"

PacifidlogTown_House2_Text_179283:: @ 8179283
	.string "포켓몬이 많이 따를수록\n"
	.string "은혜갚기의 위력도 높아진다\p"
	.string "별로 따르지 않으면\n"
	.string "화풀이의 위력이 높아진다고!$"

PacifidlogTown_House2_Text_1792F2:: @ 81792F2
	.string "그래그래 앞으로 {STR_VAR_1}일 지나면\n"
	.string "좋은 기술머신이 손에 들어와!\p"
	.string "그때 다시 놀러오도록 해!\n"
	.string "네 포켓몬에게 맞는\l"
	.string "근사한 기술머신을 줄 테니까$"

PacifidlogTown_House2_Text_17938B:: @ 817938B
	.string "루리리: 루리-$"

PacifidlogTown_House2_Text_17939B:: @ 817939B
	.string "굉장히 따르고 있는 듯하다$"

PacifidlogTown_House2_Text_1793CC:: @ 81793CC
	.string "루리리: 루리리!!$"

PacifidlogTown_House2_Text_1793DD:: @ 81793DD
	.string "별로 안 따르는 듯하다...$"
