PacifidlogTown_House3_Text_17940E:: @ 817940E //JP: 15A02D
	.string "트레이너님! 괜찮다면\n"
	.string "나랑 포켓몬 교환하자!\p"
	.string "황금마을에만 있으면 잡을 수 있는\n"
	.string "포켓몬이 정해져 있어서!\p"
	.string "혹시 {STR_VAR_1} 없어?\n"
	.string "내 {STR_VAR_2} 줄게!$"

PacifidlogTown_House3_Text_1794C4:: @ 81794C4
	.string "와아!\n"
	.string "{STR_VAR_1} 정말 푹신푹신하다!$"

PacifidlogTown_House3_Text_1794DF:: @ 81794DF
	.string "그거 {STR_VAR_1} 아니잖아$"

PacifidlogTown_House3_Text_1794ED:: @ 81794ED
	.string "쇼크야...$"

PacifidlogTown_House3_Text_17950A:: @ 817950A
	.string "이렇게 포켓몬 교환하면\n"
	.string "너랑 난 이제 친구지?$"

PacifidlogTown_House3_Text_179541:: @ 8179541
	.string "그거 포켓몬 도감이야?\p"
	.string "그 말은 너 많은 포켓몬이랑\n"
	.string "만났다는 소리 아니야?\p"
	.string "그거 정말 부러워!$"
