PacifidlogTown_House4_Text_17959B:: @ 817959B
	.string "호연의 하늘 높은 곳을 날아가는\n"
	.string "포켓몬을 봤다고\l"
	.string "하는 사람이 있는데\p"
	.string "계속 날아다니고 있는 걸까?\n"
	.string "어딘가에서 쉬었다가\l"
	.string "가기도 할 것 같은데$"

PacifidlogTown_House4_Text_17961F:: @ 817961F
	.string "하늘의 포켓몬!\n"
	.string "하늘의 포켓몬!$"

PacifidlogTown_House4_Text_17963D:: @ 817963D
	.string "넌 어느 마을에서 왔니?$"

PacifidlogTown_House4_Text_179656:: @ 8179656
	.string "예...?\n"
	.string "yeah...마을...?\p"
	.string "모르겠는데 그런 마을은?$"

PacifidlogTown_House4_Text_17968C:: @ 817968C
	.string "아니요라니...\n"
	.string "어디서든 왔을 거 아니야\p"
	.string "서, 설마 너...\n"
	.string "바닷속에서 태어났다는 거야...?$"
