PetalburgWoods_Text_194D71:: @ 8194D71
	.string "음...\n"
	.string "안 보이네...$"

PetalburgWoods_Text_194D92:: @ 8194D92
	.string "어이 자네 이 근처에서\n"
	.string "버섯꼬라는 포켓몬 본 적 없나?\p"
	.string "내가 그 포켓몬을 정말 좋아하거든$"

PetalburgWoods_Text_194DED:: @ 8194DED
	.string "계속 기다리고 있었어\n"
	.string "등화숲에서\l"
	.string "어슬렁어슬렁하면서...\p"
	.string "그러다가 지쳐서 그냥 내가 왔다!$"

PetalburgWoods_Text_194E6B:: @ 8194E6B
	.string "어이! 데봉의 연구원!\p"
	.string "그 서류, 일로 내놔!$"

PetalburgWoods_Text_194E9A:: @ 8194E9A
	.string "으에-!\p"
	.string "자네 포켓몬 트레이너지?\n"
	.string "나 좀 살려줘$"

PetalburgWoods_Text_194EE8:: @ 8194EE8
	.string "...응? 뭐야 넌?\n"
	.string "그 녀석을 도와주려고?\p"
	.string "{EVIL_TEAM}단을 방해하는 녀석은\n"
	.string "설령 아이라도 봐주지 않는다!\l"
	.string "한번 덤벼봐!$"

PetalburgWoods_Text_194F83:: @ 8194F83
	.string "...가, 강하잖아!$"

PetalburgWoods_Text_194FA4:: @ 8194FA4
	.string "에이...{EVIL_TEAM}단을\n"
	.string "방해하다니 이 건방진 녀석!\l"
	.string "다시 한 번 더 덤벼!\p"
	.string "...라고 하고 싶지만\n"
	.string "더 이상 지닌 포켓몬이 없어...\p"
	.string "게다가 금탄도시에도 {EVIL_TEAM}단이\n"
	.string "노리고 있는 게 있으니까!\p"
	.string "오늘은 이 정도로 봐준다!$"

PetalburgWoods_Text_19507E:: @ 819507E
	.string "...휴우\n"
	.string "위험했다!\p"
	.string "자네 덕분에 중요한 서류를\n"
	.string "지킬 수 있었어!\p"
	.string "...아 그래! 감사의 표시로\n"
	.string "이 수퍼볼을 주도록 하지!$"

PetalburgWoods_Text_19510A:: @ 819510A
	.string "...아!? 그러고 보니\n"
	.string "아까 {EVIL_TEAM}단이\p"
	.string "“금탄도시에도\n"
    .string "노리고 있는 게 있다”\l"	
	.string "라고 했었지...?$"

PetalburgWoods_Text_195153:: @ 8195153
	.string "큰일 났다!!\n"
	.string "이러고 있을 시간이 없어!$"

PetalburgWoods_Text_195182:: @ 8195182
	.string "가방이 가득 찼구나\n"
	.string "그럼 이 수퍼볼을 줄 수 없겠네$"

PetalburgWoods_Text_1951BE:: @ 81951BE
	.string "포켓몬을 왕창 잡았어!\p"
	.string "자 가랏!\n"
	.string "나의 벌레포켓몬 팀!$"

PetalburgWoods_Text_195202:: @ 8195202
	.string "포켓몬이 이렇게 많은데\n"
	.string "이길 수 없다니...$"

PetalburgWoods_Text_195232:: @ 8195232
	.string "포켓몬을 많이 잡았더니\n"
	.string "몬스터볼이 부족해졌어$"

PetalburgWoods_Text_19526A:: @ 819526A
	.string "벌레포켓몬을 학교에 가지고 가면\n"
	.string "완전 인기쟁이가 되겠지?!$"

PetalburgWoods_Text_1952AE:: @ 81952AE
	.string "져버리면 인기쟁이가 될 수 없어...$"

PetalburgWoods_Text_1952CC:: @ 81952CC
	.string "큰 벌레포켓몬을 가지고 있기만 해도\n"
	.string "존경받지 않을까?!$"

PetalburgWoods_Text_195306:: @ 8195306
	.string "내 벌레포켓몬 짱 많이 컸어!\n"
	.string "이제 이걸로 또 인기쟁이가 될 거야!$"

PetalburgWoods_Text_195338:: @ 8195338
	.string "져버리면 인기쟁이가 될 수 없어...$"

PetalburgWoods_Text_195356:: @ 8195356
	.string "강한 포켓몬을 가지고 있으면\n"
	.string "인기쟁이가 될 수 있겠지?\l"
	.string "그래서 열심히 키우고 있는 거야!$"

PetalburgWoods_Text_1953AC:: @ 81953AC
	.string "여어! 네 포켓몬 괜찮아?\p"
	.string "지닌 포켓몬이 약해져서\n"
	.string "배틀에 내보내고 싶지 않을 때는\p"
	.string "되도록이면 풀숲을 피해서\n"
	.string "움직이는 게 좋을 거야!$"

PetalburgWoods_Text_19542B:: @ 819542B
	.string "눈에 보이진 않아도\n"
	.string "도구가 떨어져 있을 때가 있어서\l"
	.string "발밑을 찾아보고 있어!$"

PetalburgWoods_Text_19549E:: @ 819549E
	.string "어머! 네가 갖고 있는 그거!\n"
	.string "금탄체육관의 배지!\p"
	.string "그걸 가지고 있다는 건\n"
	.string "너 포켓몬 트레이너구나\p"
	.string "그럼\n"
	.string "이 도구 한번 사용해 보는 건 어때?$"

PetalburgWoods_Text_195503:: @ 8195503
	.string "기적의씨를\n"
	.string "지니게 하면 풀타입\l"
	.string "기술의 위력이 올라가\p"
	.string "기적의씨 외에도\n"
	.string "포켓몬에게 지니게 하면 편리한\l"
	.string "도구가 있다고 하더라고$"

PetalburgWoods_Text_1955B0:: @ 81955B0
	.string "정보 나눔 게시판!!\p"
	.string "승부할 때\n"
	.string "한 번이라도 배틀에 나온 포켓몬은\l"
	.string "경험치를 받을 수 있습니다!\p"
	.string "약한 포켓몬을\n"
	.string "지닌 포켓몬 리스트의\l"
	.string "왼쪽 위에 놓고\l"
	.string "승부할 때 바로 교체!\p"
	.string "이렇게 하면 약한 포켓몬도\n"
	.string "키울 수 있어요!$"

PetalburgWoods_Text_1956A6:: @ 81956A6
	.string "정보 나눔 게시판!!\p"
	.string "포켓몬에게는 히트포인트 외에\n"
	.string "기술을 사용하기 위한 힘의 근원인\l"
	.string "파워포인트가 있습니다\p"
	.string "기술의 파워포인트를\n"
	.string "모두 사용했을 때도\l"
	.string "포켓몬센터로 갑시다!$"
