PetalburgCity_PokemonCenter_1F_Text_17BD30:: @ 817BD30
	.string "PC를 이용한\n"
	.string "포켓몬 맡기기 시스템이라니...\p"
	.string "만든 녀석은 아마\n"
	.string "엄청난 두뇌의 소유자일 거야!$"

PetalburgCity_PokemonCenter_1F_Text_17BD92:: @ 817BD92
	.string "포켓몬한테 오랭열매를 먹였더니\n"
	.string "체력을 회복했다!$"

PetalburgCity_PokemonCenter_1F_Text_17BDC5:: @ 817BDC5
	.string "포켓몬에는\n"
	.string "다양한 타입이 있어!\p"
	.string "그래서 포켓몬 배틀을 할 때는\n"
	.string "타입 상성에 따라\l"
	.string "유리할 때도 있고 불리할 때도 있지$"

PetalburgCity_PokemonCenter_1F_Text_17BE6C:: @ 817BE6C
	.string "예를 들면 너의 나무지기는\n"
	.string "풀타입이니까\p"
	.string "물타입이나 땅타입에 강하고\n"
	.string "불꽃타입에는 약한 거야!$"

PetalburgCity_PokemonCenter_1F_Text_17BEF1:: @ 817BEF1
	.string "예를 들면 너의 아차모는\n"
	.string "불꽃타입이니까\p"
	.string "풀타입이나 벌레타입에 강하고\n"
	.string "물타입에는 약한 거야!$"

PetalburgCity_PokemonCenter_1F_Text_17BF73:: @ 817BF73
	.string "예를 들면 너의 물짱이는\n"
	.string "물타입이니까\p"
	.string "불꽃타입에 강하고 풀타입이나\n"
	.string "전기타입에는 약한 거야!$"
