PetalburgCity_WallysHouse_Text_179805:: @ 8179805
	.string "너는...\n"
	.string "아- {PLAYER}{K_I} 맞지?\p"
	.string "아깐 민진이와 같이 놀아줘서\n"
	.string "고맙구나...\p"
	.string "그 애는 태어났을 때부터\n"
	.string "몸이 그다지 좋지 않거든\p"
	.string "그래서 잔디마을에 있는 친척 집에서\n"
	.string "잠시 동안 신세 좀 지라고 했단다\p"
	.string "거긴 여기보다 훨씬\n"
	.string "공기가 깨끗한 곳이니깐!\p"
	.string "...그래서 민진이 보러 온 거지?\p"
	.string "미안한데\n"
	.string "민진이라면 벌써 출발했단다\p"
	.string "지금이면 어디쯤 갔으려나...$"

PetalburgCity_WallysHouse_Text_179975:: @ 8179975
	.string "민진은 잘 있으려나...$"

PetalburgCity_WallysHouse_Text_179996:: @ 8179996
	.string "안녕 {PLAYER}{K_AYA}!\p"
	.string "우리 민진이가 잔디마을에 갔을\n"
	.string "때보다 훨씬 건강해져서 말이야\p"
	.string "너한테 신세 졌구나!\p"
	.string "그날 네가 포켓몬 잡는 걸\n"
	.string "도와준 덕분에 민진이가\l"
	.string "이렇게 건강해질 수 있었단다\l"
	.string "정말 고맙구나\p"
	.string "우리 민진이한테 너 같은\n"
	.string "상냥한 친구가 있어서\l"
	.string "다행이라고 생각한단다!\p"
	.string "...아 그래!\p"
	.string "보답이라고 하긴 좀 그렇다만\n"
	.string "이걸 너에게 주마$"

PetalburgCity_WallysHouse_Text_179B14:: @ 8179B14
	.string "파도타기를 쓸 수 있게 되면\n"
	.string "포켓몬들과 함께\l"
	.string "바다를 건널 수도 있단다$"

PetalburgCity_WallysHouse_Text_179B5B:: @ 8179B5B
	.string "민진이가\n" 
	.string "곧 돌아온다고 했단다\p"
	.string "빨리 돌아온다면 좋겠구나$"

PetalburgCity_WallysHouse_Text_179B92:: @ 8179B92
	.string "에엥!? 그랜드시티에서\n"
	.string "민진이를 만났다고...?\p"
	.string "에이 {PLAYER}\p"
	.string "그 애가 아무리 건강해졌다고 해도\n"
	.string "그렇게 먼 곳까지\l"
	.string "혼자 갈 수 있을 리가 없잖니...$"

PetalburgCity_WallysHouse_Text_179C2C:: @ 8179C2C
	.string "민진이가 “포켓몬 잡았어!”라며\n"
	.string "정말 기쁜듯이 얘기했단다\p"
	.string "그 애가 그렇게 기뻐하는 모습\n"
	.string "오랜만에 봐$"

PetalburgCity_WallysHouse_Text_179CA1:: @ 8179CA1
	.string "안녕 {PLAYER}{K_AYA}!\n"
	.string "네게 전해줄 것이 있단다\p"
	.string "우리 남편이 가지고 있으니\n"
	.string "직접 물어보도록 하렴$"

PetalburgCity_WallysHouse_Text_179D12:: @ 8179D12
	.string "우리 남편한테는 비밀인데...\p"
	.string "민진이가 아무에게도 말하지 않고\n"
	.string "잔디마을에서 없어졌대...\p"
	.string "민진이는 몸이 약하지만\n"
	.string "어느샌가 갑자기 활기차졌더구나\p"
	.string "그래도 민진이가 반드시 집으로\n"
	.string "돌아올 거라고 난 믿고 있단다!$"
