PetalburgCity_Text_16433E:: @ 816433E
	.string "우리 민진이는 대체 어디까지\n"
	.string "놀러 간 걸까...?\p"
	.string "이제 곧 잔디마을로\n"
	.string "출발해야 할 시간인데...$"

PetalburgCity_Text_16438A:: @ 816438A
	.string "안녕! 혹시...\n"
	.string "신참 트레이너야?\p"
	.string "트레이너가 마을에 도착하면\n"
	.string "가장 먼저 하는 일이 뭔지 알아?\p"
	.string "바로 그 마을의 체육관을\n"
	.string "확인하는 거야!$"

PetalburgCity_Text_164426:: @ 8164426
	.string "보이지? 여기가 바로\n"
    .string "등화도시의 체육관이야$"

PetalburgCity_Text_164449:: @ 8164449
	.string "여기 있는 게 체육관의 간판!\n"
	.string "체육관을 찾을 때 참고하도록 해$"

PetalburgCity_Text_164490:: @ 8164490
	.string "내 얼굴이 수면에 비치고 있어...\p"
	.string "희망에 가득 차\n"
	.string "반짝이는 미소...\p"
	.string "불안과 맞서 싸우는\n"
	.string "조용한 침묵...\p"
	.string "네 얼굴은 어떻게 비치고 있어?$"

PetalburgCity_Text_16453F:: @ 816453F
	.string "이미 포켓몬을 6마리 데리고 있을 때\n"
	.string "새로운 포켓몬을 잡는다\p"
	.string "그러면 PC의 네트워크를 통해서\n"
	.string "자동으로 박스에 보내지게 돼!$"

PetalburgCity_Text_1645BB:: @ 81645BB
	.string "등화도시 포켓몬체육관\n"
	.string "관장 종길\l"
	.string "강함을 추구하는 남자!$"

PetalburgCity_Text_164602:: @ 8164602
	.string "여기는 등화도시\n"
	.string "자연과 사람이 어우러지는 마을$"

PetalburgCity_Text_164634:: @ 8164634
	.string "“민진의 집”$"
