PetalburgCity_Gym_Text_179DF6:: @ 8179DF6
	.string "아빠: ...응?\p"
	.string "{PLAYER}\e잖아!\n"
	.string "이사가 다 끝났나 보구나\p"
	.string "그것보다\n"
	.string "여기까지 잘도 혼자 왔구나\p"
	.string "그렇군...\n"
	.string "포켓몬과 함께인 건가\p"
	.string "흠... 그럼 {PLAYER}\e도\n"
	.string "나 같은\l"
	.string "포켓몬 트레이너가 되는 건가\p"
	.string "그거 기대되는걸!$"

PetalburgCity_Gym_Text_179F07:: @ 8179F07
	.string "저기... 저\n"
	.string "포켓몬이 가지고 싶은데요...$"

PetalburgCity_Gym_Text_179F37:: @ 8179F37
	.string "아빠: 음? 너는... 아마\n"
	.string "민진이라고 했지$"

PetalburgCity_Gym_Text_179F70:: @ 8179F70
	.string "민진: 전 오늘부터 잔디마을의\n"
	.string "친척 집에 가는데\p"
	.string "혼자서는 외로우니까 포켓몬을\n"
	.string "데려갈까 해서요...\p"
	.string "하지만 지금까지 스스로 포켓몬을\n"
	.string "잡아본 적이 없어서\l"
	.string "어떻게 해야 할지...$"

PetalburgCity_Gym_Text_17A03A:: @ 817A03A
	.string "아빠: ...흠 그렇군$"

PetalburgCity_Gym_Text_17A04A:: @ 817A04A
	.string "아빠: {PLAYER}!\n"
	.string "얘기는 들었겠지?\p"
	.string "민진군이 무사히\n"
	.string "포켓몬을 잡을 수 있도록\l"
	.string "잘 지켜봐 주도록 하거라$"

PetalburgCity_Gym_Text_17A0A8:: @ 817A0A8
	.string "민진군\n"
	.string "나의 포켓몬을 빌려주겠네!\p"
	.string "민진은\n"
	.string "지그제구리를 받았다!$"

PetalburgCity_Gym_Text_17A0EB:: @ 817A0EB
	.string "민진: 우와...\n"
	.string "포켓몬이다...!\p"
	.string "아빠: 흠...\n"
	.string "몬스터볼을 줄 테니\l"
	.string "열심히 해봐라!\p"
	.string "민진은\n"
	.string "몬스터볼을 받았다!$"

PetalburgCity_Gym_Text_17A156:: @ 817A156
	.string "민진: 감사합니다...!\n"
	.string "종길님!$"

PetalburgCity_Gym_Text_17A171:: @ 817A171
	.string "저기...{PLAYER}님...\n"
	.string "저랑 같이...\l"
    .string "가주실 거죠...?$"

PetalburgCity_Gym_Text_17A196:: @ 817A196
	.string "아빠: 성공했니?$"

PetalburgCity_Gym_Text_17A1B0:: @ 817A1B0
	.string "민진: 네! 해냈어요!\n"
	.string "빌려주신 포켓몬 돌려 드릴게요\p"
	.string "{PLAYER}님 저랑 같이 가주셔서\n"
	.string "정말 감사했습니다...\p"
	.string "두 분 덕분에\n"
	.string "제 포켓몬을 잡을 수 있었어요!\p"
	.string "제 포켓몬...\n"
	.string "정말 소중히 키울게요\p"
	.string "...엄마가 기다리시니\n"
	.string "이제 가야 해요!\p"
	.string "그럼 안녕히 계세요!$"

PetalburgCity_Gym_Text_17A2A4:: @ 817A2A4
	.string "아빠: 그럼...\p"
	.string "{PLAYER}! 포켓몬 트레이너로서\n"
	.string "강해지고 싶다면\l"
	.string "내 어드바이스를 듣거라\p"
	.string "먼저 이 앞에 있는\n"
	.string "금탄도시로 가거라\p"
	.string "거기서 원규라는 체육관 관장과\n"
	.string "배틀하도록 해!\p"
	.string "그렇게 각 지역의 포켓몬체육관에서\n"
	.string "체육관 관장을 쓰러뜨리고\l"
	.string "체육관 배지를 모아가는 거다\p"
	.string "물론 나도 체육관 관장이다\n"
	.string "언젠가는 {PLAYER}\h 승부를 하겠지\p"
	.string "하지만 그건\n"
	.string "{PLAYER}\r 강해졌을 때의 이야기다$"

PetalburgCity_Gym_Text_17A41E:: @ 817A41E
	.string "아빠: 응? 금탄도시의\n"
	.string "포켓몬체육관에는 가지 않니?\p"
	.string "아직 풋내 나는 트레이너와\n"
	.string "배틀해도 재미가 없지 않니\p"
	.string "{PLAYER}\r 더욱 강해져서\n"
	.string "내 앞에 나타나 줬으면 좋겠구나\p"
	.string "그래 체육관 배지를\n"
	.string "4개 모으면 그때는\l"
	.string "{PLAYER}\h 승부하지!$"

PetalburgCity_Gym_Text_17A518:: @ 817A518
	.string "아빠: 그렇군... 금탄도시의\n"
	.string "체육관 관장에게 이겼구나\p"
	.string "하지만 아직도 {PLAYER}보다\n"
	.string "강한 트레이너는 많이 있다\p"
	.string "바다의 저편 무로마을의 체육관 관장\n"
	.string "그 이름은 철구...\p"
	.string "그하고도 배틀해보도록 해$"

PetalburgCity_Gym_Text_17A5F3:: @ 817A5F3
	.string "아빠: 흠... {PLAYER}\n"
	.string "강해지고 있구나\p"
	.string "그 배지의 수를 보면\n"
	.string "알 수 있어$"

PetalburgCity_Gym_Text_17A653:: @ 817A653
	.string "아빠: 그래...\n"
	.string "체육관 배지 4개를 모았구나\p"
	.string "그럼 약속대로\n"
	.string "포켓몬 승부를 해야겠지...\p"
	.string "{PLAYER}...\p"
	.string "난 지금 이렇게\n"
	.string "내 아이와 진지하게\l"
	.string "승부를 할 수 있다는 게\l"
	.string "매우 기쁘단다!\p"
	.string "하지만 승부는 승부!\p"
	.string "난 체육관 관장으로서\n"
	.string "최선을 다하마!\p"
	.string "{PLAYER}도 진심을 다해\n"
	.string "덤비도록!$"

PetalburgCity_Gym_Text_17A77A:: @ 817A77A
	.string "...!\p"
	.string "설마...\p"
	.string "설마 {PLAYER}에게...\p"
	.string "{PLAYER}에게 질 줄이야...\p"
	.string "...좋다! 규칙은 규칙이다!\n"
	.string "이걸 주도록 하지$"

PetalburgCity_Gym_Text_17A7DD:: @ 817A7DD
	.string "{PLAYER}\s 아빠에게\n"
	.string "밸런스배지를 받았다!!$"

PetalburgCity_Gym_Text_17A805:: @ 817A805
	.string "아빠: 그 밸런스배지로\n"
	.string "{PLAYER}의 포켓몬들의\l"
	.string "방어력이 올라가게 된다\p"
	.string "비전기술 파도타기를\n"
	.string "배운 포켓몬이 있다면\l"
	.string "물 위를 이동할 수 있지\p"
	.string "이건 내가 주는 선물이다\n"
	.string "{PLAYER}\e라면 잘 다룰 수 있겠지!$"

PetalburgCity_Gym_Text_17A8CF:: @ 817A8CF
	.string "아빠: 기술머신42는 객기\p"
    .string "독, 마비, 화상에 걸리면\n"
	.string "기술의 위력이 2배가 되지!\p"
	.string "위기를 기회로\n"
	.string "바꿀 수 있을지도 모른다$"

PetalburgCity_Gym_Text_17A976:: @ 817A976
	.string "아빠: 체육관 관장으로서\n"
	.string "분해서 말이 안 나오는구나...\p"
	.string "하지만 부모로서는\n"
	.string "기쁘면서도 한편으로는\l"
	.string "조금 쓸쓸한 복잡한 기분이야...$"

PetalburgCity_Gym_Text_17A9F6:: @ 817A9F6
	.string "아빠: 아 그래...\p"
	.string "아까 민진이의 부모님께서\n"
	.string "오셔서 {PLAYER}한테\l"
	.string "주실 게 있다고 하셨단다!$"

PetalburgCity_Gym_Text_17AA6B:: @ 817AA6B
	.string "아빠: {PLAYER}! 가끔은 엄마를\n"
	.string "만나러 가도록 해!\p"
	.string "나는 여기서\n"
	.string "스스로를 단련하겠다!\p"
	.string "{PLAYER}에게 진 채로는\n"
	.string "트레이너로서 분하니까 말이야$"

PetalburgCity_Gym_Text_17AB17:: @ 817AB17
	.string "아빠: {PLAYER}!\n"
    .string "상태는 어때?\p"
	.string "세상에는 다양한 포켓몬들이\n"
	.string "잠들어 있다\p"
	.string "{PLAYER}도 더 강해지지 않으면\n"
	.string "앞으로 힘들어질지도 모른다!$"

PetalburgCity_Gym_Text_17AB96:: @ 817AB96
	.string "잘 있었나!!\n"
	.string "챔피언을 노리는 {PLAYER}!!\p"
	.string "이 체육관은 방에 있는 트레이너를\n"
	.string "쓰러뜨리면 안쪽에 있는 문이 열려!\p"
	.string "...앗! 이 방은 이미\n"
	.string "문이 열리게 되어 있으니\l"
	.string "날 쓰러뜨리지는 말아 달라고!\p"
	.string "이곳 등화체육관의 트레이너들은\n"
	.string "다양한 도구를 쓰지!\p"
	.string "참고로 지금 이 방에서\n"
	.string "갈 수 있는 곳은\p"
	.string "왼쪽... 스피드 방과\n"
	.string "오른쪽... 명중의 방이야!\p"
	.string "문에도 쓰여 있으니\n"
	.string "잘 읽고 들어가 봐!\p"
	.string "자! 어느 쪽으로 갈지 정했나?\n"
	.string "그럼 힘내라고-!!$"

PetalburgCity_Gym_Text_17AD49:: @ 817AD49
	.string "{PLAYER}\s 자신의 아버지마저\n"
	.string "뛰어넘은 건가?!\p"
	.string "으아- 정말 기절초풍!!$"

PetalburgCity_Gym_Text_17ADA5:: @ 817ADA5
	.string "상대보다 먼저 공격한다...\p"
	.string "그것만으로도 승부가\n"
	.string "상당히 유리해지겠지?$"

PetalburgCity_Gym_Text_17AE11:: @ 817AE11
	.string "정말 눈부신 승부였다...!$"

PetalburgCity_Gym_Text_17AE30:: @ 817AE30
	.string "안쪽 방으로 향해라!\n"
	.string "더 혹독한 시련이 널 기다리고 있다\p"
	.string "왼쪽은 떨어지지 않는 방\n"
	.string "오른쪽은 방어의 방이다!$"

PetalburgCity_Gym_Text_17AEBB:: @ 817AEBB
	.string "누구한테 이기든\n"
	.string "누구한테 지든\l"
	.string "자신과 포켓몬을 계속 단련시키는 것...\p"
	.string "그게 바로 체육관 관장이야$"

PetalburgCity_Gym_Text_17AF5A:: @ 817AF5A
	.string "내 포켓몬의 능력을\n"
	.string "아무리 낮추려 해도 소용없어!$"

PetalburgCity_Gym_Text_17AF98:: @ 817AF98
	.string "능력은 떨어지지 않았지만\n"
	.string "그래도 이길 수 없었다...$"

PetalburgCity_Gym_Text_17AFD3:: @ 817AFD3
	.string "다음은 힘의 방! 과연 그\n"
	.string "공격력을 버틸 수 있을까?$"

PetalburgCity_Gym_Text_17B016:: @ 817B016
	.string "체육관 관장이 너에게 지고 나서부터\n"
	.string "훈련의 강도가 더 세졌어!$"

PetalburgCity_Gym_Text_17B058:: @ 817B058
	.string "거의 쓰러뜨렸다고 생각했을 때\n"
	.string "상대의 HP가 회복된다\l"
	.string "그게 얼마나 혹독한 일인지...\p"
	.string "그 고통을 맛보게 해주마!$"

PetalburgCity_Gym_Text_17B0F7:: @ 817B0F7
	.string "미처 다 회복하지 못할 정도의...\n"
	.string "엄청난 공격력이다...$"

PetalburgCity_Gym_Text_17B12C:: @ 817B12C
	.string "과연 체육관 관장의 아이군...\p"
	.string "아니지! 트레이너의 재능은\n"
	.string "노력을 바탕으로 만들어지는 것...\p"
	.string "너에게 진 건\n"
	.string "나의 노력이 부족했기 때문이다...!\p"
	.string "자, 다음은 일격의 방이다!$"

PetalburgCity_Gym_Text_17B1F4:: @ 817B1F4
	.string "포켓몬체육관에서 계속 수행해서\n"
	.string "언젠가는 체육관 관장이\l"
	.string "되고야 말겠어$"

PetalburgCity_Gym_Text_17B237:: @ 817B237
	.string "체육관 관장의 아이라고 해서\n"
	.string "봐주지 않을 거야!\p"
	.string "급소를 맞는 두려움을\n"
	.string "실컷 맛보게 해줄게!$"

PetalburgCity_Gym_Text_17B2C0:: @ 817B2C0
	.string "네 실력은 진짜다...!$"

PetalburgCity_Gym_Text_17B2E4:: @ 817B2E4
	.string "네 아빠는 정말 강하면서도\n"
	.string "존경할 수 있는 트레이너야!\p"
	.string "그리고 너에게도\n"
	.string "네 아빠와 같은\l"
	.string "반짝임이 느껴져...\p"
	.string "가족이 서로의 실력을 겨루는\n"
	.string "최고의 명승부를 보여줘!$"

PetalburgCity_Gym_Text_17B39B:: @ 817B39B
	.string "네 아빠가 체육관 관장으로\n"
	.string "오고 나서 등화도시에\l"
	.string "있는 트레이너들도 강해졌어$"

PetalburgCity_Gym_Text_17B3F7:: @ 817B3F7
	.string "후후후...\n"
	.string "여긴 명중의 방!\p"
	.string "모든 공격이 맞게 되면\n"
	.string "꽤 성가실 거야$"

PetalburgCity_Gym_Text_17B454:: @ 817B454
	.string "네가 한 수 위구나...$"

PetalburgCity_Gym_Text_17B46F:: @ 817B46F
	.string "안에는 더욱더 강한 트레이너가\n"
	.string "너를 기다리고 있어\p"
	.string "왼쪽은 방어의 방\n"
	.string "오른쪽은 회복의 방이야\p"
	.string "네 포켓몬의 공격력이\n"
	.string "시험받게 될 거야$"

PetalburgCity_Gym_Text_17B521:: @ 817B521
	.string "넌 우리 같은 트레이너가\n"
	.string "무엇을 목표로 하고 있는지 아니?\p"
	.string "......그건 말야 포켓몬과\n"
	.string "한마음이 되는 거야!$"

PetalburgCity_Gym_Text_17B58D:: @ 817B58D
	.string "방어가 강하면 강할수록\n"
	.string "과감하게 공격할 수 있어$"

PetalburgCity_Gym_Text_17B5CB:: @ 817B5CB
	.string "완벽하게 방어할 수 없었어...$"

PetalburgCity_Gym_Text_17B5EA:: @ 817B5EA
	.string "너에게는 소중한 무언가를\n"
	.string "배운 거 같아...\p"
	.string "자, 그럼 다음으로 가!\n"
	.string "왼쪽은 힘의 방\l"
	.string "오른쪽은 일격의 방\p"
	.string "양쪽 모두\n"
	.string "공격을 중시하고 있어!$"

PetalburgCity_Gym_Text_17B6B5:: @ 817B6B5
	.string "어때? 파도타기는\n"
	.string "잘 쓰고 있어?$"

PetalburgCity_Gym_Text_17B6D4:: @ 817B6D4
	.string "온 힘을 다해 너를\n"
	.string "쓰러뜨리라고\l"
	.string "체육관 관장이 말했어...\p"
	.string "설령 그 상대가\n"
	.string "체육관 관장의 아이라 해도!$"

PetalburgCity_Gym_Text_17B732:: @ 817B732
	.string "모든 힘을 다 쏟아부었는데...!$"

PetalburgCity_Gym_Text_17B749:: @ 817B749
	.string "네가 포켓몬을 다루는 방법...\n"
	.string "어딘지 모르게\l"
	.string "너의 아빠와 닮았어\p"
	.string "자! 이 안쪽에는 체육관 관장,\n"
	.string "네 아빠가 기다리고 있어!$"

PetalburgCity_Gym_Text_17B7C0:: @ 817B7C0
	.string "포켓몬을 강하게 키우는 것도\n"
	.string "좋지만 승부의 승패를\l"
	.string "정하는 건 포켓몬을 생각하는\l"
	.string "그 자신의 마음이야...!$"

PetalburgCity_Gym_Text_17B844:: @ 817B844
	.string "지금 이 문은\n"
	.string "아직 잠겨 있는 것 같다...$"

PetalburgCity_Gym_Text_17B870:: @ 817B870
	.string "이 앞은 스피드의 방\p"
	.string "...이라고 쓰여 있다\n"
	.string "안으로 들어가겠습니까?$"

UnknownString_817B8A8: @ 817B8A8
	.string "지금 이 문은\n"
	.string "아직 잠겨 있는 것 같다...$"

PetalburgCity_Gym_Text_17B8D4:: @ 817B8D4
	.string "이 앞은 명중의 방\p"
	.string "...이라고 쓰여 있다\n"
	.string "안으로 들어가겠습니까?$"

PetalburgCity_Gym_Text_17B90F:: @ 817B90F
	.string "이 앞은 떨어지지 않는 방\p"
	.string "...이라고 쓰여 있다\n"
	.string "안으로 들어가겠습니까?$"

PetalburgCity_Gym_Text_17B950:: @ 817B950
	.string "이 앞은 방어의 방\p"
	.string "...이라고 쓰여 있다\n"
	.string "안으로 들어가겠습니까?$"

PetalburgCity_Gym_Text_17B98A:: @ 817B98A
	.string "이 앞은 회복의 방\p"
	.string "...이라고 쓰여 있다\n"
	.string "안으로 들어가겠습니까?$"

PetalburgCity_Gym_Text_17B9C5:: @ 817B9C5
	.string "이 앞은 힘의 방\p"
	.string "...이라고 쓰여 있다\n"
	.string "안으로 들어가겠습니까?$"

PetalburgCity_Gym_Text_17BA00:: @ 817BA00
	.string "이 앞은 일격의 방\p"
	.string "...이라고 쓰여 있다\n"
	.string "안으로 들어가겠습니까?$"

PetalburgCity_Gym_Text_17BA3D:: @ 817BA3D
	.string "이 앞은 체육관 관장\p"
	.string "어떤 포켓몬이 기다리고 있는지는\n"
	.string "자신의 눈으로 확인해라!\p"
	.string "...라고 쓰여 있다\n"
	.string "안으로 들어가겠습니까?$"

PetalburgCity_Gym_Text_17BAA5:: @ 817BAA5
	.string "등화도시 포켓몬체육관$"

PetalburgCity_Gym_Text_17BAC0:: @ 817BAC0
	.string "등화도시 포켓몬체육관\p"
	.string "체육관 관장 종길\n"
	.string "인정 트레이너!\l"
	.string "{PLAYER}$"
