PetalburgCity_Mart_Text_17BFFD:: @ 817BFFD
	.string "지금은 약한 포켓몬이라도\n"
	.string "잘 키우면 꼭 강해질 거야!\p"
	.string "진짜 중요한 건\n"
	.string "포켓몬을 향한 사랑이지!$"

PetalburgCity_Mart_Text_17C06C:: @ 817C06C
	.string "벌레회피스프레이는 쓰고 있니?\p"
	.string "그걸 쓰면\n"
	.string "포켓몬이 나타나지 않아서\l"
	.string "서둘러야 할 때 아주 편리해!$"

PetalburgCity_Mart_Text_17C0BC:: @ 817C0BC
	.string "이봐, 너\n"
	.string "해독제는 가지고 있나?\p"
	.string "독에 걸린 포켓몬의 HP는\n"
	.string "걸어다니고 있는 사이\l"
	.string "점점 줄어든다네\p"
	.string "모험에 나갈 때는\n"
	.string "해독제를 준비할 것을 추천하네!$"
