PetalburgCity_House1_Text_17BAFB:: @ 817BAFB
	.string "여행만큼 좋은 건 없지!\p"
	.string "이 몸도 젊은 시절엔 이곳저곳의\n"
	.string "바다와 산을 떠돌아다녔었다!$"

PetalburgCity_House1_Text_17BB4A:: @ 817BB4A
	.string "아아...\p"
	.string "나도 포켓몬이랑 같이\n"
	.string "모험을 떠나보고 싶어...\p"
	.string "축축한 풀숲에 기어 들어가고\n"
	.string "울퉁불퉁한 바위산을 오르기도 하고\l"
	.string "거친 파도가 치는 바다를 건너\l"
	.string "깜깜한 동굴 속에서 헤메고...\p"
	.string "그리고 때때로\n"
	.string "우리 집을 그리워하겠지...\p"
	.string "여행이란 참 멋져!$"
