Route110_TrickHousePuzzle5_Text_19D423:: @ 819D423
	.string "달그락달그락...\n"
	.string "이 몸은 꼭두각시인형 1호!\p"
	.string "꼭두각시인형 5호가 있는 곳까지\n"
	.string "연속해서 퀴즈를 맞추면\l"
	.string "암호를 알 수 있을 거야!$"

Route110_TrickHousePuzzle5_Text_19D4AE:: @ 819D4AE
	.string "꼭두각시인형 1호 퀴즈!\p"
	.string "이 중에 103번도로에\n"
	.string "없는 포켓몬은 뭘까?$"

Route110_TrickHousePuzzle5_Text_19D501:: @ 819D501
	.string "꼭두각시인형 1호 퀴즈!\p"
	.string "이 중에서 풀타입이 아닌\n"
	.string "포켓몬은 뭘까?$"

Route110_TrickHousePuzzle5_Text_19D553:: @ 819D553
	.string "꼭두각시인형 1호 퀴즈!\p"
	.string "이 중에서 할퀴기를\n"
	.string "사용하는 포켓몬은 뭘까?$"

Route110_TrickHousePuzzle5_Text_19D599:: @ 819D599
	.string "축하해 정답이야!\n"
	.string "자 그럼 안으로 가!$"

Route110_TrickHousePuzzle5_Text_19D5CF:: @ 819D5CF
	.string "땡!\n"
	.string "틀렸어!$"

Route110_TrickHousePuzzle5_Text_19D5ED:: @ 819D5ED
	.string "와하하하하! 와하하하하!\n"
	.string "달그락달그락!$"

Route110_TrickHousePuzzle5_Text_19D615:: @ 819D615
	.string "재도전을 기다릴게-!$"

Route110_TrickHousePuzzle5_Text_19D636:: @ 819D636
	.string "달그락달그락...\n"
	.string "이 몸은 꼭두각시인형 2호!\l"
	.string "1호의 퀴즈는 너무 쉬워!$"

Route110_TrickHousePuzzle5_Text_19D68E:: @ 819D68E
	.string "꼭두각시인형 2호 퀴즈!\p"
	.string "털보박사 가방에\n"
	.string "가장 오른쪽에 있던 포켓몬은 뭘까?$"

Route110_TrickHousePuzzle5_Text_19D6EC:: @ 819D6EC
	.string "꼭두각시인형 2호 퀴즈!\p"
	.string "포켓몬트레이너스쿨에서\n"
	.string "교환한 포켓몬은 뭘까?$"

Route110_TrickHousePuzzle5_Text_19D745:: @ 819D745
	.string "꼭두각시인형 2호 퀴즈!\p"
	.string "등화숲에서 데봉 사원이\n"
	.string "찾고 있던 포켓몬은 뭘까?$"

UnknownString_819D79D: @ 819D79D
	.string "축하해 정답이야!\n"
	.string "자 그럼 안으로 가!$"

Route110_TrickHousePuzzle5_Text_19D7D3:: @ 819D7D3
	.string "달그락달그락...\n"
	.string "이 몸은 꼭두각시인형 3호!\l"
	.string "돈에 대해서는 좀 까다로워$"

Route110_TrickHousePuzzle5_Text_19D81B:: @ 819D81B
	.string "꼭두각시인형 3호 퀴즈!\p"
	.string "몬스터볼 3개 사는 거랑\n"
	.string "좋은상처약 1개 사는 거랑\l"
	.string "뭐가 더 비쌀까?$"

Route110_TrickHousePuzzle5_Text_19D865:: @ 819D865
	.string "꼭두각시인형 3호 퀴즈!\p"
	.string "동굴탈출로프를 팔아서\n"
	.string "해독제를 사면 얼마 남을까?$"

Route110_TrickHousePuzzle5_Text_19D8BA:: @ 819D8BA
	.string "꼭두각시인형 3호 퀴즈!\p"
	.string "만병통치제랑 수퍼볼을 사면\n"
	.string "기력의조각보다 비싸질까?$"

UnknownString_819D907: @ 819D907
	.string "축하해 정답이야!\n"
	.string "자 그럼 안으로 가!$"

Route110_TrickHousePuzzle5_Text_19D93D:: @ 819D93D
	.string "달그락달그락...\n"
	.string "난 꼭두각시인형 4호야!\l"
	.string "아름다운 나의 퀴즈 한번 맞혀봐!$"

Route110_TrickHousePuzzle5_Text_19D987:: @ 819D987
	.string "꼭두각시인형 4호 퀴즈야!\p"
	.string "금탄도시 체육관 관장\n"
	.string "원규의 포켓몬\l"
	.string "꼬마돌은 수컷일까 암컷일까?$"

Route110_TrickHousePuzzle5_Text_19D9DC:: @ 819D9DC
	.string "꼭두각시인형 4호 퀴즈야!\p"
	.string "무로마을의 집회소에는\n"
	.string "남성과 여성 중 어느 쪽이 많을까?$"

Route110_TrickHousePuzzle5_Text_19DA1D:: @ 819DA1D
	.string "꼭두각시인형 4호 퀴즈야!\p"
	.string "무로마을 체육관에서\n"
	.string "제일 먼저 싸우는\l"
	.string "트레이너는 남성? 아니면 여성?$"

UnknownString_819DA64: @ 819DA64
	.string "축하해 정답이야-!\n"
	.string "우훗 안으로 들어가!$"

Route110_TrickHousePuzzle5_Text_19DA9A:: @ 819DA9A
	.string "달그락달그락...\n"
	.string "이 몸은 꼭두각시인형 5호!\l"
	.string "대왕의 최고 걸작!$"

Route110_TrickHousePuzzle5_Text_19DAEF:: @ 819DAEF
	.string "꼭두각시인형 5호 퀴즈!\p"
	.string "미스터 카제노가 가게 밖에\n"
	.string "진열해 놓은 자전거는 몇 대일까?$"

Route110_TrickHousePuzzle5_Text_19DB43:: @ 819DB43
	.string "꼭두각시인형 5호 퀴즈!\p"
	.string "플라워숍 꽃잎 화원에서\n"
	.string "나무열매를 주는 사람은\l"
	.string "몇 명일까? $"

Route110_TrickHousePuzzle5_Text_19DB97:: @ 819DB97
	.string "꼭두각시인형 5호 퀴즈!\p"
	.string "해안시티에 간판은\n"
	.string "몇 개 있을까요?$"

UnknownString_819DBD4: @ 819DBD4
	.string "축하해 정답이야!\n"
	.string "자 그럼 안으로 가!$"

UnknownString_819DC0A: @ 819DC0A
	.string "{PLAYER}{K_EUNNEUN} 암호를\n"
	.string "문에 적었다!\p"
	.string "“미궁대왕님 소중해”\p"
	.string "... ... ...\p"
	.string "문의 자물쇠가 풀렸다!$"
