Route116_Text_17032A:: @ 817032A
	.string "아아아 이거 어쩌지!\p"
	.string "피코랑 같이 산책하고 있었는데\n"
	.string "갑자기 별 이상한 녀석이 와서\p"
	.string "내 귀여운 피코를\n"
	.string "뺏어 갔다네!\p"
	.string "오오-! 피코야!$"

Route116_Text_1703CF:: @ 81703CF
	.string "으음-!!\p"
	.string "터널 파고 싶어-!!$"

Route116_Text_1703F7:: @ 81703F7
	.string "으음-!!\n"
	.string "뭐야!?\p"
	.string "도구고 뭐고 안 쓰고\n"
	.string "터널을 파고 있었는데\l"
	.string "별 이상한 남자한테 쫓겨났어!!\p"
	.string "저 터널에는\n"
	.string "큰 소리에 반응해서\l"
	.string "동요하는 포켓몬이 있어\p"
	.string "그래서 기계를 사용한\n"
	.string "개발 공사도 중지했는데...\p"
	.string "괜한 소란을 피우면\n"
	.string "포켓몬이 겁먹지 않을까 걱정이야!$"

Route116_Text_170556:: @ 8170556
	.string "음-!\p"
	.string "이상한 남자가 뛰쳐나갔어!\n"
	.string "이제 다시 터널을 팔 수 있어!$"

Route116_Text_1705AE:: @ 81705AE
	.string "아앗!\n"
	.string "당신은!!\p"
	.string "등화숲에서 도와준 것뿐만 아니라\n"
	.string "도둑맞은 짐도 되찾아주고\l"
	.string "거기다가 잿빛도시로의 물건 배달도\l"
	.string "흔쾌히 해준 사람!!\p"
	.string "해양관장에게\n"
	.string "“짐은 잘 도착했다”라고\l"
	.string "연락이 왔었어요!\p"
	.string "정말 고마워요!\n"
	.string "너무 감사해서 눈물이 날 정도예요\p"
	.string "그런 멋진 트레이너님에게\n"
	.string "아주 좋은 뉴스!\p"
	.string "최근 저희 회사에서\n"
	.string "새로운 몬스터볼\l"
	.string "개발에 성공했어요!\p"
	.string "감사의 마음을 담아서\n"
	.string "트레이너님께도 선물할게요!$"

Route116_Text_1707B8:: @ 81707B8
	.string "새로운 몬스터볼은\n"
	.string "금탄도시의 프렌들리숍에서도\l"
	.string "팔고 있으니까\p"
	.string "부디 한번 사용해 보세요!\n"
	.string "그럼...$"

Route116_Text_17082A:: @ 817082A
	.string "가방이 가득 찼군요...\n"
	.string "이 리피드볼은 드릴 수 없겠네요$"

Route116_Text_170865:: @ 8170865
	.string "우리 회사의 화물을\n"
	.string "전달해주신 감사의 표시로\l"
	.string "대단한 트레이너님께\l"
	.string "새로운 몬스터볼을 드릴게요!$"

Route116_Text_1708EE:: @ 81708EE
	.string "안경을 떨어뜨렸어...\n"
	.string "너도 찾는 것 좀 도와줘$"

Route116_Text_170921:: @ 8170921
	.string "그 안경...?\n"
	.string "잠깐 좀 보여줘 봐!$"

Route116_Text_17094D:: @ 817094D
	.string "음...\n"
	.string "이건 검은안경이네\l"
	.string "내가 찾는 게 아니야...\p"
	.string "여기엔 내 안경이 없는 걸까$"

Route116_Text_1709B7:: @ 81709B7
	.string "음...\n"
	.string "아무리 찾아도 안경을 못 찾겠어\l"
	.string "여기에는 내 안경이 없는 걸까$"

Route116_Text_170A03:: @ 8170A03
	.string "음...\n"
	.string "이건 검은안경이네\l"
	.string "내가 찾는 게 아니야...$"

Route116_Text_170A46:: @ 8170A46
	.string "여기는 116번 도로\n"
	.string "{0x7B} 금탄도시$"

Route116_Text_170A60:: @ 8170A60
	.string "금탄도시와 잔디마을을 연결하는\n"
	.string "“금잔터널”\p"
	.string "개통 공사는 중지되었습니다$"

Route116_Text_170AB8:: @ 8170AB8
	.string "터널공사 작업원 대기실$"

Route116_Text_170ACE:: @ 8170ACE
	.string "정보 나눔 게시판!!\p"
	.string "포켓몬이 진화할 것 같을 때\n"
	.string "B 버튼을 누르면 놀라서\l"
	.string "진화를 멈춰버려요!\p"
	.string "그걸 진화캔슬이라고 해요$"

Route116_Text_170B7D:: @ 8170B7D
	.string "정보 나눔 게시판!!\p"
	.string "가방에는 몇 개의 포켓이 있어\n"
	.string "도구를 넣으면 종류에 따라\l"
	.string "각 포켓에\l"
	.string "자동으로 분류됩니다\p"
	.string "이건 정말 트레이너에게\n"
	.string "있어 필수품이에요!$"
