Route110_TrickHouseEntrance_Text_19BA56:: @ 819BA56
	.string "누군가의 시선이 느껴진다...$"

Route110_TrickHouseEntrance_Text_19BA6E:: @ 819BA6E
	.string "으 으음...!\p"
	.string "어떻게 이 몸이 책상 밑에\n"
	.string "숨어 있다는 걸 알았지?...대단한데!$"

Route110_TrickHouseEntrance_Text_19BAC0:: @ 819BAC0
	.string "으 으음...!\p"
	.string "어떻게 이 몸이 나무 밑에\n"
	.string "숨어 있다는 걸 알았지?...대단한데!$"

Route110_TrickHouseEntrance_Text_19BB11:: @ 819BB11
	.string "으 으음...!\p"
	.string "어떻게 이 몸이 옷장 안에\n"
	.string "숨어 있다는 걸 알았지?...대단한데!$"

Route110_TrickHouseEntrance_Text_19BB61:: @ 819BB61
	.string "으 으음...!\p"
	.string "어떻게 이 몸이 창문 건너편에\n"
	.string "숨어 있다는 걸 알았지?...대단한데!$"

Route110_TrickHouseEntrance_Text_19BBB4:: @ 819BBB4
	.string "으 으음...!\p"
	.string "어떻게 이 몸이 화분 안에\n"
	.string "숨어 있다는 걸 알았지?...대단한데!$"

Route110_TrickHouseEntrance_Text_19BC04:: @ 819BC04
	.string "으 으음...!\p"
	.string "어떻게 이 몸이 찬장 안에\n"
	.string "숨어 있다는 걸 알았지?...대단한데!$"

Route110_TrickHouseEntrance_Text_19BC55:: @ 819BC55
	.string "으 으음...!\p"
	.string "어떻게 이 몸이 창문 건너편에\n"
	.string "숨어 있다는 걸 알았지?...대단한데!$"

Route110_TrickHouseEntrance_Text_19BCA8:: @ 819BCA8
	.string "으 으음...!\p"
	.string "어떻게 이 몸이 방석 밑에\n"
	.string "숨어 있다는 걸 알았지?...대단한데!$"

Route110_TrickHouseEntrance_Text_19BCFD:: @ 819BCFD
	.string "이 몸이 바로\p"
	.string "호연지방 최대의\n"
	.string "수수께끼 인물!\l"
	.string "그 이름도 유명한...\p"
	.string "미궁대왕이닷\n"
	.string "와하하하! 잘 부탁한다!$"

Route110_TrickHouseEntrance_Text_19BD82:: @ 819BD82
	.string "자네 여기 미궁의 대저택에\n"
	.string "도전하러 온 거군\l"
	.string "어때 내 말이 맞나?\l"
	.string "좋아 도전을 받아주지!\p"
	.string "저기 있는 족자로 들어가서\n"
	.string "도전하도록!\l"
	.string "이 몸은\n"
	.string "제일 안쪽 방에서 기다리겠다!$"

Route110_TrickHouseEntrance_Text_19BE6E:: @ 819BE6E
	.string "족자다!$"

Route110_TrickHouseEntrance_Text_19BE7D:: @ 819BE7D
	.string "족자 뒤를 들여다보니\n"
	.string "커다란 구멍이 있다!\p"
	.string "안으로 들어가보겠습니까?$"

Route110_TrickHouseEntrance_Text_19BEB3:: @ 819BEB3
	.string "족자 위에는 메모가 붙어 있다\p"
	.string "“여행 떠납니다...찾지 말아 주세요\n"
	.string "미궁대왕”$"

Route110_TrickHouseEntrance_Text_19BF19:: @ 819BF19
	.string "자 그럼 이번 장치에는\n"
	.string "이런 거나 저런 걸...\p"
	.string "우후후... 내가 생각해봐도\n"
	.string "무진장 어렵다고... 우후후$"

Route110_TrickHouseEntrance_Text_19BFAB:: @ 819BFAB
	.string "우왓 뭐야! 자넨가!\p"
	.string "지금은 아직 다음에 쓰일 장치를\n"
	.string "생각 중이라고!\p"
	.string "좀 더 이 몸에게\n"
	.string "생각할 시간을\l"
	.string "줘도 괜찮잖아!\l"
	.string "좀 있다가 다시 와줘!$"

Route110_TrickHouseEntrance_Text_19C07E:: @ 819C07E
	.string "오오 자넨가! 어디 보자 지난번의\n"
	.string "선물을 가지러 온 거군!\l"
	.string "좋아 지금 주마!$"

Route110_TrickHouseEntrance_Text_19C0FC:: @ 819C0FC
	.string "어라?\n"
	.string "선물을 가지러 온 게 아니었어?$"

Route110_TrickHouseEntrance_Text_19C128:: @ 819C128
	.string "이 몸은 꼭두각시인형 5호!\n"
	.string "선물을 받지 않으면\l"
	.string "미궁대왕을 따라갈 수 없다고!$"

Route110_TrickHouseEntrance_Text_19C17E:: @ 819C17E
	.string "그럼 안녕!$"

Route110_TrickHouseEntrance_Text_19C18D:: @ 819C18D
	.string "PC가 가득 찼네...?\n"
	.string "너무하잖아!$"
