Route111_Text_16F705:: @ 816F705
	.string "이보게! 여행 중인 건 알고 있지만,\p"
	.string "잠깐 어떤가? 지금 여기서\n"
	.string "우리 가족 4명과\l"
	.string "포켓몬 승부를 해보지 않겠나?$"

Route111_Text_16F785:: @ 816F785
	.string "그렇군!\n"
	.string "마음이 바뀌면 다시 오게!$"

Route111_Text_16F7B3:: @ 816F7B3
	.string "멋진 배짱이군! 마음에 들었다!$"

Route111_Text_16F7D2:: @ 816F7D2
	.string "어허!\n"
	.string "생각했던 것보다 강하군!$"

Route111_Text_16F7FF:: @ 816F7FF
	.string "이봐-!\n"
	.string "상당히 강한 트레이너가 있다-!$"

Route111_Text_16F82D:: @ 816F82D
	.string "어머머! 생각보다 어리군요?!\p"
	.string "우리 남편을 이기다니\n"
	.string "정말 굉장한 실력의\l"
	.string "트레이너인가 보죠?\p"
	.string "자 그럼 이번엔 저와 승부해요!$"

Route111_Text_16F8A6:: @ 816F8A6
	.string "에구머니나!\n"
	.string "어쩜 그렇게 강하신가요?!$"

Route111_Text_16F8D5:: @ 816F8D5
	.string "강해-!\n"
	.string "이 사람 엄청나게 강해요-!$"

Route111_Text_16F90E:: @ 816F90E
	.string "엄마보다 강하다니 굉장하다!\p"
	.string "하지만 나도 꽤 강하다고!\n"
	.string "진짜라니까?!$"

Route111_Text_16F956:: @ 816F956
	.string "응? 서, 설마 져버린 건가...?$"

Route111_Text_16F96C:: @ 816F96C
	.string "너무 분해...\p"
	.string "...훌쩍!\n"
	.string "할머니이-이!!$"

Route111_Text_16F991:: @ 816F991
	.string "요 녀석-!\n"
	.string "우리 귀여운 손녀에게\l"
	.string "무슨 짓을 한 게냐!\p"
	.string "이렇게 된 이상 내가 직접\n"
	.string "네 포켓몬을 혼내줄 테니 각오해라잇!$"

Route111_Text_16F9EC:: @ 816F9EC
	.string "아이고! 강하구먼...\n"
	.string "우리 손녀가 한 말이 사실이었어$"

Route111_Text_16FA22:: @ 816FA22
	.string "얘야... 갈 길이 바쁘지 않으면\n"
	.string "종종 우리 집에 들렀다 가거라...$"

Route111_Text_16FA54:: @ 816FA54
	.string "뿌리화석을 발견했다!\p"
	.string "이 화석을 캐면\n"
	.string "다른 화석은 가라앉을 것 같다...\p"
	.string "뿌리화석을 캐겠습니까?$"

Route111_Text_16FACE:: @ 816FACE
	.string "{PLAYER}\s 뿌리화석을\n"
	.string "그대로 놔뒀다$"

Route111_Text_16FAED:: @ 816FAED
	.string "발톱화석을 발견했다!\p"
	.string "이 화석을 캐면\n"
	.string "다른 화석은 가라앉을 것 같다...\p"
	.string "발톱화석을 캐겠습니까?$"

Route111_Text_16FB67:: @ 816FB67
	.string "{PLAYER}\s 발톱화석을\n"
	.string "그대로 놔뒀다$"

Route111_Text_16FB86:: @ 816FB86
	.string "좀 더 포켓몬을 단련시키지 않으면\n"
	.string "앞으로 이기기 어려울 것 같아\p"
	.string "포켓몬리그에 있는 사천왕은\n"
	.string "지금까지 승부했던\l"
	.string "체육관 관장들보다\l"
	.string "훨씬 강하다고 하니까 말이야$"

Route111_Text_16FC3A:: @ 816FC3A
	.string "연승가족에게 도전했는데\n"
	.string "4명과 연속으로\l"
	.string "포켓몬 승부를 하는 건\l"
	.string "정말 힘들더라... 완패하고 말았어$"

Route111_Text_16FC9C:: @ 816FC9C
	.string "여기는 111번 도로\n"
	.string "{0x7A} 보라시티$"

Route111_Text_16FCB6:: @ 816FCB6
	.string "우리 가족은 한마음\n"
	.string "“연승가족의 집”$"

Route111_Text_16FCEF:: @ 816FCEF
	.string "여기는 111번 도로\n"
	.string "{0x7B} 112번 도로$"

Route111_Text_16FD05:: @ 816FD05
	.string "여기는 111번 도로\n"
	.string "{0x7B} 113번 도로$"

Route111_Text_16FD1B:: @ 816FD1B
	.string "“건강할머니의 집”\n"
	.string "지쳤다고 느낀다면 들렀다 가렴!$"

Route111_Text_16FD55:: @ 816FD55
	.string "정보 나눔 게시판!!\p"
	.string "포켓몬의 능력을 나타내는 말 중에\n"
	.string "특수공격이란\l"
	.string "특수공격력을\p"
	.string "특수방어란\n"
	.string "특수방어력을 뜻하는 말입니다!$"
