Route101_Text_16D10E:: @ 816D10E
	.string "사 살려줘-!!$"

Route101_Text_16D119:: @ 816D119
	.string "어이-! 거기 자네!\n"
	.string "나 좀 살려줘!!\p"
	.string "거기 있는 가방 안에\n"
	.string "몬스터볼이 들어 있어!$"

Route101_Text_16D15E:: @ 816D15E
	.string "어 어디 가는 거야!?\n"
	.string "날 버리지 말아줘-!$"

Route101_Text_16D191:: @ 816D191
	.string "털보박사: 헉 헉...\p"
	.string "야생 포켓몬에 대해 조사하려고\n"
	.string "풀숲에 들어갔더니\l"
	.string "갑자기 포켓몬이 덮쳐 와서...\p"
	.string "어쨌든 구해줘서 고마워!\p"
	.string "...응?\p"
	.string "자넨 종길씨네\n"
	.string "{PLAYER}{K_I}잖아!\l"
	.string "이야 많이 컸는데!\p"
	.string "...흠 이런 곳에 서서\n"
	.string "얘기하기도 뭐하니까\l"
	.string "잠깐 연구소에 좀 들러줘$"

Route101_Text_16D25E:: @ 816D25E
	.string "포켓몬이 약해지면\n"
	.string "포켓몬센터로 가는 게 좋을 거야!\p"
	.string "포켓몬센터는 근처에 있는\n"
	.string "고도마을에 있어$"

Route101_Text_16D2CB:: @ 816D2CB
	.string "야생 포켓몬은\n"
	.string "풀숲에서 튀어나오니까!\p"
	.string "이렇게 풀숲으로 들어가서\n"
	.string "잡고 싶은 포켓몬을 찾으면 돼!$"

Route101_Text_16D349:: @ 816D349
	.string "여기는 101번 도로\n"
	.string "{0x79} 고도마을$"
