Route109_SeashoreHouse_Text_19B4D9:: @ 819B4D9
	.string "난 바다의 집 아저씨!\n"
	.string "사람들은 바다아저씨라고 부르지!\p"
	.string "어쨌든 뜨거운 포켓몬 승부를\n"
	.string "보는 걸 정말 좋아한다고-!\p"
	.string "자네도 말이야- 뜨-거운 하트로\n"
	.string "여기에 있는\p"
	.string "모든 트레이너를 상대로\n"
	.string "이기면 내가 좋은 거 줄게-$"

Route109_SeashoreHouse_Text_19B5B9:: @ 819B5B9
	.string "뜨-거운 승부를 보여줘!\p"
	.string "그거 하나만 보고\n"
	.string "이 바다의 집을 하고 있는 거야 난-!$"

Route109_SeashoreHouse_Text_19B609:: @ 819B609
	.string "자네 대단한데-!\n"
	.string "정말 뜨거운 포켓몬 승부였어!\l"
	.string "나 정말 대만족했어!\p"
	.string "이건 뜨거운 승부를 보여준\n"
	.string "자네에게 주는 감사의 표시야\p"
	.string "미네랄사이다 반 세트\n"
	.string "가져가-$"

Route109_SeashoreHouse_Text_19B6BE:: @ 819B6BE
	.string "가방이 가득 찼네-\n"
	.string "가방 비우고 오면 줄게$"

Route109_SeashoreHouse_Text_19B702:: @ 819B702
	.string "포켓몬도 정말 좋아하는\n"
	.string "미네랄사이다!\p"
	.string "한 병에 300원이야-\n"
	.string "사 가지 않을래?$"

Route109_SeashoreHouse_Text_19B74C:: @ 819B74C
	.string "자 여기$"

Route109_SeashoreHouse_Text_19B759:: @ 819B759
	.string "돈이 부족한데-$"

Route109_SeashoreHouse_Text_19B773:: @ 819B773
	.string "그거 아쉽네-$"

UnknownString_819B787: @ 819B787
	.string "포켓몬도 정말 좋아하는\n"
	.string "미네랄사이다 한 병에 300원!\p"
	.string "하나 사 가지 않을래?$"

UnknownString_819B7C5: @ 819B7C5
	.string "자 여기$"

UnknownString_819B7D2: @ 819B7D2
	.string "음\n"
	.string "돈이 부족한걸-$"

UnknownString_819B7F9: @ 819B7F9
	.string "그거 아쉽네-$"

Route109_SeashoreHouse_Text_19B809:: @ 819B809
	.string "이 바다의 집에서 가장\n"
	.string "뜨거운 포켓몬 승부를\l"
	.string "벌일 수 있는 건\l"
	.string "바로 이 몸이시다!$"

Route109_SeashoreHouse_Text_19B869:: @ 819B869
	.string "확실히 뜨거운 승부였다\n"
	.string "패배를 수긍할 수밖에 없는 느낌이군!$"

Route109_SeashoreHouse_Text_19B89F:: @ 819B89F
	.string "나는 잿빛도시에 올 때마다\n"
	.string "뜨거운 승부와\l"
	.string "시원한 미네랄사이다를 즐기지!$"

Route109_SeashoreHouse_Text_19B8E5:: @ 819B8E5
	.string "지루한 승부는 필요 없어!\p"
	.string "타오르는 듯한 승부야말로\n"
	.string "트레이너와 포켓몬을\l"
	.string "강하게 만드는 거야!$"

Route109_SeashoreHouse_Text_19B949:: @ 819B949
	.string "너무 뜨겁잖아!$"

Route109_SeashoreHouse_Text_19B955:: @ 819B955
	.string "아- 목말라\n"
	.string "미네랄사이다나 마실까?$"

Route109_SeashoreHouse_Text_19B988:: @ 819B988
	.string "굉장한 내 포켓몬을\n"
	.string "똑똑히 보여줄 테니까 울지 말라고!$"

Route109_SeashoreHouse_Text_19B9C7:: @ 819B9C7
	.string "...졌지만 울지 않겠어$"

Route109_SeashoreHouse_Text_19B9E5:: @ 819B9E5
	.string "포켓몬이 날 태우고\n"
	.string "물 위를 나아갈 수 있는 기술을\l"
	.string "쓸 수 있다면\l"
	.string "튜브도 필요 없을 텐데$"
