Route114_FossilManiacsTunnel_Text_192795:: @ 8192795
	.string "나는 화석마니아...\n"
	.string "화석을 좋아하는 나이스 가이야...\p"
	.string "너도 화석을 가지고 싶니...?\p"
	.string "여기서 발견되는 화석은\n"
	.string "모두 내 거라서 줄 수가 없어...\p"
	.string "어떻게든 가지고 싶으면\n"
	.string "111번 도로에 있는 사막에 가봐...\p"
	.string "내가 들은 이야기로는\n"
	.string "모래바람 때문에\l"
	.string "모래 밑에 잠들어 있던 화석이\l"
	.string "표면으로 떠오를 때가 있대...$"

Route114_FossilManiacsTunnel_Text_1928DE:: @ 81928DE
	.string "너도 화석을 발견했구나...\n"
	.string "멋져... 나도 모르게\l"
	.string "멍하니 바라보게 돼...\p"
	.string "너 그 화석 어떻게 할 거니...?\p"
	.string "내가 들은 이야기로는 데봉에서\n"
	.string "화석을 포켓몬으로 부활시키는\l"
	.string "연구를 하고 있대...\p"
	.string "나는 화석이 더 좋으니까\n"
	.string "그런 건 안 할 거지만...$"

Route114_FossilManiacsTunnel_Text_1929DC:: @ 81929DC
	.string "화석은...\n"
	.string "정말 멋져...\l"
	.string "넋을 놓고 바라보게 돼...$"
