Route128_Text_171EE0:: @ 8171EE0 //JP: 1541BD
	.string "{EVIL_LEADER}: 뭐야...\n"
	.string "이 끔찍한 광경은...?\p"
	.string "나는...\n"
	.string "터무니없는 잘못을...$"

Route128_Text_171F35:: @ 8171F35
	.string "나는...\n"
	.string "그저...$"

Route128_Text_171F4B:: @ 8171F4B
	.string "{GOOD_LEADER}: 알겠나 {EVIL_LEADER}!\n"
	.string "네가 한 짓이\l"
	.string "얼마나 어리석은 것인지를...\p"
	.string "...어쨌든 서두르자!\n"
	.string "이 이상 심각해지기 전에\l"
	.string "뭐라도 하지 않으면 안되니까!$"

Route128_Text_172008:: @ 8172008
	.string "{GOOD_LEADER}: {PLAYER}인가...\p"
	.string "우리 {GOOD_TEAM}단은 이렇게 되지 않도록\n"
	.string "{EVIL_TEAM}단을 쫓고 있었던 거다\p"
	.string "너도 열심히 해주었지만\n"
	.string "최악의 상황이야...\p"
	.string "이렇게 되었으니 어린애인 너에게는\n"
	.string "아무것도 할 수 있는 게 없겠지\l"
	.string "여기는 우리에게 맡겨두고 떠나거라!$"

Route128_Text_17210B:: @ 817210B
	.string "{GOOD_LEADER}: 그건 그렇고...\p"
	.string "초 고대포켓몬...\n"
	.string "엄청난 파워다\l"
	.string "모든 균형이 무너졌어...$"

Route128_Text_172181:: @ 8172181
	.string "성호: {PLAYER}!\n"
	.string "이건 대체...?$"

Route128_Text_1721A2:: @ 81721A2
	.string "...이건 좀 심한걸\p"
	.string "이대로라면 호연지방...\n"
	.string "아니 전 세계가 잠길 거야!\p"
	.string "이 비를 내리게 하고 있는 구름은\n"
	.string "루네시티의 상공을 중심으로\l"
	.string "퍼져 있는 건가...\p"
	.string "대체 저기서\n"
	.string "뭐가 일어나는 거지?!\p"
	.string "여기서 이것저것 생각할 게 아니고\n"
	.string "루네시티로 직접 가면 알겠네...$"

Route128_Text_1722A1:: @ 81722A1
	.string "...이건 좀 심한걸\p"
	.string "이대로라면 호연지방...\n"
	.string "아니 전 세계가 말라붙어 버릴 거야!\p"
	.string "이 심한 가뭄의 원인\n"
	.string "새빨간 태양은 루네시티의 상공에\l"
	.string "떠 있는 건가...\p"
	.string "대체 저기서\n"
	.string "뭐가 일어나는 거지?!\p"
	.string "여기서 이것저것 생각할 게 아니고\n"
	.string "루네시티로 직접 가면 알겠네...$"

Route128_Text_1723BE:: @ 81723BE
	.string "{PLAYER}...\n"
	.string "네가 뭘 할 생각인지는\l"
	.string "모르겠지만 무리만은 하지 마\p"
	.string "...그럼\n"
	.string "나는 루네시티로 갈게$"
