Route103_Text_16D57A:: @ 816D57A
	.string "봄이: 음- 103번도로에 있는\n"
	.string "포켓몬이 저 아이랑 저 아이고...$"

Route103_Text_16D5B6:: @ 816D5B6
	.string "어머 {PLAYER}{K_AYA}!\p"
	.string "...아아! 아빠한테\n"
	.string "포켓몬을 선물 받았구나!\p"
	.string "모처럼 포켓몬도 받았으니까\n"
	.string "포켓몬 승부 한번 해보자!\p"
	.string "트레이너가 어떤 건지\n"
	.string "내가 알려줄게!$"

Route103_Text_16D65B:: @ 816D65B
	.string "우와! 진짜 굉장해!\n"
	.string "강하구나?! {PLAYER}!$"

Route103_Text_16D688:: @ 816D688
	.string "봄이: 나 왜 아빠가\n"
	.string "그렇게 너를 주목하는지\l"
	.string "왠지 알 거 같아!\p"
	.string "왜냐면 선물 받은 지\n"
	.string "얼마 되지도 않은 포켓몬이\l"
	.string "벌써 널 따르고 있잖아!\p"
	.string "너라면 어떤 포켓몬이랑도\n"
	.string "금방 친해질 수 있을 것 같아!\p"
	.string "조사도 대충 끝났으니까\n"
	.string "연구소로 같이 돌아가자!$"

Route103_Text_16D762:: @ 816D762
	.string "휘웅: 아하 얘랑 얘가\n"
	.string "103번도로에 있는 포켓몬이구나...$"

Route103_Text_16D7A9:: @ 816D7A9
	.string "응? 아 {PLAYER}{K_AYA}!\p"
	.string "...아아 아빠한테서\n"
	.string "포켓몬 받았구나\p"
	.string "그럼 포켓몬도 생겼겠다\n"
	.string "포켓몬 승부 한번 해볼까?\p"
	.string "트레이너라는 게 어떤 건지\n"
	.string "내가 알려줄게!$"

Route103_Text_16D836:: @ 816D836
	.string "흐음...\n"
	.string "{PLAYER} 너 꽤 강하구나$"

Route103_Text_16D856:: @ 816D856
	.string "휘웅: 아빠가 왜 {PLAYER}{K_EULREUL}\n"
	.string "주목하고 있는지\l"
	.string "왠지 알 거 같아...\p"
	.string "받은 지 얼마 안 된 포켓몬이\n"
	.string "벌써 이렇게 잘 따르고 있잖아\p"
	.string "{PLAYER} 너라면 어떤 포켓몬이랑도\n"
	.string "금세 친해질 수도 있겠다\p"
	.string "...자 그럼\n" 
	.string "조사도 일단락되었으니까\l"
	.string "연구소로 같이 돌아가자$"

Route103_Text_16D950:: @ 816D950
	.string "내 포켓몬이 쓰러지기 직전이야...\n"
	.string "상처약 챙겨 올 걸 그랬어...$"

Route103_Text_16D996:: @ 816D996
	.string "여기에서 바다를 건너면\n"
	.string "고도마을까지 가는 지름길이야!\p"
	.string "후후후 꽤 쓸만한 정보지?$"

Route103_Text_16D9FB:: @ 816D9FB
	.string "여기는 103번도로\n"
	.string "{0x7A} 고도마을$"
