Route119_WeatherInstitute_1F_Text_19EB8A:: @ 819EB8A
	.string "리더가 여기서의 연구에\n"
	.string "흥미가 있으셔서\l"
	.string "우리들을 보낸 거다! 방해하지 마!$"

Route119_WeatherInstitute_1F_Text_19EBEE:: @ 819EBEE
	.string "젠장-\n"
	.string "어린애에게 졌다...$"

Route119_WeatherInstitute_1F_Text_19EC0E:: @ 819EC0E
	.string "리더는 뭐든지 알고 있어\p"
	.string "하지만 무엇을 생각하고 있는지\n"
	.string "조무래기인 우리는 전혀 상상도 안 가$"

Route119_WeatherInstitute_1F_Text_19EC6B:: @ 819EC6B
	.string "어라?\n"
	.string "왜 여기에 어린애가 있는 거지?$"

Route119_WeatherInstitute_1F_Text_19EC89:: @ 819EC89
	.string "어머-\n"
	.string "져버린 건가-?!$"

Route119_WeatherInstitute_1F_Text_19EC97:: @ 819EC97
	.string "어머머...\n"
	.string "어린애한테 진 게 알려지면\l"
	.string "혼이 날 거야...\p"
	.string "침대에서 자는 척이라도 할까?$"

Route119_WeatherInstitute_1F_Text_19ECF4:: @ 819ECF4
	.string "내가 침대에서 자는 동안\n"
	.string "모두 2층으로 가버렸어$"

Route119_WeatherInstitute_1F_Text_19ED22:: @ 819ED22
	.string "{K_BOY_CALL} 강하네!\p"
	.string "나도 {K_BOY_CALL} 같은\n"
	.string "포켓몬 트레이너가 되고 싶어!$"

Route119_WeatherInstitute_1F_Text_19ED6B:: @ 819ED6B
	.string "박사님은 말이야\n"
	.string "비를 정말 좋아해\p"
	.string "그렇지만 계속 비가 내리면\n"
	.string "곤란해지는 사람도 있지\p"
	.string "그래서 박사님은\n"
	.string "이 비를 무언가로\l"
	.string "바꿔 쓸 수 없을까 하고\l"
	.string "연구하고 있어$"

Route119_WeatherInstitute_1F_Text_19EE25:: @ 819EE25
	.string "안녕!\n"
	.string "당신 덕분에 살았어요!\p"
	.string "...그건 그렇고\n"
	.string "{EVIL_TEAM}단 녀석들은\l"
	.string "도대체 무얼 할 생각이었을까요?$"

Route119_WeatherInstitute_1F_Text_19EE8B:: @ 819EE8B
	.string "침대가 있다...\n"
	.string "좀 쉬었다 가자$"
