Route110_TrickHousePuzzle7_Text_19DF0B:: @ 819DF0B
	.string "항상 미궁대왕은 팟 하고\n"
	.string "사라지던데 어떻게 하는 걸까?$"

Route110_TrickHousePuzzle7_Text_19DF4B:: @ 819DF4B
	.string "히엑-!\n"
	.string "어째서 그렇게 강한 거야?$"

Route110_TrickHousePuzzle7_Text_19DF7E:: @ 819DF7E
	.string "나도 자유자재로\n"
	.string "사라졌다가 나타났다가 하고 싶다$"

Route110_TrickHousePuzzle7_Text_19DFBB:: @ 819DFBB
	.string "같은 곳을 계속해서\n"
	.string "몇 번이고 맴돌고 있어서 불길해...$"

Route110_TrickHousePuzzle7_Text_19DFF2:: @ 819DFF2
	.string "졌다...!\n"
	.string "재수가 안 좋아...!$"

Route110_TrickHousePuzzle7_Text_19E00F:: @ 819E00F
	.string "나는 이제 10회 이상\n"
	.string "맴돌고 말았어... 불길한데...$"

Route110_TrickHousePuzzle7_Text_19E054:: @ 819E054
	.string "이긴 쪽이 먼저 이 장치를\n"
	.string "빠져나갈 거 같은 예감이 들어!$"

Route110_TrickHousePuzzle7_Text_19E098:: @ 819E098
	.string "어라!\n"
	.string "자 그럼 먼저 나가!$"

Route110_TrickHousePuzzle7_Text_19E0B2:: @ 819E0B2
	.string "당신은 미궁의 대저택의 장치를\n"
	.string "전부 풀 거 같은 예감이 들어!$"

UnknownString_819E0FF: @ 819E0FF
	.string "{PLAYER}\s 암호를\n"
	.string "문에 적었다!\p"
	.string "“미궁대왕님 사랑해요”\p"
	.string "... ... ...\p"
	.string "문의 자물쇠가 풀렸다!$"
