Route110_TrickHousePuzzle6_Text_19DC87:: @ 819DC87
	.string "최근에 이상한 저택이 생겼다는\n"
	.string "소문을 듣고 조사하러 왔어!$"

Route110_TrickHousePuzzle6_Text_19DCC6:: @ 819DCC6
	.string "강한 트레이너를 발견했다!$"

Route110_TrickHousePuzzle6_Text_19DCE7:: @ 819DCE7
	.string "저택을 조사하고 있는데 재미있어서\n"
	.string "몇 번이고 도전하고 있어!$"

Route110_TrickHousePuzzle6_Text_19DD49:: @ 819DD49
	.string "나의 새포켓몬으로\n"
	.string "벽을 뛰어넘어 버릴까...?$"

Route110_TrickHousePuzzle6_Text_19DD83:: @ 819DD83
	.string "와앗 져버렸다!$"

Route110_TrickHousePuzzle6_Text_19DD96:: @ 819DD96
	.string "데헤헤... 잔꾀를 부려서\n"
	.string "져버린 건가...$"

Route110_TrickHousePuzzle6_Text_19DDCF:: @ 819DDCF
	.string "회전하는 문 때문에\n"
	.string "눈이 돌아간다...$"

Route110_TrickHousePuzzle6_Text_19DDFE:: @ 819DDFE
	.string "빙글빙글 빙글빙글\n"
	.string "난 더 이상은 못한다...$"

Route110_TrickHousePuzzle6_Text_19DE44:: @ 819DE44
	.string "너는 전혀 아무렇지도 않은 모양이네\n"
	.string "그게 아니면 무표정이란 거니?$"

UnknownString_819DE8D: @ 819DE8D
	.string "{PLAYER}\s 암호를\n"
	.string "문에 적었다!\p"
	.string "“미궁대왕님 껴안고 싶어”\p"
	.string "... ... ...\p"
	.string "문의 자물쇠가 풀렸다!$"
