Route116_TunnelersRestHouse_Text_192F33:: @ 8192F33
	.string "저 금잔터널은...\p"
	.string "처음엔 수많은 사람들과\n"
	.string "최신식 기계로 파 나갔지\p"
	.string "하지만 그대로 계속 파면\n"
	.string "주변의 포켓몬에게\l"
	.string "악영향을 끼친다는군\p"
	.string "그래서 우리들은 어쩌지도 못하고\n"
	.string "여기서 멍하니 있는 거야$"

Route116_TunnelersRestHouse_Text_193049:: @ 8193049
	.string "어떻게 해서든 잔디마을에\n"
	.string "가고 싶어 하는 녀석이\l"
	.string "혼자서 터널을 파왔어\p"
	.string "사람의 힘으로 조금씩 파내면\n"
	.string "포켓몬을 놀라게 하지도 않고\l"
	.string "주변 자연환경에도 나쁜 영향을\l"
	.string "끼치지 않을 거라면서 말이야$"

Route116_TunnelersRestHouse_Text_193135:: @ 8193135
	.string "여기서 터널을 지나지 않고\n"
	.string "잔디마을로 가려면 바다를 건너\l"
	.string "무로마을에서 잿빛도시로 간 다음\p"
	.string "보라시티를 통해서\n"
	.string "가는 수밖에 없군!$"

Route116_TunnelersRestHouse_Text_1931C1:: @ 81931C1
	.string "결국엔 잔디마을까지 가는\n"
	.string "터널이 뚫린 모양이야!\p"
	.string "이거야말로\n"
	.string "“꿈은 이루어진다”로구만!$"
