Route104_Prototype_Text_19AD9B:: @ 819AD9B
	.string "실력 좋아 보이는 트레이너군요\n"
	.string "제 포켓몬 보실래요?$"

Route104_Prototype_Text_19ADDA:: @ 819ADDA
	.string "저는 당신에게\n"
    .string "충분하지 않았군요...$"

Route104_Prototype_Text_19ADF7:: @ 819ADF7
	.string "즐거운 배틀이었어요!\n"
	.string "시간이 된다면 언제든지 다시 해요!$"

Route104_Prototype_Text_19AE3E:: @ 819AE3E
	.string "가랏!\n"
	.string "우리의 포켓몬들!$"

Route104_Prototype_Text_19AE53:: @ 819AE53
	.string "이런... 이길 수 없었어...$"

Route104_Prototype_Text_19AE6A:: @ 819AE6A
	.string "포켓몬 두 마리가 동시에\n"
	.string "배틀해서 놀라지 않았어?$"

Route104_Prototype_Text_19AEA9:: @ 819AEA9
	.string "포켓몬이 1마리밖에 없다면\n"
	.string "우리와 승부할 수 없어!\l"
	.string "왜냐면 우린 강하니까!$"

Route104_Prototype_Text_19AEFB:: @ 819AEFB
	.string "이봐! 이건 내 첫 배틀이라고,\n"
	.string "최선을 다하겠어!$"

Route104_Prototype_Text_19AF3E:: @ 819AF3E
	.string "최선을 다했지만...$"

Route104_Prototype_Text_19AF56:: @ 819AF56
	.string "넌 너무 강해!\n"
	.string "훌륭한 트레이너가 될 것 같은걸?$"

Route104_Prototype_Text_19AF8A:: @ 819AF8A
	.string "제 포켓몬은 정말 귀엽고\n"
	.string "정말 강하답니다\l"
	.string "당신에게도 보여드리도록 하죠$"

Route104_Prototype_Text_19AFDB:: @ 819AFDB
	.string "패배를 인정하죠\n"
	.string "당신은 정말로 강하군요$"

Route104_Prototype_Text_19B00D:: @ 819B00D
	.string "다음에 만났을 때는\n"
	.string "포켓몬을 더 키울 겁니다\p"
	.string "그때는 봐주지 않겠어요$"

Route104_Prototype_Text_19B066:: @ 819B066
	.string "등산가는 언제나 풀-에너지!\n"
	.string "내 포켓몬들도 풀-에너지!\l"
	.string "포켓몬 승부를 기다리고 있었다!$"

Route104_Prototype_Text_19B0D7:: @ 819B0D7
	.string "에너지를 다 써버렸어...$"

Route104_Prototype_Text_19B0EF:: @ 819B0EF
	.string "와하하! 져버렸구먼!\n"
	.string "하지만 대단한 승부였구먼\l"
	.string "만족했다!$"

Route104_Prototype_Text_19B148:: @ 819B148
	.string "강해 보이지만...\n"
	.string "우리를 이길 수 있을까?$"

Route104_Prototype_Text_19B17D:: @ 819B17D
	.string "우와!\n"
	.string "져버렸다...$"

Route104_Prototype_Text_19B18D:: @ 819B18D
	.string "포켓몬 두 마리가 동시에 배틀하면\n"
	.string "여러 새로운 상황이 생겨나죠!$"

Route104_Prototype_Text_19B1DD:: @ 819B1DD
	.string "포켓몬을 1마리밖에\n"
	.string "가지고 있지 않다면\p"
	.string "우리와 배틀할 수 없어!$"

Route104_Prototype_Text_19B22E:: @ 819B22E
	.string "다른 트레이너들과 싸워서\n"
	.string "모두 이겨봤나요?$"

Route104_Prototype_Text_19B267:: @ 819B267
	.string "오늘 와주셔서 감사해요!\p"
	.string "이 게임의 발매를\n"
	.string "기대하시길 바라겠습니다!$"

Route104_Prototype_Text_19B2B6:: @ 819B2B6
	.string "음? 이미 다른 트레이너들과\n"
	.string "다 싸워보셨나요?$"

Route104_Prototype_Text_19B2E9:: @ 819B2E9
	.string "오늘 와주셔서 감사해요!\p"
	.string "이 게임의 발매를\n"
	.string "기대하시길 바라겠습니다!$"

Route104_Prototype_Text_19B33B:: @ 819B33B
	.string "본 적 없는 포켓몬을 가지고 있군\n"
	.string "조금 부러운걸$"

Route104_Prototype_Text_19B37F:: @ 819B37F
	.string "저 트레이너들을 보세요!\n"
	.string "그들도 다른 포켓몬들을 지니고 있답니다!\l"
	.string "모두 당신을 기다리고 있어요!$"

Route104_Prototype_Text_19B3DE:: @ 819B3DE
	.string "포켓몬스터의 세계에\n"
	.string "오신 걸 환영합니다!$"

Route104_Prototype_Text_19B3FF:: @ 819B3FF
	.string "모든 포켓몬 승부가\n"
	.string "재밌고, 격렬할 거예요!$"
