Route110_TrickHousePuzzle3_Text_19CF76:: @ 819CF76
	.string "몇 번이든 같은 곳으로\n"
	.string "돌아와버려-!$"

Route110_TrickHousePuzzle3_Text_19CF9D:: @ 819CF9D
	.string "내가 곤란해하고 있는데\n"
	.string "확실하게 이겨버리다니 너무해-!$"

Route110_TrickHousePuzzle3_Text_19CFE6:: @ 819CFE6
	.string "문만으로 가득차 있어서\n"
	.string "좁아서 무섭다고-!$"

Route110_TrickHousePuzzle3_Text_19D026:: @ 819D026
	.string "뭐가 뭔지 모르겠어서\n"
	.string "슬퍼지기 시작했어...$"

Route110_TrickHousePuzzle3_Text_19D065:: @ 819D065
	.string "너 너무해...$"

Route110_TrickHousePuzzle3_Text_19D07A:: @ 819D07A
	.string "당연히 나는 약한데다가\n"
	.string "방향치라고-!$"

Route110_TrickHousePuzzle3_Text_19D0AE:: @ 819D0AE
	.string "대체 뭘 위해서\n"
	.string "이런 저택이 있는 거지...?$"

Route110_TrickHousePuzzle3_Text_19D0F0:: @ 819D0F0
	.string "대체 왜\n"
	.string "내가 진 거지...?$"

Route110_TrickHousePuzzle3_Text_19D110:: @ 819D110
	.string "대체 이 저택에는\n"
	.string "얼마나 많은 장치가 있는 거지?\p"
	.string "자네라면 알지도 모르겠군$"

UnknownString_819D164: @ 819D164
	.string "{PLAYER}\s 암호를\n"
	.string "문에 적었다!\p"
	.string "“미궁대왕님 멋있어”\p"
	.string "... ... ...\p"
	.string "문의 자물쇠가 풀렸다!$"
