Route110_TrickHousePuzzle1_Text_19CB4F:: @ 819CB4F
	.string "방금 막 배우게 한 풀베기로\n"
	.string "자르고 자르고 또 자를 거야!$"

Route110_TrickHousePuzzle1_Text_19CB93:: @ 819CB93
	.string "진짜 실력을 몽땅 발휘하지 말아줘-!$"

Route110_TrickHousePuzzle1_Text_19CBAB:: @ 819CBAB
	.string "자르고 잘라도 질리지가 않아!$"

Route110_TrickHousePuzzle1_Text_19CBD6:: @ 819CBD6
	.string "길을 헤매다가\n"
	.string "이상한 저택에 들어와 버렸다...$"

Route110_TrickHousePuzzle1_Text_19CC06:: @ 819CC06
	.string "게다가 져버렸다...$"

Route110_TrickHousePuzzle1_Text_19CC1B:: @ 819CC1B
	.string "심지어 길도 잃었다...\n"
	.string "나갈 수가 없어...$"

Route110_TrickHousePuzzle1_Text_19CC68:: @ 819CC68
	.string "미궁대왕이란 사람은\n"
	.string "도대체 누굴까?$"

Route110_TrickHousePuzzle1_Text_19CC86:: @ 819CC86
	.string "미궁대왕에 정신이 팔려 있는 동안\n"
	.string "져버렸어!$"

Route110_TrickHousePuzzle1_Text_19CCAA:: @ 819CCAA
	.string "강하다!\n"
	.string "넌 또 정체가 뭐니?$"

UnknownString_819CCCB: @ 819CCCB
	.string "{PLAYER}\s 암호를\n"
	.string "문에 적었다!\p"
	.string "“미궁대왕님 똑똑해”\p"
	.string "... ... ...\p"
	.string "문의 자물쇠가 풀렸다!$"
