Route113_GlassWorkshop_Text_19E4E6:: @ 819E4E6
	.string "요 주변에는\n"
	.string "온통 화산재뿐이야 콜록콜록!\p"
	.string "그리고 난 대단해 콜록콜록\p"
	.string "화산재를 가지고 유리를 만들어서\n"
	.string "그걸로 도구를\l"
	.string "만들 수 있어 콜록콜록!$"

Route113_GlassWorkshop_Text_19E59B:: @ 819E59B
	.string "그 주머니를 가지고\n"
	.string "재가 쌓여 있는 곳에 들어가면\l"
	.string "어머 신기해라!\p"
	.string "주머니 속에 화산재가\n"
	.string "모일 거야 콜록콜록!\p"
	.string "화산재가 많이 모였다고 생각되면\n"
	.string "나한테 와 봐 콜록콜록!$"

Route113_GlassWorkshop_Text_19E65B:: @ 819E65B
	.string "화산재 있으려나 콜록콜록!\n"
	.string "어디 어디 한번 보여줘 콜록쿨럭!$"

Route113_GlassWorkshop_Text_19E697:: @ 819E697
	.string "음...\n"
	.string "화산재가 얼마 없어 콜록콜록!\l"
	.string "유리로 된 도구를\l"
	.string "만들 수 없어 콜록콜록!\p"
	.string "앞으로 {STR_VAR_1}걸음 더 걸으면\n"
	.string "파랑비드로를 만들 수 있어 콜록콜록!$"

Route113_GlassWorkshop_Text_19E757:: @ 819E757
	.string "오오!\n"
	.string "화산재 모여 있어 콜록콜록!\l"
	.string "유리로 된 도구\l"
	.string "만들 수 있어 콜록콜록!\p"
	.string "어떤 게 좋을까나 콜록콜록$"

Route113_GlassWorkshop_Text_19E7CD:: @ 819E7CD
	.string "{STR_VAR_1} 말이지 콜록콜록!\n"
	.string "정말 이걸로 할 거지? 콜록콜록$"

Route113_GlassWorkshop_Text_19E802:: @ 819E802
	.string "어떤 게 좋을까나 콜록콜록$"

Route113_GlassWorkshop_Text_19E827:: @ 819E827
	.string "{STR_VAR_1} 말이지 콜록콜록!\p"
	.string "좋아! 도구 만들게 콜록콜록!\n"
	.string "잠깐 기다리고 있어 콜록콜록$"

Route113_GlassWorkshop_Text_19E890:: @ 819E890
	.string "{STR_VAR_1} 말이지 콜록콜록!\p"
	.string "그치만 그걸 만들기 위해선\n"
	.string "아직 화산재가 부족해 콜록콜록!\p"
	.string "화산재가 쌓여 있는 곳을\n"
	.string "앞으로 {STR_VAR_2}걸음 더\l"
	.string "걸어야 해 콜록콜록!\p"
	.string "어떤 게 좋을까나 콜록콜록$"

Route113_GlassWorkshop_Text_19E990:: @ 819E990
	.string "기껏 화산재를 모아 왔는데\n"
	.string "갖고 싶은 건 없나 콜록콜록...$"

Route113_GlassWorkshop_Text_19E9D7:: @ 819E9D7
	.string "오오 {STR_VAR_1} 다 만들었어\n"
	.string "자 가져가 콜록콜록$"

Route113_GlassWorkshop_Text_19EA06:: @ 819EA06
	.string "어라?\n"
	.string "그 이상은 가지고\l"
	.string "다닐 수 없어 콜록콜록\p"
	.string "맡고 있을 테니까\n"
	.string "다음에 와 콜록콜록$"

Route113_GlassWorkshop_Text_19EA64:: @ 819EA64
	.string "어라?\n"
	.string "PC가 가득 찼네 콜록콜록\p"
	.string "맡고 있을 테니까\n"
	.string "다음에 와 콜록콜록$"

Route113_GlassWorkshop_Text_19EAC1:: @ 819EAC1
	.string "어라? 검댕자루를\n"
	.string "지니고 있지 않네 콜록콜록\p"
	.string "가지고 다니지 않으면\n"
	.string "화산재를 모을 수 없어 콜록콜록$"

Route113_GlassWorkshop_Text_19EB3B:: @ 819EB3B
	.string "스승님이 말씀하시는 거에 맞춰서\n"
	.string "비드로를 불면 즐거워!\p"
	.string "콜록콜록! 콜록쿨럭!$"
