DewfordTown_Text_16E080:: @ 816E080
	.string "하기: 호이! 잿빛도시에 도착!\p"
	.string "분명 해양씨한테\n"
	.string "데봉화물을 전달한다고 했었지!$"

Route109_Text_16E0F9:: @ 816E0F9
	.string "하기: 화물을 전달 안 하나?\p"
	.string "그게 아니면\n"
	.string "무로마을로 돌아가는 겐가?$"

Route109_Text_16E159:: @ 816E159
	.string "하기: 무로마을 말이지\p"
	.string "좋다! 가자 피코!$"

Route109_Text_16E1B1:: @ 816E1B1
	.string "하기: 그럼 화물을 전달하고 오게나\n"
	.string "난 여기서 기다리고 있을 테니$"

DewfordTown_Text_16E1FA:: @ 816E1FA
	.string "하기: 호이! 잿빛도시에 도착!\p"
	.string "배를 타고 싶어지면\n"
	.string "언제든 나한테 말해 주게나!$"

Route109_Text_16E26A:: @ 816E26A
	.string "하기: 여어! 자네가 원한다면\n"
	.string "언제든지 배를 준비시키지!\p"
	.string "자네가 가고 싶은 곳은 어딘가?$"

Route109_Text_16E2C5:: @ 816E2C5
	.string "하기: 배를 타야 할 때는\n"
	.string "언제든지 말해 주게나$"

Route109_Text_16E307:: @ 816E307
	.string "뜨거운 트레이너 분들! 그리고\n"
	.string "뜨겁지 않은 트레이너 분들!\l"
	.string "모두 저희 아빠 가게에 들러주세요-!$"

Route109_Text_16E35B:: @ 816E35B
	.string "아이는 이곳저곳 돌아다니니까\n"
	.string "걱정이 돼서 눈을 뗄 수가 없어!\p"
	.string "그나마 포켓몬이 같이 있으니까\n"
	.string "괜찮을 거라고 생각하지만...$"

Route109_Text_16E405:: @ 816E405
	.string "좀처럼 모래성이 완성이 안돼$"

Route109_Text_16E433:: @ 816E433
	.string "{K_GIRL_CALL}!\n"
	.string "이거 줄게!$"

Route109_Text_16E446:: @ 816E446
	.string "모래사장에 있는 모래 전-부 모아서\n"
	.string "커-다란 성을 만들 거야\p"
	.string "그래서 우리는\n"
	.string "왕이랑 여왕이 될 거야\p"
	.string "{K_GIRL_CALL}는 특별히\n"
	.string "우리 신하 하게 해줄게$"

Route109_Text_16E4D5:: @ 816E4D5
	.string "이 주변 바다는 깨끗하긴 한데\p"
	.string "그래도 가끔 이렇게 버려지는\n"
	.string "쓰레기를 지그제구리가\l"
	.string "모아주고 있단다\p"
	.string "더러워진 물은 비가 돼서\n"
	.string "강으로 흘러 들어가\l"
	.string "마시는 물이 되지...\p"
	.string "결국 바다를 더럽히면\n"
	.string "피해를 보는 건\l"
	.string "자기 자신이란 소리야$"

Route109_Text_16E5CA:: @ 816E5CA
	.string "지그제구리: 구구?$"

Route109_Text_16E5DC:: @ 816E5DC
	.string "“바다의 집”\p"
	.string "모래사장 하면 또 포켓몬 승부지!\n"
	.string "뜨거운 트레이너들은 여기 모여라!$"

Route109_Text_16E62C:: @ 816E62C
	.string "정보 나눔 게시판!!\p"
	.string "포켓몬의 레벨이 같아도\n"
	.string "그 파워까지 같진 않아요!\p"
	.string "그리고 트레이너가 키운\n"
	.string "포켓몬이 더 강해진다고\l"
	.string "알려져 있지요!$"
