PetalburgCity_Text_16D361:: @ 816D361
	.string "민진: {PLAYER}님...\n"
	.string "포켓몬은 보통 이런 풀숲에\l"
	.string "있지 않나요...?\p"
	.string "제가 잘 잡는지\n"
	.string "옆에서 한번 봐주세요...\p"
	.string "...우와!!$"

PetalburgCity_Text_16D3DE:: @ 816D3DE
	.string "민진: 잡혔어...내...\n"
	.string "내 포켓몬이다...!!$"

PetalburgCity_Text_16D408:: @ 816D408
	.string "{PLAYER}님 고마워요!\n"
	.string "체육관으로 같이 돌아가요!$"

Route102_Text_16D431:: @ 816D431
	.string "난... 키가 작아서\n"
	.string "풀숲을 걸으면\p"
	.string "풀잎이 코에 들어가\n"
	.string "에 에 에...\p"
	.string "엣치!$"

UnknownString_816D4A5: @ 816D4A5
	.string "후후후...\n"
	.string "내가 하는 걸 잘 봐$"

UnknownString_816D4BB: @ 816D4BB
	.string "짜-잔! 어때 멋지지?\p"
	.string "이렇게 턱이 진 곳은 올라갈 수는\n"
	.string "없지만 내려가는 건 간단하다고!$"

Route102_Text_16D51A:: @ 816D51A
	.string "포켓몬 많이 많이 잡아야지-!$"

Route102_Text_16D547:: @ 816D547
	.string "여기는 102번 도로\n"
	.string "{0x7C} 고도마을$"

Route102_Text_16D55F:: @ 816D55F
	.string "여기는 102번 도로\n"
	.string "{0x7B} 등화도시$"
