Route114_Text_170154:: @ 8170154
	.string "내 포켓몬 매일 울부짖기만 해서\n"
	.string "다들 도망가 버려요...\p"
	.string "당신이 괜찮다면\n"
	.string "이 기술머신 좀 가져가 주세요$"

Route114_Text_1701C5:: @ 81701C5
	.string "기술머신05의 내용은 울부짖기예요\n"
	.string "울부짖으면 포켓몬이 도망간답니다$"

Route114_Text_1701F9:: @ 81701F9
	.string "포!! 포포!!$"

Route114_Text_170206:: @ 8170206
	.string "여기는 유성의 폭포\n"
	.string "여길 지나가면 금탄도시$"

Route114_Text_17022E:: @ 817022E
	.string "“화석마니아의 집”\n"
	.string "희귀한 화석이 있으면 주세요!$"

Route114_Text_170263:: @ 8170263
	.string "“보은의 집”$"
