Route111_OldLadysRestStop_Text_1923AF:: @ 81923AF
	.string "아니 아니 자네의 포켓몬\n"
	.string "지쳐 있는 것 같구먼\p"
	.string "괜찮으면 쉬었다가 가시게나!\n"
	.string "그래! 쉴 땐 쉬어야지!$"

Route111_OldLadysRestStop_Text_192423:: @ 8192423
	.string "그래그래\n"
	.string "여기서 푹 쉬고 가시게!$"

Route111_OldLadysRestStop_Text_19244D:: @ 819244D
	.string "아니 아니\n"
	.string "아직 지쳐 있구먼?\p"
	.string "좀 더 쉬었다 가시게나!\n"
	.string "그래! 쉴 땐 쉬어야지!$"

Route111_OldLadysRestStop_Text_1924C6:: @ 81924C6
	.string "그려...?\n"
	.string "정말 괜찮은 겐가?\l"
	.string "사양 말게나$"
