Route124_DivingTreasureHuntersHouse_Text_19F416:: @ 819F416 //JP: 17F193
	.string "난 다이빙 트레져헌터!\p"
	.string "깊은 바닷속으로 잠수해서\n"
	.string "해저에 잠들어 있는 보물을 모으는\l"
	.string "대단한 녀석이야!$"

Route124_DivingTreasureHuntersHouse_Text_19F48F:: @ 819F48F
	.string "머나먼 옛날에 만들어졌다고 하는\n"
	.string "다양한 조각 발견했어?$"

Route124_DivingTreasureHuntersHouse_Text_19F4D1:: @ 819F4D1
	.string "너 보물 안 가지고 있구나...\p"
	.string "빨강조각이라든가\n"
	.string "다양한 조각 발견하면\l"
	.string "교환해 줘!$"

Route124_DivingTreasureHuntersHouse_Text_19F544:: @ 819F544
	.string "오오! 이건!\n"
	.string "내가 찾고 있던 조각!!\p"
	.string "저기 말이야!\n"
	.string "네가 가지고 있는 보물이랑\l"
	.string "내 보물이랑 교환해 줘!$"

Route124_DivingTreasureHuntersHouse_Text_19F5C5:: @ 819F5C5
	.string "어떤 거랑 교환해 줄 거야?$"

Route124_DivingTreasureHuntersHouse_Text_19F5E0:: @ 819F5E0
	.string "{STR_VAR_1}을 {STR_VAR_2}이랑\n"
	.string "교환하는 거지?$"

Route124_DivingTreasureHuntersHouse_Text_19F606:: @ 819F606
	.string "교환 성립!\n"
	.string "소중하게 써 줘!$"

Route124_DivingTreasureHuntersHouse_Text_19F629:: @ 819F629
	.string "또 교환할래?$"

Route124_DivingTreasureHuntersHouse_Text_19F64E:: @ 819F64E
	.string "잠깐 가지고 있는 게 너무 많아\n"
	.string "도구를 좀 줄이고 와 줘$"

Route124_DivingTreasureHuntersHouse_Text_19F686:: @ 819F686
	.string "그거 실망인데\n"
	.string "마음이 바뀌면 다시 와 줘!$"

Route124_DivingTreasureHuntersHouse_Text_19F6C5:: @ 819F6C5
	.string "원하는 것       교환할 것\n"
	.string " 빨강조각   {0x7B}{0x7C} 불꽃의돌\p"
	.string "원하는 것       교환할 것\n"
	.string " 노랑조각   {0x7B}{0x7C} 천둥의돌\p"
	.string "원하는 것       교환할 것\n"
	.string " 파랑조각   {0x7B}{0x7C} 물의돌\p"
	.string "원하는 것       교환할 것\n"
	.string " 초록조각   {0x7B}{0x7C} 리프의돌$"
