Route110_TrickHousePuzzle2_Text_19CD46:: @ 819CD46
	.string "어느 스위치로\n"
	.string "어느 구멍이 닫히는 거지?$"

Route110_TrickHousePuzzle2_Text_19CD66:: @ 819CD66
	.string "승부했더니\n"
	.string "더 알 수 없게 돼버렸어!$"

Route110_TrickHousePuzzle2_Text_19CD91:: @ 819CD91
	.string "너 나 대신에\n"
	.string "스위치 전부 눌러주라!$"

Route110_TrickHousePuzzle2_Text_19CDBF:: @ 819CDBF
	.string "우옷! 미궁의 대저택에\n"
	.string "2번 챌린지하는 거구나!$"

Route110_TrickHousePuzzle2_Text_19CDF0:: @ 819CDF0
	.string "포켓몬 승부도 잘하는 거야?$"

Route110_TrickHousePuzzle2_Text_19CE0D:: @ 819CE0D
	.string "미궁대왕 혼자서\n"
	.string "이 장치들을 만들었나봐!$"

Route110_TrickHousePuzzle2_Text_19CE52:: @ 819CE52
	.string "언젠가 내 체육관을 만들고 싶어서\n"
	.string "여기의 장치들을 연구하는 중이야!$"

Route110_TrickHousePuzzle2_Text_19CE98:: @ 819CE98
	.string "포켓몬 승부는\n"
	.string "연구가 부족했어-!$"

Route110_TrickHousePuzzle2_Text_19CEB8:: @ 819CEB8
	.string "너 강하구나... 체육관 관장이\n"
	.string "될 수 있을 거 같은데?$"

UnknownString_819CEF9: @ 819CEF9
	.string "{PLAYER}\s 암호를\n"
	.string "문에 적었다!\p"
	.string "“미궁대왕님 존경”\p"
	.string "... ... ...\p"
	.string "문의 자물쇠가 풀렸다!$"
