Route110_TrickHouseEnd_Text_19C281:: @ 819C281
	.string "앗!\n"
	.string "자네 여기까지 온 건가!\l"
	.string "음...대단한데!$"

Route110_TrickHouseEnd_Text_19C2B2:: @ 819C2B2
	.string "밤을 새서 나무 심었는데...\p"
	.string "이 몸 다음 다음 다음\n"
	.string "다음 다음 다음으로\l"
	.string "대단하군! $"

Route110_TrickHouseEnd_Text_19C333:: @ 819C333
	.string "밤을 새서\n"
	.string "바위를 옮겨 놓았는데....\p"
	.string "이 몸 다음 다음 다음\n"
	.string "다음 다음으로\l"
	.string "대단하군!$"

Route110_TrickHouseEnd_Text_19C3A7:: @ 819C3A7
	.string "밤을 새서 창문 막아\n"
	.string "방 안을 어둡게 했는데...\p"
	.string "이 몸 다음 다음 다음 다음으로\n"
	.string "대단하군!$"

Route110_TrickHouseEnd_Text_19C41F:: @ 819C41F
	.string "밤을 새서 바위를 밀어 놨는데...\p"
	.string "이 몸 다음 다음 다음으로\n"
	.string "대단하군!$"

Route110_TrickHouseEnd_Text_19C491:: @ 819C491
	.string "밤을 새서 인형 만들고\n"
	.string "밤을 새서 퀴즈 생각했는데...\p"
	.string "이 몸 다음 다음으로\n"
	.string "대단하군!$"

Route110_TrickHouseEnd_Text_19C515:: @ 819C515
	.string "밤을 새서 문을\n"
	.string "설치해 놓았는데...\p"
	.string "이 몸 다음으로\n"
	.string "대단하군!$"

Route110_TrickHouseEnd_Text_19C567:: @ 819C567
	.string "밤을 새서 화살표 정렬해 놨는데...\p"
	.string "이 몸과 비슷할 만큼 대단해!$"

Route110_TrickHouseEnd_Text_19C5AF:: @ 819C5AF
	.string "밤을 새서 바닥을 닦아 놨는데...\p"
	.string "이 몸보다 더 대단할지도...!$"

Route110_TrickHouseEnd_Text_19C602:: @ 819C602
	.string "어 어쩌지...\n"
	.string "숨겨진 장치를 만들 만한\l"
	.string "아이디어가 다 떨어져버렸어...\p"
	.string "또 전국 각지를 돌면서\n"
	.string "새로운 장치를 생각해와야겠다...$"

Route110_TrickHouseEnd_Text_19C691:: @ 819C691
	.string "인정하고 싶진 않지만\n"
	.string "자네한테는 졌다...!\p"
	.string "뭐 그렇게 몇 번이나 와준 걸 보면\n"
	.string "그만큼 이 몸이\l"
	.string "매력 있었단 소리겠지만\l"
	.string "그거랑 이 몸이 진 거랑은 상관없어!\p"
	.string "아 그래!\p"
	.string "노력파인 자네와\n"
	.string "천재인 이 몸의\l"
	.string "우정을 기념해서...\p"
	.string "이걸 주도록 하지!$"

Route110_TrickHouseEnd_Text_19C7D7:: @ 819C7D7
	.string "뭐 PC에 들어가지 않는다고?\n"
	.string "그런 거 내 알 바냐!\p"
	.string "...라고 말하고 싶지만\n"
	.string "이 몸은 상냥하니까\l"
	.string "나중에 찾으러 오도록!$"

Route110_TrickHouseEnd_Text_19C85C:: @ 819C85C
	.string "... ... ...\p"
	.string "이 몸은 이제부터\n"
	.string "새로운 아이디어를 찾으러\l"
	.string "여행을 떠날까 해...\p"
	.string "자네도 나중에 또\n"
	.string "여기 와서 놀다 가도록 해!\p"
	.string "그럼 안녕...!$"

Route110_TrickHouseEnd_Text_19C90B:: @ 819C90B
	.string "좋아 자네에게\n"
	.string "선물을 주지!$"

Route110_TrickHouseEnd_Text_19C92E:: @ 819C92E
	.string "뭣 전부 들 수가 없다고?\n"
	.string "뭘 그렇게 많이 들고 있는 건가?\l"
	.string "뭐 그래도 여기까지 와주었고\l"
	.string "상품은 다음에 주도록 하지!$"

Route110_TrickHouseEnd_Text_19C9BD:: @ 819C9BD
	.string "어쭈 뭘 그렇게 자신있어 해\n"
	.string "이 몸한테 완전히 이기려면\l"
	.string "아직 멀었어!\p"
	.string "앞으로 또 새로운 장치를 만들 테니\n"
	.string "그거나 돌파한 다음에 날 비웃어 봐!\p"
	.string "그럼 다음을 기대하도록!$"

Route110_TrickHouseEnd_Text_19CA8B:: @ 819CA8B
	.string "어이어이\n"
	.string "이 몸을 무시하는 거야!\l"
	.string "그거 아주 서러운데$"

UnknownString_819CAD1: @ 819CAD1
	.string "{PLAYER}{K_EUNNEUN} 암호를\n"
	.string "문에 적었다!\p"
	.string "“미궁대왕님 짱”\p"
	.string "... ... ...\p"
	.string "문의 자물쇠가 풀렸다!$"
