Route104_MrBrineysHouse_Text_191A82:: @ 8191A82
	.string "하기: 이 녀석!\n"
	.string "거기 서라 피코!$"

Route104_MrBrineysHouse_Text_191AAD:: @ 8191AAD
	.string "응? 자네는 저번에\n"
	.string "피코를 구해준 {PLAYER} 아니더냐!\l"
	.string "그때는 정말 신세 졌구먼!\p"
	.string "...뭐라고?\n"
	.string "배를 타고 싶다고?\p"
	.string "흠?\p"
	.string "무로마을까지 편지와\n"
	.string "잿빛도시에 화물을\l"
	.string "전달해야 한다고...\p"
	.string "그 정도야 식은 죽 먹기다!\n"
	.string "나에게 맡기게나!\l"
	.string "그럼 바로 무로마을로 가볼까!$"

Route104_MrBrineysHouse_Text_191BFD:: @ 8191BFD
	.string "하기: 무로마을 말이지\p"
	.string "좋아! 가자 피코!$"

Route104_MrBrineysHouse_Text_191C57:: @ 8191C57
	.string "하기: 그러냐\n"
	.string "부탁받은 일은 괜찮나?\p"
	.string "뭐 배를 타야 할 때는\n"
	.string "언제든지 사양 말고 말해 주게나!$"

Route104_MrBrineysHouse_Text_191CC3:: @ 8191CC3
	.string "하기: 자네가 무슨 말을\n"
	.string "하고 싶은지는 알고 있어!\p"
	.string "무로마을로 편지를 전달하고\n"
	.string "잿빛도시에 화물을 갖다 줘야\l"
	.string "하는 게지?\p"
	.string "그 정도야 식은 죽 먹기다!\n"
	.string "나에게 맡기게나!\p"
	.string "우선 무로마을로 출발하자꾸나$"

Route104_MrBrineysHouse_Text_191DA6:: @ 8191DA6
	.string "하기: 자네가 무슨 말을\n"
	.string "하고 싶은지는 알고 있어!\p"
	.string "잿빛도시에 있는 해양씨한테\n"
	.string "화물을 전달해야 하는 게지?\p"
	.string "그 정도야 식은 죽 먹기다!\n"
	.string "나에게 맡기게나!\p"
	.string "우선 무로마을로 출발하자꾸나$"

Route104_MrBrineysHouse_Text_191E80:: @ 8191E80
	.string "하기: 여어! 자네가 원한다면\n"
	.string "언제든지 배를 준비시키지!\p"
	.string "자네가 가고 싶은 곳은 어딘가?$"

Route104_MrBrineysHouse_Text_191EDB:: @ 8191EDB
	.string "하기: 그런가... 자네는\n"
	.string "피코의 생명의 은인이다\p"
	.string "배를 타야 할 때는\n"
	.string "언제든지 사양 말고 말해 주게나!$"

UnknownString_8191F4F: @ 8191F4F
	.string "하기: 호이! 등화도시에 도착!\p"
	.string "배를 타고 싶어지면\n"
	.string "언제든 나한테 말해 주게나!$"

Route104_MrBrineysHouse_Text_191FB9:: @ 8191FB9
	.string "피코: 피- 피피-!$"
