Route123_Text_171D83:: @ 8171D83 //JP: 153B55
	.string "나 풀타입 포켓몬이\n"
	.string "너무 좋아!\p"
	.string "당신은 풀타입 포켓몬\n"
	.string "가지고 있지 않아...?$"

Route123_Text_171DC2:: @ 8171DC2
	.string "어라?\p"
	.string "너도 풀타입 포켓몬을\n"
	.string "정말 좋아하는구나!\p"
	.string "기쁘니까 이거 줄게!\n"
	.string "우리가 친구라는 증표야!$"

Route123_Text_171E34:: @ 8171E34
	.string "풀포켓몬이랑 같이\n"
	.string "나무들의 상태를 보고 다니고 있어\l"
	.string "이름 붙이자면 나무 의사 같은 거지$"

Route123_Text_171E76:: @ 8171E76
	.string "{0x7C} 123번 도로\n"
	.string "{0x7B} 118번 도로$"

Route123_Text_171E8E:: @ 8171E8E
	.string "{0x79}...송화산\n"
	.string "마음 약한 자 접근하지 말 것$"

Route123_Text_171EBC:: @ 8171EBC
	.string "“나무열매 명인의 집”$"
