Route119_Text_1710BB:: @ 81710BB
	.string "봄이: {PLAYER}!\n"
	.string "어디에 있었어? 찾았잖아!\p"
	.string "얼마나 강해졌는지\n"
	.string "잠깐 시험해 볼게!\p"
	.string "포켓몬의 준비는...\n"
	.string "당연히 끝났겠지! 간다!$"

Route119_Text_171156:: @ 8171156
	.string "으아-!\n"
	.string "{PLAYER} 강하잖아!\p"
	.string "포켓몬을 키우지 못해서\n"
	.string "곤란할 거라고 걱정하고 있었는데$"

Route119_Text_1711B1:: @ 81711B1
	.string "봄이: 전혀 아무렇지도 않아!\n"
	.string "그 기세로 힘내도록 해!\p"
	.string "이건 내가 주는 선물이야!$"

Route119_Text_171214:: @ 8171214
	.string "봄이: 공중날기를 쓰면\n"
	.string "한 번 갔던 도시라면 순식간에\l"
	.string "날아갈 수 있게 돼!\p"
	.string "하지만 공중날기를 쓰려면\n"
	.string "검방울시티의\l"
	.string "체육관 배지가 필요해\l"
	.string "이거 중요한 거니까 잊지 마!\p"
	.string "가끔 공중날기로\n"
	.string "미로마을에 가보는 것도\l"
	.string "좋을 것 같아\p"
	.string "{PLAYER}네 엄마\n"
	.string "걱정하고 계실지도 모르니까...\p"
	.string "그럼\n"
	.string "또 어딘가에서 만나!$"

Route119_Text_171358:: @ 8171358
	.string "휘웅: {PLAYER}!\n"
	.string "여기에서 포켓몬 찾고 있었어?\p"
	.string "얼마나 강해졌는지\n"
	.string "시험해 줄게\p"
	.string "자!\n"
	.string "승부 승부다!$"

Route119_Text_1713E2:: @ 81713E2
	.string "흠...\n"
	.string "꽤 강해졌구나$"

Route119_Text_17140B:: @ 817140B
	.string "휘웅: 그 정도면\n"
	.string "어디에서 포켓몬을 찾아도\l"
	.string "아무 문제 없겠는데\p"
	.string "이거 줄 테니까 써 봐!$"

Route119_Text_171475:: @ 8171475
	.string "휘웅: 공중날기를 쓰면\n"
	.string "한 번 갔던 도시라면\l"
	.string "순식간에 날아갈 수 있어\p"
	.string "단지 검방울시티 체육관의\n"
	.string "체육관 배지가 필요하지만...\p"
	.string "그럼 난 먼저 갈게$"

Route119_Text_171520:: @ 8171520
	.string "우린 여기에서 망을 보고 있지\p"
	.string "어이 너! 위험하니까\n"
	.string "날씨 연구소에는 가까이 가지 마$"

Route119_Text_17157C:: @ 817157C
	.string "망보는 건 의외로 한가롭네...\p"
	.string "어이 너! 부탁이니까 연구소에는\n"
	.string "가까이 가지 마라!$"

Route119_Text_1715D7:: @ 81715D7
	.string "새포켓몬을 많이 잡아서\n"
	.string "매달리면\l"
	.string "하늘을 날 수 있을 거라 생각했어요\p"
	.string "그런데 “공중날기”라는\n"
	.string "비전기술이 있다는 거예요!?\p"
	.string "좀 더 일찍 알고 싶었는데...$"

Route119_Text_171698:: @ 8171698
	.string "큰일이야...\p"
	.string "긴 풀이 타이어에 휘감기니까\n"
	.string "자전거를 탈 수가 없어...$"

Route119_Text_1716F4:: @ 81716F4
	.string "너의 포켓몬\n"
	.string "비밀의힘이라는 기술을 써서\l"
	.string "큰 풀 덩어리에\l"
	.string "비밀기지를 만들 수 있어?$"

Route119_Text_171749:: @ 8171749
	.string "여기는 119번도로\n"
	.string "{0x7C} 검방울시티$"

Route119_Text_171762:: @ 8171762
	.string "“날씨 연구소”$"

Route119_Text_171774:: @ 8171774
	.string "정보 나눔 게시판!!\p"
	.string "비밀기지에는 굿즈를\n"
	.string "16개까지 놓을 수 있습니다!\p"
	.string "좋아하는 굿즈를 선택해서\n"
	.string "당신만의 마음에 드는\l"
	.string "비밀기지를 만듭시다!$"
