Route112_Text_16FDF0:: @ 816FDF0
	.string "중얼중얼...\p"
	.string "단풍마을로 향한 자들은...\n"
	.string "뭘 꾸물거리고 있는 거지...$"

Route112_Text_16FE3E:: @ 816FE3E
	.string "중얼중얼...\p"
	.string "나도 케이블카 타고\n"
	.string "정상으로 가고 싶다...$"

Route112_Text_16FE7A:: @ 816FE7A
	.string "끄응... 보라시티로 가고 싶은데...\n"
	.string "이 턱을 내려가면\l"
	.string "용암마을로 돌아가는 게 어렵다고...$"

Route112_Text_16FEED:: @ 816FEED
	.string "“굴뚝산 케이블카 승강장”\n"
	.string "{0x79} 바로 이 앞!$"

Route112_Text_16FF19:: @ 816FF19
	.string "“굴뚝산”\p"
	.string "용암마을이나 정상으로 가려면\n"
	.string "케이블카를 이용해 주십시오$"

Route112_Text_16FF64:: @ 816FF64
	.string "여기는 112번 도로\n"
	.string "{0x7B} 용암마을$"
