Route111_WinstrateFamilysHouse_Text_191FCE:: @ 8191FCE
	.string "너 정도로 포켓몬을 능숙하게\n"
	.string "다루는 트레이너는 처음이군!\p"
	.string "하지만 너보다\n"
	.string "우리 아들이 더 강하다!\p"
	.string "뭐니 뭐니 해도 포켓몬리그에\n"
	.string "도전하러 갔을 정도니 말이다!$"

Route111_WinstrateFamilysHouse_Text_19208A:: @ 819208A
	.string "우리 가족 모두는\n"
	.string "교정깁스로 포켓몬을\l"
	.string "단련시키고 있어요!\p"
	.string "우리 가족 모두에게 이긴\n"
	.string "당신에겐 필요 없을지도 모르지만\l"
	.string "꼭 받아주셨으면 해요!$"

Route111_WinstrateFamilysHouse_Text_19214D:: @ 819214D
	.string "우리는 포켓몬 승부에\n"
	.string "정열을 쏟아붓고 있어요!$"

Route111_WinstrateFamilysHouse_Text_192190:: @ 8192190
	.string "아빠보다 엄마가 강하고\p"
	.string "엄마보다 내가 강하고\p"
	.string "나보다 할머니가 강하지\p"
	.string "하지만 할머니보다 강한 건\n"
	.string "우리 오빠야!$"

Route111_WinstrateFamilysHouse_Text_192219:: @ 8192219
	.string "네가 아무리 강해도\n"
	.string "우리 손자를 만나면\l"
	.string "패배의 눈물을 흘리게 될 게다...\p"
	.string "우리 가족이 알고 있는\n"
	.string "그 어떤 트레이너보다\l"
	.string "강했으니까 말이다!\p"
	.string "손주 녀석도 지금쯤\n"
	.string "포켓몬리그 챔피언에\l"
	.string "도전하고 있겠구먼\p"
	.string "아니면 내 손주답게\n"
	.string "벌써 챔피언이\l"
	.string "돼 있을지도 모르지... 이히히!$"

Route111_WinstrateFamilysHouse_Text_192334:: @ 8192334
	.string "손주 녀석도 지금쯤\n"
	.string "포켓몬리그 챔피언에\l"
	.string "도전하고 있겠구먼\p"
	.string "아니면 내 손주답게\n"
	.string "벌써 챔피언이\l"
	.string "돼 있을지도 모르지... 이히히!$"
