Route104_Text_16DA13:: @ 816DA13
	.string "저기 해변에 있는 작은 집에는\n"
	.string "하기노인이라는 사람이 살고 있어!\p"
	.string "옛날에는 아무리 거친 파도도\n"
	.string "무서워하지 않는\l"
	.string "실력 있는 선원이었대!$"

Route104_Text_16DA89:: @ 816DA89
	.string "바다라...\p"
	.string "바다 깊은 곳은\n"
	.string "과연 어떤 모습일까?$"

Route104_Text_16DAC9:: @ 816DAC9
	.string "몬스터볼을 던질 때\n"
	.string "포켓몬의 기술로\l"
	.string "독이나 화상 상태로 만들거나\p"
	.string "잠들게 해 놓으면\n"
	.string "훨씬 잡기 쉬워!$"

Route104_Text_16DB5C:: @ 816DB5C
	.string "남의 포켓몬을 잡는 건 도둑이야\p"
	.string "몬스터볼은\n"
	.string "야생 포켓몬에게만 던져야 돼!$"

Route104_Text_16DBC9:: @ 816DBC9
	.string "난 트레이너가 아니야\p"
	.string "그치만 트레이너끼리 눈이 마주치면\n"
	.string "승부를 하자는 사인이지!\p"
	.string "만약에 싸우고 싶지 않을 때는\n"
	.string "눈을 마주치지 않으면 돼!$"

Route104_Text_16DC5F:: @ 816DC5F
	.string "안녕! 씨앗으로 입안을 가득 채우고\n"
	.string "빠르게 뱉는 게 상쾌해서 좋아!\p"
	.string "너도 이거 줄 테니까 한번 써 봐!\p"
	.string "포켓몬에게 쓰면 씨앗으로\n"
	.string "공격하는 기술을 배울 거야!$"

Route104_Text_16DD0E:: @ 816DD0E
	.string "하나 어드바이스 해줄게!\p"
	.string "기술머신은 한 번 사용하면\n"
	.string "사라지게 되어버려\p"
	.string "그러니 사용할 때는 누구에게\n"
	.string "가르칠지 신중하게 결정하도록 해!$"

Route104_Text_16DD91:: @ 816DD91
	.string "요즘에 여기 꽃집\n"
	.string "화분도 팔고 있어!\p"
	.string "너무 기뻐서 많이 샀거든\n"
	.string "그래서 내 하양허브는\l"
	.string "이제 필요 없어\l"
	.string "그러니까 네가 가져가!$"

Route104_Text_16DE36:: @ 816DE36
	.string "요즘에 여기 꽃집\n"
	.string "화분도 팔고 있어!\p"
	.string "너무 기뻐서 많이 샀어!\n"
	.string "이걸 어디다 장식할까?$"

Route104_Text_16DEB3:: @ 816DEB3
	.string "“하기노인의 작은 집”$"

Route104_Text_16DEC8:: @ 816DEC8
	.string "여기는 104번 도로\n"
	.string "{0x7C} 등화도시$"

Route104_Text_16DEE3:: @ 816DEE3
	.string "여기는 104번 도로\n"
	.string "{0x79} 금탄도시$"

Route104_Text_16DEFD:: @ 816DEFD
	.string "“플라워숍 꽃잎 화원”$"

Route104_Text_16DF16:: @ 816DF16
	.string "정보 나눔 게시판!!\p"
	.string "호연지방의 트레이너 중에는\n"
	.string "더블배틀이라고 해서 2대2로\l"
	.string "포켓몬 승부를 걸어오는\l"
	.string "사람들이 있습니다!\p"
	.string "더블배틀에서는 포켓몬의 리스트\n"
	.string "왼쪽 위와\l"
	.string "오른쪽 위에 있는 포켓몬이\p"
	.string "제일 먼저 나가서\n"
	.string "배틀에 참가하기 때문에\l"
	.string "리스트 순서에 주의합시다!$"
