Route117_Text_170C26:: @ 8170C26
	.string "키우미집에 포켓몬을\n"
	.string "맡겨놓고 있었어\p"
	.string "그랬더니 글쎄 내 포켓몬이 어느샌가\n"
	.string "모르는 기술을 배우고 있어서\l"
	.string "깜짝 놀랐지 뭐야!$"

Route117_Text_170CA7:: @ 8170CA7
	.string "어때?\n"
	.string "예쁘게 늘어선 이 꽃들!\p"
	.string "전부 다- 내가 심은 거야!$"

Route117_Text_170CEB:: @ 8170CEB
	.string "공기가 마시쪄-!$"

Route117_Text_170D02:: @ 8170D02
	.string "여기는 117번도로\n"
	.string "{0x7B} 잔디마을$"

Route117_Text_170D1E:: @ 8170D1E
	.string "여기는 117번도로\n"
	.string "{0x7C} 보라시티$"

Route117_Text_170D38:: @ 8170D38
	.string "“포켓몬 키우미집”\n"
	.string "당신의 포켓몬을 키워 드립니다$"
