Route120_Text_171827:: @ 8171827
	.string "성호: 응? {PLAYER}{K_I}구나\n"
	.string "오랜만이네\p"
	.string "여기에 보이지 않는 무언가가 있지?\p"
	.string "그 보이지 않는 무언가에게\n"
	.string "이 도구를 쓰면...\p"
	.string "아니지... 설명하는 것보다\n"
	.string "실제로 써보는 편이 재미있겠어\p"
	.string "{PLAYER} 너의 포켓몬\n"
	.string "승부할 준비는 돼 있나?$"

Route120_Text_17193D:: @ 817193D
	.string "성호: 그래?\p"
	.string "나는 여기서 기다리고 있을 테니\n"
	.string "준비를 하도록 해$"

Route120_Text_17196F:: @ 817196F
	.string "성호: {PLAYER} 너의 포켓몬\n"
	.string "승부할 준비는 돼 있나?$"

Route120_Text_1719A0:: @ 81719A0
	.string "성호: {PLAYER}\n"
	.string "너의 트레이너로서의\l"
	.string "실력을 보여줘!$"

Route120_Text_1719D4:: @ 81719D4
	.string "성호는\n"
	.string "데봉스코프를 사용했다!\p"
	.string "투명했던 포켓몬의 모습이\n"
	.string "훤히 보이게 됐다!\p"
	.string "포켓몬은\n"
	.string "놀라서 덤벼들었다!$"

Route120_Text_171A40:: @ 8171A40
	.string "성호: 역시\n"
	.string "너의 배틀 방식은 재미있구나\p"
	.string "처음에 무로마을에서 만났을 때보다\n"
	.string "포켓몬도 성장해 있고...\p"
	.string "그렇지\n"
	.string "이 데봉스코프는 너에게 줄게\p"
	.string "또 모습을 숨기고 있는\n"
	.string "포켓몬이 있을지도 모르니까$"

Route120_Text_171B0E:: @ 8171B0E
	.string "성호: {PLAYER}\p"
	.string "나는 열심히 하는\n"
	.string "트레이너와 포켓몬을 좋아하지\p"
	.string "그래서 너도 좋아해\p"
	.string "그럼\n"
	.string "다시 어딘가에서 만나자!$"

Route119_Text_171B93:: @ 8171B93
Route120_Text_171B93:: @ 8171B93
	.string "보이지 않는 무언가가 있는 것 같다$"

Route119_Text_171BB6:: @ 8171BB6
	.string "보이지 않는 무언가가 있는 것 같다\p"
	.string "데봉스코프를 사용하겠습니까?$"

Route119_Text_171BF6:: @ 8171BF6
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "데봉스코프를 사용했다!\p"
	.string "투명했던 포켓몬의 모습이\n"
	.string "훤히 보이게 됐다!\p"
	.string "포켓몬은\n"
	.string "놀라서 덤벼들었다!$"

Route120_Text_171C5E:: @ 8171C5E
	.string "여기는 120번 도로\n"
	.string "{0x7B} 검방울시티$"

Route120_Text_171C77:: @ 8171C77
	.string "{0x7C} 121번 도로\n"
	.string "{0x7B} 120번 도로$"
