Route118_Text_170D66:: @ 8170D66
	.string "성호: 안녕!\p"
	.string "넌 무로마을에서 만났던\n"
	.string "트레이너였지!\p"
	.string "... ... ... ...\n"
	.string "... ... ... ...\p"
	.string "그래 {PLAYER}{K_I}라고 하는구나\n"
	.string "기억해둘게\p"
	.string "{PLAYER}\p"
	.string "이 넓은 세계에는\n"
	.string "다양한 포켓몬이 있고\l"
	.string "각자 여러 가지 타입을 가지고 있어\p"
	.string "여러 가지 타입의\n"
	.string "포켓몬을 키울 것인가\l"
	.string "아니면 좋아하는 타입의\l"
	.string "포켓몬만을 키울 것인가...\p"
	.string "넌 포켓몬 트레이너로서\n"
	.string "어떻게 생각해?\p"
	.string "내가 신경 쓸 건 아니긴 한데\p"
	.string "그럼\n"
	.string "또 만날 수 있음 좋겠네$"

Route118_Text_170F12:: @ 8170F12
	.string "음!\n"
	.string "좋은낚싯대는 정말 좋은 거 같아!\p"
	.string "너도 그렇게 생각하지?$"

Route118_Text_170F46:: @ 8170F46
	.string "음!\n"
	.string "너랑은 죽이 맞는데!\p"
	.string "음!\n"
	.string "좋은낚싯대를 줄게!$"

Route118_Text_170F7E:: @ 8170F7E
	.string "물이 있는 곳이라면\n"
	.string "어디서든 낚시를 하는 게 좋을 거야!$"

Route118_Text_170FB0:: @ 8170FB0
	.string "낚시 싫어하니?$"

Route118_Text_170FC8:: @ 8170FC8
	.string "좋은낚싯대로\n"
	.string "다양한 포켓몬을 낚아 봐!$"

Route118_Text_170FFE:: @ 8170FFE
	.string "배를 안 가지고 있어도\n"
	.string "파도타기를 배운 포켓몬이 있으면\l"
	.string "바다든 강이든 건너갈 수 있어!\p"
	.string "포켓몬은 정말 믿음직스러운 거 같아!$"

Route118_Text_17108B:: @ 817108B
	.string "여기는 118번 도로\n"
	.string "{0x7B} 보라시티$"

Route118_Text_1710A5:: @ 81710A5
	.string "여기는 118번 도로\n"
	.string "{0x79} 119번 도로$"
