Route113_Text_16FF7F:: @ 816FF7F
	.string "와하하!!\n"
	.string "요즘 과학의 힘은 정말 대단해요!\p"
	.string "놀랍게도 이 화산재를\n"
	.string "유리로 바꿀 수 있으니까요!$"

Route113_Text_16FFEE:: @ 816FFEE
	.string "화산재가 가득 쌓인 풀숲 위에서\n"
	.string "걸으면 지나온 곳을 알 수 있어서\l"
	.string "재밌어지게 돼!$"

Route113_Text_170065:: @ 8170065
	.string "여기는 113번 도로\n"
	.string "{0x7C} 111번 도로$"

Route113_Text_17007B:: @ 817007B
	.string "여기는 113번 도로\n"
	.string "{0x7B} 단풍마을$"

Route113_Text_170096:: @ 8170096
	.string "정보 나눔 게시판!!\p"
	.string "가방의 중요한 물건에 넣은\n"
	.string "도구를 등록해 두면\l"
	.string "SELECT 버튼을 눌러서\l"
	.string "쓸 수 있어서 편리해요!$"

Route113_Text_17011D:: @ 817011D
	.string "“유리 세공 가게”\n"
	.string "화산재로 유리를 만들어요$"
