Route110_Text_16E6C0:: @ 816E6C0
	.string "{EVIL_TEAM}단의 활동에 대해서\n"
	.string "지금은 아직\l"
	.string "아무에게도 말할 수 없어$"

Route110_Text_16E6F2:: @ 816E6F2
	.string "나도 잿빛도시에 가서\n"
	.string "한바탕하고 싶었는데-!$"

Route110_Text_16E729:: @ 816E729
	.string "{EVIL_TEAM}단에 들어와서 맡은\n"
	.string "첫 일이야... 두근두근$"

Route110_Text_16E76A:: @ 816E76A
	.string "{EVIL_TEAM}단의 활동은 반드시\n"
	.string "사람들에게 웃음을 주게 될 거야$"

Route110_Text_16E7A1:: @ 816E7A1
	.string "봄이: {PLAYER}{K_AYA} 오랜만!\p"
	.string "여러 포켓몬을 찾는 동안에\n"
	.string "내 포켓몬들도 강해졌어!\p"
	.string "그러니까...\n"
	.string "잠깐 승부하자!$"

Route110_Text_16E826:: @ 816E826
	.string "으아-!\n"
	.string "생각했던 것보다 강하구나!$"

Route110_Text_16E84C:: @ 816E84C
	.string "봄이: {PLAYER}도\n"
	.string "포켓몬을 잘 키우고 있구나!\p"
	.string "음 그럼 이건\n"
	.string "내가 주는 선물이야!$"

Route110_Text_16E8B3:: @ 816E8B3
	.string "봄이: 그건 다우징머신!\p"
	.string "다우징머신을 쓰면\n"
	.string "눈에는 보이지 않아도 떨어져 있는\l"
	.string "도구에 반응하여\l"
	.string "소리로 알려준다고!\p"
	.string "그럼 {PLAYER}\n"
	.string "또 어디선가 보자!\p"
	.string "진 내가 이런 말하긴 그렇지만\n"
	.string "그때까지 좀 더 포켓몬\l"
	.string "키워두는 게 좋을걸!$"

Route110_Text_16E99A:: @ 816E99A
	.string "휘웅: {PLAYER}{K_I}구나\n"
	.string "이런 곳에 있었네\l"
	.string "어떻게 지냈어?\p"
	.string "포켓몬이 어떻게 성장했는지\n"
	.string "내가 확인해줄게$"

Route110_Text_16EA0F:: @ 816EA0F
	.string "흠...\n"
	.string "꽤 하네$"

Route110_Text_16EA2A:: @ 816EA2A
	.string "휘웅: {PLAYER} 어느새\n"
	.string "이렇게 포켓몬을 키웠구나...\p"
	.string "좋아!\n"
	.string "이걸 줄게$"

Route110_Text_16EA7B:: @ 816EA7B
	.string "휘웅: 그 녀석은 다우징머신\p"
	.string "쓰면 눈에는 보이지 않아도\n"
	.string "떨어져 있는 도구가 있으면\l"
	.string "반응하여 소리로 장소를 알려줘\p"
	.string "그럼 난 새로운\n"
	.string "포켓몬을 찾으러 갈게$"

Route110_Text_16EB22:: @ 816EB22
	.string "이 사이클링 로드를\n"
	.string "자전거로 달려나가면\l"
	.string "훨씬 기분 좋을 거야!$"

Route110_Text_16EB65:: @ 816EB65
	.string "어때? 바람에 휘날리는\n"
	.string "나의 검은 머리가!\p"
	.string "이걸 위해 머리를 기른 거라고!$"

Route110_Text_16EBC9:: @ 816EBC9
	.string "어! 그 자전거\n"
	.string "미스터 카제노에게 받았구나!\p"
	.string "딱 보면 알지\n"
	.string "왜냐면 너의 자전거에...\p"
	.string "카제노 카제노 카제노 카제노 카제노\n"
	.string "카제노 카제노 카제노 카제노\p"
	.string "카제노 카제노 카제노 카제노 카제노\n"
	.string "카제노 카제노 카제노 카제노\p"
	.string "카제노 카제노 카제노 카제노 카제노\n"
	.string "카제노 카제노 카제노 카제노\p"
	.string "카제노 카제노 카제노 카제노 카제노\n"
	.string "카제노 카제노 카제노 카제노\p"
	.string "카제노 카제노 카제노 카제노 카제노\n"
	.string "카제노 카제노 카제노 카제노\l"
	.string "...라고 쓰여 있거든!\p"
	.string "여기저기 타고 다니며\n"
	.string "선전해주면 좋을 거야!$"

Route110_Text_16EDC5:: @ 816EDC5
	.string "위와 아래 2가지 도로...\p"
	.string "사람과 포켓몬\n"
	.string "각각의 도로라고 생각하면\l"
	.string "이런 게 있는 것도 이해는 가네$"

Route110_Text_16EE30:: @ 816EE30
	.string "난 자전거가 없어서 말이야\n"
	.string "아래쪽 길을 느긋하게 걸어갈 거야$"

Route110_Text_16EE74:: @ 816EE74
	.string "여러 테크닉을 배우면\n"
	.string "더욱 자전거가 즐거워질 거야!\p"
	.string "테크닉을 안 쓰면\n"
	.string "지나갈 수 없는 장소도 있어!$"

Route110_Text_16EEF6:: @ 816EEF6
	.string "사이클링 로드를 타고\n"
	.string "보라시티로 갈지\p"
	.string "아래쪽 길로 가서\n"
	.string "포켓몬을 찾을지\l"
	.string "어느 쪽으로 할까?$"

Route110_Text_16EF65:: @ 816EF65
	.string "부딪힌 횟수\n"
	.string " ... {STR_VAR_1}!\p"
	.string "걸린 타임\n"
	.string " ... {STR_VAR_2}!$"

Route110_Text_16EF9F:: @ 816EF9F
	.string "브라보-!! 대단해!!\p"
	.string "넌 자전거를 진심으로\n"
	.string "사랑하고 있어! 영혼까지 감동했어!$"

Route110_Text_16F012:: @ 816F012
	.string "어느 정도의 테크닉을 가지고 있군!\p"
	.string "뭐 너무 스피드를 내서\n"
	.string "사고를 일으키지 않도록 하라고!$"

Route110_Text_16F069:: @ 816F069
	.string "아직 미숙한 부분도 있지만\n"
	.string "모처럼 이렇게 자전거를\l"
	.string "즐기고 있다는 그 마음을 잊지는 마$"

Route110_Text_16F0D0:: @ 816F0D0
	.string "이봐 이봐 뭔가\n"
	.string "아슬아슬한 운전을 하고 있네\l"
	.string "좀 더 연습하라고$"

Route110_Text_16F139:: @ 816F139
	.string "끄응... 끄으응...\p"
	.string "너에게 자전거는 어울리지 않는지도\n"
	.string "미스터 카제노에게 돌려주는 게 어때?$"

Route110_Text_16F1D0:: @ 816F1D0
	.string "이 사이클링 로드!\p"
	.string "보라시티에서 잿빛도시로 향해서\n"
	.string "마하자전거로 달려나가는\l"
	.string "레이서의 부딪힌 횟수와\l"
	.string "걸린 타임을 재고 있어!$"

Route110_Text_16F26A:: @ 816F26A
	.string "어떤 결과가 나오든 더 위를\n"
	.string "노리는 도전자가 기다리고 있어!$"

Route110_Text_16F2C4:: @ 816F2C4
	.string "이 사이클링 로드에서는\n"
	.string "마하자전거로 달려나가는\l"
	.string "레이서의 부딪힌 횟수와\l"
	.string "걸린 타임을 재고 있어!\p"
	.string "더트자전거라면 꺾이기 쉬우니까\n"
	.string "기록을 잴 수 없어!$"

Route110_Text_16F381:: @ 816F381
	.string "여기는 110번도로\n"
	.string "{0x7A} 잿빛도시$"

Route110_Text_16F39C:: @ 816F39C
	.string "“시사이드 사이클링 로드”$"

Route110_Text_16F3B1:: @ 816F3B1
	.string "“{EVIL_TEAM}단 등장!”\p"
	.string "...간판에 낙서가 있다$"

Route110_Text_16F3E9:: @ 816F3E9
	.string "여기는 110번도로\n"
	.string "{0x7B} 103번도로$"

Route110_Text_16F3FF:: @ 816F3FF
	.string "“시사이드 주차장”$"

Route110_Text_16F40F:: @ 816F40F
	.string "여기는 110번도로\n"
	.string "{0x79} 보라시티$"

Route110_Text_16F429:: @ 816F429
	.string "정보 나눔 게시판!!\p"
	.string "포켓몬은 잠들게 하거나 마비시키면\n"
	.string "상대의 자유를 뺏을 수 있습니다!\p"
	.string "이것은 포켓몬 승부의\n"
	.string "중요한 테크닉입니다!$"

Route110_Text_16F4AE:: @ 816F4AE
	.string "정보 나눔 게시판!!\p"
	.string "가방의 메뉴에서\n"
	.string "SELECT 버튼을 누르면\l"
	.string "도구의 순서를 바꿀 수 있습니다$"

Route110_Text_16F4F7:: @ 816F4F7
	.string "여기서부터 {0x7C}3걸음 {0x79}2걸음 가면\n"
	.string "그곳은 멋진 “미궁의 대저택”!$"

Route110_Text_16F53A:: @ 816F53A
	.string "지금까지의 최고 기록...\p"
	.string "부딪힌 횟수\n"
	.string " ... {STR_VAR_1}!\p"
	.string "걸린 타임\n"
	.string " ... {STR_VAR_2}!!$"

Route110_Text_16F57C:: @ 816F57C
	.string "지금까지의 최고 기록...\p"
	.string "아직 도전하지 않았는지\n"
	.string "아무것도 기록되어 있지 않다!$"

UnknownString_816F5D7: @ 816F5D7
	.string "식물들에게 매일 물을 주고 있는데\n"
	.string "꽃을 많이 피워!\p"
	.string "그리고 나무열매도 많이 열리지!\p"
	.string "나는 많이 있으니까\n"
	.string "하나 줄게!$"

UnknownString_816F657: @ 816F657
	.string "빨강포켓몬스넥을 만들려고 해!\n"
	.string "너도 한번 만들어 봐!$"

UnknownString_816F68A: @ 816F68A
	.string "가방의 나무열매 포켓이 다 찼네!\p"
	.string "그럼 다음에 줄게$"

UnknownString_816F6CF: @ 816F6CF
	.string "빨강포켓몬스넥을 만들기 위해서\n"
	.string "빨간 나무열매를 찾고 있어!$"
