RustboroCity_DevonCorp_1F_Text_1828EE:: @ 81828EE
	.string "어서 오세요!\n"
	.string "데봉 코포레이션입니다!\p"
	.string "여러분의 생활에 도움이 되는\n"
	.string "도구나 약을 만들고 있습니다!$"

RustboroCity_DevonCorp_1F_Text_18295E:: @ 818295E
	.string "얼빠진 연구원이\n"
	.string "화물을 빼앗겨서...$"

RustboroCity_DevonCorp_1F_Text_1829A4:: @ 81829A4
	.string "오! 러닝슈즈!\n"
	.string "우리 회사의 발명품이잖아!\p"
	.string "우리 회사 제품을\n"
	.string "실제로 사용하고 있는 사람을 보면\l"
	.string "굉장히 기뻐지지!$"

RustboroCity_DevonCorp_1F_Text_182A19:: @ 8182A19
	.string "확실히 그 화물은\n"
	.string "소중한 물건이지만...\p"
	.string "다른 사람이 훔쳐가도\n"
	.string "사용할 수 없을 거라 생각해\p"
	.string "내 추측으로는 그 도둑\n"
	.string "그리 똑똑해 보이진 않았거든$"

RustboroCity_DevonCorp_1F_Text_182AB3:: @ 8182AB3
	.string "듣자 하니 데봉화물은\n"
	.string "다시 돌아왔다더군$"

RustboroCity_DevonCorp_1F_Text_182AF0:: @ 8182AF0
	.string "어이쿠 관계자가 아니신 분은\n"
	.string "여기서부터\l"
	.string "앞으로 가실 수 없습니다!$"

RustboroCity_DevonCorp_1F_Text_182B2D:: @ 8182B2D
	.string "도둑에게 화물을 빼앗기다니\n"
	.string "왜 이렇게 얼빠진 거야...$"

RustboroCity_DevonCorp_1F_Text_182B5A:: @ 8182B5A
	.string "오!\n"
	.string "너라면 언제나 환영이지!$"
