RustboroCity_PokemonSchool_Text_184321:: @ 8184321
	.string "칠판에\n"
	.string "포켓몬이 배틀할 때 일어나는\l"
	.string "컨디션 변화에 대한 내용이 쓰여 있다$"

RustboroCity_PokemonSchool_Text_184368:: @ 8184368
	.string "어느 항목을 읽겠습니까?$"

RustboroCity_PokemonSchool_Text_184389:: @ 8184389
	.string "독에 중독되면\n"
	.string "체력이 줄어듭니다\p"
	.string "배틀 후에도 독 상태는\n"
	.string "그대로 남아서\l"
	.string "이동할 때 체력이 줍니다\p"
	.string "해독제로 치료해줍시다$"

RustboroCity_PokemonSchool_Text_184447:: @ 8184447
	.string "마비가 되면 스피드가 떨어지고\n"
	.string "가끔 기술을\l"
	.string "쓸 수 없게 됩니다\p"
	.string "배틀이 끝난 뒤라도\n"
	.string "마비된 상태는 그대로 남습니다\p"
	.string "마비치료제로 치료해줍시다$"

RustboroCity_PokemonSchool_Text_1844EC:: @ 81844EC
	.string "잠들어버리면\n"
	.string "그동안에는 공격할 수 없습니다\p"
	.string "스스로 일어나는 경우도 있지만\n"
	.string "잠든 채로 배틀이 끝나면\l"
	.string "계속 잠든 상태로 있습니다\p"
	.string "잠깨는약으로 깨워줍시다$"

RustboroCity_PokemonSchool_Text_1845A5:: @ 81845A5
	.string "화상을 입으면 공격력이\n"
	.string "떨어질 뿐만 아니라\l"
	.string "체력도 점점 줄어듭니다\p"
	.string "배틀이 끝나도\n"
	.string "화상을 입은 채로 있게 됩니다\p"
	.string "화상치료제로 치료해줍시다$"

RustboroCity_PokemonSchool_Text_184627:: @ 8184627
	.string "얼어버리면\n"
	.string "아무것도 할 수 없게 됩니다\p"
	.string "배틀이 끝나도\n"
	.string "얼어붙은 그대로 있게 됩니다\p"
	.string "얼음상태치료제로 녹여줍시다$"

RustboroCity_PokemonSchool_Text_1846A2:: @ 81846A2
	.string "공부를 하지 않은 학생에게는\n"
	.string "내 손톱의 때를\l"
	.string "달여서 마시게 하겠어!\p"
	.string "네가 공부하는지 안 하는지는\n"
	.string "이 도구를 능숙하게 다룰 수\l"
	.string "있는지를 보면 알 수 있겠지!$"

RustboroCity_PokemonSchool_Text_184737:: @ 8184737
	.string "포켓몬에게 선제공격손톱을\n"
	.string "지니게 하면 가끔 빨라져서\l"
	.string "선제공격을 할 때가 있어!\p"
	.string "이렇게 포켓몬에게\n"
	.string "지니게 하는 도구만 해도\l"
	.string "공부할 게 엄청 많다고!$"

RustboroCity_PokemonSchool_Text_18480E:: @ 818480E
	.string "지금 친구와\n"
	.string "포켓몬을 교환하고 있어!$"

RustboroCity_PokemonSchool_Text_18483C:: @ 818483C
	.string "갖고 싶었던 도토링을\n"
	.string "이제야 손에 넣을 수 있어!$"

RustboroCity_PokemonSchool_Text_184873:: @ 8184873
	.string "포켓몬도\n"
	.string "도구를 지닐 수 있지만\p"
	.string "상처약이나 해독제 같은\n"
	.string "사람이 만든 도구는\l"
	.string "사용법을 잘 모르는 것 같아$"

RustboroCity_PokemonSchool_Text_1848D8:: @ 81848D8
	.string "포켓몬의 기술로\n"
	.string "혼란이 될 때가 있잖아?\p"
	.string "혼란이 되면 가끔 착각해서\n"
	.string "자신을 공격해버려...\p"
	.string "하지만 한 번이라도\n"
	.string "배틀에서 멀어지면\l"
	.string "원래대로 돌아와!$"

RustboroCity_PokemonSchool_Text_184988:: @ 8184988
	.string "...포켓몬에게\n"
	.string "나무열매를 지니게 하면\l"
	.string "스스로 체력을 회복한다\p"
	.string "포켓몬이 지닐 수 있는 도구는\n"
	.string "그 밖에도 많다...\p"
	.string "노트에 제대로 기록하는 건\n"
	.string "참 힘들어....$"

RustboroCity_PokemonSchool_Text_184A17:: @ 8184A17
	.string "이 아이의 노트다...\p"
	.string "포켓몬은 몬스터볼로 잡아서\n"
	.string "동시에 6마리 지닐 수 있다\p"
	.string "그렇게 잡은 포켓몬을\n"
	.string "키워서 배틀시키는 사람을\l"
	.string "포켓몬 트레이너라고 한다\p"
	.string "각 지역의\n"
	.string "포켓몬체육관에 있는\l"
	.string "강한 트레이너를 이기는 것!\p"
	.string "그것이 포켓몬 트레이너의\n"
	.string "목표라고 할 수 있다$"
