RusturfTunnel_Text_194159:: @ 8194159
	.string "덤빌 거야?\n"
	.string "덤빌 테면 덤벼 봐!$"

RusturfTunnel_Text_194188:: @ 8194188
	.string "피코: 삐- 삐요-!$"

RusturfTunnel_Text_19419B:: @ 819419B
	.string "이런 젠장-!\p"
	.string "빼앗은 포켓몬은\n"
	.string "전혀 도움도 안 되지\p"
	.string "적당한 곳 찾아서\n"
	.string "도망 왔다고 생각했는데\l"
	.string "이 터널은 막다른 길이잖아!\p"
	.string "어이! 너!\n"
	.string "나랑 승부할 거지!?$"

RusturfTunnel_Text_194243:: @ 8194243
	.string "으으윽-!\n"
	.string "나의 악행도 여기까진가!$"

RusturfTunnel_Text_194274:: @ 8194274
	.string "이상하네...\p"
	.string "분명히 리더한테 들었을 때는\n"
	.string "뭔가 데봉에서 짐을\l"
	.string "훔쳐 오기만 하면 되는\l"
	.string "편한 일이었는데...\p"
	.string "쳇!\n"
	.string "이딴 거 그냥 돌려주고 만다!$"

RusturfTunnel_Text_19432A:: @ 819432A
	.string "피코! 무사해서 다행이다!$"

RusturfTunnel_Text_19434F:: @ 819434F
	.string "자넨 피코의\n"
	.string "생명의 은인이다!\p"
	.string "난 하기라고 하는데\n"
	.string "자넨 이름이 뭔가...?\p"
	.string "... ... ... ...\n"
	.string "... ... ... ...\p"
	.string "그래 {PLAYER}\e라고 하는구먼!\n"
	.string "정말 고맙구나!\p"
	.string "앞으로 뭐 곤란한 거 있으면\n"
	.string "사양 말고 나한테 말하게나!\p"
	.string "평상시에는 등화숲 가까이에 있는\n"
	.string "해변의 작은 집에 있으니깐!\p"
	.string "자 피코\n"
	.string "우린 그럼 집으로 돌아가자꾸나!\p"
	.string "피코: 삐요요--!!$"

RusturfTunnel_Text_1944C5:: @ 81944C5
	.string "...\p"
	.string "어째서 더 파지 못하는 거지...\n"
	.string "이 바위가 너무\l"
	.string "딱딱해서 그런 건가?\p"
	.string "이 앞에 있는 잔디마을이라는 곳에\n"
	.string "사랑하는 그녀가 있는데...\p"
	.string "금탄도시랑\n"
	.string "잔디마을 사이를 터널로 연결하면\l"
	.string "매일 그녀를 보러 갈 수 있어\p"
	.string "그런데 이건...\n"
	.string "난 도대체 어쩌면 좋은 거야...$"

RusturfTunnel_Text_1945B2:: @ 81945B2
	.string "금탄도시에서\n"
	.string "잔디마을로 가기 위해선\p"
	.string "무로마을에서 잿빛도시를\n"
	.string "거치고 보라시티를\l"
	.string "지나가지 않으면 안 돼...$"

RusturfTunnel_Text_19461D:: @ 819461D
	.string "오오! 고마워!\n"
	.string "답례라고 하긴 좀 뭐하지만\p"
	.string "감사의 증표로\n"
	.string "이 비전머신을 너한테 줄게!$"

RusturfTunnel_Text_194693:: @ 8194693
	.string "그 비전머신의 내용물은\n"
	.string "괴력이야!\p"
	.string "힘센 포켓몬에게 배우게 하면\n"
	.string "큰 바위도 움직일 수 있게 되지!$"

RusturfTunnel_Text_194706:: @ 8194706
	.string "미진씨!\n"
	.string "앞으로는 언제든지 볼 수 있어요!\p"
	.string "미진: 정말로...기뻐요\p"
	.string "자 저희 집에서\n"
	.string "푹 쉬었다 가세요$"

RusturfTunnel_Text_194766:: @ 8194766
	.string "이 바위 건너편에는...\n"
	.string "내 그이가 있어\p"
	.string "그이... 나를 만나려는 이유만으로\n"
	.string "이 터널을 파고 있는 건 아니야\p"
	.string "모두를 위해 손을 다쳐가면서도\n"
	.string "정말 힘내고 있어$"

RusturfTunnel_Text_194814:: @ 8194814
	.string "등산하는 사람은 등산가!\p"
	.string "하지만 왜 포켓몬이 등산하면\n"
	.string "등산포켓몬이라고\l"
	.string "부르지 않는 거지?$"

RusturfTunnel_Text_1948A2:: @ 81948A2
	.string "포켓몬...\n"
	.string "힘이 다했다...$"

RusturfTunnel_Text_1948C4:: @ 81948C4
	.string "이곳의 개발 공사는\n"
	.string "포켓몬을 지키기 위해\l"
	.string "중지되었다지?\p"
	.string "정말 훈훈한 이야기야$"
