RustboroCity_PokemonCenter_1F_Text_184B37:: @ 8184B37
	.string "내 포켓몬은 천진난만하고\n"
	.string "내 친구의 포켓몬은 명랑하지\p"
	.string "포켓몬에게도 성격이 있다니\n"
	.string "참 재미있군-!$"

RustboroCity_PokemonCenter_1F_Text_184BAB:: @ 8184BAB
	.string "포켓몬도 인간이랑 똑같이\n"
	.string "수컷이랑 암컷이 있는데\l"
	.string "성별에 따라 뭐가 다른지는\l"
	.string "아직 아무것도 밝혀지지 않았대$"

RustboroCity_PokemonCenter_1F_Text_184C19:: @ 8184C19
	.string "내 포켓몬은\n"
	.string "옆집 아저씨가 준 비전머신으로\l"
	.string "얇은 나무를 자를 수 있어!$"
