RustboroCity_House1_Text_184EBA:: @ 8184EBA
	.string "포켓몬에게 별명 지어주고 있어?\n"
	.string "난 멋있는 별명 지어주고 있어!\p"
	.string "그치만 내가 포켓몬을 부르면\n"
	.string "모두 다 킥킥거리고 웃어...\p"
	.string "그래도 괜찮다면 내 {STR_VAR_2}\h\n"
	.string "네 {STR_VAR_1}\f 교환하지 않을래?$"

RustboroCity_House1_Text_184F6B:: @ 8184F6B
	.string "에헷!!\n"
	.string "괜히 두근두근거린다$"

RustboroCity_House1_Text_184F8F:: @ 8184F8F
	.string "걔 {STR_VAR_1}\r 아니잖아\n"
	.string "쳇 실망이야$"

RustboroCity_House1_Text_184FC1:: @ 8184FC1
	.string "좋은 포켓몬이긴 하지만...$"

RustboroCity_House1_Text_184FDD:: @ 8184FDD
	.string "다른 사람의 포켓몬이\n"
	.string "어떤 별명으로\l"
	.string "불리는지 궁금하지 않아?$"

RustboroCity_House1_Text_185020:: @ 8185020
	.string "다양한 장소에\n"
	.string "다양한 포켓몬이 있고\l"
	.string "다양한 사람들도 있어\p"
	.string "그게 좋아서 나도\n"
	.string "다양한 곳으로 가는 거야!$"
