RustboroCity_House3_Text_185584:: @ 8185584
	.string "자신의 포켓몬에게\n"
	.string "딱 어울리는 별명을\l"
	.string "지어주는 게다!\p"
	.string "그게 바로 오리지널리티지!$"

RustboroCity_House3_Text_1855FA:: @ 81855FA
	.string "그렇다고 피카츄에게\n"
	.string "“페카츄”라는 별명을 붙이는 건\l"
	.string "조금...\p"
	.string "뭐... 이해하기 쉬운\n"
	.string "이름을 붙이는 것도\l"
	.string "별명의 중요한 점이긴 하지만$"

RustboroCity_House3_Text_18567D:: @ 818567D
	.string "페카츄: 페카!$"
