RustboroCity_DevonCorp_3F_Text_18320B:: @ 818320B
	.string "내가 데봉 코포레이션\n"
	.string "사장인 나발명이다!\p"
	.string "너에 대한 얘기는 아까 들었다!\p"
	.string "놀랍게도 우리 연구원을\n"
	.string "두 번이나 구해줬다면서?\p"
	.string "이렇게 대단한 사람을\n"
	.string "만나다니 감사할 따름이군\p"
	.string "네가 우리 회사의 화물을\n"
	.string "잿빛시티의\l"
	.string "조선소까지 전달한다고 들었다\p"
	.string "그런데 도중에\n"
	.string "무로마을에 들러줄 수 있겠나?\p"
	.string "무로마을에 있는\n"
	.string "성호라는 남자에게\l"
	.string "이 편지를 전해다오!$"

RustboroCity_DevonCorp_3F_Text_18337E:: @ 818337E
	.string "나발명: 물론 나는\n"
	.string "굉장-히 훌륭한 사장이니까!\p"
	.string "답례도 없이 부탁하는\n"
	.string "인색한 짓은 하지 않는다!\p"
	.string "그럼 이걸 너에게 주마!$"

RustboroCity_DevonCorp_3F_Text_183422:: @ 8183422
	.string "{PLAYER}\s\n"
	.string "포켓내비를 받았다!$"

RustboroCity_DevonCorp_3F_Text_183439:: @ 8183439
	.string "나발명: 그건...\p"
	.string "포켓몬 내비게이터!\n"
	.string "줄여서 포켓내비라고도 하는데\p"
	.string "모험을 떠나는 트레이너의\n"
	.string "필수품이란다!\p"
	.string "그걸 사용하면 언제든지\n"
	.string "호연지방의 지도를 볼 수 있다!\p"
	.string "무로마을과 잿빛도시의\n"
	.string "위치도 간편히 확인할 수 있지!$"

RustboroCity_DevonCorp_3F_Text_18351E:: @ 818351E
	.string "나발명: 그러면\n"
	.string "여러모로 잘 부탁한다!$"

RustboroCity_DevonCorp_3F_Text_18353E:: @ 818353E
	.string "나발명: 편지는 무사히 전달했나?\n"
	.string "정말로 고맙구다!\p"
	.string "이건 내 감사의 표시다\n"
	.string "네게 분명 도움이 될 거다$"

RustboroCity_DevonCorp_3F_Text_1835B3:: @ 81835B3
	.string "나발명: 학습장치를 지닌 포켓몬은\n"
	.string "다른 배틀한 포켓몬의 경험을\l"
	.string "전달받게 된다!\p"
	.string "배틀하지 않아도 경험치를\n"
	.string "전달받을 수 있다는 건\p"
	.string "약한 포켓몬도 키우기\n"
	.string "쉽게 해준다는 뜻이지!$"

RustboroCity_DevonCorp_3F_Text_18368D:: @ 818368D
	.string "나발명: 나는 젊었을 때부터\n"
	.string "일만 해 왔기 때문에\l"
	.string "잘 모르네만...\p"
	.string "요즘 젊은 사람들은\n"
	.string "트레이너가 되어\l"
	.string "포켓몬리그에 나가는 게 목표인가?$"

RustboroCity_DevonCorp_3F_Text_18374C:: @ 818374C
	.string "여기가 데봉 코포레이션 3층\n"
	.string "사장실입니다!\p"
	.string "그건 그렇고 당신에겐\n"
	.string "진심으로 감사드립니다\p"
	.string "...그런데 되찾아주신\n"
	.string "화물 말인데요\p"
	.string "혹시 잿빛도시의 조선소까지\n"
	.string "운반해주실 수 있을까요?\p"
	.string "그 도둑들에게 다시 빼앗기는 건\n"
	.string "정말 싫을 것 같아서...\p"
	.string "어... 헤헤헤\p"
	.string "...그럼 사장님께 당신에 대해\n"
	.string "말씀드리고 올 테니\l"
	.string "잠깐 기다려주세요$"

RustboroCity_DevonCorp_3F_Text_183903:: @ 8183903
	.string "사장님께서 꼭 좀\n"
	.string "이야기를 나누고 싶어하십니다\p"
	.string "저를 따라와 주세요$"

RustboroCity_DevonCorp_3F_Text_18394A:: @ 818394A
	.string "자 이쪽으로$"

RustboroCity_DevonCorp_3F_Text_18395C:: @ 818395C
	.string "잿빛도시의 조선소에 들르면\n"
	.string "해양관장을 찾아가 보세요!$"

RustboroCity_DevonCorp_3F_Text_1839A3:: @ 81839A3
	.string "최근에 데봉이 발명하여\n"
	.string "트레이너들에게 팔리는 인기상품!\p"
	.string "그것이 바로 리피드볼과\n"
	.string "타이마볼입니다!$"

RustboroCity_DevonCorp_3F_Text_183A04:: @ 8183A04
	.string "사장이 수집한\n"
	.string "희귀한 돌이 장식되어 있다!$"
