RustboroCity_DevonCorp_2F_Text_182B81:: @ 8182B81
	.string "지금 포켓몬과\n"
	.string "대화할 수 있게 해주는 도구를\l"
	.string "개발하고 있는데...\p"
	.string "이게 좀처럼 쉽지가 않네요$"

RustboroCity_DevonCorp_2F_Text_182BD8:: @ 8182BD8
	.string "지금 신형 몬스터볼을\n"
	.string "개발하고 있는데...\p"
	.string "이게 좀처럼 쉽지가 않네요$"

RustboroCity_DevonCorp_2F_Text_182C25:: @ 8182C25
	.string "드디어 신형 몬스터볼\n"
	.string "개발에 성공했어요!\p"
	.string "예전에 잡았던 포켓몬에게\n"
	.string "이 리피드볼을 사용하면\l"
	.string "더 쉽게 잡을 수 있어요!\p"
	.string "그리고 이 타이마볼은 포켓몬과의\n"
	.string "배틀 시간이 길면 길어질수록\l"
	.string "더 쉽게 잡을 수 있어요!\p"
	.string "두 개 모두 저희 회사가\n"
	.string "자랑하는 제품이니\l"
	.string "많이 사용해 주세요!$"

RustboroCity_DevonCorp_2F_Text_182D2A:: @ 8182D2A
	.string "제가 바로\n"
	.string "그 포켓내비를 만든 사람이에요!\p"
	.string "이야- 그런 엄청난 걸\n"
	.string "개발하게 되다니\l"
	.string "개발자인 제가 더 영광이죠!$"

RustboroCity_DevonCorp_2F_Text_182D7E:: @ 8182D7E
	.string "오오! 혹시 그건 포켓내비!\p"
	.string "포켓몬의 기분을\n"
	.string "알고 싶다는 사장님의 아이디어를\l"
	.string "실현시킨 물건이에요!\p"
	.string "좀 더 자세히 설명해 드릴까요?\p"
	.string "...아니지\n"
	.string "사용하시다 보면\l"
	.string "저절로 알게 되실 거예요!\p"
	.string "그러니\n"
	.string "포켓내비를 많이 사용해 주세요!$"

RustboroCity_DevonCorp_2F_Text_182E6B:: @ 8182E6B
	.string "현재 포켓몬이 꾸고 있는\n"
	.string "꿈을 볼 수 있게 해주는 도구를\l"
	.string "개발하고 있습니다만...\p"
	.string "아직까진 진척이 없네요$"

RustboroCity_DevonCorp_2F_Text_182ED5:: @ 8182ED5
	.string "포켓몬의 화석을 재생시키는\n"
	.string "장치를 개발하고 있는데...\p"
	.string "그럭저럭 잘 되고 있어요!$"

RustboroCity_DevonCorp_2F_Text_182F35:: @ 8182F35
	.string "당신이 갖고 있는 그건 설마\n"
	.string "포켓몬의 화석!?\p"
	.string "괜찮으시면 제가 만든\n"
	.string "화석 재생 머신으로\l"
	.string "화석을 복원시켜도 될까요?$"

RustboroCity_DevonCorp_2F_Text_182FD7:: @ 8182FD7
	.string "아 그렇군요...\p"
	.string "데봉의 기술력은\n"
	.string "정말 대단한데 말이죠$"

RustboroCity_DevonCorp_2F_Text_183023:: @ 8183023
	.string "알겠습니다!\n"
	.string "그럼 바로...\p"
	.string "{PLAYER}{K_EUNNEUN} 데봉의 연구원에게\n"
	.string "{STR_VAR_1}{K_EULREUL} 건넸다$"

RustboroCity_DevonCorp_2F_Text_183072:: @ 8183072
	.string "제가 만든\n"
	.string "화석 재생 머신은 굉장하지만\l"
	.string "시간이 조금 걸린답니다...\p"
	.string "잠깐 다른 곳을\n"
	.string "견학하시는 건 어떨까요?$"

RustboroCity_DevonCorp_2F_Text_183124:: @ 8183124
	.string "오래 기다리셨습니다!\n"
	.string "화석이 되살아났습니다!\p"
	.string "복원된 화석은 고대의 포켓몬\n"
	.string "{STR_VAR_2}입니다!$"

RustboroCity_DevonCorp_2F_Text_18319E:: @ 818319E
	.string "{PLAYER}{K_EUNNEUN} 데봉의 연구원에게\n"
	.string "{STR_VAR_2}{K_EULREUL} 받았다!$"

RustboroCity_DevonCorp_2F_Text_1831C8:: @ 81831C8
	.string "앗! 포켓몬이 가득하군요\n"
	.string "포켓몬을 드릴 수 없겠네요$"
