RustboroCity_Text_16689D:: @ 816689D
	.string "데봉 코포레이션...\n"
	.string "다들 데봉이라고 줄여서 부르지\p"
	.string "그 회사에서는 여러 가지\n"
	.string "편리한 물건을 만들고 있어!$"

RustboroCity_Text_16690C:: @ 816690C
	.string "응? 수상한 남자?\p"
	.string "그러고 보니 인상이 험한 남자가\n"
	.string "저기 모퉁이를 돌아갔어$"

RustboroCity_Text_16696D:: @ 816696D
	.string "포켓몬체육관에 도전했니?\p"
	.string "그 반짝반짝 빛나는\n"
	.string "체육관 배지를 지니면\p"
	.string "트레이너로서의 자각이\n"
	.string "싹트게 된다고!$"

RustboroCity_Text_1669FE:: @ 81669FE
	.string "앗! 금탄의 체육관 배지!\p"
	.string "여러 가지 배지 중에\n"
	.string "금탄도시 체육관 배지가 제일 멋지지!$"

RustboroCity_Text_166A67:: @ 8166A67
	.string "어라? 넌 누구니?\n"
	.string "이 근처에서 본 적 없는 얼굴이군\p"
	.string "트레이너스쿨의 전학생?$"

RustboroCity_Text_166AE0:: @ 8166AE0
	.string "체육관 관장에게 도전했는데...\p"
	.string "내 불꽃타입 포켓몬으론\n"
	.string "이기기 조금 어려울 것 같아...\p"
	.string "왜냐면 불꽃타입은\n"
	.string "바위타입에게 상성이 나쁘잖아...$"

RustboroCity_Text_166B86:: @ 8166B86
	.string "해변의 작은 집에 사는\n"
	.string "선원 하기노인\l"
	.string "가끔 터널로 산책을 가$"

RustboroCity_Text_166BEF:: @ 8166BEF
	.string "해변의 작은 집에 사는\n"
	.string "선원 하기노인\l"
	.string "피코를 위해 잿빛도시에 가서\l"
	.string "쇼핑을 한대\p"
	.string "그 할아버지\n"
	.string "정말 피코를 좋아하는구나!$"

RustboroCity_Text_166C98:: @ 8166C98
	.string "너도 포켓몬을 데리고 있구나\p"
	.string "나도 어른이 되면\n"
	.string "포켓몬과 어디론가 갈 거야!$"

RustboroCity_Text_166CFA:: @ 8166CFA
	.string "포켓몬트레이너스쿨이라!\p"
	.string "여기에 입학하면\n"
	.string "희귀한 포켓몬도 쉽게\l"
	.string "잡을 수 있게 될까?$"

RustboroCity_Text_166D59:: @ 8166D59
	.string "포켓몬은 배틀의 경험을\n"
	.string "쌓아가면 생김새가\l"
	.string "변하기도 한다고!$"

RustboroCity_Text_166DB0:: @ 8166DB0
	.string "포켓몬의 생김새가 바뀐다고?\n"
	.string "갑자기 바뀌면 놀라겠는데!$"

RustboroCity_Text_166DEE:: @ 8166DEE
	.string "다른 사람과 교환한 포켓몬은\n"
	.string "성장이 빨라!\p"
	.string "...하지만 체육관 배지를\n"
	.string "지니고 있지 않으면\l"
	.string "말을 듣지 않아$"

RustboroCity_Text_166E65:: @ 8166E65
	.string "비켜-! 비켜비켜-!!$"

RustboroCity_Text_166E7E:: @ 8166E7E
	.string "거기 서-!\p"
	.string "그 화물을 돌려줘어어어-!!$"

RustboroCity_Text_166EA5:: @ 8166EA5
	.string "아아 당신은!\p"
	.string "등화숲에서 구해주신\n"
	.string "멋진 트레이너 아니신가요!\p"
	.string "부탁합니다!\p"
	.string "{EVIL_TEAM}단에게 빼앗긴\n"
	.string "데봉화물을 되찾아 주십시오!\p"
	.string "그게 없으면....\n"
	.string "전 매우 곤란해집니다$"

RustboroCity_Text_166F6B:: @ 8166F6B
	.string "방금 전 수상한 녀석은\n"
	.string "건너편의 터널 쪽으로\l"
	.string "도망갔을 거라 생각합니다$"

RustboroCity_Text_166FB4:: @ 8166FB4
	.string "아아! 어떻게 됐나요\n"
	.string "데봉화물은...?\p"
	.string "그런가요!\n"
	.string "되찾아 주신 건가요!\p"
	.string "당신은 정말\n"
	.string "대단한 트레이너군요!\p"
	.string "...그래요! 답례로\n"
	.string "또다른 수퍼볼을 드리죠!$"

RustboroCity_Text_16704C:: @ 816704C
	.string "가방이 가득 찼다면\n"
	.string "이 수퍼볼은 드릴 수 없겠네요$"

RustboroCity_Text_16707F:: @ 816707F
	.string "저기! 저기!\n"
	.string "날 따라와 주세요!$"

RustboroCity_Text_1670A7:: @ 81670A7
	.string "봄이: 아 {PLAYER}!\n"
	.string "포켓몬 도감은 많이 채웠어?\l"
	.string "난 꽤 괜찮은 느낌이야!\p"
	.string "등화숲에서\n"
	.string "몬스터볼이 다 떨어질 정도로\l"
	.string "포켓몬을 잡았거든!$"

RustboroCity_Text_16713C:: @ 816713C
	.string "봄이: 그러고 보니 등화숲에서\n"
	.string "하기노인하고 스쳐 지나갔는데\p"
	.string "아마도...\n"
	.string "해변의 작은 집으로\l"
	.string "되돌아가는 중이 아니었을까!\p"
	.string "{PLAYER}{K_EUNNEUN} 이사 와서\n"
	.string "잘 모를 테지만\p"
	.string "하기노인은 예전에\n"
	.string "대단한 선원이었어!$"

RustboroCity_Text_167213:: @ 8167213
	.string "휘웅: {PLAYER}\n"
	.string "포켓몬 도감은 어때?\l"
	.string "페이지 많이 채웠어?\p"
	.string "난 완전 끝내준다!\p"
	.string "등화숲에서\n"
	.string "포켓몬을 하도 많이 잡았더니\l"
	.string "몬스터볼이 다 떨어졌어!$"

RustboroCity_Text_1672B8:: @ 81672B8
	.string "휘웅: 그러고 보니 등화숲에서\n"
	.string "하기노인하고 스쳐 지나갔어\p"
	.string "분명 해변의 작은 집으로\n"
	.string "돌아가는 길이었을 거야\p"
	.string "넌 아마 모르겠지만\n"
	.string "그 사람 언제나\l"
	.string "포켓몬과 함께 다니거든$"
	// ユウキ『そういえば トウカのもりでｎ
	// ハギろうじんと すれちがったよｐ
	// きっと はまべの こやにｎ
	// かえる ところ だなｐ
	// おまえ しらない だろうけどｎ
	// あの ひと いつもｌ
	// ポケモンと いっしょ なんだ

RustboroCity_Text_167374:: @ 8167374
	.string "“편리한 터널 곧 완성!”\p"
	.string "...이라고 간판에 적혀 있지만\n"
	.string "그 위에 빨간 페인트로\l"
	.string "크게 X 표시가 그려져 있다$"

RustboroCity_Text_1673FA:: @ 81673FA
	.string "“데봉 코포레이션”\p"
	.string "여러분의 생활을 위해\n"
	.string "무엇이든 만들고 있습니다!$"

RustboroCity_Text_167439:: @ 8167439
	.string "금탄도시 포켓몬체육관\n"
	.string "관장 원규\l"
	.string "바위를 보면 가슴이 뛰는 우등생!$"

RustboroCity_Text_167485: @ 8167485
	.string "“데봉 코포레이션 분실”\p"
	.string "관계자 외 출입 금지\n"
	.string "양해 바랍니다!$"

RustboroCity_Text_1674DD:: @ 81674DD
	.string "여기는 금탄도시\p"
	.string "자연과 과학의 융합을\n"
	.string "추구하는 마을$"

RustboroCity_Text_167525:: @ 8167525
	.string "“포켓몬트레이너스쿨”\p"
	.string "포켓몬에 관한 것이라면\n"
	.string "무엇이든 가르쳐 드립니다!$"

RustboroCity_Text_167568:: @ 8167568
	.string "“풀베기아저씨의 집”$"
