RustboroCity_Mart_Text_184C76:: @ 8184C76
	.string "등화숲에서 버섯꼬가\n"
	.string "튀어나왔을 때를 대비해서\p"
	.string "마비치료제와 해독제를\n"
	.string "사둘 거야!$"

RustboroCity_Mart_Text_184CD8:: @ 8184CD8
	.string "포켓몬이 진화해서\n"
	.string "체력이 늘어났으니\p"
	.string "상처약 말고\n"
	.string "좋은상처약을 사줄까?$"

RustboroCity_Mart_Text_184D43:: @ 8184D43
	.string "동굴에서 길을\n"
	.string "잃었을 때를 대비해서\l"
	.string "동굴탈출로프가 갖고 싶어!\p"
	.string "이것만 쓰면 눈 깜짝할 사이에\n"
	.string "입구까지 돌아갈 수 있거든!$"
