RustboroCity_Gym_Text_183A4B:: @ 8183A4B
	.string "잘 있었나!!\p"
	.string "갑작스럽지만 너!\n"
	.string "챔피언을 목표로 해보지 않을래?\p"
	.string "난 트레이너는 아니지만\n"
	.string "이기기 위한 확실한\l"
	.string "어드바이스를 할 수 있어!\p"
	.string "좋아 정했다! 같이\n"
	.string "포켓몬 챔피언을 목표로 하자\p"
	.string "트레이너의 목적이라고 하면\n"
	.string "체육관 배지를 모으는 거잖아\l"
	.string "그렇지만 체육관 관장은 강하다!\p"
	.string "그래서 내가 나올 차례라는 거지!\p"
	.string "너에게 확실한\n"
	.string "어드바이스를 해줄게!\p"
	.string "여기 체육관 관장 원규는\n"
	.string "바위타입의 포켓몬 사용자!\p"
	.string "바위타입은 단단하지만\n"
	.string "물타입이나 풀타입의\l"
	.string "공격에는 약해!\p"
	.string "체육관 관장을 이기면\n"
	.string "다시 나에게 말 걸어줘!\p"
	.string "그럼 힘내-!!$"

RustboroCity_Gym_Text_183C90:: @ 8183C90
	.string "우오오! 멋진 승리다!!\n"
	.string "내 응원이 좋았던 걸까!?\p"
	.string "좋아! 너의\n"
	.string "트레이너카드를 봐봐!\p"
	.string "아까 손에 넣은 스톤배지가\n"
	.string "잘 기록되어 있지\p"
	.string "즉...\p"
	.string "너는 챔피언으로 향한 계단을\n"
	.string "하나 올라간 거야!\p"
	.string "늠름해-!!$"

RustboroCity_Gym_Text_183D99:: @ 8183D99
	.string "체육관 소속 트레이너를\n"
	.string "우습게 보지 말라고!\l"
	.string "실력의 차이를 보여주겠어!$"

RustboroCity_Gym_Text_183DDD:: @ 8183DDD
	.string "실력이 너무 달라...!$"

RustboroCity_Gym_Text_183DF9:: @ 8183DF9
	.string "바위타입의 진정한 무서움은\n"
	.string "이 정도가 아니라고!$"

RustboroCity_Gym_Text_183E38:: @ 8183E38
	.string "날 이길 실력이 없으면\n"
	.string "원규님에겐 절대로 이길 수 없어!$"

RustboroCity_Gym_Text_183E78:: @ 8183E78
	.string "엄청난 실력이다!$"

RustboroCity_Gym_Text_183E98:: @ 8183E98
	.string "원규님은 나보다\n"
	.string "몇 배는 더 강해!\p"
	.string "방심하지 않는 게 좋을 거야!$"

RustboroCity_Gym_Text_183EE5:: @ 8183EE5
	.string "어머 안녕하세요\p"
	.string "전 금탄도시 포켓몬체육관\n"
	.string "체육관 관장 원규라고 합니다\p"
	.string "트레이너스쿨에서 배운 내용을\n"
	.string "승부에 살리고 싶어서\l"
	.string "체육관 관장이 되었습니다\p"
	.string "어떤 포켓몬으로\n"
	.string "어떻게 배틀할지\l"
	.string "저에게 알려주시겠어요?$"

RustboroCity_Gym_Text_183FC4:: @ 8183FC4
	.string "전 져버린 거군요...\p"
	.string "더 많은 것을\n"
	.string "공부할 필요가 있는 것 같아요...\p"
	.string "잘 알았습니다\p"
	.string "포켓몬리그의 규칙으로\n"
	.string "체육관 관장을 이긴 트레이너에게\l"
	.string "이것을 드리게 되어 있습니다\p"
	.string "어서 포켓몬리그 공인\n"
	.string "스톤배지를 받아 주세요$"

RustboroCity_Gym_Text_1840AB:: @ 81840AB
	.string "{PLAYER}{K_EUNNEUN} 원규에게\n"
	.string "스톤배지를 받았다!$"

RustboroCity_Gym_Text_1840D5:: @ 81840D5
	.string "스톤배지를 가지고 있으면\n"
	.string "지닌 포켓몬의\l"
	.string "공격력이 올라가게 됩니다\p"
	.string "또한 비전기술인 풀베기를\n"
	.string "사용할 수 있게 됩니다\p"
	.string "마지막으로...\n"
	.string "이것도 받아 주세요$"

RustboroCity_Gym_Text_184170:: @ 8184170
	.string "기술머신39의 안에는\n"
	.string "암석봉인이 들어 있습니다\p"
	.string "암석봉인은 상대를 향해\n"
	.string "바위를 떨어뜨려 데미지를 주고\p"
	.string "거기에 상대의 스피드까지\n"
	.string "떨어뜨리는 기술입니다\p"
	.string "기술머신을 사용하면 포켓몬에게\n"
	.string "한순간에\l"
	.string "기술을 배우게 할 수 있습니다\p"
	.string "다만 한 번 쓰면 없어져버리니\n"
	.string "쓸 때는 잘 생각하도록 하세요$"

RustboroCity_Gym_Text_184252:: @ 8184252
	.string "그 정도로 강하다면\n"
	.string "다른 포켓몬체육관에도\l"
	.string "도전하는 건 어떠세요?\p"
	.string "많은 트레이너와 승부하는 것으로\n"
	.string "여러 가지를 배울 수 있을 거예요$"

RustboroCity_Gym_Text_1842CC:: @ 81842CC
	.string "금탄도시 포켓몬체육관$"

RustboroCity_Gym_Text_1842E6:: @ 81842E6
	.string "금탄도시 포켓몬체육관\p"
	.string "원규 인정 트레이너!\n"
	.string "{PLAYER}$"
