SeafloorCavern_Room3_Text_1975DC:: @ 81975DC //JP: 17454C
	.string "오호호!\p"
	.string "잠수정도 없는데\n"
	.string "잘도 여기까지 쫓아왔네!\l"
	.string "대단한 꼬맹이네!\p"
	.string "하지만 말야...\n"
	.string "방해받는 건 싫단 말이지\p"
	.string "날씨 연구소에서의\n"
	.string "빚도 갚아주고 싶고...\p"
	.string "조금 아픈 기억이 될 테니까\n"
	.string "각오하라고-!!$"

SeafloorCavern_Room3_Text_1976F3:: @ 81976F3
	.string "오호호!\p"
	.string "아파!$"

SeafloorCavern_Room3_Text_197704:: @ 8197704
	.string "오호호!\p"
	.string "너 그렇게 강한데\n"
	.string "{EVIL_TEAM}단의 동료가 아니라서\n"
	.string "무척 유감이야\p"
	.string "리더가 실현해줄\n"
	.string "멋진 세계를\l"
	.string "같이 즐길 수 있는데...$"
