SlateportCity_ContestLobby_Text_17C937:: @ 817C937
	.string "승부에서든 콘테스트에서든\n"
	.string "최고로 활약하는 포켓몬을\l"
	.string "키우고 싶어...\p"
	.string "배우게 할 기술 때문에 고민이야!$"

SlateportCity_ContestLobby_Text_17C9D5:: @ 817C9D5
	.string "당신의 친구는\n"
	.string "나무열매 가지고 있어?\p"
	.string "저기에 있는 나무열매블렌더로\n"
	.string "친구와 함께\l"
	.string "포켓몬스넥을 만들 수 있어!\l"
	.string "정말 재밌어!$"

SlateportCity_ContestLobby_Text_17CA67:: @ 817CA67
	.string "두 개 있으니까\n"
	.string "이거 하나 줄게!$"

SlateportCity_ContestLobby_Text_17CA88:: @ 817CA88
	.string "포켓몬스넥을 만들고\n"
	.string "거기에 넣으면 돼!\p"
	.string "그리고 포켓몬스넥을 만들 때는\n"
	.string "모두가 다른 나무열매로\l"
	.string "만들지 않으면 안 돼!$"

SlateportCity_ContestLobby_Text_17CAEC:: @ 817CAEC
	.string "콘테스트에서 우승하면\p"
	.string "벽에 우승한 포켓몬의 초상화를\n"
	.string "이름과 함께 장식하게 돼!$"
