SlateportCity_SternsShipyard_2F_Text_17C7A2:: @ 817C7A2
	.string "거대한 배를 만든다는 건\n"
	.string "탈것을 만드는 것보다는\l"
	.string "큰 건물을 짓는 거랑 비슷해$"

SlateportCity_SternsShipyard_2F_Text_17C80C:: @ 817C80C
	.string "쇠로 만들어진 무거운 배가\n"
	.string "물 위에 뜨는 게 신기하지?\p"
	.string "그건 “부력”이라는 원리를\n"
	.string "응용하고 있기 때문이야$"

UnknownString_817C882: @ 817C882
	.string "잿빛도시와 황금마을 사이에는\n"
	.string "물살이 정말 강해서\p"
	.string "일반적인 배로는\n"
	.string "건너가기 힘들지\p"
	.string "건너가기 위해서는\n"
	.string "강한 추진력이 필요해...$"
