SlateportCity_OceanicMuseum_1F_Text_17E18D:: @ 817E18D
	.string "바다의 과학박물관에\n"
	.string "어서 오세요 환영합니다!\p"
	.string "입장료는 50원입니다\n"
	.string "견학하시겠습니까?$"

SlateportCity_OceanicMuseum_1F_Text_17E1DE:: @ 817E1DE
	.string "여유롭게 구경하세요!$"

SlateportCity_OceanicMuseum_1F_Text_17E1F5:: @ 817E1F5
	.string "...어머 돈이 부족하네요$"

SlateportCity_OceanicMuseum_1F_Text_17E22D:: @ 817E22D
	.string "...어머 아까 그 단체의\n"
	.string "일행이신가요?\p"
	.string "고객님만 뒤처지셨다니\n"
	.string "어쩔 수 없네요\l"
	.string "빨리 들어가세요!$"

UnknownString_817E2A0: @ 817E2A0
	.string "또 와주세요$"

SlateportCity_OceanicMuseum_1F_Text_17E2BB:: @ 817E2BB
	.string "모두를 위해서\n"
	.string "우리 {EVIL_TEAM}단이 있는 거야!$"

SlateportCity_OceanicMuseum_1F_Text_17E2E3:: @ 817E2E3
	.string "현장에서 집합하라는 얘길 듣고\n"
	.string "여기로 모인 건 좋은데...\p"
	.string "제일 중요한 리더가\n"
	.string "아직 오시지 않았어$"

SlateportCity_OceanicMuseum_1F_Text_17E338:: @ 817E338
	.string "여기에 놓여 있는 것들\n"
	.string "모두 훔쳐 가면 벌이 좀 되려나?$"

SlateportCity_OceanicMuseum_1F_Text_17E36F:: @ 817E36F
	.string "이 지식을 이용해서\n"
	.string "나쁜 짓이나 해볼까...$"

SlateportCity_OceanicMuseum_1F_Text_17E3A9:: @ 817E3A9
	.string "동료가 금탄도시에서\n"
	.string "실수만 안 했으면\l"
	.string "여기까지 올 일도 없었을 텐데!$"

SlateportCity_OceanicMuseum_1F_Text_17E3ED:: @ 817E3ED
	.string "아까 50원이 없어서 접수처에서\n"
	.string "엄청 시간 잡아먹었어...$"

SlateportCity_OceanicMuseum_1F_Text_17E434:: @ 817E434
	.string "바다에 대해 공부해서\n"
	.string "포켓몬 승부 때 써먹을 거야$"

SlateportCity_OceanicMuseum_1F_Text_17E477:: @ 817E477
	.string "저요!\n"
	.string "바다를 보면 흥분돼요!\p"
	.string "이런 저한테 있어서\n"
	.string "해양관장은 동경하는 사람\l"
	.string "넘버1에 속하는 사람이에요!$"

SlateportCity_OceanicMuseum_1F_Text_17E4D7:: @ 817E4D7
	.string "바다는 끝없이 넓고\n"
	.string "끝없이 깊어...\p"
	.string "분명히 우리가 모르는 포켓몬도\n"
	.string "많이 있을 거야$"

SlateportCity_OceanicMuseum_1F_Text_17E540:: @ 817E540
	.string "나 바다의 포켓몬 가지고 싶어\p"
	.string "왜냐면 서늘한 느낌이 들어서\n"
	.string "껴안으면 기분 좋을 거 같거든$"

SlateportCity_OceanicMuseum_1F_Text_17E582:: @ 817E582
	.string "우악-!!\n"
	.string "왜 네가 여기 있는 거야!?\p"
	.string "나?\n"
	.string "난 너한테 손도 발도 못 쓰고 당한\l"
	.string "{EVIL_TEAM}단이야\p"
	.string "이거 줄 테니까 봐줘!$"

SlateportCity_OceanicMuseum_1F_Text_17E606:: @ 817E606
	.string "칫! 너 때문에\n"
	.string "작전에 실패해서 대신\l"
	.string "뭐라도 훔쳐 갈 생각이었는데...\p"
	.string "젠장! 두고 보자!$"

SlateportCity_OceanicMuseum_1F_Text_17E695:: @ 817E695
	.string "칫! 가방이 가득 차면\n"
	.string "주고 도망가 버릴 수 없잖아$"

SlateportCity_OceanicMuseum_1F_Text_17E6C9:: @ 817E6C9
	.string "유리 안에서 파란 물이\n"
	.string "빙글빙글 돌고 있다!\p"
	.string "“이것은 바람의 힘을 이용해\n"
	.string "  인공적으로 바다회오리를\l"
	.string "  일으키는 실험입니다”$"

SlateportCity_OceanicMuseum_1F_Text_17E741:: @ 817E741
	.string "유리 안에서 빨간 공이 떠올랐다\n"
	.string "가라앉기를 반복하고 있다!\p"
	.string "“이것은 공의 부력을 이용한\n"
	.string "  폭포오르기의 원리 실험입니다”$"

SlateportCity_OceanicMuseum_1F_Text_17E7C4:: @ 817E7C4
	.string "바다 밑바닥 흙의 표본이다!\p"
	.string "“바다 밑바닥에는 오랜 세월에 걸쳐\n"
	.string "  생물의 사체가 쌓여\l"
	.string "  지층이 형성되어 있습니다”\p"
	.string "“이 지층을 분석함으로써\n"
	.string "  먼 옛날에 대해\l"
	.string "  알 수 있는 것입니다”$"

SlateportCity_OceanicMuseum_1F_Text_17E892:: @ 817E892
	.string "바닷가 모래의 표본이다!\p"
	.string "“산에서 강을 타고 떠내려온 돌은\n"
	.string "  물속에서 구르는 동안\l"
	.string "  부서지고 깎여갑니다”\p"
	.string "“그 돌들이 작은 알갱이가 되어\n"
	.string "  바닷가의 모래가 되는 것입니다”$"

SlateportCity_OceanicMuseum_1F_Text_17E944:: @ 817E944
	.string "“바다 미니 정보 1\n"
	.string "  왜 바닷물은 파란색인가요?”\p"
	.string "“빛에는 다양한 색이 있고\n"
	.string "  대부분의 빛은 물에 들어가면\l"
	.string "  그 색 자체를 잃게 됩니다”\p"
	.string "“그렇지만 파란빛만은\n"
	.string "  그 색 그대로 유지되기 때문에\l"
	.string "  바다는 파랗게 보이는 것입니다”$"

SlateportCity_OceanicMuseum_1F_Text_17EA19:: @ 817EA19
	.string "“바다 미니 정보 2\n"
	.string "  어째서 바닷물은 짠가요?”\p"
	.string "“해수에는 바위에서 나오는\p"
	.string "  소금의 근본인\n"
	.string "  나트륨 이온과 염소 이온이라는\l"
	.string "  물질이 많은 양 포함되어 있습니다\p"
	.string "  그래서 핥으면 짠 것입니다”$"

SlateportCity_OceanicMuseum_1F_Text_17EB0D:: @ 817EB0D
	.string "“바다 미니 정보 3\n"
	.string "  바다와 육지 중\l"
	.string "  어느 쪽이 더 넓은가요?”\p"
	.string "“이 별에서의 비율은\n"
	.string "  대략 바다가 70퍼센트고\l"
	.string "  육지가 30퍼센트 정도입니다\p"
	.string "  육지에 비해 바다는\n"
	.string "  그 두 배 이상인 것이죠”$"

SlateportCity_OceanicMuseum_1F_Text_17EBBC:: @ 817EBBC
	.string "울퉁불퉁한 물결 모양의\n"
	.string "화석이 있다!\p"
	.string "“바다 밑바닥에\n"
	.string "  가라앉아 있는 흙에는\l"
	.string "  해수의 흐름에 의해\l"
	.string "  파도와 같은 문양이 생깁니다”\p"
	.string "“그 모습 그대로 화석이 된 것을\n"
	.string "  연흔이라고 부르고 있습니다”$"

SlateportCity_OceanicMuseum_1F_Text_17EC98:: @ 817EC98
	.string "동그란 돔 안에서\n"
	.string "알 수 없는 기계가 돌아가고 있다!\p"
	.string "무언가의 깊이를\n"
	.string "조사하고 있는 걸까?$"
