SlateportCity_House1_Text_17D46A:: @ 817D46A
	.string "안녕 안녕!\n"
	.string "나는 이름 감정사\l"
	.string "이름으로 점을 보는 사람이지\p"
	.string "자! 자네 포켓몬의\n"
	.string "별명을 감정해 주겠네$"

SlateportCity_House1_Text_17D4DB:: @ 817D4DB
	.string "어떤 포켓몬의\n"
	.string "별명을 감정하겠나?$"

SlateportCity_House1_Text_17D505:: @ 817D505
	.string "음- {STR_VAR_1}{K_I}라...\p"
	.string "꽤 좋은 닉네임을 지었군\p"
	.string "그렇지만-\n"
	.string "내가 조금 더 좋은 이름을\l"
	.string "지어주고 싶은데, 어떤가?$"

SlateportCity_House1_Text_17D580:: @ 817D580
	.string "그래 그럼\n"
	.string "어떤 별명으로 해줄까?$"

SlateportCity_House1_Text_17D5B0:: @ 817D5B0
	.string "좋아 이제부터\n"
	.string "이 포켓몬은 {STR_VAR_1}{K_I}라네!\p"
	.string "전보다 좋은 이름이지 않은가\n"
	.string "잘됐군!$"

SlateportCity_House1_Text_17D61E:: @ 817D61E
	.string "알았네\n"
	.string "그럼 또 오게나$"

SlateportCity_House1_Text_17D63A:: @ 817D63A
	.string "좋아 이제부터\n"
	.string "이 포켓몬은 {STR_VAR_1}{K_I}라네!\p"
	.string "전과 같아 보이지만\n"
	.string "이쪽이 당연히 더 좋다고!\l"
	.string "잘됐군!$"

SlateportCity_House1_Text_17D6CC:: @ 817D6CC
	.string "음- {STR_VAR_1}{K_I}라!\n"
	.string "정말 멋진 별명이군!\l"
	.string "흠잡을 데가 없어!\p"
	.string "앞으로도 {STR_VAR_1}{K_EULREUL}\n"
	.string "귀여워해 주게나!$"

SlateportCity_House1_Text_17D752:: @ 817D752
	.string "이보게나...\n"
	.string "그것은 알이지 않은가!$"
