SlateportCity_Text_164642:: @ 8164642
	.string "나는 노력가! 열심히 노력해서\n"
	.string "여러 가지를 팔지요!$"

SlateportCity_Text_164682:: @ 8164682
	.string "어머?\n"
	.string "네 {STR_VAR_1}...$"

SlateportCity_Text_164691:: @ 8164691
	.string "엄청 노력했구나!\p"
	.string "상으로\n"
	.string "이 노력리본을 달아 줘!$"

SlateportCity_Text_1646DD:: @ 81646DD
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "노력리본을 받았다!$"

SlateportCity_Text_1646FC:: @ 81646FC
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "노력리본을\l"
	.string "{STR_VAR_1}에게 달아 줬다!$"

SlateportCity_Text_16471C:: @ 816471C
	.string "좀 더 노력해봐!\p"
	.string "열심히 노력하면 내가 포켓몬한테\n"
	.string "좋은 걸 줄게!$"

SlateportCity_Text_164775:: @ 8164775
	.string "오! 네 {STR_VAR_1}\n"
	.string "노력리본이 잘 어울린다!$"

SlateportCity_Text_1647A7:: @ 81647A7
	.string "등대의 불빛은\n"
	.string "수십 킬로 떨어진 곳에서도 보여\p"
	.string "바닷속에 있는 포켓몬 너무\n"
	.string "눈부셔서 놀라거나 하지 않을까?$"

SlateportCity_Text_164814:: @ 8164814
	.string "여기 한번 보세요!\p"
	.string "이 근방에서 딴 해초는\n"
	.string "신선하고 팔팔하답니다!\l"
	.string "당장이라도 덮쳐 올 것 같아요!$"

SlateportCity_Text_1648A0:: @ 81648A0
	.string "물이 맑은 곳에\n"
	.string "많은 열매가 열리고\p"
	.string "사람들이 많이 가는 곳에\n"
	.string "시장이 생긴다...\p"
	.string "이렇게 마을은 점점 커져가는 거야$"

SlateportCity_Text_164937:: @ 8164937
	.string "바다의 향기가 나는 곳에서\n"
	.string "쇼핑을 할 수 있다니...\p"
	.string "잿빛도시는 정말 멋진 곳이야!$"

SlateportCity_Text_164995:: @ 8164995
	.string "봉제인형이나 쿠션은\n"
	.string "바닥에 놔두면 더러워지잖아?\p"
	.string "그래서 봉제인형이나 쿠션이\n"
	.string "더러워지지 않도록\l"
	.string "올려 둘 수 있는 벽돌을 사러 왔어!$"

SlateportCity_Text_164A30:: @ 8164A30
	.string "우오-! 그토록 기다리고 기다리던\n"
	.string "포켓몬 콘테스트!  \l"
	.string "나도 출전해야지-!\p"
	.string "일단 그 전에!\n"
	.string "포켓몬 잡아 와야지!$"

SlateportCity_Text_164AA9:: @ 8164AA9
	.string "후우 후우...\p"
	.string "난 보라시티에서\n"
	.string "여기까지 걸어서 왔는데\l"
	.string "이 마을 무지 넓네...\p"
	.string "이럴 줄 알았으면\n"
	.string "자전거 타고 올 걸 그랬어!$"

SlateportCity_Text_164B34:: @ 8164B34
	.string "이 박물관을 만든\n"
	.string "해양이라는 사람은\p"
	.string "해저 조사대\n"
	.string "리더이기도 해!\p"
	.string "아무튼 사람들은 그를\n"
	.string "해양관장이라고 부르고 있어!$"

SlateportCity_Text_164BBF:: @ 8164BBF
	.string "뭐지 저 줄은\n"
	.string "뭔 일 있나?$"

SlateportCity_Text_164BEA:: @ 8164BEA
	.string "이 박물관에는\n"
	.string "나도 어렸을 때 많이 왔어요\p"
	.string "여기 전시된 전시품을 보고\n"
	.string "바다의 신비를 동경했었죠$"

SlateportCity_Text_164C64:: @ 8164C64
	.string "잠깐 너! 밀지 마!\n"
	.string "순서 지켜야지!$"

SlateportCity_Text_164C9F:: @ 8164C9F
	.string "우리 {EVIL_TEAM}단의 기본 방침은\n"
	.string "“현지 집합” 그리고\l"
	.string "“현지 해산”이다!$"

SlateportCity_Text_164CE8:: @ 8164CE8
	.string "리더같이 똑똑하신 분이\n"
	.string "이제 와서 박물관에는\l"
	.string "무슨 볼일이지...?$"

SlateportCity_Text_164D2B:: @ 8164D2B
	.string "이번 작전은 뭐지?\p"
	.string "리더를 화나게 만들면 무서우니까\n"
	.string "절대 실패하고 싶지 않아...$"

SlateportCity_Text_164D92:: @ 8164D92
	.string "박물관 안에 갖고 싶은 게 있으면\n"
	.string "아예 통째로 뺏어버리면 될 텐데...$"

SlateportCity_Text_164DD5:: @ 8164DD5
	.string "어이 거기!\n"
	.string "순서 지켜라!$"

SlateportCity_Text_164DF4:: @ 8164DF4
	.string "이런 줄을 보면\p"
	.string "엄청난 인기였던 게임을 샀을 때를\n"
	.string "떠올리게 되네...$"

SlateportCity_Text_164E46:: @ 8164E46
	.string "착실하게 돈 내지 말고\n"
	.string "억지로 그냥 들어가면 될 텐데!$"

SlateportCity_Text_164E85:: @ 8164E85
	.string "바다는 정말 넓어...\p"
	.string "혹시 바다는\n"
	.string "포켓몬이 흘린 눈물로\l"
	.string "되어 있는 걸까....$"

SlateportCity_Text_164EDB:: @ 8164EDB
	.string "오래 되서 탈 수 없게 된 배가\n"
	.string "어떻게 되는지 알고 있나?\p"
	.string "바닷속에 가라앉혀서\n"
	.string "포켓몬의 거처가 되도록 하는 거야!$"

SlateportCity_Text_164F62:: @ 8164F62
	.string "여기 오면 너무 좋아서\n"
	.string "나도 모르게 많이 사 버려!$"

SlateportCity_Text_164F9E:: @ 8164F9E
	.string "포켓몬의 닉네임을 바꾸고 싶다면\n"
	.string "이 마을에 살고 있는\l"
	.string "이름 감정사한테 부탁하면 돼!$"

SlateportCity_Text_164FFC:: @ 8164FFC
	.string "다른 사람이랑 교환한 포켓몬은\n"
	.string "닉네임을 바꿀 수 없어!\p"
	.string "왜냐하면 닉네임은 지어준 사람의\n"
	.string "마음이 담겨 있으니까!$"

SlateportCity_Text_16507C:: @ 816507C
	.string "최근에 잿빛도시에도\n"
	.string "콘테스트 회장이 생겼어\p"
	.string "나도 포켓몬의 컨디션을\n"
	.string "높여서 참가할 생각이야$"

SlateportCity_Text_1650F1:: @ 81650F1
	.string "나무열매블렌더라고 알아?$"

SlateportCity_Text_16511E:: @ 816511E
	.string "모두가 함께 돌려야\n"
	.string "빠르게 돌아가고\p"
	.string "빠르게 돌릴수록\n"
	.string "좋은 포켓몬스넥이 나온대!$"

SlateportCity_Text_1651A1:: @ 81651A1
	.string "사용하면 포켓몬스넥이라고 하는\n"
	.string "과자를 만들 수 있대\p"
	.string "좋은 포켓몬스넥을 주면 포켓몬의\n"
	.string "컨디션도 쑥쑥 업해!$"

SlateportCity_Text_165222:: @ 8165222
	.string "유명한 스타가\n"
	.string "온 줄 알고\l"
	.string "사인 받으려고 했는데\p"
	.string "인터뷰하고 있는 사람\n"
	.string "어라...? 해양관장 아냐?$"

SlateportCity_Text_1652A0:: @ 81652A0
	.string "저 인터뷰어 언니\n"
	.string "미인에다가 멋있기까지 해!\p"
	.string "나도 크면\n"
	.string "국제 저널리스트가 될 거야!$"

SlateportCity_Text_16530A:: @ 816530A
	.string "해양관장이 바닷속에서\n"
	.string "무언가를 발견했다나 봐!\p"
	.string "그게 뭘까? 뭘까?$"

SlateportCity_Text_165376:: @ 8165376
	.string "뭐야 뭐야!?\p"
	.string "관장이 바다에서\n"
	.string "대물이라도 낚아 올린 거야?$"

SlateportCity_Text_1653D1:: @ 81653D1
	.string "얘들아-! 보고 있어-?\n"
	.string "나 TV에 잘 나오고 있니-?$"

SlateportCity_Text_1653F4:: @ 81653F4
	.string "방송국에서 취재하러 오다니\n"
	.string "관장도 유명인이 다 됐네!$"

SlateportCity_Text_165425:: @ 8165425
	.string "다이: 자 해양씨\n"
	.string "거기서 웃으세요!$"

SlateportCity_Text_165458:: @ 8165458
	.string "마리: 아... 그렇군요...\n"
	.string "참 귀중한 경험을 하셨네요...$"

SlateportCity_Text_165498:: @ 8165498
	.string "해양: ...그럼 앞으로도\n"
	.string "조사는 계속해 나갈게요!$"

SlateportCity_Text_1654E0:: @ 81654E0
	.string "마리: 그렇군요 아 그럼 해양씨!\n"
	.string "오늘 바쁘신데 시간 내주셔서\l"
	.string "정말 감사합니다!\p"
	.string "또 뭔가 발견하시면\n"
	.string "다시 취재하러 오겠습니다!$"

SlateportCity_Text_16558D:: @ 816558D
	.string "해양: 후우...\p"
	.string "방송국 카메라에 찍히는 건\n"
	.string "태어나서 처음이라 긴장했어!$"

SlateportCity_Text_1655E7:: @ 81655E7
	.string "오! {PLAYER}{K_I}인가!\n"
	.string "좋아 보이는군\p"
	.string "이번 해저 조사에서\n"
	.string "정말 엄청난 걸 발견했어!\p"
	.string "아주 먼 옛날에 멸종된 걸로 알려진\n"
	.string "포켓몬의 둥지를 말이야!\l"
	.string "발견했어!\p"
	.string "128번수로 심해에 있는\n"
	.string "해저동굴에 있더라고$"

SlateportCity_Text_1656BC:: @ 81656BC
	.string "후후후...\p"
	.string "들리고 있나?\l"
	.string "해양관장이여...\p"
	.string "네놈의 잠수정은\n"
	.string "우리 {EVIL_TEAM}단이 가져가겠다...!\p"
	.string "계획이 헛수고가 되었군!\n"
	.string "발명품은 잘 쓰도록 하마!\p"
	.string "하하하...!\n"
	.string "우리 {EVIL_TEAM}단의 계획을\l"
	.string "똑똑히 지켜보도록 해라!$"

SlateportCity_Text_16578F:: @ 816578F
	.string "해양: 방금 목소리는...?\p"
	.string "누가 확성기를 써서...\n"
	.string "어디서 말하고 있는 거지...?$"

SlateportCity_Text_1657FA:: @ 81657FA
	.string "선착장 안이야!\p"
	.string "잠수정을...\n"
	.string "빼앗으려고 하고 있어...?$"

SlateportCity_Text_16583A:: @ 816583A
	.string "{PLAYER}!\n"
	.string "함께 와 줘! 부탁해!$"

SlateportCity_Text_165856:: @ 8165856
	.string "포켓몬 콘테스트 하이퍼랭크 접수처\n"
	.string "열정적으로 도전하라 트레이너!$"

SlateportCity_Text_1658A0:: @ 81658A0
	.string "“해양조선소”\p"
	.string "파도를 자유자재로 조종하는 선원\n"
	.string "모집 중!$"

SlateportCity_Text_1658E8:: @ 81658E8
	.string "“해양조선소”\p"
	.string "잿빛도시와 해안시티를 연결하는\n"
	.string "연락선 타이드립호는\l"
	.string "완성이 이제 눈앞에!$"

SlateportCity_Text_165952:: @ 8165952
	.string "“해양조선소”\p"
	.string "연락선 타이드립호에\n"
	.string "승선을 희망하는 분은\l"
	.string "배 타는 곳의 접수처로 오세요!$"

SlateportCity_Text_1659B3:: @ 81659B3
	.string "“포켓몬 애호가클럽”\p"
	.string "포켓몬을 좋아하는 사람\n"
	.string "모두 모여라!$"

SlateportCity_Text_1659E3:: @ 81659E3
	.string "끝없는 바다...\n"
	.string "그것은 생명의 근원...\p"
	.string "“바다의 과학박물관”$"

SlateportCity_Text_165A17:: @ 8165A17
	.string "여기는 잿빛도시\n"
	.string "사람과 포켓몬이 왕래하는 항구$"

SlateportCity_Text_165A57:: @ 8165A57
	.string "“잿빛시장”\p"
	.string "여기서밖에\n"
	.string "구할 수 없는 물건 한가득!$"

SlateportCity_Text_165A8B:: @ 8165A8B
	.string "“잿빛도시 배 타는 곳”\p"
	.string "연락선 타이드립호는\n"
	.string "조선소에서 건조 중!\p"
	.string "조금만 더 기다려 주세요!$"

SlateportCity_Text_165B02:: @ 8165B02
	.string "“잿빛도시 배 타는 곳”\p"
	.string "연락선 타이드립호로\n"
	.string "신나는 배여행을 즐겨 주세요!$"

SlateportCity_Text_165B48:: @ 8165B48
	.string "“이름 감정사의 집”\n"
	.string "포켓몬의 이름을 점칩니다$"
