SlateportCity_ContestHall_Text_17CB71:: @ 817CB71
	.string "콘테스트의 나이스한 정보를\n"
	.string "알려줄게!\p"
	.string "몇몇 기술 다음에\n"
	.string "특정한 기술로 어필하면\l"
	.string "엄청 눈에 띄는 경우가 있어!\p"
	.string "잘하면 꽤나\n"
	.string "유리한 어필이 가능하다고!\p"
	.string "다만 방해받는 경우도 있어$"

SlateportCity_ContestHall_Text_17CC80:: @ 817CC80
	.string "우리 아빠는 콘테스트의\n"
	.string "심사위원을 하고 있어!\p"
	.string "나 어른이 되면\n"
	.string "콘테스트의 심사위원하고\l"
	.string "체육관 관장 중에 뭘 할까?$"

SlateportCity_ContestHall_Text_17CCE2:: @ 817CCE2
	.string "어째서 내 포켓몬이\n"
	.string "우승하지 못했는지\l"
	.string "전혀 납득할 수 없어서 말이야\l"
	.string "심사위원한테 좀 따져봤는데\p"
	.string "전혀 상대해주지 않아서\n"
	.string "너무 분해 죽겠어!\p"
	.string "어이 너!\n"
	.string "잠자코 이거나 받아!$"

SlateportCity_ContestHall_Text_17CE28:: @ 817CE28
	.string "기술머신41은 트집!\p"
	.string "상대가 같은 기술을 반복해서\n"
	.string "사용할 수 없게 만드는 기술이지!\p"
	.string "참고로 말하지만\n"
	.string "난 트집 잡은 적 없다!$"

SlateportCity_ContestHall_Text_17CEF3:: @ 817CEF3
	.string "사회자: 어머! 꽤 멋진\n"
	.string "포켓몬을 데리고 있네!\p"
	.string "부디! 콘테스트에\n"
	.string "참가해줘!\p"
	.string "분명 잘 될 거야!\n"
	.string "내 눈은 확실하거든!$"

SlateportCity_ContestHall_Text_17CFA7:: @ 817CFA7
	.string "심사위원: 여어, 안녕하신가!\n"
	.string "너도 트레이너인가 보구나!\p"
	.string "그러면 포켓몬 콘테스트에\n"
	.string "나올 수 없는 건 아니야!\p"
	.string "콘테스트패스를 잔디마을에서 받고\n"
	.string "지금 바로 참가하는 거다!$"

SlateportCity_ContestHall_Text_17D054:: @ 817D054
	.string "드디어 이제부터 어필타임!\n"
	.string "어느 기술부터 보여줄까나?$"

SlateportCity_ContestHall_Text_17D07F:: @ 817D07F
	.string "내 포켓몬의 어필\n"
	.string "그다지 주목받지 못했어...\p"
	.string "흥... 저 심사위원\n"
	.string "보는 눈이 없군!$"

SlateportCity_ContestHall_Text_17D0F9:: @ 817D0F9
	.string "앗! 이런 곳에까지 온 너\n"
	.string "연구에 열심이구나!\l"
	.string "그러면 좋은 걸 알려줄게\p"
	.string "보여준 기술의 반응이 좋으면\n"
	.string "회장이 익사이트 해져!\p"
	.string "가장 익사이트 해졌을 때\n"
	.string "어필한 포켓몬에겐...\p"
	.string "좋은 일이 일어날지도!$"

SlateportCity_ContestHall_Text_17D222:: @ 817D222
	.string "아 안되겠어! 포켓몬보다\n"
	.string "내가 더 긴장하고 있잖아!\l"
	.string "부들부들.... 두근두근...$"

SlateportCity_ContestHall_Text_17D27F:: @ 817D27F
	.string "포켓몬 승부와 콘테스트는\n"
	.string "다른 것 같으면서도 닮았어!\p"
	.string "소중히 키운 포켓몬을\n"
	.string "믿고 응원한다는 점이 말야!$"

SlateportCity_ContestHall_Text_17D300:: @ 817D300
	.string "저 포켓몬 기세 좋아 보인다!\p"
	.string "2차 심사에서 기세가 좋은\n"
	.string "포켓몬은 딱히 긴장하지 않아서\l"
	.string "어필할 수 있는 것 같네$"

SlateportCity_ContestHall_Text_17D39A:: @ 817D39A
	.string "뭐야- 이 정도면\n"
	.string "내 포켓몬 쪽이\l"
	.string "더 대단하다고!$"

SlateportCity_ContestHall_Text_17D3F0:: @ 817D3F0
	.string "기운 넘치는 어필을 보고 있으면\n"
	.string "같이 몸이\l"
	.string "기운 넘치게 되지 않아?$"

SlateportCity_ContestHall_Text_17D447:: @ 817D447
	.string "포켓몬 콘테스트\n"
	.string "하이퍼랭크 스테이지!$"
