SlateportCity_House2_Text_1804CF:: @ 81804CF
	.string "내 포켓몬은 성격이 “성급”이라\n"
	.string "다른 포켓몬에 비해\l"
	.string "스피드가 빠르더군\p"
	.string "성격에 따라 오르기 쉬운 능력이\n"
	.string "다른 건가?$"

SlateportCity_House2_Text_180567:: @ 8180567
	.string "콘테스트에 참가하려면\n"
	.string "콘테스트패스가 필요해\p"
	.string "포켓몬을 가지고 있는 사람이라면\n"
	.string "누구든지 받을 수 있으니 안심이지!$"

SlateportCity_House2_Text_1805CD:: @ 81805CD
	.string "어머! 그건 콘테스트패스!?\n"
	.string "너도 콘테스트에 참가할 거구나!$"
