SlateportCity_PokemonFanClub_Text_17D773:: @ 817D773
	.string "으흠!\p"
	.string "내가 바로 포켓몬 애호가클럽에서\n"
	.string "가장 대단한 회장이랍니다!\p"
	.string "뭐니 뭐니 해도 회장이니까요\n"
	.string "포켓몬 키우기로\l"
	.string "나를 따라올 수 있는 사람은 없죠!\p"
	.string "어떤 콘테스트라도\n"
	.string "우승은 따 놓은 당상이에요!\p"
	.string "하지만 그래서는 다른 분들의\n"
	.string "즐거움을 빼앗아 버리게 되니까요\p"
	.string "지금은 여기서\n"
	.string "다른 분들의 포켓몬을\l"
	.string "보는 것만으로 만족하고 있답니다\p"
	.string "이야- 다른 사람이 키운 포켓몬을\n"
	.string "보는 건 정말 즐거워요!\p"
	.string "제대로 키운 포켓몬의\n"
	.string "그 행복해 보이는 얼굴...\p"
	.string "그걸 바라보고 있는 트레이너의\n"
	.string "상냥한 눈동자...\p"
	.string "이야- 정말 행복함으로\n"
	.string "가슴이 벅차올라요...\p"
	.string "오오 실례!\n"
	.string "저도 모르게 얘기가 길어졌네요\p"
	.string "그럼 바로 그대의 포켓몬이\n"
	.string "얼마나 성장했는지\l"
	.string "한번 봐 볼게요!$"

SlateportCity_PokemonFanClub_Text_17DA14:: @ 817DA14
	.string "그대의 포켓몬은 잘 자라고 있나요?\n"
	.string "한번 봐 보도록 하죠!$"

SlateportCity_PokemonFanClub_Text_17DA49:: @ 817DA49
	.string "흠흠...\n"
	.string "그렇군...$"

SlateportCity_PokemonFanClub_Text_17DA5C:: @ 817DA5C
	.string "흠...\n"
	.string "나쁘진 않지만\l"
	.string "그렇다고 좋지도 않고...\p"
	.string "어버이 트레이너인 그대의 노력이\n"
	.string "필요할 거 같네요!\p"
	.string "예를 들어 더 많이\n"
	.string "포켓몬스넥을 주는 건 어떨까요?$"

SlateportCity_PokemonFanClub_Text_17DB0B:: @ 817DB0B
	.string "오오...\p"
	.string "그대의 포켓몬은\n"
	.string "진짜 잘 성장했네요!\l"
	.string "따라서 상을 드려야겠지만\p"
	.string "아쉽게도 가방이\n"
	.string "가득 차신 모양이군요$"

SlateportCity_PokemonFanClub_Text_17DB89:: @ 817DB89
	.string "그대의 {STR_VAR_1} 말인데요\n"
	.string "진짜 잘 성장했네요!\l"
	.string "이야- 정말 대단해요!\p"
	.string "하지만 이 도구를 지니게 하면\n"
	.string "더욱 매력이 올라갈 거예요\l"
	.string "제가 보장합니다!$"

SlateportCity_PokemonFanClub_Text_17DC1B:: @ 817DC1B
	.string "그 빨강밴드를 지니게 하면\n"
	.string "포켓몬의 근사함을\l"
	.string "모두에게 인정받게 될 거예요!$"

SlateportCity_PokemonFanClub_Text_17DC74:: @ 817DC74
	.string "그 파랑밴드를 지니게 하면\n"
	.string "포켓몬의 아름다움을\l"
	.string "지금보다 더 뽐낼 수 있게 될 거예요!$"

SlateportCity_PokemonFanClub_Text_17DCCB:: @ 817DCCB
	.string "그 분홍밴드를 지니게 하면\n"
	.string "포켓몬의 귀여움을\l"
	.string "더 이끌어 낼 수 있을 거예요!$"

SlateportCity_PokemonFanClub_Text_17DD27:: @ 817DD27
	.string "그 초록밴드를 지니게 하면\n"
	.string "포켓몬의 슬기로움을\l"
	.string "더욱 성장시킬 수 있을 거예요!$"

SlateportCity_PokemonFanClub_Text_17DD78:: @ 817DD78
	.string "그 노랑밴드를 지니게 하면\n"
	.string "포켓몬의 강인함을\l"
	.string "더욱 어필할 수 있을 거예요!$"

SlateportCity_PokemonFanClub_Text_17DDD5:: @ 817DDD5
	.string "그대에게 줄 도구는\n"
	.string "이제 더 이상 없어요!\p"
	.string "왜냐하면 도구에 기대지 않아도\n"
	.string "포켓몬을 키우는 그대의 능력은\l"
	.string "환상적이니까요!$"

SlateportCity_PokemonFanClub_Text_17DE6B:: @ 817DE6B
	.string "난 포켓몬이\n"
	.string "사람을 따르는 모습을\l"
	.string "보는 게 너무 좋아\p"
	.string "포켓몬은 함께 있는\n"
	.string "사람의 감정에 매우 민감해!\p"
	.string "네가 포켓몬을 소중하게 여기면\n"
	.string "포켓몬도 너를\l"
	.string "금세 따르게 될 거야!\p"
	.string "네 포켓몬이\n"
	.string "너를 잘 따르기 시작하면\l"
	.string "나한테도 좀 보여줘$"

SlateportCity_PokemonFanClub_Text_17DF57:: @ 817DF57
	.string "네 포켓몬\n"
	.string "널 정말 잘 따르고 있구나\p"
	.string "포켓몬에게 자상한 트레이너를 위한\n"
	.string "애호가클럽의 선물이야$"

SlateportCity_PokemonFanClub_Text_17DFB8:: @ 817DFB8
	.string "포켓몬은 함께 있는\n"
	.string "사람의 감정에 매우 민감해!\p"
	.string "네가 포켓몬을 소중하게 여기면\n"
	.string "포켓몬도 너를\l"
	.string "금세 따르게 될 거야!$"

SlateportCity_PokemonFanClub_Text_17E03B:: @ 817E03B
	.string "포켓몬 승부에서 져서\n"
	.string "기절을 많이 하게 되면\l"
	.string "포켓몬이 점점 위축돼서\l"
	.string "트레이너를 의심하기 시작해\p"
	.string "다시 말해서\n"
	.string "잘 따르지 않게 된다는 거야$"

SlateportCity_PokemonFanClub_Text_17E0ED:: @ 817E0ED
	.string "포켓몬은 자기한테 도구를\n"
	.string "써 주는 게 좋은 걸까?\p"
	.string "왜냐면 타우린 같은 걸 주면\n"
	.string "정말 기뻐하잖아!$"

SlateportCity_PokemonFanClub_Text_17E14E:: @ 817E14E
	.string "에나비: 에냐-아$"

SlateportCity_PokemonFanClub_Text_17E164:: @ 817E164
	.string "지그제구리: 지규....$"

SlateportCity_PokemonFanClub_Text_17E178:: @ 817E178
	.string "마릴리: 마리 마리!?$"
