SlateportCity_Harbor_Text_17FA0A:: @ 817FA0A //JP: 15FB54
	.string "에? 배 말입니까?\p"
	.string "죄송합니다만 현재\n"
	.string "연락선은 없습니다...$"

SlateportCity_Harbor_Text_17FA73:: @ 817FA73
	.string "연락선을 이용하시려는 거군요!\n"
	.string "티켓은 가지고 계신가요?$"

SlateportCity_Harbor_Text_17FAAD:: @ 817FAAD
	.string "{PLAYER}\s\n"
	.string "티켓이 없다!\p"
	.string "...죄송합니다!\p"
	.string "배에는 티켓을 가진 분들만\n"
	.string "탑승하실 수 있습니다$"

SlateportCity_Harbor_Text_17FB0A:: @ 817FB0A
	.string "{PLAYER}\s\n"
	.string "승선티켓을 보여줬다!\p"
	.string "네! 확인했습니다!\p"
	.string "어디로 가시겠어요?$"

SlateportCity_Harbor_Text_17FB5F:: @ 817FB5F
	.string "또 이용해 주십시오!$"

SlateportCity_Harbor_Text_17FB81:: @ 817FB81
	.string "해안시티 말씀이시군요!$"

SlateportCity_Harbor_Text_17FB9C:: @ 817FB9C
	.string "배틀타워 말씀이시군요!$"

SlateportCity_Harbor_Text_17FBB6:: @ 817FBB6
	.string "연락선에서 잠시 기다려 주십시오$"

SlateportCity_Harbor_Text_17FBE5:: @ 817FBE5
	.string "어디로 가시겠어요?$"

SlateportCity_Harbor_Text_17FC07:: @ 817FC07
	.string "바닷속 깊은 곳이라...\n"
	.string "과연 어떤 모습일까?\p"
	.string "나도 언젠가 들어가 보고 싶어!$"

SlateportCity_Harbor_Text_17FC7C:: @ 817FC7C
	.string "나도 해양관장과 같이\n"
	.string "해저 조사하러 가고 싶었어!\p"
	.string "그렇지만 잠수정 안은 좁으니까\n"
	.string "내가 타 버리면 관장이\l"
	.string "못 타게 될 거야...$"

SlateportCity_Harbor_Text_17FD1C:: @ 817FD1C
	.string "해양: 저 녀석들은...\p"
	.string "예전에 박물관에서\n"
	.string "데봉화물을 빼앗아 가려고 했던...$"

SlateportCity_Harbor_Text_17FD7D:: @ 817FD7D
	.string "{EVIL_LEADER}: 후후후...!\p"
	.string "꽤 고생했겠군\n"
	.string "일부러 송화산에서\l"
	.string "여기까지 쫓아온 건가?\p"
	.string "하지만 이제 어느 누구도\n"
	.string "우리를 막을 순 없다!\p"
	.string "막고 싶다면\n"
	.string "해안시티의 아지트까지 와라!\l"
	.string "후후후...$"

SlateportCity_Harbor_Text_17FE60:: @ 817FE60
	.string "해양: 어째서...\p"
	.string "{EVIL_TEAM}단이\n"
	.string "내 잠수정\l"
	.string "“해연 1호”를 빼앗은 거지?\p"
	.string "설마 그 녀석들도\n"
	.string "해저에 잠들어 있는 포켓몬을...\p"
	.string "하지만 나는 쫓아가도\n"
	.string "그 녀석들을 상대할 수 없을 텐데...$"

SlateportCity_Harbor_Text_17FF35:: @ 817FF35
	.string "해양: 아아 {PLAYER}\i...\p"
	.string "그런가... {EVIL_TEAM}단은\n"
	.string "이미 출발해버렸구나...\p"
	.string "아니야 신경쓰지 않아도 돼\n"
	.string "네 책임이 아니니까\p"
	.string "잠수정을 따라간다는 거\n"
	.string "자체가 보통 인간에게는\l"
	.string "말도 안되는 일이지\p"
	.string "포켓몬에게 다이빙이라고 하는\n"
	.string "바닷속으로 들어갈 수 있는 기술을\l"
	.string "가르치면 또 모를까...\p"
	.string "이끼시티에 가면\n"
	.string "다이빙을 하는 사람이\l"
	.string "많이 있으니까 가르쳐줄 사람이\l"
	.string "있을지도 모르겠다$"

SlateportCity_Harbor_Text_1800A0:: @ 81800A0
	.string "해양: 잠수정을 따라간다는 거\n"
	.string "자체가 보통 인간에게는\l"
	.string "말도 안되는 일이지\p"
	.string "포켓몬에게 다이빙이라고 하는\n"
	.string "바닷속으로 들어갈 수 있는 기술을\l"
	.string "가르치면 또 모를까...\p"
	.string "이끼시티에 가면\n"
	.string "다이빙을 하는 사람이\l"
	.string "많이 있으니까 가르쳐줄 사람이\n"
	.string "있을지도 모르겠다$"

SlateportCity_Harbor_Text_18017B:: @ 818017B
	.string "해양: 맞다! 하기노인이\n"
	.string "조선소에 와 주었어!\p"
	.string "좋-아! 이걸로 연락선이\n"
	.string "완성되는 것도 얼마 안 남았어!$"

SlateportCity_Harbor_Text_1801EA:: @ 81801EA
	.string "해양: {PLAYER}!\p"
	.string "연락선 타이드립호가\n"
	.string "드디어 완성됐어!\p"
	.string "네 지인인 하기노인이\n"
	.string "도와준 덕분이야\p"
	.string "한번 타 보도록 해$"

SlateportCity_Harbor_Text_18028B:: @ 818028B
	.string "해양: 으음?\n"
	.string "{PLAYER}\e 가지고 있는 그거...\p"
	.string "탐지기잖아!\n"
	.string "그게 있으면 조사가\l"
	.string "더욱 진전될 것 같아\p"
	.string "{PLAYER}! 내가 가지고 있는\n"
	.string "심해의이빨과 심해의비늘 중\l"
	.string "하나랑 탐지기를 교환하지 않을래?$"

SlateportCity_Harbor_Text_180360:: @ 8180360
	.string "해양: 그래?\n"
	.string "{PLAYER}\r 가지고 있어도\l"
	.string "쓸데는 없을 거라고 생각하지만...\p"
	.string "뭐 괜찮아\n"
	.string "탐지기를 교환하고 싶어지면\l"
	.string "다시 또 말 걸어줘!$"

SlateportCity_Harbor_Text_1803DD:: @ 81803DD
	.string "해양: 심해의이빨과 교환할 거지?$"

SlateportCity_Harbor_Text_180412:: @ 8180412
	.string "해양: 심해의비늘과 교환할 거지?$"

SlateportCity_Harbor_Text_180447:: @ 8180447
	.string "해양: 어느 쪽이랑 교환할래?$"

SlateportCity_Harbor_Text_18046B:: @ 818046B
	.string "{PLAYER}\s 해양관장에게\n"
	.string "탐지기를 전달했다!$"

SlateportCity_Harbor_Text_180491:: @ 8180491
	.string "해양: 고마워 {PLAYER}!\n"
	.string "이걸로 연구가 더 진전되겠어$"
