SootopolisCity_House3_Text_18FB36:: @ 818FB36
	.string "당신은 포켓몬 트레이너시군요?\p"
	.string "루네시티의 체육관 관장이신\n"
	.string "윤진님은 팬이 정말 많은데\l"
	.string "당신은 팬이 있나요?$"

SootopolisCity_House3_Text_18FB9C:: @ 818FB9C
	.string "흐-응\n"
	.string "그럼 꽤 강하신가 보군요?!$"

SootopolisCity_House3_Text_18FBC0:: @ 818FBC0
	.string "어머머...\n"
	.string "그건 좀 슬프네요\p"
	.string "팬이 많이 생기도록 열심히 해보세요!$"

SootopolisCity_House3_Text_18FC1A:: @ 818FC1A
	.string "열성적인 팬들은 관동지방이나\n"
	.string "성도지방에서도 찾아와!\p"
	.string "내가 해안시티의\n"
	.string "트레이너 팬클럽에 갔었을 때도\l"
	.string "엄청 굉장했어!$"
