SootopolisCity_House6_Text_18FEA1:: @ 818FEA1
	.string "와- 이게 얼마 만에 오신 손님이야?!\p"
	.string "너-무 기쁘니까\n"
	.string "커다란 고래왕자인형을 줄게!$"

SootopolisCity_House6_Text_18FF12:: @ 818FF12
	.string "소중히 해줘!$"

SootopolisCity_House6_Text_18FF28:: @ 818FF28
	.string "필요하지만 지금은 안 돼?\n"
	.string "그럼 가지고 있을게$"

SootopolisCity_House6_Text_18FF6D:: @ 818FF6D
	.string "그래?\n"
	.string "인형 필요 없니?$"

SootopolisCity_House6_Text_18FF95:: @ 818FF95
	.string "난 인형이 너무 좋아!$"
