SootopolisCity_Mart_Text_18F890:: @ 818F890 //JP: 16D7BE
	.string "포인트업은 정말 대단해!\p"
	.string "왜냐하면 포켓몬의\n"
	.string "파워포인트를 늘려주니까!$"

SootopolisCity_Mart_Text_18F8D7:: @ 818F8D7
	.string "대체 뭐가 일어나고 있는 거지?!$"

SootopolisCity_Mart_Text_18F8F2:: @ 818F8F2
	.string "“회복약”이라고 알고 있나요?\p"
	.string "포켓몬의 체력이 완쾌!\n"
	.string "상태 이상도 모두 회복!\p"
	.string "정말 꿈만 같은 도구랍니다$"

SootopolisCity_Mart_Text_18F96B:: @ 818F96B
	.string "이 날씨...\n"
	.string "무언가가 눈을 뜬 징조인가...?$"
