ClosedSootopolisGymDoorText: @ 8169690 //JP: 14A7B8
	.string "문이 닫혀 있다!$"

SootopolisCity_Text_1696A4:: @ 81696A4
	.string "당신은 무슨 일로 오셨나요?\p"
	.string "이곳은 각성의 사당...\p"
	.string "송화산에서 잠든\n"
	.string "포켓몬의 영혼이\l"
	.string "되살아난다고 전해지는 장소...\p"
	.string "부디 돌아가 주십시오$"

SootopolisCity_Text_16972B:: @ 816972B
	.string "바다로 잠수하거나\n"
	.string "계단을 오르락내리락...\p"
	.string "이 마을에서 살다 보면\n"
	.string "몸이 꽤 튼튼해진단 말이지$"

SootopolisCity_Text_1697A7:: @ 81697A7
	.string "나 아직 단 한 번도 이 마을에서\n"
	.string "벗어나 본 적이 없어\p"
	.string "저 동그란 하늘 저편에는\n"
	.string "어떤 세계가 있는 걸까?$"

SootopolisCity_Text_169813:: @ 8169813
	.string "호오!\n"
	.string "일부러 여기 루네시티까지 오다니\l"
	.string "무료한 관광객은 아니군!\p"
	.string "그렇다고 돈을 내고 온\n"
	.string "관광객도 아니고...$"

SootopolisCity_Text_1698A0:: @ 81698A0
	.string "루네시티는 운석의 낙하로 인해 생긴\n"
	.string "크레이터의 중심에 있는 마을이야\p"
	.string "위를 보면 크레이터의 가장자리도\n"
	.string "같이 보여서\l"
	.string "하늘 전체를 볼 수는 없어...\p"
	.string "하지만 그렇기 때문에\n"
	.string "루네시티에서 보이는 하늘이\l"
	.string "가장 아름다워$"

SootopolisCity_Text_169988:: @ 8169988
	.string "성호: {PLAYER}\n"
	.string "너도 온 거구나\l"
	.string "이렇게 엄청난 비인데도...\p"
	.string "아!\n"
	.string "그의 얘기를 좀 들어 줄래?$"

SootopolisCity_Text_1699FD:: @ 81699FD
	.string "난 윤진\n"
	.string "이 마을의 체육관 관장\p"
	.string "그리고\n"
	.string "각성의 사당을 지키는 자\p"
	.string "이 많은 양의 비는\n"
	.string "각성의 사당에서 나오는\l"
	.string "힘에 의해 내리고 있다$"

SootopolisCity_Text_169AB7:: @ 8169AB7
	.string "그건 쪽빛구슬\p"
	.string "알았어\n"
	.string "날 따라와$"

SootopolisCity_Text_169AE7:: @ 8169AE7
	.string "성호: 사람이... 포켓몬이...\n"
	.string "살아가기 위해 필요한 물이\p"
	.string "어째서 우리들을\n"
	.string "불안하게 만드는 거지...\p"
	.string "루네시티 상공에 모인 먹구름은\n"
	.string "더욱 거대해져서\l"
	.string "호연 전체를 뒤덮겠지...\p"
	.string "이대로라면...$"

SootopolisCity_Text_169BC7:: @ 8169BC7
	.string "윤진: 이 앞은 각성의 사당\p"
	.string "우리들 루네 사람은\n"
	.string "이 각성의 사당 안으로\l"
	.string "들어갈 수 없어\p"
	.string "하지만 너는 가야만 해\n"
	.string "그 쪽빛구슬과 함께\p"
	.string "사당 안에서 무슨 일이 일어나도\n"
	.string "무엇이 기다리고 있더라도$"

SootopolisCity_Text_169C99:: @ 8169C99
	.string "성호: {PLAYER}\n"
	.string "네가 쪽빛구슬을\l"
	.string "가지고 있을 줄이야\p"
	.string "괜찮아!\n"
	.string "너와 너의 포켓몬이라면\l"
	.string "무슨 일이 있어도 잘 해낼 수 있어\p"
	.string "나는 그렇게 믿어$"

SootopolisCity_Text_169D37:: @ 8169D37
	.string "윤진: 너는 가야만 해\n"
	.string "그 쪽빛구슬과 함께\p"
	.string "사당 안에서 무슨 일이 일어나도\n"
	.string "무엇이 기다리고 있더라도$"

SootopolisCity_Text_169DA6:: @ 8169DA6
	.string "성호: 괜찮아!\n"
	.string "너와 너의 포켓몬이라면\l"
	.string "무슨 일이 있어도 잘 해낼 수 있어\p"
	.string "나는 그렇게 믿어$"

SootopolisCity_Text_169E0F:: @ 8169E0F
	.string "성호: {PLAYER}\n"
	.string "너도 온 거구나\l"
	.string "이렇게 심한 가뭄인데도...\p"
	.string "아!\n"
	.string "그의 얘기를 좀 들어 줄래?$"

SootopolisCity_Text_169E82:: @ 8169E82
	.string "난 윤진\n"
	.string "이 마을의 체육관 관장\p"
	.string "그리고\n"
	.string "각성의 사당을 지키는 자\p"
	.string "이 가뭄은 각성의 사당에서 나오는\n"
	.string "힘에 의해 나타나고 있다$"

SootopolisCity_Text_169F3C:: @ 8169F3C
	.string "그건 주홍구슬\p"
	.string "알았어\n"
	.string "날 따라와$"

SootopolisCity_Text_169F6B:: @ 8169F6B
	.string "성호: 사람이... 포켓몬이...\n"
	.string "살아가기 위해 필요한 빛이\p"
	.string "어째서 우리들을\n"
	.string "불안하게 만드는 거지...\p"
	.string "루네시티의 상공에 보이는 태양은\n"
	.string "더욱 그 빛을 더해서\l"
	.string "호연 전체를 비추겠지...\p"
	.string "이대로라면...$"

SootopolisCity_Text_16A06C:: @ 816A06C
	.string "윤진: 이 앞은 각성의 사당\p"
	.string "우리들 루네 사람은\n"
	.string "이 각성의 사당 안으로\l"
	.string "들어갈 수 없어\p"
	.string "하지만 너는 가야만 해\n"
	.string "그 주홍구슬과 함께\p"
	.string "사당 안에서 무슨 일이 일어나도\n"
	.string "무엇이 기다리고 있더라도$"

SootopolisCity_Text_16A13E:: @ 816A13E
	.string "성호: {PLAYER}\n"
	.string "네가 주홍구슬을\l"
	.string "가지고 있을 줄이야\p"
	.string "괜찮아!\n"
	.string "너와 너의 포켓몬이라면\l"
	.string "무슨 일이 있어도 잘 해낼 수 있어\p"
	.string "나는 그렇게 믿어$"

SootopolisCity_Text_16A1DB:: @ 816A1DB
	.string "윤진: 너는 가야만 해\n"
	.string "그 주홍구슬과 함께\p"
	.string "사당 안에서 무슨 일이 일어나도\n"
	.string "무엇이 기다리고 있더라도$"

SootopolisCity_Text_16A249:: @ 816A249
	.string "성호: 괜찮아!\n"
	.string "너와 너의 포켓몬이라면\l"
	.string "무슨 일이 있어도 잘 해낼 수 있어\p"
	.string "나는 그렇게 믿어$"

SootopolisCity_Text_16A2B2:: @ 816A2B2
	.string "송화산 할아버지의 말씀...\n"
	.string "그건 사실이었군요...$"

SootopolisCity_Text_16A2FB:: @ 816A2FB
	.string "지금 호연지방의 균형이\n"
	.string "크게 무너지려고 합니다...$"

SootopolisCity_Text_16A33E:: @ 816A33E
	.string "성호: {PLAYER}\n"
	.string "네 덕분이다\p"
	.string "루네의 하늘이 원래대로 돌아왔어\n"
	.string "윤진도 감사하다고 전해 달래\p"
	.string "그래그래 윤진 말인데\n"
	.string "안에서 너를 기다리고 있어\p"
	.string "그는 강해\n"
	.string "하지만 지금의 너라면\l"
	.string "대등하게 싸울 수 있겠지\p"
	.string "그럼\n"
	.string "열심히 해$"

SootopolisCity_Text_16A455:: @ 816A455
	.string "모든 일의 시작은 각성의 사당\n"
	.string "모든 일의 끝은 송화산...\p"
	.string "포켓몬도 사람도\n"
	.string "어디에서 오고\l"
	.string "어디로 가는 걸까요...$"

SootopolisCity_Text_16A4D6:: @ 816A4D6
	.string "너 혹시\n"
	.string "윤진님께 도전할 생각이야?\p"
	.string "용기 있네-!$"

SootopolisCity_Text_16A531:: @ 816A531
	.string "너 혹시\n"
	.string "윤진님한테 이긴 거야!?\p"
	.string "그럼 이제부터 나\n"
	.string "네 팬이 돼볼까!!$"

SootopolisCity_Text_16A587:: @ 816A587
	.string "호오!\n"
	.string "일부러 여기 루네시티까지 오다니\l"
	.string "무료한 관광객은 아니군!\p"
	.string "그렇다고 돈을 내고 온\n"
	.string "관광객도 아니고...$"

SootopolisCity_Text_16A614:: @ 816A614
	.string "운석의 크레이터라는\n"
	.string "고리에 둘러싸인 둥근 밤하늘\p"
	.string "그 안에서는 수많은 별이\n"
	.string "살아 있는 것처럼 반짝여...\l"
	.string "내가 제일 좋아하는 풍경이야$"

SootopolisCity_Text_16A6AE:: @ 816A6AE
	.string "얼레? 우리 집이 어디더라?$"

SootopolisCity_Text_16A6C7:: @ 816A6C7
	.string "루네시티 포켓몬체육관\n"
	.string "관장 윤진\l"
	.string "물을 사랑하는 아티스트!$"

SootopolisCity_Text_16A711:: @ 816A711
	.string "여기는 루네시티\n"
	.string "역사가 잠들어 있는 신비한 마을$"
