SootopolisCity_House4_Text_18FC92:: @ 818FC92
	.string "이 몸이 좋은 걸 알려주지!\p"
	.string "이 주변 바닷속에는\n"
	.string "고대의 유적이 있다고 한다!\p"
	.string "잘하면 고대의 보물을\n"
	.string "마구마구 발견할 수\l"
	.string "있을지도 모른다고!$"

SootopolisCity_House4_Text_18FD41:: @ 818FD41
	.string "보물이라...\p"
	.string "그야 있으면 좋겠지만\n"
	.string "없다고 해도 포켓몬과 함께\l"
	.string "바닷속을 산책할 수 있다니\l"
	.string "정말 멋져!$"

SootopolisCity_House4_Text_18FDD8:: @ 818FDD8
	.string "마릴리: 마루리-$"
