SootopolisCity_PokemonCenter_1F_Text_18F6A2:: @ 818F6A2
	.string "이 마을 체육관 관장인 윤진은\n"
	.string "호연지방에서도 제일 강하다고\l"
	.string "여겨지는 실력자...\p"
	.string "그런 윤진보다도 더 강하다는 게\n"
	.string "사천왕... 챔피언...\p"
	.string "그 강함은\n"
	.string "도대체 어느 정도일까...?$"

SootopolisCity_PokemonCenter_1F_Text_18F770:: @ 818F770
	.string "이 마을에 사는 사람들이 모두\n"
	.string "집에 틀어박혀서 나오질 않아요!\p"
	.string "이 날씨...\n"
	.string "무언가 일어날 징조일까요?$"

SootopolisCity_PokemonCenter_1F_Text_18F7EA:: @ 818F7EA
	.string "어떤 때라도\n"
	.string "무슨 일이 있더라도\l"
	.string "난 계속 포켓몬과 친구로 있을 거야\p"
	.string "왜냐하면 포켓몬이랑 같이 있으면\n"
	.string "엄청 즐거우니까!$"

SootopolisCity_PokemonCenter_1F_Text_18F860:: @ 818F860
	.string "이유는 모르겠는데...\n"
	.string "무지... 불안해...$"
