SootopolisCity_Gym_1F_Text_18E8A5:: @ 818E8A5 //JP: 16CDA3
	.string "잘 있었나!!\n"
	.string "챔피언을 노리는 {PLAYER}!!\p"
	.string "루네시티 체육관 관장 윤진은\n"
	.string "물타입 포켓몬을 사용한다!!\p"
	.string "그리고 윤진이 있는 장소까지\n"
	.string "도달하기 위해서는 얼음 바닥을\l"
	.string "얼음 바닥을 요령껏 건널 필요가 있지...\p"
	.string "미안해! 너에게 알려\n"
	.string "줄 수 있는 건 여기까지야...!\p"
	.string "나머지는 스스로 힘내보라고!$"

SootopolisCity_Gym_1F_Text_18E9C9:: @ 818E9C9
	.string "호연에서 가장 강하다고 알려져 있는\n"
	.string "윤진까지 이겨버렸군!!\p"
	.string "좋아 너의\n"
	.string "트레이너카드를 보도록!\p"
	.string "모든 배지가 모였다면\n"
	.string "이제 드디어\n"
	.string "포켓몬리그에 도전할 수 있다!$"

SootopolisCity_Gym_B1F_Text_18EA87:: @ 818EA87
	.string "체육관 관장인 윤진님이 가르쳐주신\n"
	.string "화려한 테크닉을 보여주겠어!$"

SootopolisCity_Gym_B1F_Text_18EACF:: @ 818EACF
	.string "윤진님... 죄송해요...$"

SootopolisCity_Gym_B1F_Text_18EAED:: @ 818EAED
	.string "모든 바닥에 금이 가게 하면\n"
	.string "무슨 일이 일어날까?$"

SootopolisCity_Gym_B1F_Text_18EB22:: @ 818EB22
	.string "모처럼 여기까지 왔는데 미안해\n"
	.string "아마 나한테 질 거니까\p"
	.string "윤진님을 만날 수 없을 거야!$"

SootopolisCity_Gym_B1F_Text_18EB81:: @ 818EB81
	.string "강하잖아!!\n"
	.string "귀여운 모습에 속았어!$"

SootopolisCity_Gym_B1F_Text_18EBB1:: @ 818EBB1
	.string "너라면 윤진님과 승부해도\n"
	.string "한 방에 날아가지 않을 거야$"

SootopolisCity_Gym_B1F_Text_18EBFA:: @ 818EBFA
	.string "윤진님이 배틀하는 모습...\p"
	.string "그 아름다움에 마음을 빼앗겨\n"
	.string "저도 포켓몬 승부를 시작했어요$"

SootopolisCity_Gym_B1F_Text_18EC5E:: @ 818EC5E
	.string "아름다운 모습에\n"
	.string "지고 말았어요...$"

SootopolisCity_Gym_B1F_Text_18EC92:: @ 818EC92
	.string "당신의 배틀하는 모습도\n"
	.string "정말 멋져요\p"
	.string "아아...!\n"
	.string "포켓몬을 만나게 돼서 정말 행복해요$"

SootopolisCity_Gym_B1F_Text_18ECEB:: @ 818ECEB
	.string "내가 승부란 게 얼마나 무서운 건지\n"
	.string "제대로 가르쳐 줄게$"

SootopolisCity_Gym_B1F_Text_18ED18:: @ 818ED18
	.string "뭐야...\n"
	.string "강하잖아$"

SootopolisCity_Gym_B1F_Text_18ED2B:: @ 818ED2B
	.string "좋은 걸 가르쳐 줄게\p"
	.string "윤진님을 만나고 싶으면\n"
	.string "모든 바닥을 한 번씩\l"
	.string "밟으면서 가면 돼$"

SootopolisCity_Gym_B1F_Text_18ED91:: @ 818ED91
	.string "호연지방에서 가장\n"
	.string "레벨이 높은 포켓몬체육관\p"
	.string "바로 이 루네시티 체육관이야!$"

SootopolisCity_Gym_B1F_Text_18EDE8:: @ 818EDE8
	.string "이렇게 레벨이 높을 수가...$"

SootopolisCity_Gym_B1F_Text_18EE03:: @ 818EE03
	.string "레벨이 높은 체육관에 있다는 것에\n"
	.string "만족하지 않고\l"
	.string "다른 곳으로 수행을 가는 편이\l"
	.string "강해질 수 있으면서도 즐거울 것 같아$"

SootopolisCity_Gym_B1F_Text_18EE96:: @ 818EE96
	.string "윤진님과 함께\n"
	.string "포켓몬을 단련시키고 있어\p"
	.string "간단하게 쓰러뜨릴 수\n"
	.string "있을 거라고 생각하지 마$"

SootopolisCity_Gym_B1F_Text_18EEDC:: @ 818EEDC
	.string "쓰러졌다...$"

SootopolisCity_Gym_B1F_Text_18EEF7:: @ 818EEF7
	.string "넌 소질이 있는 것 같아\n"
	.string "여기서 같이 포켓몬을\l"
	.string "단련시키지 않을래?$"

SootopolisCity_Gym_B1F_Text_18EF39:: @ 818EF39
	.string "얼음 위에서 일필휘지!\p"
	.string "그걸 할 수 있는 트레이너는\n"
	.string "엘레강트하고 아름답지요!$"

SootopolisCity_Gym_B1F_Text_18EFB8:: @ 818EFB8
	.string "잠깐만요-?!$"

SootopolisCity_Gym_B1F_Text_18EFCA:: @ 818EFCA
	.string "당연한 말이지만\n"
	.string "포켓몬 배틀의 실력은\l"
	.string "나이와는 전혀 상관없어요$"

SootopolisCity_Gym_B1F_Text_18F037:: @ 818F037
	.string "포켓몬과 함께 있으면\n"
	.string "눈 깜짝할 사이에 시간이 가버려요!$"

SootopolisCity_Gym_B1F_Text_18F07F:: @ 818F07F
	.string "앗!$"

SootopolisCity_Gym_B1F_Text_18F085:: @ 818F085
	.string "승부에 져버린 것도\n"
	.string "눈 깜짝할 새에\l"
	.string "잊어버리고 싶어요...$"

SootopolisCity_Gym_1F_Text_18F0CA:: @ 818F0CA
	.string "그럼 다시 한 번 내 소개를 하지\p"
	.string "난 윤진\n"
	.string "이 루네시티의 체육관 관장\p"
	.string "뭐랄까 너의 분위기가\n"
	.string "조금 변한 거 같은...\p"
	.string "그런 느낌이 드는군\p"
	.string "각성의 사당에서 무슨 일이 있었는지\n"
	.string "네가 무엇을 해왔는지 지금부터\l"
	.string "펼쳐질 승부로 알게 되겠지\p"
	.string "자 그럼 한번 확인해볼까\n"
	.string "너와 포켓몬의 힘을\p"
	.string "그리고 확실하게 보여주도록 하지\n"
	.string "나와 포켓몬에 의한\l"
	.string "물의 일루전을!$"

SootopolisCity_Gym_1F_Text_18F282:: @ 818F282
	.string "굉장해\p"
	.string "넌 정말 굉장한\n"
	.string "포켓몬 트레이너다\p"
	.string "그런 너와 너의 포켓몬을\n"
	.string "만나게 된 걸 기쁘게 생각해\p"
	.string "이 레인배지는\n"
	.string "네가 받기에 적합한 것 같군\l"
	.string "자 받아$"

SootopolisCity_Gym_1F_Text_18F342:: @ 818F342
	.string "{PLAYER}{K_EUNNEUN} 윤진에게\n"
	.string "레인배지를 받았다!$"

SootopolisCity_Gym_1F_Text_18F36B:: @ 818F36B
	.string "레인배지를 가지고 있으면\n"
	.string "모든 포켓몬이\l"
	.string "순순히 네 말을 따르게 되지\p"
	.string "비전기술 폭포오르기를 사용해\n"
	.string "세차게 흐르는 폭포조차도\l"
	.string "올라갈 수 있게 해줄 거야\p"
	.string "그리고 이건 나와의 승부를\n"
	.string "잊지 않도록 주는 거다...$"

SootopolisCity_Gym_1F_Text_18F466:: @ 818F466
	.string "너에게 넘겨준 그 기술머신의\n"
	.string "내용물은 물의파동\p"
	.string "쓰면 가끔씩 초음파로\n"
	.string "상대를 혼란시키지$"

SootopolisCity_Gym_1F_Text_18F4D7:: @ 818F4D7
	.string "호연에서 모을 수 있는\n"
	.string "모든 체육관 배지를 손에 넣은\l"
	.string "트레이너가 가야 할 장소\p"
	.string "그것이 바로 포켓몬리그\p"
	.string "포켓몬리그에 가려면\n"
	.string "호연지방 끝에 있는\l"
	.string "그랜드시티라고 불리는 섬으로\l"
	.string "가면 될 거야$"

SootopolisCity_Gym_1F_Text_18F5B4:: @ 818F5B4
	.string "호연에서 모을 수 있는\n"
	.string "체육관 배지는 앞으로 하나\p"
	.string "네가 포켓몬리그에 도전할 거라면\n"
	.string "검방울시티의 포켓몬체육관에서\l"
	.string "남은 배지를 손에 넣어야 할 거야$"

SootopolisCity_Gym_1F_Text_18F649:: @ 818F649
	.string "루네시티 포켓몬체육관$"

SootopolisCity_Gym_1F_Text_18F665:: @ 818F665
	.string "루네시티 포켓몬체육관\p"
	.string "체육관 관장 윤진\n"
	.string "인정 트레이너!\l"
	.string "{PLAYER}$"
