SSTidalLowerDeck_Text_1993C1:: @ 81993C1
	.string "이렇게 넓은 곳을\n"
	.string "언제 다 청소하지?! 이제 질렸어!\l"
	.string "잠깐 승부나 하자고!$"

SSTidalLowerDeck_Text_19941A:: @ 819941A
	.string "아우야! 져버렸다!$"

SSTidalLowerDeck_Text_19942E:: @ 819942E
	.string "우리들은 청소브라더스!\p"
	.string "형은 세제를 마구 뿌리고-\n"
	.string "동생은 빡빡 닦는다-$"

SSTidalLowerDeck_Text_199491:: @ 8199491
	.string "이렇게 넓으니까\n"
	.string "뱃바닥에서 포켓몬 승부를 해도\l"
	.string "괜찮겠지?$"

SSTidalLowerDeck_Text_1994F7:: @ 81994F7
	.string "형님! 져버렸습니다!$"

SSTidalLowerDeck_Text_199508:: @ 8199508
	.string "우리들은 청소브라더스!\p"
	.string "형은 세제를 마구 뿌리고-\n"
	.string "동생은 빡빡 닦는다-$"
