VerdanturfTown_Text_16CAEB:: @ 816CAEB
	.string "우리 아빠가 말씀하셨어\p"
	.string "이 터널에는 큰- 소리에\n"
	.string "반응해서 소란 피우는\l"
	.string "겁쟁이 포켓몬이 가득하대!\p"
	.string "그래서 개발 공사를 그만뒀는데\n"
	.string "어떤 남자가 혼자서\l"
	.string "터널을 파려고 한다나 봐!$"

VerdanturfTown_Text_16CBCE:: @ 816CBCE
	.string "사랑하는 사람을 위해\n"
	.string "동굴을 팠던 사람이 있어!\p"
	.string "왠지 굉-장해!$"

VerdanturfTown_Text_16CC24:: @ 816CC24
	.string "바람의 방향 때문에 이 마을에는\n"
	.string "화산재가 날아오지 않아!\p"
	.string "공기가 맑은 이 마을에서 살면\n"
	.string "몸이 튼튼하지 않은 사람도\l"
	.string "반드시 건강해질 거야!$"

VerdanturfTown_Text_16CCD0:: @ 816CCD0
	.string "내 포켓몬 귀여움에\n"
	.string "조금 자신감이 생겨서 말이야\p"
	.string "콘테스트 데뷔에 내보내려고\n"
	.string "이 마을에 온 거야!$"

VerdanturfTown_Text_16CD4D:: @ 816CD4D
	.string "프렌들리숍 옆에\n"
	.string "동굴이 있지?\p"
	.string "안을 막고 있는 바위를 부수고\n"
	.string "지나갈 수 있게 하려고 노력하는\l"
	.string "사람이 있다고 하더라!\p"
	.string "잘 됐으면 해...\n"
	.string "금탄도시에도 가기 쉬워지니까!$"

VerdanturfTown_Text_16CE30:: @ 816CE30
	.string "프렌들리숍 옆의 동굴 말이야\n"
	.string "지나갈 수 있게 되었지?\p"
	.string "금탄도시까지 데봉의 신제품을\n"
	.string "사러 가기 쉬워져서 기뻐!$"

VerdanturfTown_Text_16CEC0:: @ 816CEC0
	.string "여기는 잔디마을\n"
	.string "풀 내음의 바람이 부는 고원$"

VerdanturfTown_Text_16CF0D:: @ 816CF0D
	.string "“미진의 집”$"

VerdanturfTown_Text_16CF1B:: @ 816CF1B
	.string "포켓몬 콘테스트 노말랭크 접수처\n"
	.string "모여라! 포켓몬 트레이너!$"

VerdanturfTown_Text_16CF6D:: @ 816CF6D
	.string "금탄도시와 잔디마을을 연결하는\n"
	.string "“금잔터널”\p"
	.string "개통 공사는 중단되었습니다$"
