VerdanturfTown_ContestHall_Text_177FB4:: @ 8177FB4
	.string "넌 무슨 콘테스트에 나갈 거야?\n"
	.string "하나 어드바이스 해줄게!\p"
	.string "예를 들어 귀여움콘테스트에서는\n"
	.string "1차 심사에서 귀여움만이\l"
	.string "평가되는 게 아닌 것 같아\p"
	.string "키우는 방법을 구분해 두는 게 좋아!$"

VerdanturfTown_ContestHall_Text_178091:: @ 8178091
	.string "포켓몬이 귀여워지도록\n"
	.string "키우고 있는데\p"
	.string "콘테스트에서는 귀여운 걸로도\n"
	.string "경쟁할 수가 있구나!\p"
	.string "소중하게 키워서 다행이다...$"

VerdanturfTown_ContestHall_Text_178120:: @ 8178120
	.string "내 포켓몬...\p"
	.string "엄청나게 근사하고\n"
	.string "강인하고 아름답고\l"
	.string "귀엽고 슬기로운데 말야\p"
	.string "이렇게 된 이상 모든 콘테스트에서\n"
	.string "닥치는 대로 우승을 노릴 거야!$"

VerdanturfTown_ContestHall_Text_1781A5:: @ 81781A5
	.string "포켓몬 콘테스트\n"
	.string "노말랭크 스테이지!$"
