VerdanturfTown_ContestLobby_Text_177D6C:: @ 8177D6C
	.string "거기 입구에서부터 들어와서\n"
	.string "콘테스트 회장을 둘러보고 있었어\l"
	.string "저렇게 큰 스테이지에서\l"
	.string "서게 된다니 긴장된다!$"

VerdanturfTown_ContestLobby_Text_177DEC:: @ 8177DEC
	.string "나의 포켓몬을 향한 마음...\n"
	.string "그것이 바로 헤롱헤롱이야...\p"
	.string "어머 이상한 모습을 들켰네\p"
	.string "뭐 좋아\n"
	.string "너 콘테스트에 나갈 거면\l"
	.string "이 기술머신은 어때?$"

VerdanturfTown_ContestLobby_Text_177E98:: @ 8177E98
	.string "포켓몬의 나를 향한 마음도...\n"
	.string "역시 헤롱헤롱인 게 틀림없어!$"

VerdanturfTown_ContestLobby_Text_177ECD:: @ 8177ECD
	.string "넌 무슨 콘테스트에 나간다고?\p"
	.string "만약 근사함콘테스트에 나갈 거라면\n"
	.string "근사한 포켓몬이 좋을 거야!\p"
	.string "콘테스트에 알맞은 포켓몬에게\n"
	.string "알맞은 기술을 배우게 해서 엔트리!\l"
	.string "이건 상식이라구!$"
