VerdanturfTown_Mart_Text_1781C9:: @ 81781C9
	.string "포켓몬 승부에\n"
	.string "스페셜업은 빠질 수 없지!\p"
	.string "배틀 때만이라고는 해도\n"
	.string "기술의 위력이 올라간다고!$"

VerdanturfTown_Mart_Text_178240:: @ 8178240
	.string "콘테스트에서 이길 수 있는\n"
	.string "도구는 안 파네요...\p"
	.string "역시 평소부터\n"
	.string "소중하게 키워야 하는 거군요$"

VerdanturfTown_Mart_Text_1782C0:: @ 81782C0
	.string "잔디마을에서밖에 살 수 없는\n"
	.string "네스트볼은\l"
	.string "약한 포켓몬일수록 잡기 쉬워져$"
