VictoryRoad_B1F_Text_197CE9:: @ 8197CE9
	.string "포켓몬리그에\n"
	.string "가까워지고 있다고 생각하니\l"
	.string "왠지 가슴이 두근거리기 시작했어...$"

VictoryRoad_B1F_Text_197D42:: @ 8197D42
	.string "아무것도 할 수 없었어...$"

VictoryRoad_B1F_Text_197D5B:: @ 8197D5B
	.string "포켓몬리그가 멀어졌어...\n"
	.string "완전 김빠진다...$"

VictoryRoad_B1F_Text_197D98:: @ 8197D98
	.string "포켓몬리그를 이겨나가기 위해서는\n"
	.string "포켓몬을 향한 신뢰가 필요해$"

VictoryRoad_B1F_Text_197DE8:: @ 8197DE8
	.string "아주 돈독한 신뢰 관계구나!$"

VictoryRoad_B1F_Text_197E13:: @ 8197E13
	.string "언제나 함께 있는 걸로\n"
	.string "포켓몬과 트레이너 사이에\l"
	.string "신뢰 관계가 형성되는 거야$"

VictoryRoad_B1F_Text_197E5D:: @ 8197E5D
	.string "여기는 골인 지점이 아니야\n"
	.string "포켓몬리그로 가는 중간 지점이지!$"

VictoryRoad_B1F_Text_197EA6:: @ 8197EA6
	.string "그래! 바로 그거야!$"

VictoryRoad_B1F_Text_197EB6:: @ 8197EB6
	.string "너라면 분명히 괜찮을 거야!\n"
	.string "포켓몬도 의욕이 넘치니까!$"
