VictoryRoad_B2F_Text_197EF2:: @ 8197EF2
	.string "가족들끼리\n"
	.string "포켓몬 수행을 했었어!\l"
	.string "누구에게도 지지 않는다고!$"

VictoryRoad_B2F_Text_197F46:: @ 8197F46
	.string "우리 가족보다 강하다고?!\n"
	.string "그런 게 가능한 건가?!$"

VictoryRoad_B2F_Text_197F71:: @ 8197F71
	.string "가족 중에서 제일 강했던 내가...\n"
	.string "지금까지 누구에게도\l"
	.string "지지 않았던 내가...\p"
	.string "하지만 이제 자신이 없어졌어\n"
	.string "집으로 돌아갈까...?$"

VictoryRoad_B2F_Text_197FE5:: @ 8197FE5
	.string "강한 꼬맹이가 있다는 소문이 있더군!\n"
	.string "그게 바로 넌가?$"

VictoryRoad_B2F_Text_19802B:: @ 819802B
	.string "진짜로 강하군!$"

VictoryRoad_B2F_Text_198047:: @ 8198047
	.string "내가 들은 소문에 의하면\n"
	.string "그 강한 꼬맹이는\l"
	.string "등화도시 출신이라고 하더군!$"

VictoryRoad_B2F_Text_198089:: @ 8198089
	.string "이제 슬슬 지치기 시작했겠지?$"

VictoryRoad_B2F_Text_1980AD:: @ 81980AD
	.string "하나도 안 지쳐 있잖아!$"

VictoryRoad_B2F_Text_1980C8:: @ 81980C8
	.string "이 챔피언로드도\n"
	.string "포켓몬리그도 아주 긴 여정이지!\l"
	.string "체력에 주의해!$"

VictoryRoad_B2F_Text_198121:: @ 8198121
	.string "체육관 배지를 많이 가지고 있다고\n"
	.string "방심하지 마 뛰는 사람 위에\l"
	.string "나는 사람이 있으니까!$"

VictoryRoad_B2F_Text_1981A3:: @ 81981A3
	.string "바로 네가 나는 사람이었구나!$"

VictoryRoad_B2F_Text_1981BA:: @ 81981BA
	.string "내가 모은 체육관 배지를 보면서\n"
	.string "지금까지 승부했던\l"
	.string "트레이너를 떠올려$"
