VictoryRoad_1F_Text_19782B:: @ 819782B //JP: 17B408
	.string "민진: 앗! {PLAYER}님!\p"
	.string "제가 이런 곳에 있으니까\n"
	.string "놀랐죠!\p"
	.string "그때의 약속...\n"
	.string "제대로 지켜줘서 고마워요!\p"
	.string "제가 여기까지 올 수 있었던 건\n"
	.string "{PLAYER}님 덕분이에요!\p"
	.string "...그치만!\n"
	.string "전 이제 지지 않아요\p"
	.string "저에게 힘과 용기를 준\n"
	.string "포켓몬을 위해서라도 이기겠어요!\p"
	.string "그럼... 갑니다!$"

VictoryRoad_1F_Text_197943:: @ 8197943
	.string "우와!\n"
	.string "역시 {PLAYER}님은 강하네요!$"

VictoryRoad_1F_Text_197967:: @ 8197967
	.string "민진: ...이번에는\n"
	.string "{PLAYER}님한테 이기지 못했지만\l"
	.string "언젠가 반드시 뒤쫓아 갈 거예요!$"

VictoryRoad_1F_Text_1979BA:: @ 81979BA
	.string "민진: 앗! {PLAYER}님!\p"
	.string "저 그때보다 강해졌어요!\n"
	.string "그걸 {PLAYER}님에게\l"
	.string "보여주고 싶어요!\p"
	.string "그럼... 갑니다!$"

VictoryRoad_1F_Text_197A23:: @ 8197A23
	.string "우와!\n"
	.string "역시 {PLAYER}님은 강하네요!$"

VictoryRoad_1F_Text_197A47:: @ 8197A47
	.string "민진: ...이번에는\n"
	.string "{PLAYER}님한테 이기지 못했지만\l"
	.string "언젠가 반드시 뒤쫓아 가서...\p"
	.string "포켓몬리그에 도전할 거예요!$"

VictoryRoad_1F_Text_197AD1:: @ 8197AD1
	.string "여기까지는 어떻게든\n"
	.string "올 수 있었겠지만\l"
	.string "앞으로가 엄청 멀어...$"

VictoryRoad_1F_Text_197B1A:: @ 8197B1A
	.string "여기서 끝난 건가...$"

VictoryRoad_1F_Text_197B36:: @ 8197B36
	.string "여기까지 왔으면\n"
	.string "기세를 몰아서 챔피언이 되라고!\l"
	.string "너라면 할 수 있을 거야!$"

VictoryRoad_1F_Text_197B99:: @ 8197B99
	.string "여기까지 왔는데\n"
	.string "이제 와서 진다는 건 말이 안 되지!$"

VictoryRoad_1F_Text_197BE1:: @ 8197BE1
	.string "설마...\n"
	.string "진 건가...?$"

VictoryRoad_1F_Text_197BF7:: @ 8197BF7
	.string "여기서 졌다...\p"
	.string "졌다는 것은 아직 챔피언이 될\n"
	.string "자격이 없다는 건가...$"

VictoryRoad_1F_Text_197C45:: @ 8197C45
	.string "이 끝없이 험한 길이야말로\n"
	.string "바로 챔피언으로 향하는 길인 거야!$"

VictoryRoad_1F_Text_197C8D:: @ 8197C8D
	.string "멋진 실력이야...$"

VictoryRoad_1F_Text_197CAF:: @ 8197CAF
	.string "너에겐 챔피언이 될 가능성이\n"
	.string "있는 것 같구나$"
