#include "global.h"
#include "strings.h"

// placeholder strings
const u8 gExpandedPlaceholder_Empty[] = _("");
const u8 gExpandedPlaceholder_Kun[] = _("군");
const u8 gExpandedPlaceholder_Chan[] = _("양");
const u8 gExpandedPlaceholder_Sapphire[] = _("사파이어");
const u8 gExpandedPlaceholder_Ruby[] = _("루비");
const u8 gExpandedPlaceholder_Aqua[] = _("아쿠아");
const u8 gExpandedPlaceholder_Magma[] = _("마그마");
const u8 gExpandedPlaceholder_Archie[] = _("아강");
const u8 gExpandedPlaceholder_Maxie[] = _("마적");
const u8 gExpandedPlaceholder_Kyogre[] = _("가이오가");
const u8 gExpandedPlaceholder_Groudon[] = _("그란돈");
const u8 gExpandedPlaceholder_Brendan[] = _("휘웅");
const u8 gExpandedPlaceholder_May[] = _("봄이");
const u8 gExpandedPlaceholder_Brother[] = _("형");
const u8 gExpandedPlaceholder_Sister[] = _("누나");
const u8 gExpandedPlaceholder_Brother2[] = _("오빠");
const u8 gExpandedPlaceholder_Sister2[] = _("언니");

// system text
const u8 gSystemText_Egg[] = _("알");
const u8 gSystemText_Pokemon2[] = _("포켓몬");

// main menu text
const u8 gMainMenuString_NewGame[] = _("새로운 모험을 시작한다");
const u8 gMainMenuString_Continue[] = _("모험을 계속한다");
const u8 gMainMenuString_Option[] = _("설정을 바꾼다");
const u8 gMainMenuString_MysteryEvents[] = _("이상한 소포");

// system text 2
const u8 SystemText_UpdatingSaveExternal[] = _("외부 데이터를 리포트에 갱신합니다\n잠시만 기다려 주십시오");
const u8 SystemText_SaveUpdated[] = _("리포트가 갱신되었습니다!");
const u8 SystemText_SaveUpdatedExchangeBackup[] = _("리포트가 갱신되었습니다!\p더 이상 리포트를 쓸 수 없으므로\n백업 카트리지를\l교환해주시기 바랍니다!\p자세한 내용은\n닌텐도 서비스 센터로\l문의해주세요");
const u8 SystemText_SaveNotUpdated[] = _("리포트 갱신에\n실패했습니다!\p백업 카트리지를\n교환해주시기 바랍니다!\p자세한 내용은\n닌텐도 서비스 센터로\l문의해주세요");

// save file text
const u8 gSaveFileCorruptMessage[] = _("리포트가 정확히 쓰여있지 않기 때문에\n전에 작성한 리포트를 읽겠습니다!");
const u8 gSaveFileDeletedMessage[] = _("리포트의 내용이 사라졌다!");

// system text 3
const u8 gBoardNotInstalledMessage[] = _("1M 서브보드가 꽂혀 있지 않습니다!");
const u8 gBatteryDryMessage[] = _("전지가 다 되어서\n시계가 움직이지 않습니다\p시계와 관련된 이벤트는\n일어나지 않지만\l게임은 계속 플레이할 수 있습니다");

// main menu text 2
const u8 gMainMenuString_Player[] = _("주인공");
const u8 gMainMenuString_Pokedex[] = _("포켓몬 도감");
const u8 gMainMenuString_Time[] = _("플레이 시간");
const u8 gMainMenuString_Badges[] = _("가지고 있는 배지");

// birch text
const u8 gBirchText_Boy[] = _("남자");
const u8 gBirchText_Girl[] = _("여자");
const u8 gBirchText_NewName[] = _("스스로 결정한다!");

#ifdef SAPPHIRE
const u8 gDefaultBoyName1[] = _("해호"); //SEAN
#else
const u8 gDefaultBoyName1[] = _("대호"); //LANDON
#endif
const u8 gDefaultBoyName2[] = _("영성"); //TERRY
const u8 gDefaultBoyName3[] = _("홍준"); //SETH
const u8 gDefaultBoyName4[] = _("민혁"); //TOM

#ifdef SAPPHIRE
const u8 gDefaultGirlName1[] = _("해은"); //MARINA
#else
const u8 gDefaultGirlName1[] = _("대은"); //TERRA
#endif
const u8 gDefaultGirlName2[] = _("나영"); //KIMMY
const u8 gDefaultGirlName3[] = _("연지"); //NICOLA
const u8 gDefaultGirlName4[] = _("규희"); //SARA

const u8 gSystemText_IntroWeCall[] = _("포켓몬스터\n...즉 포켓몬");
const u8 gSystemText_NewPara[] = _("\p");

const u8 gDexText_UnknownPoke[] = _("           ?????포켓몬");
const u8 gDexText_UnknownHeight[] = _("{CLEAR_TO 3}???.?m");
const u8 gDexText_UnknownWeight[] = _("{CLEAR_TO 3}???.?kg$"); // extra terminator?
const u8 gDexText_CryOf[] = _("{CLEAR_TO 2}울음소리$"); // extra terminator?
const u8 gDexText_SizeComparedTo[] = _("{K_WAGWA} {PLAYER}의 크기 비교");
const u8 gDexText_RegisterComplete[] = _("포켓몬 도감 등록 완료!");
const u8 gDexText_Searching[] = _("검색하고 있습니다...");
const u8 gDexText_SearchComplete[] = _("검색이 완료되었습니다!");
const u8 gDexText_NoMatching[] = _("해당하는 포켓몬이 없습니다...");

const u8 DexText_SearchForPoke[] = _("조건을 지정해서\n포켓몬을 검색합니다");
const u8 DexText_SwitchDex[] = _("도감리스트의 순서를 변경합니다");
const u8 DexText_ReturnToDex[] = _("도감으로 돌아갑니다");
const u8 DexText_SelectDexMode[] = _("도감 모드를 지정합니다");
const u8 DexText_SelectDexList[] = _("도감의 순서를 지정합니다");
const u8 DexText_ListByABC[] = _("이름의 첫 글자를 지정합니다\n /발견한 포켓몬만");
const u8 DexText_ListByColor[] = _("몸의 색을 지정합니다\n /발견한 포켓몬만");
const u8 DexText_ListByType[] = _("타입을 지정합니다\n /잡은 포켓몬만");
const u8 DexText_ExecuteSearchSwitch[] = _("검색 또는 변경을 실행합니다");
const u8 DexText_HoennDex[] = _("호연도감");
const u8 DexText_NationalDex[] = _("전국도감");
const u8 DexText_NumericalMode[] = _("번호 순");
const u8 DexText_ABCMode[] = _("가나다 순");
const u8 DexText_HeaviestMode[] = _("무거운 순");
const u8 DexText_LightestMode[] = _("가벼운 순");
const u8 DexText_TallestMode[] = _("키가 큰 순");
const u8 DexText_SmallestMode[] = _("키가 작은 순");
const u8 DexText_ABC[] = _("ㄱㄴ");
const u8 DexText_DEF[] = _("ㄷㄹ");
const u8 DexText_GHI[] = _("ㅁㅂ");
const u8 DexText_JKL[] = _("ㅅㅇ");
const u8 DexText_MNO[] = _("ㅈㅊ");
const u8 DexText_PQR[] = _("ㅋㅌ");
const u8 DexText_STU[] = _("ㅍㅎ");
const u8 DexText_VWX[] = _("");    //dummy로 처리
const u8 DexText_YZ[] = _("");     //dummy로 처리
const u8 DexText_Red[] = _("빨간색");
const u8 DexText_Blue[] = _("파란색");
const u8 DexText_Yellow[] = _("노란색");
const u8 DexText_Green[] = _("초록색");
const u8 DexText_Black[] = _("검정색");
const u8 DexText_Brown[] = _("갈색");
const u8 DexText_Purple[] = _("보라색");
const u8 DexText_Gray[] = _("회색");
const u8 DexText_White[] = _("하얀색");
const u8 DexText_Pink[] = _("분홍색");
const u8 DexText_HoennDex2[] = _("호연지방 포켓몬 도감");
const u8 DexText_NationalDex2[] = _("전국 포켓몬 도감");
const u8 DexText_ListByNumber[] = _("포켓몬을\n번호 순으로 표시합니다");
const u8 DexText_ListByABC2[] = _("발견한 포켓몬의 이름을\n가나다 순으로 표시합니다");
const u8 DexText_ListByHeavyToLightest[] = _("잡은 포켓몬을\n무거운 순으로 표시합니다");
const u8 DexText_ListByLightToHeaviest[] = _("잡은 포켓몬을\n가벼운 순으로 표시합니다");
const u8 DexText_ListByTallToSmallest[] = _("잡은 포켓몬을\n키가 큰 순으로 표시합니다");
const u8 DexText_ListBySmallToTallest[] = _("잡은 포켓몬을\n키가 작은 순으로 표시합니다");
const u8 DexText_Terminator5[] = _("");
const u8 DexText_DontSpecify[] = _("지정하지 않는다");
const u8 DexText_None[] = _("없음");
const u8 DexText_RightPointingTriangle[] = _("▶"); // right pointing triangle
const u8 DexText_Terminator6[] = _(" ");

const u8 gMenuText_WelcomeToHOFAndDexRating[] = _("전당등록을 축하합니다!$발견한 포켓몬 {STR_VAR_1}!\n잡은 포켓몬 {STR_VAR_2}!\p털보박사의\n포켓몬 도감 평가!\p털보박사: 어디 보자\p");
const u8 gMenuText_HOFSaving[] = _("지금까지의 리포트를 작성하고 있습니다!\n전원을 끄지 마십시오");
const u8 gMenuText_HOFCorrupt[] = _("전당등록의 기록이 손상되었습니다!");
const u8 gMenuText_HOFNumber[] = _("제"); // 뒤에 띄어쓰기 없이 바로 숫자변수 n이 출력되므로 해당 리소스를 찾아서 n회 전당등록이 되도록 해주세요
const u8 gMenuText_HOFCongratulations[] = _("리그 챔피언! 축하합니다!");

const u8 gOtherText_Number2[] = _("No. ");
const u8 gOtherText_Level3[] = _("Lv. ");
const u8 gOtherText_IDNumber[] = _("IDNo. /");
const u8 gOtherText_Name[] = _("이름 /");
const u8 gOtherText_IDNumber2[] = _("IDNo. /");
const u8 gOtherText_BirchInTrouble[] = _("{HIGHLIGHT WHITE2}{COLOR DARK_GREY}털보박사님이 위험하다!\n포켓몬을 꺼내서 도와주자!");
const u8 gOtherText_DoYouChoosePoke[] = _("{HIGHLIGHT WHITE2}{COLOR DARK_GREY}이 포켓몬으로 결정하겠습니까?");
const u8 gOtherText_Poke[] = _("포켓몬");

const u8 gSystemText_SaveErrorExchangeBackup[] = _("리포트를 작성할 수 없습니다\p백업 카트리지를 교체하여 주십시오");
const u8 gOtherText_FlyToWhere[] = _("어디로 날아갈까요?");

const u8 OtherText_Use[] = _("쓴다");
const u8 OtherText_Toss[] = _("버린다");
const u8 OtherText_Register[] = _("등록");
const u8 OtherText_Give2[] = _("건네준다");
const u8 OtherText_CheckTag[] = _("태그확인");
const u8 OtherText_Confirm[] = _("결정");
const u8 gOtherText_Walk[] = _("내린다");

const u8 gUnknownText_Exit[] = _("되돌아간다");
const u8 gOtherText_CancelNoTerminator[] = _("그만둔다");
const u8 gOtherText_CancelNoTerminator2[] = _("필요없다");
const u8 gOtherText_CancelWithTerminator[] = _("$그만둔다"); // with terminator at beginning?

const u8 OtherText_Item[] = _("지닌물건");
const u8 OtherText_Mail[] = _("메일");
const u8 OtherText_Take2[] = _("가져온다");
const u8 OtherText_Store[] = _("맡긴다");

const u8 gOtherText_Check[] = _("본다");
const u8 gOtherText_None[] = _("없음");

const u8 gOtherText_ThreeQuestions2[] = _("???");

const u8 gOtherText_FiveQuestionsAndSlash[] = _("?????$/");

const u8 gOtherText_OneDash[] = _("-");
const u8 gOtherText_TwoDashes[] = _("--");
const u8 gOtherText_ThreeDashes2[] = _("---");
const u8 gOtherText_MaleSymbol2[] = _("♂");
const u8 gOtherText_FemaleSymbolAndLv[] = _("♀$Lv.");
const u8 gOtherText_TallPlusAndRightArrow[] = _("{TALL_PLUS}${RIGHT_ARROW}");
const u8 gMenuText_GoBackToPrev[] = _("이전으로 돌아갑니다!");
const u8 gOtherText_WhatWillYouDo[] = _("무엇을 하겠습니까?");

const u8 gOtherText_xString1[] = _("×{STR_VAR_1}");
const u8 gOtherText_Berry2[] = _("열매");
const u8 gOtherText_Coins2[] = _("{STR_VAR_1}개");
const u8 gOtherText_CloseBag[] = _("가방을 닫는다");

const u8 OtherText_TheField3[] = _("필드로");
const u8 OtherText_TheBattle[] = _("배틀로");
const u8 OtherText_ThePokeList[] = _("포켓몬 리스트로");
const u8 OtherText_TheShop[] = _("숍으로");
const u8 OtherText_TheField[] = _("필드로");
const u8 OtherText_TheField2[] = _("필드로");
const u8 OtherText_ThePC[] = _("PC로");

const u8 *const gUnknown_0840E740[7] =
{
    OtherText_TheField3,
    OtherText_TheBattle,
    OtherText_ThePokeList,
    OtherText_TheShop,
    OtherText_TheField,
    OtherText_TheField2,
    OtherText_ThePC,
};

const u8 gOtherText_ReturnTo[] = _("돌아갑니다");
const u8 gOtherText_WhatWillYouDo2[] = _("어떻게 할까요?");
const u8 gOtherText_CantWriteMail[] = _("여기서는 메일을\n쓸 수 없습니다!");
const u8 gOtherText_NoPokemon[] = _("포켓몬이 없습니다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_SwitchWhichItem[] = _("어느 것과\n바꿀까요?");
const u8 gOtherText_CantBeHeld[] = _("{STR_VAR_1}{K_EULREUL}\n지니게 할 수 없습니다!");
const u8 gOtherText_CantBeHeldHere[] = _("여기서는 {STR_VAR_1}{K_EULREUL}\n지니게 할 수 없습니다!");
const u8 gOtherText_HowManyToDeposit[] = _("얼마나 맡기겠습니까?");
const u8 gOtherText_DepositedItems[] = _("{STR_VAR_1}{K_EULREUL}\n{STR_VAR_2}개 맡겼습니다!");
const u8 gOtherText_NoRoomForItems[] = _("더 이상\n맡길 수 없습니다!");
const u8 gOtherText_CantStoreSomeoneItem[] = _("PC에\n남이 맡긴 것은\n넣을 수 없습니다!");
const u8 gOtherText_TooImportant[] = _("이것은 매우\n소중한 것이므로\n버릴 수 없습니다!");
const u8 gOtherText_HowManyToToss[] = _("몇 개 버리겠습니까?");
const u8 gOtherText_ThrewAwayItem[] = _("{STR_VAR_1}{K_EULREUL}\n{STR_VAR_2}개 버렸습니다");
const u8 gOtherText_OkayToThrowAwayPrompt[] = _("{STR_VAR_1}{K_EULREUL}\n{STR_VAR_2}개 버려도\n괜찮겠습니까?");
const u8 gOtherText_DadsAdvice[] = _("아빠의 말...\n{PLAYER}! 이런 것은\l쓸 때가 따로 있단다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_CantGetOffBike[] = _("여기서는 탈 수 없다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_ItemfinderResponding[] = _("앗!\n기계가 반응하고 있어!\p어딘가에 도구가 묻혀있어!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_ItemfinderItemUnderfoot[] = _("기계가 발밑에\n엄청 반응하고 있어!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_NoResponse[] = _("... ... 휴우!\n...아무 반응이 없다{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_Coins3[] = _("당신의 동전: {STR_VAR_1}개{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_BootedTM[] = _("기술머신을 켰다!");
const u8 gOtherText_BootedHM[] = _("비전머신을 켰다!");
const u8 gOtherText_ContainsMove[] = _("안에는 {STR_VAR_1}{K_IGA}\n기록되어 있다!\p{STR_VAR_1}{K_EULREUL}\n포켓몬에게 배우게 하겠습니까?");
const u8 gOtherText_UsedItem[] = _("{PLAYER}{K_EUNNEUN}\n{STR_VAR_2}{K_EULREUL} 썼다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_RepelLingers[] = _("아직 전에 썼던\n스프레이의 효과가 남아 있습니다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_UsedFlute[] = _("{PLAYER}{K_EUNNEUN}\n{STR_VAR_2}{K_EULREUL} 썼다!\p포켓몬과\n마주치기 쉬워졌다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_UsedRepel[] = _("{PLAYER}{K_EUNNEUN}\n{STR_VAR_2}{K_EULREUL} 썼다!\p포켓몬과\n마주치기 힘들어졌다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_BoxIsFull[] = _("박스가 가득 찼습니다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_Size[] = _("크기");
const u8 gOtherText_Firm[] = _("경도");

const u8 gContestStatsText_Unknown1[] = _("{STR_VAR_1}.{STR_VAR_2}cm");

const u8 ContestStatsText_VerySoft[] = _("매우 부드럽다");
const u8 ContestStatsText_Soft[] = _("부드럽다");
const u8 ContestStatsText_Hard[] = _("딱딱하다");
const u8 ContestStatsText_VeryHard[] = _("매우 딱딱하다");
const u8 ContestStatsText_SuperHard[] = _("엄청나게 딱딱하다");

const u8 ContestStatsText_RedPokeBlock[] = _("빨강포켓몬스넥");
const u8 ContestStatsText_BluePokeBlock[] = _("파랑포켓몬스넥");
const u8 ContestStatsText_PinkPokeBlock[] = _("담홍포켓몬스넥");
const u8 ContestStatsText_GreenPokeBlock[] = _("초록포켓몬스넥");
const u8 ContestStatsText_YellowPokeBlock[] = _("노랑포켓몬스넥");
const u8 ContestStatsText_PurplePokeBlock[] = _("보라포켓몬스넥");
const u8 ContestStatsText_IndigoPokeBlock[] = _("남색포켓몬스넥");
const u8 ContestStatsText_BrownPokeBlock[] = _("갈색포켓몬스넥");
const u8 ContestStatsText_LiteBluePokeBlock[] = _("하늘포켓몬스넥");
const u8 ContestStatsText_OlivePokeBlock[] = _("황록포켓몬스넥");
const u8 ContestStatsText_GrayPokeBlock[] = _("회색포켓몬스넥");
const u8 ContestStatsText_BlackPokeBlock[] = _("검정포켓몬스넥");
const u8 ContestStatsText_WhitePokeBlock[] = _("하양포켓몬스넥");
const u8 ContestStatsText_GoldPokeBlock[] = _("황금포켓몬스넥");

const u8 gContestStatsText_Spicy[] = _("매운맛");
const u8 gContestStatsText_Dry[] = _("떫은맛");
const u8 gContestStatsText_Sweet[] = _("단맛");
const u8 gContestStatsText_Bitter[] = _("쓴맛");
const u8 gContestStatsText_Sour[] = _("신맛$좋은맛$부드러움"); // tasty is unused, feel might not be

const u8 gContestStatsText_StowCase[] = _("케이스를 닫는다");
const u8 gContestStatsText_ThrowAwayPrompt[] = _("{STR_VAR_1}{K_EULREUL}\n버려도 괜찮겠습니까?");
const u8 gContestStatsText_WasThrownAway[] = _("{STR_VAR_1}{K_EULREUL}\n버렸습니다");
const u8 gContestStatsText_NormallyAte[] = _("{STR_VAR_1}{K_EUNNEUN} {STR_VAR_2}{K_EULREUL}\n먹었다!{PAUSE_UNTIL_PRESS}");
const u8 gContestStatsText_HappilyAte[] = _("{STR_VAR_1}{K_EUNNEUN} {STR_VAR_2}{K_EULREUL}\n기뻐하며 먹었다!{PAUSE_UNTIL_PRESS}");
const u8 gContestStatsText_DisdainfullyAte[] = _("{STR_VAR_1}{K_EUNNEUN} {STR_VAR_2}{K_EULREUL}\n싫어하며 먹었다!{PAUSE_UNTIL_PRESS}");

const u8 MartText_Buy[] = _("사러 왔다");
const u8 MartText_Sell[] = _("팔러 왔다");
const u8 MartText_Quit2[] = _("아무것도 아닙니다");

const u8 gOtherText_QuitShopping[] = _("쇼핑을 그만둡니다");

const u8 gOtherText_HowManyYouWant[] = _("{STR_VAR_1}{K_EULREUL}\n몇 개 구입하시겠습니까?");
const u8 gOtherText_ThatWillBe[] = _("{STR_VAR_1} {STR_VAR_2}개로군요\n총 {STR_VAR_3}원입니다.");
const u8 gOtherText_ThatWillBe2[] = _("{STR_VAR_1} 말이지!\n{STR_VAR_2}원인데 살 거야?"); //い だね!ｎう￥ だけど かうかい?$
const u8 gOtherText_ThatWillBe3[] = _("{STR_VAR_1} 말이죠!\n{STR_VAR_2}원인데 사실래요?"); //い ですね!ｎう￥ だけど かいますか?$
const u8 gOtherText_HereYouGo[] = _("네 여기 있습니다\n대단히 감사합니다");
const u8 gOtherText_HereYouGo2[] = _("감사합니다!\n집의 PC로 전송해 드리겠습니다");
const u8 gOtherText_HereYouGo3[] = _("감사합니다!\n집의 PC로 전송해 드리겠습니다");
const u8 gOtherText_NotEnoughMoney[] = _("돈이 부족하시군요!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_NoRoomFor[] = _("그 이상은\n가지고 다닐 수 없어요!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_SpaceForIsFull[] = _("{STR_VAR_1}{K_EUNNEUN}\n그 이상 지닐 수 없습니다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_AnythingElse[] = _("그 밖에 저희가\n뭐 도와드릴 건 없습니까?");
const u8 gOtherText_CanIHelpYou[] = _("그 밖에 뭔가 필요한가요?");
const u8 gOtherText_FreePremierBall[] = _("프레미어볼 1개를\n서비스로 드리겠습니다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_CantBuyThat[] = _("{STR_VAR_2}{K_EUNNEUN}\n파실 수 없습니다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_HowManyToSell[] = _("{STR_VAR_2}{K_EULREUL}\n몇 개 파시겠습니까?");
const u8 gOtherText_CanPay[] = _("그 물건은 {STR_VAR_1}원으로\n쳐 드리겠습니다");
const u8 gOtherText_SoldItem[] = _("{STR_VAR_2}{K_EULREUL} 건네고\n{STR_VAR_1}원을 받았다");

const u8 OtherText_Money[] = _("{STR_VAR_1}원");
const u8 OtherText_Shift[] = _("교체한다");
const u8 OtherText_SendOut[] = _("교체한다");
const u8 OtherText_Switch2[] = _("순서바꾸기");
const u8 OtherText_Summary[] = _("능력치를 본다");
const u8 OtherText_Moves[] = _("기술을 본다");
const u8 OtherText_Enter2[] = _("참가한다");
const u8 OtherText_NoEntry[] = _("참가 안 한다");
const u8 OtherText_Take[] = _("메일을 받는다");
const u8 OtherText_Read2[] = _("메일을 읽는다");

const u8 gOtherText_Hp2[] = _("체력");
const u8 gOtherText_SpAtk2[] = _("특수공격");
const u8 gOtherText_SpDef2[] = _("특수방어");
const u8 gOtherText_WontHaveAnyEffect[] = _("사용해도 효과가 없다!{PAUSE_UNTIL_PRESS}");


const u8 gOtherText_CantUseOnPoke[] = _("그 포켓몬에게는\n쓸 수 없습니다{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_CantBeSwitched[] = _("{STR_VAR_1}{K_EULREUL}\n돌아오게 할 수 없습니다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_AlreadyBattle[] = _("{STR_VAR_1}{K_EUNNEUN}\n이미 배틀에 나가 있습니다{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_AlreadySelected[] = _("{STR_VAR_1}{K_EUNNEUN} 이미\n선택되어 있습니다{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_NoEnergyLeft[] = _("{STR_VAR_1}{K_EUNNEUN} 싸우기 위한\n기력이 남아있지 않습니다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_CantSwitchPokeWithYours[] = _("{STR_VAR_1}의 포켓몬과는\n교체할 수 없습니다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_EGGCantBattle[] = _("알은\n배틀에 내보낼 수 없습니다{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_CantBeUsedBadge[] = _("새로운 배지를 얻을 때까지\n아직 쓸 수 없습니다");
const u8 gOtherText_NoMoreThreePoke[] = _("참가할 수 있는 포켓몬은\n3마리까지입니다!");
const u8 gOtherText_SendRemovedMailPrompt[] = _("받은 메일을 PC로\n전송하겠습니까?");
const u8 gOtherText_MailWasSent[] = _("메일을 PC에\n전송하였습니다{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_MailboxIsFull[] = _("PC의 메일박스가\n가득 찼습니다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_MailRemovedMessageLost[] = _("메일을 받으면 메시지가 지워집니다\n괜찮겠습니까?");
const u8 gOtherText_MailMustBeRemoved[] = _("메일이 있으면\n도구를 지닐 수 없습니다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_WasGivenToHold[] = _("{STR_VAR_1}에게\n{STR_VAR_2}{K_EULREUL} 지니게 했다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_AlreadyHolding[] = _("{STR_VAR_1}{K_EUNNEUN} 이미\n{STR_VAR_2}{K_EULREUL} 지니고 있습니다\p지니고 있는 도구를\n교환하겠습니까?");
const u8 gOtherText_NotHoldingAnything[] = _("{STR_VAR_1}{K_EUNNEUN} 도구를 아무것도\n지니고 있지 않습니다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_ReceivedTheThingFrom[] = _("{STR_VAR_1}{K_EU}로부터\n{STR_VAR_2}{K_EULREUL} 가져왔습니다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_MailTaken[] = _("포켓몬으로부터 메일을\n받았습니다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_TakenAndReplaced[] = _("{STR_VAR_2}{K_EULREUL} 가져오고\n{STR_VAR_1}{K_EULREUL} 지니게 했습니다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_PokeHoldingItemCantMail[] = _("이미 도구를 지니고 있으므로\n메일을 지니게 할 수 없습니다{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_MailTransferredMailbox[] = _("박스에서 메일을 옮겼습니다{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_BagFullCannotRemoveItem[] = _("가방이 가득 차서 포켓몬의\n도구를 받을 수 없습니다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_LearnedMove[] = _("{STR_VAR_1}{K_EUNNEUN} 새로\n{STR_VAR_2}{K_EULREUL} 배웠다!");
const u8 gOtherText_NotCompatible[] = _("{STR_VAR_1}{K_WAGWA} {STR_VAR_2}{K_EUNNEUN}\n상성이 좋지 않았다!\p{STR_VAR_2}{K_EUNNEUN} 배울 수 없다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_WantsToLearn[] = _("{STR_VAR_1}{K_EUNNEUN} 새로\n{STR_VAR_2}{K_EULREUL} 배우고 싶다...!\p그러나 {STR_VAR_1}{K_EUNNEUN} 기술을 4개\n알고 있으므로 더 이상 배울 수 없다!\p{STR_VAR_2} 대신\n다른 기술을 잊게 하겠습니까?");
const u8 gOtherText_StopTryingTo[] = _("그럼... {STR_VAR_2}{K_EULREUL}\n배우는 것을 포기하겠습니까?");
const u8 gOtherText_DidNotLearnMove2[] = _("{STR_VAR_1}{K_EUNNEUN} {STR_VAR_2}{K_EULREUL}\n결국 배우지 않았다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_WhichMoveToForget2[] = _("어느 기술을 잊게 하겠습니까?{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_ForgetMove123_2[] = _("{PAUSE 32}1, {PAUSE 15}2, {PAUSE 15}... {PAUSE 15}... {PAUSE 15}... {PLAY_SE SE_KON}짠!\p{STR_VAR_1}{K_EUNNEUN} {STR_VAR_2}{K_EULREUL}\n깨끗이 잊었다!\p그리고...!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_AlreadyKnows[] = _("{STR_VAR_1}{K_EUNNEUN} 이미\n{STR_VAR_2}{K_EULREUL} 기억하고 있습니다{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_HPRestoredBy[] = _("{STR_VAR_1}의 체력이\n{STR_VAR_2} 회복되었다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_CuredPoisoning[] = _("{STR_VAR_1}의 독은\n말끔하게 해독됐다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_CuredParalysis[] = _("{STR_VAR_1}의\n몸저림이 풀렸다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_WokeUp[] = _("{STR_VAR_1}{K_EUNNEUN}\n눈을 떴다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_BurnHealed[] = _("{STR_VAR_1}의\n화상이 나았다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_ThawedOut[] = _("{STR_VAR_1}의\n얼었던 몸이 녹았다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_PPRestored[] = _("기술포인트를 회복했다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_RegainedHealth[] = _("{STR_VAR_1}{K_EUNNEUN}\n기력을 회복했다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_BecameHealthy[] = _("{STR_VAR_1}{K_EUNNEUN}\n건강해졌다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_PPIncreased[] = _("{STR_VAR_1}의\n기술포인트가 늘었다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_ElevatedTo[] = _("{STR_VAR_1}{K_EUNNEUN}\n레벨{STR_VAR_2}{K_EU}로 올랐다!");
const u8 gOtherText_WasRaised[] = _("{STR_VAR_1}{K_EUNNEUN} {STR_VAR_2}의\n기초포인트가 올라갔다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_SnapConfusion[] = _("{STR_VAR_1}의\n혼란이 풀렸다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_GotOverLove[] = _("{STR_VAR_1}의\n헤롱헤롱이 풀렸다!{PAUSE_UNTIL_PRESS}");
const u8 OtherText_ChoosePoke[] = _("포켓몬을 선택해 주십시오");
const u8 OtherText_MovePokeTo[] = _("어디로 이동할까?");
const u8 OtherText_TeachWhat[] = _("어느 포켓몬에게 가르칠까?");
const u8 OtherText_UseWhat[] = _("어느 포켓몬에게 사용할까?");
const u8 OtherText_GiveWhat[] = _("어느 포켓몬에게 건네줄까?"); //どのポケモンに もたせますか?
const u8 OtherText_DoWhat[] = _("{STR_VAR_1}{K_EULREUL} 어떻게 할까?");
const u8 OtherText_NothingToCut[] = _("여기서는 쓸 수 없습니다");
const u8 OtherText_CantSurf[] = _("여기서는 쓸 수 없습니다");
const u8 OtherText_AlreadySurfing[] = _("이미 파도타기를 하고 있습니다");
const u8 OtherText_CantUseThatHere[] = _("여기서는 쓸 수 없습니다");
const u8 OtherText_RestoreWhatMove[] = _("어느 기술을 회복하겠습니까?");
const u8 OtherText_BoostPP[] = _("어느 기술의 포인트를 늘릴까?");
const u8 OtherText_DoWhatWithItem[] = _("지닌물건을 어떻게 할까?");
const u8 OtherText_NoPokeForBattle[] = _("대전에 내보낼 포켓몬이 없습니다!");
const u8 OtherText_ChoosePoke2[] = _("맡길 포켓몬을 선택해 주십시오");
const u8 OtherText_NotEnoughHP[] = _("체력이 부족합니다...");
const u8 OtherText_ThreePokeNeeded[] = _("포켓몬 3마리가 필요합니다!");
const u8 OtherText_PokeCantBeSame[] = _("같은 포켓몬이 있습니다!");
const u8 OtherText_NoIdenticalHoldItems[] = _("도구가 같은 포켓몬이 있습니다!");
const u8 OtherText_TeachWhichPoke[] = _("어느 포켓몬에게 가르칠까?");
const u8 gOtherText_Attack[] = _("공격");
const u8 gOtherText_Defense[] = _("방어");
const u8 gOtherText_SpAtk[] = _("특수공격");
const u8 gOtherText_SpDef[] = _("특수방어");
const u8 gOtherText_Speed[] = _("스피드");
const u8 gOtherText_HP[] = _("HP");
const u8 gOtherText_Terminator18[] = _("앞으로");
const u8 gOtherText_OriginalTrainer[] = _("어버이/");
const u8 gOtherText_Type2[] = _("타입/");
const u8 gOtherText_Power2[] = _("위력");
const u8 gOtherText_Accuracy2[] = _("명중");
const u8 gOtherText_Appeal2[] = _("어필");
const u8 gOtherText_Jam2[] = _("방해");
const u8 gOtherText_Status[] = _("상태");
const u8 gOtherText_ExpPoints[] = _("현재 경험치");
const u8 gOtherText_NextLv[] = _("레벨업까지");
const u8 gOtherText_Ribbons00[] = _("현재{CLEAR_TO 0x38}개");

const u8 OtherText_Event[] = _("이벤트");
const u8 OtherText_Switch[] = _("교체");
const u8 OtherText_PokeInfo[] = _("포켓몬 정보");
const u8 OtherText_PokeSkills[] = _("포켓몬 능력");
const u8 OtherText_BattleMoves[] = _("싸울 기술");
const u8 OtherText_ContestMoves[] = _("콘테스트 기술"); // why the l33t 0, that's stupid
const u8 OtherText_Info[] = _("자세히");

const u8 gOtherText_EggLongTime[] = _("이 알은 태어나기까지 상당한\n시간이 걸릴 것 같다");
const u8 gOtherText_EggSomeTime[] = _("무엇이 태어날까? 태어나기까지\n아직 시간이 걸릴 것 같다");
const u8 gOtherText_EggSoon[] = _("가끔 움직이고 있는 것 같다\n태어나기까지 이제 조금 남은 건가?");
const u8 gOtherText_EggAbout[] = _("안에서 소리가 들려온다\n이제 곧 태어날 것 같아!");
const u8 gOtherText_CantForgetHMs[] = _("그건 중요한 기술입니다\n잊게 할 수 없습니다!");
const u8 gOtherText_PlayersBase[] = _("의 비밀기지");
const u8 gOtherText_OkayToDeleteFromRegistry[] = _("{STR_VAR_1}의 등록을\n해제해도 괜찮겠습니까?"); //い の とうろくをｎかいじょ しても よろしい ですか?$
const u8 gOtherText_RegisteredDataDeleted[] = _("등록을 해제했습니다{PAUSE_UNTIL_PRESS}"); //とうろくを かいじょ しました

const u8 gSecretBaseText_NoRegistry[] = _("등록 리스트가 없습니다{PAUSE_UNTIL_PRESS}");
const u8 SecretBaseText_DelRegist[] = _("등록 해제");
const u8 SecretBaseText_Decorate[] = _("굿즈를 꺼낸다");
const u8 SecretBaseText_PutAway[] = _("굿즈를 되돌린다");
const u8 SecretBaseText_Toss[] = _("굿즈를 버린다");
const u8 SecretBaseText_PutOutDecor[] = _("선택한 굿즈를 방으로 꺼냅니다!");
const u8 SecretBaseText_StoreChosenDecor[] = _("선택한 굿즈를 PC로 되돌립니다!");
const u8 SecretBaseText_ThrowAwayDecor[] = _("필요 없어진 굿즈를 버립니다!");
const u8 gSecretBaseText_NoDecors[] = _("굿즈가 없습니다!{PAUSE_UNTIL_PRESS}");
const u8 SecretBaseText_Desk[] = _("책상");
const u8 SecretBaseText_Chair[] = _("의자");
const u8 SecretBaseText_Plant[] = _("화분");
const u8 SecretBaseText_Ornament[] = _("장식품");
const u8 SecretBaseText_Mat[] = _("매트");
const u8 SecretBaseText_Poster[] = _("벽장식");
const u8 SecretBaseText_Doll[] = _("봉제인형");
const u8 SecretBaseText_Cushion[] = _("쿠션");
const u8 gSecretBaseText_GoldRank[] = _("금");
const u8 gSecretBaseText_SilverRank[] = _("은");
const u8 gSecretBaseText_PlaceItHere[] = _("여기에 놓겠습니까?");
const u8 gSecretBaseText_CantBePlacedHere[] = _("여기에 놓을 수 없습니다!");
const u8 gSecretBaseText_CancelDecorating[] = _("놓기를 그만두겠습니까?");
const u8 gSecretBaseText_InUseAlready[] = _("이미 놓여 있습니다!");
const u8 gSecretBaseText_NoMoreDecor[] = _("더는 놓을 수 없습니다\n비밀기지에 놓는 건{STR_VAR_1}개까지입니다");
const u8 gSecretBaseText_NoMoreDecor2[] = _("더는 놓을 수 없습니다\n방에 놓는 건{STR_VAR_1}개까지입니다$여기에 놓을 수 없습니다!\n책상 위 등에 놓아 주십시오!");
const u8 gSecretBaseText_DecorCantPlace[] = _("이 굿즈는\n자신의 방에 놓을 수 없습니다!");
const u8 gSecretBaseText_DecorInUse[] = _("이 굿즈는 놓여 있으므로\n버릴 수 없습니다!");
const u8 gSecretBaseText_WillBeDiscarded[] = _("{STR_VAR_1}{K_IGA} 없어져 버립니다만\n괜찮겠습니까?");
const u8 gSecretBaseText_DecorThrownAway[] = _("굿즈를 버렸습니다!");
const u8 gSecretBaseText_StopPuttingAwayDecor[] = _("되돌리는 것을 그만두겠습니까?");
const u8 gSecretBaseText_NoDecor[] = _("여기에는 굿즈가 없습니다!");
const u8 gSecretBaseText_ReturnDecor[] = _("이 굿즈를 PC로 되돌리겠습니까?");
const u8 gSecretBaseText_DecorReturned[] = _("굿즈를 PC로 되돌렸습니다!");
const u8 gSecretBaseText_NoDecorInUse[] = _("굿즈가 놓여 있지 않습니다!{PAUSE_UNTIL_PRESS}");
const u8 SecretBaseText_Tristan[] = _("원류"); //원문 ヒロミ, 이하 4개의 이름은 정식 명칭이 없어 작명했음을 알림.
const u8 SecretBaseText_Philip[] = _("향리"); //ユウリ
const u8 SecretBaseText_Dennis[] = _("유준"); //ヨシオ
const u8 SecretBaseText_Roberto[] = _("현웅"); //サダハル
const u8 SecretBaseText_TurnOff[] = _("접속을 끊는다");
const u8 SecretBaseText_Decoration[] = _("모양바꾸기");
const u8 SecretBaseText_ItemStorage[] = _("도구 보관소");

const u8 gPCText_Mailbox[] = _("메일박스");
const u8 PCText_DepositItem[] = _("도구를 맡긴다");
const u8 PCText_WithdrawItem[] = _("도구를 가져간다");
const u8 PCText_TossItem[] = _("도구를 버린다");
const u8 PCText_StoreItems[] = _("PC에 도구를\n맡길 수 있습니다");
const u8 PCText_TakeOutItems[] = _("PC에 맡긴 도구를\n가져갈 수 있습니다");
const u8 PCText_ThrowAwayItems[] = _("PC에 있는 도구를\n버릴 수 있습니다");

const u8 gOtherText_NoItems[] = _("아무것도 없습니다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_NoMoreRoom[] = _("더 이상\n가방에 넣을 수 없습니다");
const u8 gOtherText_HowManyToWithdraw[] = _("몇 개 꺼내겠습니까?");
const u8 gOtherText_WithdrewThing[] = _("{STR_VAR_1}{K_EULREUL}\n{STR_VAR_2}개 꺼냈습니다");
const u8 OtherText_Read[] = _("내용을 읽는다");
const u8 gOtherText_MoveToBag[] = _("가방으로 되돌아간다");
const u8 OtherText_Give[] = _("포켓몬에게 건네준다");
const u8 gOtherText_NoMailHere[] = _("메일이 1통도 없습니다{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_WhatWillYouDoMail[] = _("{STR_VAR_1}의\n메일을 어떻게 하겠습니까?");
const u8 gOtherText_MessageWillBeLost[] = _("내용은 사라져 버립니다만\n괜찮겠습니까?");
const u8 gOtherText_BagIsFull[] = _("가방이 가득 찼습니다!{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_MailWasReturned[] = _("내용을 지운 메일을\n가방에 넣었습니다{PAUSE_UNTIL_PRESS}");
const u8 gOtherText_Dad[] = _("아빠");
const u8 gOtherText_Mom[] = _("엄마");
const u8 gOtherText_Wallace[] = _("윤진");
const u8 gOtherText_Steven[] = _("성호");
const u8 gOtherText_Brawly[] = _("철구");
const u8 gOtherText_Winona[] = _("은송");
const u8 gOtherText_Phoebe[] = _("회연");
const u8 gOtherText_Glacia[] = _("미혜");
const u8 gContestText_ContestWinner[] = _("콘테스트 우승자\n");
const u8 gOtherText_Unknown1[] = _("의 ");
const u8 OtherText_Cool[] = _("근사함 ");
const u8 OtherText_Beauty2[] = _("아름다움 ");
const u8 OtherText_Cute[] = _("귀여움 ");
const u8 OtherText_Smart[] = _("슬기로움 ");
const u8 OtherText_Tough[] = _("강인함 ");
const u8 OtherText_NonstopSuperCool[] = _("슈퍼 쿨\n논스톱 ");
const u8 OtherText_Terminator6[] = _("");
const u8 OtherText_GoodLookingPoke[] = _("굿 루킹 포켓몬 ");
const u8 OtherText_Terminator7[] = _("");
const u8 OtherText_MarvelousGreat[] = _("마블러스 원더풀\n그레이트 ");
const u8 OtherText_Terminator8[]= _("");
const u8 OtherText_CenturyLastVenus[]= _("금세기 최고의 비너스\n뷰티 ");
const u8 OtherText_Terminator9[]= _("");
const u8 OtherText_Terminator10[]= _("");
const u8 OtherText_DazzlingSmile[]= _("의 눈부신\n반짝반짝 스마일");
const u8 OtherText_PokeCenterIdol[]= _("포켓몬센터의\n슈퍼 아이돌 ");
const u8 OtherText_Terminator11[]= _("");
const u8 OtherText_LovelyAndSweet[]= _("러블리 스위트 ");
const u8 OtherText_Terminator12[]= _("");
const u8 OtherText_ThePretty[]= _("프리티 ");
const u8 OtherText_WinningPortrait[] = _("의\n새침한 숏");
const u8 OtherText_GiveUsWink[] = _("이쪽 봐줘!\n큐트 포켓몬 ");
const u8 OtherText_Terminator13[] = _("");
const u8 OtherText_SmartnessMaestro[] = _("슬기로운 마에스트로\n와이즈 포켓몬 ");
const u8 OtherText_Terminator14[] = _("");
const u8 OtherText_ChosenPokeAmong[] = _("선택받은 포켓몬...\n포켓몬 중의 포켓몬 ");
const u8 OtherText_Terminator15[] = _("");
const u8 OtherText_TheExcellent[] = _("엑설런트 ");
const u8 OtherText_ItsMomentOfElegance[] = _("의\n우아한 순간");
const u8 OtherText_PowerfullyMuscular[] = _("파워풀 머슬\n허슬 ");
const u8 OtherText_Terminator16[] = _("");
const u8 OtherText_StrongErEst[] = _("스트롱 스트롱거\n스트롱기스트 ");
const u8 OtherText_Terminator17[] = _("");
const u8 OtherText_MightyTough[] = _("터프니스 마이티\n하이퍼 포켓몬 ");
const u8 OtherText_Exclamation[] = _("!");
const u8 OtherText_Petalburg[] = _("등화도시");
const u8 OtherText_Slateport[] = _("잿빛도시");
const u8 OtherText_Littleroot[] = _("미로마을"); // unused contest location?
const u8 OtherText_Lilycove[] = _("해안시티");
const u8 OtherText_Dewford[] = _("무로마을");
const u8 OtherText_Enter[] = _("참가한다");
const u8 OtherText_Info3[] = _("설명을 듣는다");
const u8 OtherText_WhatsAContest[] = _("포켓몬 콘테스트란?");
const u8 OtherText_TypesOfContest[] = _("콘테스트의 종류");
const u8 OtherText_Ranks[] = _("랭크에 대해서");
const u8 OtherText_Judging[] = _("심사위원에 대해서");
const u8 OtherText_CoolContest[] = _("근사함콘테스트");
const u8 OtherText_BeautyContest[] = _("아름다움콘테스트");
const u8 OtherText_CuteContest[] = _("귀여움콘테스트");
const u8 OtherText_SmartContest[] = _("슬기로움콘테스트");
const u8 OtherText_ToughContest[] = _("강인함콘테스트");
const u8 OtherText_Decoration[] = _("모양바꾸기");
const u8 OtherText_PackUp[] = _("이사");
const u8 OtherText_Count[] = _("카운트");
const u8 OtherText_Registry[] = _("등록 리스트");
const u8 OtherText_Information[] = _("등록 설명");
const u8 OtherText_Mach[] = _("마하");
const u8 OtherText_Acro[] = _("더트");
const u8 OtherText_Poison[] = _("독");
const u8 OtherText_Paralysis[] = _("마비");
const u8 OtherText_Sleep[] = _("잠듦");
const u8 OtherText_Burn[] = _("화상");
const u8 OtherText_Frozen[] = _("얼음");
const u8 OtherText_Quit[] = _("그만 읽는다");
const u8 OtherText_SawIt[] = _("봤어요");
const u8 OtherText_NotYet[] = _("볼 거예요");
const u8 OtherText_Yes[] = _("예");
const u8 OtherText_No[] = _("아니오");
const u8 OtherText_Info2[] = _("설명");
const u8 OtherText_SingleBattle[] = _("싱글배틀");
const u8 OtherText_DoubleBattle[] = _("더블배틀");
const u8 OtherText_MultiBattle[] = _("멀티배틀");
const u8 OtherText_MrBriney[] = _("하기");
const u8 OtherText_MakeAChallenge[] = _("도전한다");
const u8 OtherText_ObtainInformation[] = _("설명을 듣는다");
const u8 OtherText_Lv50_2[] = _("레벨50");
const u8 OtherText_Lv100_2[] = _("레벨100");
const u8 OtherText_Zigzagoon[] = _("지그제구리");
const u8 OtherText_Nincada[] = _("토중몬");
const u8 OtherText_Poochyena[] = _("포챠나");
const u8 OtherText_Nincada2[] = _("토중몬");
const u8 OtherText_Lotad[] = _("연꽃몬");
const u8 OtherText_Roselia[] = _("로젤리아");
const u8 OtherText_Shroomish[] = _("버섯꼬");
const u8 OtherText_Nincada3[] = _("토중몬");
const u8 OtherText_Surskit[] = _("비구술");
const u8 OtherText_Treecko[] = _("나무지기");
const u8 OtherText_Torchic[] = _("아차모");
const u8 OtherText_Mudkip[] = _("물짱이");
const u8 OtherText_Seedot[] = _("도토링");
const u8 OtherText_Shroomish2[] = _("버섯꼬");
const u8 OtherText_Spinda[] = _("얼루기");
const u8 OtherText_Shroomish3[] = _("버섯꼬");
const u8 OtherText_Zigzagoon2[] = _("지그제구리");
const u8 OtherText_Wurmple[] = _("개무소");
const u8 OtherText_PokeBall[] = _("몬스터볼");
const u8 OtherText_SuperPotion[] = _("좋은상처약");
const u8 OtherText_SamePrice[] = _("같은 가격");
const u8 OtherText_Yen135[] = _("135원");
const u8 OtherText_Yen155[] = _("155원");
const u8 OtherText_Yen175[] = _("175원");
const u8 OtherText_CostMore[] = _("비싸다");
const u8 OtherText_CostLess[] = _("싸다");
const u8 OtherText_SamePrice2[] = _("같은 가격");
const u8 OtherText_MaleSymbol[] = _("수컷");
const u8 OtherText_FemaleSymbol[] = _("암컷");
const u8 OtherText_Neither[] = _("둘 다 아니다");
const u8 OtherText_Males[] = _("남성");
const u8 OtherText_Females[] = _("여성");
const u8 OtherText_SameNumber[] = _("똑같다");
const u8 OtherText_Male[] = _("남성");
const u8 OtherText_Female[] = _("여성");
const u8 OtherText_ItDepends[] = _("정해져 있지 않다");
const u8 OtherText_Six2[] = _("6대");
const u8 OtherText_Eight2[] = _("8대");
const u8 OtherText_Ten[] = _("10대");
const u8 OtherText_One[] = _("한 명");
const u8 OtherText_Two[] = _("두 명");
const u8 OtherText_Three[] = _("세 명");
const u8 OtherText_Six[] = _("6개");
const u8 OtherText_Seven[] = _("7개");
const u8 OtherText_Eight[] = _("8개");
const u8 OtherText_FreshWater[] = _("맛있는물{CLEAR_TO 0x48}200원");
const u8 OtherText_SodaPop[] = _("미네랄사이다{CLEAR_TO 0x48}300원");
const u8 OtherText_Lemonade[] = _("후르츠밀크{CLEAR_TO 0x48}350원");
const u8 OtherText_HowToRide[] = _("타는 방법");
const u8 OtherText_HowToTurn[] = _("도는 방법");
const u8 OtherText_SandySlopes[] = _("모래 비탈길");
const u8 OtherText_Wheelies[] = _("윌리");
const u8 OtherText_BunnyHops[] = _("다니엘");
const u8 OtherText_Jumping[] = _("점프");
const u8 OtherText_Satisfied[] = _("만족");
const u8 OtherText_Dissatisfied[] = _("불만");
const u8 OtherText_Deepseatooth[] = _("심해의이빨");
const u8 OtherText_Deepseascale[] = _("심해의비늘");
const u8 OtherText_BlueFlute2[] = _("파랑비드로");
const u8 OtherText_YellowFlute2[] = _("노랑비드로");
const u8 OtherText_RedFlute2[] = _("빨강비드로");
const u8 OtherText_WhiteFlute2[] = _("하양비드로");
const u8 OtherText_BlackFlute2[] = _("검정비드로");
const u8 OtherText_GlassChair[] = _("고운 의자");
const u8 OtherText_GlassDesk[] = _("고운 책상");
const u8 OtherText_TreeckoDoll[] = _("나무지기인형    1000");
const u8 OtherText_TorchicDoll[] = _("아차모인형     1000");
const u8 OtherText_MudkipDoll[] = _("물짱이인형     1000");
const u8 OtherText_50Coins[] = _(" 50개   1000원");
const u8 OtherText_500Coins[] = _("500개  10000원");
const u8 OtherText_Excellent[] = _("최고예요");
const u8 OtherText_NotSoHot[] = _("그냥 그래요");
const u8 OtherText_RedShard[] = _("빨강조각");
const u8 OtherText_YellowShard[] = _("노랑조각");
const u8 OtherText_BlueShard[] = _("파랑조각");
const u8 OtherText_GreenShard[] = _("초록조각");
const u8 OtherText_BattleTower[] = _("배틀타워");
const u8 OtherText_Right[] = _("오른쪽");
const u8 OtherText_Left[] = _("왼쪽");
const u8 OtherText_TM32[] = _("기술머신32  1500");
const u8 OtherText_TM29[] = _("기술머신29  3500");
const u8 OtherText_TM35[] = _("기술머신35  4000");
const u8 OtherText_TM24[] = _("기술머신24  4000");
const u8 OtherText_TM13[] = _("기술머신13  4000");
const u8 OtherText_1F_2[] = _("1층");
const u8 OtherText_2F_2[] = _("2층");
const u8 OtherText_3F_2[] = _("3층");
const u8 OtherText_4F_2[] = _("4층");
const u8 OtherText_5F_2[] = _("5층");
const u8 OtherText_Cool2[] = _("근사함");
const u8 OtherText_Beauty3[] = _("아름다움");
const u8 OtherText_Cute2[] = _("귀여움");
const u8 OtherText_Smart2[] = _("슬기로움");
const u8 OtherText_Tough2[] = _("강인함");
const u8 OtherText_Normal[] = _("노말");
const u8 OtherText_Super[] = _("슈퍼");
const u8 OtherText_Hyper[] = _("하이퍼");
const u8 OtherText_Master[] = _("마스터");
const u8 OtherText_Cool3[] = _("근사함");
const u8 OtherText_Beauty4[] = _("아름다움");
const u8 OtherText_Cute3[] = _("귀여움");
const u8 OtherText_Smart3[] = _("슬기로움");
const u8 OtherText_Tough3[] = _("강인함");
const u8 OtherText_Items[] = _("도구");
const u8 OtherText_KeyItems[] = _("중요한 물건");
const u8 OtherText_Balls[] = _("몬스터볼");
const u8 OtherText_TMsHMs[] = _("기술머신");
const u8 OtherText_Berries[] = _("나무열매");

const u8 gPCText_SomeonesPC[] = _("누군가의 PC");
const u8 gPCText_LanettesPC[] = _("보은의 PC");
const u8 gPCText_PlayersPC[] = _("{PLAYER}의 PC");
const u8 gPCText_HallOfFame[] = _("전당등록");
const u8 gPCText_LogOff[] = _("스위치를 끈다");

const u8 gOtherText_99Times[] = _("99회 이상");
const u8 gOtherText_1Minute[] = _("1분 이상");
const u8 gOtherText_Seconds[] = _("초");
const u8 gOtherText_Times[] = _("회$.");
const u8 gOtherText_BigGuy[] = _("오빠");
const u8 gOtherText_BigGirl[] = _("언니");
const u8 gOtherText_Son[] = _("아들");
const u8 gOtherText_Daughter[] = _("딸");
const u8 OtherText_BlueFlute[] = _("파랑비드로");
const u8 OtherText_YellowFlute[] = _("노랑비드로");
const u8 OtherText_RedFlute[] = _("빨강비드로");
const u8 OtherText_WhiteFlute[] = _("하양비드로");
const u8 OtherText_BlackFlute[] = _("검정비드로");
const u8 OtherText_PrettyChair[] = _("고운 의자");
const u8 OtherText_PrettyDesk[] = _("고운 책상");
const u8 OtherText_1F[] = _("1층");
const u8 OtherText_2F[] = _("2층");
const u8 OtherText_3F[] = _("3층");
const u8 OtherText_4F[] = _("4층");
const u8 OtherText_5F[] = _("5층");
const u8 OtherText_6F[] = _("6층");
const u8 OtherText_7F[] = _("7층");
const u8 OtherText_8F[] = _("8층");
const u8 OtherText_9F[] = _("9층");
const u8 OtherText_10F[] = _("10층");
const u8 OtherText_11F[] = _("11층");
const u8 OtherText_B1F[] = _("지하1층");
const u8 OtherText_B2F[] = _("지하2층");
const u8 OtherText_B3F[] = _("지하3층");
const u8 OtherText_B4F[] = _("지하4층");
const u8 OtherText_Rooftop[] = _("옥상");

const u8 gOtherText_NowOn[] = _("현재 플로어");

const u8 gPCText_Cancel[] = _("되돌아간다");

const u8 PCText_ExitBox[] = _("박스를 종료하겠습니까?");
const u8 PCText_WhatYouDo[] = _("이 박스를 어떻게 하겠습니까?");
const u8 PCText_PickATheme[] = _("어느 테마로 하겠습니까?");
const u8 PCText_PickAWallpaper[] = _("어느 벽지로 하겠습니까?");
const u8 PCText_IsSelected[] = _("{K_EULREUL} 어떻게 하겠습니까?");
const u8 PCText_JumpToWhichBox[] = _("어느 박스로 점프하겠습니까?");
const u8 PCText_DepositInWhichBox[] = _("어느 박스에 맡기겠습니까?");
const u8 PCText_WasDeposited[] = _("{K_EULREUL} 맡겼습니다");
const u8 PCText_BoxIsFull[] = _("이 박스는 가득 찼습니다!");
const u8 PCText_ReleasePoke[] = _("정말 놓아주겠습니까?");
const u8 PCText_WasReleased[] = _("{K_EULREUL} 밖에 놓아주었다");
const u8 PCText_ByeBye[] = _("바이바이,  !");
const u8 PCText_MarkPoke[] = _("마킹해 주십시오");
const u8 PCText_LastPoke[] = _("싸울 포켓몬이 없어집니다!");
const u8 PCText_PartyFull[] = _("지닌 포켓몬이 가득합니다!");
const u8 PCText_HoldingPoke[] = _("포켓몬을 쥐고 있습니다!");
const u8 PCText_WhichOneWillTake[] = _("데리고 갈 포켓몬을 선택하십시오!");
const u8 PCText_CantReleaseEgg[] = _("알은 놓아줄 수 없습니다!");
const u8 PCText_ContinueBox[] = _("박스 조작을 계속하겠습니까?");
const u8 PCText_CameBack[] = _("{K_IGA} 되돌아와 버렸다!");
const u8 PCText_Worried[] = _("걱정했었나...");
const u8 PCText_Surprise[] = _("...............!");
const u8 PCText_PleaseRemoveMail[] = _("메일을 제거해 주십시오!");
const u8 PCText_Cancel2[] = _("그만둔다");
const u8 PCText_Deposit[] = _("맡긴다");
const u8 PCText_Withdraw[] = _("데리고 간다");
const u8 PCText_Switch[] = _("교체한다");
const u8 PCText_Move[] = _("잡는다");
const u8 PCText_Place[] = _("여기에 둔다");
const u8 PCText_Summary[] = _("상태를 본다");
const u8 PCText_Release[] = _("놓아준다");
const u8 PCText_Mark[] = _("마킹");
const u8 PCText_Name[] = _("이름");
const u8 PCText_Jump[] = _("점프");
const u8 PCText_Wallpaper[] = _("벽지");
const u8 PCText_Scenery1[] = _("풍경1");
const u8 PCText_Scenery2[] = _("풍경2");
const u8 PCText_Scenery3[] = _("풍경3");
const u8 PCText_Etc[] = _("etc.");
const u8 PCText_Forest[] = _("숲");
const u8 PCText_City[] = _("시티");
const u8 PCText_Desert[] = _("사막");
const u8 PCText_Savanna[] = _("사바나");
const u8 PCText_Crag[] = _("바위산");
const u8 PCText_Volcano[] = _("화산");
const u8 PCText_Snow[] = _("설산");
const u8 PCText_Cave[] = _("동굴");
const u8 PCText_Beach[] = _("바닷가");
const u8 PCText_Seafloor[] = _("해저");
const u8 PCText_River[] = _("강");
const u8 PCText_Sky[] = _("하늘");
const u8 PCText_Polka[] = _("물방울");
const u8 PCText_PokeCenter[] = _("포켓센");
const u8 PCText_Machine[] = _("기계");
const u8 PCText_Plain[] = _("단색");
const u8 PCText_WhatDoYouWant[] = _("무엇을 하겠습니까?");
const u8 PCText_WithdrawPoke[] = _("포켓몬을 데리고 간다");
const u8 PCText_DepositPoke[] = _("포켓몬을 맡긴다");
const u8 PCText_MovePoke[] = _("박스를 정리한다");
const u8 PCText_SeeYa[] = _("종료");
const u8 PCText_MovePokeToParty[] = _("박스에 맡긴 포켓몬을\n지닐 수 있습니다");
const u8 PCText_StorePokeInBox[] = _("지닌 포켓몬을\n박스에 맡길 수 있습니다");
const u8 PCText_OrganizeBoxesParty[] = _("박스에 맡긴 포켓몬이나\n지닌 포켓몬을 정리할 수 있습니다");
const u8 PCText_ReturnToPrevMenu[] = _("한 단계 전의 메뉴로 돌아갑니다");

const u8 gPCText_OnlyOne[] = _("지닌 포켓몬이 1마리밖에 없습니다!");
const u8 gPCText_PartyFull2[] = _("지닌 포켓몬이 가득합니다!");
const u8 gPCText_BOX[] = _("박스");

// pokenav
const u8 PCText_CheckMap[] = _("{CLEAR 0}호연지방의 지도를 봅니다");
const u8 PCText_CheckPoke[] = _("{CLEAR 0}포켓몬을 자세히 조사합니다");
const u8 PCText_CheckTrainer[] = _("{CLEAR 0}트레이너의 정보를 봅니다");
const u8 PCText_CheckRibbons[] = _("{CLEAR 0}손에 넣은 기념리본을 봅니다");
const u8 PCText_PutAwayNav[] = _("{CLEAR 0}포켓내비를 종료합니다");
const u8 PCText_NoRibbonWin[] = _("{CLEAR 0}리본을 가진 포켓몬이 없습니다");
const u8 PCText_NoTrainers[] = _("{CLEAR 0}트레이너가 등록되어 있지 않습니다");
const u8 PCText_CheckParty[] = _("{CLEAR 0}가진 포켓몬을 자세히 조사합니다");
const u8 PCText_CheckPokeAll[] = _("{CLEAR 0}모든 포켓몬을 자세히 조사합니다");
const u8 PCText_ReturnToNav[] = _("{CLEAR 0}포켓내비 메뉴로 돌아갑니다");
const u8 PCText_FindCool[] = _("{CLEAR 0}근사한 포켓몬을 찾습니다");
const u8 PCText_FindBeauty[] = _("{CLEAR 0}아름다운 포켓몬을 찾습니다");
const u8 PCText_FindCute[] = _("{CLEAR 0}귀여운 포켓몬을 찾습니다");
const u8 PCText_FindSmart[] = _("{CLEAR 0}슬기로운 포켓몬을 찾습니다");
const u8 PCText_FindTough[] = _("{CLEAR 0}강인한 포켓몬을 찾습니다");
const u8 PCText_ReturnToCondition[] = _("{CLEAR 0}컨디션 메뉴로 돌아갑니다");

const u8 gOtherText_NumberRegistered[] = _("등록한 수");
const u8 gOtherText_NumberBattles[] = _("대전 횟수");
const u8 gOtherText_Strategy[] = _("{PALETTE 5}작전");
const u8 gOtherText_TrainersPokemon[] = _("{PALETTE 5}지닌 포켓몬");
const u8 gOtherText_SelfIntroduction[] = _("{PALETTE 5}자기소개");
const u8 gOtherText_Nature2[] = _("성격/");
const u8 gOtherText_InParty[] = _("데리고 있음");
const u8 gOtherText_Number[] = _("No. "); // n번째로 출력되도록 수정
const u8 gOtherText_Ribbons[] = _("리본");
const u8 OtherText_MakeProfilePage1[] = _("4개의 단어를 조합해서"); //4つの ことばを くみあわせて
const u8 OtherText_MakeProfilePage2[] = _("프로필을 만들자!"); //プロフィ-ルを つくろう!
const u8 OtherText_MakeMessagePage1[] = _("6개의 단어로 메시지를 만들자!"); //6つの ことばで メッセ-ジを つくろう!
const u8 OtherText_MakeMessagePage2[] = _("7글자의 단어는 1행에 2개까지!"); //7もじの ことばは 1ぎょうに 2つまで!
const u8 OtherText_DescribeFeelingsPage1[] = _("지금의 기분에 딱 맞는"); //いまの きもちに ぴったりあう
const u8 OtherText_DescribeFeelingsPage2[] = _("단어를 찾아보자!"); //ことばを みつけよう!
const u8 OtherText_WithFourPhrases[] = _("4개의 단어로"); //4つの ことばで
const u8 OtherText_CombineNinePhrasesPage1[] = _("9개의 단어를 조합해서"); //9つの ことばを くみあわせて
const u8 OtherText_CombineNinePhrasesPage2[] = _("메시지를 만들자!"); //メッセ-ジを つくろう!
const u8 OtherText_ImproveBardSongPage1[] = _("단어를 1개만 바꿔서"); //ことばを 1つだけ いれかえて
const u8 OtherText_ImproveBardSongPage2[] = _("아저씨의 노래를 좋게 해보자!"); //オヤジのうたを よくして あげよう!
const u8 OtherText_YourProfile[] = _("프로필은"); //プロフィ-ルは
const u8 OtherText_YourFeelingBattle[] = _("대전이 시작될 때의 기분"); //たいせんが はじまるときの きもちは
const u8 OtherText_SetWinMessage[] = _("대전에서 이겼을 때의 인삿말"); //たいせんに かったときの あいさつは
const u8 OtherText_SetLossMessage[] = _("대전에서 졌을 때의 인삿말"); //たいせんに まけたときの あいさつは
const u8 OtherText_TheAnswer[] = _("대답은"); //こたえは
const u8 OtherText_MailMessage[] = _("메일에 적을 내용은"); //メ-ルに のせる メッセ-ジは
const u8 OtherText_MailSalutation[] = _("메모에 적을 인삿말은"); //はがきに のせる あいさつは
const u8 OtherText_NewSong[] = _("새로운 노래는"); //あたらしい うたは
const u8 OtherText_CombineTwoPhrasesPage1[] = _("2개의 단어를 조합해서"); //2つの ことばを くみあわせて
const u8 OtherText_CombineTwoPhrasesPage2[] = _("유행시키고 싶은 말을 만들자!"); //はやらせたい ことばを つくろう!
const u8 OtherText_ConfirmTrendyPage1[] = _("유행시키고 싶은 말은"); //はやらせたい ことばは
const u8 OtherText_ConfirmTrendyPage2[] = _("이 대답으로 하시겠습니까?"); //これで いいですか?
const u8 OtherText_HipsterPage1[] = _("2개의 단어를 조합해서"); //2つの ことばを くみあわせて
const u8 OtherText_HipsterPage2[] = _("좋은 말을 알려주자!"); //いい ことばを おしえてあげよう!

const u8 gOtherText_TextDeletedConfirmPage1[] = _("편집 중인 단어를"); //へんしゅうちゅうの ことばを
const u8 gOtherText_TextDeletedConfirmPage2[] = _("모두 지워도 괜찮겠습니까?"); //ぜんぶ けしても いいですか?
const u8 gOtherText_QuitEditing[] = _("편집을 그만두겠습니까?"); //へんしゅうを やめますか?
const u8 gOtherText_EditedTextNoSavePage1[] = _("편집한 단어는 저장"); //へんしゅうした ことばは ほぞん
const u8 gOtherText_EditedTextNoSavePage2[] = _("되지 않습니다만 괜찮겠습니까?"); //されませんが いいですか?
const u8 gOtherText_EnterAPhraseOrWord[] = _("단어를 넣어 주십시오!"); //なにか ことばを いれてください!
const u8 gOtherText_TextNoDelete[] = _("단어를 모두 지울 수 없습니다!"); //ことばを ぜんぶ けすことは できません!
const u8 gOtherText_OnlyOnePhrase[] = _("바꿀 수 있는 단어는 1개까지입니다!"); //かえられる ことばは 1つ までです!
const u8 gOtherText_OriginalSongRestored[] = _("노래를 원래대로 되돌립니다!"); //うたを もとに もどします!
const u8 gOtherText_TrendyAlready[] = _("그건 이미 유행하고 있습니다!"); //それは もう はやっています!
const u8 gOtherText_CombineTwoPhrases[] = _("2개의 단어를 조합해 주십시오!"); //2つの ことばを くみあわせてください!
const u8 gOtherText_QuitGivingInfo[] = _("말을 알려주지 않겠습니까?"); //ことばを おしえるのを やめますか?
const u8 gOtherText_StopGivingMail[] = _("메일 건네주기를 그만두겠습니까?"); //メ-ルを もたせるのを やめますか?
const u8 gOtherText_Profile[] = _("프로필"); //プロフィ-ル
const u8 gOtherText_AtBattleStart[] = _("대전이 시작되었을 때"); //$たいせんが はじまるとき
const u8 gOtherText_UponWinningBattle[] = _("대전에서 이겼을 때"); //たいせんに かったとき
const u8 gOtherText_UponLosingBattle[] = _("대전에서 졌을 때"); //たいせんに まけたとき

// mauville_man?
const u8 gOtherText_TheBardsSong[] = _("아저씨의 노래");
const u8 gOtherText_WhatsHipHappening[] = _("지금의 유행어");
const u8 gOtherText_Interview[] = _("인터뷰");
const u8 gOtherText_GoodSaying[] = _("좋은 말이지");
const u8 OtherText_SoPretty[] = _(" 아름답단 말이지!");
const u8 OtherText_SoDarling[] = _(" 귀엽단 말이지!");
const u8 OtherText_SoRelaxed[] = _(" 태평하단 말이지!");
const u8 OtherText_SoSunny[] = _(" 따끈하단 말이지!");
const u8 OtherText_SoDesirable[] = _(" 동경하게 돼!");
const u8 OtherText_SoExciting[] = _(" 두근두근하지!");
const u8 OtherText_SoAmusing[] = _(" 재밌단 말이지!");
const u8 OtherText_SoMagical[] = _(" 신기하단 말이지!");

const u8 gOtherText_Is[] = _("{K_EUNNEUN}");
const u8 gOtherText_DontYouAgree[] = _("\n그렇게 생각하지 않아?");

const u8 OtherText_WantVacationNicePlace[] = _("여행 가고 싶은데\n혹시 어디 멋진 곳 알고 있어?");
const u8 OtherText_BoughtCrayonsIsNice[] = _("120색 크레파스 샀지롱-\n부럽지?");
const u8 OtherText_IfWeCouldFloat[] = _("비눗방울을 타고 한번\n날아보고 싶어-");
const u8 OtherText_SandWashesAwayMakeSad[] = _("모래해변 위에 적은 글자는\n금세 사라지니깐 슬퍼-");
const u8 OtherText_WhatsBottomSeaLike[] = _("바다 깊은 곳은 어떨까?\n한 번이라도 좋으니깐 보고 싶어-");
const u8 OtherText_SeeSettingSun[] = _("저녁 노을을 보면\n집에 돌아가고 싶지 않아?");
const u8 OtherText_LyingInGreenGrass[] = _("초록색 잔디 위에서 뒹굴뒹굴하면\n기분 좋지 않아?");
const u8 OtherText_SecretBasesWonderful[] = _("비밀기지는 정말 좋지!\n뭔가 두근거리지 않아?");

const u8 OtherText_PokeLeague[] = _("포켓몬리그");
const u8 OtherText_PokeCenter[] = _("포켓몬센터");

const u8 gOtherText_GetsAPokeBlock[] = _("에게 포켓몬스넥을 주겠습니까?");

const u8 OtherText_Coolness[] = _("근사함");
const u8 OtherText_Beauty[] = _("아름다움");
const u8 OtherText_Cuteness[] = _("귀여움");
const u8 OtherText_Smartness[] = _("슬기로움");
const u8 OtherText_Toughness[] = _("강인함");

const u8 gOtherText_WasEnhanced[] = _("{K_IGA} 올랐다!");
const u8 gOtherText_NothingChanged[] = _("변함이 없다!");
const u8 gOtherText_WontEat[] = _("더 이상 먹지 않는다...");

const u8 gSystemText_SaveFailedBackupCheck[] = _("데이터를 쓸 수 없었습니다\n백업 메모리를 검사합니다...\n잠시 기다려 주십시오\n{COLOR RED}“1분 정도 걸립니다”");
const u8 gSystemText_BackupDamagedGameContinue[] = _("백업 기능이 고장났거나\n수명이 다 되었습니다\n기록은 할 수 없지만\n게임은 즐기실 수 있습니다");
const u8 gSystemText_GameplayEnded[] = _("{COLOR RED}“이 이상 모험을 계속할 수 없습니다\n타이틀 화면으로 돌아갑니다...”");
const u8 gSystemText_CheckCompleteSaveAttempt[] = _("검사가 종료되었습니다!\n다시 한 번 더 리포트를 작성합니다\n잠시 기다려 주십시오");
const u8 gSystemText_SaveCompletedGameEnd[] = _("리포트의 작성이 끝났습니다\n{COLOR RED}“이 이상 모험을 계속할 수 없습니다\n타이틀 화면으로 돌아갑니다...”");
const u8 gSystemText_SaveCompletedPressA[] = _("리포트의 작성이 끝났습니다\n{COLOR RED}“A 버튼을 눌러 주십시오”");

const u8 gOtherText_Ferry[] = _("연락선");
const u8 gOtherText_SecretBase[] = _("비밀기지");
const u8 gOtherText_Hideout[] = _("아지트");

const u8 gSystemText_ResetRTCPrompt[] = _("RTC를 리셋합니다\nA 버튼: 결정  B 버튼: 취소");
const u8 gSystemText_PresentTime[] = _("현재 게임 내 시간");
const u8 gSystemText_PreviousTime[] = _("지난번 게임 내 시간");
const u8 gSystemText_PleaseResetTime[] = _("시간을 재설정해 주십시오");
const u8 gSystemText_ClockResetDataSave[] = _("시간을 재설정했습니다\n리포트의 작성까지 기다려 주십시오");
const u8 gSystemText_SaveCompleted[] = _("리포트를 작성했습니다!");
const u8 gSystemText_SaveFailed[] = _("리포트를 작성하는 데\n실패했습니다...");
const u8 gSystemText_NoSaveFileNoTime[] = _("리포트가 없어서\n시간을 설정할 수 없습니다!");
const u8 gSystemText_ClockAdjustmentUsable[] = _("게임 내 시간 재생 시스템이\n다시 쓸 수 있게 되었습니다!");
const u8 gSystemText_Saving[] = _("포켓몬 리포트를 작성하고 있습니다...\n전원을 끄지 않도록 해주십시오");
